### ISSUE TITLE
feat: Feature to Exclude Urls from NavLink and NavGroup

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/fluentui-blazor#1003]
# 🙋 Feature Request

Currently, we have option to set the URL's on NavLink and NavGroup to MatchAll or MatchPrefix, The Problem with this is, On Some cases we need to have Match as Prefix but we need to exclude couple of urls from it, 

## 🤔 Expected Behavior

The Active Status of NavLink or NavGroup Should applied to Selected NavMenu or NavGroup and Stays there on Urls that same view takes

## 😯 Current Behavior

On my case, I have UserView which does have multiple Urls **/users/** and **/users/{paginationIndex:int}** it is set as MatchPrefix, Therefore Navmenu would respond on both the Urls but on the other hand i have view called UserLogs which has Url of **/users/logs**, in that case if we click on user logs NavLink, the Active Indicator Applies to Both the User and Userlogs view

![image](https://github.com/microsoft/fluentui-blazor/assets/17165402/437d611c-112e-4b98-9577-960314ef4ee7)

## 💁 Possible Solution

i'm recommanding here is Add a Property to NavLink and NavGroup which takes an array of Excluded Urls

And Also, i'm ready to work on fixing this as well by creating a PR

**Comment by vnbaaij** [comment]
We're not planning on adding something like that and I think I also do not want to merge a PR for it. We tried to do our own navigation with the NavMenuTree and failed miserably. From now on we stricly follow the active state of the NavLink.

For the specific example you mention, it just makes more sense to change the href (@page) for one of those pages. The @page url does not have to include '/users/' for it to be shown under the 'Users' menu. Also, 'Exclude Urls' means what? exclude from the menu? Exclude from being selected? It is a bit to vague, I think.
