### ISSUE TITLE
fix: Default foreground colour for is unreadable when using dark luminance level in FluentMessageBar

### ISSUE THREAD

**Issue by euantorano** [microsoft/fluentui-blazor#1005]
# 🐛 Bug Report

When using `StandardLuminance.DarkMode` as the default `BaseLayerLuminance`, the foreground colour used by `FluentMessageBar` is unreadable.

## 💻 Repro or Code Sample

Setting the base luminance:

```csharp
@inject BaseLayerLuminance BaseLayerLuminance

@code {
    protected override async Task OnInitializedAsync()
    {
        await BaseLayerLuminance.WithDefault(StandardLuminance.DarkMode.GetLuminanceValue());

        await base.OnInitializedAsync();
    }
}
```

Then creating a new message bar:

```csharp
@inject IMessageService MessageService

@code {
    protected override async Task OnInitializedAsync()
    {
        await MessageService.ShowMessageBarAsync(opts =>
        {
            opts.Title = "Login Failed";
            opts.Body = "Login failed";
            opts.Intent = MessageIntent.Error;
        });

        await base.OnInitializedAsync();
    }
}
```

## 🤔 Expected Behavior

Foreground text and icon should be readable as it is when the luminance is set to `StandardLuminance.LightMode`:

<img width="1424" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/748913/ffdf12ea-3e0c-4620-a7c6-b7e18c4b985b">

## 😯 Current Behavior

Foreground text and icon are not readable unless highlighted by the user:

<img width="1425" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/748913/ead2c4e1-7707-4a16-bb5b-e83722ad119a">

## 🌍 Your Environment

* OS & Device: Windows (MAUI Hybrid app)
* Browser: WebView2
* .NET and FAST Version: .NET 8.0; Microsoft.FluentUI.AspNetCore.Components 4.0.0

**Comment by vnbaaij** [comment]
Did you so this: https://github.com/microsoft/fluentui-blazor#temporary-workaround-for-mauiwpfwindows-forms-issues?

**Comment by euantorano** [comment]
Yes, I did. I will create a minimal example tomorrow as a repo and link it. On 21 Nov 2023, at 21:17, Vincent Baaij ***@***.***> wrote:﻿
Did you so this: https://github.com/microsoft/fluentui-blazor#temporary-workaround-for-mauiwpfwindows-forms-issues?

**Comment by euantorano** [comment]
Here we go, I've created a minimal example repository: https://github.com/euantorano/exmaple-maui-blazor-hybrid-app

There's also another (minor - doesn't seem to actually affect anything as far as I can tell...) issue in the form of an uncaught error being logged in the developer console for the webview.

**Comment by euantorano** [comment]
Aha, that would make sense thanks! I've just tested the same thing and it solved the problem. I did have the `GlobalState` in place previously (before I started using the `MessageBar`) and removed it when I didn't see any difference using it.
