### ISSUE TITLE
Feature: Enable/Diasable Close button in Dialog

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fluentui-blazor#1006]
# 🙋 Feature Request

Being able to pass in DialogParameters to Enable or Disable the Close Button to force users to fill the dialog.

## 🤔 Expected Behavior

If the Close Button in dialog is disabled to force users to force users to fill in the form displayed in dialog.

## 😯 Current Behavior

You cannot disable the Close Button so the user can always close the form in the dialog without completing it.

## 🔦 Context

The users that visit a page need to give consent before they can work on the page. Currently they can close the dialog that opens after the application requested them to give consent, the application will no longer block them from working on the page.

I want to force them to fill in the consent data and send submit it, before they are able to do any action on page.
I am working on net 8.0 and the newest nugget package 4.0.

## 💻 Examples

Adding a new bool property called CloseActionEnabled that will enable or disable the close button in dialog.

**Comment by dvoituron** [comment]
You should be able to do this using a **Customized dialog box**.
You will find an example here : https://fluentui-blazor.net/Dialog#customizeddialog

**Comment by chigivigi** [comment]
@dvoituron thank you for your help.
I used the example provided to define FluentDialogHeader component and set the ShowDismiss property to false.
