### ISSUE TITLE
fix: Login Loop when Routes rendermode = InteractiveServer

### ISSUE THREAD

**Issue by bao86** [microsoft/fluentui-blazor#1007]
I'm sorry, I'm new to Blazor development.

# 🐛 Bug Report
Login / Register Looping when adding rendermode to <Routes />

![2023-11-22_15-50-45](https://github.com/microsoft/fluentui-blazor/assets/103753661/ec571499-097e-494f-8644-e7a6230ac8bd)

## 💻 Repro or Code Sample

Create new project and change <Routes > in App.razor
![image](https://github.com/microsoft/fluentui-blazor/assets/103753661/b1fb2f8e-b6a3-4fe6-aa7a-11beb3db963c)

## 🔦 Context
**I have to add rendermode because I cannot import JS file**

_in MainLayout.razor.cs_
```
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        GlobalState.SetContainer(container);

        _jsModule = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./Shared/MainLayout.razor.js");

        _mobile = await _jsModule!.InvokeAsync<bool>("isDevice");

        bool _dark = await _jsModule!.InvokeAsync<bool>("isDarkMode");
        GlobalState.SetLuminance(_dark ? StandardLuminance.DarkMode : StandardLuminance.LightMode);

        if (_selectedColorOption != OfficeColor.Default)
            await AccentBaseColor.WithDefault(_selectedColorOption.ToAttributeValue()!.ToSwatch());
    }
}
```
![image](https://github.com/microsoft/fluentui-blazor/assets/103753661/3798e5f1-85cf-469e-a4c4-ab6372a4a974)

**if RenderMode is add, import js is working BUT get Login/Register looping :(**

![image](https://github.com/microsoft/fluentui-blazor/assets/103753661/9d0e3205-59ef-479c-a7cf-a005a375cf50)

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Microsoft Edge, Google Chrome
* .NET 8 - FlutentUI 4

**Comment by vnbaaij** [comment]
I'm sorry, but this issue does not make any sense. You add a rendermode where? Is it looping by itself? Or are you clicking somewhere. The animated gif is nor really helping to make that clear. Please invest more time in describing what the issue is about and not just dump some screens here and expect us to understand. Thanks.

**Comment by bao86** [comment]
> I'm sorry, but this issue does not make any sense. You add a rendermode where? Is it looping by itself? Or are you clicking somewhere. The animated gif is nor really helping to make that clear. Please invest more time in describing what the issue is about and not just dump some screens here and expect us to understand. Thanks.

When I'm clicking on "Register", 'Login" or "Auth required" the page is indefinitely refresh.

![image](https://github.com/microsoft/fluentui-blazor/assets/103753661/6796b0d4-880d-4b09-b395-a7021ebe277d)

![2023-11-22_16-28-54](https://github.com/microsoft/fluentui-blazor/assets/103753661/4b61a7d4-10c4-497f-af73-568312e92cac)

**Comment by vnbaaij** [comment]
You say in the create dialog, you want 'per page/component' interactivity, yet in the code you are adding it to the `Route` component. That is basically saying you get global interactivity. The code generated by the template (ours and the standard one) does not work with the Account pages having InteractiveServer render mode.  You will indeed get into a loop then. They need to stay at SSR.
See also #1002
