### ISSUE TITLE
feat: add support for indeterminate state to FluentCheckbox

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#1012]
# 🙋 Feature Request

Checkboxes support an indeterminate state. Fluent UI should support using it easily.

## 🤔 Expected Behavior

There is an easy-to-use API for working with the indeterminate state on FluentCheckbox.

## 😯 Current Behavior

JavaScript interop is required.

## 💁 Possible Solution

Add a .NET API to FluentCheckbox.

## 🔦 Context

We want to use a checkbox with this state in Aspire dashboard. We could put a checkbox in this state but it required JavaScript interop that isn't ideal. See:
* https://github.com/dotnet/aspire/blob/60bd2b0b5c29ea02507265199070d4dac1fad712/src/Aspire.Dashboard/Components/Pages/Resources.razor.cs#L58-L83
* https://github.com/dotnet/aspire/blob/60bd2b0b5c29ea02507265199070d4dac1fad712/src/Aspire.Dashboard/wwwroot/js/app.js#L196-L200

## 💻 Examples

https://css-tricks.com/indeterminate-checkboxes/

**Comment by dvoituron** [comment]
Hi James,
I can work on this quickly.
I suggest imitating WinForms, by adding a `ThreeState (bool)` property 😁

1. The `Value` property will be nullable `bool?`.
2. A new `ThreeState` property could define whether the user can switch from one state to another.

![ThreeState](https://github.com/microsoft/fluentui-blazor/assets/8350694/2d38f553-5277-4dbc-a774-b666f5bd95a7)

**Comment by dvoituron** [comment]
In the meantime, you don't necessarily have to use JavaScript code, you can simply add an `indeterminate` class to the FluentCheckbox to have this "indeterminate" state.

**Comment by tocsi-hun** [comment]
I am just wondering how it could work with databinding. I mean if it wouldn't follow strictly the HTML way but rather would take a nullable bool as a value and null would mean indeterminate then it would be easy to bind to data. 
Yes i understand it is not the same because having two different states allows you to be checked or unchecked meanwhile indeterminate, but in datawise indeterminate is just null, isn't it?

**Comment by dvoituron** [comment]
My first idea was to change the `Value` property to a nullable Boolean. But this introduces a breaking change: all current FluentCheckboxes have to be modified, and I don't think that's a good thing (maybe in v5?).

One solution is therefore, as WinForms does, to add a `CheckState` property with three states. Indeed, it could be a Nullable boolean in this case. It's probably better for this property.

**Comment by tocsi-hun** [comment]
Ok, it also works. So I just have to bind to the CheckState and that drags the Value with it in case it is not null. 
Thanks.

**Comment by dvoituron** [comment]
Pushed this PR #1022

**Comment by vnbaaij** [comment]
All merged, will be in next release
