### ISSUE TITLE
TreeView Multiselection

### ISSUE THREAD

**Issue by tocsi-hun** [microsoft/fluentui-blazor#1014]
# 🙋 Feature Request
Add multiselect capability to the TreeView component

## 🤔 Expected Behavior

On top of the current behavior:
- ctrl+click or ctrl+enter on a node should add it to (or subtract it from) the list of selected items
- shift+click or shift+enter on a node should add all the nodes to the current selection from the closest selection before the node until the node 
- the list of selected items should be data bindable

## 😯 Current Behavior

A click or enter on a node selects it but removes any other selection

## 🔦 Context

We'd like to use the tree view for some configuration pages. In some of them it is possible to set certain properties for multiple nodes at the same time -> multiple selection.

I considered to use the Telerik controls, but they are slow and the library is too heavy.
I implemented my own TreeView, which works reasonably well. However I am considering to use a control library and seems to be a waste to implement new controls if the ones in the library are almost ok. 

## 💻 Examples

https://demos.telerik.com/blazor-ui/treeview/selection

**Comment by vnbaaij** [comment]
Hi,

Unfortunately, the underlying web component does not support multi-select so this is not something we can add anytime soon. I wiil try to find out if this is on the horizon for the web components.

**Comment by tocsi-hun** [comment]
Ok, understood, thanks for the answer.
