### ISSUE TITLE
redundant padding in FluentMessageBarProvider component

### ISSUE THREAD

**Issue by AdamWyzgol** [microsoft/fluentui-blazor#1017]
# 🐛 Bug Report

FluentMessageBarProvider adds div with 4px padding that is visible when header has background set

## 💻 Repro or Code Sample
Add prepare layout as below:
```@inherits LayoutComponentBase

<FluentToastProvider />
<FluentDialogProvider />
<FluentTooltipProvider />
<FluentMessageBarProvider />

<FluentMainLayout NavMenuTitle="Title">
    <Header><h3>Title</h3><FluentSpacer />  <LoginDisplay /></Header>
    <NavMenuContent>
        <NavMenu />
    </NavMenuContent>

    <Body>
        @Body
    </Body>
</FluentMainLayout>
```

## 🤔 Expected Behavior

header bar is on top of page without space before

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/155729/4629f9c1-2b80-4df7-a73c-f659ac80066c)

## 💁 Possible Solution

remove padding in fluent-messagebar-provider class

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser Microsoft Edge
* .NET 8
* Fluent Blazor 4.0

**Comment by vnbaaij** [comment]
Good catch. We will change/fix that (if possible). 
We do recommend to put the providers at the bottom of your FluentMainLayout (below the body).

**Comment by dvoituron** [comment]
Thanks but I've 4 remarks:

1. Next time, give us an example that works (your example displays nothing).

```xml
@inject IMessageService service

<FluentMessageBarProvider />

<FluentMainLayout NavMenuTitle="Title">
    <Header>Title</Header>
    <Body>
        <FluentButton OnClick="@(e => service.ShowMessageBar("Hello World"))">
            Click
        </FluentButton>
    </Body>
</FluentMainLayout>
```

2. Why do you want to set this bar before the FLuentLayout?
[FluentUI best practives](https://developer.microsoft.com/en-us/fluentui#/controls/web/messagebar) recommends: "A message bar is most commonly found near the top of an app, **underneath the app's main command bar**. For example, the Microsoft Office message bar is positioned beneath the Ribbon, but above the document canvas."

3. In our documentation (see this [Code Setup](https://www.fluentui-blazor.net/CodeSetup#add-component-providers) page), we recommend adding the providers components **at the end** of your MainLayout.razor file. 

3. You can fix your problem adding a `style` attribute.
```xml
<FluentMessageBarProvider style="padding: 0px" />
```

**Comment by AdamWyzgol** [comment]
Ok, I'm new with that components and I missed info that it should be added at the end of layout. At the moment I used 4th option but I will for sure needs to add that components on the end of layout to follow best practice, thanks for hints.

**Comment by kzu** [comment]
I worked around it for all providers anywhere on the site by adding to the app.css:

```css
.fluent-messagebar-provider {
    /* workaround for https://github.com/microsoft/fluentui-blazor/issues/1017 */
    padding-bottom: unset !important;
}
```
