### ISSUE TITLE
CheckBox DropDownList

### ISSUE THREAD

**Issue by grumpykiwi** [microsoft/fluentui-blazor#1021]
Hi

Is there a way to create a drop down list with a list of items that can be selected by Checkbox ?

I am building an asset management system for internal use. I have a search page where the user can specify the category to search. I want to be able to provide a list of pre-determined categories that they can select from. An option for select all would be ideal.

Thanks

Mark

**Comment by dvoituron** [comment]
Talking about list items as checkboxes is talking about multi-selection :-)
I think the best solution would be to use the [FluentAutocomplete](https://localhost:7062/Autocomplete) component.
