### ISSUE TITLE
fix: 'Could not copy the file "wwwroot\service-worker.js" because it was not found' error in new project

### ISSUE THREAD

**Issue by cmsw97** [microsoft/fluentui-blazor#1025]
# 🐛 Bug Report

After creating a project of type "Fluent Blazor WebAssembly Standalone App" in VS and trying to run it, I get the following error:

Could not copy the file "wwwroot\service-worker.js" because it was not found

## 💻 Repro or Code Sample

1. Install Microsoft.FluentUI.AspNetCore.Templates with the following command:
`dotnet new install Microsoft.FluentUI.AspNetCore.Templates::4.0.0`

2. In Visual Studio 2022 create a new project of type "Fluent Blazor WebAssembly Standalone App", with .NET 8.0

3. Leave PWA option unchecked:
   ☒ Configure for HTTPS
   ☐ Progressive Web Application
   ☒ Include sample pages
   ☐ Do not use top-level statements

4. Try to run the project.

## 🤔 Expected Behavior

To be able to run the app without errors

## 😯 Current Behavior

The error appears and the app can't run

![image](https://github.com/microsoft/fluentui-blazor/assets/113032512/a6c44e6e-6e91-4379-8fd2-70987de8e4ae)

## 🌍 Your Environment

Visual Studio 2022 17.8.1
 Microsoft.FluentUI.AspNetCore.Templates 4.0.0

**Comment by vnbaaij** [comment]
This is an error in the 4.0 template. Remove the lines referencing the service worker and it should work.

It is fixed in the next version
