### ISSUE TITLE
Feat: Add Sizing Options in NavMenu/NavMenuTree

### ISSUE THREAD

**Issue by rencendant** [microsoft/fluentui-blazor#1030]
# 🙋 Feature Request

This feature request is all about the ability to choose a size of the NavMenu/NavMenuTree.

## 🤔 Expected Behavior

I want the NavMenuTree/NavMenu to have options when it comes in size. Either **compact** or **default**.

- The design of the **compact** option will likely to be the current size of the NavMenu/NavMenuTree.
- The design of the **default** option will likely to be larger than the compact size. More margin/padding.

## 😯 Current Behavior

The default appearance of the NavMenuTree/NavMenu's Items are like in compact mode. It looks small when it is used on larger monitors/screens.

## 💁 Possible Solution

- Can be implemented by adding **Size** parameter in NavMenu/NavMenuTree then render the whole NavMenu/NavMenuTree and its content depending on the size.

Example: Default Size
```C#
<FluentNavMenuTree @bind-Expanded="@Expanded" 
                   Width="150" 
                   Collapsible="true" 
                   Title="Collapsible demo" 
                   Size="SizingOptions.Default">
</FluentNavMenuTree>
```

Example: Compact Size
```C#
<FluentNavMenuTree @bind-Expanded="@Expanded" 
                   Width="150"
                   Collapsible="true" 
                   Title="Collapsible demo" 
                   Size="SizingOptions.Compact">
</FluentNavMenuTree>
```

- The values of the **Size** parameter can be choosed from an enumerated class called "SizeOptions" 

Example:
```C#
public enum SizeOptions
{
    Default,
    Compact
}
```

## 🔦 Context

No additional information provided.

## 💻 Examples

No additional information provided.

**Comment by vnbaaij** [comment]
Hi,

The current version of the web components does not have a notion of these sizes. The next version will:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/a7bb7269-fc95-472d-93ee-8d1732d8ef2a)

We will work on adding those capabilities once we can start with integrating these v3 web components

**Comment by Narvalex** [comment]
Is there a publicly accessible URL where I can view those new V3 web components?

**Comment by vnbaaij** [comment]
Yes, here you go: https://web-components.fluentui.dev/?path=/docs/concepts-introduction--page

**Comment by vnbaaij** [comment]
The example Iposted literaly uses another component than NavMenu...
