### ISSUE TITLE
rfc: Possiblity of adding some sample demo apps

### ISSUE THREAD

**Issue by malisancube** [microsoft/fluentui-blazor#1031]
# 💬 RFC

## 🔦 Context

- For devs who are new to using blazor, having some demo apps can give best practices on how to layout and put together the components.

## 💻 Examples

Looking at other componet vendors. They include pre-made dashboards, full examples on various layouts for different use-cases. e.g. Social, ecommerce, marketing.

Example here https://preview.keenthemes.com/metronic8/demo1/dashboards/online-courses.html

**Comment by vnbaaij** [comment]
Hi,

We don't have any resources to work on this. The only way I see this happening is through some community contributions.

Also, the topic of dashboards and page layouts is is one where people are very opiniated and will most probably lead to big debates. I'm not sure if I want to be in that space. We have the building blocks and the demo site as a way of showing how to compose a site and pages. I don't think it is our role to say how they should be used.
