### ISSUE TITLE
docs: fix 'Chinese Taipei' in Autocomplete

### ISSUE THREAD

**Issue by ling921** [microsoft/fluentui-blazor#1033]
# 🙋 Documentation Request

`Taipei` is not a country, it is a city of `China`. Please fix the error in document.

![image](https://github.com/microsoft/fluentui-blazor/assets/88094578/fd9f9c4b-4d9a-48b9-93cd-a5595e5d5dfd)

**Comment by ling921** [comment]
`Select a country` should be changed to `Select a country or region`

**Comment by vnbaaij** [comment]
This is a political discussion and we don't do politics here. Closing this.
