### ISSUE TITLE
RZ10012: NavMenu in MainLayout.razor not working / unknown / missing

### ISSUE THREAD

**Issue by woha** [microsoft/fluentui-blazor#1035]
I've created a new project from the template version 4.1.0 with the following CLI command:

dotnet new fluentblazor -n MSFluentUI -int Auto -au Individual -ai false

This results in an MainLayout.razor which is missing the @using directive for the NavMenu:

RZ10012	Found markup element with unexpected name 'NavMenu'. If this is intended to be a component, add a @using directive for its namespace.

The NavMenu component seems to be missing and not being generated.

**Comment by vnbaaij** [comment]
As the project is using rendemode `InteractiveAuto`, the `NavMenu` components  **must** be in the Client project (which it is). I seem to have forgotten to add a `@using` directive to point MainLayout to it. If you add
```
@using FluentBlazorApp.Client.Layout
```
at the top of `MainLayout`, it will work as expected

**Comment by woha** [comment]
Thank you very much Vincent - for solving the issue that quick and for all the great things you're doing here with this project!

Wolfgang
