### ISSUE TITLE
fix: [what is the issue?] in [where is the issue?]

### ISSUE THREAD

**Issue by MrYossu** [microsoft/fluentui-blazor#1039]
# 🐛 Bug Report

Following the demo from .NET Conf 23 by Vincent and Denis where they show how to build a Fluent UI Blazor app from scratch.

I installed the two Nuget packages as they showed, and modified the `MainLayout.razor` and `Counter.razor` files, but when I run, the layout isn't quite right and clicking the button doesn't do anything.

Specifically, if you look at my layout you'll see that there is space around the header, meaning that it does not reach the edge of the window as theirs did. Also, the footer is plain text at the bottom of the left panel, not in a grey panel right across the bottom of the page...

![Screenshot 2023-11-29 142826](https://github.com/microsoft/fluentui-blazor/assets/10185332/08982f5d-91ba-473c-b1cb-69a519d81522)

Here is the full code from `MainLayout.razor`...

```xml
@inherits LayoutComponentBase

<FluentLayout>
  <FluentHeader>Fluent UI Play</FluentHeader>
  <FluentBodyContent>
    <FluentStack Orientation="Orientation.Horizontal" Style="height: 100%">
      <FluentNavMenu Width="250" Title="Navigation">
        <FluentNavLink Href="/" Icon="@(new Icons.Filled.Size12.Home())" Match="NavLinkMatch.All">Home</FluentNavLink>
        <FluentNavLink Href="/Counter" Icon="@(new Icons.Filled.Size16.AddSquare())">Counter</FluentNavLink>
        <FluentNavLink Href="/Weather" Icon="@(new Icons.Filled.Size20.WeatherRainShowersDay())">Weather</FluentNavLink>
      </FluentNavMenu>

      <div class="main-content">
        @Body
      </div>

    </FluentStack>
  </FluentBodyContent>
  <FluentFooter>Hand-crafted by me</FluentFooter>
</FluentLayout>

<div id="blazor-error-ui">
  An unhandled error has occurred.
  <a href="" class="reload">Reload</a>
  <a class="dismiss">🗙</a>
</div>
```

Also, clicking the button doesn't do anything. Here is the code for `Counter.razor`...

```xml
@page "/counter"

<PageTitle>Counter</PageTitle>

<FluentLabel Typo="Typography.PageTitle">Counter</FluentLabel>

<FluentLabel role="status">Current count: @_currentCount</FluentLabel>

<FluentButton Appearance="Appearance.Accent" OnClick="IncrementCount">Increment</FluentButton>

@code {
  private int _currentCount = 0;

  private void IncrementCount() {
    Console.WriteLine($"Counter was {_currentCount}");
    _currentCount++;
  }

}
```

## 🌍 Your Environment

* Windows 11 on a desktop PC
* Visual Studio 2022 Community
* Microsoft Edge
* .NET 8

**Comment by dvoituron** [comment]
Hi,
You have all steps used during this demo, in this [GitHub repo](https://github.com/dvoituron/dotnetconf-2023-fluentui-blazor).
In you case, probably need to add this style in your [app.css](https://github.com/dvoituron/dotnetconf-2023-fluentui-blazor/blob/main/src/DemoFluentUI/wwwroot/app.css) file
```css 
body {
    margin: 0px;
    height: 100vh;
}
```

**Comment by vnbaaij** [comment]
Hi, you can compare your source withwahat we used in the demo at https://github.com/dvoituron/dotnetconf-2023-fluentui-blazor/

If the  counter is not doing anything, you probable are using the new SSR mode. What options did you choose when creating the project?

**Comment by MrYossu** [comment]
@dvoituron and @vnbaaij Thanks for the links. I noticed that `App.razor` just had `<Routes />`, whereas your code used `    <Routes @rendermode="@RenderMode.InteractiveServer" />`.  Changing that got Blazor working.

I don't remember seeing an option for this when I created the project. Where was that?

Adding the CSS fixed most of the layout, but my footer still doesn't look like yours. I guess I can play with the CSS, I was just surprised that what I got out of the box was missing some of what you got - unless you added this CSS and didn't mention it in the demo.

Thanks again, and thanks for such a great library!

**Comment by vnbaaij** [comment]
@MrYossu you started with a blank Blazor template, I assume? If you want to make sure everything is already set up from the start, I would advise you to install our [templates](https://www.nuget.org/packages/Microsoft.FLuentUI.AspNetCore.templates#readme-body-tab) and use those when creating a new project.
We did not use that in our talk because that would lead to a very short demo :)
