### ISSUE TITLE
fix: DataGrid Not Updating properly using statehaschanged

### ISSUE THREAD

**Issue by KrishnaKumar-1409** [microsoft/fluentui-blazor#1042]
# 🐛 Bug Report

WhenEver I update an record Database I will update Grid , Its not updating eventhough StatehasChanged been used.

## 💻 Repro or Code Sample
1. Just Create IQueryable Input for FluentDataGrid and Give as input in Items.
2. Now When U update the IQueryable input ,Its not updating in the DataGrid

## 🤔 Expected Behavior
      When I modify the IQueryable input it should modify in the DataGrid. 

## 😯 Current Behavior
       FluentDataGrid is not updaing the values when using state has changed

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
I tried with this sample code which is basically the first sample on DataGrid page in the demo site with an added button to add persons to the `IQueryable`:
```
<FluentDataGrid Items="@people">
    <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" />
    <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
    <PropertyColumn Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
</FluentDataGrid>

<FluentButton OnClick="AddPerson">Add a person</FluentButton>

@code {
    record Person(int PersonId, string Name, DateOnly BirthDate);

    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9)),
    }.AsQueryable();

    private void AddPerson()
    {
        var random = new Random();
        var newPerson = new Person(random.Next(10000, 20000), "New Person", new DateOnly(random.Next(1900, 2020), random.Next(1, 12), random.Next(1, 28)));
        people = people.Append(newPerson);
    }
}
```
Result:
![DataGridUpdate](https://github.com/microsoft/fluentui-blazor/assets/1761079/1d4de138-cea1-4a15-992b-32d40c70136c)

So I'm guessing it is something in your code. Closing this a you did not provide any code to check or steps to reproduce.
