### ISSUE TITLE
fix: BaseLayerLuminance.WithDefault not working in MainLayout.razor

### ISSUE THREAD

**Issue by woha** [microsoft/fluentui-blazor#1044]
I was following the docs for design tokens and tried to set the BaseLayerLuminance in OnAfterRenderAsync as described in the docs / sample:

```
// If you would like to change the BaseLayerLuminance  value for the whole site, you can use the WithDefault method
await BaseLayerLuminance.WithDefault((float)0.15);

```
Tried the same in Routes.razor, but no luck.

What am I missing or doing wrong here?

**Comment by vnbaaij** [comment]
We can't really tell without some source to look at. Not sure doing this in `Routes.razor` is going to work as there won't by any html elements to act on yet,I think.

**Comment by dvoituron** [comment]
Why not use `FluentDesignSystemProvider` in **App.razor**?
Will it work for you? Of course, by selecting the correct `AccentBaseColor`?

```xml
<FluentDesignSystemProvider AccentBaseColor="#dedbef" BaseLayerLuminance="0.15f">
    <Router AppAssembly="@typeof(App).Assembly">
      ...
    </Router>
</FluentDesignSystemProvider>
```

**Comment by dvoituron** [comment]
@woha We've added this discussion topic #1049, about design... give us your feedback.

**Comment by woha** [comment]
Thank you Denis,

the `FluentDesignSystemProvider` helps but what I was trying to do is changing the light / dark mode programmatically from code.
Saw the new discussion topic - very nice proposal!

**Comment by woha** [comment]
@dvoituron 

I've tried your solution with `FluentDesignSystemProvider` and ran into a problem with icon color in the menu.

Project created with: `dotnet new fluentblazor -n Dashboard -int Server -au Individual -ai false`

First of all, this is how my `Routs.razor` looks:

```
@using Dashboard.Components.Account.Shared
<FluentDesignSystemProvider AccentBaseColor="#dedbef" BaseLayerLuminance="0.15f">
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)">
                <NotAuthorized>
                    <RedirectToLogin/>
                </NotAuthorized>
            </AuthorizeRouteView>
            <FocusOnNavigate RouteData="@routeData" Selector="h1"/>
        </Found>
    </Router>
</FluentDesignSystemProvider>

```
In `NavMenu.razor` I added one additional `FluentNavLink`:

`<FluentNavLink Href="admin" Icon="@(new Icons.Regular.Size24.WindowDevTools())" IconColor="Color.Warning">Administration</FluentNavLink>
`
With `IconColor="Color.Warning"` to indicate some "danger" behind this menu.

The initial page load is fine, but after selecting some menu items, the icon color changes from orange to black:

![2023-12-01_13-55-05](https://github.com/microsoft/fluentui-blazor/assets/17140559/73a6c54f-33c9-45f9-9260-6c5997ecd2c2)

What am I doing wrong?

**Comment by dvoituron** [comment]
What is the code used to display the menu item with this "orange" icon?
For example, in our FluentUI icons, the SVG behind this icon contains a `style="fill: var(--accent-fill-rest);"` to dynamically use the right color.

**Comment by woha** [comment]
I'm using `<FluentNavLink Href="admin" Icon="@(new Icons.Regular.Size24.WindowDevTools())" IconColor="Color.Warning">Administration</FluentNavLink>` as listed above.

So it is `IconColor="Color.Warning"`.

It works initially and after page reload but changes to black as soon as I click on a menu item.

**Comment by dvoituron** [comment]
Let me do the same on my machine
