### ISSUE TITLE
RZ10012 and other errors, but everything compiles.

### ISSUE THREAD

**Issue by darcome** [microsoft/fluentui-blazor#1047]
# 🐛 Bug Report

![image](https://github.com/microsoft/fluentui-blazor/assets/18150093/7e691e8c-d90d-4891-87d8-63eaa80c4491)

As you can see from the above screenshot, I get warnings and errors, but everything compiles correctly. I am on .NET 8 with vs2022 17.8.2 and this is a blazor wasm project.

I have @using Microsoft.FluentUI.AspNetCore.Components inside _Imports.razor and global using Microsoft.FluentUI.AspNetCore.Components; inside GlobalUsings.cs.

However this prevents me to fully try out FluentUI because I get lots and lots of false warnings and errors.

Is there something I can do?

Thanks in advance!

**Comment by dvoituron** [comment]
Often, it's a Visual Studio problem. Can you try to 
1. Close Visual Studio.
2. Delete all `bin`, `obj` and `.vs` folders from your project.
3. Relaunch Visual Studio and recompile the project.
