### ISSUE TITLE
docs: fix Code setup in  3.4.1

### ISSUE THREAD

**Issue by tomokusaba** [microsoft/fluentui-blazor#1053]
# 🙋 Documentation Request
now
![image](https://github.com/microsoft/fluentui-blazor/assets/46523924/54f03172-f68e-4027-8f95-51f186ffbcca)

```
builder.Services.AddFluentUIComponents(options =>
{
    options.HostingModel = {see remark below};
});
```
HostingModel has been removed and should be removed from the documentation as well.

## 💁 Possible Solution
```
builder.Services.AddFluentUIComponents();
```

**Comment by vnbaaij** [comment]
I updated the doc in 83c26c3b1f5c75e3df54f9fc72ac1205c3e5ee1f
