### ISSUE TITLE
fix: NavMenuContent disappear when trying to collapse a FluentNavGroup on iOS Safari latest version and edge in device emulation

### ISSUE THREAD

**Issue by darcome** [microsoft/fluentui-blazor#1054]
# 🐛 Bug Report

NavMenuContent disappear when trying to collapse a FluentNavGroup on iOS Safari latest version and Edge in device emulation

## 💻 Repro or Code Sample

It happens visiting the demo site https://www.fluentui-blazor.net/.

## 🤔 Expected Behavior

The NavMenuContent should stay open and the clicked FluentNavGroup collapse (or expands).

## 😯 Current Behavior

As stated on the title, when clicking or tapping on a FluentNavGroup the NavMenuContent disappears.

## 🌍 Your Environment

* OS & Device: Windows 11, latest Edge and iOS 17.1.2 with latest Safari.

**Comment by vnbaaij** [comment]
Hi, 
The content does not disappear, the menu just goes into it's collapsed view. This is not a bug in the NavMenu but is an implementation detail in the demo environment that we can't change at the moment. 

The `<nav>` element has an `onclick` handler which gets triggered before the `NavMenuGroup`'s `@onclick` method gets triggered. On a mobile device (not iOS specific) this first `onclick` handler collapses the menu which is fine if you select an item that you can navigate to, but not ideal if it is a group. I'll think of a way to change this, but it is going to be a low priority one afaic.
