### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by boukenka** [microsoft/fluentui-blazor#1055]
# 🙋 Feature Request

I expected to find a field-level validation example in the documentation, not only a validation summary example.
I've tried the following to show validation errors. Is this the right method? 
Do you intend to implement the [feat: show validation error below form components like TextField or Checkbox](https://github.com/microsoft/fluentui-blazor/issues/838) ? 

```C#
<EditForm Model="@Data" OnValidSubmit="ValidHandlerAsync">
    <DataAnnotationsValidator />
     <FluentTextField Label="Last name:"
                      Placeholder="Enter your last name"
                      @bind-Value="@Data.LastName" Immediate="true" />
     <ValidationMessage For="@(() => Data.LastName)" />
</EditForm>

public class RegisterUser
{
    [Required(ErrorMessage = "Not empty!")]
    [MinLength(20, ErrorMessage = "Too short!")]
    public string? LastName { get; set; }
}
```

## 🤔 Expected Behavior

I thought the **FluentTextField** component would have methods/parameters dedicated to validation? And the same goes for the other components.

PS : Thank you for the nice video during the .NET Conference 2023.

**Comment by vnbaaij** [comment]
Yes, we still intend to implement the feature you mention. But as said there, it might not appear until we have the v3 web components.

The code you posted already works today, so you can use that. You are using the right method. Might just need a bit more styling.

PS: Thanks. We liked doing the .NET Conf talk. Glad it showed!
