### ISSUE TITLE
,docs: add instructions  to/in [where]

### ISSUE THREAD

**Issue by KyleLJohnson** [microsoft/fluentui-blazor#1056]
# 🙋 Documentation Request

The documentation for adding a dialog component appears to be only on the GitHub site. MS Learn - No. Blazor Fluent-UI demo page - No. 

## 💁 Possible Solution

Add additional needed steps like having to register the component and add the dialogprovider element to the MainLayout.razor.

**Comment by vnbaaij** [comment]
Documentation is here: https://fluentui-blazor.net/DialogService and https://fluentui-blazor.net/Dialog
