### ISSUE TITLE
https://www.blazorfluentui.net/DatePickerPage DatePicker with TimePicker layout broken on mobile

### ISSUE THREAD

**Issue by magom001** [microsoft/fluentui-blazor#1059]
# 🐛 Bug Report

See the screenshot:

<img width="415" alt="Screenshot 2023-12-02 at 9 36 53" src="https://github.com/microsoft/fluentui-blazor/assets/2744275/8572c4a5-a18a-4711-9473-fc367c8248a1">

## 💻 Repro or Code Sample

1. Go to https://www.blazorfluentui.net/DatePickerPage
1. Scroll to **DatePicker with TimePicker**
1. Open the pickers

## 🤔 Expected Behavior

Controls are fully visible and accessible on the screen

## 😯 Current Behavior

DatePicker is off screen

See the screenshot above

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by dvoituron** [comment]
You are not in the correct GitHub project 😊 Our demo website and our library is displayed on this site. https://www.fluentui-blazor.net

**Comment by vnbaaij** [comment]
Also, not in the right project. Although I work on both these projects are completely unrelated.
