### ISSUE TITLE
Adding component providers to MainLayout causes scrollbars on outer viewport.

### ISSUE THREAD

**Issue by StephenOTT** [microsoft/fluentui-blazor#1067]
Following https://www.fluentui-blazor.net/CodeSetup#add-component-providers using the wasm template, the providers cause scroll bars appear in the overall viewport.

You end up having to add the providers into a nested space such as within the FluentStack within the MainLayout.razor file for the scrollbars to go away.

**Comment by StephenOTT** [comment]
Looking at demo we can see it in the FluentBodyContent:

https://github.com/microsoft/fluentui-blazor/blob/c9ad2c4e32d99d503a95fa817d1d44b57dffa441/examples/Demo/Shared/Shared/DemoMainLayout.razor#L76C1-L76C1

should the readme be updated?

**Comment by vnbaaij** [comment]
Adding a line to the Code Setup page: 
> **note:** If you get scrollbars in your application, move the providers up in the page elements hierarchy, for example into the FluentBodyContent component.
