### ISSUE TITLE
fix: Style not applied to FluentPaginator

### ISSUE THREAD

**Issue by SirDester** [microsoft/fluentui-blazor#1070]
# 🐛 Bug Report

The Style attribute is not applied to the markup of the FluentPaginator

## 💻 Repro or Code Sample

Add a FluentPaginator to the page and set the Style attribute (derived from FluentComponentBase)
`<FluentPaginator State="@State" Style="width: 100%" />`

## 🤔 Expected Behavior

The Style attribute is applied to the `<div class="paginator">` container

## 😯 Current Behavior

The Style attribute derived from FluentComponentBase is not applied to the component

## 💁 Possible Solution

Change the main div container to include the style
`<div class="paginator" style="@Style">`

## 🔦 Context

I was trying to apply a custom style to the component but nothing happened

## 🌍 Your Environment
Fluent UI Blazor version 4.1.1

**Comment by vnbaaij** [comment]
Fixed in next version with PR #1077 1077
