### ISSUE TITLE
fix: Radio buttons not unchecking in nested elements within FluentRadioGroup

### ISSUE THREAD

**Issue by MarkMpn** [microsoft/fluentui-blazor#1071]
# 🐛 Bug Report

If a `FluentRadio` is nested within another container within a `FluentRadioGroup`, the selecting one of the radio buttons does not uncheck the previously selected radio button

## 💻 Repro or Code Sample

```razor
<FluentRadioGroup @bind-Value="SelectedChar">
    <div>
        <h1>Digits</h1>
        <FluentRadio Value="@("1")">1</FluentRadio>
        <FluentRadio Value="@("2")">2</FluentRadio>
    </div>
    <div>
        <h1>Alpha</h1>
        <FluentRadio Value="@("A")">A</FluentRadio>
        <FluentRadio Value="@("B")">B</FluentRadio>
    </div>
</FluentRadioGroup>

@code {
  private string SelectedChar { get; set; }
}
```

## 🤔 Expected Behavior

Only one of the radio buttons should show as selected at once.

![image](https://github.com/microsoft/fluentui-blazor/assets/31017244/b74de432-9d1d-40cc-ba5b-e7564ad1ff57)

## 😯 Current Behavior

Each radio button stays checked even after selecting another option.

![image](https://github.com/microsoft/fluentui-blazor/assets/31017244/00a1b84d-3b47-44f7-ae70-602449aeb4ae)

## 🔦 Context

I have a large list of items I want to show as radio buttons. To make the list more readable and add more context to each one I want to split them up visually into groups but still only allow the user to select one.

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser: Google Chrome
* .NET and FAST Version: Microsoft.FluentUI.AspNetCore.Components 4.0.0 on .NET 8

**Comment by dvoituron** [comment]
`FluentRadio` must be used directly under the `FluentRadioGroup`.
You cannot group them. This is the way Web Components work by design

```xml
<FluentRadioGroup @bind-Value="SelectedChar">
    <FluentRadio Value="1">A</FluentRadio>
    <FluentRadio Value="2">B</FluentRadio>
    <FluentRadio Value="3">C</FluentRadio>
    <FluentRadio Value="4">D</FluentRadio>
</FluentRadioGroup>
```

One solution would be to manage this manually (yourself) or to use a `FluentListbox` that accepts the addition of subtitles, for example.
