### ISSUE TITLE
fix: Clipboard button icon color in the demo website.

### ISSUE THREAD

**Issue by p6laris** [microsoft/fluentui-blazor#1081]
# 🙋 Feature Request
The clipboard icon appears black in dark mode, and when switching the website mode to light, the color state remains unchanged unless the cache is cleared.

## 🤔 Expected Behavior
The website should use accent variant or white color in dark mode and when it switched to light mode the color state should also change to without clearing the cache.

## 😯 Current Behavior
The website use dark icon clipboard color in dark mode and won't change when the website mode changed to white.

## 💁 Possible Solution
N/A

## 🔦 Context
I want to the clipboard icon has a different color in the existing theme mode color in the website.

## 💻 Examples
![image](https://github.com/microsoft/fluentui-blazor/assets/71460146/11c292aa-a110-42b4-8cee-896263c2df77)
![image](https://github.com/microsoft/fluentui-blazor/assets/71460146/6a851fbc-7e58-49f5-b561-32d9f2c3efe8)

**Comment by vnbaaij** [comment]
Replacing the icon with a 'Copy' text. The highlightjs pluging used for this functionality can not respond well to theme changes so I replacedit with our own copy function. It can be seen already at https://preview.fluentui-blazor.net/. Will be rolled out to www site with next release
