### ISSUE TITLE
fix: wrong values of StandardLuminance, or misleading documentation

### ISSUE THREAD

**Issue by MisterGoodcat** [microsoft/fluentui-blazor#1086]
# 🐛 Bug Report

In the documentation on [design tokens](https://www.fluentui-blazor.net/DesignTokens#light-and-dark-mode), there's a statement on light and dark mode:

> `BaseLayerLuminance`: Set to `StandardLuminance.DarkMode` to switch into dark mode.
> This is a decimal value, and the LightMode and DarkMode constants represent the standard points for light and dark mode.

But if you try to take this literally by:

`BaseLayerLuminance="(float?)StandardLuminance.LightMode"`

What you end up with is dark(-ish) mode because these aren't actually constants but enum values, with numeric casts for `LightMode` of 0 and for `DarkMode` of 1 😄.

## 🤔 Expected Behavior

I'm not sure. It could just be misleading documentation, as what is described only is correct for use in code. But how are we then supposed to set the luminance per component without knowing the actual values by heart, as it is done later on [in the above linked documentation](https://www.fluentui-blazor.net/DesignTokens#using-design-tokens-as-components)?

> `<BaseLayerLuminance Value="(float?)0.15">`

**Comment by vnbaaij** [comment]
You need to use the `GetLuminanceValue` extension method on the enum to get the correct float value. We'll add a note to the documentation.
