### ISSUE TITLE
fix: CurrentSelected in FluentTreeView

### ISSUE THREAD

**Issue by tlmii** [microsoft/fluentui-blazor#1087]
# 🐛 Bug Report

The `CurrentSelected` parameter on `FluentTreeView` doesn't appear to be being used correctly to get the value into the underlying `fluent-tree`. I'm not sure how it _can_ work, but I'm fairly confident that it does not currently work correctly.

The docs say
> Gets or sets the currently selected tree item

But this line:

https://github.com/microsoft/fluentui-blazor/blob/e31a8b2d11b3c75e5d9f299402e9f67e73b194e8/src/Core/Components/TreeView/FluentTreeView.razor#L8

Appears to try to set a `currentselected` attribute on the `fluent-tree` element, but there does not appear to be any such attribute. There _is_ a field with that name: https://github.com/microsoft/fast/blob/2ea80697bc3a5193e6123fb08ac3be2a76571aeb/packages/web-components/fast-foundation/src/tree-view/tree-view.ts#L39C1-L40C59

but it is an observable, not an attribute.

Beyond that, what's being set there is an ElementReference, not an attribute value, so it gets serialized effectively with a .ToString() call and you end up with this in your DOM:

```html
<fluent-tree-view currentselected="Microsoft.AspNetCore.Components.ElementReference">
```

Other than this part of the layout, it doesn't appear the value of CurrentSelected is used anywhere in the code for the component. 

## 💻 Repro or Code Sample

You can see this generally by using browser devtools on the demo site: https://www.fluentui-blazor.net/TreeView or by looking at the repro in https://github.com/dotnet/aspire/issues/1262

## 🤔 Expected Behavior

CurrentSelected is either get-only (if that's all that's possible) and doesn't try to set the currentselected attribute, OR setting it actually changes the selection in the underlying component 

## 😯 Current Behavior

Invalid attribute values are set on the underlying component and changing the value of the parameter does not impact the rendering of the tree.

## 💁 Possible Solution

Since `currentSelected` is only a field on the tree, it'd seem like you might have to use JS to actually set it, which may make some of the orchestration complicated (you'd need to make sure rendering had already occurred before trying to call JS).

For _our particular use case_ we're really only trying to set it to null (we use the InitiallySelected and other parts of the tree items to set actual values).  So maybe adding a clear selection could be a small workaround too. But it'd be a hack more than a true fix.

## 🔦 Context

This came out of the investigation of https://github.com/dotnet/aspire/issues/1262 where selection isn't being cleared when we set the value of CurrentSelected to null (via a bound field).

**Comment by vnbaaij** [comment]
I'm removing 
https://github.com/microsoft/fluentui-blazor/blob/e31a8b2d11b3c75e5d9f299402e9f67e73b194e8/src/Core/Components/TreeView/FluentTreeView.razor#L8
from the component code. This is one of those things where we do not want to interfere in what the web component is doing. Also, the fact it is not and attribute and we are sending it incorrect data does not help.

The `CurrentSelected` parameter on our side is only used to be set from the custom event handler that is fired when you click/select a tree item.

**Comment by tlmii** [comment]
@vnbaaij Should probably update the doc comments to say that it is really only a get not a set now?
