### ISSUE TITLE
Issue With FluentNumberField

### ISSUE THREAD

**Issue by grumpykiwi** [microsoft/fluentui-blazor#1089]
I have an issue with the FluentNumberField when using the arrow keys to step a number to an allowed value. On submit, the form insists the number is invalid and gives me the error message "Please enter a valid value"

```
<FluentNumberField @bind-Value="@EditTimeModel.TimeValue"
						Label="Time (% of Hour)"
						Required="true" 
						Style="width: 81%;"
						Max="24.0"
						Min="0.25"
						Step="0.25"
						HideStep="false">
<FluentIcon Icon="Icons.Regular.Size20.TimePicker" Color="Color.Accent" Slot="end" />
</FluentNumberField>
```

If I submit a value of 8.5 it fails. If I step to a whole number it works.

**Comment by vnbaaij** [comment]
Mark,

I will take another look at this later. 

Also, I would strongly recommend you to not use a number input for anything other than a simple up/down integer input. Browsers are notoriously bad in supporting this type of input. It's not just me saying that. See also https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/ and lots of other references.

**Comment by vnbaaij** [comment]
Pattern is being supported and set on the input element created by the web component. Unfortunately the inputmode is not set
