### ISSUE TITLE
feat: add inline editor to/in components

### ISSUE THREAD

**Issue by khoughton-Landmark** [microsoft/fluentui-blazor#1091]
# 🙋 Feature Request

When designing forms, it becomes cumbersome to have different forms for read and edit. To solve this in a nice way, other component libraries have an "Inline Editor" where it displays plain text with a dashed underline in "normal" mode, and when clicked, it turns into an editable field.

## 💁 Possible Solution

Create something like this:
```
<InPlaceEditor>
  <EditorComponent>
   <TextEdit>
  </TextEdit>
 </EditorComponent>
</InPlaceEditor>
```

## 🔦 Context

Re-use a "display" type form for also an "edit" type form

Without this, I am forced to use only a different component vendor's components

## 💻 Examples

https://blazor.syncfusion.com/demos/in-place-editor/overview?_gl=1*z0h78e*_ga*MTQxMjY3NTUxNS4xNjk2MDIxOTA0*_ga_41J4HFMX1J*MTcwMjA3NTA4OC4xMy4wLjE3MDIwNzUwODguMC4wLjA.*_ga_R3Q3BGFFC9*MTcwMjA3NTA4OC4xMi4wLjE3MDIwNzUwODguNjAuMC4w&_ga=2.218255002.2029182927.1702075088-1412675515.1696021904

**Comment by vnbaaij** [comment]
This is not something we are planning to develop. The Fluent design (which we adhere to) does not describe or support such a way of handeling display /editing of information.
