### ISSUE TITLE
docs: add setup for default theme to Theming

### ISSUE THREAD

**Issue by magom001** [microsoft/fluentui-blazor#1092]
# 🙋 Documentation Request

After reading through all related documentation, I still have absolutely no understanding what steps are required to
add a default theme to a blazor wasm app.

I need to set dark mode to be the default.

Can someone please provide an example or a code snippet / required steps to achieve this.

**Comment by vnbaaij** [comment]
The demo site has that functionality. The source code is part of this repo (in the examples folder). It's a bit big but complete.
Another example is shown in the video we did for .NET Conf this year: https://youtu.be/a0xOqNemRoY?si=V0IC8CbLHMxgLcd4
Source for that example is available here:  https://github.com/dvoituron/dotnetconf-2023-fluentui-blazor?tab=readme-ov-file
The Readme shows the exact branch the theme addition is done in.

**Comment by dvoituron** [comment]
And in some days, you could use a new component to simplify the "global" Theme management.
See this discussion: #1049

Example:
```xml
<FluentDesignTheme Mode="Dark" OfficeColor="Word" />
```
