### ISSUE TITLE
Server-side FluentTreeView data binding

### ISSUE THREAD

**Issue by Myrmex** [microsoft/fluentui-blazor#1094]
# 🐛 Bug Report

Not sure if this is a bug or I am just using the component in a wrong way, but I found no documentation about my scenario. When trying to expand a node, it looks like the tree gets expanded but immediately after it is collapsed again. 

## 💻 Repro or Code Sample

This is my mock node class:

```cs
public class MockNode
{
    public MockNode(string name)
    {
        Name = name;
    }

    public string Name { get; }
    public MockNode? Parent { get; set; }
    public List<MockNode> Children { get; set; } = [];
    public bool IsExpanded { get; set; }

    public void AddChild(MockNode child)
    {
        child.Parent = this;
        Children.Add(child);
    }
}
```

I create a tree with this mock service:

```cs
internal static class MockTreeBuilder
{
    public static MockNode Build()
    {
        MockNode root = new("1.1");
        root.AddChild(new MockNode("2.1"));
        root.AddChild(new MockNode("2.2"));
        root.Children[0].AddChild(new MockNode("3.1"));
        return root;
    }
}
```

I then create a `MockNodeItem` component to represent a single tree node:

```cs
@code {
    [Parameter]
    public MockNode? Node { get; set; }

    private void ToggleExpandCollapse()
    {
        if (Node != null)
            Node.IsExpanded = !Node.IsExpanded;
    }
}

@if (Node != null)
{
    <FluentTreeItem Text="@(Node.Name)"
        Expanded="@Node.IsExpanded"
        OnClick="ToggleExpandCollapse">
        @foreach (var child in Node.Children)
        {
            <MockNodeItem Node="child" />
        }
    </FluentTreeItem>
}
```

Now, I use it with a `FluentTreeView`:

```cs
@using FluentRepro.Services
@rendermode InteractiveServer

<FluentTreeView Data="@root" @bind-CurrentSelected=currentSelected OnExpandedChange="HandleOnExpandedChanged">
    <MockNodeItem Node="root" />
</FluentTreeView>

<p>Current selected tree item is @currentSelected?.Text</p>
<p>Most recently expanded/collapsed tree item is @currentAffected?.Text</p>

@code {
    private MockNode root = MockTreeBuilder.Build();

    // https://www.fluentui-blazor.net/TreeView#withdatabinding
    FluentTreeItem? currentSelected;
    FluentTreeItem? currentAffected;
    private void HandleOnExpandedChanged(FluentTreeItem item)
    {
        currentAffected = item;
    }
}
```

## 🤔 Expected Behavior

The tree expands on click.

## 😯 Current Behavior

When I try to expand any node, it looks like it gets expanded but immediately after it is collapsed again. If I remove the `OnExpandedChange` handler, I can expand the first children, but not the child of the child. So all this points to an issue with server model update and rendering on response.

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Microsoft Edge, Google Chrome
* .NET 8.0, FluenUI test app created with FluentUI Blazor App template

**Comment by vnbaaij** [comment]
Hi,

The 🎄View (sorry, it's the season for it) doesn't support/is not designed to have binding in such a way. The Data parameter can be used to associate some piece of information to any Fluent component but has no relation with the tree's internal information structure. 
If you want the items to be added programmatically that is certainly possible. Just have a for loop (and nested loops) inside the FluentTreeView that adds the FluentTreeItems. An example of that can be seen here in Aspire: https://github.com/dotnet/aspire/blob/main/src%2FAspire.Dashboard%2FComponents%2FPages%2FMetrics.razor#L32

**Comment by Myrmex** [comment]
Thank you, this makes things clearer! Yet, as it seems from the quoted example, this implies that it is not possible to use recursion: so, if I understand correctly, unless I do know in advance my max depth level, I cannot use this component.
