### ISSUE TITLE
fix: Margin in FluentNavMenu not respecting value

### ISSUE THREAD

**Issue by calloncampbell** [microsoft/fluentui-blazor#1095]
# 🐛 Bug Report

FluentNavMenu Margin property is not respecting the value.

## 💻 Repro or Code Sample

1. Create new project with FluentUI and use sample pages.
2. Then set the Margin="0"

``` html
<nav>
    <FluentNavMenu Width="250" Collapsible="true" Title="Custom navigation menu" Margin="0">
        <FluentNavLink Margin="0"  Href="/" Match="NavLinkMatch.All" Icon="@Icon.FromImageUrl("/images/home.svg")" IconColor="Color.Accent">Home</FluentNavLink>
        <FluentNavGroup Margin="0"  Title="Examples">
            <FluentNavLink Href="fetchdata" Icon="@Icon.FromImageUrl("/images/fetchdata.svg")" IconColor="Color.Accent">Fetch data</FluentNavLink>
            <FluentNavLink Href="counter" Icon="@Icon.FromImageUrl("/images/counter.svg")" IconColor="Color.Accent">Counter</FluentNavLink>
            <FluentNavLink Href="weather" Icon="@Icon.FromImageUrl("/images/weather.svg")" IconColor="Color.Accent">Weather</FluentNavLink>
            </FluentNavGroup>
        <FluentNavLink Href="counter" Icon="@Icon.FromImageUrl("/images/counter.svg")" IconColor="Color.Accent">Counter</FluentNavLink>
        <FluentNavLink Href="weather" Icon="@Icon.FromImageUrl("/images/weather.svg")" IconColor="Color.Accent">Weather</FluentNavLink>
    </FluentNavMenu>
</nav>
```

## 🤔 Expected Behavior

I don't want to see the extra whitespace between each Nav item.

## 😯 Current Behavior

I see the margin between each Nav item (orange area).

![image](https://github.com/microsoft/fluentui-blazor/assets/4095080/6b0dd93a-f0d8-4b2b-9bc4-b6fefadee50a)

**Comment by vnbaaij** [comment]
Hi, 

The `Margin` parameter is only supported on the `FluentNavMenu` component itself, not on the `FluentNavGroup` an/or `FluentNavLink`. It controls the margin surrounding the whole menu.
You can offset a group from the rest of the items at the same level by using the `Gap` parameter (i.e Gap="20px") on the `FluentNavGroup` 

We do not have a specific parameter or support for removing all spacing between the items but it can be done with a small piece of CSS:
```css
<style>
    .fluent-nav-item {
        margin: 0 !important;
    }
</style>
```
