### ISSUE TITLE
FluentDataGrid Inconsistent Behaviour

### ISSUE THREAD

**Issue by Serge-N** [microsoft/fluentui-blazor#1097]
# 🐛 Bug Report

Fluent Data Grid renders differently when the page is refreshed. 

## 💻 Repro or Code Sample
Code taken from Manual Grid [Example](https://www.fluentui-blazor.net/DataGrid) : 
`
<FluentDataGrid id="manualGrid" GenerateHeader=GenerateHeaderOption.None GridTemplateColumns="1fr 1fr" TGridItem="string" role="grid">
    <FluentDataGridRow RowType="DataGridRowType.Header" >
        <FluentDataGridCell GridColumn=1 CellType="DataGridCellType.ColumnHeader">Column 1</FluentDataGridCell>
        <FluentDataGridCell GridColumn=2 CellType="DataGridCellType.ColumnHeader">Column 2</FluentDataGridCell>
    </FluentDataGridRow>
    <FluentDataGridRow>
        <FluentDataGridCell GridColumn=1 >1.1</FluentDataGridCell>
        <FluentDataGridCell GridColumn=2>1.2</FluentDataGridCell>
    </FluentDataGridRow>
    <FluentDataGridRow>
        <FluentDataGridCell GridColumn=1>2.1</FluentDataGridCell>
        <FluentDataGridCell GridColumn=2> 2.2</FluentDataGridCell>
    </FluentDataGridRow>
</FluentDataGrid>
`
## 🤔 Expected Behavior

A view like this
<img width="512" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/51508252/1b14d961-2fab-49a9-b720-92b9dbd63f27">

This is supposed to be the same, whether a user navigates to the page or refreshes the same page.

## 😯 Current Behavior
Here is what I get after refreshing 
<img width="521" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/51508252/655013a0-f6f7-4a67-ac82-ab1f05f2c4ff">

## 💁 Possible Solution

Fix how _manualGrid is rendered when refreshing, this should be the same as when a user is navigating to the page that contains this component.

## 🔦 Context

This issue makes the library unusable given that the Data Grid is a frequently used component. Although Quick Grid can be used, it takes away from the benefits of using this UI library in the first place.

## 🌍 Your Environment
* OS & Device:  Windows 11
* Browser: Microsoft Edge, Google Chrome, Mozilla FireFox
* .NET and FAST Version .NET 8.0 and Microsoft.FluentUI.AspNetCore.Components Version 4.1.1

**Comment by vnbaaij** [comment]
Can't repo this. The example you point to does not exhibit the behavior you observe. Pasting it in a template based site also works as expected. Please supply a repository we can observe the behavior in.

**Comment by pk9r327** [comment]
@vnbaaij 
I have created a repository for this issue at https://github.com/pk9r327/fluent-data-grid-inconsistent-1097

This only happens with static SSR, and maybe this is related to NavMenu.

**Comment by vnbaaij** [comment]
This does not have anything to do with the `NavMenu` . I got it to work consistently in SSR with the following code (for `Grid.razor`):
```
@page "/grid"
@attribute [StreamRendering]

<h3>Grid</h3>

@if (items != null)
{
    <FluentDataGrid Id="manualGrid" Items="@items" GridTemplateColumns="1fr 1fr" role="grid">
        <PropertyColumn Title="Column 1" Property="@(c => c!.Item1)" Sortable="true" Align=Align.Start />
        <PropertyColumn Title="Column 2" Property="@(c => c!.Item2)" Sortable="true" Align=Align.Start />
    </FluentDataGrid>
}
@code {
    private IQueryable<(string, string)>? items;

    protected override async Task OnInitializedAsync()
    {
        // This is needed to make it work consistently
        await Task.Delay(1);

        items = Enumerable.Range(1, 10).Select(index => ($"Item {index}A", $"Item {index}B")).AsQueryable();
    }
}
```
Could not get it to work with the manual grid. But as that will hardly ever be used **and** this only happens in SSR mode, I'm not going to pursue finding a solution for this. Closing this with the provided code here as a 'workaround'

**Comment by onerdy** [comment]
@vnbaaij
I am having this same issue although I see it on initial page load and not just refresh.  Your workaround does solve the problem in your example.  However, the workaround does not seem to be compatible with the EmptyContent parameter of FluentDataGrid (because the grid itself will never be displayed if items are null and therefore EmptyContent will never be true).  From a UI perspective, I think it would look nicer to show a loading spinner inside the empty shell of the grid rather than having a loading spinner by itself.

If I am understanding this correctly, it means the EmptyContent parameter is not usable with SSR at all right now due to this bug.  Can you think of another way to work around the issue using EmptyContent with SSR?  If not, perhaps reconsider finding a solution.

**Comment by vnbaaij** [comment]
@onerdy the FluentDataGrid is **not** designed from the ground up to be SSR compatible. Using it in that mode works mostly (i.e displaying data but sort nor working, etc) but you can't do everything. 

For `EmptyContent` we are doing conditional rendering that relies on interactivity (if you are interested, it has to do with defered rendering of the columns). So yes, the EmptyContent parameter is not usable with SSR and this is not likely going to change as that would mean a lot of rewriting of code. I don't have a workaround for that in mind. Will take a look on how it could be done when time permits.

**Comment by onerdy** [comment]
@vnbaaij Thanks for the quick reply.  Cheers!
