### ISSUE TITLE
Fluent Blazor Web App - Custom environment/appsettings

### ISSUE THREAD

**Issue by AlexKidd29** [microsoft/fluentui-blazor#1102]
Hello, 

From template "Fluent Blazor Web App" (SSR)
Using Microsoft.FluentUI.AspNetCore.Components - 4.1.1

For my use case, I need to declare one appsettings per target environment with custom name like TEST/PROD.
I obtain a 404 Not Found on CSS resources.

Working => Development
appsettings.Development.json
launchSettings.json => "ASPNETCORE_ENVIRONMENT": "Development"
![Development-OK](https://github.com/microsoft/fluentui-blazor/assets/7785299/ff627b6e-6b13-41b5-815a-154e0b9871a6)

Not working => Staging
appsettings.Staging.json
launchSettings.json => "ASPNETCORE_ENVIRONMENT": "Staging"
![Staging-KO](https://github.com/microsoft/fluentui-blazor/assets/7785299/3b5440ab-bbe7-43f5-84cc-cccabe4138bb)

To reproduce the issue:
[FluentBlazorAppNet8.zip](https://github.com/microsoft/fluentui-blazor/files/13640858/FluentBlazorAppNet8.zip)

Thanks for your help.

**Comment by vnbaaij** [comment]
This seems to be more on a .NET level than something caused by our library. Did you try the same with the standard template?

**Comment by pk9r327** [comment]
According to Microsoft recommendations for testing, staging, and production environments, always publish and deploy the app. The ASP.NET Core framework expects exactly "Development" name when configuring the app and tooling for local development runs of an app.
See: https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-8.0

**Comment by AlexKidd29** [comment]
@vnbaaij  => I tested with the template "Blazor Web App" without FluentUI-Blazor.
I confirm I reproduced the same issue with this template.
So the issue is not related to FluentUI-Blazor.

@pk9r327 => Thanks for this link.
