### ISSUE TITLE
feat: add SSR only compatibilty to NavGroup expandability

### ISSUE THREAD

**Issue by aco-mreble** [microsoft/fluentui-blazor#1105]
# 🙋 Feature Request
I'm impressed with how many features in FluentUI work seamlessly in .NET 8's SSR mode (non-interactive), considering its extensive use of JavaScript. Previously I used MudBlazor, but its once greatest strength has become its biggest weakness: most of its components are written in pure C#, rendering a lot of them incompatible with SSR in Blazor.

For example `FluentAccordion` works like a charm without `InteractiveServer` rendermode. But `FluentNavGroup` does not. I would like to see if `FluentNavGroup` would also be expandable in SSR only mode.

## 🤔 Expected Behavior

`FluentNavGroup` should expand when I click on it when `@rendermode` is not set (or when it's a pure SSR Blazor project)

## 😯 Current Behavior

Nothing happens when I click on the group.

## 💁 Possible Solution

* Add Javascript handler?
* Maybe find a smart solution with `EditForm` so that we can change the `Expanded` property?

## 💻 Examples
```
@* Without enabling InteractiveServer rendermode the "Item3" NavGroup can't be expanded by clicking on it*@
@* @rendermode InteractiveServer *@

<nav>
	<FluentNavMenu Width="250" Title="Custom navigation menu">
		<FluentNavLink Href="/" Match="NavLinkMatch.All" Icon="@Icon.FromImageUrl("/images/home.svg")" IconColor="Color.Accent">Home</FluentNavLink>
		<FluentNavLink Href="weather" Icon="@Icon.FromImageUrl("/images/weather.svg")" IconColor="Color.Accent">Weather</FluentNavLink>
		<FluentNavGroup Title="Item 3">
			<ChildContent>
				<FluentNavLink>Item 3.1</FluentNavLink>
				<FluentNavLink>Item 3.2</FluentNavLink>
			</ChildContent>
		</FluentNavGroup>
	</FluentNavMenu>
</nav>
```

**Comment by vnbaaij** [comment]
I was thinking about that as well. Only thing is the Group and Item have an Event Callback method that's called on expansion. I don't want to lose that capability. So ideally there should be some sort of 'progressive enhancement' were it uses JavaScript when in SSR mode and uses the Blazor code when there is interactivity. Not sure yet if (and how) that can be achieved.

**Comment by aco-mreble** [comment]
I totally understand your concern and I agree. I'll take a look into this, maybe I can find a solution which archive both :)

**Comment by vnbaaij** [comment]
Of course! Closing this issue then and looking forward to your PR 😉
