### ISSUE TITLE
fix: projects with names containing hyphens in project template

### ISSUE THREAD

**Issue by GinoCanessa** [microsoft/fluentui-blazor#1107]
# 🐛 Bug Report

When creating a project using the 'Fluent Blazor Web App' template, if the project name contains a hyphen (-) character, the project does not render correctly.

## 💻 Repro or Code Sample

* Create a new project using the 'Fluent Blazor Web App' template with a name containing a hyphen (e.g., 'test-test').
* -or- add the NuGet packages to an existing web app project that has a name containing a hyphen
* Run the project

## 🤔 Expected Behavior

UI renders with FluentUI components.  Below is a screenshot of a project named `fhir.candle`.

![image](https://github.com/microsoft/fluentui-blazor/assets/50417653/77be04fb-0be2-4275-9675-a2fa711d0532)

## 😯 Current Behavior

UI renders without FluentUI components.  Below is a screenshot of a project named `fhir-candle`.

![image](https://github.com/microsoft/fluentui-blazor/assets/50417653/14a4745c-befd-47a7-bcce-e4bf19448a55)

## 💁 Possible Solution

I do not know.  First *guess* would be something in how the namespaces get renamed from `-` to `_` and that something gets mis-mapped.

## 🔦 Context

Working on a cross-platform CLI/UI project that contains a hyphen in the name and wanted to swap the UI component library over to FluentUI.  Several rounds of modifying and creating projects resulted in only apps that did not render correctly.  Eventually, I tried creating a new solution with 'default everything' and it worked.  From there, I tinkered until I found (what I believe) the issue to be.

It might be possible to rename the project files, change the output to match the current names, add aliases where appropriate, etc., but I am pretty stuck with the existing (hyphenated) name and will likely not use the components unless/until it is resolved.

## 🌍 Your Environment

* OS & Device: Windows 11 on ARM PC
* Browser Microsoft Edge.
* .NET and FAST Version .Net 8.0, Microsoft.FluentUI.AspNetCore.Components 4.1.1

**Comment by pk9r327** [comment]
At https://github.com/microsoft/fluentui-blazor/blob/906c512ad4fc93fd1fdd3c82bf2f99c310343491/src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/BlazorWeb-CSharp.csproj#L10C132-L10C132

I do see a backtick character (`) before AssemblyName, perhaps this is a typo. Temporarily, you can go to the *.csproj file and delete that character.

**Comment by vnbaaij** [comment]
Yes, that backtick is definitely the culprit. I see it is there in the original template as well. Will try to find out wahat the meaning of that is.
But deleting the character does indeed make the solution with the generated project(s) work as expected (after full rebuild)

**Comment by GinoCanessa** [comment]
Thanks so much, cheers!
