### ISSUE TITLE
docs: fix/add Datagrid how to prevent column overflow

### ISSUE THREAD

**Issue by LukasKubicek** [microsoft/fluentui-blazor#1108]
In the DataGrid [examples page](https://www.fluentui-blazor.net/DataGrid), in **"Typical usage"** example, there is this css snippet:

```
/* Stop country name text from wrapping, and truncate with ellipsis */
::deep .country-name::part(control) {
    overflow: hidden;
    text-overflow: ellipsis;
}
```

I would like to replicate this functionality, but I don't understand where the `country-name` class comes from. I tried to naively replace "country" with my own property name, but that doesn't work.

**Comment by vnbaaij** [comment]
Oops, sorry, That is an oldfix we used to need and is not applicable anymore. The overflow hidden and text-overflow: ellipsis; should be there already

**Comment by LukasKubicek** [comment]
Is that some property I need to activate? Or should it be be default on? 
I am on version 4.1.1 and I basically copy pasted from Typical usage example, but my Name column overflows when I resize the column..

![image](https://github.com/microsoft/fluentui-blazor/assets/2196235/d7aecd13-c806-496a-96a7-5a91b8b79016)

**Comment by vnbaaij** [comment]
Not that I know of. The css for a gridcell has this:
```
fluent-data-grid-cell {
    text-overflow: ellipsis;
}
```
So it should be set up already. Is it just a string that is being displayed? Maybe make available a repo we can see this happening in so we can examine whqat is going on.

**Comment by LukasKubicek** [comment]
Uhm, it just started working :) but I am not sure why.. I just changed GridTemplateColumns width definitions and aligned all columns to "Start".. then it started working.

If you want I can investigate what exactly caused the change..

**Comment by vnbaaij** [comment]
No, fine be me 😀. I'll close this one.
At keast we got the samples cleanded up...
