### ISSUE TITLE
docs: How to make traditional navbar

### ISSUE THREAD

**Issue by LukasKubicek** [microsoft/fluentui-blazor#1114]
I am trying to create traditional navbar (horizontal menu bar with links, not side menu). 

It is not clear from the documentation whether I should use `NavMenu `for this purpose or if I should just create it manually in `Header` component? 

If using header is it better to use NavGroup and NavLink or not?

I would appreciate some example in documentation with horizontal navbar. 🙏

**Comment by vnbaaij** [comment]
You should not use a `NavMenu` for that. It has no parameters or settings to be displayed in a horizontal fashion. Manual creation in the `Header` is theway to go. You can combine that with the `Menu` and/or `Toolbar` componentsto compose something to your likening.

**Comment by xcaptain** [comment]
Same problem here. I tried `<FluentToolbar>`, but still not looks right.

1. The toolbar is white but the header background is blue.
2. The navlink is not centered in the button.
3. Can't set gaps between the 3 buttons to make them centered in the toolbar.

![image](https://github.com/microsoft/fluentui-blazor/assets/4054836/70598ffe-d37a-4381-a6e0-a573a62761e0)

**Comment by xcaptain** [comment]
Added some `<FluentSpacer>` now the buttons are centered in the toolbar, but still have some problems.

1. `color:blue` in toolbar not works, it's still white.
2. navlinks aligns at the bottom of the toolbar, should align center.
3. no active indicator for the current navlink.

![image](https://github.com/microsoft/fluentui-blazor/assets/4054836/ecb36c87-db86-458b-89ef-1cb7968d31f9)

**Comment by vnbaaij** [comment]
Sorry, but it is just not a component in the current Fluent Design system and therefore not something we will be building in the short term. For now you will have to revert to 'hacking' the generated styles ::deep and :part selectors are your friends there.
If you search through the code you should be able to find some examples of how we use that in other components

**Comment by xcaptain** [comment]
Thanks, will try it later.

Vincent Baaij ***@***.***> 于 2023年12月21日周四 01:01写道：
