### ISSUE TITLE
feat: add Charts and Stepper

### ISSUE THREAD

**Issue by Amine-Smahi** [microsoft/fluentui-blazor#1117]
Hi team,

is there any plan to support Charts or Stepper components ?

Would be awesome
Thank you for the good work

**Comment by Amine-Smahi** [comment]
For stepper, something like 
![image](https://github.com/microsoft/fluentui-blazor/assets/24621701/71afabe0-5a60-4580-ab0b-b135283603bd)

https://m1.material.io/components/steppers.html

**Comment by vnbaaij** [comment]
A stepper/wizard like component is indedd on the list already (NO eta yet!!)

For Charts, see #1043 
Closing this as duplicate

**Comment by hksalessio** [comment]
I'm actually currently working on a stepper component as we needed one for our website. Was already thinking of creating a pull request. Would that help you guys? It's not perfect yet but could serve as a starting point.

**Comment by vnbaaij** [comment]
@hksalessio  Maybe you can share some screenshots here first? Then we can validate those agiangst the Fluent design before we start working on coding it in.

**Comment by dvoituron** [comment]
We are working on a Wizard component which will probably be released before the end of the year. But all suggestions and ideas are welcome.
![Wizard-Sample](https://github.com/microsoft/fluentui-blazor/assets/8350694/dea4a8e2-aa08-4d70-86e0-2c91c95e5309)

**Comment by Amine-Smahi** [comment]
Great work @dvoituron! is only a vertical one ? it would be awesome also to have a horizontal one,
If both are responsive would be perfect 👌

**Comment by dvoituron** [comment]
Yes. Both: horizontal or vertical 😊 but not yet responsive. Good idea 🤪

**Comment by hksalessio** [comment]
Your wizard looks amazing! I love how much effort you guys put into this project, it's really impressive! Will there be options to toggle step indicator numbering and to allow icons for the step indicators? I guess, I can stop working on my own implementation then :D This is how my stepper looks:
<img width="185" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/143792830/52ae82a4-7aa8-4772-8726-c6e9ec4adcf2">
<img width="758" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/143792830/0416d409-2083-4afa-ac6a-95ee64bcfa81">

**Comment by dvoituron** [comment]
> Your wizard looks amazing! I love how much effort you guys put into this project, it's really impressive! Will there be options to toggle step indicator numbering and to allow icons for the step indicators? I guess, I can stop working on my own implementation then :D This is how my stepper looks: <img alt="image" width="185" src="https://private-user-images.githubusercontent.com/143792830/290770924-52ae82a4-7aa8-4772-8726-c6e9ec4adcf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzA3NTksIm5iZiI6MTcwMjYzMDQ1OSwicGF0aCI6Ii8xNDM3OTI4MzAvMjkwNzcwOTI0LTUyYWU4MmE0LTdhYTgtNDc3Mi04NzI2LWM2ZTllYzRhZGNmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwODU0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTFjN2Y5ZGQzNjk1Y2MzNzAxMWJiZWNkNzI0MzkxYWZlZmYyZjdiMjI4NWJhNWVhYjljYjNmMTM4YzczN2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G6NDvqWG2nmp6leIf5MWhyupOWcIVGbsd6YQcoi1J24"> <img alt="image" width="758" src="https://private-user-images.githubusercontent.com/143792830/290771390-0416d409-2083-4afa-ac6a-95ee64bcfa81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzA3NTksIm5iZiI6MTcwMjYzMDQ1OSwicGF0aCI6Ii8xNDM3OTI4MzAvMjkwNzcxMzkwLTA0MTZkNDA5LTIwODMtNGFmYS1hYzZhLTk1ZWU2NGJjZmE4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwODU0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTU5ZDM1NDIzYTY1Mjk1MmZkMTM2Y2UyMTQ5ZGM2ZWUwMjBhNGE1ODY2Mjc2MThkYTc3NjIwMzlhYTExYzQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zdnt7uOyob1emWrrysP9DJCllVBDNAKSTPcjX3G-Vlo">

This could be possible :-)

**Comment by dvoituron** [comment]
@hksalessio @Amine-Smahi 
A first PR is here: https://github.com/microsoft/fluentui-blazor/pull/1211 
Don't hesitate to send us your comments.
