### ISSUE TITLE
docs: Complex form example

### ISSUE THREAD

**Issue by LukasKubicek** [microsoft/fluentui-blazor#1118]
The [form example ](https://www.fluentui-blazor.net/basicform-fluentui-components) in documentation has no razor code available on the documentation page, like most other example have.

It would be great to have somewhat more complex form using Fluent inputs as an example with razor code. Mostly to show how to group, align and format elements in a form. My inputs (text input, number input..) are very narrow and I am not sure why, what is the preferred way of formatting a form?

**Comment by vnbaaij** [comment]
There is no razor code as it is just an Fluent representation of [this form](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/input-components?view=aspnetcore-8.0#example-form)

We don't have any opinions on how you should style your forms (other than following the [Fluent](https://fluent2.microsoft.design/) guidelines). All input related components support the `Class` and `Style` parameters  which you can use to size your form fields. As far as layout is concerned, we offer the `FluentStack` and `FluentGrid` components which should allow you to deliver any layout you can come up with.
