### ISSUE TITLE
fix: main content doesn't stretch to bottom with removed footer 

### ISSUE THREAD

**Issue by LukasKubicek** [microsoft/fluentui-blazor#1119]
# 🐛 Bug Report

When the FluentFooter is removed from the MainLayout, it leaves white strip at the bottom of the page and content is not rendered in this area. Not even scrollbar is used for this part.

Create new project from the Template in Visual Studio, remove FluentFooter in MainLayout, put some long content on any page (so that it is longer than screen height) and observe white strip at the bottom that is not used.

**Comment by vnbaaij** [comment]
That is just a simple CSS thing you can solve yourself. 

The total height of the window for the MainLayout is calculated as (100dvh - 86px) That 86 is normally header height + footer height, but  If you leave the footer out, the calculation does not work anymore, of course. 

Change it in the 'app.css' file around line 16

**Comment by LukasKubicek** [comment]
That is not very intuitive..

**Comment by vnbaaij** [comment]
You're changing the layout of a template and then think it is strange you need to change something to make it look right again?
