### ISSUE TITLE
fix: theme (css) not working when running in Maui (web-components-v2.5.16.min.js not available)

### ISSUE THREAD

**Issue by iwhp** [microsoft/fluentui-blazor#1123]
# 🐛 Bug Report

The documentation states the following:

> Scripts
> ... In this situation, include the following in your App.razor:
> <script src="_content/Microsoft.FluentUI.AspNetCore.Components/js/web-components-v2.5.16.min.js" type="module" async></script>

and

> Tempory workaround for MAUI/WPF/Windows Forms issues
> ... The needed initializersLoader.webview.js has been added to the library and needs to be included with a script tag **before** the _framework/blazor.webview.js script tag:
> <script app-name="{NAME OF YOUR APP}" src="./_content/Microsoft.FluentUI.AspNetCore.Components/js/initializersLoader.webview.js"></script>

Both ob these .js files are not available in v4.2.0, and the theming for fluentui components in a Maui app does not work.

## 💻 Repro or Code Sample

I updated my working Maui/Blazor app.
One may create a new Maui/Blazor app and follow the fluentui-blazor documentation.

## 🤔 Expected Behavior

Theming of fluentui components should work.

## 😯 Current Behavior

I see in the browser devtools (F12), that the two files from above are missing.

## 💁 Possible Solution

Maybe make the two files available in the nuget package,
or update the documentation for how to use fluentui-blazor in Maui.

## 🔦 Context

I have updated from v4.1.1 to v4.2.0.

## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge
* .NET v8 and FAST v?

**Comment by vnbaaij** [comment]
That's a good catch. We changed the way we are handling script with this version.

The good news is that both scripts are in fact still there but are now integrated into `Microsoft.FluentUI.AspNetCore.Components.lib.module.js`

Can you retry with replacing the `initializerLoader.webview.js` script with `_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js ` and let us know if this helps?

**Comment by vnbaaij** [comment]
I tried it locally with this:
```
<script app-name="MauiApp1" type="module" src="./_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js"></script>
```
before the `blazor.webview.js` line and it then works as expected.

I'll change the docs. Thanks.

**Comment by vnbaaij** [comment]
Yes, the script is needed for SSR as well as it contains the styling for the underlying FLuent UI Web Components.  If you use our templates to create a project, this will be taken care of.
Closing this as no further action needed.
