### ISSUE TITLE
rfc: Review Icon sizing mechanics by decoupling Icons size from svg viewport sizing, exposing Icons without their size and dropping the enum restricting the available size. 

### ISSUE THREAD

**Issue by EricOnGit** [microsoft/fluentui-blazor#1124]
# 💬 RFC

Let's break it down while keeping in mind that I'm fairly new to the library. So let me know if I missed something.
1- decoupling icons size and svg viewport size. 
The basic idea is simply to make any svg icon resizable to any value. As long as the viewport is properly defined, you can set the width to any value and "voilà".
Looking a the ToMarkup function in the Icon class, there seems to have been some thoughts in that direction since the styleWidth variable might be initialized to a different value if the size parameter is not null. But, I can't see how to provide such value since the icons constructors are not receiving the size. (the base class is, tho)

2- Exposing Icons without their size
If we agree on # 1, then it would make sense to remove the size portion from the path to an Icon and have it as a parameter to the constructor. That would facilitate icon discovery and open up any size for all icons.
From Icons.[IconVariant].[IconSize].[IconName] to Icons.[IconVariant].[IconName]**([IconSize])**. I understand that we might need to keep the previous path for compatibility.

3- Drop the IconSize enum restricting the available size. 
Well at this point why bother restricting the size? Any positive value would work. The enum becomes a nuisance that will only infuriate anyone that requires a 38px button...

In the end an Icon could be exposed this way (minus the IconSize cast):
`public static partial class Icons {
	public static partial class Filled {
		public class PresenceAvailable(uint size) : Icon("PresenceAvailable", IconVariant.Filled, (IconSize)size, "<path d=\"M5 10A5 5 0 1 0 5 0a5 5 0 0 0 0 10Zm2.1-5.9L4.85 6.35a.5.5 0 0 1-.7 0l-1-1a.5.5 0 0 1 .7-.7l.65.64 1.9-1.9a.5.5 0 0 1 .7.71Z\"/>") { }
	}
}`

End used like this:
`<FluentButton IconStart="@(new Icons.Filled.PresenceAvailable(38))" />`

4- Another options is to implement the same behavior exposed through WithColor in the Icon class but this time for the size. Something along the lines of `public virtual Icon WithSize(string size)...` allowing size using other suffix than px.

Usage syntax might feels off if # 2 is not possible:
`<FluentButton IconStart="@(new Icons.Filled.Size10.PresenceAvailable().WithSize("38rem"))" />`

**Comment by dvoituron** [comment]
Hello, and thank you for this super interesting reflection. It's good to see that you're analyzing things correctly.

In fact, we've already thought about this internally, and the main reason for these sizes comes from a discussion with the designers: we use all the icons from the https://github.com/microsoft/fluentui-system-icons website, and you'll see there that the icons are also available in several sizes.

Although these are SVG files, and therefore easily resizable, designers prefer to create different sizes, as the graphic details of a size 48 icon are not the same as those of a size 12 icon 😀 Designers' specifications and details... which I fully understand and accept. We have therefore applied the same logic to maintain the detail of size 48 icons compared with size 12 icons.

But anyway, if you don't need these details, you can easily resize the SVG icon.

```xml
<FluentIcon Value="@(new Icons.Regular.Size24.AccessTime())" Width="128px" />
```

```xml
@(new Icons.Regular.Size24.AccessTime().ToMarkup("128px", "red"));
```
In the final analysis, this is not a problem for the size of the final library, because publishing in WASM will delete all the icons not used in your project (Trimming Process), and in Server publishing, 3 MB more on the server is really a problem (or you can apply the same Trimming Process).

**Comment by EricOnGit** [comment]
Hi @dvoituron, thanks for the quick reply. 

Using ToMarkup was my first goto but how can I use this with the IconStart, IconEnd of a FluentButton which expects an Icon and not a string? This is why I came up with the idea of implementing WithSize() which would return an Icon. But, maybe I missed something.

And regarding this part:
> Finally, choosing the size at the end (Icons.Filled.PresenceAvailable(24) or Icons.Filled.PresenceAvailable.Size24) is not possible, as not all icons exist in all sizes :-)

This is only true because of the current implementation (we already agreed svg can be resized). I understand the designers wishing for more details on bigger icons and I also support the concept. That said, there are other implementations that would support both the designers wishes and the developers experience. They are more complex, I'll admit, but they would serve everyone's needs and be much more efficient for the devs. 
Going back and forth in intellisense to see if an icon is available only to find out that it is, but only in a size that doesn't fit is currently killing my experience. I spent more time looking for icons than I coded in the last 2 days. Honestly, I don't see that getting any better (my brain will never remember which Icon is available in what size). And nobody coming from a different frontend framework (material, bootstrap, fontawesome) will either. In general, you set the size on the parent and expect the svg/icon to use 100% of the space. (that would be possible using WithSize("100%")).

Putting a side the complexity, my ideal solution would be that icons be freely resizable, easy to discover from the IDE and, as a bonus, would use a more detailed version when available. Discoverability and dynamic details are 2 beasts to implements due to the sheer amount of code involved but the WithSize() function is something simple that would help in the short term.

Before investing more time on this request, I'd like to know if there's an opportunity here or not. I think I can come up with a practical implementation but I'm not too fond of making a PR only to see it sitting there for months (like I've seen with other projects).

Cheers!

**Comment by vnbaaij** [comment]
We are totally dependant on the sources that we get from the repo @dvoituron mentioned. With the process we have in place now, updating on our side to a new release on their side is just a couple of commands we need to execute. See https://github.com/microsoft/fluentui-blazor/blob/dev/src/Assets/Generator/ReadMe.md for more information. (The `buildforblazor` command was a contribution to that repo made by me).

If you can come up with a mechanism with which it is still going to be very easy for us to update to a new release done in the source repo, then (I think I can speak for Denis as well) we are definitely not against it. Because we already broke the whole icon (and emoji) mechanism for the developers with a previous version update, we rather not do that again, so anything you do/change needs to be an addition and not a replacement.

Please keep in mind that not all icons are available in all sizes for a reason (albeit mostly asthaetic). We do not want to deteriorate the experience for the end-user (ie who you are building the app for) by serving them a 'crapy' version (exagerating on purpose) of an icon that was originally not available in that size.

**Comment by dvoituron** [comment]
Another "detail": it might be interesting to check whether **Size20** contains all the other icon names (development of a small tool based on .NET thinking, for example 😀).

**Comment by EricOnGit** [comment]
hi @vnbaaij 
Thanks for sharing the information regarding the generator (I had a feeling nobody was typing those 100k lines by hand!)

I do understand that everything will need to be backward compatible and I'm perfectly ok with it. Offering better discoverability shouldn't be a breaking change nor should we render a crappy version of an icon.

@dvoituron good point regarding the use of the explorer and adding the "any size" options. I also found this site https://fluenticon.netlify.app/ but again no option to search in all sizes.

Seeing that there's an opening to move forward, I'll dig a bit more and get back to you two here.

Thanks!

**Comment by EricOnGit** [comment]
@vnbaaij, @dvoituron I've prepared a PR #1136 for the first (and easy) part of this request. Took about 5 minutes to code and 1 hour to setup and read all the doc related to submitting a PR. Still, I think I might have mess up by using the dev branch. Please let me know if anything needs to be adjusted.

**Comment by EricOnGit** [comment]
> Another "detail": it might be interesting to check whether **Size20** contains all the other icon names (development of a small tool based on .NET thinking, for example 😀).

Unfortunately it's not the case. Every size has at least one unique icon except size 10. In total there are 81 unique icons not present in any other size. Excel conditional formatting on unique values was quicker than building a tool to find this information😉

I'll put some more thoughts on how I could enhance the generator to build a flat list and still choose the proper svg based on the size requested and get back to you guys.

**Comment by EricOnGit** [comment]
After a couple hours, here's what might be possible.
First what the result can be using a FluentButton in a loop to test all possible sizes from 1 to 54 px.
```c#
<FluentButton Class="p-2" IconStart="@(new Icons.Filled.ArrowCircleDown(i))" >@($"{i}")</FluentButton>
```
![image](https://github.com/microsoft/fluentui-blazor/assets/90164955/5d71fbe1-a024-480b-b8b7-6ec5b855a57e)

Depending on the requested size the proper svg is selected as we can see here:
For 1px we get size 10 since nothing better exists
![image](https://github.com/microsoft/fluentui-blazor/assets/90164955/69d0dea7-0c6f-42fb-80a4-92c5c4b4052a)
for 11px same size 10
![image](https://github.com/microsoft/fluentui-blazor/assets/90164955/010411d9-f5db-474b-bed2-7aaec39032e9)
for 12px we get the size 12 since it exists
![image](https://github.com/microsoft/fluentui-blazor/assets/90164955/e60a328a-9124-4e8b-b53e-3b9567bd33be)
and so on up to size 48 for anything 48 and over
![image](https://github.com/microsoft/fluentui-blazor/assets/90164955/72678f7e-10c0-40b6-8471-2c0af2f337e3)

Adding and removing sizes in future releases would automatically be used. That would need to be properly documented.

My current implementation looks like this:
```c#
public static (IconSize, string)[] ArrowCircleDownSizeAndContent = new[] {
    (IconSize.Size10, "<path d=\"M5 10A5 5 0 1 0 5 0a5 5 0 0 0 0 10Zm2.1-5.9L4.85 6.35a.5.5 0 0 1-.7 0l-1-1a.5.5 0 0 1 .7-.7l.65.64 1.9-1.9a.5.5 0 0 1 .7.71Z\"/>"),
    (IconSize.Size12, "<path d=\"M11 6A5 5 0 1 1 1 6a5 5 0 0 1 10 0Zm-2.65.1a.5.5 0 0 0-.7 0L6.5 7.24V3.5a.5.5 0 0 0-1 0v3.74L4.35 6.1a.5.5 0 1 0-.7.7l2 2c.2.2.5.2.7 0l2-2a.5.5 0 0 0 0-.7Z\"/>"),
    (IconSize.Size16, "<path d=\"M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8Zm6.8 3.46a.5.5 0 0 1-.15-.1l-2.5-2.5a.5.5 0 1 1 .7-.71L7.5 9.79V5a.5.5 0 0 1 1 0v4.8l1.65-1.65a.5.5 0 0 1 .7.7l-2.5 2.5a.5.5 0 0 1-.54.11Z\"/>"),
    (IconSize.Size20, "<path d=\"M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Zm-4.65.85a.5.5 0 0 0-.7-.7l-2.15 2.14V6.5a.5.5 0 0 0-1 0v5.8l-2.15-2.15a.5.5 0 0 0-.7.7l3 3c.2.2.5.2.7 0l3-3Z\"/>"),
    (IconSize.Size24, "<path d=\"M2 12a10 10 0 1 0 20 0 10 10 0 0 0-20 0Zm14.53-.28c.27.27.29.68.07.98l-.07.08-4 4a.75.75 0 0 1-.98.07l-.08-.07-4-4a.75.75 0 0 1 .97-1.13l.09.07 2.72 2.72V7.75c0-.38.28-.7.65-.74L12 7c.38 0 .7.28.74.65v.1l.01 6.69 2.72-2.72c.27-.27.68-.3.98-.07l.08.07Z\"/>"),
    (IconSize.Size28, "<path d=\"M14 2a12 12 0 1 0 0 24 12 12 0 0 0 0-24ZM8.97 14.22c.3-.3.77-.3 1.06 0l3.22 3.22V8.75a.75.75 0 0 1 1.5 0v8.69l3.22-3.22a.75.75 0 1 1 1.06 1.06l-4.5 4.5c-.3.3-.77.3-1.06 0l-4.5-4.5a.75.75 0 0 1 0-1.06Z\"/>"),
    (IconSize.Size32, "<path d=\"M16 2a14 14 0 1 0 0 28 14 14 0 0 0 0-28ZM9.3 15.3a1 1 0 0 1 1.4 0l4.3 4.29V10a1 1 0 1 1 2 0v9.59l4.3-4.3a1 1 0 0 1 1.4 1.42l-6 6a1 1 0 0 1-1.4 0l-6-6a1 1 0 0 1 0-1.42Z\"/>"),
    (IconSize.Size48, "<path d=\"M24 4a20 20 0 1 0 0 40 20 20 0 0 0 0-40Zm-8.63 19.87a1.25 1.25 0 0 1 1.76 0l5.62 5.61V15.25a1.25 1.25 0 1 1 2.5 0v14.23l5.62-5.61a1.25 1.25 0 0 1 1.76 1.76l-7.75 7.75c-.48.5-1.28.5-1.76 0l-7.75-7.75a1.25 1.25 0 0 1 0-1.76Z\"/>")
};
public class ArrowCircleDown : Icon { public ArrowCircleDown(int size) : base("ArrowCircleDown", IconVariant.Filled, ArrowCircleDownSizeAndContent.GetProperSizeAndContent(size)) { OverriddenWidth = size; } }

/// <summary>
/// returns the tuple representing the size and content of the first smaller available size or the first size if nothing fits (size smaller than the minimum available size)
/// </summary>
public static (IconSize size, string content) GetProperSizeAndContent(this (IconSize size, string content)[] sizes, int size)
{
    if (sizes.Length == 0) { new InvalidOperationException($"{nameof(sizes)} must not be empty"); }
    if (sizes.Length == 1) { return sizes[0]; }
    for (int i = sizes.Length - 1; i >= 0; i--)
    {
        if ((int)sizes[i].size <= size) return sizes[i];
        // TODO check if we're closer to the next larger icon (23px could be better served by scaling down size 24 than scaling up size 20) 
    }
    return sizes[0];
}
```
Existing Icon classes would also be regenerated to be using the SizeAndContent tuples to reduce duplication.

Preliminary benchmarks shows no change in performance (but for some reason I cannot build in release, so this will require more investigation)

One caveat could be a change in trimming. With this implementation, my understanding is that the moment you use one icon all svg for that icon will be retained. Will that make a big difference? I don't know for sure. 

Any thoughts before I start adapting the generator?

**Comment by dvoituron** [comment]
I find this work very interesting, but I think it's still complicated.

1. It's an important Breaking Change. This means modifying all calls with new icon signatures.
2. As you say, the Trimming process will keep the 8 icons when only one is used. The final DLL size can quickly become a problem if you do x8 for all the icons.
3. I did a small test (see [this code](https://gist.github.com/dvoituron/424a37816bfc9cd26f5d9227d5ad2efd)) and on the 2521 Regular20 icons, only 95 are not present... that's **4% of the icons**. 
  The impact of this change compared to the benefits is, in my opinion, too great.

```
Number of icons
 - Regular.SizeSize10 = 7
 - Regular.SizeSize12 = 157
 - Regular.SizeSize16 = 1403
 - Regular.SizeSize20 = 2521
 - Regular.SizeSize24 = 2212
 - Regular.SizeSize28 = 629
 - Regular.SizeSize32 = 510
 - Regular.SizeSize48 = 485
 - Filled.SizeSize10 = 4
 - Filled.SizeSize12 = 154
 - Filled.SizeSize16 = 1441
 - Filled.SizeSize20 = 2559
 - Filled.SizeSize24 = 2249
 - Filled.SizeSize28 = 633
 - Filled.SizeSize32 = 516
 - Filled.SizeSize48 = 489

Size10: missing 0 icons, not include in Size20
Size12: missing 2 icons, not include in Size20
Size16: missing 54 icons, not include in Size20
Size20: missing 0 icons, not include in Size20
Size24: missing 28 icons, not include in Size20
Size28: missing 2 icons, not include in Size20
Size32: missing 8 icons, not include in Size20
Size48: missing 1 icons, not include in Size20

Missing 95 icons / 2521 Regular.Size20 = 04%
```

➡️ The question is more: "how do I find an icon easily". And I see two applicable solutions

1. Add a "Search all sizes" option to the website icon explorer.
2. Add a class that inherits the most "adapted" (Size20, larger?) sized icon.
    - `Icons.Regular.Common.ArrowDown : Size48.ArrowDown`
    - `Icons.Regular.Common.Beach: Size20.Beach`

**Comment by EricOnGit** [comment]
@dvoituron Just to be clear this change is not a breaking change with regards to the library consumption. It adds to the current definition and reuse the same content in both declarations to minimize the content duplication. 
As a complement, I've been able to build in release and here are the benchmark results
![image](https://github.com/microsoft/fluentui-blazor/assets/90164955/37126702-ee4a-4226-97bb-59c08b46ad7b)

**Comment by EricOnGit** [comment]
@dvoituron regarding trimming. 
Knowing that most icons only offer 3-4 sizes (16 to 24 px) and adding my personal experience where most applications only use a handful of icons (way under a hundred) of one type (regular or filled) and generally use more than one size of each of these. I think the impact will be very limited. That said, only a concrete example will tell.

And regarding using only size 20. Honestly that was my first thought too. But @vnbaaij did mention that he would not want to serve a "crappy" version of an icon when a better one is available. 

Summarizing my perspective,
1) not a breaking change, only an additional feature.
2) small theoretical trimming impact to be validated in real-life scenarios
3) equivalent if not better performance
4) discoverability gain (even if you doubt me here 😉)
5) flexibility gain where you can now size an icon to any dimension and benefit from the best looking icon without doing anything more.

Hope this helps you guys decide if you wish to go ahead.

**Comment by vnbaaij** [comment]
Overall, I like the outcome of the changes but I'm not a fan of storing all the sizes in 1 object. 

Even tought there might be only a couple of them in each icon, I think that the result of trimming should be that the result is that is only left what is actully being used. (I believe the number of size variations per icons is something that is increasing with every release btw)

Courious to see how you can have both `Icons.Filled.ArrowCircleDown(i)` and `Icons.Filled.Size24.ArrowCircleDown()` without breaking anything. Is there a lot of extraneous code needed for that?

**Comment by EricOnGit** [comment]
I'm using an extension method to return the proper Size and Content tuple in the constructor of the sizable class and the index of the array of tuple in the fixed one. I also assume that PR #1136 is eventually merged.

It looks like that:

Extension method
```c#
/// <summary>
/// returns the tuple representing the size and content of the first smaller available size
/// </summary>
public static (IconSize size, string content) GetProperSizeAndContent(this (IconSize size, string content)[] sizes, int size)
{
    if (sizes.Length == 0) { new InvalidOperationException($"{nameof(sizes)} must not be empty"); }
    if (sizes.Length == 1) { return sizes[0]; }
    for (int i = sizes.Length - 1; i >= 0; i--)
    {
        if ((int)sizes[i].size <= size) return sizes[i];
        // TODO check if we're closer to the previous larger icon (47px could be better served by scaling down size 48 than scaling up size 32) 
    }
    return sizes[0];
}
```

The tuple maintaining size and content [would be generated]. Worst case here since all 8 sizes are present. The vast majority have only 2 to 3 sizes.
```c#
public static (IconSize, string)[] ArrowCircleDownSizeAndContent = new[] {
    (IconSize.Size10, "<path d=\"M5 10A5 5 0 1 0 5 0a5 5 0 0 0 0 10Zm2.1-5.9L4.85 6.35a.5.5 0 0 1-.7 0l-1-1a.5.5 0 0 1 .7-.7l.65.64 1.9-1.9a.5.5 0 0 1 .7.71Z\"/>"),
    (IconSize.Size12, "<path d=\"M11 6A5 5 0 1 1 1 6a5 5 0 0 1 10 0Zm-2.65.1a.5.5 0 0 0-.7 0L6.5 7.24V3.5a.5.5 0 0 0-1 0v3.74L4.35 6.1a.5.5 0 1 0-.7.7l2 2c.2.2.5.2.7 0l2-2a.5.5 0 0 0 0-.7Z\"/>"),
    (IconSize.Size16, "<path d=\"M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8Zm6.8 3.46a.5.5 0 0 1-.15-.1l-2.5-2.5a.5.5 0 1 1 .7-.71L7.5 9.79V5a.5.5 0 0 1 1 0v4.8l1.65-1.65a.5.5 0 0 1 .7.7l-2.5 2.5a.5.5 0 0 1-.54.11Z\"/>"),
    (IconSize.Size20, "<path d=\"M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Zm-4.65.85a.5.5 0 0 0-.7-.7l-2.15 2.14V6.5a.5.5 0 0 0-1 0v5.8l-2.15-2.15a.5.5 0 0 0-.7.7l3 3c.2.2.5.2.7 0l3-3Z\"/>"),
    (IconSize.Size24, "<path d=\"M2 12a10 10 0 1 0 20 0 10 10 0 0 0-20 0Zm14.53-.28c.27.27.29.68.07.98l-.07.08-4 4a.75.75 0 0 1-.98.07l-.08-.07-4-4a.75.75 0 0 1 .97-1.13l.09.07 2.72 2.72V7.75c0-.38.28-.7.65-.74L12 7c.38 0 .7.28.74.65v.1l.01 6.69 2.72-2.72c.27-.27.68-.3.98-.07l.08.07Z\"/>"),
    (IconSize.Size28, "<path d=\"M14 2a12 12 0 1 0 0 24 12 12 0 0 0 0-24ZM8.97 14.22c.3-.3.77-.3 1.06 0l3.22 3.22V8.75a.75.75 0 0 1 1.5 0v8.69l3.22-3.22a.75.75 0 1 1 1.06 1.06l-4.5 4.5c-.3.3-.77.3-1.06 0l-4.5-4.5a.75.75 0 0 1 0-1.06Z\"/>"),
    (IconSize.Size32, "<path d=\"M16 2a14 14 0 1 0 0 28 14 14 0 0 0 0-28ZM9.3 15.3a1 1 0 0 1 1.4 0l4.3 4.29V10a1 1 0 1 1 2 0v9.59l4.3-4.3a1 1 0 0 1 1.4 1.42l-6 6a1 1 0 0 1-1.4 0l-6-6a1 1 0 0 1 0-1.42Z\"/>"),
    (IconSize.Size48, "<path d=\"M24 4a20 20 0 1 0 0 40 20 20 0 0 0 0-40Zm-8.63 19.87a1.25 1.25 0 0 1 1.76 0l5.62 5.61V15.25a1.25 1.25 0 1 1 2.5 0v14.23l5.62-5.61a1.25 1.25 0 0 1 1.76 1.76l-7.75 7.75c-.48.5-1.28.5-1.76 0l-7.75-7.75a1.25 1.25 0 0 1 0-1.76Z\"/>")
};
```
The declarations [would be generated]
```c# 
// in Icons.Filled
public class ArrowCircleDown : Icon { public ArrowCircleDown(int size) : base("ArrowCircleDown", IconVariant.Filled, ArrowCircleDownSizeAndContent.GetProperSizeAndContent(size)) { OverriddenWidth = size; } }

// in Icons.Filled.Size10
public class ArrowCircleDown : Icon { public ArrowCircleDown() : base("ArrowCircleDown", IconVariant.Filled, ArrowCircleDownSizeAndContent[0]) { } }
```
The Icon class needs a new constructor to receive the tuple
```c#
    /// <summary>
    /// Initializes a new instance of the <see cref="Icon"/> class.
    /// </summary>
    /// <param name="name"><see cref="IconInfo.Name"/></param>
    /// <param name="variant"><see cref="IconInfo.Variant"/></param>
    /// <param name="sc"><see cref="IconInfo.Size"/> <see cref="Icon.Content"/></param>
    protected Icon(string name, IconVariant variant, (IconSize size, string content) sc)
    {
        Name = name;
        Variant = variant;
        Size = sc.size;
        Content = sc.content;
    }
```
The extra code is basically an extension method and a very large bunch of constructors that need to be generated in the Filled and Regular static classes.

**Comment by EricOnGit** [comment]
I was too curious of the real world impacts. So I decided to go ahead and adapt the generator, build all the icons and trim the library with a plain Blazor Web App template. 

I got some interesting results.

Using version 4.2.0 publishing the original icon library alone produces a ~15MB dll.
Published for a trimmed client app:
- 	Using 1 icon of a single size weights in at 8k (3k compressed). Trimming is definitely working. 
- 	Adding all sizes (7 icons total) kept it at 8k
- 	Adding a new icon bumped it to 11k and adding all of its sizes (+7 more) kept it at 11k too. (3k compressed)

Using the new version with tuple arrays to maintain the Size and Content (allowing for optimal icon resize). The published dll grows to ~16MB
published for a trimmed client app:
- Using 1 icon made it a whooping ~6MB !!! (turns out static arrays are not trimmed at all) <---- who knew!?! and glad I checked
- Moving the tuple arrays in static classes made the trimmed size 8k (3k compressed) for 1 icon (same as the 4.2.0)
- Adding all size of the two same icons (14 icons) brings the size to 11k (3k compressed) (again same as the 4.2.0)
- Adding the fully resizable icons (+14 icons) adds another ~500 bytes
- Removing the fixed size icons (-14 icons) bring the total to 10.5k (3k compressed) (marginally better than 4.2.0). This might be explained by the fact that 14 icons required 14 constructors in 4.2.0 and only 2 in the new version.

Conclusions: 
- We're talking bytes here and this is a bad case scenario where 7 sizes exist for the two icons I used.
- And, if you choose to stick with only the resizable version, you actually get a marginally smaller footprint. Honestly, that was unexpected.

**Comment by vnbaaij** [comment]
Eric, we are massively gratefull for the time and effort you put in this. We decided however to not move forward with all of your proposed changes .
First of all, we will merge the WithSize PR. 

2) We are not going to change the way the icons are stored at the moment. We decided that trimming should leave a dev with just what is used, not some extra 'bonus' items for every icon. (it is now only 2 or 3 but that might (will probably change) in the future)

3) We will not offer devs options to use other sizes than those offered through the Fluent System Icon collection. They are offering those sizes for a reason (ie to follow Fluent Design system standards). We follow that Design System, offer a Blazor implementation of it and do not want to offer 'escapes'. We also want/need those sizes to be consistent and predictable for ourselves as other components might break if people start to use deviations. If a dev decides to  use an alternative value and the use it in another component which then breaks, they WILL start complaining here. 

4) There is only a real small number of icons (the 4% mentioned earlier) where we do not have a Size20 version). Do we reallty need/want to do all this work and changes to make those 95 icons better discoverable? Seems a bit of engineeering overkill to me. Besides, we now have the 'Search all sizes' option in the Icon Explorer so that should help discoverability.

5) Can we somehow have the extension methods without storing all the icons in one array/tuple? We definitely see value there. Any ideas on how we could add that in a non-breaking way.

Again, we really appriciate the thought you have given this and we hope it does not discourage you to keep offering your ideas.

**Comment by EricOnGit** [comment]
Hi @vnbaaij 

A couple things to make sure before you dismiss the change. Because I really feel something got lost in the discussion thread.

1. I don't know where the "breaking change" part is coming from but this is **not a breaking change** in any way. 
2. I also checked that trimming wasn't an issue (see comment just before yours) you actually get a smaller footprint if you use only the resizable version.

I must admit I don't understand the logic behind the "We will not offer devs options to use other sizes than those offered through the Fluent System Icon collection" statement and merging the WithSize() PR. Not saying you shouldn't merge it. Simply that you are already allowing for resize through ToMarkup and now WithSize. Only these two ways of dealing with sizing are not aligned with you requirement of "not serving a crappy version of an Icon".

The change I'm proposing is only making this easier to work with and ensures you get the best icon for the size you request without breaking anything or compromising on trimming.

If you feel like it, you can have an look a the code in the reverted commit and see for yourself.

Regards,

**Comment by vnbaaij** [comment]
> 1. I don't know where the "breaking change" part is coming from but this is **not a breaking change** in any way.

Ok, non-breaking was a poor choice of words here. I know you went through lengths not to break stuff. What I meant was, "can we have the extension methods without changing the current way the icons are declared (and keeping the current generation process)

> 2. I also checked that trimming wasn't an issue (see comment just before yours) you actually get a smaller footprint if you use only the resizable version.
Yes, I looked at that comment. It is not necessarily about the footprint. I just don't want to have trimming mean something different then "only get what you are using" and effectively not be removing unused code from the app's binaries. Also, my statement on the fact that more sizes are to be expected to come available for more icons remain. Eventually, that could lead to a different footprint story.

> I must admit I don't understand the logic behind the "We will not offer devs options to use other sizes than those offered through the Fluent System Icon collection" statement and merging the WithSize() PR. Not saying you shouldn't merge it. Simply that you are already allowing for resize through ToMarkup and now WithSize. Only these two ways of dealing with sizing are not aligned with you requirement of "not serving a crappy version of an Icon".

You got a point there on the resizing. It is unrelated to what I meant with the crappy version, though. What I mean by that is that I do not want to serve a compressed/altered 24px version if a 16px version is requested and an original 16px version is available. If a developer decides to do that regardless, that that is on him/her.
So trying to re-word my train of tought. I think we can offer different custom sizes of icons, but not always. So when using an IconStart or IconEnd, only a specific size (or perhaps group of sizes) is perscribed. This to ensure our stuff does not break and it looks good by default. 

> The change I'm proposing is only making this easier to work with and ensures you get the best icon for the size you request without breaking anything or compromising on trimming.
See my earlier remark on trimming. We are compromising if we leave unused icons in there.
 
> If you feel like it, you can have an look a the code in the reverted commit and see for yourself.
I will definitely take another look!

**Comment by EricOnGit** [comment]
> > 1. I don't know where the "breaking change" part is coming from but this is **not a breaking change** in any way.
> 
> Ok, non-breaking was a poor choice of words here. I know you went through lengths not to break stuff. What I meant was, "can we have the extension methods without changing the current way the icons are declared (and keeping the current generation process)

Unfortunately, I have no idea how we could achieve that without making it worst with reflection or reverting to dynamic code generation at compile time (something like what is possible with json serializer) but that would be a massive overhaul.
BTW, the generation process is already done and part of the reverted commit.

> 
> > 2. I also checked that trimming wasn't an issue (see comment just before yours) you actually get a smaller footprint if you use only the resizable version.
> >    Yes, I looked at that comment. It is not necessarily about the footprint. I just don't want to have trimming mean something different then "only get what you are using" and effectively not be removing unused code from the app's binaries. Also, my statement on the fact that more sizes are to be expected to come available for more icons remain. Eventually, that could lead to a different footprint story.
> 
> > I must admit I don't understand the logic behind the "We will not offer devs options to use other sizes than those offered through the Fluent System Icon collection" statement and merging the WithSize() PR. Not saying you shouldn't merge it. Simply that you are already allowing for resize through ToMarkup and now WithSize. Only these two ways of dealing with sizing are not aligned with you requirement of "not serving a crappy version of an Icon".
> 
> You got a point there on the resizing. It is unrelated to what I meant with the crappy version, though. What I mean by that is that I do not want to serve a compressed/altered 24px version if a 16px version is requested and an original 16px version is available. If a developer decides to do that regardless, that that is on him/her. So trying to re-word my train of tought. I think we can offer different custom sizes of icons, but not always. So when using an IconStart or IconEnd, only a specific size (or perhaps group of sizes) is perscribed. This to ensure our stuff does not break and it looks good by default.

This is still available and possible with the proposed change. 
> 
> > The change I'm proposing is only making this easier to work with and ensures you get the best icon for the size you request without breaking anything or compromising on trimming.
> 
> See my earlier remark on trimming. We are compromising if we leave unused icons in there.

I beg to differ here. From my perspective, adding new constructors for every icon size, is more of a compromise. I've rarely seen projects where only a single size of an icon was used. But this is futile since we're talking a couple bytes in either direction. 
And honestly, the designers would serve everyone better by adding new icons instead of adding sizes. Sorry for the mini rant here 😉

> 
> > If you feel like it, you can have an look a the code in the reverted commit and see for yourself.
> 
> I will definitely take another look!
Let me know if you need to discuss in further details.

**Comment by vnbaaij** [comment]
> Unfortunately, I have no idea how we could achieve that without making it worst with reflection or reverting to dynamic code generation at compile time (something like what is possible with json serializer) but that would be a massive overhaul. BTW, the generation process is already done and part of the reverted commit.

I've used source generators for the V2 version of the Icon implementation and that was working very well, so could be an opion again. You say you have the generation process done, but that is with the 'all icon siz variants in one', right? Because that is not how I want it.

> This is still available and possible with the proposed change.

Ok, maybe good then to get that PR up then and see if/how/what we could/want to use?
 
> I beg to differ here. From my perspective, adding new constructors for every icon size, is more of a compromise. I've rarely seen projects where only a single size of an icon was used. But this is futile since we're talking a couple bytes in either direction. And honestly, the designers would serve everyone better by adding new icons instead of adding sizes. Sorry for the mini rant here 😉
> 
Again, it is not about the bytes. I'm not going to compromise on the trimming part. Not used for me means not in the trimmed result. And we aren't limiting any project to use only one size of an icon with the current implementation in any way, are we?

Rant all you want on the design choices 😀.  I'm guessing they have their reasons for doing it like that (you could raise an issue in the repo over there to see what they come back with)

> Let me know if you need to discuss in further details.
We are willing to incorporate changes, but not just for the sake of changes alone. Trimming should still remove everything not used and we do not want multiple sizes in one object. I don't want to sound negative, but I don't really see the value of doing all these changes and in the end the developer can then do `Icons.Filled.ArrowCircleDown(i)` (where a value for i needs to be provided) as oposed to `Icons.Filled.Size24.ArrowCircleDown()`.

**Comment by EricOnGit** [comment]
I guess if you don't see the value, there's no point in wasting more time on this then.
