### ISSUE TITLE
fix: using comma as decimal seperator doesn't work neither does the dot in NumberField

### ISSUE THREAD

**Issue by GamingMaker** [microsoft/fluentui-blazor#1127]
# 🐛 Bug Report

Hi i'm quite new to the framework so sorry for any mistake by my side :)
I'm having problems regarding the NumberField. This includes two problems:

First, in Germany we use the comma (,) to seperate decimals in doubles etc.
For example: 14,25€
The Problem is: this doesn't work in the number field at all. I can't even place the comma. Is this a bug or just a feature that's not implemented?
Another problem: even if i'm using the dot to seperate (e.g. 14.25 €) the field doesn't work:

![image](https://github.com/microsoft/fluentui-blazor/assets/74767030/7d354fef-c6d2-44cf-b302-e7b015246891)

It's german but it states: "Enter a valid value. The next valid values are 145 and 146.

Is it just me being too unexperienced and stupid or is it some kind of bug? Thanks in advance :)

## 💻 Repro or Code Sample

`        <div class="mb-1">
            <FluentNumberField  @bind-Value="@mEditArticleData.Price" Label="Price" Appearance="@FluentInputAppearance.Filled" Class="w-full" />
            <ValidationMessage For="@(() => mEditArticleData.Price)" />
        </div>
 `

The "mEditArticleData.Price" is a decimal.

## 🤔 Expected Behavior

Should let me use a (,) and generally work.

## 😯 Current Behavior

Doesn't work, look at description.

## 💁 Possible Solution

I have no idea unfortunately as i'm quiete new.

## 🔦 Context

Trying to use this field in an EditForm to provide a price input for an article.

## 🌍 Your Environment

Windows 11 Enterprise
Visual Studio 17.8.3
.NET 7.0

**Comment by vnbaaij** [comment]
Hallo (und Wilkommen!),

The issue with not being able to use a comma as a separator is not a bug in this library. The underlying html input component is notoriously bad and just does not support that with all browsers across the board (some might support it).

I strongly advice you to not use a NumberField for this kind of input (i.e. a price). See also https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

So if you can get past that and use a '.' as a separator, then you need to make sure the `Step` parameter is set to the resolution that you wanr the value tbe be increased/decreased with. In your example you provide 145.15, so your step value should be set to "0.01" or "0.05". Then validation should pass

**Comment by GamingMaker** [comment]
Thank you very much, this helped me a lot.
Greetins to the Netherlands and have a nice day!
