### ISSUE TITLE
feat: Add Support for Integers in OptionValue for FluentSelect and FluentComboBox

### ISSUE THREAD

**Issue by bianwenbo** [microsoft/fluentui-blazor#1133]
# 🙋 Feature Request

I would like to request the addition of support for integers in the `OptionValue` property for Fluent UI Blazor's `FluentSelect`, `FluentComboBox`, and similar controls. Currently, these controls only support `string` and `Enum` formats for `OptionValue`. 

## 🤔 Expected Behavior

The expected behavior is that the `OptionValue` property should also accept integer (`int`) values in addition to the existing `string` and `Enum` formats.

## 😯 Current Behavior

Currently, these controls only allow for `string` and `Enum` formats as the `OptionValue`. When working with data retrieved from a database, it is common for the ID field to be of integer (`int`) format. This limitation forces developers to perform cumbersome conversions between `int` and `string` formats, which can be inconvenient.

## 💁 Possible Solution

A possible solution would be to enhance the `FluentSelect` and `FluentComboBox` controls to support `int` values directly as the `OptionValue`. This enhancement would simplify data binding and manipulation when working with integer-based IDs.

### What Are You Trying to Accomplish?

I am trying to improve the usability of Fluent UI Blazor controls when working with data that has integer-based IDs.

### How Has Not Having This Feature Affected You?

The absence of support for integer-based `OptionValue` has made it more challenging to work with data from a database where the IDs are typically integers.

### What Alternatives Have You Considered?

As an alternative, developers currently have to manually convert between `int` and `string` formats when using these controls, which is not an efficient solution.

## 💻 Examples

Examples of how this feature would be used:

```csharp
<FluentSelect TItem="MyModel" @bind-Value="selectedItemId" OptionValue="@(item => item.Id)" OptionText="@(item => item.Name)" Data="items" />

<FluentComboBox TItem="MyModel" @bind-Value="selectedItemId" OptionValue="@(item => item.Id)" OptionText="@(item => item.Name)" Data="items" />
```

In the examples above, `OptionValue` is specified to directly use the `Id` property of the `MyModel` class, which is an integer. This enhancement would make it easier to work with integer-based IDs in these controls.

Your feedback and any alternative implementation suggestions are greatly appreciated. Thank you!

**Comment by dvoituron** [comment]
Indeed, it could be interesting.

**Comment by vnbaaij** [comment]
Interesting, yes. But the vale of the internal html <option> elements is always a string (text)...(see https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element)

**Comment by dvoituron** [comment]
Indeed. And we always have a reference to the selected object via `@bind-SelectedOption`.

**Comment by bianwenbo** [comment]
> Interesting, yes. But the vale of the internal html elements is always a string (text)...(see https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element)

As per HTML standards, element values are always treated as strings since HTML primarily deals with text-based user input.

In the context of frameworks like Fluent UI Blazor, developers often handle server data, which may include integer IDs. While HTML requires string values, it's feasible for the framework to handle internal type conversions, making it easier for developers to work with integer IDs.

The feature request suggests enhancing Fluent UI Blazor to directly support integers as OptionValue, reducing the need for manual type conversions in code.

In essence, despite HTML's string-centric nature, frameworks can streamline the handling of integer IDs for developers, improving development efficiency and code readability.

**Comment by vnbaaij** [comment]
We'll see what we can do!

**Comment by dvoituron** [comment]
I agree with you, this is an improvement that could be useful, but is not blocking at present, since you have to send **objects** to the list and it is possible to retrieve an instance of the selected object `SelectedOption`. 

This only simplifies writing, but does not improve performance or memory management.

**Comment by bianwenbo** [comment]
> I agree with you, this is an improvement that could be useful, but is not blocking at present, since you have to send **objects** to the list and it is possible to retrieve an instance of the selected object `SelectedOption`.
> 
> This only simplifies writing, but does not improve performance or memory management.

Thank you for your reply and guidance.

### Current Approach
Let me explain my situation:
First, I create a data source by retrieving Id and Name fields from the database and store them in a dictionary. Then, I connect FluentSelect's OptionValue to the dictionary's Key and OptionText to its Value.
Ideally, I'd like to bind @bind-Value directly to the ForeignId property of the target object. However, I've noticed that FluentSelect works with strings, which necessitates the following steps:
1. Converting the dictionary's index to a string format.
2. Creating an extra variable called TempStringId and binding @bind-Value to TempStringId.
3. Initializing TempStringId with ForeignId.ToString().
4. Finally, converting TempStringId to an integer and assigning it to the ForeignId property of the target object.

### Issue
While this approach meets my requirements, it introduces extra conversions and a temporary variable, which adds unnecessary complexity.

## SelectedOption
Regarding the SelectedOption you mentioned, I'm still uncertain about how to address this problem—how to keep the selected option synchronized with the ForeignId when working with external keys. Any guidance you can offer would be much appreciated.

**Comment by dvoituron** [comment]
Why not have code like this: using only a SelectedItem variable that holds the object (key/value or other) selected by the user.

⚠️ The list of items must be in `Items` attribute (and not `Data`, like in your example).

```razor
<p>
    SelectItem: @SelectedItem?.Id - @SelectedItem?.Name
</p>

<FluentSelect @bind-SelectedOption="SelectedItem"
              Items="Items"
              OptionText="@(item => item?.Name)" />

@code
{
    MyModel? SelectedItem;

    // Sample Data
    IEnumerable<MyModel> Items = Enumerable.Range(1, 10).Select(i => new MyModel(i, $"Name {i}"));

    // Sample Model
    record MyModel(int Id, string Name);
}
```

`MyModel` could be replaced by a Dictionary or another object.

```razor
<p>
    SelectItem: @SelectedItem.Key - @SelectedItem.Value
</p>

<FluentSelect @bind-SelectedOption="SelectedItem"
              TOption="KeyValuePair<int, string>"
              Items="Items"
              OptionText="@(item => item.Value)" />

@code
{
    KeyValuePair<int, string> SelectedItem;

    // Sample Data
    Dictionary<int, string> Items = Enumerable.Range(1, 10).ToDictionary(i => i, i => $"Name {i}");
}
``` 

![peek](https://github.com/microsoft/fluentui-blazor/assets/8350694/fccf472e-e473-4d0b-9c8a-d3401eaf4074)

**Comment by bianwenbo** [comment]
> Why not have code like this: using only a SelectedItem variable that holds the object (key/value or other) selected by the user.
> 
> ⚠️ The list of items must be in `Items` attribute (and not `Data`, like in your example).
> 
> ```
> <p>
>     SelectItem: @SelectedItem?.Id - @SelectedItem?.Name
> </p>
> 
> <FluentSelect @bind-SelectedOption="SelectedItem"
>               Items="Items"
>               OptionText="@(item => item?.Name)" />
> 
> @code
> {
>     MyModel? SelectedItem;
> 
>     // Sample Data
>     IEnumerable<MyModel> Items = Enumerable.Range(1, 10).Select(i => new MyModel(i, $"Name {i}"));
> 
>     // Sample Model
>     record MyModel(int Id, string Name);
> }
> ```
> 
> `MyModel` could be replaced by a Dictionary or another object.
> 
> ```
> <p>
>     SelectItem: @SelectedItem.Key - @SelectedItem.Value
> </p>
> 
> <FluentSelect @bind-SelectedOption="SelectedItem"
>               TOption="KeyValuePair<int, string>"
>               Items="Items"
>               OptionText="@(item => item.Value)" />
> 
> @code
> {
>     KeyValuePair<int, string> SelectedItem;
> 
>     // Sample Data
>     Dictionary<int, string> Items = Enumerable.Range(1, 10).ToDictionary(i => i, i => $"Name {i}");
> }
> ```
> 


Thank you for your reply and the code examples. From your response, I understand that we can obtain the selected item and then use its key (the `int` object).

Let me clarify my thoughts: In some cases, we don't need an intermediary variable (like the previously mentioned `TempStringID` or the `SelectedItem.Key` you referred to).

Consider this scenario: We have loaded an entity `A`, which includes a foreign key property `EntityBId`. Now we want to change this value using a dropdown list.

Using an intermediary variable, we would need to:
1. Initialize the selected item by assigning the value of `EntityBId` to the intermediary variable.
2. On selecting a new item, update `EntityBId` with the value from the intermediary variable.

In other words, `TOption` is not a property of entity `A` (when using `@bind-SelectedOption`), or `OptionValue` does not natively support the `int` property of an entity (when using `@bind-Value`). This necessitates synchronization between the two.

Since `OptionValue` natively supports the `string` field, the property `StringKey` of entity `A` can completely avoid the use of an intermediary variable in the following way:

```csharp
Dictionary<string, string?>? productsDict;
<FluentSelect Items=@productsDict
              OptionValue="@(i => i.Key)"
              OptionText="@(i => i.Value)"
              @bind-Value="@A.StringKey">
</FluentSelect>
```

Given that the `Id` object (of `int` type) is a common property column in relational databases, I believe it's quite necessary to have `OptionValue` natively support the `int` field, thereby avoiding the need for an intermediary variable.

**Comment by bianwenbo** [comment]
For those who encounter a similar issue, you can use the following code:

```csharp
Dictionary<int, string?>? productsDict;
<FluentSelect Items=@productsDict
              OptionValue="@(i => i.Key.ToString())"
              OptionText="@(i => i.Value)"
              Value="@Entity.ForeignId.ToString()" 
              ValueChanged="@(e => Entity.ForeignId = int.Parse(e))">
</FluentSelect>
```

This code provides a perfect solution to the discussed issue.

In conclusion, I want to convey my appreciation to the developers for their valuable guidance and dedicated efforts.

**Comment by Ducki** [comment]
I'm still struggling using this in a Server Side Rendered scenario in Blazor 8.

Within an `EditForm` I need to "bind" the value of the `Select` to an `int` field in the DTO, because that's what the server accepts.
How to I have the Select actually submit this?

**Comment by vnbaaij** [comment]
You will need the `Value` and `ValueChanged` as mentioned above. It can not work with SSR...
