### ISSUE TITLE
feat: Need TextBox type that capable of handling visibility for Password

### ISSUE THREAD

**Issue by KrishnaKumar-1409** [microsoft/fluentui-blazor#1135]
# 🙋 Feature Request
Need TextBox type that capable of handling visibility for Password

**Comment by vnbaaij** [comment]
Sorry, but that is something you would need to implement for yourself. We use the standard browser behavior for this.

If the look and feel is important for you, you could try to start with subclassing our `FluentTextField` component

**Comment by gryzorr** [comment]
Do You mean that this behavior is by design (browser behavior)?
https://github.com/user-attachments/assets/6e1d1d1f-b53c-426a-b4be-3674d40ff5bd

**Comment by dvoituron** [comment]
This feature is integrated into certain browsers. For example, in Edge.
![peek_4](https://github.com/user-attachments/assets/dd5008e8-7780-4679-8bd2-e09bf4da4c3e)

If you need to have this feature always, you need to implement it manually as Vincent suggested.

**Comment by vnbaaij** [comment]
You can't have it display the value anymore once the text field has lost focus. That is default browser behavior:
![password2](https://github.com/user-attachments/assets/55fe28d2-916e-4405-b6bb-e2352961c753)
