### ISSUE TITLE
fix: documented workaround for Blazor Hybrid bug no longer works in v4.2.0

### ISSUE THREAD

**Issue by chrisrolliston** [microsoft/fluentui-blazor#1137]
# 🐛 Bug Report

Following [the documentation](https://github.com/microsoft/fluentui-blazor#tempory-workaround-for-maui-issues), an underlying bug in Blazor Hybrid that meant the Fluent visuals weren't applied in a MAUI/WinForms/WPF app could be worked around by directly referencing `initializersLoader.webview.js` in a script tag. This no longer works in v4.2.0 due to the refactoring of `initializersLoader.webview.js` (which no longer exists).

## 💻 Repro or Code Sample

Follow the [general docs for creating a WinFoms Blazor app](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-8.0), with these changes:

- Don't bother creating css/app.css
- Add a reference to the Fluent UI library **v4.1.1**
- In Form1.cs, include a call to AddFluentUIComponents
- Make the content of Content.razor just this:

```
@using Microsoft.FluentUI.AspNetCore.Components

<FluentButton>Click Me!</FluentButton>
```

- Make the content of Index.html this:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WinFormsBlazor</title>
    <base href="/" />
    <link href="WinFormsBlazor.styles.css" rel="stylesheet" />
</head>

<body>

    <div id="app">Loading...</div>

    <script app-name="WinFormsBlazor" src="/_content/Microsoft.FluentUI.AspNetCore.Components/js/initializersLoader.webview.js"></script>
    <script src="_framework/blazor.webview.js"></script>
</body>
</html>
```
- Run the application; as expected, the Click Me! button shows in the Fluent UI style
- Update the Nugat reference to v4.2.0, and rerun
- This time, the button does not have the Fluent UI style

## 🤔 Expected Behaviour

Fluent UI style used.

## 😯 Current Behaviour

Only the app.css styles are applied, the Fluent UI visuals themselves are not.

## 💁 Possible Solution

Don't know, maybe something else needs to be referenced, if so this is just a documentation bug! Also obviously it would be best for all if the underlying bug in Blazor Hybrid was fixed :-)

## 🔦 Context

Breaks use of the library in any Blazor Hybrid app.

**Comment by vnbaaij** [comment]
We are having an issue with getting the `initializersLoader` script in the 4.2.0 package. Working on it...

**Comment by vnbaaij** [comment]
In v4.2.1 the original instructions will be applicable again. Already changed the docs back. We will release the update in the next couple of days.

**Comment by vnbaaij** [comment]
In the mean time, you can create a local version of that file in your project and link to that in the script file. Contents of the file is here: https://github.com/microsoft/fluentui-blazor/blob/dev/src%2FCore%2Fwwwroot%2Fjs%2FinitializersLoader.webview.js

**Comment by chrisrolliston** [comment]
Nice, thanks!

**Comment by vnbaaij** [comment]
Closing this as workaround for current version is documented on the sirte and next version will have the file in original location again.
