### ISSUE TITLE
feat: Enhance FluentDialog in Fluent UI Blazor for Multi-Parameter Support

### ISSUE THREAD

**Issue by bianwenbo** [microsoft/fluentui-blazor#1139]
# 🙋 Feature Request

This request is to enhance the `FluentDialog` component in Fluent UI Blazor to support the passing of multiple parameter objects.

## 🤔 Expected Behavior

Ideally, `FluentDialog` should allow for the easy and intuitive passing of multiple parameters. This enhancement would align with the flexibility offered by typical Blazor components, where multiple parameters can be declared and passed directly in the markup:

```html
<FluentDialog Content="" A="" B="" />
```

## 😯 Current Behavior

Currently, in Fluent UI Blazor, the `FluentDialog` is introduced in the `MainLayout.razor` main section using `<FluentDialogProvider />` and then invoked in code using the `DialogService.ShowDialogAsync` method. However, it is unclear or not straightforward to pass multiple parameter objects to the `FluentDialog` component in this implementation.

## 💁 Possible Solution

A possible solution could be to enhance the `DialogService.ShowDialogAsync` method to accept multiple parameters, possibly in the form of a dictionary or an object that can encapsulate all the required parameters. 

## 🔦 Context

This feature is crucial for scenarios where a dialog needs to display or manipulate complex data involving multiple objects or entities. The current limitation requires workarounds or restructuring of data, which can be cumbersome and counterintuitive.

## 💻 Examples

Here's an example of how parameters are currently declared within a `FluentDialog` component:

```csharp
@code {
    [Parameter]
    public SimplePerson Content { get; set; } = default!;

    [Parameter]
    public SampleEntity A { get; set; }

    [Parameter]
    public List<string> B { get; set; }

    [CascadingParameter]
    public FluentDialog Dialog { get; set; } = default!;

    private async Task SaveAsync()
    {
        await Dialog.CloseAsync();
    }
}
```

In contrast, the typical implementation in a standard Blazor scenario allows for direct parameter passing within the component declaration:

```html
<FluentDialog Content="" A="" B="" />
```

**Comment by vnbaaij** [comment]
Hi,

This is not something we are going to implement. We already have a solution for it with the generic `ShowDialog...` methods which allows you to pass any kind of datastructure to the dialog. See also `IDialogContentComponent<T>` and the `SimpleDialog<SimplePerson>` example in the demo site. You are in control of what goes into that SimplePerson object (which can be named as you want and can contain anything)

Besides, with your proposal how would you envison A and B to be defined. They would always need a `[Parameter]...` implementation in code to be usabale as a parameter on the component. You can't just arbitrarilt thow things into a component.

**Comment by bianwenbo** [comment]
Thanks.

Certainly, based on your advice, I think I can encapsulate multiple parameters into an object and then pass this object as a parameter, and then use its contents.

**Comment by vnbaaij** [comment]
Yes, that is exactly how we envisioned it!

**Comment by Stroomtang** [comment]
For those who are looking for an easy solution: you can pass multiple parameters by creating and using [tuples](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples). You can create and show the dialog while passing multiple objects/parameters like this:
`var dialog = await DialogService.ShowDialogAsync<DialogName>((object1, object2), new DialogParameters());`

In the dialog code you use `@implements IDialogContentComponent<(object1Type Object1Name, object2Type Object2Name)>` and assign the passed parameter to Content: `[Parameter] public (object1Type Object1Name, object2Type Object2Name) Content { get; set; }`
In the dialog you can now use `Content.Object1Name` and `Content.Object2Name`.

For reading the resultdata of your dialog you can use `(((object1Type Object1Name, object2Type Object2Name))result.Data).Object1Name` (mind the double brackets ((, these are needed for tuple casting).

**Comment by vnbaaij** [comment]
That is a solution as well, but I don't think it is easier than just defining a class or record and passing that in as the generic parameter of `IDialogContentComponent`
