### ISSUE TITLE
fix: Wrap components with/without parent should be reconsidered in Design

### ISSUE THREAD

**Issue by Kumima** [microsoft/fluentui-blazor#1143]
# 🐛 Bug Report

Relative button size will break if there is no IconStart/End in FluentButton.

## 💻 Repro or Code Sample

```razor
<FluentButton Style="width: 70%"
              Appearance="Appearance.Accent"
              Loading="@_loading"
              OnClick="@StartLoadingAsync">
    Load
</FluentButton>

@code {

    bool _loading = false;

    async Task StartLoadingAsync()
    {
        _loading = true;
        await Task.Delay(TimeSpan.FromSeconds(5));
        _loading = false;
    }
}
```

## 🤔 Expected Behavior

The size should not change.

## 😯 Current Behavior

The size will break, since it's wrapped by a span.

## 💁 Possible Solution
Check the [source](https://github.com/microsoft/fluentui-blazor/blob/f2842ccc2ead924b331c06b7b040a2d2224ec802/src/Core/Components/Button/FluentButton.razor#L11) 
```razor
@if (Loading && IconStart == null && IconEnd == null)
{
    <span class="loading-button">
        @_renderButton
        <FluentProgressRing />
    </span>
}
//The button is wrapped by another element, which will break whole things. Wrap like that should not be designed.
//It makes the lib hard to use.
```

### Related:
```razor
//For FluentTextField.razor
<FluentInputLabel ForId="@Id" Label="@Label" AriaLabel="@AriaLabel" ChildContent="@LabelTemplate" Required="@Required" />
<fluent-text-field @ref=Element>
    @ChildContent
</fluent-text-field>

//There is no parent wrap for this. The label position is not relative to field.
//If we apply position on parent, the label position will break. It is centered as well. 
<FluentStack
    Orientation="Orientation.Vertical"
    HorizontalAlignment="HorizontalAlignment.Center"
    VerticalAlignment="VerticalAlignment.Center">
        <FluentTextField Style="width: 100%" Label="Email"/>
        <FluentTextField Style="width: 100%"Label="Password"/>
    <FluentButton Type="ButtonType.Submit" Style="width: 70%" Loading="_isProcessing">Login</FluentButton>
</FluentStack>
//We have to add another wrapper on the `FluentTextField` to make it works.
```
![image](https://github.com/microsoft/fluentui-blazor/assets/93973732/c5fb53a3-1264-44b8-aa6d-c9dea082d147)

## 🔦 Advice
As what I understand:
One razor Component should always have a root element. Style and class apply to the razor component, should always apply to the core element which is mostly a fluent UI web component. This rule is applied well for most components, but I think it should be consistent for all.
Maybe I'm wrong, but I'd like to discuss it.
## 🌍 Your Environment

Microsoft Edge/Win11/.NET8

**Comment by vnbaaij** [comment]
The wrapping of the button is only the case when you want to have a Loading button. We'll take a look OT the examples you provided to see how we can prevent it from breaking the size but for this specific case the wrap is needed.

With regards to the TextField, the Label parameter is offered as a convenience and makes it easier to build regular left (or right) aligned forms. If you want /need more fine grained control, you can use separate FluentInputLabel components (and don't set a value for Label)

**Comment by dvoituron** [comment]
@vnbaaij I'm trying to find a solution for this particular case where no icon is used in a loading button.
It's not perfect, but it's the only solution, I think, by applying the button style to the parent span style. If this isn't sufficient, I'd suggest removing this loading feature (the progress ring) if there's no icon (start/end) in the button.

See PR: https://github.com/microsoft/fluentui-blazor/pull/1146
