### ISSUE TITLE
How can i change the color of menu button

### ISSUE THREAD

**Issue by Amine-Smahi** [microsoft/fluentui-blazor#1145]
Hi, i want to change the color of the menu button,
there is no detail on how can i do that in the documentation,

https://www.fluentui-blazor.net/MenuButton

![image](https://github.com/microsoft/fluentui-blazor/assets/24621701/97b6b1c9-b0dd-4682-953a-d257c28fdd69)

version : 4.2.0

**Comment by dvoituron** [comment]
You could use this code:

```razor
<style>
    .fluent-menubutton-container fluent-button::part(control) {
        background: red;
    }
</style>
```

**Comment by Amine-Smahi** [comment]
@dvoituron  sadly it didnt work :(

**Comment by Amine-Smahi** [comment]
Hi @vnbaaij, happy new year, the code your provided only work on chromium based browsers, is there a way to conveniently change it through a parameter
