### ISSUE TITLE
fix: FluentDesignTheme not working in Blazor Hybrid (WPF)

### ISSUE THREAD

**Issue by NguyenLamMS** [microsoft/fluentui-blazor#1150]
# 🐛 Bug Report

I use FluentDesignTheme in Blazor Hybrid (WPF) I get error 
**Cannot read properties of undefined (reading 'readLocalStorage')**
I tried on blazor webassembly project and it works, it just throws error in Blazor Hybrid App

## 💻 Repro or Code Sample

`<FluentDesignTheme @bind-Mode="@Mode" @bind-OfficeColor="@OfficeColor" StorageName="theme" />`

## 😯 Current Behavior

![Screenshot 2023-12-18 171111](https://github.com/microsoft/fluentui-blazor/assets/23271775/7871d570-1419-496e-bc24-e471c40e1661)

**Comment by dvoituron** [comment]
Is this the same issue as #1130?
