### ISSUE TITLE
Data grid not sorting

### ISSUE THREAD

**Issue by f4n0** [microsoft/fluentui-blazor#1166]
# 🐛 Bug Report
I'm using the fluentData grid, but even if I have set on the PropertyColumn the sortable to true, the header are not sortable (If i click them, nothing happens)

## 💻 Repro or Code Sample
```
@page "/List"
@using MyApplication.Data

<PageTitle>List Page</PageTitle>

<FluentDataGrid Items="@mock" TGridItem="Mock" ResizableColumns="true">
    <PropertyColumn Property="@(p => p.Id)" Sortable="true" />
    <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
    <PropertyColumn Property="@(p => p.Description)" Sortable="true" />
    <PropertyColumn Property="@(p => p.OrderDate)" Format="yyyy-MM-dd" Sortable="true" />
    <PropertyColumn Property="@(p => p.Price)" Sortable="true" />
</FluentDataGrid>

@code {
    static List<Mock> tmp = Mock.getMultipleMock();
    IQueryable<Mock> mock = tmp.AsQueryable();


    protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);
        
    }
}
```

## 🤔 Expected Behavior
The sorting must be enabled

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC] Windows
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox] Edge
* .NET and FAST Version [e.g. 1.8.0] NET 8, FluentUI 4.2.0

**Comment by vnbaaij** [comment]
You are most probably in SSR mode and have not enabled interactivity for the site or component
