### ISSUE TITLE
fix: Tabs tablist will forever expand despite the tab containers width

### ISSUE THREAD

**Issue by pingu2k4** [microsoft/fluentui-blazor#1168]
# 🐛 Bug Report

If you have too many tabs, the list of tabs along the top will expand forever, claiming more and more horizontal space irrespective of the width contraints of the Tabs container

## 💻 Repro or Code Sample

The "dynamic" example in the demo site has this issue. Keep adding tabs and you will see that they just extend off the end. https://www.fluentui-blazor.net/Tabs

## 🤔 Expected Behavior

Tabs should stop and instead display the overflow for any tabs overflowing. 

## 😯 Current Behavior

The tab list expands forever
![image](https://github.com/microsoft/fluentui-blazor/assets/11229848/b61d73b9-2a03-473c-b07e-b496d36e56af)

## 🔦 Context

If a user displays too many tabs, the overflow will not kick in.

## 🌍 Your Environment

Windows, latest Chrome

**Comment by vnbaaij** [comment]
Overflow kicks in on resize of the window. We;ll see if we can make that work better.

**Comment by dvoituron** [comment]
Will be fixed with #1172
