### ISSUE TITLE
fix: Matched [FluentNavLink] renders with background that does not have rounded corners

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui-blazor#1169]
# 🐛 Bug Report

Have a look at these corners
![image](https://github.com/microsoft/fluentui-blazor/assets/2365592/cbc4d519-f416-4911-a051-ebe16562cf96)

## 💻 Repro or Code Sample

1. Create a project from the FluentBlazor template
2. Run

## 🤔 Expected Behavior

No dark corners

## 😯 Current Behavior

Dark corners

## 🌍 Your Environment

* OS & Device: Windows 10 22H2 x64
* Browser Microsoft Edge 120
* .NET 8.0 and FAST 4.2

**Comment by vnbaaij** [comment]
Managed to sbag this one in at the last moment. Fixed in 4.2.1

**Comment by xperiandri** [comment]
Cool, thanks!
