### ISSUE TITLE
fix: [`FluenNavGroup`] does not work (display sub-items) when a `FluentNavMenu` is collapsed

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui-blazor#1171]
# 🐛 Bug Report

[Watch the screen recording](url)

https://github.com/microsoft/fluentui-blazor/assets/2365592/dba2d833-0eee-424a-9b46-34f2d653066d

## 💻 Repro or Code Sample

``` Razor
<nav>
    <FluentNavMenu Width="250" Collapsible="true" Title="Custom navigation menu" Text="Home">
        <FluentNavGroup Href="/" Match="NavLinkMatch.All" Icon="@Icon.FromImageUrl("/images/home.svg")" IconColor="Color.Accent">
            <FluentNavLink Href="/" Match="NavLinkMatch.All" Icon="@Icon.FromImageUrl("/images/home.svg")" IconColor="Color.Accent">Home</FluentNavLink>
            <FluentNavLink Href="counter" Icon="@Icon.FromImageUrl("/images/counter.svg")" IconColor="Color.Accent">Counter</FluentNavLink>
        </FluentNavGroup>
        <FluentNavLink Href="/" Match="NavLinkMatch.All" Icon="@Icon.FromImageUrl("/images/home.svg")" IconColor="Color.Accent">Home</FluentNavLink>
        <FluentNavLink Href="counter" Icon="@Icon.FromImageUrl("/images/counter.svg")" IconColor="Color.Accent">Counter</FluentNavLink>
        <FluentNavLink Href="weather" Icon="@Icon.FromImageUrl("/images/weather.svg")" IconColor="Color.Accent">Weather</FluentNavLink>
    </FluentNavMenu>
</nav>
```

## 🤔 Expected Behavior

`FluentNavGroup` sub-items and `Text` appear in a popup aside of the `FluentNavGroup` icon

## 😯 Current Behavior

`FluentNavGroup` sub-items do not render at all

## 🌍 Your Environment

* OS & Device: Windows 10 22H2 x64
* Browser Microsoft Edge 120
* .NET 8.0 and FAST 4.2.0

**Comment by vnbaaij** [comment]
Hi,

This is not a bug. The FluentNavMenu is not designed to have a pop-up submenu like what you see in Azure DevOps.

It can be configured to automatically open if an icon is clicked while the menu is collapsed:
![navmenu-1171](https://github.com/microsoft/fluentui-blazor/assets/1761079/ab30b254-4e7a-40ba-82f6-b5d615b6baaf)

**Comment by xperiandri** [comment]
Should I create a new feature request?

**Comment by vnbaaij** [comment]
No, this is not something we have plans for. It would mean a complete overhaul of the components involved because we the need to start working with popovers and such
