### ISSUE TITLE
Templates v4.2.1: type="image/png" -> type="image/x-icon"

### ISSUE THREAD

**Issue by JeepNL** [microsoft/fluentui-blazor#1173]
Templates v4.2.1 
(dotnet new install Microsoft.FluentUI.AspNetCore.Templates::4.2.1)

In `App.razor`

There's this line:
`<link rel="icon" type="image/png" href="favicon.ico" />`

And I think it should be:
`<link rel="icon" type="image/x-icon" href="favicon.ico">`

**Comment by vnbaaij** [comment]
Good catch! Will change it for next release.
