### ISSUE TITLE
fix: missing image /images/authrequired.svg in template project Microsoft.FluentUI.AspNetCore.Templates.csproj

### ISSUE THREAD

**Issue by iwhp** [microsoft/fluentui-blazor#1174]
# 🐛 Bug Report

The image `/images/authrequired.svg` is missing in the template (4.2.1) project: `Microsoft.FluentUI.AspNetCore.Templates.csproj`

See source in [src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/Layout/NavMenu.razor](https://github.com/microsoft/fluentui-blazor/blob/83aa7bb4b593129fc18a22347c34d8870d1f6841/src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/Layout/NavMenu.razor#L21)

**Comment by iwhp** [comment]
This one is working
`<FluentNavLink Href="auth" Icon="@(new Icons.Regular.Size20.LockClosedKey())" IconColor="Color.Accent">Auth Required</FluentNavLink>
`
used in [src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Layout/NavMenu.razor](https://github.com/microsoft/fluentui-blazor/blob/83aa7bb4b593129fc18a22347c34d8870d1f6841/src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Layout/NavMenu.razor#L21)

This one is not working:
`<FluentNavLink Href="auth" Icon="@Icon.FromImageUrl("/images/authrequired.svg")" IconColor="Color.Accent">Auth Required</FluentNavLink>
`
used in [src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/Layout/NavMenu.razor](https://github.com/microsoft/fluentui-blazor/blob/83aa7bb4b593129fc18a22347c34d8870d1f6841/src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/Layout/NavMenu.razor#L21)

**Comment by vnbaaij** [comment]
We changed from included SVG's to using our own icon package. Apparently I missed one ☹️
Will fix it for the next release
