### ISSUE TITLE
docs: FluentPersona section in the Autocomplete page?

### ISSUE THREAD

**Issue by tg2648** [microsoft/fluentui-blazor#1178]
# 🙋 Documentation Request

Hello. Is there a reason for the `FluentPersona` section in the [Autocomplete](https://www.fluentui-blazor.net/Autocomplete) page? Unless I'm missing something, it's not actually related to the autocomplete functionality.

## 💁 Possible Solution

Removing the `FluentPersona` example and API documentation from the Autocomplete page. I can submit a PR.

**Comment by vnbaaij** [comment]
The reason is that the persona is being used as a template in the autocomplete example. So yeah, it is related.
We'll clarify the context a bit more with an update soon. Or you can take a stab at that with a PR?
