### ISSUE TITLE
fix: The project file .../FluentBlazorApp-SSR.csproj was not found

### ISSUE THREAD

**Issue by dromerolovo** [microsoft/fluentui-blazor#1179]
When running `dotnet build`  I'm getting the following error:  `C:\Program Files\dotnet\sdk\8.0.100\NuGet.targets(399,5): error MSB3202: The project file "D:\Dev\Test\FluentUI\fluentui-blazor\examples\SSR\FluentBlazorApp-SSR.csproj" was not found. [D:\Dev\Test\FluentUI\fluentui-blazor\Microsoft.FluentUI.sln]` 

So the mentioned project is registered in the solution:

`Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "ssr", "ssr", "{B188051D-4A12-4DE7-889B-7BAB9BF563E4}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "FluentBlazorApp-SSR", "examples\SSR\FluentBlazorApp-SSR.csproj", "{A5130D9A-CAE1-411A-9542-475DC1A817F4}"
EndProject`  but the project is not found in the repo.

The possible solution is removing the folder `ssr` and the project `FluentBlazorApp-SSR.csproj` and rebuild the solution. 

It's okay to delete the project from the solution for upcoming PRs? or is there a particular reason why the project is in the solution?

Environment:
.NET 8.0.100
Visual Studio Version 17.8.0 Preview 4.0

**Comment by vnbaaij** [comment]
Oops, I was moving around a new project (to validate templates) and had it at a few diffferent locations. Apparently some of it was left behind in the `.sln` file. Strange thing is VS is ot showing any building issues...

I've pushed a fix to the `dev` branch, so if you do a pull before push, you should be good to go
