### ISSUE TITLE
fix: RZ10012 / VS suggestion error for old package (Microsoft.Fast.Components.FluentUI) in new version 4.2.1 NET8

### ISSUE THREAD

**Issue by nicolasmohamed** [microsoft/fluentui-blazor#1180]
# 🐛 Bug Report

When using FluentUI v4.2.1 (NET8), Visual Studio 2022 shows RZ10012 error on FluentUI components and suggests adding a new @using Microsoft.Fast.Components.FluentUI, which is the previous namespace.

Tried deleting VS cache files, Roslyn cache, etc. but the issue is still there.

Project is running OK but no chance to code in razor files as Intellisense is broken.

## 💻 Repro or Code Sample

![blazor rz10012](https://github.com/microsoft/fluentui-blazor/assets/30346948/0c64a75e-d231-4544-b8a2-2201f0ec1a76)

![blazor-using](https://github.com/microsoft/fluentui-blazor/assets/30346948/6b48efed-c754-4fa1-8d67-63888b7b10a2)

![blazor project](https://github.com/microsoft/fluentui-blazor/assets/30346948/97d1fe4a-c2c4-4a8f-beac-a1e2cb34997e)

## 🤔 Expected Behavior

It should behave like previous version and Intellisense should work as always.

## 😯 Current Behavior

Intellisense is broken

![blazor code](https://github.com/microsoft/fluentui-blazor/assets/30346948/98449277-d927-4171-9afb-07800c2b2e77)

## 🔦 Context

Upgraded project from FluentUI v3.5.0 to v4.2.0
Changed @using Microsoft.Fast.Components.FluentUI to @using Microsoft.FluentUI.AspNetCore.Components

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Visual Studio 2022 v17.8.3
* .NET and FAST Version: NET 8 FluentUI v4.2.1

**Comment by dvoituron** [comment]
Could you try to clean your cached files?
1. Close Visual Studio
2. Delete `bin` and `obj` folder
3. Remove the folder `C:\Users\<user>\.nuget\packages\microsoft.fast.components.fluentui`
4. Restart Visual Studio and rebuild you project

**Comment by nicolasmohamed** [comment]
1. Removed C:\Users\<user>\.nuget\packages\microsoft.fast.components.fluentui and C:\Users\<user>\.nuget\packages\microsoft.fast.components.fluentui.icons folders.

2. Deleted bin and obj folders from client AND server projects

Now it's working as expected. Please add to Upgrade Guide (https://www.fluentui-blazor.net/UpgradeGuide). 

Thanks.

**Comment by vnbaaij** [comment]
Docs updated. See https://preview.fluentui-blazor.net/UpgradeGuide#upgrading-your-vs-solution-from-v3-to-v4

Will be deployed to regular site soon.
