### ISSUE TITLE
Nav Menu does not show link text when in mobile view port when menu was collapsed before resize

### ISSUE THREAD

**Issue by StephenOTT** [microsoft/fluentui-blazor#1183]
# 🐛 Bug Report

Using latest wasm template 4.2.1 on chrome.

If you collapse the menu:

<img width="807" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1994838/3716ef45-3aeb-4a67-8c21-1c72d7e51d36">

and then go to mobile sized:

<img width="508" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1994838/72dceced-61fa-45b4-8f56-e97faad163a0">

and open the menu:

<img width="511" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1994838/d43ff81d-bcd9-47bb-afa6-21e9d520a0c5">

We can see the text is missing on the links.

If we repeat the steps but have the menu opened before resize:

<img width="862" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1994838/4c4fd651-52b1-42ed-8c76-5b08cd244500">

we can see the link text:

<img width="504" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1994838/a98d8e48-c17f-476a-ad71-de8fd4e2d5c1">

This looks like the expanded boolean added in navmenu.razor is being kept after resize?

**Comment by vnbaaij** [comment]
Fixed in next release. See https://github.com/microsoft/fluentui-blazor/commit/353e1081af777bf3d1da9f447884b77624531ce1
