### ISSUE TITLE
fix: Collapse button doesn't work correctly in Fluent Blazor Web App template

### ISSUE THREAD

**Issue by shui106** [microsoft/fluentui-blazor#1185]
# 🐛 Bug Report

Collapse button doesn't work correctly in Fluent Blazor Web App template for SSR.

## 💻 Repro or Code Sample

Here is the initial setting for the template.
![image](https://github.com/microsoft/fluentui-blazor/assets/3031491/7630dc3b-6bd6-425b-8c66-0174ff3b6a77)
Steps to reproduce:
1. Run the project.
2. Click the collapse button. -- it works now
3. Click a menu item Home or Weather.
4. Click the collapse button again -- it doesn't work.

## 🤔 Expected Behavior

The collapse button should work every time.

## 😯 Current Behavior

The collapse button doesn't work correctly after some actions.

## 💁 Possible Solution

Need your help.

## 🌍 Your Environment

Win11 + .NET8 + VS2022

**Comment by vnbaaij** [comment]
PR submitted, will be fixed in next release.
