### ISSUE TITLE
fix: Active Indicator jumps to wrong place when adding tabs to tablist

### ISSUE THREAD

**Issue by pingu2k4** [microsoft/fluentui-blazor#1186]
# 🐛 Bug Report

When adding a tab to a tab list, the active indicator will slide all the way to the left before "pinging" to the new tab on the right. When that new tab is hidden it has been taken into the overflow, the active indicator will underline empty space, and push the active indicator further right than was intended.

## 💻 Repro or Code Sample

![image](https://github.com/microsoft/fluentui-blazor/assets/11229848/2d38af8e-b40b-4ee1-aca5-471b20d626f7)
The dynamic section in the demo shows this (look at the preview site, as this contains a fix for the overflow itself) https://preview.fluentui-blazor.net/Tabs

## 🤔 Expected Behavior

Active indicator should not push the overflow label over to the right, and when adding a tab it should not jump around as though it doesn't know where it should be.

## 😯 Current Behavior

https://github.com/microsoft/fluentui-blazor/assets/11229848/5f87dae4-4550-45fd-944d-2ddb3c2b6033

## 🌍 Your Environment

Windows, Chrome, .net8, 4.2.2

**Comment by vnbaaij** [comment]
Hi,

Unfortunately this is not something we can change on our level. It is handeled in the underlying web component.

The behavior with the new tabs is not so strange though. If you add a new one,  that is going to be the active tab (after it redraws the list, causing the jump to the left). As it does not fit one the screen, the component has not oither place to put the bar than all the way at the end.

**Comment by pingu2k4** [comment]
Are we not able to at least place the active indicator underneath the overflow label, rather than having it push it to the side? I would expect that to happen rather than it push it out of bounds

**Comment by vnbaaij** [comment]
No, we cant do that because they are two separate components. We would need to render the overflow inside the tab strip which is not possible...

**Comment by dvoituron** [comment]
It's a limitation we regret, but the `fluent-tabs` web component we use doesn't manage this overflow by default.
We added this functionality without being able to correct this graphic "detail".

**Comment by vnbaaij** [comment]
Closed as not accionable.
