### ISSUE TITLE
fix: Changing the label style on a tab label incorrectly places it at the end of the tablist until new tab is selected

### ISSUE THREAD

**Issue by pingu2k4** [microsoft/fluentui-blazor#1187]
# 🐛 Bug Report

When you change the style for a label on a tab, said tab will jump to the end of the tablist. This is despite its order remaining correct in the DOM. When you select another tab, the order is then restored and everything renders in the correct order once again.

## 💻 Repro or Code Sample

You should be able to run the following code within the base FluentUI Template.
```csharp
@using Microsoft.FluentUI.AspNetCore.Components.Utilities

<FluentButton OnClick="AddTab">
    Add Tab
</FluentButton>

<FluentTabs>
    @foreach (var tab in Tabs)
    {
        <FluentTab Label="@tab" LabelStyle="@GetLabelStyle(tab)">
            Content for @tab
            <FluentButton OnClick="() => SetTabSuccess(tab)">
                Success
            </FluentButton>
        </FluentTab>
    }
</FluentTabs>

@code {
    List<string> Tabs { get; set; } = [];

    void AddTab()
    {
        Tabs.Add($"Tab {Tabs.Count}");
    }

    void SetTabSuccess(string tab)
    {
        var index = Tabs.IndexOf(tab);

        Tabs[index] = $"# {tab}";
    }

    string? GetLabelStyle(string tab)
    {
        return new StyleBuilder()
            .AddStyle("color", "var(--success)", tab.Contains("#"))
            .Build();
    }
}
```

Example is a trivial minimal repro, the needs for this look different yet behave exactly the same.

## 🤔 Expected Behavior

Order of tabs should be maintained, and follow the order shown in the DOM.

## 😯 Current Behavior

You will see what I mean by running the example above, but I also created a short video of it.

https://github.com/microsoft/fluentui-blazor/assets/11229848/d5fd1a92-2ef1-45bb-b9c9-6fd2e03b1df7

## 🌍 Your Environment

Windows, Chrome, 4.2.1

**Comment by dvoituron** [comment]
This seems to be due to an internal problem with the `fluent-tabs` web component which, probably, retains instances of `fluent-tab` to enable tab switching to be managed. 
But since Blazor regenerates HTML tabs when a label is modified `@foreach (var tab in Tabs)`, new `fluent-tab` instances are created without the `fluent-tabs` container being informed.

It's going to be very complicated to find a solution on our side (Blazor). We can see with the FAST teams if it's possible to adapt the web component.

In the meantime, we need to find a way to " notify " 'fluent-tabs` of a change to force it to redraw its content. For example, by adding an `ActiveTabId` attribute and modifying it: 

```razor
<FluentTabs ActiveTabId="@ActiveId"> ... </FluentTabs>

@code {
    string? ActiveId;
    void SetTabSuccess(string tab)
    {
        var index = Tabs.IndexOf(tab);
        Tabs[index] = $"# {tab}";
        ActiveId = null;     // <======
    }
}
```

**Comment by vnbaaij** [comment]
It is like @dvoituron says. Your code is 'messing' with the internal structure of the Tabs component on who decides what is in there . You need to provide a link between those two structure. See for an example of how we did this the demo site: https://www.fluentui-blazor.net/#dynamic

The FAST team is not going to change anything here as 1) they are focussing on newer web components. 2) We are 'mis-using' the way their code was intending to work.

Closing this as we have a (sufficient workaround available as shown in the linked example,
