### ISSUE TITLE
fix: Combobox wrong z-index stack order

### ISSUE THREAD

**Issue by dromerolovo** [microsoft/fluentui-blazor#1188]
When the `Height` property is not specify in `FluentCombobox`, some elements are displayed on top of the combobox options list.

![image](https://github.com/microsoft/fluentui-blazor/assets/49217428/4d87d1ec-457c-46e5-9573-8f5d74dd8e07)

![image](https://github.com/microsoft/fluentui-blazor/assets/49217428/b682366d-3791-45eb-9242-23fb8ca4afc4)

Basically the guitly is this logic:

`@if (!String.IsNullOrEmpty(Height))
{
    <style>
        @($"#{Id}::part(listbox) {{ max-height: {Height}; z-index: {ZIndex.ComboboxPopup} }}")
    </style>
}`

I can make a PR, I just wanted to know if this is intended.

**Comment by vnbaaij** [comment]
No, this is not intended. PR is welcome!

**Comment by mkgn** [comment]
I am using this in a Blazor serverside using .Net 8 (Microsoft.FluentUI.AspNetCore.Components v 4.3.1). I have the <FluentCombobox/> inside a <FluentDataGrid/> Below is a minimum syntax that you can just dump to a page and test.

    <FluentDataGrid Id="timesheet" Items="workHoursList" TGridItem="WorkHourEntry">
    <TemplateColumn>
        <FluentCombobox Placeholder="Select Project" Items="projectList" @bind-Value="@selectedProject" Autocomplete="ComboboxAutocomplete.Both" TOption="string"  Height="200px" />
    </TemplateColumn>
    </FluentDataGrid>
    
And this is how it appears
    
![image](https://github.com/microsoft/fluentui-blazor/assets/8392595/4bbf414f-3783-4a70-b42a-3b09d177f063)

If I just set the height of fluent-data-grid-cell then the list appears. Note that I have set the Height to 200px in <FluentCombobox/> So I guess the z-index issue still remains.

![image](https://github.com/microsoft/fluentui-blazor/assets/8392595/b3b51584-3e90-4c1f-9e2f-fd9a224d178a)
