### ISSUE TITLE
feat: add masking to Text Field

### ISSUE THREAD

**Issue by GamingMaker** [microsoft/fluentui-blazor#1190]
# 🙋 Feature Request

I thought it would be a great feature to add the option of masking into the Text Field. You could provide a pattern and the textfields behaves according to it. Let me give an example:
Pattern = "xxxx.xxxx" and the Text Field gets pre-filled like this: "\_\_\_\_x\_\_\_\_". Every time the end-user inputs a character, one underscore disappears and the character is in the position.
Also: the end-user can't provide more characters than the pattern length and every time he removes one character, the underscore comes back to the position.
Also if the pattern is like "dd.mm", the field should only accept valid inputs, unlike for example "51.56", since this is not a correct format.

This would be a nice addition to the text fields, especially for using the text fields in forms.

## 💁 Possible Solution

You could add a "Pattern" or "Mask" parameter into the Text Field where a user can provide a pattern for the masking.
Example: Pattern="dd.mm" and the field gets pre-filled with underscores: "\_\_.\_\_".
The maxlength and minlength Parameters should be set to the lenght of the pattern. 

## 🔦 Context

What are you trying to accomplish?
-> having a masked text input inside a form.

How has not having this feature affected you? 
-> i tried implementing it myself but i'm not that experienced and it works in general but could be way better. 

## 💻 Examples

![image](https://github.com/microsoft/fluentui-blazor/assets/74767030/10b0c4fb-61e8-490c-b0f8-55c169c32838)

![image](https://github.com/microsoft/fluentui-blazor/assets/74767030/7bcbe10b-0002-4b54-a70b-da0737c40810)

![image](https://github.com/microsoft/fluentui-blazor/assets/74767030/fc5ba0ce-aaab-407e-b03c-eea2eb1e080a)

**Comment by vnbaaij** [comment]
This is currently not possible as it is not supported by the underlying web component.

**Comment by omidkrad** [comment]
You can use [Blazor-FluentUI-MaskedTextField](https://github.com/omidkrad/Blazor-FluentUI-MaskedTextField). It's a wrapper on `<FluentTextField>` and using **IMask.js**.

There is also [BlazorInputMask](https://github.com/raphadesa/BlazorInputMask/tree/master/BlazorInputMask) that is a simpler Blazor component with **IMask.js** on `<input type="text"/>` (not Fluent UI), but I think you can do something similar for `FluentTextField`

**Comment by dvoituron** [comment]
We just added a `MaskedPattern` parameter in the v5 lib

https://fluentui-blazor-v5.azurewebsites.net/TextInput#masked-input
