### ISSUE TITLE
docs: how to change border style on cards

### ISSUE THREAD

**Issue by kzu** [microsoft/fluentui-blazor#1192]
I'd like to highlight certain FluentCard instances by changing the border to be the accent color, but I can't seem to get it to work.

I see the underlying web components use elevation (for the border width), but I can't figure out how to use that or change the color.

Any clues?

**Comment by kzu** [comment]
Nevermind: `<FluentCard Style="border: 1px solid red" `...

**Comment by vnbaaij** [comment]
![ElCZd-lEWjc0Blw7OZaWF6XcsEs.gif](https://github.com/microsoft/fluentui-blazor/assets/1761079/9df202d2-751c-4bfd-8dfa-b1a58a90ccb0)
