### ISSUE TITLE
fix: FluentTextField inside FluentTabs, pressing Enter re-renders FluentTab's content

### ISSUE THREAD

**Issue by gzdorik-brightgrove** [microsoft/fluentui-blazor#1194]
# 🐛 Bug Report

A component with a FluentTextField that is inside FluentTab is being re-rendered when Enter is pressed in the text field.

## 💻 Repro or Code Sample

Open the Home page, enter some text into the text box, wait until "You typed:" is updated. Now, press Enter.

Home.razor
```razor
@page "/"

<FluentTabs>
    <FluentTab Label="My tab">
        <MyComponent Fn="@(() => "from parent")" />
    </FluentTab>
</FluentTabs>
```

MyComponent.razor
```razor
<FluentTextField Immediate="true" ValueChanged="@(value => localValue = value)" />
<p>You typed: @localValue</p>

@code {
    [Parameter] public Func<string> Fn { get; set; }

    string localValue;

    protected override void OnParametersSet()
    {
        localValue = Fn();
    }
}
```

## 😯 Current Behavior
The "You typed: \<whatever you entered\>" is updated to "You typed: from parent".
OnParametersSet triggered, MyComponent was re-rendered.

## 🤔 Expected Behavior
Components inside tab component should not be re-rendered.

## 💁 Possible Solution
As a workaround, pass only primitive parameters to the nested component.

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Edge, Chrome, FireFox
* .NET 8, Microsoft.FluentUI.AspNetCore.Components 4.2.1

**Comment by vnbaaij** [comment]
Hi,

This is not a bug on FluentTextInput. If you change the first line of `MyComponent` to
```
<InputText @bind-Value=localValue @oninput=HandleInput />
```
You will see the exact same behavior

**Comment by vnbaaij** [comment]
Implemented fix changes had (very much) undisired effects elsewhere (#1333). Reverting those changes.

The example above can still be made to work after reverting these changes by changing
```
 protected override void OnParametersSet()
```
to
```
 protected override void OnInitialized()
```
in `MyComponent.razor`
