### ISSUE TITLE
Add a vitrual column collection wrapper to DataGrid

### ISSUE THREAD

**Issue by cairabbit** [microsoft/fluentui-blazor#1199]
# 🙋 Feature Request

I couldn't find a way after googling a long while and asking chatGPT with no proper answer. What I want to do is to use the DataGrid in my component with some predefined columns, like checkbox column, <actual field columns>, action columns (including edit and delete). This component also include some filtering methods. So, in short, this is a basic data manage component including some common features (filtering, selection rows, row actions etc). 

## 🤔 Expected Behavior

There is a virtual column group which contains a few <ColumnBase> implemented columns, this virtual column group just pass its child columns to the DataGrid.

## 😯 Current Behavior

No such column wrapper

## 💁 Possible Solution

I have no solution yet

## 💻 Examples

Currently, I need to use the datagrid in every data manage page like this:

```
<DataGrid TGridItem="Model" ...>
   <TemplateColumn>
       <HeaderCellItemTemplate><FluentCheckbox ..></FluentCheckbox></HeaderCellItemTemplate>
       <ChildContent><FluentCheckbox ..></FluentCheckbox></ChildContent>
   </TemplateColumn>
   <PropertyColumn Property="t=>t.Name" ...></PropertyColumn>
   <PropertyColumn Property="t=>t.Age" ...></PropertyColumn>
   <TemplateColumn Title="Actions" Align="@Align.End">
       <FluentButton IconEnd="@(new Icons.Regular.Size16.Edit())" OnClick="@(() => EditItem(context))" />
       <FluentButton IconEnd="@(new Icons.Regular.Size16.Delete())" OnClick="@(() => DeleteItem(context))" />
   </TemplateColumn>
</DataGrid>
```

But I don't want to repeat adding checkbox columns and action columns. So I create MyDateGrid:

```
<DataGrid TGridItem="Model" ...>
   <TemplateColumn>
       <HeaderCellItemTemplate><FluentCheckbox ..></FluentCheckbox></HeaderCellItemTemplate>
       <ChildContent><FluentCheckbox ..></FluentCheckbox></ChildContent>
   </TemplateColumn>
   @GridColumns(Model) // **this is to bring the field columns of model back to DataGrid, need to pass the type Model to columns**
   <TemplateColumn Title="Actions" Align="@Align.End">
       <FluentButton IconEnd="@(new Icons.Regular.Size16.Edit())" OnClick="@(() => EditItem(context))" />
       <FluentButton IconEnd="@(new Icons.Regular.Size16.Delete())" OnClick="@(() => DeleteItem(context))" />
   </TemplateColumn>
</DataGrid>
```

So for example, in my employee management page, I can use the MyDataGrid like this:

```
<MyDataGrid TGridItem="Employee" ...>
    <GridColumns>
       <PropertyColumn Property="t=>t.Name" ...></PropertyColumn>
       <PropertyColumn Property="t=>t.Age" ...></PropertyColumn>
    </GridColumns>
</MyDataGrid>
```

However, I couldn't create a custom GridColumns under DataGrid as the data grid context is internal. Can't pass it through.
Is there anything that can be done with existing components? Or can we add a virtual GridColumns, which just pass the child columns to DataGrid (please remember that the generic type parameter needs to pass as well)?

Hope my above codes explains. Thank you.

**Comment by vnbaaij** [comment]
Hi,

I think I understand what you would like to have but that is not something we are  going to add in the short term. It is a very computed change and would require significant rewriting of (parts of) the underlying QuickGrid code. We want to stay close to that code in general to be able to pick up changes that are being made there. We also lack the capacity to do this.
