### ISSUE TITLE
FluentTextField does not update model before form submit when using enter to submit

### ISSUE THREAD

**Issue by MisterGoodcat** [microsoft/fluentui-blazor#1201]
# 🐛 Bug Report

When using the enter key to submit a form, a currently focused `FluentTextField` does not properly update the model before the form is submit. A standard `InputText` does this.

## 💻 Repro or Code Sample

`<FluentTextField @bind-Value:get="@model.SomeString" @bind-Value:set="@model.SetSomeString"></FluentTextField>`

Focus the text field, change value, hit enter, and observe the form is submit with the old model value.

`<InputText @bind-Value:get="@model.SomeString" @bind-Value:set="@model.SetSomeString"></InputText>` 

Focus the text field, change value, hit enter, and observe the form is submit with the properly updated model value.

## 🤔 Expected Behavior

The `FluentTextField` should update its binding properly, in the same way as the standard `InputText`.

**Comment by vnbaaij** [comment]
Please supply a minimal reproduction for the issue (either something we can copy/paste or  a repo link).  

Hope you can understand it is too much work an too complicated for us to work on incomplete code like the two lines you submitted. We need to creat model, form, etc...

**Comment by MisterGoodcat** [comment]
Sure. Here's a minimal repro, just replace the content of "Home.razor" in a newly created project (4.2.1) with this:

```
@page "/"
@rendermode InteractiveServer

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

<EditForm Model="@this" OnValidSubmit="OnValidSubmit" FormName="CounterForm">
    <FluentTextField @bind-Value="value"></FluentTextField><br />
    <InputText @bind-Value="value"></InputText><br />
    <FluentButton Type="ButtonType.Submit">Submit</FluentButton><br />
    <span>Submit message: @submitMessage</span>
</EditForm>

@code {
    private string value = "edit, then hit enter to submit";
    private string submitMessage = "";

    private void OnValidSubmit()
    {
        submitMessage = $"Submitted: {value}";
    }
}
```

You will see that if you change the content of the `FluentTextField` with something like "abc", then hit enter, `value` still hold the old content in `OnValidSubmit`. It works as expected for the `InputText` component.

**Comment by vnbaaij** [comment]
Ok, thanks. Might take a few days before I take a look (🎄 break)

**Comment by dvoituron** [comment]
I don't know why (yet), but the FluentTextField updates its Binded value only at LostFocus (which is normal) but is not compatible with the Submit Return.

A (temporary) workaround might be to add an `Immediate` parameter. It's not acceptable in all cases, but perhaps in yours?

```csharp
<FluentTextField Immediate @bind-Value="value"></FluentTextField>
```

**Comment by MisterGoodcat** [comment]
To me it was important to somehow prevent submitting outdated data. Luckily that problem went away when I had to add some async validation and removed the explicit submit type from the respective button for that. That way the form is not automatically submitted on enter anymore.

**Comment by vnbaaij** [comment]
Workaround provided. Original issue was solved in a different way.

**Comment by kjkrum** [comment]
@vnbaaij The existence of a workaround is not a reason to ignore a bug.

**Comment by vnbaaij** [comment]
As maintainers of this repo, that is exactly our prerogative.

**Comment by kjkrum** [comment]
@vnbaaij Zero interest in quality. Got it.

**Comment by vnbaaij** [comment]
Lame and totally uncalled for. 

You have **NO** idea how much time and energy we as maintainers are investing in this.

**Comment by kjkrum** [comment]
@vnbaaij How many devs have wasted their time with this issue? Worse, how many devs have failed to notice this issue? This is a fairly serious bug.

**Comment by vnbaaij** [comment]
>How many devs have wasted their time and energy with this issue? Worse, how many devs have failed to notice this issue? 

Judging from the interaction we got on this issue, not that many.

>This is a fairly serious bug. Got bigger problems? Fine. Backlog it, don't close it

You don't have to tell us how to run our repo. And certainly not in that tone.

This is an upstream issue that we do not have control over and is undergoing significant changes at the moment. It is addressed by other **open** issues here (#1085, #1050).

**Comment by kjkrum** [comment]
@vnbaaij Neither of those sounds like the same issue. The workaround for #1050 of using a non-Fluent submit button does not address this issue.

`FluentTextField` _does_ update the model, but only _after_ the submit callback is called. As described by the OP, if you type "abc" and press enter the callback sees an empty string. If you then append "xyz" so the field contains "abcxyz" and press enter again, the callback sees "abc".

Imagine opening a form, updating a field, and pressing enter. Validation passes; the value that was there before must have passed. But the form is submitted with the old value and the database doesn't update.

I consider myself lucky to have noticed this bug within minutes the first time I ever tried to use a `FluentTextField`, and to only have lost one day to it. This is the kind of issue that will have developers and users ripping their hair out trying to figure out what happened, and possibly never tracing it back to this library.

**Comment by jbam-cgy** [comment]
@vnbaaij Having the same issue

**Comment by vnbaaij** [comment]
> Neither of those sounds like the same issue. The workaround for #1050 of using a non-Fluent submit button does not address this issue.\n\nFluentTextField does update the model, but only after the submit callback is called. As described by the OP, if you type \"abc\" and press enter the callback sees an empty string. If you then append \"xyz\" so the field contains \"abcxyz\" and press enter again, the callback sees \"abc\".

Why won't you accept it when I say it is the same issue? A submit is being called when you press enter **before** anything else is done. This happens both with TextField as with TextArea. Everything that is described here by you again, happens because of that erroneous submit. 

The issue originates from the FAST library (which is in the middle of a giant overhaul). We are tracking it in the other issues mentioned (open and labeled blocked)

**Comment by vnbaaij** [comment]
Ok, fine. I'm done with this. Have a nice weekend.

**Comment by garrettpauls** [comment]
It's a shame this was never fixed, I originally used the `Immedidate=true` "workaround" only to discover that while it works fine on a fully local dev system, it completely messes up typing in our production deployment (as mentioned by https://github.com/microsoft/fluentui-blazor/issues/1201#issuecomment-1962055918).

There seems to be no appetite to fix this issue which doesn't give me a lot of confidence in this project. Thankfully we only used it for a small internal website, so I'm not pivoting to a different Blazor UI framework.

**Comment by vnbaaij** [comment]
You are of course totally free to use whatever you want.

It is not a matter of appetite. As explained before, this exists because of an error in the upstream FAST library (which the Web Component use, which we wrap for our text components). It is not getting fixed there anymore _**but**_ we are working on our v5 version which uses a newer version of the Web Components and the issue is fixed in those.
_We don't have an ETA yet, but you can try our preview packages (https://github.com/microsoft/fluentui-blazor/blob/dev/docs/using-latest-daily.md)_

**Comment by garrettpauls** [comment]
@vnbaaij Ahh, I saw this was closed as not planned and missed the small notes on it being an upstream issue, thanks for the clarification!
