### ISSUE TITLE
FluentSelect Mutiple Selection not working correctly

### ISSUE THREAD

**Issue by kamazheng** [microsoft/fluentui-blazor#1206]
Cascading selection, the second selection multiple is true:
The first selection selected option changed, trigger the second selection items change, and clear the second selected options, the clear not working, the second selection keep the same position selected options.

![image](https://github.com/microsoft/fluentui-blazor/assets/49426393/ad93396f-9a12-44f4-84dc-4de9c1ecee09)

Keep same position options selected, even the selected option cleaned by code:
![image](https://github.com/microsoft/fluentui-blazor/assets/49426393/e4cfa0da-1b96-4b00-976c-456f25af3e54)

**Comment by vnbaaij** [comment]
Hi. 
Please supply us a minimal reproduction that shows the issue and we can copy/run.

**Comment by kamazheng** [comment]
@vnbaaij , Here is the reproduction code:
![image](https://github.com/microsoft/fluentui-blazor/assets/49426393/a28e75ac-2b5f-47d3-ae07-5bb815ee19b1)

```C#
<h4>Test</h4>

<h5>Select1</h5>
<FluentSelect Appearance="Appearance.Filled"
              TOption="string"
              Style="z-index:100"
              Items="@select1Items"
              @bind-Value="@selected1Value">

</FluentSelect>
<h5>Select2</h5>
<FluentSelect Appearance="Appearance.Stealth"
              TOption="string"
              Style="z-index:1"
              Multiple=true
              Items="@select2Items"
              @bind-Value="@selected2Value">

</FluentSelect>

@code {
    private string[] select1Items = new[] { "option1", "option2" };

    private string selected1Value
    {
        get => _selected1Value; set
        {
            _selected1Value = value;
            select2Items = new[] { Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId() };
        }
    }

    private string[] select2Items = new[] { Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId() };
    private string _selected1Value;

    private string selected2Value { get; set; }
}

```

**Comment by vnbaaij** [comment]
Ok, it is not the FluentSelect that is not working correctly, it is your code...
1) you are using `@bind-Value` on a multiple select (Select2) which **does not do** what you assume it does. As indicated in the docs and by IntelliSense: "Gets or sets the selected value. When Multiple = true this only reflects the first selected option value." You need to use `@bind-SelectedOptions` here
2) You are using a complex setup with a property and get/set implementation (presumably to use `@bind-Value` on Select1) which is not needed if you just do the binding yourself by using `Value` and `ValueChanged`. This way you can hook into the handling of making a selection in Select1 and call a method to do something with Select2

I have it working (ie. newlist and cleared selection) by using the following code:
```
<h4>Test</h4>

<h5>Select1</h5>
<FluentSelect Appearance="Appearance.Filled"
              TOption="string"
              Style="z-index:100"
              Items="@select1Items"
              Value="@selected1Value"
              ValueChanged="HandleValueChanged">

</FluentSelect>
<h5>Select2</h5>
<FluentSelect Appearance="Appearance.Stealth"
              TOption="string"
              Style="z-index:1"
              Multiple=true
              Items="@select2Items"
              @bind-SelectedOptions="@selected2Options">

</FluentSelect>

@code {
    
    private string[]? select1Items = new[] { "option1", "option2" };
    private string[]? select2Items = new[] { Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId() };
    private string? selected1Value;

    private IEnumerable<string>? selected2Options;

    private async Task HandleValueChanged(string? value)
    {
        selected1Value = value;
        await RefreshSelect2();
    }

    private async Task RefreshSelect2()
    {
        select2Items = null;
        await Task.Delay(5);
        select2Items = new[] { Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId(), Identifier.NewId() };
    }
}
```

The crux is to introduce that tiny delay in the `RefreshSelect2` method to give the rendering process the time to 'catch up' with the changes. Without it, it will not work as intended.

**Comment by kamazheng** [comment]
What actual make this works is the code:
` await Task.Delay(5);`
Any trick inside? @vnbaaij

**Comment by vnbaaij** [comment]
No, no tricks. Like I said, the tiny delay in the RefreshSelect2 method is needed to give the rendering process the time to 'catch up' with the changes.

**Comment by kamazheng** [comment]
This not work now for new version 4.3.0:
![image](https://github.com/microsoft/fluentui-blazor/assets/49426393/edb3d6db-7bca-42b9-a089-fd4e92edbda6)
