### ISSUE TITLE
FluentSelect SelectedOptionsChanged event not trigger when using manual options

### ISSUE THREAD

**Issue by kamazheng** [microsoft/fluentui-blazor#1207]
**Bug as title, if I change the manual options to Items parameter, the SelectedOptionsChanged can trigger.
(I have to use manual option, as I need to add @key for each options, the Items parameter is dynamic, if I update the items, the selected options will not update accordingly, will keep same position options selected)**

``` C#
<FluentSelect Appearance="Appearance.Filled"
              TOption="string"
              Multiple="true"
              Style="height:95%;overflow-y:auto;z-index:100"
              SelectedOptions="@selectedTableNames"
              SelectedOptionsChanged="tblsChanged">
    @foreach (var item in tableNames)
    {
        var tblName = "aaa";
        <FluentOption @key="@($"{tblName}-{item}")" TOption="string" Selected="@(selectedTableNames?.Contains(item)==true)">@item</FluentOption>
    }
</FluentSelect>

```

**Comment by vnbaaij** [comment]
When using manual options, we have no way of updating the `FluentSelect`s internal data structure in a reliable and solid way so we have no connect that event callback. 
We do not forsee change in this behavior in the short run.

**Comment by infofromca** [comment]
you should mention this on the doc. waste my whole day

**Comment by vnbaaij** [comment]
> you should mention this on the doc. waste my whole day

This sounds pretty entitled. We accept PRs, you know. We are a small team and can't do everything...
