### ISSUE TITLE
fix: using password manager for login in fluent-text-field

### ISSUE THREAD

**Issue by MxNbrt** [microsoft/fluentui-blazor#1208]
# 🐛 Bug Report

I used the template from [here](https://github.com/microsoft/fluentui-blazor/blob/e059bd15bd7a41294f3a063fb8990658489cd6b4/src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Login.razor) to create a login page based on fluentui-blazor but cant get my password manager (Microsoft AutoFill) to work.

## 💻 Repro or Code Sample

Exactly the same code as in the link provided above.

## 🤔 Expected Behavior

The password manager should open the popup and autofill my user and password.

## 😯 Current Behavior

Nothing happens

## 💁 Possible Solution

I dont know, sorry

## 🌍 Your Environment

Although I dont believe it is dependent on my env, I am working on 

- Windows 10
- Google Chrome 120.0.6099.111 
- Microsoft AutoFill 2.0.5
- .NET 8
- fluentui-blazor 4.2.1

**Comment by vnbaaij** [comment]
That must be something in the AutoFill extension (maybe blocked fro loacalhost?). When doing this in FireFox (top image) or Edge (bottom image), it works fine. You can also see int the login form you linked, the right autofill properties are set.

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/b733cbd7-30d6-4016-aa36-9588e99247e1)
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/cae6bb6d-fbc1-4e2f-818d-741087f21997)

Closing this as not actionable from our side

**Comment by MxNbrt** [comment]
You are right. After testing multiple extensions and browsers, the error just occurs with the Microsoft Autofill extension for Chrome. I created a bug report at https://chromewebstore.google.com/detail/microsoft-autofill/fiedbfgcleddlbcmgdigjgdfcggjcion/support?hl=en and am looking forward for an answer. 

Thank you very much for your support and have a nice day
