### ISSUE TITLE
fix: Unable to call a function from Blazor Component

### ISSUE THREAD

**Issue by Hemanth089** [microsoft/fluentui-blazor#1209]
# 🐛 Bug Report
I am implementing a tree view using FluentUI. I have written a recursive function. For child nodes I am trying to call a function. There is no build error. But when I run the project it closes without any error.

## 💻 Repro or Code Sample
```
void ShowTreeData(List<xxx> propertyList)
{
    @foreach (var property in propertyList)
    {       
        if (true)
        {            
            var children = xxx.ToList();
            <FluentTreeItem Text="@jsonName">
                @{
                    ShowTreeData(children);
                }
            </FluentTreeItem>
        }
        else
        {
            <FluentTreeItem Text="@jsonName"></FluentTreeItem>
        }
    }
}
```

## 🤔 Expected Behavior

Successful display the child tree nodes without runtime issue

## 😯 Current Behavior
Project closed without any error

## 🌍 Your Environment
I am using Windows 11, Visual Studio 2022 with latest Blazor Web App using .NET 8

* OS & Device: Windows
* Browser Microsoft Edge, Google Chrome
* .NET 8

**Comment by dvoituron** [comment]
This problem doesn't seem to be linked to the FluentUI library, but rather to Blazor itself.

**Comment by Hemanth089** [comment]
Is there a alternate solution for this?

**Comment by vnbaaij** [comment]
You probably need to supply a `@key` in your `for` loop. See for example:  https://learn.microsoft.com/en-us/aspnet/core/blazor/components/element-component-model-relationships?view=aspnetcore-8.0 and https://blazor-university.com/components/render-trees/optimising-using-key/ 

Closing as not actionable

**Comment by Hemanth089** [comment]
ShowTreeData(children) is not working. 

```
<FluentTreeItem Text="@jsonName">
      @{
          ShowTreeData(children);
      }
 </FluentTreeItem>
```
But with plain HTML is working
```
<div>
    @{
        ShowTreeData(children);
    }
</div>
```
