### ISSUE TITLE
feat: allow styling the IconStart/IconEnd of a FluentButton via the Color property

### ISSUE THREAD

**Issue by kzu** [microsoft/fluentui-blazor#1212]
# 🙋 Feature Request

Using the following elements:

```xml
  <FluentButton Title="Sign in" Appearance="Appearance.Stealth">
      <FluentIcon Value="@(new Icons.Regular.Size20.ShieldLock())" Color="Color.Neutral" Title="Sign in" />
  </FluentButton>
  <FluentButton Title="Sign in" Appearance="Appearance.Stealth" Color="Color.Neutral" 
                IconStart="@(new Icons.Regular.Size20.ShieldLock())">
  </FluentButton>
```

yields the following resut:

![image](https://github.com/microsoft/fluentui-blazor/assets/169707/df5b62ca-aa61-4ac7-b5c8-7b282cb02674)

## 🤔 Expected Behavior

The `Color` property in the `FluentButton` using the `IconStart` does not change the color of the icon within. So in order to properly style the icon of any buttons, you actually need to use a full nested `FluentIncon`, making the usage of IconStart/IconEnd much less useful.

## 😯 Current Behavior

Icon is rendered with its default color?

## 🔦 Context

Perhaps a separate IconColor property is necessary?

**Comment by dvoituron** [comment]
`FluentButton.Color` is used to define the color of the **button text**,
 but not the color of the icons. You can use `WithColor(Color.Neutral)` for this. 

```razor
<FluentButton Title="Sign in" Appearance="Appearance.Stealth">
    <FluentIcon Value="@(new Icons.Regular.Size20.ShieldLock())" Color="Color.Neutral" Title="Sign in" />
</FluentButton>
<FluentButton Title="Sign in" Appearance="Appearance.Stealth" Color="Color.Neutral"
              IconStart="@(new Icons.Regular.Size20.ShieldLock().WithColor(Color.Neutral))">
                                                             // ^^^^^^^^^^^^^^^^^^^^^^^^^^
</FluentButton>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/e4b5541c-91d6-4312-89a7-0f208ab5592d)
