### ISSUE TITLE
FluentTextField does not set id to its input element

### ISSUE THREAD

**Issue by timmik994** [microsoft/fluentui-blazor#1217]
When i inspected an FluentTextField in browset console, its inner input element always have id=control
This causes an issue to appear in chrome inspector. It also prevents autofill from working properly.

**Comment by dvoituron** [comment]
The `FluentTextField` is based on the `fluent-text-field` web component. A web component includes "internal/private" HTML elements. This Chrome message seems to be an error from Chrome Dev Console, but the code is correct.
