### ISSUE TITLE
Long Menu List does not scroll and ruin footer

### ISSUE THREAD

**Issue by mah0o7co** [microsoft/fluentui-blazor#1218]

**Comment by vnbaaij** [comment]
Sorry, but you will have to supply a bit more details...

Please provide us with minimal code (either something we can copy/paste or a repository), screenshots, etc. to make the issue observable/reproducable

**Comment by mah0o7co** [comment]
Copy and paste some menu item until go out of screen 
then scroll footer is moving 
I used default template.
`dotnet new fluentblazor`

**Comment by vnbaaij** [comment]
This is not what I meant. We have all those areas in the issue template for a reason. You can't expect us to do all the work.

Supply something 'ready to run' and help us to help you!

**Comment by mah0o7co** [comment]
There it is:
[fluent.zip](https://github.com/microsoft/fluentui-blazor/files/13777709/fluent.zip)

**Comment by vnbaaij** [comment]
This can be fixed by changing the `app.css`. Change the '.main' to the following:
```css
.main {
    height: calc(100% - 86px);
    color: var(--neutral-foreground-rest);
}
```
(so 100% instead of 100dvh) in height calculation)

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/0db46bc7-3c66-4366-953b-16adb5613c4f)
