### ISSUE TITLE
Loading startup costumization 

### ISSUE THREAD

**Issue by rofiimdad** [microsoft/fluentui-blazor#1219]
![image](https://github.com/microsoft/fluentui-blazor/assets/64058585/463fd0f4-284c-4712-9ee7-457a96ebf23d)

I haven't changed anything from the FluentUI Blazor site, I tried to find a way to delete/modify it, but I couldn't find it. did I miss something? please help me solve it thank you

**Comment by dvoituron** [comment]
You probably want to customize the Loading Progress Indicator, like explaining in this chapter?

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-8.0#client-side-loading-progress-indicators

**Comment by vnbaaij** [comment]
CLosing this as not actionable from our side
