### ISSUE TITLE
fix: [`FluentTreeItem`] in that `span` that renders `Text` proprty is not conditional and adds unnecessary space when `gap` CSS property is applied

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui-blazor#1227]
# 🐛 Bug Report

`FluentTreeItem` renders a `span` tag regardless of content of `Text` property.
Which cases to have tripple space before the `ChildContent` if `Text` property is null or empty.
https://github.com/microsoft/fluentui-blazor/blob/49314fdd2e7376d469c7c39e1aacd2d4f1899759/src/Core/Components/TreeView/FluentTreeItem.razor#L15

## 🤔 Expected Behavior

`span` is rendered only if `!string.IsNullOrWhitespace(Text)`

## 😯 Current Behavior

`span` is rendered always

## 💁 Possible Solution

I can make a PR which does
``` Razor
@namespace Microsoft.FluentUI.AspNetCore.Components
@inherits FluentComponentBase
<fluent-tree-item @ref=Element
                  class="@Class"
                  aria-label="@Text"
                  aria-expanded="@Expanded.ToAttributeValue()"
                  style="@Style"
                  id="@Id"
                  expanded="@Expanded"
                  selected="@Selected"
                  disabled="@Disabled"
                  @onselectedchange="@HandleSelectedChangeAsync"
                  @onexpandedchange="@HandleExpandedChangeAsync"
                  @attributes="AdditionalAttributes">
    @if (!string.IsNullOrWhitespace(Text))
    {
        <span class="treeitem-text">@Text</span>
    }
    @ChildContent
</fluent-tree-item>
```

## 🔦 Context

I cannot render `FluentIcon` with text within `FluentTreeItem` as child content. I want to use `gap` CSS property

## 🌍 Your Environment

* .NET 8 and FAST Version 4.2.1

**Comment by vnbaaij** [comment]
Changed it and will be in next release (5d585ae2118883a0006afb2384d0276f8ec0b43e)
