### ISSUE TITLE
fix: FluentDataGrid in horizontal scroll when there are numerous columns

### ISSUE THREAD

**Issue by jgmsb** [microsoft/fluentui-blazor#1228]
# 🐛 Bug Report

Following the page https://www.fluentui-blazor.net/DataGrid we have noticed that the examples don't contemplate the situation when a lot of columns are needed and collapsing them isn't the best solution in terms of ux. When the FluentDataGrid is wrapped in a div with a fixed width and horizontal scroll, the data grid becomes unstable and the internal style and feedback (for Virtualize) are lost in the areas outside the initial position of the horizontal scrollbar.

## 💻 Repro or Code Sample
**The code:**
razor
```
<div class="result-container">
    @{var gridStyleColumns = $"repeat({tableHeaders.Count}, 200px)";}
    <FluentDataGrid Virtualize="true" Items=@fluentTable GenerateHeader="GenerateHeaderOption.Sticky"
                    ResizableColumns=true GridTemplateColumns=@gridStyleColumns>
        <ChildContent>
            @foreach (var header in tableHeaders)
            {
                var lambda = DynamicExtensions.GetPropertyLambda(header);
                <PropertyColumn Title="@header" Property=@lambda Sortable="true" />
            }
        </ChildContent>
        <EmptyContent>
            <span style="color: #9f9f9f; font-weight: normal"><i>Tabla sin datos</i></span>
        </EmptyContent>
    </FluentDataGrid>
</div>
```
css
```
.result-container {
    width: 162vh;
    overflow-x: scroll;
    max-height: 80vh;
    padding-left: 10px;
}
```

**Steps:**
Horizontal scroll in initial position renders correctly the FluentDataGrid:
![Screenshot_1](https://github.com/microsoft/fluentui-blazor/assets/105709204/bbc948fe-416f-4779-8557-9d218c2e5a73)
If we scroll horizontally, the style is lost. Notice the horizontal lines and the background of the headers disappear:
![Screenshot_2](https://github.com/microsoft/fluentui-blazor/assets/105709204/5cfc0f75-1188-4463-97ec-f06dee47a5ec)
If we scroll horizontally to the initial position and then scroll vertically to trigger the dynamic refresh of Virtualize, it works well:
![Screenshot_3](https://github.com/microsoft/fluentui-blazor/assets/105709204/f25b32a8-8a1b-4973-ba73-f4766f8bf4d7)
If we scroll horizontally again and then scroll vertically, the dynamic refresh of Virtualize is lost:
![Screenshot_4](https://github.com/microsoft/fluentui-blazor/assets/105709204/ab0b5423-ec33-47d6-b422-c314aa280e40)
![Screenshot_5](https://github.com/microsoft/fluentui-blazor/assets/105709204/295e5d64-3616-467d-ba79-dad2cd588156)

## 🤔 Expected Behavior

When wrapping the FluentDataGrid inside of a horizontal scroll because the numerous columns, the fluent style of the grid and the dynamic refresh of the Virtualize  shouldn't be lost 

## 😯 Current Behavior

When wrapping the FluentDataGrid inside of a horizontal scroll the style and dynamic refresh of the Virtualize is lost

## 🌍 Your Environment

Windows 11 with Google Chrome (120.0.6099.130) , Mozilla FireFox (121.0 (64-bit)) and Microsoft Edge (120.0.2210.91).
.NET: 8.0
Nuget Microsoft.FluentUI.AspNetCore.Components (4.2.1)

**Comment by vnbaaij** [comment]
I use the following code:
```
<div style="width: 700px; height: 400px; overflow-y: scroll; overflow-x: scroll;">
    <FluentDataGrid Style="width: 900px;" Items=@items Virtualize="true" ItemSize="54" GridTemplateColumns="1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr">
        <ChildContent>
            <PropertyColumn Property="@(c => c.Item1)" Sortable="true" />
            <PropertyColumn Property="@(c => c.Item2)" />
            <PropertyColumn Property="@(c => c.Item3)" Align="Align.Center" />
            <PropertyColumn Property="@(c => c.Item4)" Align="Align.End" />
            <PropertyColumn Property="@(c => c.Item1)" Sortable="true" />
            <PropertyColumn Property="@(c => c.Item2)" />
            <PropertyColumn Property="@(c => c.Item3)" Align="Align.Center" />
            <PropertyColumn Property="@(c => c.Item4)" Align="Align.End" />
            <PropertyColumn Property="@(c => c.Item1)" Sortable="true" />
            <PropertyColumn Property="@(c => c.Item2)" />
            <PropertyColumn Property="@(c => c.Item3)" Align="Align.Center" />
            <PropertyColumn Property="@(c => c.Item4)" Align="Align.End" />
        </ChildContent>
        <EmptyContent>
            <FluentIcon Value="@(new Icons.Filled.Size24.Crown())" Color="@Color.Accent"/>&nbsp; Nothing to see here. Carry on!
        </EmptyContent>
    </FluentDataGrid>
</div>
<br />
<FluentSwitch @bind-Value="@_clearItems" 
              @bind-Value:after="ToggleItems" 
              UncheckedMessage="Clear all results"
              CheckedMessage="Restore all results">
</FluentSwitch>


@code {
    bool _clearItems = false;
    public record SampleGridData(string Item1, string Item2, string Item3, string Item4);

    IQueryable<SampleGridData>? items = Enumerable.Empty<SampleGridData>().AsQueryable();

    private IQueryable<SampleGridData> GenerateSampleGridData(int size)
    {
        SampleGridData[] data = new SampleGridData[size];

        for (int i = 0; i < size; i++)
        {
            data[i] = new SampleGridData($"value {i}-1", $"value {i}-2", $"value {i}-3", $"value {i}-4");
        }
        return data.AsQueryable();
    }
    protected override void OnInitialized()
    {
        items = GenerateSampleGridData(5000);
    }

    private void ToggleItems()
    {
        if (_clearItems)
		{
			items = null;
		}
		else
		{
			items =GenerateSampleGridData(5000);;
		}
    }
}
```

Which gives me this:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/e1637b7d-c593-476a-9cec-6aa7b641cf03)
Scrolls both ways perfectly fine.

Next time, please supply code or a repo we can run to reproduce an issue. Thanks.

**Comment by jgmsb** [comment]
Hello @vnbaaij 
happy new year,

I've been able to replicate it with the fluentblazor template -> https://github.com/jgmsb/fluentui-bug-report
Pressing the Load Random Data button will show you the problem. It seems it's only when columns are dynamically created or there is a large number of them.

Anyway, our team were able to find a workaround but thank you.
Cheers

**Comment by vnbaaij** [comment]
With the code you supplied, I can replicate. I think it is an problem to use a sticky header in combination with `Virtualize`.  Will investigate further.

**Comment by RobDene** [comment]
Hi
We are seeing the same issue with the "ShowHover" in a FluentDatagrid. If you have the horizontal scroll bar , Showhover will only highlight the initial columns in the view, when you start scrolling the hover isn't selecting the entire row

**Comment by RobDene** [comment]
Playing with this issue a little more , it appears that when the horizontal scroll becomes active, the ShowHover is restricted to the original view width .

**Comment by adospace** [comment]
@jgmsb do you mind sharing how your team was able to work around it?
