### ISSUE TITLE
fix: FluentUI Templates generate Account Pages with misspelled component name <FluentValidationMesssage> (With 3 S's)

### ISSUE THREAD

**Issue by emilioc7** [microsoft/fluentui-blazor#1230]
# 🐛 Bug Report

When template option `-auth Individual` for Including Individual authentication pages is added during new project creation with Microsoft.FluentUI.AspNetCore.Templates version 4.2.1, several pages under path "Components/Account/Pages/" include an incorrect component name for FluentValidationMessage.

**Expected:** 

Component name should be (with 2 S's):

 <FluentValidationMessage

**Actual:**
The generated pages include incorrect component name as (with 3 S's):

 <FluentValidationMe**sss**age

## 💻 Repro or Code Sample

1. Install Fluent UI Templates `dotnet new install Microsoft.FluentUI.AspNetCore.Templates::4.2.1`
2. Create a new Blazor Server project with Authentication: Individual `dotnet new fluentblazor --auth Individual`
3. Go to any of below pages:
  - Components/Account/Pages/ForgotPassword.razor
  - Components/Account/Pages/Login.razor
  - Components/Account/Pages/LoginWith2fa.razor
  - Components/Account/Pages/LoginWithRecoveryCode.razor
  - Components/Account/Pages/Register.razor
  - Components/Account/Pages/Manage/ChangePassword.razor
  - Components/Account/Pages/Manage/DeletePersonalData.razor
  - Components/Account/Pages/Manage/Email.razor
  - Components/Account/Pages/Manage/EnableAuthenticator.razor
  - Components/Account/Pages/Manage/Index.razor
  - Components/Account/Pages/Manage/SetPassword.razor
4. This causes error:

> Found markup element with unexpected name 'FluentValidationMesssage'. If this is intended to be a component, add a @using directive for its namespace. 

![image](https://github.com/microsoft/fluentui-blazor/assets/33851624/bc2bd64b-e5e2-4b62-be98-82422b725e4e)
![image](https://github.com/microsoft/fluentui-blazor/assets/33851624/5603e11e-cf03-400f-bff0-ef503655a001)

In few of the generated Account pages the correct component name '<FluentValidationMessage' can be found:

- Components/Account/Pages/ExternalLogin.razor
- Components/Account/Pages/ResendEmailConfirmation.razor
- Components/Account/Pages/ResetPassword.razor

## 💁 Possible Solution
Submitted PR : https://github.com/microsoft/fluentui-blazor/pull/1231

## 🌍 Your Environment

Microsoft.FluentUI.AspNetCore.Templates
      Version: 4.2.1
      
dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.d75fd3e4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.2
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.d75fd3e4
 [aspire]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.0-preview.2.23619.3/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.0.0-preview.2.23619.3/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  7.0.308 [/usr/local/share/dotnet/sdk]
  7.0.311 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by vnbaaij** [comment]
Fixed with #1234
