### ISSUE TITLE
MessageBar color does not update when the theme changes:

### ISSUE THREAD

**Issue by aDisplayName** [microsoft/fluentui-blazor#1239]
# 🐛 Bug Report

In https://www.fluentui-blazor.net/MessageBar, if switch the theme between light and dark, the message bar fill color does not change. Need to reload the website to get the color updated.

## 💻 Repro or Code Sample
Demo and documentation site for version 4.2.1 of the library. This version supports .NET 8 only

Open https://www.fluentui-blazor.net/MessageBar (at the time the bug is being submitted) in light mode, the display is:
![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/7c7ef582-f53f-44a1-b2ea-a33fb7009ef9)

Change the theme from light to dark from the settings menu:
![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/d8159b8a-6219-4e64-adc8-002585b9eed8)

## 🤔 Expected Behavior
The color of message bars are updated correctly:
Static:
![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/e9fc652f-6846-40cb-93b3-d0c63e1c1349)
Dynamic:
![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/ee638eb7-e3a5-4d21-abd5-a8742564eac0)

## 😯 Current Behavior

The message bar is displayed as:
![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/7c9e5151-e068-460b-bf66-87a0c690d089)

The dynamically generated message bar is the same:
![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/681e5b6c-9f6d-481b-800b-fd9233944ff0)

After reload the webpage, all the color goes back to correct:
![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/24170075-7273-4d92-8d0d-c8e7a0eeb22e)

![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/fbdc4bd9-d419-4ff8-9fc9-3c1fc68e109f)

## 💁 Possible Solution

Manually reload the website solved the problem, but the problem will still show up if change the theme back to light.

## 🔦 Context

A link to a similar situation in Blazor Maui:
https://github.com/microsoft/fluentui-blazor/issues/1005

## 🌍 Your Environment

Microsoft Edge Version 120.0.2210.91 (Official build) (64-bit)

**Comment by vnbaaij** [comment]
There was an issue in the `FluentDesignThem` component where the global state of the mode was only set when an eventhandler was defined for the luminance change. This is corrected in the referenced commit. Will be part of next release
