### ISSUE TITLE
fix: dragging the splitter bar is inverted with RTL enabled in fluent splitter

### ISSUE THREAD

**Issue by Narvalex** [microsoft/fluentui-blazor#1245]
# 🐛 Bug Report

## 💻 Repro or Code Sample

Go to the [splitter docs](https://www.fluentui-blazor.net/Splitter). Then go to the settings and enable RTL (Right to left) option. After that try to drag the vertical bar of any of the splitters of the docs.

## 🤔 Expected Behavior

You would expect that the vertical bar of the splitter will follow the mouse cursor on the same horizontal direction.

## 😯 Current Behavior

The bar moves to the oposite direction and make some "jumps" an the begining of the drag. It seems that is inverted (when pulling right it goes to the left and viceversa)

## 🌍 Your Environment

The current and (last?) version of the year 2023 of the [official Fluent UI Blazor Docs page](https://www.fluentui-blazor.net)

This is related to #1244

**Comment by vnbaaij** [comment]
Yes, I've seen it too (as raised in the linked issue). I've put it on the list (for next year 🎆).
Closed the other issue to try and 'train' the reporter to submit complete issue reports. Did not say there I was not going to look at it 😉

**Comment by Narvalex** [comment]
Thanks @vnbaaij. You and @dvoituron are a huge part of my project. I'm so grateful. Best wishes to both of you!
