### ISSUE TITLE
fix: GridTemplateColumns cannot be applied to FluentDataGrid globally in FluentDataGrid

### ISSUE THREAD

**Issue by aDisplayName** [microsoft/fluentui-blazor#1252]
# 🐛 Bug Report

GridTemplateColumns could not be applied globally in FluentDataGrid. Instead, it is applied to each `fluent-data-grid-row` individually.

We want the name and birthdate columns are using minimum width possible, and the Id uses the rest of the space. So we applied the `1fr auto auto` as the value for `GridTemplateColumns` property.

## 💻 Repro or Code Sample

We want to auto sizing the data grid column based on the content it is displaying. For example:
```razor
<FluentDataGrid Items="@people" GridTemplateColumns="1fr auto auto">
    <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" />
    <PropertyColumn Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
    <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
</FluentDataGrid>

<FluentCard> <!-- Reference for expected behavior -->
    <div style="display: grid;  grid-template-columns: 1fr auto auto;  gap: 20px;">
        <div>10895</div>        <div>1985-03-16</div>        <div>Jean Martin</div>
        <div>10944</div>        <div>1991-12-01</div>        <div>António Langa</div>
        <div>11203</div>        <div>1958-10-10</div>        <div>Julie Smith</div>
        <div>11205</div>        <div>1922-04-27</div>        <div>Nur Sari</div>
        <div>11898</div>        <div>2011-05-03</div>        <div>Jose Hernandez</div>
        <div>12130</div>        <div>2004-01-09</div>        <div>Kenji Sato</div>
    </div>
</FluentCard>
@code {
    record Person(int PersonId, string Name, DateOnly BirthDate);

    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9)),
    }.AsQueryable();
}
```

Full code example can be accessed at https://github.com/aDisplayName/bugsamplecode/tree/main/20240102/BlazorApp1

## 🤔 Expected Behavior
The column width are globally adjusted to the minimum for Date and Name columns.
![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/754335f5-bc6e-47b2-b1b1-bf6131145655)

## 😯 Current Behavior
Instead, the `GridTemplateColumns` was applied to each row individually, defeating the purpose of auto sizing the columns globally based on the content
![image](https://github.com/microsoft/fluentui-blazor/assets/19527258/2bdb1794-c134-4659-8a9d-95e7d5f127b2)

## 🌍 Your Environment

* Microsoft Edge
* Microsoft.FluentUI.AspNetCore.Components 4.2.1
* .NET 8.0

**Comment by vnbaaij** [comment]
Hi,

This is not something we can fix currently as it is behavior that comes from the underlyinging web components. I think it will be very hard to fix over there as well. This type of column definition would require that the values for auto would need to be calculated and adjusted after all the rows have been inserted. I will bring this up with the web compnents/FAST team, but don't expect a change for it anytime soon. Sorry, don't want to be negative but also don't want to give any false hope.

What you can do as a 'workaround' is to kind of reverse the logic and do somthing like `GridTemplateColumns="auto 0.2fr 0.2fr"`

You will see the same behaviour if you go to https://explore.fast.design/components/fast-data-grid and replace the code with:

```
<div>
    <script>
        (function () {const sampleGrid = document.getElementById("samplegrid");sampleGrid.rowsData = [{item1: "value 1-1",item2: "value 2",item3: "value 4-1111",item4: "value 5-1111111",},{item1: "value 1-2",item2: "value 2-2222222222",item3: "value 4-222",item4: "value 5-222222222",},{item1: "value 1-3",item2: "value 2-3",item3: "value 4-3",item4: "value 5-3",},];})();
    </script>
    <fast-data-grid id="samplegrid" grid-template-columns="1fr auto auto"></fast-data-grid>
    <p></p>
   </div>
```

**Comment by aDisplayName** [comment]
@vnbaaij , appreciate for the quick feedback and suggestion. 

I agree with you about the current status by analyzing the resulting DOM tree. Hopefully there could be some improvement in the near future.

**Comment by vnbaaij** [comment]
Ok, closing this one then
