### ISSUE TITLE
Radio group complex content

### ISSUE THREAD

**Issue by martinbu** [microsoft/fluentui-blazor#1253]
I have already found the [issue](https://github.com/microsoft/fluentui-blazor/issues/1071). So maybe this is also something that won't be fixed for this component... But lets see.

# 🐛 Bug Report

The RadioGroup component only allows simple string Radio items. If complex items are added, the selection does not work correctly anymore. Additionally, the RadioGroup accepts a TValue Parameter, but in fact, only string is supported for TValue.

## 💻 Repro or Code Sample

I have added [3 examples](https://github.com/martinbu/fluentui-blazor/commit/93b0cfd9df6eab1127997a392ff99516e69f9ce2) in the demo page which causes issues.

### Complex Content 1
If complex content is added, the selection does not work correctly anymore. E.g. If the content of the FluentTextField is set to Item 1 or Item 2 the selection is changed. If something different than the Radio icon is clicked, the selection sometimes changes or does not change correctly.

### Complex Content 2 and 3
It would also be nice if the TValue can be something different than string.

**Comment by vnbaaij** [comment]
Hi Martin,

I don't think I fully agree with the issue you are describing for 'Complex Content 1'. I think it makes sense the selection changes when clicking on any part of the content shown inside the radio item (in this case the components in the stack). This works the same as with a 'regular' radio item where clicking on a label also selects that item. You just have a very specific label here.
I did notice the selection is not always maintained when clicking around so will take a look.

As for the generic issue (TValue other than string, I will need to take a closer look and compare to what the base Blazor `InputRadio` and `InputRadioGroup` are doing. That will however take some more time and will not be in the upcoming v4.3 release.

**Comment by martinbu** [comment]
Hi Vincent,

thank you for looking into this. For now I have used a FluentListbox as suggested here #1071. This works for "complex content" and the selection is maintained correctly so far.

Regarding the 'Complex Content 1': 
I have updated the [example](https://github.com/martinbu/fluentui-blazor/tree/radio-group-issues), that 'Nothing is selected' is shown if the `selectedItem` gets null. Additionally the `selectedItemName` from the bin-value property is shown now to make the issue more clear.

1) If I click not the radio button directly, the selection is updated correctly, but the bind-value property gets null or takes the "value" of the clicked element, e.g. Textbox content or "on" if the switch is clicked directly after reload the page.
![grafik](https://github.com/microsoft/fluentui-blazor/assets/1791936/b74d0ad1-5394-4354-9398-40a3a6a4b3ce")

2) If I click on the Textbox that contains a value which is the label of another item, this one gets selected.
![grafik](https://github.com/microsoft/fluentui-blazor/assets/1791936/ff4605db-69e6-4b6e-abe8-03129bfa2dee)

3) If the container itself is clicked, the bin-value gets null.
![grafik](https://github.com/microsoft/fluentui-blazor/assets/1791936/79ce3aca-3477-41af-b7e0-cb78fb547252)

Another issue that I just noticed is that I can't put spaces in the Textbox if it is inside a radio content.

**Comment by vnbaaij** [comment]
Ok, I'll dig a bit more. In teh meantime, If you trie using a generic type with the standard Blazor `InputRadio` and `InputRadioGroup`, you'll find that it is not just a matter of using your `Item' as the `TValue` type. Try the example 3 with this:
```
<InputRadioGroup TValue="Item" @bind-Value=selectedItem Name="ComplexContent3b">
    @foreach (var item in items)
    {
        <FluentStack Orientation="Orientation.Horizontal" Style="border: 1px solid black; padding: 8px 16px" VerticalAlignment="VerticalAlignment.Center">
            <InputRadio @key=@item Value="@item"  />
            <FluentStack Orientation="Orientation.Vertical">
                <FluentLabel>@item.Name</FluentLabel>
                <FluentTextField Label="Custom Name" @bind-Value="@item.CustomName" />
                <FluentSwitch @bind-Value="@item.Enabled" Label="Enable" />
            </FluentStack>
        </FluentStack>

    }
</InputRadioGroup>
```
(extra FluentStack because `InputRadio` has no ChildContent support) 

As said, I will like more at this but I think in the end the result will work and behave like the standard components, so you also will not just be able to specify anything for the `TValue`.

**Comment by vnbaaij** [comment]
I'm going to close this as not planned. Been looking into getting it to work with more complex types but the (web) components do not like that. Besides, a workaround is available with the Listbox
