### ISSUE TITLE
fix: Page content visible over drop down list in Combobox Option template

### ISSUE THREAD

**Issue by NickHirras** [microsoft/fluentui-blazor#1254]
# 🐛 Bug Report

I saw a bug when viewing the live demo at: 
https://www.fluentui-blazor.net/Combobox

## 💻 Repro or Code Sample

1. Visit the fluentui-blazor live demo at https://www.fluentui-blazor.net
2. Click "Combobox" in the left nav menu.
3. Scroll down to the **Opetion template** example.  Scroll down so that the Documentation section below it is also visible on the screen.  Now open the sample combobox.

## 🤔 Expected Behavior

The Combobox options should appear cleanly in their own menu element.

## 😯 Current Behavior

Instead I'm seeing the contents of the page show through the menu, shown in this screenshot.

![image](https://github.com/microsoft/fluentui-blazor/assets/3911628/75e9abf3-880c-4bb3-b8d3-63eb33e4a0a6)

## 🌍 Your Environment

MacOS Ventura 13.6.2
Google Chrome Version 120.0.6099.129 (Official Build) (arm64)

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Hi,

Thanks for reporting this. It has already been fixed for the next release. See https://preview.fluentui-blazor.net/Combobox#optiontemplate

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/59fe6abf-a3b7-4ab0-8509-16581f39d953)
