### ISSUE TITLE
The Time picker icon is not same color as Date Picker

### ISSUE THREAD

**Issue by kamazheng** [microsoft/fluentui-blazor#1258]
In DarkMode:
Readonly:
![image](https://github.com/microsoft/fluentui-blazor/assets/49426393/1b0befb5-beea-4a35-af3d-e853c734cb79)
Not readonly:
![image](https://github.com/microsoft/fluentui-blazor/assets/49426393/b0152751-ad2d-4e9b-837e-47e9b47dee9f)

**Comment by dvoituron** [comment]
It's because the TimePicker uses the default `input type=time` component. And the Dark mode is not detected by this HTML component (except if you use the Browser Theme). 

You could set a custom icon like describe here: #1193

Or wait some weeks to let us the time to create a new Time component.

**Comment by vnbaaij** [comment]
Closing as this is not actionable at this time.

**Comment by RudyCo** [comment]
Still an issue as of 23-apr-2024, version 4.7.0

**Comment by vnbaaij** [comment]
Nothing has changed here. It is still using the `input type="time"` internally. Is the workaround mentioned in #1193 not working for you?

**Comment by RudyCo** [comment]
Not tested yet, but I was surprised to see this small bug on the [website](https://www.fluentui-blazor.net/DateTime#fluenttimepicker-class).

**Comment by dvoituron** [comment]
@RudyCo The `FluentTimePicker` uses the default HTML element `input type="time"` and it's not possible to easily customize the Browser icon.

You could find a "solution" here: https://github.com/microsoft/fluentui-blazor/discussions/1193#discussioncomment-7930415
