### ISSUE TITLE
FluentDesignTheme not persisted / switches back to system default

### ISSUE THREAD

**Issue by woha** [microsoft/fluentui-blazor#1259]
I've created a new project from the templates with: `dotnet new fluentblazor -n ThemeDemo -int Server -au Individual -ai false`
and followed the instructions provided by @dvoituron to implement the FluentDesignTheme.

All works nice, but as soon as I click on one of the included / generated FluentNavLinks the theme switches back to system default:

![2024-01-03_12-35-19](https://github.com/microsoft/fluentui-blazor/assets/17140559/c68477b1-c247-41cf-bcca-e6d81a38ab4e)

Sample repo can be found here: [https://github.com/woha/theme-demo](url)

**Comment by woha** [comment]
One addition. The settings in the local storage (ThemeDemo in my case) are set back to null as soon as I click on one of the FluentNavLinks:
![2024-01-03_12-43-10](https://github.com/microsoft/fluentui-blazor/assets/17140559/6578668e-7492-4766-9a9c-ccc3d59385b3)

**Comment by woha** [comment]
Looks like this is caused by the way I set the render mode.
I'm doing it in `MainLayout.razor` with `<FluentDialogProvider @rendermode="InteractiveServer"/>`.
I cannot do it for the entire app in `App.razor` with `<Routes @rendermode="InteractiveServer"/>` because this causes an infinite loop for the Account pages, here is an example of this behavior (after 13s when I click the login link):

![2024-01-03_12-53-42](https://github.com/microsoft/fluentui-blazor/assets/17140559/68001cd7-be46-45b2-b1af-4088058b282f)

**Comment by vnbaaij** [comment]
It works in my clone of your repo if I just remove the `FluentDesignTheme` component from the `Routes.razor` component.

**Comment by woha** [comment]
Sorry Vincent, but I do not understand.
There is no FluentDesignTheme component in my Routes.razor.

**Comment by vnbaaij** [comment]
Hmm, then that must have been something I added in my clone. Besides that I must also have changed something else  because I got it working before I coded this issue. I already sledges my clone I believe but will check again (tomorrow)

**Comment by vnbaaij** [comment]
Wolfgang, I got it working again...I removed the `FluentDesignTheme` form `MainLayout.razor`

**Comment by woha** [comment]
Yes, Vincent, thank you.
Removing the `FluentDesignTheme` from `MainLayout.razor` solved the problem.

Great help - as always, thank you!
