### ISSUE TITLE
Can the data grid columns be resizable on a per column basis?

### ISSUE THREAD

**Issue by Rocky-25** [microsoft/fluentui-blazor#1260]
# 🙋 Feature Request

When using the data grid there is a property to set all columns to be resizable. It'd be great if we could also define this on a per column basis. 

A use case example:
![image](https://github.com/microsoft/fluentui-blazor/assets/52032850/6e0995cb-af32-4c15-9b37-e7736a01d6e1)

In this case it'd be good to remove the resize on the first column containing the check box.

**Comment by vnbaaij** [comment]
No, this is not possible now and not planned. 

It would need a lot of work and introduce a lot of complexity, edge cases, etc. to get that set up in a robust and reliable way.
