### ISSUE TITLE
fix: Incorrect placement with scrollbar blip in [`Popover`]

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui-blazor#1261]
# 🐛 Bug Report

If you open `Popover` at the very right of the page it tries to occupy more space than necessary causing the vertical scrollbar to appear and disappear like a blip.

See the screen recording
https://github.com/microsoft/fluentui-blazor/assets/2365592/f052ea75-5c5c-4d7f-8423-6a911b3c8ac1

## 💻 Repro or Code Sample

Just put a button with a popover at the very top right of the page.

## 🤔 Expected Behavior

No scrollbar blip

## 😯 Current Behavior

Scrollbar blip

## 🔦 Context

See the screen recording

## 🌍 Your Environment

* .NET 8 and FAST 4.2.1

**Comment by Narvalex** [comment]
I had a similar problem with pop over. Tried later with menu and I had hozorintal scroll-bar blip. It seem that is something related to the overlay component. As a workaround I had to add a css rule for `body` of `overflow-x: hidden;`.

**Comment by OYVT** [comment]
I had the same problem.
Resolved by adding FluentMessageBarProvider to your MainLayout.razor.

**Comment by xperiandri** [comment]
I wonder how `FluentMessageBarProvider` is related to `Popover` display.
It does not make any effect for me

**Comment by vnbaaij** [comment]
Yeah, I also don't think the `FluentMesssageBarProvider` is of any influence here.

@xperiandri Andrii were you able to get rid of the blib with Alexis's (@Narvalex) workaround?

**Comment by mariianazarova** [comment]
> I had a similar problem with pop over. Tried later with menu and I had hozorintal scroll-bar blip. It seem that is something related to the overlay component. As a workaround I had to add a css rule for `body` of `overflow-x: hidden;`.

Thanks, it worked!

**Comment by vnbaaij** [comment]
Andrii, closing this as 2 people confirmed it is solved with `overflow-x: hidden` on `body`.

Feel free to re-open if this does not solve it for you
