### ISSUE TITLE
Home Page Displays Border Around 'Hello World' - Fluent Blazor Web App

### ISSUE THREAD

**Issue by marqdouj-spartan** [microsoft/fluentui-blazor#1265]
# 🐛 Bug Report

I created a .NET 8.0 fluent blazor web app (Server) using the template provided by VS 2022.

When I run the app the 'Hello World' is always displayed with a border.

![image](https://github.com/microsoft/fluentui-blazor/assets/97969185/c214dd23-df3a-4bbf-9147-dc32c3e0624d)

I published the app to azure - same issue.

## 🤔 Expected Behavior

The home page should display without a border around 'Hello World'

NOTE: once I click anywhere on the page the border disappears and never comes back - even when navigating between pages, etc.

## 🌍 Your Environment

Windows 10
VS 2022 Enterprise 17.8.3
<ItemGroup>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.*-* " />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.*-* " />
</ItemGroup>

**Comment by dvoituron** [comment]
I think that it's linked to the "Focus an element on navigation" feature. 

Remove `Selector="h1"` to avoid that. 

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#focus-an-element-on-navigation

**Comment by vnbaaij** [comment]
I was about to say that. Not an issue. Just some standard templates configuration. Closing this

**Comment by marqdouj-spartan** [comment]
Perhaps the template should be updated to not use the h1 on the home page.

**Comment by dvoituron** [comment]
That's a default feature, often requested by Accessibility tools.

**Comment by marqdouj-spartan** [comment]
I tried this and get the same results:

<FluentLabel Appearance="Appearance.Accent" Typo="Typography.H1">Hello World!</FluentLabel>

**Comment by marqdouj-spartan** [comment]
okay... the post stripped out the FluenLabel stuff.

`
<FluentLabel Appearance="Appearance.Accent" Typo="Typography.H1">Hello World!</FluentLabel>
`

**Comment by marqdouj-spartan** [comment]
my bad... I didn't realize there was a `Selector="h1"` - I thought you meant to not use h1 in the home page.... Doh!
