### ISSUE TITLE
Time picker lost the precision

### ISSUE THREAD

**Issue by kamazheng** [microsoft/fluentui-blazor#1266]
As title says, when Datetime is with more than second precision, it will be lost. The current time picker cannot keep the same precision, please consider adding new time picker for this situation.
Thanks.

**Comment by dvoituron** [comment]
How do you intend to do this? Because we're using the default HTML Input Time component and this `step` attribute doesn't seem to be working properly.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#using_the_step_attribute

**Comment by vnbaaij** [comment]
Closing as not actionable.

**Comment by kamazheng** [comment]
My datetime is from MsSql datetime2(3), after binding-value with FluentTimePicker, the millisecond will lose.

**Comment by dvoituron** [comment]
I understand, but I don't think the component will be able to fix this. It rounds up the value to what the web component proposes. You may need to keep the original value to handle these seconds.
