### ISSUE TITLE
fix: interactivity is not working until WASM is loaded in case of InteractivityAuto, only when FluentUI is used

### ISSUE THREAD

**Issue by vukasinpetrovic** [microsoft/fluentui-blazor#1269]
# 🐛 Bug Report

I installed the provided template to test out the Fluent UI and I also set it up manually on existing small test project. In both cases, project was set to Interactive Auto and in both projects when I accessed the Counter page, it was frozen until the WASM was loaded and there was no interactivity. It opens up the socket connection for Server interactivity and downloads WASM in the background, but it's not interactive until download is finished. 

On my small test project, it only started happening when I added FluentUI, before that it worked normally.
What can be the case? I'll attach zip files of both test projects and you can see it for yourself when you access the Counter page.

## 💻 Repro or Code Sample

BalzorFluentUI is project created with your template from Visual Studio.
BlazorTest-RM-Auto is my small test app where I tested basic functions of net .net 8 blazor.
[BlazorFluentUI.zip](https://github.com/microsoft/fluentui-blazor/files/13843301/BlazorFluentUI.zip)
[BlazorTest-RM-Auto.zip](https://github.com/microsoft/fluentui-blazor/files/13843302/BlazorTest-RM-Auto.zip)

## 🤔 Expected Behavior

Interactive Auto should work and not freeze the UI.

## 😯 Current Behavior
It block the UI until download is completed.

## 💁 Possible Solution

I hope it's just a configuration thing, but I don't see where the problem is as I also used provided template and the problem is happening there also.

## 🌍 Your Environment

I tried this on both mac and windows, so it's not OS related.

* OS & Device: MacOS and Windows
* Browser: Google Chrome
* .NET and FAST Version: .NET 8, Fluent 4.2.1

**Comment by vnbaaij** [comment]
Hi,

This is not a library issue but is a Blazor issue. See https://github.com/dotnet/aspnetcore/issues/52154 for more information.

**Comment by vukasinpetrovic** [comment]
@vnbaaij Oh my god, this is really weird. I could have bet that it worked normally prior to adding FluentUI. I'm really sorry for bothering you with this bug report. I just tested again without FluentUI and the behaviour is same. Read that GitHub Issue and it made sense after they explained what is going on in the background. Thank you for quick reply, I would have not found that issue myself.

**Comment by vnbaaij** [comment]
No worries!
