### ISSUE TITLE
fix: Inconsistent visible/invisible behavior in FluentOverlay

### ISSUE THREAD

**Issue by askarhu** [microsoft/fluentui-blazor#1271]
# 🐛 Bug Report

<FluentOverlay> has a bindable Visible prop, which works when showing, or when setting to true, but it didn't work or hide the overlay when set to false, unless clicked on the overlay. Clearly looks like a bug.

## 💻 Repro or Code Sample

Set @bind-Visible to a variable and set the variable (app state) from a child component that does some network operations. The overlay showed (even that is a bit inconsistent) but never was able to dismiss the overlay unless a click was made on the overlay. I thought of tapping into the VisibleChanged event to set the StateHasChanged() but that seem to be not allowed since the "Visible" prop was bound.

## 🤔 Expected Behavior

Setting the @bind-Visible consistently shows and hides the overlay.

## 😯 Current Behavior

FluentOverlay doesn't hide when @bind-Visible is set to false. At times, even showing the overlay was also a bit buggy.

## 🌍 Your Environment

* OS & Device: Windows 10 laptop
* Browser Google Chrome, Edge
* .NET 8 and latest version of FluentUI 4.2.1

**Comment by vnbaaij** [comment]
I don't think this is a bug. It is pretty normal to close an overlay by clicking on it. Besides that it can also be closed with binding to the `Visible` parameter.

As you did not supply repo code, I can't confirm like that.
I tried it with this code (which is a copy of OverlayDefault) but with a change in the button's `@onclick`:
```
<FluentSelect Items=@(Enum.GetValues<JustifyContent>())
              OptionValue="@(c => c.ToAttributeValue())"
              TOption="JustifyContent"
              Position="SelectPosition.Below"
@bind-SelectedOption="@justification" />

<FluentSelect Items=@(Enum.GetValues<Align>())
              OptionValue="@(c => c.ToAttributeValue())"
              TOption="Align"
              Position="SelectPosition.Below"
@bind-SelectedOption="@alignment" />
<br />
<br />


<FluentButton Appearance="Appearance.Accent" @onclick="HandleOnOpen">Show Overlay</FluentButton>

<FluentOverlay @bind-Visible=@visible
               Opacity="0.4"
               Alignment="@alignment"
               Justification="@justification"
               OnClose="HandleOnClose">
    <FluentProgressRing />
</FluentOverlay>

@code {
    bool visible = false;
    JustifyContent justification = JustifyContent.Center;
    Align alignment = Align.Center;

    protected void HandleOnClose()
    {
        Console.WiteLine("Overlay closed");
    }

    protected async Task HandleOnOpen()
    {
        visible = true;
        Console.WriteLine("Overlay opened");
        await Task.Delay(2000);
        visible = false;
        Console.WiteLine("Overlay closed");
    }
}
```

So, you click the button, overlay appears, 2 secs later the overlay disappears because `visible` changed

**Comment by vnbaaij** [comment]
Closing this a s no further action from ous side needed. I'm adding the demo above to the demo site.

> I thought of tapping into the VisibleChanged event to set the StateHasChanged() but that seem to be not allowed since the "Visible" prop was bound.

This is standard Blazor binding code. You can use `Visible` and `VisibleChanged` together instead of `@bind-Value`. You can't combine them.
