### ISSUE TITLE
About the width properties of FluentSelect and FluentSelect components

### ISSUE THREAD

**Issue by sswi** [microsoft/fluentui-blazor#1272]
FluentSelect and FluentSelect components do not take effect when the Width property is less than 250px

 <FluentSelect Width="200px" TOption="string"/>
 <FluentCombobox Width="200px" TOption="string"/>

**Comment by vnbaaij** [comment]
Hi,

We have a template for raising issues. Please use that and supply code or a repository we can use to reproduce the issue. Help us to help you!

If you do not supply us with the information, the issue will be closed.
