### ISSUE TITLE
fix: [Width less than 250px does not take effect] in [FluentCombobox and FluentSelect]

### ISSUE THREAD

**Issue by sswi** [microsoft/fluentui-blazor#1274]
# 🐛 Bug Report
FluentSelect and FluentSelect components do not take effect when the Width property is less than 250px

## 💻 Repro or Code Sample

```xml
     <div style="display:grid;grid-template-rows:auto auto auto auto;grid-row-gap:10px;padding:20px;">
            <FluentCombobox TOption="string" Label="Default" />
            <FluentCombobox Width="120px" TOption="string" Label="Width=120px" />
            <FluentCombobox Width="250px" TOption="string" Label="Width=250px" />
            <FluentCombobox Width="100px" Style="min-width=50px;" TOption="string" Label="Width=100px and min-width=50px" />
     </div>
```

## 🤔 Expected Behavior
Width less than 250px should also take effect

## 😯 Current Behavior
![QQ截图20240107184202](https://github.com/microsoft/fluentui-blazor/assets/39110708/ef91aef0-a1ca-4e6b-9d84-4e0627d1c59c)

## 🌍 Your Environment
.Net8.0  BlazorApp 
Microsoft.FluentUI.AspNetCore.Components 4.2.1

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by dvoituron** [comment]
@sswi A workaround to use a style like this one: `min-width: 50px;`
