### ISSUE TITLE
docs: add example on how to increase/decrease font size using to

### ISSUE THREAD

**Issue by kzu** [microsoft/fluentui-blazor#1280]
# 🙋 Documentation Request

I want to implement a "Make Font Bigger/Smaller" pair of buttons on my site:

![image](https://github.com/microsoft/fluentui-blazor/assets/169707/d1055a7d-5825-4ad0-88e1-a399cca9e3fc)

From [this comment](https://github.com/microsoft/fluentui-blazor/issues/777#issuecomment-1733038859) it seems I should be able to do this by incrementing the BodyFont size (ramp?).

> Or better, you could set these variable values using the [Design Tokens](https://www.fluentui-blazor.net/DesignTokens) component (see section Sizing).

But I'm unsure on how to achieve that.

Here's my text size component so far:

```razor
@using Microsoft.FluentUI.AspNetCore.Components.DesignTokens
@inherits LocalizedComponent
@inject BodyFont BodyFont
@rendermode InteractiveAuto

<div>
    <FluentButton id="btnTextSize" Appearance="Appearance.Stealth" Title="@Localizer["Text size"]" OnClick="OnToggle">
        <FluentIcon Value="@(new Icons.Regular.Size20.TextFont())" Color="Color.Neutral" />
    </FluentButton>

    <FluentPopover AnchorId="btnTextSize" @bind-Open="showTextSize">
        <Body>
            <div class="links">
                <FluentButton IconEnd="@(new Icons.Regular.Size20.FontIncrease())" Appearance="Appearance.Accent" OnClick="OnIncrease" />
                <FluentButton IconEnd="@(new Icons.Regular.Size20.FontDecrease())" Appearance="Appearance.Accent" OnClick="OnIncrease" />
            </div>
        </Body>
    </FluentPopover>
</div>

@code {
    bool showTextSize = false;

    void OnToggle() => showTextSize = !showTextSize;

    void OnIncrease() => BodyFont.WithDefault("??");
    
    void OnDecrease() => BodyFont.WithDefault("??");
}
```

How would one achieve the relative incrementing/decrementing on each button click?

**Comment by kzu** [comment]
Ok, I got this to work: 

```razor
@using Microsoft.FluentUI.AspNetCore.Components.DesignTokens
@inherits LocalizedComponent
@inject TypeRampBaseFontSize FontSize
@rendermode InteractiveAuto

<div>
    <FluentButton id="btnTextSize" Appearance="Appearance.Stealth" Title="@Localizer["Text size"]" OnClick="OnToggle">
        <FluentIcon Value="@(new Icons.Regular.Size20.TextFont())" Color="Color.Neutral" />
    </FluentButton>

    <FluentPopover AnchorId="btnTextSize" @bind-Open="showTextSize">
        <Body>
            <div class="links">
                <FluentButton IconEnd="@(new Icons.Regular.Size20.FontIncrease())" Appearance="Appearance.Accent" OnClick="OnIncrease" />
                <FluentButton IconEnd="@(new Icons.Regular.Size20.FontDecrease())" Appearance="Appearance.Accent" OnClick="OnDecrease" />
            </div>
        </Body>
    </FluentPopover>
</div>

@code {
    bool showTextSize = false;
    string fontSize = "14px";

    protected override void OnInitialized()
    {
        base.OnInitialized();
        fontSize = FontSize.Value ?? "14px";
    }

    void OnToggle() => showTextSize = !showTextSize;

    void OnIncrease()
    {
        fontSize = int.Parse(fontSize[..^2]) + 2 + "px";
        FontSize.WithDefault(fontSize);
    }

    void OnDecrease()
    {
        fontSize = int.Parse(fontSize[..^2]) - 2 + "px";
        FontSize.WithDefault(fontSize);
    }
}
```

What's not working, however, is the (non)automatic adjusting of the relative font sizes when I change the base type ramp size. It's an issue also [in the underlying](https://github.com/microsoft/fast/issues/3233) library, it seems. Not sure how to account for it other than re-applying the same algorithm myself :(

**Comment by dvoituron** [comment]
Using your code, and adding a similar `TypeRampBaseLineHeight`, I get this result. What's wrong with this solution?

```csharp
void OnSetFontSize(int fontSize)
{
    FontSize.WithDefault(fontSize + "px");
    LineHeight.WithDefault(fontSize + "px");   // <=====
    this.fontSize = fontSize;
}
```

![1280](https://github.com/microsoft/fluentui-blazor/assets/8350694/a0ef73c1-683a-40bb-b3a2-068189c71dd7)

**Comment by vnbaaij** [comment]
Hi Daniel,

Do you need anything else to get this working as you want?

**Comment by Eagle3386** [comment]
@vnbaaij & @dvoituron Sorry for the necro, but just came across this.
The OP talked about _global_ font size de-/increment, didn't he?

Because right now, I'm struggling with how to _correctly_ & _most efficiently_ get a smaller font size for _one_ `FluentLabel` element within one of my components:
```razor
<BodyFont Value="@(new TypeRampMinus2FontSize().Value)">
  <FluentLabel>@Subtext</FluentLabel>
</BodyFont>
```
Is this the best syntax or is there a simpler one possible? 🤔

**Comment by dvoituron** [comment]
For one **FluentLabel**, you can use the `Style` property:

```html
<FluentLabel Style="font-size: 8px;">Hello World</FluentLabel>
```

**Comment by Eagle3386** [comment]
And if I'm aiming for "near-zero magic strings/values", i.e., rely on constants as much as possible?
Is there something like a `DesignTokens.BodyFont.TypeRampMinus2FontSize` constant we could use instead of `"8px"` or, better yet, even `font-size: 8px`?

**Comment by dvoituron** [comment]
Yes, you have CSS variables

```html
<FluentLabel Style="font-size: var(--type-ramp-minus-2-font-size);">Hello World</FluentLabel>
```

![Image](https://github.com/user-attachments/assets/0613cf38-5e4a-45dd-b0ba-af52ccc50887)

**Comment by Eagle3386** [comment]
@dvoituron 3 things:
1. Thanks _so_ much!
2. I guess, its CSS vars only then, no C#-based constants as I outlined above?
3. As asked in #1873, too, where do we find those lines?! 🤔

**Comment by Eagle3386** [comment]
I don't fully understand your first (2.) answer. The first half is clear.
However, the second ("define your values & send it to the client") isn't.
I'd like to either have some `Constants` class or some other mechanism to specify, via C# & C# only, that `Typography.Body`, on a specific occasion, should be 2 "type-ramps" smaller than it normally is.
Right now, that seems impossible & either CSS vars or (given the actual outcome, quite complex) Razor syntax is needed.

Regarding your screenshot: thanks for that. But my actually question is: where does that come from?
I mean, there must be a file where those lines are written - which file, in the repo's source code structure, is that? Please tell us! 😍

**Comment by vnbaaij** [comment]
> I don't fully understand your first (2.) answer. The first half is clear.
> However, the second ("define your values & send it to the client") isn't.
> I'd like to either have some `Constants` class or some other mechanism to specify, via C# & C# only, that `Typography.Body`, on a specific occasion, should be 2 "type-ramps" smaller than it normally is.

We don't have anything for that and is is technically not really feasible to transport from C# to CSS. 

> Right now, that seems impossible & either CSS vars or (given the actual outcome, quite complex) Razor syntax is needed.
> 
> Regarding your screenshot: thanks for that. But my actually question is: where does that come from?
> I mean, there must be a file where those lines are written - which file, in the repo's source code structure, is that? Please tell us!

They come from the web-components.js file which is loaded by us automatically. It is  in the Core.Assets project as a resource that gets loaded from a node module.

**Comment by Eagle3386** [comment]
I agree & will stick with CSS vars then. 😉

Special thanks for pointing out the file's location & name! 👍🏻
