### ISSUE TITLE
fix: Looping behaviour after update to 4.3.0 / FluentDesignTheme

### ISSUE THREAD

**Issue by woha** [microsoft/fluentui-blazor#1282]
I've updated to 4.3.0 and I'm having a strange behaviour now in my settings panel where the user can set the theme via the `FluentDesignTheme` component.

It looks like the color select list is populated in an endless loop:

![2024-01-09_09-16-35](https://github.com/microsoft/fluentui-blazor/assets/17140559/89bbcc48-1336-4e3c-9d3b-c5529523d424)

A sample repo is available here: https://github.com/woha/theme-demo

**Comment by vnbaaij** [comment]
There might be an issue with a cached script. Have you tried a full hard reload?

**Comment by woha** [comment]
Yes.
And I've also deleted the local storage for the the settings.

Look what's happening to the local storage:

![2024-01-09_09-47-35](https://github.com/microsoft/fluentui-blazor/assets/17140559/c8e8edab-9752-4e91-b6e1-379a80fe058c)

**Comment by dvoituron** [comment]
Hi,
I downloaded and ran your code, but without this problem... Weird.

https://github.com/microsoft/fluentui-blazor/assets/8350694/5bb6e49b-8687-4e0b-8490-5776aa9ce54c

**Comment by dvoituron** [comment]
I get it... This problem also occurs on our demo site and seems to be due to the new "OfficeColor.Random".
We will update this and find a workaround as soon as possible.

**Comment by woha** [comment]
Thank you very much for your support, Denis.
Glad you can reproduce it and it’s not something stupid in my code.
Please let me know, if I can be of any help or assistance.

**Comment by woha** [comment]
@vnbaaij / @dvoituron Thank you for fixing this!
