### ISSUE TITLE
fix: flickering on page load/reload

### ISSUE THREAD

**Issue by vukasinpetrovic** [microsoft/fluentui-blazor#1286]
# 🐛 Bug Report
When page loads, or reloads, the whole UI flickers for a very short period of time. It looks like css is not loaded for a brief moment and then is applied. I tried this effect with pure blazor project, both with and without fluent UI and on regular one (with bootstrap), it does not happen (see video below).

## 💻 Repro or Code Sample
Both examples are default new projects with visual studio template (with and without fluent).

## 🔦 Context
Both pages are using Static Server Rendering, so there is no interactivity on them. I tried removing the rendermode from NavMenu on Fluent example, but that does not change the behaviour, as the whole page is flickering, not just the nav menu (you can see even header is doing it.

### One note is that it only happens on page initial load and reloads, but if I navigate though the menu, it works fine.

Here is the video where it is shown.

https://github.com/microsoft/fluentui-blazor/assets/23005422/946ff45f-7777-463c-9f35-fc68e310b8ab

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Hi,

We are using script based theming ( coming from the web components script. This can only be applied once Blazor has loaded. That is why you see the flash. 
We have come up with a way to prevent that by using another script/web component independently from Blazor, which we do not want to include in the templates by default.  
The documentation page at https://www.fluentui-blazor.net/DesignTheme describes what you need to do to implement it in your own application.

**Comment by vukasinpetrovic** [comment]
@vnbaaij Thank you for that info, again I missed it when I read the docs. It works as expected and I'm fine with that implementation as long as it's working. But, I have one issue now where initially mode is set as dark and when I reload the page or change the page through navigation, it then sets to light mode and after that it's working fine, it's only on initial load probably as it does not have anything set in localStorage. How can I set that light mode of default office color is actually default? I'm missing something right?


```razor
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="PovratneTure.styles.css" />
    <link rel="icon" type="image/png" href="favicon.ico" />
    <HeadOutlet />
</head>

<body>
    <script src="_content/Microsoft.FluentUI.AspNetCore.Components/js/loading-theme.js" type="text/javascript"></script>
    <loading-theme storage-name="theme"></loading-theme>

    <FluentDesignTheme Mode="DesignThemeModes.Light" OfficeColor="OfficeColor.Default" StorageName="theme" />
    <Routes/>
    
    <script src="_framework/blazor.web.js"></script>
    <script src="_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js" type="module" async></script>
</body>

</html>
```

**Comment by vnbaaij** [comment]
Are you running into this: https://github.com/microsoft/fluentui-blazor/issues/1259?

p.s. I think you don't need the last `<script>`-line

**Comment by vukasinpetrovic** [comment]
Just looked at it and I think for me it's a bit different. My problem is that it reads from localStorage, but initially there is no setting in the localStorage, until I click on navigation link, so it default to system (which is currently dark mode). How can I set it that the default and initial value is light mode, as I never want to use dark mode for my app? Do I have to manually write to localStorage on page load, or there is setting somewhere to be set?

**Comment by vnbaaij** [comment]
You can "force" the Light theme using a syntax like <loading-theme mode="light" />

**Comment by vukasinpetrovic** [comment]
Figured it out, I had to set mode and office-color attributes to loading-theme element

```html
<loading-theme mode="light" office-color="default" storage-name="theme"></loading-theme>
```

**Comment by schaveyt** [comment]
I'm just encountering this as well. Let's see if I can repeat the success.
