### ISSUE TITLE
fix: CheckBox sends "on" value for bool field

### ISSUE THREAD

**Issue by vukasinpetrovic** [microsoft/fluentui-blazor#1293]
# 🐛 Bug Report
Hope I'm not too annoying with opening issues these couple of days, but I'm using the library extensively for a new project. I really appreciate your work and quick replies.
What I stumbled upon right now is that in default project template with FluentUI, if I click on "Remember Me" on Login page, I get the validation error saying "The value 'on' is not valid for 'RememberMe'.". I checked in network tab and indeed it sends string "on" for remember me value. 

![image](https://github.com/microsoft/fluentui-blazor/assets/23005422/a180226d-1442-4efa-a27f-6eceb5fdae7a)

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by dvoituron** [comment]
It seems that the `value` attribute of the checkbox is empty. So the default value is "on".
We take a look.

**Comment by dvoituron** [comment]
See #1319

**Comment by vnbaaij** [comment]
This is fixed with #1319

**Comment by joriverm** [comment]
Hey i just came across this when writing tests for our project and i thought value was the checked state of the checkbox :D
after some digging i came across this issue/PR. is the value attribute needed of the fluent checkbox? i dont see it when looking at the learn/demo page of the web components so no idea where it comes from?

https://learn.microsoft.com/en-us/fluent-ui/web-components/components/checkbox?pivots=typescript

**Comment by vnbaaij** [comment]
It is needed to set the initial value of the checkbox. Bit strange but until we get WebComponents v3, this will have to do.

**Comment by joriverm** [comment]
thats ok, thanks!
i know the webcomponents v3 is coming and a big refactor is coming with it. just checking!
