### ISSUE TITLE
fix:  FluentDatePicker unable to bind to a non-nullable value?

### ISSUE THREAD

**Issue by f2bo** [microsoft/fluentui-blazor#1296]
# 🐛 Bug Report

Binding a non-nullable DateTime property to a standard Blazor `InputDate` component is allowed. However, if the component is replaced by a `FluentDatePicker` the code fails to compile.

## 💻 Repro or Code Sample

```razor
@page "/test"
@rendermode InteractiveServer
@using System.ComponentModel.DataAnnotations
@inject ILogger<Test> Logger

<PageTitle>Test</PageTitle>

<EditForm Enhance Model="Model" OnValidSubmit="Submit" FormName="Test">
    @* <InputDate @bind-Value="Model!.DueDate" /> *@
    <FluentDatePicker @bind-Value="Model!.DueDate" />
    <FluentButton Type="ButtonType.Submit" Appearance="Appearance.Accent">Submit</FluentButton>
</EditForm>

@code
{
    [SupplyParameterFromForm]
    public Foo? Model { get; set; }

    protected override void OnInitialized()
    {
        Model ??= new() { DueDate = DateTime.Today };
    }

    private void Submit()
    {
        Logger.LogInformation("DueDate = {DueDate}", Model!.DueDate);
    }

    public class Foo
    {
        [Required]
        public DateTime DueDate { get; set; }
    }
}
```

The code compiles and works correctly once the property is made nullable.

```C#
public class Foo
{
    [Required]
    public DateTime? DueDate { get; set; }
}
```

## 🤔 Expected Behavior

Component should support binding to a non-nullable property.

## 😯 Current Behavior
Compilation fails with the following error:
```
CS1503	Argument 2: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<System.DateTime>' to 'Microsoft.AspNetCore.Components.EventCallback'
```

## 🌍 Your Environment
```
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\
 Browser: Microsoft Edge
```

```
Microsoft.FluentUI.AspNetCore.Components Version="4.3.0"
```

**Comment by dvoituron** [comment]
We've already talked about it here: #846

**Comment by f2bo** [comment]
True. I can see that this was mentioned in the issue you linked. The justification there for requiring the bound field to be nullable is so that it can be cleared, something that is not always desired. Moreover, it's different from the behavior of the built-in InputDate Blazor component and it's not immediately obvious, at least to me, that "_Cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<System.DateTime>' to 'Microsoft.AspNetCore.Components.EventCallback'_" means that I need to change the bound field to be nullable. 

I watched your .NET Conf session and I'm just beginning to explore the FluentUI components. My, perhaps incorrect, assumption was that I would mostly be able to replace the standard components with the components in this library without significant effort, at least initially. Later, as I become more familiar with the library, I can start customizing the UI to take advantage of its features. Is that not the case?

**Comment by vnbaaij** [comment]
Your assumption is/was indeed not entirely correct. I don't believe we have suggested anywhere that our input/form related components are drop in replacements for the standard Blazor components. If we did, please let us know where so we can correct it.

**Comment by f2bo** [comment]
> I don't believe we have suggested anywhere that our input/form related components are drop in replacements for the standard Blazor components.

No. I can't say that I can point to any specific place where you make such claim.  Perhaps it was my expectation and, in my opinion, highly desirable. At least, in cases such as this one where I fail to see an advantage in diverging from the behavior of the standard control. 

In any case, thank you for building this library. Feel free to close the issue if this will not be considered.

**Comment by vnbaaij** [comment]
We'll close this one. As discussed in the other issue, we will look into binding both nullable and non-nullable values.

**Comment by dvoituron** [comment]
Indeed, we try to be as close as possible to existing components. Sometimes it's not easy to maintain ease of use with innovative new features. In this particular case, we're probably going to make the component evolve to have this feature.

**Comment by HunterAhlquist** [comment]
Any movement on this?

**Comment by vnbaaij** [comment]
> Any movement on this?

Not before v5
