### ISSUE TITLE
feat: allow navigation via `FluentWizardStep` label

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#1299]
# 🙋 Feature Request

First of all, I love the new `FluentWizard` component! You guys really did a great job!
However, I'm missing one essential feature: navigating to a step by clicking on its label.
I could probably achieve this myself using the `StepTemplate` but I think this is a feature that many people would like to get implemented.

You could then maybe add a "Linear" (or something similar) parameter to the wizard, which would only allow navigating to the previous and next steps of the active step (which is somewhat similar to the current behavior, I guess?).

## 🤔 Expected Behavior

When clicking on a `FluentWizardStep`'s label or its icon, the active step should change to the clicked step (at least, if the step is not disabled).

## 😯 Current Behavior

Currently, the label is just simple text with no functionality.

## 💁 Possible Solution

Adding an `@onclick` handler to a step's icon and title elements that updates the wizard's `Value` to the step's `Index` should hopefully do the trick.

**Comment by dvoituron** [comment]
Thank you very much for your feedback.

Personally, I don't think this is a feature that should be added **by default**: such a `Wizard `component shouldn't have the same purpose as a `Tabs `component. I think this could have a negative impact on usage.
But I can understand how this feature could be useful in your case. As you mentioned, it's possible to customize the component via `TemplateStep`.

Now, if this feature is in high demand, why not. 😀

**Comment by hksalessio** [comment]
Hm, I do get your point.
Maybe limiting this feature to steps that have already been visited would differentiate it from regular tabs?
Because usability would also be negatively impacted if the wizard has 10 steps and a user wants to go from the last one to the first to make some adjustments 😅

**Comment by dvoituron** [comment]
Yes, make sense.

**Comment by dvoituron** [comment]
Will be fixed when this PR #1909 will be merged (next release)
