### ISSUE TITLE
feat: add When the screen is small, the menu automatically collapses

### ISSUE THREAD

**Issue by HuaFangYun** [microsoft/fluentui-blazor#1300]
![image](https://github.com/microsoft/fluentui-blazor/assets/30250585/31db52d8-53be-46e9-8af2-aec63d2d4481)
When the screen is small, the menu automatically collapses

**Comment by vnbaaij** [comment]
When using the template to create a new application, the menu will automatically collapse to the top once the screen width is smaller than 600px. Works the same as the standard Blazor template:

![navmenu-collapse](https://github.com/microsoft/fluentui-blazor/assets/1761079/5b800d02-4629-4276-a0d1-8947df809a46)

**Comment by HuaFangYun** [comment]
Thank you. I used the old version of the template, which has been updated and has found this highlight. I have been using Ant Blazor development, this is very good, recently I want to try to use Fluent UI
