### ISSUE TITLE
feat: make Autocomplete set its height automatically

### ISSUE THREAD

**Issue by aco-mreble** [microsoft/fluentui-blazor#1302]
# 🙋 Feature Request
I would like to see the Autocomplete component set its height dependend on the selected items automatically. 
## 🤔 Expected Behavior
Like in outlook.com:
![image](https://github.com/microsoft/fluentui-blazor/assets/139233990/8e8c06ea-c8f3-4a87-8c8f-bd270caf3362)

## 😯 Current Behavior
The items are only shown horizontally and overflow if too many items where selected
![image](https://github.com/microsoft/fluentui-blazor/assets/139233990/8f0791df-fd4f-4e02-807a-90d6e26e1646)

## 💁 Possible Solution
Use a text-area instead and do the rest with flexbox magic

**Comment by dvoituron** [comment]
It could be interesting. Let's see what can be done

In the meantime, you can add a style `overflow: auto;` to display a scrollbar. It's not the same result, but it may help you out.

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/86020801-8ff0-4821-bd83-c0a2692f85d9)

By the way, I see that there's a bug in the component that should display left/right arrows at the extremes of the Textfield, when there are more elements than space.

**Comment by ra-one** [comment]
I think setting height automatically would not be the desired in all cases, may be a flag to indicate if auto-height is enabled or not. Display flipper (left/right arrow) if auto-height is disabled.

**Comment by ra-one** [comment]
@dvoituron can you please link the bug you mentioned in component, for tracking purpose.
With workaround of `overflow: auto;` the scrollbar  does appear but since i have fixed `height` and `width` autocomplete box, the selected items still overflow the box.

![image](https://github.com/microsoft/fluentui-blazor/assets/2285281/d42d7b1d-b550-46d3-9e65-8fb6b8d09fc5)

**Comment by dvoituron** [comment]
I haven't created any new bugs. I've updated to version 4.4.

**Comment by dvoituron** [comment]
See #1302
