### ISSUE TITLE
fix: FluentDataGrid throws dbContext exception when used with EF Core

### ISSUE THREAD

**Issue by vukasinpetrovic** [microsoft/fluentui-blazor#1304]
# 🐛 Bug Report
I setup the FluentDataGrid to use EF Core dbContext like in the examples and it loads and displays the data fine, but the problem occurs when I click on sorting the column twice or fast consecutively. It then executes multiple operations on dbContext and breaks with the exception below.

![image](https://github.com/microsoft/fluentui-blazor/assets/23005422/68e98969-f836-4cf8-87a0-f4ef647c0571)

## 💻 Repro or Code Sample
```razor
@page "/users"
@rendermode InteractiveServer

@using PovratneTure.Data
@inject ApplicationDbContext DbContext

<h3>Users</h3>

<FluentDataGrid Items="@DbContext.Users">
    <PropertyColumn Property="@(u => u.Email)" Sortable="true" />    
    <PropertyColumn Property="@(u => u.UserName)" Sortable="true" />    
</FluentDataGrid>
```

## 💁 Possible Solution
I tried experimenting with setting different ServiceLifetime options when registering dbContext, but non of them affected this problem, it occurred on all options.

```razor
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString)), 
    ServiceLifetime.Transient
);
```

## 🔦 Context
I tried this with QuickGrids, but there this problem is not present, so I'm concluding it's regarding this library.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vukasinpetrovic** [comment]
@cduluCNB Yes I did and I registered it in builder.services. Generally the datagrid works, it loads the data and displays it, it sorts, that's all ok, but if I double click sort (call it two times quickly), it then throws this exception as it executes two queries on the same dbContext. I assume this would also happen if I paginate quickly, but I'll have to add more data in table to test that.

Here is the project if you need it for testing. It's almost plain template.
[PovratneTure.zip](https://github.com/microsoft/fluentui-blazor/files/13908364/PovratneTure.zip)

**Comment by vnbaaij** [comment]
Hi @vukasinpetrovic,
I have not worked with EF in a looong time. Can you supply some instructions on how to get the zipped project to work. I do not fancy to install MySQL. Can it run on mssql localdb?

**Comment by vukasinpetrovic** [comment]
@vnbaaij It should run fine with mssql. There are three things that you should do to make it work.

1. Change line 29 in Program.cs to:
```c#
builder.Services.AddDbContextFactory<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString)
);
```

2. Adjust connection string in appsettings.json to something like:
``` 
"DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=YourTestDatabaseName;Trusted_Connection=True;MultipleActiveResultSets=true"
```

3. Run command `dotnet ef database update` to execute migrations

**Comment by vnbaaij** [comment]
2.5. Change a buch of data types in the ..._initial.cs because MSSQL does not recognize MySQL type
3. As above
4. 
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/e6bfcea9-5bc8-49af-af51-ae8f554d6f6b)

Sorry, but this takes too much time to get to the actual issue. Can you supply a ready-to-run repo/zip?

**Comment by vukasinpetrovic** [comment]
Ahh, sorry. Delete the Migration folder and run these two commands to generate new migrations:
`dotnet ef migrations add Init` this one generates new migration
`dotnet ef database update` this one executes them to database

In the meantime, I'll additionally provide you with a ready-to-run zip. I'll try to do it in next 15 minutes.

**Comment by vnbaaij** [comment]
No rush, It is bed time over here so won't look at it for the next couple of hours

**Comment by vukasinpetrovic** [comment]
[PovratneTure-MSSQL.zip](https://github.com/microsoft/fluentui-blazor/files/13909112/PovratneTure-MSSQL.zip)

**Comment by vnbaaij** [comment]
Ok, got it working. Added 2 users and then went to Users page and sorted colums as quickly as I could. No errors whatsoever...
![issue-#1304](https://github.com/microsoft/fluentui-blazor/assets/1761079/36f953e7-11f0-4451-ac88-781acbd74aa3)

Nt sure how we can help you further with this

**Comment by vukasinpetrovic** [comment]
@vnbaaij Hmm, is it possible that it's because of MySQL and it's provider library (Pomelo)?

**Comment by vukasinpetrovic** [comment]
Thank you for taking time to test this. I'll try to investigate deeper on why is it happening with MySQL only. I tried it quickly with SQLite and it's ok there, so this must be MySQL only problem.
