### ISSUE TITLE
How to vertically center slider controls?

### ISSUE THREAD

**Issue by kzu** [microsoft/fluentui-blazor#1308]
Given the following:

```razor
<FluentStack VerticalAlignment="VerticalAlignment.Center" Style="background-color: cornflowerblue;">
    <FluentBadge Appearance="Appearance.Accent">
        100 words &nbsp;
        <FluentIcon Value="@(new Icons.Filled.Size12.ArrowBidirectionalUpDown().WithColor(Color.Lightweight))" />
    </FluentBadge>
    <FluentSlider Style="background-color: red;" Min="0" Max="100" Step="10" Value="0" />
</FluentStack>
```

The slider doesn't render vertically centered:

![image](https://github.com/microsoft/fluentui-blazor/assets/169707/a7705438-5eb4-4360-9254-34e84abb8b23)

I've tried all sorts of combinations of CSS alignment attributes but I can't figure out how to tell the slider to align its parts vertically centered (via style or otherwise). Any tips? 

The goal is to have the slider be vertically centered (both thumb and track) with regards to other elements in the same "row" (flex-wise)

**WORKAROUND**

Set the slider height, such as: `Style="calc((var(--design-unit) + var(--stroke-width)) * 1px)"`

**Comment by vnbaaij** [comment]
I've come this far:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/29bfdf4c-b11c-40aa-82fb-83b448bc5e08)
By using this CSS:
```
::deep fluent-slider::part(positioning-region) {
    align-items: center;
    border: 1px solid red;;
}

::deep fluent-slider.horizontal::part(track-container) {
        align-self: auto;
    }

::deep fluent-slider.horizontal::part(thumb-container) {
    transform: translateX(calc(var(--thumb-size) * 0.5px)) translateY(0);
}
```

You should be able to get that adapted to your use case.

**Comment by kzu** [comment]
wow, I wish there was more docs on the `::part` and what parts each control has for advanced styling like this. Totally awesome CSS-fu, sir!

**Comment by kzu** [comment]
I wonder if a vertically centered display couldn't be just a built-in property (like VerticalAlignment) that automatically causes those styles to apply 🤔

**Comment by vnbaaij** [comment]
I tend to agree. But that would need to be implemented at the web component level then...
