### ISSUE TITLE
fix: Problems with validation border color / validation classes in FluentDatePicker / FluentAutocomplete

### ISSUE THREAD

**Issue by FritzTheCat9** [microsoft/fluentui-blazor#1311]
# 🐛 Bug Report

FluentDatePicker validation border is green when field validation fails. Field have had applied multiple validation classes (valid and invalid at the same time). It looks like a bug. 

Im using FluentValidation for validation and Im making wrappers for FluentUI components. Validation messages are showing but validation css classes on fluent-text-field are not correct. 

For FluentTextField component everything is ok and works as expected. But for FluentDatePicker there is green border when walidation fails and for FluentAutocomplete there is no border being shown.

## 💻 Repro or Code Sample

**CreateEventDialog.razor - form to create event model containing XTextField, XDatePicker and XDictionaryItemPicker**
```

@implements IDialogContentComponent<CreateEvent.Command>

@inject IEventApiClient EventApiClient
@inject IExceptionHandler ExceptionHandler

<EditForm Model="Content" OnValidSubmit="HandleValidSubmit">
    <CustomValidator @ref="CustomValidator" />
    <FluentValidationValidator />

    <FluentDialogBody>
        <XTextField @bind-Value="Content.Name" For="(() => Content.Name)" Label="Name" />
        <FluentValidationMessage For="(() => Content.Name)" />

        <XDatePicker @bind-Value="Content.Date" For="(() => Content.Date)" Label="Date" />
        <FluentValidationMessage For="(() => Content.Date)" />
            
        <XDictionaryItemPicker @bind-Value="Content.CityId" DictionaryCode="@DictionaryCode.City" Label="City" Placeholder="Select city" />
        <FluentValidationMessage For="(() => Content.CityId)" />

        <XDictionaryItemPicker @bind-Value="Content.HallId" DictionaryCode="@DictionaryCode.Hall" Label="Hall" Placeholder="Select hall" />
        <FluentValidationMessage For="(() => Content.HallId)" />
    </FluentDialogBody>

    <FluentDialogFooter>
        <FluentButton Type="Fluent.ButtonType.Submit" Color="Fluent.Color.Info">Create</FluentButton>
    </FluentDialogFooter>
</EditForm>

@code {
    [CascadingParameter] FluentDialog Dialog { get; set; }
    [Parameter] public CreateEvent.Command Content { get; set; } = new();

    private CustomValidator CustomValidator;

    private async Task HandleValidSubmit()
    {
        try
        {
            await EventApiClient.CreateEvent(Content);
            await Dialog.CloseAsync(Fluent.DialogResult.Ok(true));
        }
        catch (MyValidationException validationException)
        {
            CustomValidator.DisplayErrors(validationException.Errors);
        }
        catch (Exception ex)
        {
            ExceptionHandler.HandleExceptions(ex);
        }
    }
}

```
**XDatePicker.razor - inherits FluentCalendarBase**

```
@inherits FluentCalendarBase

<FluentDatePicker Immediate="true" Value="Value" ValueChanged="OnValueChanged" ValueExpression="For" Label="@Label" autocomplete="@Autocomplete" style="width: 100%;" />

@code {
    [Parameter] public Expression<Func<DateTime?>> For { get; set; }
    [Parameter] public string Autocomplete { get; set; } = "off";

    private void OnValueChanged(DateTime? value)
    {
        Value = value;
        ValueChanged.InvokeAsync(Value);

        EditContext.NotifyFieldChanged(FieldIdentifier);
    }

    protected override bool TryParseValueFromString(string value, out DateTime? result, out string validationErrorMessage)
    {
        if (value == null || value.Length < 6)
        {
            result = null;
        }
        else
        {
            string[] formats = { "yyyy-MM-dd" };
            if (DateTime.TryParseExact(value, formats, CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime validDate))
            {
                result = validDate;
            }
            else
            {
                result = null;
            }
        }

        if (result.HasValue)
        {
            validationErrorMessage = null;
            return true;
        }
        else
        {
            validationErrorMessage = "Enter a valid date";
            return false;
        }
    }
}
```

**XDictionaryItemPicker.razor - inherits InputBase containing FluentAutocomplete**

```
@inherits InputBase<int?>
@inject IMyDictionaryItemApiClient MyDictionaryItemApiClient
@inject IExceptionHandler ExceptionHandler

<FluentAutocomplete SelectedOptions="DictionaryItems" Label="@Label" Placeholder="@Placeholder" style="width: 100%;"
                    TOption="MyDictionaryItemDto" OnOptionsSearch="SearchMyDictionaryItems" SelectedOptionsChanged="SelectedOptionsChanged"
                    OptionText="(item => item.Name)" MaximumSelectedOptions="1" AutoComplete="@Autocomplete">
    <SelectedOptionTemplate Context="item">
        <FluentLabel>
            @item.Name
        </FluentLabel>
    </SelectedOptionTemplate>
    <FooterContent Context="item">
        @if (!item.Any())
        {
            <FluentLabel Style="font-size: 11px; text-align: center; width: 200px;">
                No items found in dictionary with code: "@DictionaryCode"
            </FluentLabel>
        }
    </FooterContent>
</FluentAutocomplete>

@code {
    [Parameter] public string Label { get; set; }
    [Parameter] public string Placeholder { get; set; }
    [Parameter] public string DictionaryCode { get; set; }
    [Parameter] public MyDictionaryItemDto DictionaryItem { get; set; }
    [Parameter] public string Autocomplete { get; set; } = "off";

    private IEnumerable<MyDictionaryItemDto> DictionaryItems { get; set; } = [];

    protected override async Task OnInitializedAsync()
    {
        if (DictionaryItem is not null)
        {
            DictionaryItems = new List<MyDictionaryItemDto>() { DictionaryItem };

            Value = DictionaryItems.FirstOrDefault()?.Id;
            await ValueChanged.InvokeAsync(Value);

            EditContext.NotifyFieldChanged(FieldIdentifier);
        }
    }

    protected override bool TryParseValueFromString(string value, out int? result, out string validationErrorMessage)
    {
        result = DictionaryItems.FirstOrDefault()?.Id;
        validationErrorMessage = null;
        return true;
    }

    public async void SelectedOptionsChanged(IEnumerable<MyDictionaryItemDto> dictionaryItems)
    {
        DictionaryItems = dictionaryItems;

        Value = DictionaryItems.FirstOrDefault()?.Id;
        await ValueChanged.InvokeAsync(Value);

        EditContext.NotifyFieldChanged(FieldIdentifier);
    }

    public async Task SearchMyDictionaryItems(OptionsSearchEventArgs<MyDictionaryItemDto> e)
    {
        e.Items = await ReturnMyDictionaryItems(e.Text, DictionaryCode);
    }

    public async Task<List<MyDictionaryItemDto>> ReturnMyDictionaryItems(string searchText, string dictionaryCode)
    {
        PagedList<MyDictionaryItemDto> DictionaryItemsPagedList;

        var query = new GetAllMyDictionaryItemsByCode.Query
            {
                Page = 1,
                PageSize = 10,
                SortColumn = "name",
                SortOrder = SortOrder.Ascending,
                SearchTerm = searchText ?? "",
                DictionaryCode = dictionaryCode,
            };

        try
        {
            DictionaryItemsPagedList = await MyDictionaryItemApiClient.GetAllMyDictionaryItemsByCode(query);
            return DictionaryItemsPagedList.Items;
        }
        catch (Exception ex)
        {
            ExceptionHandler.HandleExceptions(ex);
            return new List<MyDictionaryItemDto>();
        }
    }
}

```
**XTextField.razor - inherits InputBase**

```
@inherits InputBase<string>

<FluentTextField Value="@Value" ValueChanged="OnValueChanged" ValueExpression="For" Label="@Label" style="width: 100%;" AutoComplete="@Autocomplete" />

@code {
    [Parameter] public Expression<Func<string>> For { get; set; }
    [Parameter] public string Label { get; set; }
    [Parameter] public string Autocomplete { get; set; } = "off";

    protected override bool TryParseValueFromString(string value, out string result, out string validationErrorMessage)
    {
        result = value;
        validationErrorMessage = null;
        return true;
    }

    private void OnValueChanged(string value)
    {
        Value = value;
        ValueChanged.InvokeAsync(Value);
    }
}
```

**CreateEvent - model binded to form**
```
using FluentValidation;
using MediatR;

    public class CreateEvent
    {
        public class Command : IRequest<int>
        {
            public string Name { get; set; }
            public DateTime? Date { get; set; }
            public int FederationId { get; set; }
            public int? CityId { get; set; }
            public int? HallId { get; set; }
        }

        public class Validator : AbstractValidator<Command>
        {
            public Validator()
            {
                RuleFor(x => x.Name)
                    .NotEmpty();

                RuleFor(x => x.Date)
                    .NotEmpty();

                RuleFor(x => x.CityId)
                    .NotEmpty();

                RuleFor(x => x.HallId)
                    .NotEmpty();
            }
        }
    }

```

**CustomValidator** - to handle validation errors from backend API

```
@code {
    [CascadingParameter] private EditContext EditContext { get; set; }
    private ValidationMessageStore _validationMessageStore;

    protected override void OnInitialized()
    {
        if (EditContext is null)
        {
            throw new Exception();
        }

        _validationMessageStore = new ValidationMessageStore(EditContext);

        EditContext.OnValidationRequested += ValidationRequested;
        EditContext.OnFieldChanged += FieldChanged;
    }

    public void ClearErrors()
    {
        _validationMessageStore.Clear();

        EditContext.NotifyValidationStateChanged();
    }

    public void DisplayErrors(Dictionary<string, List<string>> errors)
    {
        foreach (var error in errors)
        {
            _validationMessageStore.Add(new FieldIdentifier(EditContext.Model, error.Key), error.Value);
        }

        EditContext.NotifyValidationStateChanged();
    }

    private void ValidationRequested(object sender, ValidationRequestedEventArgs e)
    {
        _validationMessageStore.Clear();
        
        EditContext.NotifyValidationStateChanged();
    }
    
    private void FieldChanged(object sender, FieldChangedEventArgs e)
    {
        _validationMessageStore.Clear(e.FieldIdentifier);

        EditContext.NotifyValidationStateChanged();
    }
}
```

## 🤔 Expected Behavior

Validation classes should update correctly for FluentDatePicker and FluentAutocomplete. When there are validation errors, validation messages appear but border of FluentDatePicker is green and there is no border on FluentAutocomplete. <fluent-text-field> classes should update correclty for valid and invalid css classes.

## 😯 Current Behavior

**XDatePicker.razor - inherits FluentCalendarBase - green border when model is invalid (wrong behaviour)**

![Zrzut ekranu 2024-01-11 190035](https://github.com/microsoft/fluentui-blazor/assets/62745092/6830592b-7947-4419-851d-ea0d89230ee8)

![Zrzut ekranu 2024-01-11 190110](https://github.com/microsoft/fluentui-blazor/assets/62745092/4e200e43-0836-4f53-bd5f-04e5c76c51ef)

**XDictionaryItemPicker.razor - inherits InputBase containing FluentAutocomplete - no border when model is invalid (wrong behaviour)**

![Zrzut ekranu 2024-01-11 225540](https://github.com/microsoft/fluentui-blazor/assets/62745092/2af2affd-1887-4413-9bfd-ca6a139b4ab9)

**XTextField.razor - inherits InputBase - green border when model is valid. red border when model is invalid (good behaviour)**

![Zrzut ekranu 2024-01-11 190209](https://github.com/microsoft/fluentui-blazor/assets/62745092/dccda6c4-ab7d-48f4-806f-0264a056b594)

![Zrzut ekranu 2024-01-11 190235](https://github.com/microsoft/fluentui-blazor/assets/62745092/264f88de-6307-460c-b15d-5fbb83d6e084)

## 💁 Possible Solution

On this screenshot we can see that there are both "valid" and "invalid" class names on <fluent-text-field> tag. Something is not right with that. I dont know if i have knowledge why this happening. 

![Zrzut ekranu 2024-01-11 190110](https://github.com/microsoft/fluentui-blazor/assets/62745092/5f7f2b09-1084-4ce3-8b77-9d990086e1e0)

## 🔦 Context

Im trying to wrap this components to use them across some dialogs in my application. I want to have frontend and backend validation supported in my app. Backend validations work because i have CustomValidator showing errors from backend API. Also i have forntend validation (FluentValidation) fired on submit button click and when the field is changed. There are some problems with validation on FluentDatePicker and FluentAutocomplete. FluentText works ok.
Sorry for my english :P if something is not written well

## 🌍 Your Environment

Windows 11
Google Chrome
.NET 8
Microsoft.FluentUI.AspNetCore.Components" Version="4.3.0"

**Comment by vnbaaij** [comment]
Hi,

No need to appologize for your English. It is not my native language either and we are all allowed to make mistakes.

Assigning a class to indicate valid/invalid input is handeled in the `FluentInputBase` class (with the virtual `ClassValue` property). Most input components derive from this component, but `FluentAutoComplete` does not (yet). So that is why there is not border on invalid input. We plan to change that for a future version.

I'm not sure what is happening exactely with the DatePicker but I think it has something to do with that `ClassValue` not being set correctly.

Please supply a zip or a repo we can run to reproduce. Copying pasting and then getting it all to work takes us to much time.

**Comment by FritzTheCat9** [comment]
@vnbaaij 
I made a small program and added public repo with this error reproduced: 
https://github.com/FritzTheCat9/Blazor.FluentUI.BugWithValidation

FluentDatePicker:

![image](https://github.com/microsoft/fluentui-blazor/assets/62745092/8c395ad4-6167-4a14-a439-862e5cddcf07)

FluentAutocomplete:

![image](https://github.com/microsoft/fluentui-blazor/assets/62745092/1ec10fed-14c9-4b14-9882-5def2f9d243f)

**Comment by FritzTheCat9** [comment]
@vnbaaij
I was also testing FluentNumberField and ParseErrorMessage is still showing when i passed good int value.

Entering valid int: (ok)
![Zrzut ekranu 2024-01-12 164823](https://github.com/microsoft/fluentui-blazor/assets/62745092/744657b3-cc8c-47a9-943f-b4a9bb96a436)

Empty string passed: (ok - ParsingErrorMessage is shown)
![Zrzut ekranu 2024-01-12 164854](https://github.com/microsoft/fluentui-blazor/assets/62745092/c97a1168-4210-4c21-8cb9-69e559670b06)

Entering valid int second time: (wrong behaviour - ParsingErrorMessage should be hidden now since i entered a valid int value)
![Zrzut ekranu 2024-01-12 164929](https://github.com/microsoft/fluentui-blazor/assets/62745092/3c782e33-d24c-4638-905b-58e4bf9f413a)

On the other hand, FluentCheckbox works fine :)
Updated https://github.com/FritzTheCat9/Blazor.FluentUI.BugWithValidation repo with FluentNumberField bug reproduced.

**Comment by vnbaaij** [comment]
> @vnbaaij I was also testing FluentNumberField and ParseErrorMessage is still showing when i passed good int value.
> 
> Entering valid int: (ok) *snip*
> 
> Empty string passed: (ok - ParsingErrorMessage is shown) *snip* 
> Entering valid int second time: (wrong behaviour - ParsingErrorMessage should be hidden now since i entered a valid int value) *snip*
> 
> On the other hand, FluentCheckbox works fine :) Updated https://github.com/FritzTheCat9/Blazor.FluentUI.BugWithValidation repo with FluentNumberField bug reproduced.

Please create a separate issue for this!

**Comment by vnbaaij** [comment]
> @vnbaaij I made a small program and added public repo with this error reproduced: https://github.com/FritzTheCat9/Blazor.FluentUI.BugWithValidation
> 
> FluentDatePicker:
> 
> *snip*
> 
> FluentAutocomplete:
> 
> *snip*

I have come up with a solution for this. Will be fixed in next release
