### ISSUE TITLE
feat: add loading indicator to DataGrid

### ISSUE THREAD

**Issue by pk-hoh** [microsoft/fluentui-blazor#1317]
# 🙋 Feature Request

When used with remote data (items provider) it doesn't seem easily possible to add a loading indicator of some sorts. Using an overlay or similar won't work because a) toggling visibility in the data fetch request is not picked up automatically by Blazor and b) forcing a render update with "StateHasChanged" triggers the DataGrid to start yet another fetch request, which leads to all sorts of trouble.

## 🤔 Expected Behavior

It should be possible to give users a visual clue when remote data loading happens.

## 💁 Possible Solution

This could be a built-in feature like a `LoadingContent` render fragement in addition to `ChildContent` and `EmptyContent`, maybe even with the option to configure a delay to avoid flickering for short durations. Or expose a working loading flag that can be used in a flexible way to toggle some overlay or additional content in the child content render fragment.

## 🔦 Context

Sometimes loading data might be slow, for complex queries or during server-side warm-up or initial query compilation. I want to give users a clue that there's an ongoing operation to avoid bad UX.

**Comment by vnbaaij** [comment]
We will take it into consideration for next minor release.
