### ISSUE TITLE
[Fluent-Blazor.Net] Disrupted And Does Not Open

### ISSUE THREAD

**Issue by AmBplus** [microsoft/fluentui-blazor#1318]
https://www.fluentui-blazor.net/ Disrupted And Does Not Open
![image](https://github.com/microsoft/fluentui-blazor/assets/96792239/7085cfc7-4089-4fed-bea9-86f59b51af17)

Has Bellow Errors
MONO_WASM: instantiate_wasm_module() failed DOMException: The operation was aborted. [dotnet.runtime.8.0.1.9o34sz4099.js:3:12259](https://www.fluentui-blazor.net/_framework/dotnet.runtime.8.0.1.9o34sz4099.js)
MONO_WASM: ke@https://www.fluentui-blazor.net/_framework/dotnet.js:3:19020
Ll/e.instantiateWasm/<@https://www.fluentui-blazor.net/_framework/dotnet.runtime.8.0.1.9o34sz4099.js:3:201531
[logging.ts:32:12](https://raw.githubusercontent.com/dotnet/runtime/bf5e279d9239bfef5bb1b8d6212f1b971c434606/src/mono/wasm/runtime/loader/logging.ts)
Error in mono_download_assets: AbortError: The operation was aborted. [blazor.webassembly.js:1:46670](https://www.fluentui-blazor.net/_framework/blazor.webassembly.js)
Uncaught (in promise) DOMException: The operation was aborted. 7
Uncaught (in promise) Error: Failed to start platform. Reason: AbortError: The operation was aborted. 
    hn https://www.fluentui-blazor.net/_framework/blazor.webassembly.js:1
[blazor.webassembly.js:1:57366](https://www.fluentui-blazor.net/_framework/blazor.webassembly.js)
Uncaught (in promise) DOMException: The operation was aborted.
```[tasklist]
### Tasks
```

**Comment by vnbaaij** [comment]
Working fine here. Tried a refresh already?
