### ISSUE TITLE
Scrollbar for all controls does not look same in dark mode comparing with light mode.

### ISSUE THREAD

**Issue by acdotnet** [microsoft/fluentui-blazor#1322]
# 🐛 Bug Report

Scrollbar for all controls does not look same in dark mode comparing with light mode. The bg of scrollbar is white in dark mode.

## 💻 Repro or Code Sample

Dark mode
![image](https://github.com/microsoft/fluentui-blazor/assets/99289225/5701992d-c6f5-4951-809c-988ba393d394)

Light mode
![image](https://github.com/microsoft/fluentui-blazor/assets/99289225/655ed29e-b907-43dc-89ea-920707bfc1fb)

## 🤔 Expected Behavior

Scrollbars should look same in all color modes. In dark mode scrollbar bgcolor should be dark.

## 🌍 Your Environment

https://fluentui-blazor.net/ and all other fluentui blazor projects.

* OS & Device: Windows 11
* Browser: All

**Comment by dvoituron** [comment]
Hi,
I don't know if it's possible: this scrollbar is the browser's scrollbar and seems to be configurable only on Firefox (using `scrollbar-color`).
Do you know a way to change the color of a scrollbar in all browsers?

**Comment by acdotnet** [comment]
Could you please check this link https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_custom_scrollbar2 and and try /* width */
::-webkit-scrollbar {
  width: 20px;
  background: #0f0f0f;
}

/* Track */
::-webkit-scrollbar-track {
  box-shadow: inset 0 0 5px grey; 
  border-radius: 4px;
  background: transparent;
}
 
/* Handle */
::-webkit-scrollbar-thumb {
  background: red; 
  border-radius: 4px;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #b30000; 
}

I see in edge it looks like 
![image](https://github.com/microsoft/fluentui-blazor/assets/99289225/868a3f97-cae6-47f8-84c1-d54b4ec95b1a)

**Comment by dvoituron** [comment]
As describe in this doc: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
> This `CSS pseudo-element` is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

I don't think it's appropriate to use features that are specifically described as "not to be used". I think it's better to create a style directly in your project to handle this particular case. 

Furthermore, with your example, we're forcing all platforms to use a single scrollbar design, which is not (yet) provided for in the FluentUI model. And in your example, the up/down arrows are no longer present.

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/27d5c76b-8fa7-43e1-901c-e500fbdbb2f9)

If you can provide us with a complete CSS code, we could add it to the documentation.
Or if it's possible to change only the background and cursor color (without having to redraw the whole thing), we could include it in the Lib.

**Comment by acdotnet** [comment]
Will make changes in my poject, closing the issue.

**Comment by dvoituron** [comment]
If you have CSS, we can add it to the FluentUI-Blazor documentation, so that others can benefit from your reflection.

**Comment by marielsgtzz** [comment]
@acdotnet could you please share your solution? I'm also trying to have my scrollbars follow the current theme instead of having them always be white.

**Comment by JasonWeise** [comment]
@acdotnet I also would like to see your solution. Having non-styled scrollbars in dark mode breaks the visual fidelity of an app.
