### ISSUE TITLE
Rapidly clicking between UI component throws Microsoft.JSInterop.JSException

### ISSUE THREAD

**Issue by aliastopan** [microsoft/fluentui-blazor#1323]
# 🐛 Bug Report
Rapidly clicking between UI component randomly throw Microsoft.JSInterop.JSException: Cannot create a JSObjectReference from the value 'undefined' at FluentDataGrid.razor.cs:line 236

## 💻 Repro or Code Sample
My [repo](https://github.com/aliastopan/BlazorCustom).
The repo was just standard Fluent Blazor template with additional custom middleware.

## 🤔 Expected Behavior
Recklessly click the UI component should not break the application.

## 😯 Current Behavior
Not only I can reproduce this with every Blazor Fluent template, I'm also able to reproduce same anomaly on the
[official Fluent UI Blazor webpage](https://www.fluentui-blazor.net/Grid)

![exception](https://github.com/microsoft/fluentui-blazor/assets/18718365/c4057a12-7ec9-4a07-a146-10afb5ec16be)

## 🔦 Context
I was fooling around and expecting things to break and it did gave me "An unhandled error has occurred."

![fluent-blazor-exception](https://github.com/microsoft/fluentui-blazor/assets/18718365/3ee5e7ba-fcbe-4f48-a59b-45b817fc336e)

## 🌍 Your Environment

OS:
- Windows 10 (19045.3930)
- Ubuntu Server (22.04.3 LTS)

Browser:
Google Chrome Version 120.0.6099.217 (Official Build) (64-bit)

Nuget: 
"Microsoft.FluentUI.AspNetCore.Components" Version="4.3.1"

**Comment by vnbaaij** [comment]
With the fixes I made locally (in PR #1325) I can't get it to trigger in the template anymore. It does still happen on the demo site but that is because those pages do a bit of (slow) reflection for getting the documentation from the source code. Think it is defendable to have the 'error' occuring then when clicking around like crazy.
