### ISSUE TITLE
fix: FluentLayout expenders stop working after UI updates

### ISSUE THREAD

**Issue by TMUNYU** [microsoft/fluentui-blazor#1327]
# 🐛 Bug Report
Multiple events are being attached by 'attachEventHandlers' on the FluentNavGroup when updates are made on the page. 

## 💻 Repro or Code Sample
MainLayout.razor
https://github.com/TMUNYU/reproductions
![image](https://github.com/microsoft/fluentui-blazor/assets/1405525/d231c7ef-1a5b-4359-85a5-abbff494be20)
1. Click on the first menu item (group)
2. click on the 2nd menu item
3. click back on the group and observe that
    i. Open state has not been preserved 
    ii. The menu group is no longer expandable

This seems to be because the UI update is attaching more events to the group expander controls 

## 🤔 Expected Behavior
Should continue to expand and collapse
Should also preserve the expanded state post update 

## 😯 Current Behavior
FluentNavGroup stop expanding

**Comment by vnbaaij** [comment]
Please supply a complete sample that we can use to reproduce the issue. Your sample code fails as we do not have the pages used in the Hrefs and we also can't just paste this in a page because of the `@Body` being used.

**Comment by TMUNYU** [comment]
WebAssembly. Will supply the sample later on today

**Comment by TMUNYU** [comment]
> Please supply a complete sample that we can use to reproduce the issue. Your sample code fails as we do not have the pages used in the Hrefs and we also can't just paste this in a page because of the `@Body` being used.
> 
> Also provide us with detail in what type of Blazor project your are encountering this: Server/WebAssembly/Auto Rendermode, SSR, etc.

Updated the issue description with a reproduction repo. Hope that helps

**Comment by vnbaaij** [comment]
Although you project runs on WebAssembly, the `MainLayout` does not have a rendermode set so it will be running in SSR mode. A state will in that case never be maintained (as there is only HTML)

I will need todive deeper into the script to see where the expanding/collapsing is going wrong. Unfortunately I'm not a JS guru, so might take a bit

**Comment by vnbaaij** [comment]
Fix will be in next release. Code was moved in SSR handling script from `onUpdate` to `onLoad`
