### ISSUE TITLE
feat: Allow SVG Icon viewBox to be set via configuration instead of reusing icon size

### ISSUE THREAD

**Issue by TMUNYU** [microsoft/fluentui-blazor#1328]
# 🙋 Feature Request
Icons sizes being used for svg viewBox is a a little problematic when trying to use third party svgs. Can we either make the view port numbers configurable.

## 🤔 Expected Behavior
Be able to set the viewBox on the svg manually

## 😯 Current Behavior
This viewBox is currently built from the Icon.Size property which is an enum with insufficient granularity and range.

## 💁 Possible Solution
Allow the viewBox to be set by either ints or singly a string e.g "0 0 73 30"

## 🔦 Context
I would live to be able to add my own icons. Currently I can create a class inheriting from Icon to create my own svg icon. Only problem is that I cannot set the viewBox.

**Comment by dvoituron** [comment]
After a quick check of the code, we were able to add an `IconSize.Custom` enumeration. In this case, the **FluentIcon** component will use the icon content as a "raw" value and display the content as is.

Example, using a SVG with a size of 124x124.

```csharp
public class MyIcon : Microsoft.FluentUI.AspNetCore.Components.Icon
{
    private const string SVG_CONTENT = @"<svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 124 124"">
                                            <rect width=""124"" height=""124"" rx=""24""/>
                                            <path d=""M19.375 36.7818V100.625C19.375 102.834 21.1659 104.625 23.375 104.625H87.2181C90.7818 104.625 92.5664 100.316 90.0466 97.7966L26.2034 33.9534C23.6836 31.4336 19.375 33.2182 19.375 36.7818Z"" fill=""white""/>
                                            <circle cx=""63.2109"" cy=""37.5391"" r=""18.1641"" fill=""black""/>
                                            <rect opacity=""0.4"" x=""81.1328"" y=""80.7198"" width=""17.5687"" height=""17.3876"" rx=""4"" transform=""rotate(-45 81.1328 80.7198)"" fill=""#FDBA74""/>
                                            </svg>";

    public MyIcon() : base("MyIcon", IconVariant.Filled, IconSize.Custom, SVG_CONTENT)
    {
        // Default Color
        WithColor("#F97316");
    }
}
```

And you could use this icon like another:

```razor
<FluentIcon Value="@(new MyIcon().WithColor("red"))" Width="32px" />
<FluentIcon Value="@(new MyIcon())" Width="48px" />
```

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/ea858c19-aa5b-41cd-88f8-a9adbcecbf34)

But certain restrictions will apply: `FluentButton.Loading` or `Icon.ToMarkup` could be affected.

What do you think?

**Comment by TMUNYU** [comment]
This would work perfectly yes.

**Comment by dvoituron** [comment]
#1342 - Will be published in the next release
