### ISSUE TITLE
[Performance Issue] Combobox is taking lot of time to render when binding large chunk of data

### ISSUE THREAD

**Issue by PraleshGitHub** [microsoft/fluentui-blazor#1331]
# 🐛 Bug Report

Rendering of a combobox in a page is taking lot of time when binding a large chunk of data to it.

## 💻 Repro or Code Sample

Getting the list of servers. In the database there are thousands of servers. Fetching the server details through LINQ.
It takes not more than 2 to 3 sec for fetching 8k records. However taking very much for binding the list of records to Combobox and getting it render in browser.

<FluentCombobox Id="@nameof(ViewModel.Server)" Items="@Servers"
                Autocomplete="ComboboxAutocomplete.List"
                TOption="ServerViewModel"
                SelectedOptionChanged="@((option)=>ViewModel.Server = option)"
                Width="100%"
                class="userDefinedCB"
                SelectedOption="ViewModel.Server"
                Placeholder="Search by server name..."
                OptionText="@(item => item.Name)"
                Height="200px"
                Multiple="false"
                AriaLabel="XYZ">
</FluentCombobox>

## 🤔 Expected Behavior

Should not take much to render combobox with large set of data.

## 😯 Current Behavior

Taking ~1 to 1 1/2 min to load the page with 8k of records in combobox.

## 💁 Possible Solution
Not sure

## 🌍 Your Environment

* OS & Device: Windows
* Browser : Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET: NET 6 and FAST Version : 3.5.0(microsoft.fast.components.fluentui)

**Comment by vnbaaij** [comment]
Loading 8k items in a Combobox is never a good idea. All items will be loaded into the DOM so the page will get very heavy, even when just using standard HTML option elements. There will not be much we can do about that.

Think you need to re-think what interface to use for this.
