### ISSUE TITLE
FluentSwitch inside FluentTab does not work anymore (since 4.3.0)

### ISSUE THREAD

**Issue by martinbu** [microsoft/fluentui-blazor#1333]
# 🐛 Bug Report

Since version 4.3.0 a switch inside a tab does not update the bind-value anymore.

## 💻 Repro or Code Sample

I have added a test based on the latest dev branch in this [repository](https://github.com/martinbu/fluentui-blazor/tree/issue-switch-in-tab). Additionally, here the code that does not work anymore.

```
<FluentTabs>
    <FluentTab Label="Tab with Switch">
        <span>Enabled: @Enabled</span>
        <FluentSwitch @bind-Value="Enabled" />
    </FluentTab>

</FluentTabs>

@code {
    bool Enabled = false;
}

```

The bind-value updates once to `true` after clicking the switch. Afterwards, the bind-value does not change anymore.

**Comment by AlexDickerson** [comment]
Observed the same; the content of the tab will get rerender as expected once. However, the bound value are still being updated and switching to a different tab and back shows the expected content.

Assuming this is caused by the changes from: https://github.com/microsoft/fluentui-blazor/pull/1222

**Comment by vnbaaij** [comment]
@martinbu, @AlexDickerson this was indeed caused by #1222. Reverting those changes for next release

**Comment by geowong2022** [comment]
Hi @vnbaaij, I noticed that v3.5.1 also have this problem. And I think not only Switch is affected, same goes to other control. Can you confirm? Thanks. :)

**Comment by vnbaaij** [comment]
> Hi @vnbaaij, I noticed that v3.5.1 also have this problem. And I think not only Switch is affected, same goes to other control. Can you confirm? Thanks. :)

Yes. Reverted it and will release v3.5.2 today
