### ISSUE TITLE
Consider removing the `PageScript` component from the public API

### ISSUE THREAD

**Issue by MackinnonBuck** [microsoft/fluentui-blazor#1335]
In the future, Blazor may add framework features that render `PageScript` obsolete. It seems that `PageScript` was added to this repo as an internal implementation detail to support Fluent component functionality (although I could be wrong!), so it might be worth it to either:
* Make the `PageScript` component internal, or...
* Render the `<page-script>` custom element directly

That way, `PageScript` can be safely replaced with an alternative in the future without breaking customers who start taking a dependency on it.

Furthermore, in case customers define their own component based on the [`PageScript` docs example](https://learn.microsoft.com/aspnet/core/blazor/javascript-interoperability/static-server-rendering), it might also be worth it to rename the `page-script` custom element to `fluent-page-script` (or something similar) to avoid naming conflicts.

Some additional thoughts about this can be found in https://github.com/MackinnonBuck/blazor-page-script/issues/5#issuecomment-1894415425.

**Comment by vnbaaij** [comment]
We will rename component to FluentPageScwritp and web component to fluent-page-script for next release.

**Comment by MackinnonBuck** [comment]
@vnbaaij Is the `FluentPageScript` component intended to be used by consumers of this library? I'm worried that apps may start taking a dependency on it but get broken by its removal in the future (if a similar feature gets added as a Blazor framework feature). Would it work to either make `FluentPageScript` have `internal` visibility, or remove it and only use the `fluent-page-script` custom element?

Not trying to be pushy about this - if the goal was to provide a `FluentPageScript` component to customers, I think that's fine! Just want to make it clear that there might be reason to deprecate it in the future.

**Comment by vnbaaij** [comment]
We use it in the library to enrich our components in SSR scenarios. But think users can use it to enrich their own pages too (but only when using the library as well} 
As it is part of the library (now with a more unique name), I don't think there is a risk it won't work anynore if something changes on the Blazor side
