### ISSUE TITLE
fix: Slider for `Microsoft.Fast.Components.FluentUI` shows an error on the demo and documentation site for V.3.5.1

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#1340]
# 🐛 Bug Report

Slider for `Microsoft.Fast.Components.FluentUI` shows an error on the demo and documentation site for V.3.5.1

> An error has occurred: Failed to fetch dynamically imported module: https://calm-sea-053fa6a03-archivesv3.westeurope.3.azurestaticapps.net/_content/Microsoft.Fast.Components.FluentUI/Components/Slider/FluentSliderLabel.razor.js TypeError: Failed to fetch dynamically imported module: https://calm-sea-053fa6a03-archivesv3.westeurope.3.azurestaticapps.net/_content/Microsoft.Fast.Components.FluentUI/Components/Slider/FluentSliderLabel.razor.js

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/0d1b0349-d7c0-4f63-83bd-8f4d5775030d)

## 💻 Repro or Code Sample

https://calm-sea-053fa6a03-archivesv3.westeurope.3.azurestaticapps.net/Slider

**Comment by vnbaaij** [comment]
Fixed with v3.5.1 release
