### ISSUE TITLE
fix: Latest NuGet available is v3.5.0 but demo and documentation site says v3.5.1

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#1341]
# 🐛 Bug Report

Latest NuGet available is v3.5.0 but demo and documentation site says v3.5.1

https://www.nuget.org/packages/Microsoft.Fast.Components.FluentUI/#versions-body-tab

https://calm-sea-053fa6a03-archivesv3.westeurope.3.azurestaticapps.net/

## 💻 Repro or Code Sample

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/5e1942cc-51cf-4cc6-b541-4f1c21d95b20)

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/b74a0761-6ade-4896-a2de-21bfa40fcbc7)

**Comment by vnbaaij** [comment]
Hi Oscar,

Unfortunately, we can not use the same option with the previous version (3.5) as we have with current version (v4) where we have a prod site (www...) and a dev site (preview...).  So the v3 site will always show the latest in developent version (which is indeed 3.5.1) and that will not always be in sync with what is available on NuGet. 

I will update the banner on the site to reflect this situation.

**Comment by vnbaaij** [comment]
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/2d74a411-d3dd-4935-82c4-25a804ef9ed0)
(not deployed yet)
