### ISSUE TITLE
fix: FluentDataGrid sorting not working if implement OnRowFocus event

### ISSUE THREAD

**Issue by lcarnini** [microsoft/fluentui-blazor#1343]
# 🐛 Bug Report

Using FluentDataGrid in the template app , if I implement the OnRowFocus event method, there is no sorting happening anymore
The method get called even when i click on the header column

## 💻 Repro or Code Sample

FluentDataGrid  Items=@MyModels TGridItem=MyModel Virtualize="true" OnRowFocus="HandleOnRowFocus"
        
 
 
 private void HandleOnRowFocus(FluentDataGridRow< MyModel > r)
 {
     int idx = (r.RowIndex ?? 0) - 1;
     Selected= r?.Item;
 }`

## 🤔 Expected Behavior

Sorting the table iven if OnRowFocus implemented in custom component

## 😯 Current Behavior

sorting work if not implemented OnRowFocus
if using OnRowFocus event, no sorting happening and no error

## 🔦 Context
 
add row selection to FluentDataGrid , mantaining column sorting

## 🌍 Your Environment
windows
asp net core .8
visualstudio Community 2022 17.8.2
nugetpackages: 
Components: 4.3.1
DataGrid.EntityFrameworkAdapter: 4.3.1

**Comment by vnbaaij** [comment]
Hi,

You say in an app based on the template. What type of interactivity are you using? If nothing is specified, you are using SSR and sorting does not work then. 

As you haven't supplied reproducion code, we can't verify.

**Comment by lcarnini** [comment]
Thanks for the info.
I have @rendermode InteractiveServer in my component and  app.MapRazorComponents<App>()    .AddInteractiveServerRenderMode(); in Program.cs

Sorting is working fine if i comment out OnRowFocus on the grid definition, but i will watch closely differences i introduced from the template

**Comment by vnbaaij** [comment]
I added a `OnRowFocus` locally to a demo site example:
![issue-#1343](https://github.com/microsoft/fluentui-blazor/assets/1761079/e3017c92-07e5-4677-90d5-48c511f064d9)
You can see the row focus event being executed in the log console on the right. Can still sort...
