### ISSUE TITLE
fix: Keyboard navigation does not trigger value nor option change in Listbox

### ISSUE THREAD

**Issue by tocsi-hun** [microsoft/fluentui-blazor#1344]
# 🐛 Bug Report

When I select an item in a listbox via mouse I get the selected value. But when I navigate with the arrow keys up and down the visuals suggest the selection changed but no event is triggered.

## 🤔 Expected Behavior

When i change the selection with keyboard I should get the same selection/value/option changes like i get with mouse click.

**Comment by vnbaaij** [comment]
I'm adding functionality to make the keyboard selection work **but**, for now, it only works when the list based component (listbox, select, combobox, autocomplete) is using the `Items` parameter to specify the list items.
Making it work with a list where the itmes are manually specified is a lot more (complicated) work.

See below for how it works. First selection is done with click, then End, Home and arrows down/up:

![issue-#1344](https://github.com/microsoft/fluentui-blazor/assets/1761079/4de91b54-06db-4667-b26b-2d87801fa936)
