### ISSUE TITLE
docs: add How to use `DesignToken` object from JavaScript

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui-blazor#1346]
# 🙋 Documentation Request

I want to create a design token from JavaScript with a custom CSS name in order to use it on the loader screen.
I tried this with no luck
``` JS
import { DesignToken } from '/_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js';

DesignToken.create(
    'my-token', // This will not immediately emit to a CSS custom property
    "my-css-custom-property-name" // Emits to --my-css-custom-property-name
).withDefault(2);

DesignToken.registerRoot(); // Default values are now emitted
```

And the documentation says nothing about this case

**Comment by vnbaaij** [comment]
Hi,
This is not a scenario we are actively supporting from the Blazor library. It is more about using the web components script directly.
I'd suggest to use https://fluent-components.azurewebsites.net/?path=/docs/design-system-design-tokens--page

P. S the script import part looks good. We include and expose the web components script like this

**Comment by vnbaaij** [comment]
Maybe ask here: https://discord.com/channels/449251231706251264/1188317450199113748

**Comment by xperiandri** [comment]
I cannot open the link that you provided

**Comment by vnbaaij** [comment]
And this one from www home page:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/9f7ecb2e-55fc-43f4-b236-9fb1204c4508)

If you're in then go to the support forum there.

**Comment by xperiandri** [comment]
Thanks

Also I tried
``` C#
using System.Diagnostics.CodeAnalysis;

using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.FluentUI.AspNetCore.Components;
using Microsoft.FluentUI.AspNetCore.Components.DesignTokens;
using Microsoft.JSInterop;

public static class DesignTokensExtensions
{
    public static IServiceCollection RegisterDesignTokens([NotNull] this IServiceCollection services)
    {
        return services
            .AddSingleton<ToolbarIconsColor>();
    }

    public static async ValueTask RegisterDesignTokens([NotNull] this IServiceProvider serviceProvider)
    {
        await (await serviceProvider.GetRequiredService<ToolbarIconsColor>().Register()).WithDefault(Color.Accent);
    }
}

public class ToolbarIconsColor: DesignToken<Color>
{
    public ToolbarIconsColor() => base.Name = "toolbarIconsColor";
    public ToolbarIconsColor(IJSRuntime jsRuntime) : base(jsRuntime) => base.Name = "toolbarIconsColor";

    public ValueTask<DesignToken<Color>> Register() => base.Create(this.Name!);
}
```

and then in `App.razor`
``` C#
    override protected async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await ServiceProvider.RegisterDesignTokens();
        }
    }
```

but got
`Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'DesignToken.create' ('DesignToken' was undefined).
      Error: Could not find 'DesignToken.create' ('DesignToken' was undefined).`

**Comment by xperiandri** [comment]
@vnbaaij does that work?
