### ISSUE TITLE
fix: "i.addEventListener is not a function" in "Microsoft.FluentUI.AspNetCore.Components.lib.module.js":369"

### ISSUE THREAD

**Issue by JoaoLucasSR** [microsoft/fluentui-blazor#1350]
# 🐛 Bug Report

Error in the development console in the fluent library. Just opening the app and checking the console the error remains, the manual installation was done according to the documentation for a hybrid Maui blazor app.

`Microsoft.FluentUI.AspNetCore.Components.lib.module.js:369  Uncaught (in promise) TypeError: i.addEventListener is not a function
    at ea (Microsoft.FluentUI.AspNetCore.Components.lib.module.js:369:3103)
    at blazor.webview.js:1:45172
    at Array.map (<anonymous>)
    at _t.invokeAfterStartedCallbacks (blazor.webview.js:1:45164)
    at Object.xt [as start] (blazor.webview.js:1:48247)`
![image](https://github.com/microsoft/fluentui-blazor/assets/28392592/0839d7a9-5267-4c1e-92f5-71f6f4e3cdc2)

## 💻 Repro or Code Sample

![image](https://github.com/microsoft/fluentui-blazor/assets/28392592/ba5e883c-a831-4d4c-8aed-1b4673b84edb)
![image](https://github.com/microsoft/fluentui-blazor/assets/28392592/266213dc-1267-45ac-8078-9e5f24dfbc1d)

Error made on Windows 11 23H2 build 22631.3007 With .NET 8.0.101

## 🤔 Expected Behavior

No library error in development console.

## 😯 Current Behavior

It's trying to put an event listener on an object it doesn't support.
![image](https://github.com/microsoft/fluentui-blazor/assets/28392592/a240fe59-d17f-454c-884c-fb554407c17b)
![image](https://github.com/microsoft/fluentui-blazor/assets/28392592/6595b924-ffe6-48c2-8b9c-712ac05640dc)
![image](https://github.com/microsoft/fluentui-blazor/assets/28392592/5186523b-156c-42ef-9e16-3602bb00fa7c)

## 💁 Possible Solution

I don't know

## 🔦 Context

The validations that I was putting in the input were not being applied in the EditForm, when I evaluated it in the developer console I saw that I had this error, I don't know if it is what is preventing the validation. But all screens are showing this error.

## 🌍 Your Environment

MAUI Blazor Project

* OS & Device: Windows 11 23H2 build 22631.3007
* Browser MAUI WebView
* .NET 8.0.101 and FluentUI 4.3.1

**Comment by vnbaaij** [comment]
Going by you last screenshot, `blazor.webview.js` does not support the `addEventListener` function. Can confirm the error goes away if we check for existance of the function first.

I've added a check which will be in for the next version. (ETA in the coming days)
