### ISSUE TITLE
feat: Default Animation Support

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/fluentui-blazor#1351]
Default Animation Support for Most or All of the Fluent Blazor Controls, Having Default Animation for Most of the Controls would brings in Character to Fluent UI Blazor and etc..

For Example, When it comes to Fluent Select Component, The Flyout Could Really use some animation when opening and closing likewise having animation other controls would be awesome in usability stand point and etc..

**Comment by vnbaaij** [comment]
This has been discussed before. We are not going to add it ourselves (as it is not in the v2 web components and Fluent 1 design).

If it will be part of web components v3 (which follow Fluent 2 design), it will flow to our components as well.
