### ISSUE TITLE
fix: FluentNumberField ParseErrorMessage is showing when I enter a valid int value second time

### ISSUE THREAD

**Issue by FritzTheCat9** [microsoft/fluentui-blazor#1352]
# 🐛 Bug Report

I was testing FluentNumberField and ParseErrorMessage is still showing when i passed good int value.

Entering valid int: (ok)
![296290892-744657b3-cc8c-47a9-943f-b4a9bb96a436](https://github.com/microsoft/fluentui-blazor/assets/62745092/88e1a214-c1e3-4c4e-88f2-b255a8b98eab)

Empty string passed: (ok - ParsingErrorMessage is shown)
![296290899-c97a1168-4210-4c21-8cb9-69e559670b06](https://github.com/microsoft/fluentui-blazor/assets/62745092/824e6205-2a04-44a6-ab90-eddcb5a13884)

Entering valid int second time: (wrong behaviour - ParsingErrorMessage should be hidden now since i entered a valid int value)
![296290914-3c782e33-d24c-4638-905b-58e4bf9f413a](https://github.com/microsoft/fluentui-blazor/assets/62745092/aa8c7eb1-47c2-48d1-966f-de7509aa1a00)

On the other hand, FluentCheckbox works fine :)
Updated https://github.com/FritzTheCat9/Blazor.FluentUI.BugWithValidation repo with FluentNumberField bug reproduced.

**Comment by FritzTheCat9** [comment]
Can be related to: https://github.com/microsoft/fluentui-blazor/issues/1345

**Comment by vnbaaij** [comment]
Yes, it is a duplicate. Closing this one.
