### ISSUE TITLE
fix: color code of (neutral-fill-layer-rest) is wrong in [dark mode] with Template

### ISSUE THREAD

**Issue by speedypard** [microsoft/fluentui-blazor#1360]
I just started a new project with the template and set it to dark mode.
Then I discovered that The Stealth button is still visible because the background color is wrong with #333333.
![螢幕擷取畫面 2024-01-20 125049](https://github.com/microsoft/fluentui-blazor/assets/24541350/200687db-3790-484e-af93-ada81d16b9c6)

I modified the var(--neutral-fill-layer-rest) to #272727, which is the same as the [fluentui-blazor.net](https://www.fluentui-blazor.net/), then it looks better.
![螢幕擷取畫面 2024-01-20 125144](https://github.com/microsoft/fluentui-blazor/assets/24541350/5a80a2ab-7c76-4c2e-9795-4989eb88dd4d)

**Comment by vnbaaij** [comment]
Stealth it is not officially supported by the web components as a button appearance. You can change it to abbringen you like bit Wer won't make any changes on our side for it.

Closing this as not planned.

**Comment by vnbaaij** [comment]
Hi,

We can't adjust the values of the CSS variables as they are defined by the web components script we use. 

You can solve this by changing the background color of the body of the generated site (ie use a different CSS var for that property)

As you have not proved any code with which we can reproduce, I can't see what you did to change the theme. Normally the body should use `var(--neutral-layer-rest)` for its backgroud as well (as specified in reboot.css).

Closing this as workaround is provided
