### ISSUE TITLE
Clarify Nuget Package Usage for Blazor

### ISSUE THREAD

**Issue by perpetualintelligencegit** [microsoft/fluentui-blazor#1361]
We have been using Microsoft.Fast.Components.FluentUI for Blazor WebAssembly that was targeting .NET 6. Now we 2 packages

- Microsoft.Fast.Components.FluentUI
- Microsoft.FluentUI.AspNetCore.Components (.NET 8 as per doc)

Few questions:

I see updates being made for Microsoft.Fast.Components.FluentUI as well  what is the recommended Nuget package to use for Microsoft Fast components for Blazor ?

Is Microsoft.Fast.Components.FluentUI obsolete or going to be obsolete ?

**Comment by vnbaaij** [comment]
> We have been using Microsoft.Fast.Components.FluentUI for Blazor WebAssembly that was targeting .NET 6. Now we 2 packages
> 
> * Microsoft.Fast.Components.FluentUI
> * Microsoft.FluentUI.AspNetCore.Components (.NET 8 as per doc)

It is exactly as you describe. `Microsoft.Fast...` (ie the 3.x version) is for .NET 6 & 7. `Microsoft.Fluent...` (ie the 4.x versiom) is for .NET8.

New components and development is primarily taking place on the v4/.NET 8 versio,n of course. But we are still supporting and maintaining the 3.x version as wel. We plan to do so as long as .NET 6 (which is a LTS release) is supported. Don't expect any major new functionaliti to be added to the v3.x packages.

Closing this as not further action is needed.
