### ISSUE TITLE
fix: Unable to expand menu if initially unexpanded in BlazorWasm in FluentNavMenu

### ISSUE THREAD

**Issue by c0g1t8** [microsoft/fluentui-blazor#1370]
# 🐛 Bug Report

Create a Blazor WASM application from fluent templates (v4.3.1). Configure the menu to initially start in unexpanded mode. Clicking the hamburger does not expand the menu in desktop mode.

 

## 💻 Repro or Code Sample

Change line 13 in **NavMenu.razor** file to:

```c#
    private bool expanded = false;
```
Run application. Behaviour can be seen in desktop mode. 

## 🤔 Expected Behavior

Ability to toggle between expanded and unexpanded mode.

## 😯 Current Behavior

Toggling menu does not work.

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser: Microsoft Edge, Google Chrome
* .NET and FAST Version: net8 and v4.3.1

**Comment by c0g1t8** [comment]
Looking at the source of _FluentNavMenu.razor.js_

![image](https://github.com/microsoft/fluentui-blazor/assets/23250332/eedcdda3-5327-4d72-bfb1-f9d425671f59)

In line 6, **origStyle** is set when the menu is originally initialized. **origStyle** is unexpanded. **toggleMenuExpandedAsync** effectively changes nothing. 

I believe the fix would entail setting **origStyle** to the expanded style initially.

**Comment by vnbaaij** [comment]
The functionality in the `FluentNavMenu.razor.js` script is only supposed to be called in an SSR scenario. Currently it gets called even when interactivity is available. I'm in touch with the Bazor team to investigate.

**Comment by vnbaaij** [comment]
As said in #1387, there is nothing that can be done at the moment to change fact that menu uses the SSR script in a non SSR senario,
However, there have been some other chages to the scrip and component for v4.3.2 that makes you described scenario work so closing this one.
![issue-#1370](https://github.com/microsoft/fluentui-blazor/assets/1761079/e7cd4a45-249d-450f-85e7-4f44b4c77948)
