### ISSUE TITLE
Memory leak issue with FluentCard, FluentTextField, and FluentSelect

### ISSUE THREAD

**Issue by NguyenLamMS** [microsoft/fluentui-blazor#1377]
# 🐛 Bug Report

I am experiencing a memory leak issue with FluentCard, FluentTextField, and FluentSelect. When I display 1000 FluentCards on my Counter page, the memory usage of my application continuously increases. The memory is not released when I leave the Counter page. I am also experiencing the same issue with FluentTextField and FluentSelect. This is making my application sluggish.

Steps to reproduce:

Open the application.
Go to the Counter page.
Display 1000 FluentCards.
Go to the Home page.
Go to the Counter page.
Go to the Home page.
Observe the memory usage of the application.

## 🤔 Expected Behavior

The memory usage of the application should decrease when I leave the Counter page.

## 😯 Current Behavior

The memory usage of the application does not decrease when I leave the Counter page.

![Screenshot 2024-01-24 175914](https://github.com/microsoft/fluentui-blazor/assets/23271775/15c57f74-c874-49d1-bcd8-7468376eb3ff)
![Screenshot 2024-01-24 180030](https://github.com/microsoft/fluentui-blazor/assets/23271775/b3cb4ca8-f875-4634-9c9a-488f6ea390b7)
![image](https://github.com/microsoft/fluentui-blazor/assets/23271775/bd7637d7-8248-4ff5-9c3c-577cd5a35c60)
![Screenshot 2024-01-24 180043](https://github.com/microsoft/fluentui-blazor/assets/23271775/a7c58df0-b2c9-4956-aed5-1f8cbd9d665b)

## 💁 Possible Solution

The FluentCard, FluentTextField, and FluentSelect components may not be releasing all of the memory they are allocated.

## 🌍 Your Environment

Operating system: Windows 11
Browser: Chrome
Fluent UI version: 4.3.1

**Comment by NguyenLamMS** [comment]
I am still experiencing this issue with a page that only has a few FluentTextFields and FluentSelects. When I navigate between pages, memory usage increases gradually and is not being released. I do not know where I am going wrong.

**Comment by dvoituron** [comment]
Is it possible to have an example of the source code (GitHub) that generates this problem?
This would allow us to check and correct (if possible).

**Comment by vnbaaij** [comment]
Maybe/might be related to #817?

**Comment by NguyenLamMS** [comment]
Yes, I think these two problems are the same. Is there any solution to fix the issue yet, sir? This issue is very serious for me. You can see in my test, the application has consumed a lot of memory, causing the FluentDesignTheme to be delayed and not smooth when changing themes.
[repo](https://github.com/NguyenLamMS/BlazorWpf.git)
https://github.com/microsoft/fluentui-blazor/assets/23271775/063ce575-805f-496d-9323-38598e3ed9bc

**Comment by vnbaaij** [comment]
Closing thisas it is a duplicate. We are dependant on upstream work to get this fixed. Can't give any ETA for that.
