### ISSUE TITLE
fix: Adding and removing items causes overflow count to incorrectly increase in FluentOverflow

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#1378]
# 🐛 Bug Report

Adding and removing items causes overflow count to incorrectly increase. The number stops reflecting the real overflow value.

## 💻 Repro or Code Sample

Razor:
https://github.com/dotnet/aspire/blob/3cd891a57338b0a5bafc39c4586c54fc94989afe/src/Aspire.Dashboard/Components/Controls/ChartContainer.razor#L31-L52

Code behind:
https://github.com/dotnet/aspire/blob/3cd891a57338b0a5bafc39c4586c54fc94989afe/src/Aspire.Dashboard/Model/CounterChartViewModel.cs

Demo:
![aspire-overflow](https://github.com/microsoft/fluentui-blazor/assets/303201/034e583d-6e0d-47ae-a724-dc0d3609f44b)

## 🤔 Expected Behavior

Overflow count is correct.

## 😯 Current Behavior

Adding and removing items causes overflow count to increase incorrectly.

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Chrome
* .NET: .NET 8

**Comment by dvoituron** [comment]
The Remove feature seems to be faulty :-) Let us fix it for the next version.

**Comment by dvoituron** [comment]
That will be fixed in the next release #1385
