### ISSUE TITLE
Need to have Custom implementation for Close Method in Dialog , to clear form values when closed.

### ISSUE THREAD

**Issue by KrishnaKumar-1409** [microsoft/fluentui-blazor#1381]
# 🙋 Feature Request
Need to have custom closing method for Dialog as you can see when we set ShowDismiss property to true ,It displays an X for closing the dialog , The thing needed is , when u have form in that dialog , if you are closing the dialog for some reasons , the values should be cleared when we re-open the dialog, Thus needed custom implementation for Closing the Dialog like an event are something is needed to handle clearing process.

**Comment by vnbaaij** [comment]
~~Need~~ We prefer if you use "I would like"

Anyways, we added `OnDialogClosing` to `DialogParameters` recently. See https://www.fluentui-blazor.net/Dialog#dialogservicewithcus for example.
