### ISSUE TITLE
fix: NavMenu Expanded won't update if prerendering is disabled

### ISSUE THREAD

**Issue by aco-mreble** [microsoft/fluentui-blazor#1387]
# 🐛 Bug Report

When using `@bind-Expanded="expanded"` or `ExpandedChanged="OnExpandedChanged"` and when prerendering is disabled `expanded` won't update/`OnExpandedChanged` won't be called when clicking on the Hamburger Menu.

## 💻 Repro or Code Sample
Create a new template with 
```shell
dotnet new fluentblazor -o FluentUiTest
```
go to `FluentUiTest\Components\Layout\NavMenu.razor` and add this line of code anywhere on the page:
```
<p>@expanded</p>
```
Run the application. Everything works as expected, the text in the `<p>` tag will update accordingly to true/false.

Now go to `App.razor` and replace the `<Routes />` line with this
```
<Routes @rendermode="new InteractiveServerRenderMode(prerender: false)"/>
```
Run the application again and see, that the text in the `<p>` tag won't change anymore.

## 🌍 Your Environment

* Blazor with interactive server side rendering enabled
* Edge
* .net 8.0.1 with fluent-ui 4.3.1

**Comment by vnbaaij** [comment]
Never mind, I see what you mean in a proper Server site...

What is happening is that the FluentNavMenu script is handeling the expanding/collapsing with Javascript. That is why @expanded never gets updated. I'm asking internally if it is possible to hae  script that **only** runs in SSR mode and uses Blazr when interactivity is there,

**Comment by vnbaaij** [comment]
Apparently there is no way to have a script that is run only when in SSR mode. So, for now we can either:
a) remove the script - We end app with a menu that does not expand/colapse (and same for groups inside the menu) in SSR mode
b) keep the script - in a couple of specific scenarios you can't get the expanded state of the menu. Everything else works

I vote for b 😀

Closing this as it is currently not possible to solve in another way
