### ISSUE TITLE
fix: Blazor Web App auto rendermode

### ISSUE THREAD

**Issue by quintendc** [microsoft/fluentui-blazor#1388]
# 🐛 Bug Report

I installed the Blazot Fluent UI templates and created a Web App with auto render mode, if i go to the weather page the sorting is not working, i also copied a component from the documentation example with persons located here: https://www.fluentui-blazor.net/DataGrid and same issue sorting is not working also sometimes when i visit the new page "people" the layout is not loading correctly and i have to refresh the page

## 💻 Repro or Code Sample

people page
```
@page "/people"

<h3>People</h3>

<FluentDataGrid Items="@people">
    <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" />
    <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
    <PropertyColumn Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
</FluentDataGrid>

@code {
    record Person(int PersonId, string Name, DateOnly BirthDate);

    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9)),
    }.AsQueryable();
}
```

## 🤔 Expected Behavior

- sorting should work
- layout to render correctly

## 😯 Current Behavior

- sorting not working
- layout is not always rendered correctly
![people](https://github.com/microsoft/fluentui-blazor/assets/1389203/05ab80b8-f153-4d2a-8f2d-3aed88c83f8a)

## 🌍 Your Environment
VS 17.8
Blazor Fluent UI web app template (.NET 8)

**Comment by quintendc** [comment]
When Using @rendermode InteractiveServer it works as intended with the other rendermodes the issue still persists

**Comment by pk9r327** [comment]
same issue #1097

**Comment by vnbaaij** [comment]
If sorting is not working, the page is rendered in SSR mode. 
You have not provided us a repro of the issue, but my guess is you are using the :per page: rendermode
