### ISSUE TITLE
fix: External Authentication in Middleware

### ISSUE THREAD

**Issue by MikeRobGIT** [microsoft/fluentui-blazor#1391]
# 🐛 Bug Report

I've tried to add external authenticators to my app but the authenticator's schema name is being duplicated, even when specified.

## 💻 Repro or Code Sample

Update `Program.cs` to use external authentication:

```cs 
var builder = WebApplication.CreateBuilder(args);
var config = builder.Configuration;
// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents()
    .AddInteractiveWebAssemblyComponents();

builder.Services.AddFluentUIComponents();

builder.Services.AddCascadingAuthenticationState();
builder.Services.AddScoped<IdentityUserAccessor>();
builder.Services.AddScoped<IdentityRedirectManager>();
builder.Services.AddScoped<AuthenticationStateProvider, PersistingRevalidatingAuthenticationStateProvider>();

builder.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
        options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    })
    .AddGoogle("Google", googleOptions =>
    {
        googleOptions.ClientId = config["Authentication:Google:ClientId"];
        googleOptions.ClientSecret = config["Authentication:Google:ClientSecret"];
        googleOptions.SignInScheme = IdentityConstants.ExternalScheme;
    })
    .AddIdentityCookies();
```

## 🤔 Expected Behavior

External authentication should work as it would using the default blazor template.

## 😯 Current Behavior

When the Google button is clicked I get the error below. The scheme is being recognized as "Google,Google" instead of "Google". 

System.InvalidOperationException: No authentication handler is registered for the scheme 'Google,Google'. The registered schemes are: Google, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Google,Google",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Http.HttpResults.ChallengeHttpResult.ExecuteAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteResultWriteResponse(IResult result, HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass104_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

## 🔦 Context

I'm trying to allow external logins to make it easier for users to register.

## 🌍 Your Environment
* Fluent Blazor Web App Template
* Windows 11, PC
* Browser: Google Chrome
* .NET 8

**Comment by malthuswaswrong** [comment]
I just encountered the same issue.

**Comment by malthuswaswrong** [comment]
The problem is the FluentButton provided by the Fluent new project template in ExternalLoginPicker.

<FluentButton Type="ButtonType.Submit" Appearance="Appearance.Accent" name="provider" Value="@provider.Name" Title="@($"Log in using your {provider.DisplayName} account")">@provider.DisplayName</FluentButton>

If both "name" and "Value" are present it concatenates "Google,Google".  If either one of them is removed, the provider comes back properly without the concatenation.

I tried to fix the template myself, but I am too stupid.

**Comment by MikeRobGIT** [comment]
I ended up overriding the duplicate in the backend. I threw this `provider = provider.Split(',')[0];` in the `MapAdditionalIdentityEndpoints` function where the provider is consumed. Just to get the functionality working.
