### ISSUE TITLE
Checkbox and ComboBox TabIndex property resets to 0 during runtime 

### ISSUE THREAD

**Issue by GovindRulz** [microsoft/fluentui-blazor#1392]
# 🐛 Bug Report

We are setting TabIndex for each input control in a page , to enable keyboard navigation using Tab Key as well as Enter Key, Due to unexpected behavior being noticed at runtime , we inspected the element in the browser and saw that Tab Index for all check box and combo box controls have been reset to "0" This issue is critical because our keyboard navigation using the Enter Key relies on the Tab Index value set for the controls during design time. 

## 💻 Repro or Code Sample

@page "/"

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.
<FluentCheckbox tabindex="2" />

## 🤔 Expected Behavior
`<fluent-checkbox id="f583a6f3c" tabindex="2" role="checkbox" aria-checked="true" aria-required="false" aria-disabled="false" _bl_2="" current-checked="true" class="checked" value="" current-value=""></fluent-checkbox>
`

## 😯 Current Behavior
`<fluent-checkbox id="f583a6f3c" tabindex="0" role="checkbox" aria-checked="true" aria-required="false" aria-disabled="false" _bl_2="" current-checked="true" class="checked" value="" current-value=""></fluent-checkbox>
`

## 💁 Possible Solution

I would very love to fix the issue and contribute , but i have not been able to figure out at which point the value is changing 

## 🔦 Context

We want users to be able to navigate through the data entry for using Enter Key. We set the tab index at design time and use Javascript to process enter key hits and navigate to the next control. we have 100's of such forms so it has to be a generic solution. individually setting focus is not feasible 

## 🌍 Your Environment

This issue is being faced on a chrome browser , running on a windows 11 developer machine. We are using the .Net Core 8 and the library in use is  **Microsoft.FluentUI.AspNetCore.Components**

**Comment by dvoituron** [comment]
Unfortunately, this problem seems to come from the Web Components we use (and not from the FLuentUI-Blazor library).

Example:
```html
<fluent-checkbox tabindex="1">Hello</fluent-checkbox>
```

will generate the code:
```
                 XXXXXXXXXXXX
<fluent-checkbox tabindex="0" role="checkbox" aria-checked="false" aria-required="false" aria-disabled="false" current-value="on" current-checked="false">Hello</fluent-checkbox>
```

You should create a new problem on this repo: https://github.com/microsoft/fluentui/
