### ISSUE TITLE
Panel/Dialog Validation

### ISSUE THREAD

**Issue by ZnowuJa** [microsoft/fluentui-blazor#1395]
# 🙋 Documentation Request

Hi,
Can you document how can we validate data in Dialogs or Panels? 
They are not a EditForm and it is hard for beginners to figure it out.
How to force Save button to validate?
Regards

**Comment by dvoituron** [comment]
Here you'll find a new example of how to validate an `EditForm` included in a dialog box.

https://github.com/microsoft/fluentui-blazor/pull/1397
