### ISSUE TITLE
Help needed: Can not compile: AddDesignTokens doesn't exit in IServiceCollection

### ISSUE THREAD

**Issue by ypeng-ming** [microsoft/fluentui-blazor#1400]
I'm using .Net6/7 which is v3 version, but I can't compile this project named Microsoft.Fast.Components.FluentUI, error info is :
'IServiceCollection' does not contain a definition for 'AddDesignTokens' and no accessible extension method 'AddDesignTokens' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	Microsoft.Fast.Components.FluentUI (net6.0).

Did I do something wrong?

**Comment by vnbaaij** [comment]
Add DesignTokens ones from a .NET Source Generator project (which is part of the repo). Did you clone everything? For that v3 version, you need to be on the archives/v3 branch

**Comment by ypeng-ming** [comment]
> `AddDesignTokens` comes from a .NET Source Generator project (which is part of the repo). Did you clone everything? For that v3 version, you need to be on the archives/v3 branch

Hello vnbaaij, thanks for replying, I did build Microsoft.Fast.Components.FluentUI.Generators.
![image](https://github.com/microsoft/fluentui-blazor/assets/52032205/616a4096-d0e3-4995-99fd-828821f60ed9)
but errror still exists
![image](https://github.com/microsoft/fluentui-blazor/assets/52032205/ef3c7b0c-3ca1-43ea-ba42-78cea5e9e984)

**Comment by vnbaaij** [comment]
Not sure what is happening. 
I do see in your images that Shared is set as the start up project which is wrong. Should be either Client or Server project.

**Comment by ypeng-ming** [comment]
I updated VS and using .Net8, I still have a werid problem:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1105	Unable to find project information for 'C:\GitHub\fluentui-blazor\src\Core.Assets\Microsoft.FluentUI.AspNetCore.Components.Assets.esproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.	Microsoft.FluentUI.AspNetCore.Components	C:\GitHub\fluentui-blazor\src\Core\Microsoft.FluentUI.AspNetCore.Components.csproj	1	


I noticed path is \fluentui-blazor\src\Core.Assets\, so I added a folder  named Core.Assets as subdirectory of folder "src", but it did't help.
![image](https://github.com/microsoft/fluentui-blazor/assets/52032205/459bd028-317f-4032-a0b8-6fa7118ee97b)

Someone has encountered this problem? Thanks

**Comment by dvoituron** [comment]
To use the `esproj` project, you need to use the Preview version of Visual Studio 2022.
If the problem persists, you can close Visual Studio, run the command `dotnet restore` from Terminal, located in the folder containing `Microsoft.FluentUI.sln` and restart VS.

**Comment by vnbaaij** [comment]
Also, if you cloned the whole repo and are on the dev branch now, you should already have that folder and project. Are you sure you congress everything alright?

**Comment by ypeng-ming** [comment]
> To use the `esproj` project, you need to use the Preview version of Visual Studio 2022. If the problem persists, you can close Visual Studio, run the command `dotnet restore` from Terminal, located in the folder containing `Microsoft.FluentUI.sln` and restart VS.

Thanks, dvoituron, run "dotnet restore" in CMD solved my issue.

**Comment by ypeng-ming** [comment]
> Also, if you cloned the whole repo and are on the dev branch now, you should already have that folder and project. Are you sure you cloned everything alright? I highly doubt that since you say you needed to create a folder and files...

Thanks for your time, vnbaaij.
