### ISSUE TITLE
fix: "disabled" class is lost when value is changed in a disabled FluentCheckbox

### ISSUE THREAD

**Issue by gunnasko** [microsoft/fluentui-blazor#1401]
# 🐛 Bug Report

When value of a checkbox is changed through bindings, it loses its disabled css class, causing it to no longer appear as a disabled control.

## 💻 Repro or Code Sample

A simple reproduction repo can be found here: https://github.com/gunnasko/FluentUiCheckboxDisableBug
Or one can reproduce the error with the following blazor page:

```razor
@page "/"
@rendermode InteractiveServer


<FluentCheckbox @bind-Value:get="@FirstCheckboxChecked" @bind-Value:set="FirstCheckboxChanged">FirstCheckbox</FluentCheckbox>
<FluentCheckbox @bind-Value="@SecondCheckboxChecked" Disabled=true>Disabled</FluentCheckbox>

@code {
	public bool SecondCheckboxChecked = true;

	public bool FirstCheckboxChecked = false;


	public void FirstCheckboxChanged(bool newValue)
	{
		FirstCheckboxChecked = newValue;
		SecondCheckboxChecked = !newValue;
	}
}
```
## 🤔 Expected Behavior
When a user clicks "FirstCheckbox", I expect "Disabled" checkbox to toggle state, but still be disabled.

For a more technical description, I expect after clicking "FirstCheckbox" that the other checkbox has HTML output:

```html
<fluent-checkbox id="f4ae5624a" class="disabled" disabled="" role="checkbox" aria-checked="false" aria-required="false" aria-disabled="true" _bl_140b63f3-14f5-474e-a4c4-f28d10273912="">Disabled</fluent-checkbox>
```

## 😯 Current Behavior
After clicking "FirstCheckbox" the disabled checkbox outputs current HTML. Note the missing class="disabled".

```html
<fluent-checkbox id="f62510cec" disabled="" role="checkbox" aria-checked="false" aria-required="false" aria-disabled="true" _bl_2ce124a7-e64e-4b84-ab0c-0ae4d04fcded="">Disabled</fluent-checkbox>
```
Note that it is not possible to toggle changes on the disabled checkbox, so this is only a visual bug.

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser Microsoft Edge
* .NET 8 and using library Microsoft.FluentUI.AspNetCore.Components 4.3.1

**Comment by dvoituron** [comment]
For some strange reason, the class is not updated by the `fluent-checkbox` WebComponent.
This PR will correct this in the next version

https://github.com/microsoft/fluentui-blazor/pull/1402
