### ISSUE TITLE
Support multiline column headers in FluentDataGrid

### ISSUE THREAD

**Issue by askarhu** [microsoft/fluentui-blazor#1403]
# 🙋 Feature Request

When there are too many columns to show in a FluentDataGrid, enterprise apps may need to show many columns, it cuts off the column headers with a few characters that's not usable. Would be nice to support a taller column header where the title shall wrap around to predefined number of lines if needed.

## 🤔 Expected Behavior

The FluentDataGrid columns wrap around for titles that are longer in length.

## 😯 Current Behavior

The sort button control cuts of the title with very few characters shown.

## 💁 Possible Solution

Support multiline column titles, that wraps the text around, with a possible limitation to a max number of lines or allow the users to set the max lines of text shown in the header title.

## 🔦 Context

It's impacting most of our data grids as some of them are numeric columns but have longer header titles.

**Comment by vnbaaij** [comment]
It is not possible in HTML to set a limit on a number of lines (before cutting of). This is not something we can prevent. You will just need to make the grid wider (by using Class/Style parameters) if you have a large number of columns

**Comment by askarhu** [comment]
Thanks @vnbaaij Even when we make the grid wider to w100 it still isn't enough. The problem is that the column header title weren't word wrapping and sticking to just one line and cutting off after very few characters. 

I understand your recommendation, but we tried everything possible and the only way this could be usable is to have some support for multiline grid column headers with word wrap support.

**Comment by askarhu** [comment]
Since it has the action columns as the last column it makes it really harder for someone to scroll to the right every time to make an update or delete, it really presents a bad UX. Whereas, if we have support for multiline column headers then we could constrain these columns to a smaller width but still show the headers reasonably well and can avoid the horizontal scroll. I tried to hack it around with CSS, but with the nested hierarchy it's not yielding the right results.

**Comment by vnbaaij** [comment]
I'm sure it can be done with CSS but I do not have any pointers for you on how to achieve it, sorry.
