### ISSUE TITLE
fix: Issue with FluentCalendar component's View="CalendarViews.Months" behavior

### ISSUE THREAD

**Issue by bianwenbo** [microsoft/fluentui-blazor#1406]
# 🐛 Bug Report

## 💻 Repro or Code Sample

To reproduce the issue:
1. Use the FluentCalendar component with the View set to "CalendarViews.Months."
2. Click on a year to navigate to the list of months.
3. Try clicking on the current year to return to the list of months.

## 🤔 Expected Behavior

Clicking on the current year should also return to the list of months, just like clicking on other years does.

## 😯 Current Behavior

Currently, when clicking on the current year in the FluentCalendar component's months view, it does not return to the list of months.

## 💁 Possible Solution

This behavior might be by design, but it could also be improved for better user experience. One possible solution is to allow clicking on the current year to return to the list of months, just like other years.

## 🔦 Context

This issue affects the usability of the FluentCalendar component when navigating between years and months. It can be confusing for users if clicking on the current year does not behave the same way as clicking on other years.

## 🌍 Your Environment

* OS & Device: Windows 10, PC
* Browser: Google Chrome
* .NET and FAST Version: .NET 8

**Comment by dvoituron** [comment]
I don't understand exactly what you want to do.
Could you give us more details about your proposal?

For the second calendar (where `View="CalendarViews.Months"`), when I click on the year, the **list of years** within a 12-year interval is displayed. This allows you to select a year. How can I return to the "current" year without selecting it?

![Calendar](https://github.com/microsoft/fluentui-blazor/assets/8350694/a3b2c6e1-0454-41a1-bfae-a6092cd1b27d)

**Comment by dvoituron** [comment]
@bianwenbo OK, I get it :-) Yes, it could be better. I'll work on it

**Comment by dvoituron** [comment]
This feature will be solved via the PR #1545.
