### ISSUE TITLE
FluentMessageBarProvider doesn't work in dark mode.

### ISSUE THREAD

**Issue by Rocky-25** [microsoft/fluentui-blazor#1418]
# 🐛 Bug Report

When using the FluentMessageBarProvider if switching to dark mode the messages displayed are unreadable.

## 🤔 Expected Behavior

Messages should change colour to be readable like the other components do.

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/52032850/5c92a056-1f77-4e7c-bd4b-186dbe4d951a)

**Comment by vnbaaij** [comment]
This has been covered in a number of issues already. Are you using the FluentDesignTheme?

**Comment by Rocky-25** [comment]
I thought I was but must be doing something wrong. Will look at the demo site source code
