### ISSUE TITLE
feat: add HTML Element CSS styles

### ISSUE THREAD

**Issue by tbasallo** [microsoft/fluentui-blazor#1423]
Feature Request: CSS styles for equivalent html elements

There are some elements that I do not need a Fluent web component. For example, an anchor to look like a button. Or a simple button. Components are not free - they're more "expensive" than an HTML button, they render more HTML, cannot be copy & pasted between projects, etc.

However, if I want a button or anchor to match the styles, I must use the fluent component. I tried looking at the inspector, but there's quite a bit of cascading and isolation in the CSS used which makes it quite a task.

It would be nice to have a basic set of CSS styles that matched the web component styles for general HTML elements.

**Comment by dvoituron** [comment]
The goal of this library is not simply to offer FluentUI-style rendering.
Rather, it's to provide components adapted to the needs of the developer. For example, `FluentAnchor` offers an `Appearance` attribute for appearance, as well as `IconStart` and `IconEnd` which don't exist in the HTML `a` tag. This is all the more important for other, more complex components.

To "just" have a FluentUI look, you'll probably have to use other, more appropriate packages.

**Comment by dvoituron** [comment]
That was the way used by Microsoft some years ago, using [Office UI Fabric JS](https://developer.microsoft.com/en-us/fabric-js)
```xml
<button class="ms-Button">
  <span class="ms-Button-label">Create Account</span>
</button>
```
Support for Office UI Fabric JS has ended. Microsoft recommend that you use the Fluent UI framework instead.

**Comment by tbasallo** [comment]
@dvoituron I understand 100% and it makes a lot of sense.

It's an awesome library and I'm just learning everything it can do and the many, many options. Maybe I'm missing a nuanced usage that hasn't clicked.

But, if I just want to do a table that is not based on a list of objects. How would I go about that? It doesn't seem like that's doable. So I can create a <table> but how do I style it to match?

**Comment by tbasallo** [comment]
Found that particular ask: Manual grid - https://www.fluentui-blazor.net/_content/FluentUI.Demo.Shared/sources/DataGridManual.razor.txt
