### ISSUE TITLE
fix: Paginator UI doesn't always update when used with a DataGrid and an async ItemProvider

### ISSUE THREAD

**Issue by jpduchon** [microsoft/fluentui-blazor#1428]
# 🐛 Bug Report

The Paginator UI doesn't update correctly if a DataGrid uses an ItemProvider with async calls where the result should update the current page index to the new last page index.

## 💻 Repro or Code Sample
The Sample is a DataGrid with a Paginator that shows 10 pages.
Via the search box above the grid you can directly update the total page count of the data grid in the item provider result.

Steps to repro:
1. Navigate to page 5 on the Paginator
2. In the search box enter 4 and hit enter

```
@page "/"

<PageTitle>Paginator UI Bug</PageTitle>

<FluentSearch @bind-Value="totalCount"></FluentSearch>
<FluentDataGrid ItemsProvider="LoadData"
                TGridItem="GridItem"
                Pagination="@pagination">
    <PropertyColumn Property="@(x => x.Value)"></PropertyColumn>
</FluentDataGrid>
<FluentPaginator State="@pagination"></FluentPaginator>

@code
{
    readonly PaginationState pagination = new() { ItemsPerPage = 1 };
    string totalCount = "10";

    private async ValueTask<GridItemsProviderResult<GridItem>> LoadData(GridItemsProviderRequest<GridItem> request)
    {
        if (!int.TryParse(totalCount, out var count))
        {
            count = 10;
        }

        await Task.Delay(100);

        return GridItemsProviderResult.From([new GridItem("hello")], count);

    }

    record GridItem(string Value);

}
```

## 🤔 Expected Behavior

I would expect that the Paginator displays the new state e.g. "4 of 4" when the current page index is greater than the last page index.

## 😯 Current Behavior

The Paginator still displays "5 of 10" and didn't update its UI.
![image](https://github.com/microsoft/fluentui-blazor/assets/157502294/33064b8a-3fd1-485b-a21e-3b4c5c075d7c)

It seems the state is correct under the hood because after navigating to the previous page the UI updates to "3 of 4".
![image](https://github.com/microsoft/fluentui-blazor/assets/157502294/4987582d-8c4e-4848-8925-8093a1d6c368)

If you repeat the described example without any async calls then it works as expected.

## 💁 Possible Solution

I didn't find or understand the cause for this issue. :(

## 🔦 Context

The issue breaks the UI and could confuse users. It is also possible in some circumstances that you are allowed to navigate to page 0 because of the broken UI, which may produce additional errors.

## 🌍 Your Environment

* OS & Device: Windows 10 on PC
* Browser Microsoft Edge and Chrome
* .NET and FAST Version: .NET8

**Comment by vnbaaij** [comment]
This seems t be a rather niche case. I dont think you should manipultate the pagecount like that. The component calculates the number based ion the data provided and your code is interfering with that, If you absoutelty want to do it async, I suggest you take a look at the `PaginationState.SetCurrentPageIndexAsync` method.
Colsing this as the effect of this is small

**Comment by jpduchon** [comment]
Sorry, it seems I didn't formulate my use case well. Maybe there is a misunderstanding. 

I only manipulate the count result in the repro to simulate a asynchronous query to a remote data source that queries the data for the current page where a filter may return less items so my current page wouldn't be valid anymore. My comprehension is that the PaginationState handles this and sets the current page to the last page. 

For example I have 18 books and I want to display 10 books per page. 
- The first query takes 10 books and skips 0. The result are the first 10 books and a total count of 18. 
- Now I navigate to page 2. The item provider now executes a query which skips 10 books and take the next 10 books. The result are 8 books and a total count of 18. 
- Now I enter a search for "Orwell". The item provider executes a query which applies the filter skips 10 take 10. The result now is 0 Books and a total count of 1.
- The pagination state gets updated and handles the case that the current page index (1) is greater than the last page index (0 because only 1 books satifies the filter). As a result the current page index gets updated to the new last page index. 
- This results in another query from the item provider which now still applies the filter, skips 0 and take 10. The result is 1 book with the total count of 1.
- The paginator UI doesn't reflect the current state. Only after the next UI update the paginator displays the correct state again. 

A workaround was to set pagination state to a current page of 0 when triggering a search. But a caveat with this solution seems to be that I trigger an additional request because of setting the current page in addition to the requests described above. 

Nonetheless, if it wasn't a misunderstanding I am sorry and thank you for your work and time.
