### ISSUE TITLE
feat: only render active tab in FluentTabs

### ISSUE THREAD

**Issue by majkada** [microsoft/fluentui-blazor#1429]
# 🙋 Feature Request

It would be great to have a configuration option in the FluentTabs component with which it's possible to either render all tab content at once or only render the active tab and remove all others from the dom.
E.g. MudBlazor calls it KeepPanelsAlive.

## 🤔 Expected Behavior

When e.g. KeepPanelsAlive is false:
FluentTabs only renders the active tab. When a tab is switched the content of the selected tab is getting rendered and the content of the previous tab is removed from the dom. So on a tab switch the OnInitialized method of all child components of the active FluentTab are being called.

## 😯 Current Behavior

Currently all tabs and its contents are getting rendered together with the FluentTabs. On a tab switch the tab content is only hidden and shown again.

## 🔦 Context

I intend to have a page with a FluentTabs component. The tab contents hold other complex child components which load data from an API etc.. For FluentTabs with simple contents it's totally fine to render them all at once but if they get more complex I only want to render them on demand. So a tab switch would behave like an actual page change.

**Comment by hksalessio** [comment]
If I'm not mistaken, you can apply the `DeferredLoading` attribute to `FluentTab`s to achieve this effect.

**Comment by majkada** [comment]
oh, you are totally right. Thanks!
