### ISSUE TITLE
FluentDatePicker Formatting

### ISSUE THREAD

**Issue by cowsen** [microsoft/fluentui-blazor#1430]
When I click on the Fluent DatePicker calendar icon, I get a dropdown list with first the month, followed by up and down arrows, then days of the week, followed by days of the month.
 
I have a hybrid Blazor desktop app with Fluent UI Blazor components and WPF for navigation.  The razor markup code is:
<FluentTooltip Anchor="delay2" Position=TooltipPosition.Top Delay=200>DD/MM/YYYY</FluentTooltip>
 <label for="invoicedate" style="font-size:16px; margin-left:10px; padding:5px; background-color:lightgray; border-radius:2px; ">Invoice Date:</label>
 <FluentDatePicker id="invoicedate" @bind-Value="@ContextModel.InvoiceDate" TValue="DateTime?" 
         Placeholder="DD/MM/YYYY" style="font-size:16px; padding:5px;background-color:ghostwhite; border-radius:2px; "></FluentDatePicker>
 <ValidationMessage style="color:darkred; font-size:14px; font-weight:600" For="() => ContextModel.InvoiceDate" />
Finally, the index.html code is:
<!DOCTYPE html>
<html lang="en">
<head>
	<HeadOutlet />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
	<title>ClinicServices</title>
	<base href="/" />
	<link href="css/app.css" rel="stylesheet" />
	<link href="FluentBlazor.styles.css" rel="stylesheet" />
	<link href="_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css" rel="stylesheet" />
</head>
<body>
	<div class="status-bar-safe-area"></div>
	<div id="app">Loading...</div>
	<div id="blazor-error-ui">
		An unhandled error has occurred.
		<a href="" class="reload">Reload</a>
		<a class="dismiss">🗙</a>
	</div>
	<Routes />
	<script src="_framework/blazor.web.js"></script>
	<script app-name="ClinicServices" src="./_content/Microsoft.FluentUI.AspNetCore.Components/js/initializersLoader.webview.js"></script>
	<script src="_framework/blazor.webview.js"></script>
</body>
</html>
FluentBlazor.styles.css code has minimal styling for error dialogs

**Comment by dvoituron** [comment]
Without reproducing your problem, I can't solve anything :-)
It seems to be a cache problem. Could you clear your browser's cache and restart your project?

**Comment by vnbaaij** [comment]
Also, you are adding blazor.web.js twice. Once before calling the initialization loader and once after. Probably our events do not get hooked up. Remove the first blazor.web.js call and try again

**Comment by cowsen** [comment]
Denis,

Thank you for you quick response.  I tried clearing Chrome browser’s cache to no avail.  I have a similar problem with the default paging with FluentDataGrid.  Since I haven’t seen any others with similar problems on your website,  I am wondering if it might have something to do with the fact I am running a hybrid desktop application (WPF)?

I am attaching my original request with better formatting/layout than I could achieve on your website:

When I click on the Fluent DatePicker calendar icon, I get a dropdown list with first the month, followed by up and down arrows, then days of the week, followed by days of the month.
[A screenshot of a computer  Description automatically generated]

I have a hybrid Blazor desktop app with Fluent UI Blazor components and WPF for navigation.  The razor markup code is:

<FluentTooltip Anchor="delay2" Position=TooltipPosition.Top Delay=200>DD/MM/YYYY</FluentTooltip>
<label for="invoicedate" style="font-size:16px; margin-left:10px; padding:5px; background-color:lightgray; border-radius:2px; ">Invoice Date:</label>
<FluentDatePicker id="invoicedate" @***@***.***" TValue="DateTime?"
         Placeholder="DD/MM/YYYY" style="font-size:16px; padding:5px;background-color:ghostwhite; border-radius:2px; "></FluentDatePicker>
<ValidationMessage style="color:darkred; font-size:14px; font-weight:600" For="() => ContextModel.InvoiceDate" />


Finally, the index.html code is:

<!DOCTYPE html>
<html lang="en">
<head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
                <title>ClinicServices</title>
                <base href="/" />
                <link href="css/app.css" rel="stylesheet" />
                <link href="FluentBlazor.styles.css" rel="stylesheet" />
                <link href="_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css" rel="stylesheet" />
</head>
<body>
                <div class="status-bar-safe-area"></div>
                <div id="app">Loading...</div>
                <div id="blazor-error-ui">
                                An unhandled error has occurred.
                                <a href="" class="reload">Reload</a>
                                <a class="dismiss">🗙</a>
                </div>
                <Routes />
                <script app-name="ClinicServices" src="./_content/Microsoft.FluentUI.AspNetCore.Components/js/initializersLoader.webview.js"></script>
                <script src="_framework/blazor.webview.js"></script>
</body>
</html>

FluentBlazor.styles.css code has minimal styling for error dialogs.

Craig

**Comment by cowsen** [comment]
Vincent,

Thank you for your fast response.  I had noticed that yesterday and removed it but to no avail.  I have a similar problem with the default paging with FluentDataGrid.  Since I haven’t seen any others with similar problems on your website,  I am wondering if it might have something to do with the fact I am running a hybrid desktop application (WPF)?

I am attaching my original request with better formatting/layout than I could achieve on your website:

When I click on the Fluent DatePicker calendar icon, I get a dropdown list with first the month, followed by up and down arrows, then days of the week, followed by days of the month.
[A screenshot of a computer  Description automatically generated]

I have a hybrid Blazor desktop app with Fluent UI Blazor components and WPF for navigation.  The razor markup code is:

<FluentTooltip Anchor="delay2" Position=TooltipPosition.Top Delay=200>DD/MM/YYYY</FluentTooltip>
<label for="invoicedate" style="font-size:16px; margin-left:10px; padding:5px; background-color:lightgray; border-radius:2px; ">Invoice Date:</label>
<FluentDatePicker id="invoicedate" @***@***.***" TValue="DateTime?"
         Placeholder="DD/MM/YYYY" style="font-size:16px; padding:5px;background-color:ghostwhite; border-radius:2px; "></FluentDatePicker>
<ValidationMessage style="color:darkred; font-size:14px; font-weight:600" For="() => ContextModel.InvoiceDate" />


Finally, the index.html code is:

<!DOCTYPE html>
<html lang="en">
<head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
                <title>ClinicServices</title>
                <base href="/" />
                <link href="css/app.css" rel="stylesheet" />
                <link href="FluentBlazor.styles.css" rel="stylesheet" />
                <link href="_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css" rel="stylesheet" />
</head>
<body>
                <div class="status-bar-safe-area"></div>
                <div id="app">Loading...</div>
                <div id="blazor-error-ui">
                                An unhandled error has occurred.
                                <a href="" class="reload">Reload</a>
                                <a class="dismiss">🗙</a>
                </div>
                <Routes />
                <script app-name="ClinicServices" src="./_content/Microsoft.FluentUI.AspNetCore.Components/js/initializersLoader.webview.js"></script>
                <script src="_framework/blazor.webview.js"></script>
</body>
</html>

FluentBlazor.styles.css code has minimal styling for error dialogs.

Craig

**Comment by vnbaaij** [comment]
Sorry, but I understand what exatly is the issue. Add some screenshots maybe?

**Comment by cowsen** [comment]
Vincent,

So, will there be a fix in a future update?

Craig

**Comment by vnbaaij** [comment]
You still have not made clear what the issue is...

**Comment by vnbaaij** [comment]
Closed due to inactivity
