### ISSUE TITLE
feat: add option for Autocomplete to select found entry on tab

### ISSUE THREAD

**Issue by jewicht** [microsoft/fluentui-blazor#1435]
# 🙋 Feature Request

## 🤔 Expected Behavior

An option could be added for Autocomplete to select the found entry without using the mouse or pressing the enter key.
For example, in the first example of https://www.fluentui-blazor.net/Autocomplete , I would be able to type "arg" and press tab and Argentina would be selected.
MudBlazor calls this option SelectValueOnTab which is disabled by default: https://mudblazor.com/api/autocomplete

## 😯 Current Behavior

It would be disabled by default, so doesn't change the behavior.
It allows faster form entry.
It probably only makes sense when Autocomplete is set with MaximumSelectedOptions = 1.

**Comment by dvoituron** [comment]
Thank you for your suggestion. I will check if it is still compatible with our Accessibility rules.

**Comment by dvoituron** [comment]
Will be included in the next Release... see PR #2110
