### ISSUE TITLE
OnSelectedChange fired twice in FluentTreeView

### ISSUE THREAD

**Issue by hevilhuy** [microsoft/fluentui-blazor#1439]
🐛 Bug Report

Using FluentTreeView with OnSelectedChange. Add some items to the tree. Then click on any item, the OnSelectedChange will be fired twice.

🤔 Expected Behavior

OnSelectedChange only fire once.

😯 Current Behavior

OnSelectedChange is firing twice

**Comment by vnbaaij** [comment]
Unfortunately, we can't change that. It is done by the undelying web components script.

If you want to handle selection in a easier way, do it with `@bind-CurrentSelected` as shown in https://www.fluentui-blazor.net/TreeView#defaultwitheventhand
