### ISSUE TITLE
fix: Autocomplete left click does not work

### ISSUE THREAD

**Issue by tai-yi** [microsoft/fluentui-blazor#1445]
# 🐛 Bug Report

Cannot use mouse click select item.

https://www.fluentui-blazor.net/Autocomplete

## 💻 Repro or Code Sample

https://www.fluentui-blazor.net/Autocomplete

## 🤔 Expected Behavior

Mouse click should able to select/unselect items.

## 😯 Current Behavior

After click, nothing happened.

## 🔦 Context

N/A

## 🌍 Your Environment

Microsoft.FluentUI.AspNetCore.Components : 4.4.0

**Comment by dvoituron** [comment]
We will soon be releasing a Hotfix including #1449
