### ISSUE TITLE
ToastService with Primary and Secondary action will crash

### ISSUE THREAD

**Issue by EvaRichie** [microsoft/fluentui-blazor#1452]
# 🐛 Bug Report

Use the `ToastService` with `Primary` and `Secondary` Action string been set on v4.4 will crash.

## 💻 Repro or Code Sample

![image](https://github.com/microsoft/fluentui-blazor/assets/9699415/a61d8523-3496-41af-8ec5-888e070e3750)

## 🤔 Expected Behavior

If should show the Toast with Primary or Section action string.

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/9699415/77513b4c-9c18-4ecd-ace5-4e82f773d825)
- Detail message.
[BUG_FLUENTUIV4.4.txt](https://github.com/microsoft/fluentui-blazor/files/14172173/BUG_FLUENTUIV4.4.txt)

## 🔦 Context

Will I want having the progress toast with cancel operation, but seems like in v4.4.0 will break toast.

## 🌍 Your Environment

* OS & Device: Windows 11, PC, 
* Browser:  ALL Browser
* .NET and FAST Version: .NET 8.0.1, Nuget Fluent v4.4

**Comment by EvaRichie** [comment]
Just change the FluentAnchor click syntax from `@onclick` to `OnClick` then it will fixed.
![image](https://github.com/microsoft/fluentui-blazor/assets/9699415/1873c522-e251-46a5-938d-b5c2df37540a)

**Comment by vnbaaij** [comment]
The require @onclick->OnClick will be in the 4.4.1 release
