### ISSUE TITLE
Autocomplete is not responding to click event when selecting an item

### ISSUE THREAD

**Issue by eleyvanetflg** [microsoft/fluentui-blazor#1454]
# 🐛 Bug Report

Autocomplete is not responding to click event when selecting an item

## 💻 Repro or Code Sample
Steps:
Go to the component's page (on the two examples we can reproduce the issue)
https://www.fluentui-blazor.net/Autocomplete

Start typing a name of any country within the countries autocomplete and notice when you click on the specific one you would like it won't get selected.

## 🤔 Expected Behavior
Users should be able to click and select the desired item.

## 😯 Current Behavior
Users are not able to select the desired item using click event, it works only when hitting the Enter button.

**Comment by dvoituron** [comment]
This problem is identical to #1445
And will be solved via #1449
