### ISSUE TITLE
fix: FluentSelect does not re-evaluate "Selected" property when it depends on a query parameter

### ISSUE THREAD

**Issue by Gabriel123N** [microsoft/fluentui-blazor#1456]
# 🐛 Bug Report

When using a `FluentSelect` with a condition based on a query parameter, the selected `FluentOption` is not properly updated in the UI when the navigation removes the linked query parameter from the URI even though the `Selected` lambda accounts for it.

## 💻 Repro or Code Sample

Create a FluentUI webassembly blazor app using the latest dotnet template and replace the content of `Home.razor` with the following code:

```razor
@page "/"

<PageTitle>Home</PageTitle>

<FluentAnchor Href="/">Reset url</FluentAnchor>

<FluentSelect TOption="string">
    @foreach (var option in Options)
    {
        <FluentOption OnSelect="OnSelectionChanged" TOption="string" Value="@option" Selected="@(Option == null ? option == "option2" : option == Option)">@option</FluentOption>
    }
</FluentSelect>

<FluentLabel>Selected option is: @(Option ?? "null")</FluentLabel>


@code {
[Inject] public NavigationManager NavigationManager { get; set; }
    public List<string> Options = new List<string>()
    {
        "option1",
        "option2",
        "option3",
        "option4"
    };
    
    [SupplyParameterFromQuery]
    public string? Option { get; set; }

    public void OnSelectionChanged(string option)
    {
        if (option is not null)
        {
            NavigationManager.NavigateTo(NavigationManager.GetUriWithQueryParameter("option", option));
        }
    }

}
```

## 🤔 Expected Behavior

When changing the select option and then clicking "Reset url", the current selected value inside the select element goes back to "option2"

## 😯 Current Behavior

- On the first navigation, Option is null and the default selected option is "option2"
- When you select any other option, the `option == Option` condition is properly respected and the selected value reflects the value of the query parameter `Option`
- When clicking "Reset url", `Option` goes back to being null and the `Selected` property should be evaluated with `option == "option2"`. However, if you had any other option than `option2` before clicking the option, the select element does not update to `option2`

## 🔦 Context

I have a page where content can be filtered based on various query parameters. One of the query parameters is set after selecting an element inside a `FluentSelect` triggering a navigation through `NavgationManager`.

The same page has a `Home` / `Reset filtering` button that trigger a navigation to the same page with all query parameters removed.

But once I click it, even though the page works properly, the `FluentSelect` is showing a filtering term that is different of what is actually being used (ie: `FluentSelect` shows `Sort by date descending` when the page is sorting by date ascending)

## 🌍 Your Environment

* OS & Device: Windows + Android
* Browse: Edge and Chrome
* .NET and FAST Version: .NET 8 + FluentUI 4.\*-\*

**Comment by vnbaaij** [comment]
If I change your code for the select to:

```
<FluentSelect TOption="string" SelectedOption="@(Option ?? "option2")">
    @foreach (var option in Options)
    {
        <FluentOption OnSelect="OnSelectionChanged" TOption="string" Value="@option">@option</FluentOption>
    }
</FluentSelect>
```
it works for me.
