### ISSUE TITLE
InteractiveWebAssembly with .NET8 and fluent ui is not working

### ISSUE THREAD

**Issue by evilz** [microsoft/fluentui-blazor#1459]
# 🐛 Bug Report

Trying to use InteractiveWebAssembly on page break everything with the following error:

```
blazor.web.js:1 
        
        
       GET http://localhost:5009/_framework/dotnet.js net::ERR_ABORTED 404 (Not Found)
       
Uncaught (in promise) Error: Failed to start platform. Reason: TypeError: Failed to fetch dynamically imported module: http://localhost:5009/_framework/dotnet.js
    at ei (blazor.web.js:1:163985)
```

## 💻 Repro or Code Sample

- create app from template
- add reference to `Microsoft.AspNetCore.Components.WebAssembly.Server`
- add call to AddInteractiveWebAssemblyRenderMode (services and app)
- change rendermode of counter to `InteractiveWebAssembly`

## 🤔 Expected Behavior

Should download blazor page and works.
Can be usefull for the datagrid.

**Comment by vnbaaij** [comment]
Sorry, but this is not an issue report we can work with.
- Which template? 
- What options did you use for that template?
- Is Counter in a Client project? Everything that runs on WebAssembly needs to be in a separate project
