### ISSUE TITLE
fix: fluent-data-grid rendered after rows in manual FluentDataGrid

### ISSUE THREAD

**Issue by SindreSB** [microsoft/fluentui-blazor#1461]
# 🐛 Bug Report

After #1422 the ChildContent for manual grids are not rendered inside of the fluent-data-grid 

## 💻 Repro or Code Sample
This repros even on the docs/demo page, with the simple manual example. Inspecting the rendered page shows the fluent-data-grid element is rendered after all the rows. 

```razor
<FluentDataGrid id="manualGrid" GenerateHeader=GenerateHeaderOption.None GridTemplateColumns="1fr 1fr" TGridItem="string" role="grid">
    <FluentDataGridRow RowType="DataGridRowType.Header" >
        <FluentDataGridCell GridColumn=1 CellType="DataGridCellType.ColumnHeader">Column 1</FluentDataGridCell>
        <FluentDataGridCell GridColumn=2 CellType="DataGridCellType.ColumnHeader">Column 2</FluentDataGridCell>
    </FluentDataGridRow>
    <FluentDataGridRow>
        <FluentDataGridCell GridColumn=1 >1.1</FluentDataGridCell>
        <FluentDataGridCell GridColumn=2>1.2</FluentDataGridCell>
    </FluentDataGridRow>
    <FluentDataGridRow>
        <FluentDataGridCell GridColumn=1>2.1</FluentDataGridCell>
        <FluentDataGridCell GridColumn=2> 2.2</FluentDataGridCell>
    </FluentDataGridRow>
</FluentDataGrid>
```

## 🤔 Expected Behavior

The rows are rendered inside the data grid.

## 😯 Current Behavior

The data grid element is rendered after the rows instead of the rows inside the data grid. This is visible even on the demo site:

![image](https://github.com/microsoft/fluentui-blazor/assets/11072936/04aad00a-2502-4dfb-a208-db140f0f1422)

## 💁 Possible Solution

Revert to rendering child content inside the fluent-data-grid element. Optionally remove the reference to the child content outside of the fluid-data-grid element. 

It's unclear to me why it's rendered outside in the first place. With some guidance, I can try to contribute myself. 

## 🔦 Context

This breaks the manual grid, as column widths are not respected. 

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Microsoft Edge
* .NET and FAST Version: .NET 8 and FAST 4.4

**Comment by vnbaaij** [comment]
THis was caused by a recent change I made in the rendering. Reverting it for 4.4.1 release (later today)
