### ISSUE TITLE
feat: add direct FieldIdentifier parameter to FluentValidationMessage

### ISSUE THREAD

**Issue by thebarrettlo** [microsoft/fluentui-blazor#1465]
# 🙋 Feature Request

Would like to be able to pass a [`FieldIdentifier`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.fieldidentifier?view=aspnetcore-8.0) object to the `FluentValidationMessage` component, rather than only given the option of an accessor expression to pass to `FieldIdentifier.Create()`.

## 🤔 Expected Behavior

Pass a `FieldIdentifier` object as a parameter to `FluentValidationMessage` and the `FluentValidationMessage` use that identifier for querying validation messages.

## 😯 Current Behavior

Right now, the `FluentValidationMessage` component only accepts a `Expression<Func<TValue>>` parameter to specify the accessor that should be used to get a `FieldIdentifier` on the cascaded `EditContext.Model`. This works for compile-time defined models, but not run-time models (see the [Context](#context) section for more info).

## 💁 Possible Solution

An additional parameter could be added, and within `FluentValidationMessage.OnParametersSet()`, check that only either the new parameter or the existing `For` parameter is set.

   ```csharp
   /// <summary>
   /// The <see cref="FieldIdentifier"/> for which validation messages should be displayed.
   /// </summary>
   [Parameter] public FieldIdentifier? Field { get; set; }

   protected override void OnParametersSet()
   {
       ...
       if (Field != null)
       {
           _fieldIdentifier = Field.Value;
       }
       else if (For != null)
       {
       ...
   ```

## 🔦 Context

We are creating dynamic forms that map to different input types depending on the type given at run-time. Rather than supplying an object whose type is known at compile-time to an `EditForm`'s `EditContext.Model`, we are supplying a `Dictionary<TSelector, object?>` as the model. We've gotten this to work, with field validation and all. But for the validation message to render, we cannot pass the accessor using the existing `For` parameter. Having a parameter that takes a `FieldIdentifier` reference allows us to render validation messages for specific fields when we're dynamically generating a form model.

## 💻 Examples

I have copied the `FluentValidationMessage` component files locally and created a `CustomFluentValidationMessage` component with the suggested addition. No other changes were made to the .cs, .razor, or .css files. The component usage in a template looks like:

```razor
<CustomFluentValidationMessage TValue=FieldIdentifier Field=MyFieldIdentifier />
```

Where `MyFieldIdentifier` is a `FieldIdentifier` obtained through the [`EditContext.Field()` method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.editcontext.field?view=aspnetcore-8.0#microsoft-aspnetcore-components-forms-editcontext-field(system-string)).

**Comment by vnbaaij** [comment]
Seems like a worthwhile addition. As you already have most of the code, are you willing/can you create a PR or this?

**Comment by thebarrettlo** [comment]
Yes, I can put a PR up later this week :)

**Comment by thebarrettlo** [comment]
PR #1489 is up with the addition and working example snippet

**Comment by vnbaaij** [comment]
PR is merged. Closing this one
