### ISSUE TITLE
fix: Items not rendering in FluentDataGrid v4.4.0, but does in v 4.3.1

### ISSUE THREAD

**Issue by ejkani** [microsoft/fluentui-blazor#1466]
# 🐛 Bug Report

Items not rendering in FluentDataGrid v4.4.0, but does in v 4.3.1

![FluentDataGrid-NotRenderingItems-v4 4 0](https://github.com/microsoft/fluentui-blazor/assets/1128034/89329273-786d-426b-94db-561fd20144c2)

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorFluentDataGridBug440.Client\BlazorFluentDataGridBug440.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.*-*" />
  </ItemGroup>
  <ItemGroup>

	  <!-- 4.4.0 Does not populate/render FluentDataGrid -->
	  <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.*-* " />       <!-- Effectively using version 4.4.0 -->
	  <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.*-* " /> <!-- Effectively using version 4.4.0 -->

	  <!-- Working version 4.3.1-->
	  <!--
	  <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.3.1" />
	  <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.3.1" />
	  -->
  </ItemGroup>
</Project>

```

## 💻 Repro or Code Sample

https://github.com/ejkani/blazor-fluentdatagrid-bug

## 🤔 Expected Behavior

Expecting to se items in weather data grid.

## 😯 Current Behavior

Data grid is not rendering items, even though the items are populated. Works in v 4.3.1, as shown in repo above.

## 🔦 Context

Error occurs when creating a new project like

```sh
dotnet new fluentblazor -o {your project name}
```

## 🌍 Your Environment

```txt
$ dotnet --version
8.0.101

Microsoft Edge
Version 121.0.2277.106 (Official build) (64-bit)

Windows 11 Pro, version 23H2 (OS Build 22631.3007)
```

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Hi,

This has already been raised and is fixed in the 4.4.1 release. Working on the final touches right now.
