### ISSUE TITLE
GridItemsProvider in FluentDataGrid Fails to Handle Empty List from Remote Service, Resulting in Grid Jam

### ISSUE THREAD

**Issue by jmjcoelho** [microsoft/fluentui-blazor#1467]
# 🐛 Bug Report

Description:
The "GridItemsProvider" component within FluentDataGrid encounters a problem when it receives an empty list as a response from a remote service. This issue leads to an unexpected behavior where the grid becomes unresponsive or jammed during filtering operations.

## 💻 Repro or Code Sample

1. Begin by setting up a FluentDataGrid, incorporating a GridItemsProvider designed to manage remote data retrieval.

2. Customize the FluentDataGrid by adding at least one column and implementing a FluentSearch component. This search functionality is intended to enable filtering based on the contents of the selected column.

3. Initially, with no filtering applied, the FluentDataGrid operates smoothly, rendering all available items correctly.

4. To recreate the issue, input a specific filter condition using the FluentSearch component in a manner that causes the remote service to respond with an empty list. 

5. Following the receipt of an empty list from the remote service, observe that the FluentDataGrid ceases to respond to user interactions. Additionally, the visible items in the grid do not update, even if attempts are made to remove the applied filter.

This is the code of my component
@page "/land/fields"
@using FarmSystem.SharedKernel.Pagination

@inherits BasePage

@inject HttpClient Http
<PageTitle>Weather</PageTitle>

<h1>Fields</h1>

@if (fieldsProvider == null)
{
    <p><em>@Localizer["Loading"]</em></p>
}
else
{
    <div style="height: calc(100vh - 210px); overflow:auto;" tabindex="-1">
        <FluentDataGrid @ref="@grid" Id="fieldsGrid"
                        ItemsProvider="fieldsProvider"
                        ItemSize="35" ItemKey="@(c => c.Id)"
                        GridTemplateColumns="0.5fr 1fr 1fr 2fr 0.5fr 0.5fr 0.5fr"
                        GenerateHeader="GenerateHeaderOption.Sticky"
                        TGridItem=Field
                        Style="height: 100%;" Pagination="@pagination">

            <ChildContent>
                <TemplateColumn Title="@Localizer["Field.Id"]" Sortable="true" Align="@Align.End" SortBy="@sortById">
                        <FluentAnchor Href="#" Appearance="Appearance.Hypertext">@context.Id</FluentAnchor>
                    </TemplateColumn>
                    <PropertyColumn Title="@Localizer["Field.No"]" Property="@(c => c.No)" Sortable="true" Align=Align.Start>
                        <ColumnOptions>
                            <div class="search-box">
                                <FluentSearch type="search" 
                                              Autofocus=true 
                                              Placeholder="@Localizer["Field.No"]"
                                              Value="@noFilter"
                                              ValueChanged="NoFilterValueChanged"/>
                            </div>
                        </ColumnOptions>
                    </PropertyColumn>
                    <PropertyColumn Title="@Localizer["Field.StatesNo"]" Property="@(c => c.StatesNo)" Sortable="true" Align=Align.Start />
                    <PropertyColumn Title="@Localizer["Field.Name"]" Property="@(c => c.Name)" Sortable="true" Align=Align.Start />
                    <PropertyColumn Title="@Localizer["Field.Area"]" Property="@(c => c.Area)" Sortable="true" Align=Align.End Format="n2" />
                    <PropertyColumn Title="@Localizer["Field.TotalArea"]" Property="@(c => c.TotalArea)" Sortable="true" Align=Align.End Format="n2" />
                    <PropertyColumn Title="@Localizer["Field.Type"]" Property="@(c => c.Type)" Sortable="true" Align=Align.End />
                </ChildContent>
                <EmptyContent>
                    <FluentIcon Value="@(new Icons.Regular.Size24.Clipboard())" Color="@Color.Success" />@Localizer["Nothing to see here!"]
                </EmptyContent>
                <LoadingContent>
                    <FluentStack Orientation="Orientation.Vertical" HorizontalAlignment="HorizontalAlignment.Center">
                        @Localizer["Loading"]<br />
                    <FluentProgress Width="240px" />
                </FluentStack>
            </LoadingContent>
        </FluentDataGrid>
    </div>
    <FluentPaginator State="@pagination">
        <SummaryTemplate>
            There are <strong>@(pagination.TotalItemCount ?? 0)</strong> rows
        </SummaryTemplate>
        <PaginationTextTemplate>
            This is page <strong>@(pagination.CurrentPageIndex + 1)</strong> out of a total of <strong>@(pagination.LastPageIndex + 1)</strong> pages
        </PaginationTextTemplate>
    </FluentPaginator>
}

@code {

    private FluentDataGrid<Field> grid;
    private GridItemsProvider<Field> fieldsProvider = default!;
    private HttpClient httpClient;

    private GridSort<Field> sortById = GridSort<Field>.ByAscending(p => p.Id);

    private string noFilter = string.Empty;
    private string statedNoFilter = string.Empty;
    private string nameFilter = string.Empty;
    private Dictionary<string, object> filter = [];

    PaginationState pagination = new PaginationState { ItemsPerPage = 25 };

    protected override async Task OnInitializedAsync()
    {
        httpClient = HttpClientFactory.CreateClient("WebApi");

        fieldsProvider = async req =>
          {
              try
              {
                  var parameters = new Dictionary<string, object>
                                {
                                { "skip", req.StartIndex },
                                { "take", req.Count ?? 25 },
                                };

                  List<string> sortByProperties = [];
                  foreach (var sortedColumn in req.GetSortByProperties())
                  {
                      var field = sortedColumn.PropertyName;
                      var order = sortedColumn.Direction == SortDirection.Ascending ? "asc" : "desc";
                      sortByProperties.Add($"{field} {order}");
                  }

                  if (sortByProperties.Any())
                  {
                      parameters.Add("orderBy", string.Join(",", sortByProperties));
                  }

                  if (!string.IsNullOrEmpty(noFilter))
                  {
                      parameters.Add("Filter", $"no ct '{noFilter}'");
                  }

                  var url = NavigationManager.GetUriWithQueryParameters("fields", parameters);

                  var response = await httpClient.GetFromJsonAsync<PagedList<Field>>(url);

                  return GridItemsProviderResult.From(items: response.Items, totalItemCount: response.TotalItems);

              }
              catch (Exception ex)
              {
                  await HandleErrorAsync(ex);

                  return GridItemsProviderResult.From(items: new List<Field>(), totalItemCount: 0);
              }
          };

        await  Task.CompletedTask;
    }

    private void NoFilterValueChanged(string newValue)
    {
        if (!string.IsNullOrWhiteSpace(newValue))
        {
            if (filter.ContainsKey("no"))
            {
                filter["no"] = noFilter;
            }
            else
            {
                filter.Add("no", noFilter);
            }

            noFilter = newValue;

        }
        else
        {
            noFilter = string.Empty;
            filter.Remove("no");
        }
    }

    // private async Task HandleClear()
    // {
    //     if (string.IsNullOrWhiteSpace(noFilter))
    //     {
    //         noFilter = string.Empty;
    //         filter.Remove("no");
    //     }
    // }

    public class Field
    {
        public int Id { get; set; }

        public string No { get; set; }

        public string StatesNo { get; set; }

        public string Name { get; set; }

        public decimal Area { get; set; }

        public decimal TotalArea { get; set; }

        public string Type { get; set; }

    }
}

**Comment by vnbaaij** [comment]
Hi,

Sorry, but we really need a ready-to-use minimal reproduction or a repo we can use. We do not have capacity to create repro code for every issue ourselves.

Note that if I do filtering as in the https://www.fluentui-blazor.net/DataGrid#typicalusage example, the grid keeps working as expected. Perhaps you can try to do filtering in this way in your code first as well?

**Comment by jmjcoelho** [comment]
Hi Vincent,

Thank you for the swift reply. I've upgraded to the latest version 4.4.1, and the issue has been resolved or is not showing on this version.

Regards
José coelho

**Comment by vnbaaij** [comment]
Cool. Thanks for letting us know. Closing this one.
