### ISSUE TITLE
Fluent Data Grid Items Property Doesn't Change with PreCondition

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/fluentui-blazor#1469]
Fluent Data Grid Items Property Doesn't Change with PreCondition, On Fluent Blazor v4.3.1, i had a Conditonal Items Based on Boolean Which would change Items Property in Runtime whenever the conditon satisfies, This behavior is no longer possible with v4.4.0

```razor
<FluentDataGrid 
Items="@(Search.IsSearchMode ? 
Search.Results.AsQueryable() : Pagination.Items)" 
Pagination="@(Search.IsSearchMode ? null : pagination)">
</FluentDataGrid>
```

**Comment by vnbaaij** [comment]
We made some changes again in 4.4.1. Please re-try with that version.

If the problem persists, then please supply a ready-to-run minimal reproduction. Thanks,
