### ISSUE TITLE
Requesting for multi-selection option in TreeView.

### ISSUE THREAD

**Issue by Sowmyasubramayam** [microsoft/fluentui-blazor#1471]
# 🙋 Feature Request
We would like to have multi-selection option in TreeView. we need to select multiple options for both parent and child items.

## 😯 Current Behavior
Currently, we don't have any checkboxes or multi select options in TreeView.

**Comment by Sowmyasubramayam** [comment]
![treeview](https://github.com/microsoft/fluentui-blazor/assets/124342477/de2ea524-2656-420f-9300-01038dec5a17)
 
TreeView should be like this.

**Comment by vnbaaij** [comment]
This is not planned. Would need to be supported by fluent-tree-view web component first.
