### ISSUE TITLE
fix: Add `FluentMenuItem` checkbox and radio button styling according to Fluent Design

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui-blazor#1472]
# 🐛 Bug Report

![image](https://github.com/microsoft/fluentui-blazor/assets/2365592/80120423-0d62-40dd-ad7d-4b7c7f45475a)

## 🤔 Expected Behavior

I expected to be able to enable checkbox and radio button Fluent Design styling like on the right

## 😯 Current Behavior

Only plain style is available

## 🌍 Your Environment

* .NET and FAST Version 4.4

**Comment by vnbaaij** [comment]
The display of these menu capabilities is done in the underlying web component with a SVG. It does not use `FluentCheckbox` or `FluentRadio` components for this. Styling them that way would lead to people expecting behavior that is not there (i.e. show an empty radio for the not selected items, etc). 

As shown in the example you can choose to use your own SVG for the checkbox (`Slot="checkbox-indicator"`) and radio (Slot="radio-indicator") indicator to style them to your likening but they will remain "just" SVG's. We have no plan or means to change this (as we rely on the web component implementation here).

**Comment by vnbaaij** [comment]
p.s. just checked the next web components version at https://web-components.fluentui.dev/?path=/docs/components-menulist--menu-list and it seems the behavior is not going to change for the next release
