### ISSUE TITLE
FluentSelect with many options renders slowly.

### ISSUE THREAD

**Issue by simsan96** [microsoft/fluentui-blazor#1473]
# 🐛 Bug Report

Rendering multiple FluentSelect components and passing a list containing atleast 100 items via the Items parameter significantly increases rendering time of the component.

## 💻 Repro or Code Sample

Create a blazor application using the Blazor Web App template. 

![image](https://github.com/microsoft/fluentui-blazor/assets/144006602/385b995e-241f-43be-8b59-cdc19adeacd3)

Add 10 FluentSelect components to a page. Pass a list of ~100 strings to the Items parameter in the FluentSelect. 
```
<FluentSelect TOption="string" Items="@strings">
</FluentSelect>

@code {
    IEnumerable<string> strings;

    private IEnumerable<string> GetLongListOfStrings()
    {
        IList<string> longListOfStrings = new List<string>();

        for(int i = 0; i < 100; i++)
        {
            longListOfStrings.Add("123456");
        }
        return longListOfStrings;
    }

    protected override Task OnInitializedAsync()
    {
        strings = GetLongListOfStrings();
        return base.OnInitializedAsync();
    }
}
```

## 🤔 Expected Behavior

The page is rendered without a notable rendering delay.

## 😯 Current Behavior

The page takes ~3 seconds or more to render.

## 💁 Possible Solution

See if performance can be optimized.

## 🔦 Context

I'm developing a blazor application where we need multiple select elements that can include fairly long lists of items. With the performance noticed by doing it like described in this issue this greatly slows down the application on navigation and tab changes. Simply replacing the FluentSelect with an ordinary Select and rendering options in a loop doesn't affect performance at all. 

## 🌍 Your Environment

* Windows 11
* Chrome
* .NET 8
* FluentUI.AspNetCore.Components 4.3.1

**Comment by vnbaaij** [comment]
We'll look into how we can make the performance better. (Started a separate PR for it)

Comparing performance of this to plainn HTML will always be in favor of plain HTML so is a bit moot. These components are doing a lot more work behind and in front of the scenes and that will always come at a price.

**Comment by chrpai** [comment]
Front end newbie here but FWIW I experienced this too with about 2400 rows.  I switched to the Search control using the Interactive with debounce pattern and it works great.   Might be worth looking into for your situation.

https://www.fluentui-blazor.net/Search

**Comment by vnbaaij** [comment]
Made it a bit better for next release. Closing this as we can't do more at this time.

**Comment by parsalotfy** [comment]
I experienced the same issue,  with only 400 items. it takes 1200ms to render.
@vnbaaij  can we have a lazyload=true?
or virtualize?

 I will use Popover and use span inside of it for now, to fix this issue for myself.

**Comment by vnbaaij** [comment]
We are dependent on the underlying web component here. That doesn't support the Virtualize component currently. Lazy load might be an option but I don't see us adding that in the short term. We are quite busy working on the next major version...

**Comment by dvoituron** [comment]
The next version will support a long list of items. You have an example at then end if this page. 

https://fluentui-blazor-v5.azurewebsites.net/List/Select

In the meantime you can use the **FluenAutocomplete** component to do that.
