### ISSUE TITLE
Unable to use Date Control in SSR

### ISSUE THREAD

**Issue by darena-pjindal** [microsoft/fluentui-blazor#1474]
Hello - are these components compatible with SSR? I am developing a Blazor web app with no interactivity.  I am not able to see any calendar on the date controller (See screenshot below). I wanted to check if there are any known limitations with SSR before we use it. Thanks for your help. 
![image](https://github.com/microsoft/fluentui-blazor/assets/45796558/274d17ae-a074-48ac-9bda-4f5a0956b4e2)

**Comment by vnbaaij** [comment]
The limitation is that you can not use the components when they need interactivity to function (not specific to our library). In our case that is what it is like for a lot of them, like the Date picker. It uses a Blazor event to show the Calendar on click.
Sometimes a component may render but with limited functionality, like with the DataGrid, It shows the data but you can not sort on the columns.
