### ISSUE TITLE
fix: Components won't load on iPadOS 15

### ISSUE THREAD

**Issue by weskroesbergen** [microsoft/fluentui-blazor#1481]
# 🐛 Bug Report

We've discovered that the FluentUI components won't load at all on iPadOS 15, while they load perfectly fine on iPadOS 16 & 17.

## 💻 Repro or Code Sample

Visit any site using the Microsoft.FluentUI.AspNetCore.Components library on a device or emulator using iPadOS 15.5.

Example site: https://fluentui-blazor.net

## 🤔 Expected Behavior

The components should load.

## 😯 Current Behavior

Inspecting in Safari tools, we see the following errors:

> MONO_WASM: Failed to import library initializer '../_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js': TypeError: Illegal constructor

> [Error] MONO_WASM: onConfigLoaded() failed
TypeError: The second argument must be a constructor
define
ia — index.ts:308
uv — index.ts:308
asyncFunctionResume
(anonymous function)
promiseReactionJobWithoutPromise
promiseReactionJob
	u (dotnet.js:3:924)
	(anonymous function) (dotnet.js:3:26129)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob

> [Error] MONO_WASM: Failed to load config file ./blazor.boot.json TypeError: The second argument must be a constructor define@[native code]
ia@https://XXXXXXXXXX/_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js:369:378278
uv@https://XXXXXXXXXX/_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js:369:375175
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
@https://XXXXXXXXXX/_framework/dotnet.js:3:26607
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
	u (dotnet.js:3:924)
	(anonymous function) (dotnet.js:3:19967)
	ke (dotnet.js:3:20163)
	(anonymous function) (dotnet.js:3:26596)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob

## 💁 Possible Solution

I suspect that this may be related to SIMD, which is on by default in .Net 8

https://github.com/dotnet/runtime/issues/94231 

Maybe disabling it will solve the issue?
`<WasmEnableSIMD>false</WasmEnableSIMD> `

## 🔦 Context

We have a solution that district school boards use on their iPads. Older devices waiting to be lifecycled due to budget constraints are unable to use the solution.

**Comment by weskroesbergen** [comment]
More context; deploying a build with Microsoft.Fast.Components.FluentUI v3.5.5 on .Net 6 also fails to load on iPadOS 15. This time I get this error:

> [Error] TypeError: Illegal constructor
CSSStyleSheet
Module Code — SplitPanels.js:6
evaluate
moduleEvaluation
moduleEvaluation
(anonymous function)
asyncFunctionResume
(anonymous function)
promiseReactionJobWithoutPromise
promiseReactionJob
	(anonymous function) (blazor.webassembly.js:1:60895)
	promiseReactionJob

**Comment by weskroesbergen** [comment]
Digging into this further, at least on v3.5.5, the issue on iPadOS 15 is that the CSSStyleSheet constructor is only supported in Safari 16.4 and later. It appears the TabPanels use this component.

https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/CSSStyleSheet#browser_compatibility

**Comment by vnbaaij** [comment]
Hi Wes,

Thanks for the PR! Ar e yu looking for a v3.x build of the package specifically or does an updated v4 work for you as well?

**Comment by weskroesbergen** [comment]
V4 is the one I want. I'll submit a PR for v3 later today, hopefully. V3 was what I used to troubleshoot given the errors were a little easier to trace and I knew it wasn't compiled with SIMD.

**Comment by vnbaaij** [comment]
PR is merged. Will be in next elease. Closing this

**Comment by marcusbooyah** [comment]
@vnbaaij I'm seeing this same issue in v4 - any reason it only got fixed in v3?
