### ISSUE TITLE
fix: Memory leak in FluentOverflow

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#1483]
# 🐛 Bug Report

Updated to 4.4.1 and there is:
* A fast memory leak with FluentOverflow.
* Overflow control doesn't show `[+1]` etc when there is an overflow.

I double checked the overflow is the cause of the leak by testing the page with and without the overflow.

**Without (memory usage stays constant):**
![traces-no-overflow](https://github.com/microsoft/fluentui-blazor/assets/303201/8cf80153-d296-4a85-ad88-d3136548d67c)

**With (fast leak to multiple gigabytes of memory):**
![traces-with-overflow](https://github.com/microsoft/fluentui-blazor/assets/303201/a68c4d82-a7b2-455e-b283-a9277cbc6b1c)

## 💻 Repro or Code Sample

https://github.com/dotnet/aspire/pull/2140

Run TestShop app host and then navigate to traces page.

## 🤔 Expected Behavior

Overflow counter is displayed and no memory leak.

## 😯 Current Behavior

No overflow counter and a memory leak.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Cause of this issue has been found. There is a StateHasChanged where it should not be. Will be fixed in next release

**Comment by JamesNK** [comment]
FYI I found perhaps a related issue with FluentOverflow - https://github.com/microsoft/fluentui-blazor/issues/1537. It's the same place where the memory leak was. I'm guessing the rerendering is what triggered the memory leak to grow so fast.

**Comment by vnbaaij** [comment]
This is fixed in 16e6db5f2f081606fa801d6d871cf6e0d2aa7956
