### ISSUE TITLE
fix: invalid markup in weather.razor sample in Fluent Blazor Web App template

### ISSUE THREAD

**Issue by RichardSquires** [microsoft/fluentui-blazor#1486]
# 🐛 Bug Report

Upon generating a new project from the template "Fluent Blazor Web App" using the default settings (so server side, .Net 8 with sample pages ticked) the project is unable to run or build due to a markup error.

## 💻 Repro or Code Sample

1. Install the latest templates (as per your documentation)
2. Create a new project (for me I was using an existing solution file in VS 2022)
3. Leave settings as default with sample pages ticked
4. Attempt to build the project.

## 🤔 Expected Behavior

Build should complete without errors.

## 😯 Current Behavior

Build fails and logs various errors from the invalid markup inside "weather.razor".
`<FluentDataGrid Id="weathergrid" Items="@forecasts"" GridTemplateColumns="1fr 1fr 1fr 2fr" TGridItem="WeatherForecast">`
There is an extra quote at the end of the Items value, this should only be one quote at the end.

## 💁 Possible Solution

Removing the extra quote resolves the issue the line becomes:
`<FluentDataGrid Id="weathergrid" Items="@forecasts" GridTemplateColumns="1fr 1fr 1fr 2fr" TGridItem="WeatherForecast">`

## 🔦 Context

Learning Fluent UI

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser: Microsoft Edge
* IDE: Visual Studio 2022
* .NET and FAST Version: .NET 8 &  Microsoft.FluentUI.AspNetCore.Components 4.4.2-preview.24040.1 (as is from the template)

**Comment by vnbaaij** [comment]
Already known and will be fixed in next release.

Thanks for reporting though!
