### ISSUE TITLE
fix: FluentSelect display issue

### ISSUE THREAD

**Issue by allrightsreserved** [microsoft/fluentui-blazor#1493]
# 🐛 Bug Report

FluentSelect display issue.

## 💻 Repro or Code Sample
Even if there is no selected item in FluentSelect, an item will be displayed. This makes no sense and will cause confusion.

https://www.fluentui-blazor.net/Select
![1](https://github.com/microsoft/fluentui-blazor/assets/14358954/78085c7f-8555-4aa4-b06e-8d137030e339)

![2](https://github.com/microsoft/fluentui-blazor/assets/14358954/88e45b67-9b5f-480d-a442-f0239bf908eb)

## 🤔 Expected Behavior
FluentSelect should display blank when “SelectedOption” or “Value” is empty, and the first option in the drop-down list should not display as selected.

![3](https://github.com/microsoft/fluentui-blazor/assets/14358954/99615344-381d-4fae-bb8b-7e36f826882d)

![4](https://github.com/microsoft/fluentui-blazor/assets/14358954/7b50ab4b-930d-417e-84e8-10058f837d2e)

## 🌍 Your Environment
Windows
Chrome
.NET 8 and Fluent Blazor 4.4.1

**Comment by vnbaaij** [comment]
Sorry, but that is just how this component works. 

We are not planning on changing that as it inherits that behavior from the web component it uses internally. See https://www.fast.design/docs/components/select and https://fluent-components.azurewebsites.net/?path=/docs/components-select--select

You can solve it yourself easily by making sure the items contain option with an empty value and 'placeholder' text.
