### ISSUE TITLE
feat: add context menu

### ISSUE THREAD

**Issue by Amine-Smahi** [microsoft/fluentui-blazor#1498]
Hi team,

is it planned to add a right click context menu ?

Thank you

**Comment by vnbaaij** [comment]
To what? Menu? => https://fluentui-blazor.net/Menu#simplecontextmenu

**Comment by dvoituron** [comment]
Yes, as Vincent said, you can do that using `Trigger="MouseButton.Right"`
```xml
<FluentMenu Anchor="myId4" Trigger="MouseButton.Right" ... />
```
