### ISSUE TITLE
fix: Overlay Fullscreen is ignored and always fullscreen

### ISSUE THREAD

**Issue by zebby-nick** [microsoft/fluentui-blazor#1502]
# 🐛 Bug Report

Fluent Overlays Fullscreen option appears to do nothing. Overlay is always fullscreen regardless of what I seem to set.

## 💻 Repro or Code Sample

```
<FluentOverlay @bind-Visible=@loading
        Opacity="0.8"
        Justification="JustifyContent.Center"
        Alignment="Align.Center"
        FullScreen=false
        Dismissable=false>
    <FluentProgressRing />
</FluentOverlay>
```

and 
```
<div style="width: 500px; height: 500px">
  <FluentOverlay @bind-Visible=@loading
          Opacity="0.8"
          Justification="JustifyContent.Center"
          Alignment="Align.Center"
          FullScreen=false
          Dismissable=false>
      <FluentProgressRing />
  </FluentOverlay>
</div>
```

## 🤔 Expected Behavior

Overlay should stick to its parent container like in the examples. Instead its always full screen even in the second example where I set a div of fixed size.

## 😯 Current Behavior

Currently the above code results in this: 
![Screenshot 2024-02-12 010245](https://github.com/microsoft/fluentui-blazor/assets/50813055/381886aa-dd3b-4252-a2a6-1c62f0f44b15)

![Screenshot 2024-02-12 011302](https://github.com/microsoft/fluentui-blazor/assets/50813055/b8487738-21c0-47ed-92f1-043dbc4689a7)

## 🔦 Context

I am using the overlay to block inputs while loading, I only want to block inputs of the form/body not the menu.

## 🌍 Your Environment

Blazor .Net 8
Google Chrome
Windows 11

**Comment by vnbaaij** [comment]
You can see in the demo site that it is working as intended (ie only full screen when parameter is set to true.
Please supply us with source code or repo with which we can reproduce the issue.

I'm gussing from what I can sse from your screenshots, you are still using Bootstrap? That css might interfere with ours...

**Comment by zebby-nick** [comment]
[OverlayTest.zip](https://github.com/microsoft/fluentui-blazor/files/14254409/OverlayTest.zip)

Here is a example, I have isolated the behavior. The Overlay works as expected when wrapped inside a Fluent Tab just like all the examples on the documentation site. If I use the Overlay with a standard Div it doesnt respect the parents size. I cant see much difference in styles applied to the tabs vs my div. If its expected behavior I can just wrap everything in tabs i guess.

![Screenshot 2024-02-13 091616](https://github.com/microsoft/fluentui-blazor/assets/50813055/a6f710b9-05aa-4132-8d53-3d8ce0ab2c63)

**Comment by vnbaaij** [comment]
As a workaround, you can add the following css (either in the razor file or in you app.css)
```
<style>
    .fluent-overlay {
        position: relative !important;
    }
</style>
```
This will constrain the overlay to the enclosing div and you do not need to put everything in a tab then.

We will work on a fix for the next release,

**Comment by zebby-nick** [comment]
Thats a fantastic help thank you.

**Comment by chigivigi** [comment]
I am having the same issue; the Fluent Tab wraps the Fluent Overlay, but it is not a solution. One of the reasons is that a empty Fluent Tab header is visible on the page.

I am trying to use the Fluent Overlay to disable a form while it is executing. The CSS work around does not work in my example, because the Fluent Overlay does not cover the entire page, only the bottom of the page where it is defined. If I wrap the entire form inside the Fluent Overlay, the form components are not disabled.

Do you have any information regarding the fix for Fluent Overlay?

**Comment by vnbaaij** [comment]
@chigivigi create a new issue with clear and ready-to-run reproduction code/steps/repo. Although your issue has to do with Overlay, it is a different one then described here.
