### ISSUE TITLE
feat: allow cancelation of panel/dialog closing

### ISSUE THREAD

**Issue by rfrancisco** [microsoft/fluentui-blazor#1508]
# 🙋 Feature Request

Panels and Dialogs can be closed by explicit user actions and they can also be closed by pressing escape, by clicking on the backdrop, or the close button on the top-right corner. I believe it's a fairly common scenario to have forms inside these controls, and in these cases, it's useful to show a message when the user tries to close the panel/dialog and has made changes to the form.
Currently there's no way to intercept the close action to validate if the close action is allowed or not.

## 🤔 Expected Behavior

Be able to intercept close request and perform logic to determine if the closing the panel/dialog is allowed or not.

## 💁 Possible Solution

Allow setting a custom function that is called, instead of the default one, when the user tries to close the panel/dialog by clicking the close button, pressing escape, or clicking on the backdrop. Alternatively, it would also work to have a callback function that intercepts the close and allows the developer to implement custom logic (for example show a confirmation messagebox) to determine if the close should proceed or be canceled.

## 🔦 Context

Show a panel with forms. If the user tries to close the form with unsaved changes be able to request confirmation from the user and cancel the close event if the user decides not to lose the changes made.

**Comment by vnbaaij** [comment]
You should be able to do what you want by hooking into the `OnDialogClosing` event callback.

**Comment by rfrancisco** [comment]
> You should be able to do what you want by hooking into the `OnDialogClosing` event callback.

I don't see a way to cancel the closing using OnDialogClosing callback. I looked for usages of OnDialogClosing on the source code but could only find an example of using it to display animations. Is there an example on how it can be used to cancel the operation?

**Comment by vnbaaij** [comment]
> @vnbaaij I don't see a way to cancel the closing using OnDialogClosing callback. I looked for usages of OnDialogClosing on the source code but could only find an example of using it to display animations. Is there an example on how it can be used to cancel the operation?

No, we don;t have an example of that
 
> Also, and I might be getting it wrong, it looks like this event is useful to run code from outside the dialog instance. In the case of dialogs with forms, the decision to prevent the close is made on the dialog itself because he is the one who knows if the form is dirty.

Ok, you might be right there. 

Another way to achieve this is by using `PreventDismissOnOverlayClick` to stop dialog from being closed by clicking outside of it. Combine it with <FluentDialogHeader ShowDismiss="false"> to not show the closiong icon and use the method shown in `SimpleDialog,razor` in "DialogService with IDialogReference" example to disable the 'Save' button as long as the form is not valid.

As we are wrapping a web component, we are not able to intercept all events we would wnt to interceptl

**Comment by rfrancisco** [comment]
> Another way to achieve this is by using `PreventDismissOnOverlayClick` to stop dialog from being closed by clicking outside of it (See "Editable Dialog"). Combine it with to not show the closiong icon and use the method shown in `SimpleDialog,razor` in "DialogService with IDialogReference" example to disable the 'Save' button as long as the form is not valid.
> 

That's the workaround I was already using, but is a pain in terms of user experience.

**Comment by vnbaaij** [comment]
Well for now, that is what we have. We take PR's so if you're willing to submit a change, we would welcome that.

Cloding this as our is not further actionable.
