### ISSUE TITLE
fix: unable to submit form when FluentSelect only has one option

### ISSUE THREAD

**Issue by thebarrettlo** [microsoft/fluentui-blazor#1509]
# 🐛 Bug Report

## 💻 Repro or Code Sample

```razor
<EditForm EditContext=@_editContext OnSubmit=@OnSubmitAsync>
    <FluentSelect @ref=@_multiValueSelect
                  Id=@(nameof(MultiValueEnum))
                  Label=@(nameof(MultiValueEnum))
                  Required=@true
                  TOption=@Enum
                  Items=@(Enum.GetValues<MultiValueEnum>().Cast<Enum>())
                  OptionValue=@(value => value.ToString())
                  OptionText=@(value => value.ToString())
                  OptionSelected=@(value => value == _dynamicModel["Multi value"])
                  SelectedOption=@(_dynamicModel["Multi value"])
                  SelectedOptionChanged=@(value => OnValueChanged("Multi value", value))
                  Value=@(_dynamicModel["Multi value"]?.ToString()) />
    <p>@_dynamicModel["Multi value"]</p>

    <FluentSelect @ref=@_singleValueSelect
                  Id=@(nameof(SingleValueEnum))
                  Label=@(nameof(SingleValueEnum))
                  Required=@true
                  TOption=@Enum
                  Items=@(Enum.GetValues<SingleValueEnum>().Cast<Enum>())
                  OptionValue=@(value => value.ToString())
                  OptionText=@(value => value.ToString())
                  OptionSelected=@(value => value == _dynamicModel["Single value"])
                  SelectedOption=@(_dynamicModel["Single value"])
                  SelectedOptionChanged=@(value => OnValueChanged("Single value", value))
                  Value=@(_dynamicModel["Single value"]?.ToString()) />
    <p>@_dynamicModel["Single value"]</p>
    <FluentButton Type=ButtonType.Submit Appearance=Appearance.Accent Loading=@_loading>Submit form</FluentButton>
</EditForm>

@code {
    private EditContext _editContext = new(new object());
    private Dictionary<string, Enum?> _dynamicModel = new();
    private FluentSelect<Enum> _singleValueSelect;
    private FluentSelect<Enum> _multiValueSelect;
    private bool _loading = false;

    private enum SingleValueEnum
    {
        OnlyValue
    }

    private enum MultiValueEnum
    {
        Value1,
        Value2,
        Value3
    }

    protected override void OnInitialized()
    {
        _dynamicModel = new()
        {
            { "Multi value", null },
            { "Single value", null }
        };
        _editContext = new EditContext(_dynamicModel);
    }

    private async Task OnSubmitAsync()
    {
        _loading = true;
        await Task.Delay(1000);
        _loading = false;
    }

    private void OnValueChanged(string key, Enum value)
    {
        _dynamicModel[key] = value;
    }

    /*
    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            _multiValueSelect.SelectedOptionChanged.InvokeAsync(MultiValueEnum.Value1); // Set value on render
            _singleValueSelect.SelectedOptionChanged.InvokeAsync(SingleValueEnum.OnlyValue); // Set value on render
            _editContext?.NotifyFieldChanged(_editContext.Field("Multi value"));
            _editContext?.NotifyFieldChanged(_editContext.Field("Single value"));
        }
    }
    */
}
```

## 🤔 Expected Behavior

`FluentSelect` should recognize when user interaction/selected option has changed for a single-option selection so that the form can be submitted when there is only a single value that can be selected.

## 😯 Current Behavior

When using a `FluentSelect` component enum values as the `Items`, and the enum contains only one value, the containing `EditForm` cannot be submitted because the `FluentSelect` (or the backing `fluent-select` component?) does not recognize that a value is selected. This is even after user interaction to select the only item in the list.

![image](https://github.com/microsoft/fluentui-blazor/assets/36118918/1c2074b7-dbcd-41f4-88b7-b5e39b51ca12)

In fact, maybe closer to the root of my issue, it seems that the even for a select component with multiple values, user interaction to (re-)select the default/shown value does not trigger the necessary event to indicate that the field has been set.

## 💁 Possible Solution

None found yet, even after searching through the code for `ListComponentBase` and `FluentSelect` for workarounds to manually trigger an event.

The `OnAfterRender(bool)` hook has been attempted to be used to set the initial value on render; inspecting the `FluentSelect` component references in this hook (i.e., `_multiValueSelect.SelectedOptionChanged.InvokeAsync(MultiValueEnum.Value1);` shows the `FluentSelect`'s `InternalValue` and `Value` being changed from `null` to the given value. According to [`ListComponentBase.InternalValue`'s setter](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/List/ListComponentBase.razor.cs), I would expect the component to call `StateHasChanged()` and update through the call to `RaiseChangedEventsAsync()`. Despite this, the component does not recognize that the value has been set for the form's satisfaction.

## 🔦 Context

We are creating dynamic forms with input fields rendered based on the public properties of given `Type`s (see the description in https://github.com/microsoft/fluentui-blazor/pull/1489 for more context on the dynamic form implementation). Some of these properties are enums, and some of those only have one value defined. In these cases, we find that we cannot submit an `EditForm` even after user interaction with the selection component.

## 🌍 Your Environment

* OS & Device: Windows 11, PC, virtual desktop
* Browser: Microsoft Edge
* .NET 8.0, Fluent UI Blazor version 4.4.1

**Comment by vnbaaij** [comment]
I see the behavior in your sample. It exposesitself on the first select too. Just selecting the first item in the select and then hitting submit triggers the validation as well...😕🤯Very weird. Eve more weird is slecting a diffferent value from the first list, clears the validation error.

**Comment by vnbaaij** [comment]
I'm guessing this might have something to do with the fact the list based somponents are not yet derived from `FluentInputBase`. That one is still on our list. It might just be that the problem solves itself once we get the inheritance hooked up (because input base interacts with EditContext/FieldIdentifier).

**Comment by vnbaaij** [comment]
I took a deepre look at inheriting from `FluentInputBase` but could not get it working with that either. Only viable solution i See for the moment is to extend your enumerables with a dummy option and act on that one in the `FluentSelect`s like this:

```
  OptionValue=@(value => value.ToString() == "--dummy--" ? "" : value.ToString())
  OptionText=@(value => value.ToString() == "--dummy--" ? "Please select a value" : value.ToString())
:
 private enum SingleValueEnum
 {
     --dummy--,
     OnlyValue
 }
```

That way you always need to select a value from the list and it is always going to be  a valid value.  If anyone has another option to solve this in a better way, I'm all ears.

**Comment by thebarrettlo** [comment]
I appreciate you trying out `FluentInputBase` as a solution! A dummy value was the only workaround I could think of too. The validation error in this case is coming from the underlying FAST component, right? My train of thought is that there must be some kind of event that is not being triggered to tell the component that the value has been set when binding the value in this way.

**Comment by vnbaaij** [comment]
It seems to come from the underlying web components indedd. Fixing it there will probably take a while so going the dummy options is, for now the best workaround.

If that is a workaround you can live/work with, then I think we can close this one, agreed?

**Comment by thebarrettlo** [comment]
If that's the only workaround, then I'll make it work! If anyone comes across this issue in the future with another suggestion, please tag me :)
