### ISSUE TITLE
FluentFooter dynamic positioning and high navigation with a lot of items do not work together...

### ISSUE THREAD

**Issue by ZnowuJa** [microsoft/fluentui-blazor#1510]
# 🐛 Bug Report

FluentFooter is not properly positioned at the bottom of browser window when you create and expand so long navigation that it is higher than browser. Even resizing window do not fix bad footer position.
If you have normal short navigation then FluentFooter works perfect.

![image](https://github.com/microsoft/fluentui-blazor/assets/70036908/200f253b-b670-476a-a383-f57b56387d2c)

## 💻 Repro or Code Sample

https://github.com/ZnowuJa/Second-FluentSelect-Crashesh.git

## 🤔 Expected Behavior

Footer should always be at the bottom, dynamically even if you have long menu. Last item from menu should also be visible.

## 😯 Current Behavior

If you expand navigation menu from my example above (both: IT CMDB and IT CMDB Settings>Dictionaries) and try to scroll window to get navitems below the bottom of browser, then footer is moving like it was anchored. Additionally it hoods the navitem which initially was on footer's level.

## 🌍 Your Environment

Windows, VS 2022 Pro, Edge, Chrome, FluentUI 4.3.1 and 4.4.0 (tested in both)

**Comment by vnbaaij** [comment]
This is a simple CSS thing. Has nothing to do with library in particular. 
To fix add `flex: 1;` in your `app.css` file.

**Comment by ZnowuJa** [comment]
Unfortunately it doesn't help. In Edge it became even worse.
Footer positioning also not.
JS also was not helpful (which is strange).  

But I realized it is a very bad design to create such long menus, so I shortened it to one page of "settings " with cards pointing to proper subpages.

Thank you very much for your very fast response!
