### ISSUE TITLE
rfc: change FluentBadge's dismiss icon margin

### ISSUE THREAD

**Issue by joriverm** [microsoft/fluentui-blazor#1511]
# 💬 RFC
in the application i am making with my client's team we are using a font that is smaller than the default font used in fluentUI & has its alignment higher than normal fonts... (its euh... not a fun font!)
Overal this works normal and as expected as we compensate for the smaller font by adjusting all the css variables related of line-height & font-size. 
However, in the FluentBadge's content ive noticed the dismiss icon has standard margin of 2px top and 2px left.
The Left pixels is fine, but the top pixels make the badge look off as seen in the screenshot.
![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/569e8938-1ed2-4d1b-bbbe-e2d83559a183)

After some investigations ive noticed that the text in the dom has only 14 pixels height, compared to the 16 in the storybook. this makes the margin of the icon off.
Therefor, Ive changed this margin to `margin: calc(calc(var(--type-ramp-minus-1-line-height) - 12px) / 2) 0px 0px 2px` so its kinda positioned in the centre of the line height. it looks as following : 

![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/9abc6811-0b61-4b9d-b8e0-5734de40a0b2)

it looks better, but because of the kind of fix, im not feeling particular good with it.
Im also sorry i can not share the font, as it is a font paid for by my client.

## 🔦 Context
we are using the Autocomplete to select items, but the dismiss icon on the icons looks off when using smaller fonts. we could overwrite it, but would prefer not to do so. we could also leave the line-height as is, but this ends up taking useless space in the UI, as the font is smaller.

## 💻 Examples
Ive tried to reproduce it using the default font, but was unable to do so sadly... the only example i can give is above screenshots with the data that the line-height was 14px (16px in storybook) and the text is up higher than default.

**Comment by vnbaaij** [comment]
Hi, 

I'm not sure what your ask is here. 

If you are achieving what you need with changing the marging yourself, then I'd say go for it! As it is only an issue in your situation with a particular font, I don't think there is a lot of chance we are going to make changes on or side,
