### ISSUE TITLE
IDictionary<String,Object> this object is passed in items in data grid, error comes in sorting.

### ISSUE THREAD

**Issue by Pavithra-Vijayakumar** [microsoft/fluentui-blazor#1516]
# 🐛 Bug Report

Converted datatable object to IDictionary<String,Object>, and passed this as an input to fluent data grid values binded properply but sorting is not working.

**Comment by vnbaaij** [comment]
No repro code, no steps, no version info ==> No help

Follow the template. It is provided for a reason.

You probably need to specify your own GridSort like:
```
GridSort<Country> nameSort = GridSort<Country>.ByAscending(x => x.Name, StringLengthComparer.Instance);
```
