### ISSUE TITLE
fix: Can't remove more than one letter at once in `FluentAutocomplete`

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#1524]
# 🐛 Bug Report

When text in a `FluentAutocomplete` is selected (for example using CTRL + A) and pressing Backspace to remove the letters, only the last letter is removed instead of all selected letters.

## 💻 Repro or Code Sample

This bug can be observed on the Fluent UI Blazor components demo page (https://www.fluentui-blazor.net/Autocomplete).
Just select one of the examples' inputs, input more than one letter, press CTRL + A and afterwards press the Backspace button on your keyboard.

## 🤔 Expected Behavior

All letters should be removed.

## 😯 Current Behavior

Only the last letter is removed.

**Comment by dvoituron** [comment]
Thanks for your feedback.
This issue will be fixed in the next release, via this PR #1544
