### ISSUE TITLE
fix: Can't build the code in Visual Studio Preview VisualStudio.17.Preview/17.10.0-pre.1.0+34607.79

### ISSUE THREAD

**Issue by neosign** [microsoft/fluentui-blazor#1532]
# 🐛 Bug Report
![1708245301129](https://github.com/microsoft/fluentui-blazor/assets/4457571/e7b0eae3-aeca-4b12-b795-73a1366b011a)

Scenario 1
1. I just created new project using Fluent Blazor Web App template  using Visual Studio Community 2022 Preview
2. Then tried to build the code error as above
Scenario 2
1. Create project by using command dotnet new fluentblazor --name MyApplication 
2. Open with Visual Studio Community 2022 Preview and then tried to build the code error as above
 

## 🤔 Expected Behavior
It should be built successfully on the fresh Project on command on vs template

## 🔦 Context
Just wanted to try to find boilerplates for blazor web project. found fluent blazor interesting.
FYI. not experts in any C#,( I am from Springboot realm)

## 🌍 Your Environment
OS Windows 10 
Visual Studio community 2022 Preview
Dotnet v.8.0.200

![1708245367619](https://github.com/microsoft/fluentui-blazor/assets/4457571/b521cc86-6d50-44aa-a390-d6f7547bcde9)
![1708245326489](https://github.com/microsoft/fluentui-blazor/assets/4457571/6b5dbb18-9e8c-4b82-bd6c-e0307c473693)![1708245791486](https://github.com/microsoft/fluentui-blazor/assets/4457571/3a71c453-0923-421a-a06c-69fec4d3365f)

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by dvoituron** [comment]
This error has already been detected (#1486) and will be corrected in the next version.

To correct it, it's very simple: just follow the instructions given by the compiler: 
Remove the second **double-quote** added by mistake in the **Weather.razor** page (Items` attribute).

```razor
                                                  ⬇️
<FluentDataGrid Id="weathergrid" Items="@forecasts"" GridTemplateColumns="1fr 1fr 1fr 2fr" TGridItem="WeatherForecast">
```

**Comment by neosign** [comment]
thanks @dvoituron
