### ISSUE TITLE
ValueChanged never trigerred in FluentWizard

### ISSUE THREAD

**Issue by ejalbertinfoej** [microsoft/fluentui-blazor#1534]
# 🐛 Bug Report

Using the sample demo code, we have this code:
```
<FluentWizard Id="customized-wizard"
              @bind-Value="@Value"
              StepTitleHiddenWhen="@GridItemHidden.XsAndDown"
              Height="300px">
```
and this in the code block:

```
@code
{
    int Value = 0;
}
```

when clicking 'Next' button in the wizard, the Value stays at 0.  The ValueChanged callback method is never called.

## 💻 Repro or Code Sample

add this line over the FluentWizard:
```
@Value
```

## 🤔 Expected Behavior

The Value variable follow the step currently displayed

## 😯 Current Behavior

The Value variable is always 0 and never change.

## Fix:

just add this code before line 183 in the Microsoft.FluentUI.AspNetCore.Components/Components/Wizard/FluentWizard.razor.cs
```
await ValueChanged.InvokeAsync(targetIndex);
```
I tried to create a pull request, but had no success with Git in my Visual Studio ! sorry!

**Comment by dvoituron** [comment]
Thanks for your work. I fixed this in this PR #1538 which will be included in the next release.
