### ISSUE TITLE
fix: [IconColor="Color.Custom"] in [FluentNavLink] : the color cannot be set

### ISSUE THREAD

**Issue by KaniSchotski** [microsoft/fluentui-blazor#1535]
# 🐛 Bug Report

I want to set the color of the Icon in the FluentNavLink tag to a custom color. That does not seem to work. 

## 💻 Repro or Code Sample

I downloaded the Fluent UI blazor template with Individual Accounts (dotnet 8). In the NavMenu.Razor component, I tried to change the color of an icon to a custom color. I used the following code :

<FluentNavLink Href="auth" Icon="@(new Icons.Regular.Size20.LockClosedKey().WithColor("#ff0000"))" IconColor="Color.Custom">Auth Required</FluentNavLink>

## 🌍 Your Environment

Windows 11
Visual Studio (latest)
Dotnet 8 (latest)
Blazor
C#
Fluent Blazor Web app
Browser : Edge, Chrome

**Comment by dvoituron** [comment]
Thanks,

This issue will be fixed when this PR #1539 is merged into the `dev` branch.
This will be included in the next release.
