### ISSUE TITLE
fix: FluentDataGrid OnRowFocus and sorting not working when contained in FluentGrid

### ISSUE THREAD

**Issue by MxNbrt** [microsoft/fluentui-blazor#1540]
# 🐛 Bug Report

I tried to implement an OnRowClick event for the FluentDataGrid as already mentioned in #779 (I understand that this is not possible because of the underlying library). Then i stumbled across the same bug reported in #1343 but can now reproduce it.

## 💻 Repro or Code Sample

1. Create a new Blazor Server project with .NET 8
2. Add to csproj the PackageReference "Microsoft.FluentUI.AspNetCore.Components" in Version 4.4.1 (latest as of now)
3. Change content of Home.razor to

```
@page "/"
@using Microsoft.FluentUI.AspNetCore.Components

<PageTitle>People</PageTitle>

<FluentGrid>
    <FluentGridItem>
        <FluentDataGrid Items="@people" TGridItem="Person" OnRowFocus="HandleRowFocus">
            <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" />
            <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
            <PropertyColumn Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
        </FluentDataGrid>
    </FluentGridItem>
</FluentGrid>

@code {
    record Person(int PersonId, string Name, DateOnly BirthDate);

    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9)),
    }.AsQueryable();

    private void HandleRowFocus(FluentDataGridRow<Person> row)
    {
        Console.WriteLine($"Row focused: {row.Item?.Name}");
    }
}
```

## 🤔 Expected Behavior

The FluentDataGrid should
- execute the HandleRowFocus method if i click on the row
- and also sort the rows if i click on one of the headers

## 😯 Current Behavior

The FluentDataGrid does
- execute the HandleRowFocus method if i click on the row ✅ 
- but does not sort the rows if i click on one of the headers ❌ 

## 💁 Possible Solution

If I remove the containing FluentGrid and FluentGridItem, everything works as expected.

## 🔦 Context

Usually you have a FluentGrid on every page to do the styling and eventually it contains a FluentDataGrid to display a large amount of data. So I think, this is a pretty common scenario.

## 🌍 Your Environment

Windows
.NET 8.0.2
Blazor Server
Google Chrome latest
FluentUI Blazor 4.4.1

Thank you very much 😄

**Comment by vnbaaij** [comment]
With Server project, default for Homepage will be SSR. 
For sorting to work you need interactivity. Apply a @rendermode to the component, page or Router in App.razor

**Comment by MxNbrt** [comment]
Hi @vnbaaij 

The App.razor has already set the @rendermode to InteractiveServer:

![image](https://github.com/microsoft/fluentui-blazor/assets/21066449/3bfe0226-df34-4340-b9f8-6423216bb6a8)

I also tried setting it explicitly on the Home.razor by adding `@rendermode InteractiveServer ` but this has no effect.
So could you please have another look or further elaborate on your comment?

Thanks

**Comment by vnbaaij** [comment]
Ok, I assumed SSR was the culprit. Will take  a closer look, but not for another week (ooo).

**Comment by vnbaaij** [comment]
Will be fixed with mentioned PR. 

Turns out it has nothing to do with being in a FluentGrid. Sorting did not work because the OnRowFocus was capturing the click and sorting never got called. With this PR OnRowFocus/OnCellFocus will only get clled for default rows/cells.
