### ISSUE TITLE
Visual inconsistency with the FluentMenu

### ISSUE THREAD

**Issue by garrenf** [microsoft/fluentui-blazor#1541]
I've noticed that with a FluentMenu having rounded corners, the parent div does not have a border-radius applied to it, actually giving it a squared look. Here I have taken screenshots of what it looks like (red circle) vs. what it should actually look like (green circle).

![fm](https://github.com/microsoft/fluentui-blazor/assets/144177629/b103067c-629d-4034-850a-3de3bab30761)
![fm2](https://github.com/microsoft/fluentui-blazor/assets/144177629/4891c3f4-5e17-44be-9924-4390a84f2753)

This squared look can even be seen in the demo in the documentation here. https://www.fluentui-blazor.net/Menu
Although hardly noticeable, its something that I've noticed and somewhat bothers me.

**Comment by vnbaaij** [comment]
Thanks for supporting and reporting that. We will fix this for the next release.

**Comment by vnbaaij** [comment]
Fixed with the commit mentioned above.
