### ISSUE TITLE
fix: Id attribute not being rendered out to html in FluentNavLink

### ISSUE THREAD

**Issue by NickHirras** [microsoft/fluentui-blazor#1547]
# 🐛 Bug Report

I'd like to render an `id` property on the resulting `a href` link of a `FluentNavLink` component.  We're writing some selenium tests against our application, and having an `id` field to target these links would make test writing and maintenance easier.  

## 💻 Repro or Code Sample

```
<FluentNavLink Id="nav-link-home" Tooltip="Home" Href="/" Match="NavLinkMatch.All" Icon="@(new Icons.Regular.Size20.Home())" IconColor="Color.Accent">Home</FluentNavLink>
```

## 🤔 Expected Behavior

I was expecting `id="nav-link-home"` to show up in the DOM, either on the `<a href` link element, or the parent `<div class="fluent-nav-item"...`.  

## 😯 Current Behavior

The Id is not appearing.  Performing a `document.getElementById('nav-link-home')` returns nothing.

![image](https://github.com/microsoft/fluentui-blazor/assets/3911628/7d45e61a-29df-4141-9d4e-ac362b353498)

## 🔦 Context

Would like the ability to target elements by `id` when performing automated testing through a browser driver such as selenium.

## 🌍 Your Environment

MacOS 14.2.1 (arm)
Chrome Version 121.0.6167.184 (Official Build) (arm64)
DotNet SDK 8.0.101

**Comment by NickHirras** [comment]
That would work well for me.

**Comment by vnbaaij** [comment]
Fixed in commit mentioned above. Will be in next release.
