### ISSUE TITLE
fix: FluentMenu positioning & rendering not correct when created inside of a new containing block.

### ISSUE THREAD

**Issue by DanielCordell** [microsoft/fluentui-blazor#1548]
# 🐛 Bug Report

When a `<FluentMenu>` is created inside of a new [Containing Block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block) (such as a div with `container-type: inline-size` to allow for [container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries#using_container_queries)), it causes a few miscelaneous visual glitches. See **Current Behavior** for a more detailed breakdown.

## 💻 Repro or Code Sample

You can reproduce this trivially by going to `https://www.fluentui-blazor.net/Menu` and in devtools, adding the rule `container-type: inline-size;` to the `.demo-section-example` selector:

![image](https://github.com/microsoft/fluentui-blazor/assets/16806427/c977a1b0-932e-429b-9ec1-aef2f0327888)

## 🤔 Expected Behavior

The menu should act as it does if there is no new containing block containing it.

### Z-Index not taking effect

You can see that because of the new containing block being created, the high z-index of the menu isn't taking effect:

![image](https://github.com/microsoft/fluentui-blazor/assets/16806427/a98fcb06-5e6e-42f2-96d5-aa097b0eb6ab)

Compare that to the same thing without the containing block:

![image](https://github.com/microsoft/fluentui-blazor/assets/16806427/ebf86926-3225-4e6c-a8d3-52eb53df5140)

### Un-Anchored menus appearing at the wrong coordinates

When creating an un-anchored menu (such as a context menu), the position of the fixed menu element becomes relative to the _containing block_, and not relative to the window:

- Blue dot is where I right-clicked, the menu that spawned is circled in red.

![image](https://github.com/microsoft/fluentui-blazor/assets/16806427/ec25f0be-10b5-4f65-a89c-4ccd52bdd975)

Removing the `container-type: inline-size` cause the menu to go back to where it should:

![image](https://github.com/microsoft/fluentui-blazor/assets/16806427/d8196467-80c7-4913-bcba-0bec316e0d50)

## 💁 Possible Solution

Could menus spawn at the top-level, similar to the dialogs/toasts/tooltips? Perhaps a `<FluentPopupProvider/>`, or you could make use of one of the existing providers? That would ensure that no "local CSS" rules could affect the menus.

## 🔦 Context

I'm sure this will affect other contexts, but creating menus in layouts that are dynamic & adjust via container queries is where I've noticed this. As you can see from [this MDN link](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block), lots of things can spawn a new containing block and it would be frustrating for me if the menu just couldn't be used in these cases.

There may be other fluent components that act in a similar way that will likely have the same issues.

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser: Affects Chrome, Edge & Firefox
* .NET and FAST Version: Tested locally on `Net6` & FluentUI Blazor `3.5.5`, but also able to reproduce on https://www.fluentui-blazor.net/Menu on which I assume is the latest release.

**Comment by vnbaaij** [comment]
Hi,

This is not something we will be able to support with the current Fluent design system (v1). It pre-dates browsers container support and I think it will be very hard to get it 'integrated' in a good and stable way.

I'm hopefull that the next version of the Web Components (v3) will support this.

**Comment by vnbaaij** [comment]
If you are able and have time to work on a provider kind of solution, we will happily take a PR

**Comment by DanielCordell** [comment]
> I'm hopefull that the next version of the Web Components (v3) will support this. See https://web-components.fluentui.dev/?path=/docs/components-menu--menu and add container-type: inline-size; to one of the buttons. Menus show up in the right place.

I'm not too sure. On that site, if I add `container-type: inline-size` to the grey container (shaded crudely in red) it seems to render weirdly:

![image](https://github.com/microsoft/fluentui-blazor/assets/16806427/7836f648-0f70-402e-92e1-b46d7327f422)

Perhaps this is something that may need forwarding on to the web components repo?

> If you are able and have time to work on a provider kind of solution, we will happily take a PR

I'd be happy to have a go when I get the time! :)

**Comment by vnbaaij** [comment]
> Perhaps this is something that may need forwarding on to the web components repo?

Yes! Would be great if you can raise an issue there.

**Comment by vnbaaij** [comment]
Closing this as we can't solve it on our side.

**Comment by DanielCordell** [comment]
To update on this (for my own benefit) it looks like v3 has fixed this!

> > I'm hopefull that the next version of the Web Components (v3) will support this. See https://web-components.fluentui.dev/?path=/docs/components-menu--menu and add container-type: inline-size; to one of the buttons. Menus show up in the right place.
> 
> I'm not too sure. On that site, if I add `container-type: inline-size` to the grey container (shaded crudely in red) it seems to still render weirdly:
> 
> ![image](https://private-user-images.githubusercontent.com/16806427/308976505-7836f648-0f70-402e-92e1-b46d7327f422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDc1MTcsIm5iZiI6MTcyNzM0NzIxNywicGF0aCI6Ii8xNjgwNjQyNy8zMDg5NzY1MDUtNzgzNmY2NDgtMGY3MC00MDJlLTkyZTEtYjQ2ZDczMjdmNDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEwNDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MzYwNmQ4Mjk5MGMwYWI0MmVkZTM4YWRmYTliZDAzZDhjMGY4OTk1ZDQxZGI3YTQ1YWFlNzkxNjBlMzZjMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xm57u80XXKtNiW0RIAKXtNLi2rOxVia9yi_gDCtkAIE)
> 
> Perhaps this is something that may need forwarding on to the web components repo?
> 
> > If you are able and have time to work on a provider kind of solution, we will happily take a PR
> 
> I'd be happy to have a go when I get the time! :)
> 
> We did something similar at work a while back before migrating to Fluent, so it's definitely doable.
