### ISSUE TITLE
feat: add automatic position adjustment to FluentMenu to prevent opening off-screen.

### ISSUE THREAD

**Issue by DanielCordell** [microsoft/fluentui-blazor#1549]
# 🙋 Feature Request

It would be great if the `<FluentMenu>` component would adjust the position it was created in if it would be hidden by being partially outside of the window. This would make the menus function similarly to native menus that dynamically adjust to avoid being obscured.

## 🤔 Expected Behavior

Menus upon opening adjust their position to avoid being partially outside of the window.

(manually adjusted in this screenshot below)
![image](https://github.com/microsoft/fluentui-blazor/assets/16806427/5846d2b9-c6fd-4024-82a7-445c75d59ed2)

## 😯 Current Behavior

The menu appears half "outside" of the window, meaning it cannot be interacted with.

![image](https://github.com/microsoft/fluentui-blazor/assets/16806427/12d0cd8b-2aa3-4fd3-a022-a874440b8bc6)

This occurs for both anchored and non-anchored menus.

## 🔦 Context

Menus on the right-hand-side of the window / at the bottom of the window are being cut off by the window itself.

**Comment by vnbaaij** [comment]
This will be fixed the next version (v3) of the underlying web components. We can't change that ourselves.

**Comment by DanielCordell** [comment]
Awesome, thanks for the update! Is there a specific timeline as to when V3 comes out, and in what version of FluentUI Blazor that would apply to? I can't find anything on the FluentUI repo about a V3 release date.

**Comment by vnbaaij** [comment]
One thing we are changing is adding  VerticalThreshold and HorizontalThreshold parameters which will help in positioning the menu better. See #1640 for more info.
I'll close this issue in favor of that one
