### ISSUE TITLE
NavMenu hover in Fluent Blazor Web App template

### ISSUE THREAD

**Issue by achmstein** [microsoft/fluentui-blazor#1558]
# 🐛 Bug Report

I created a new blazor app using Fluent Blazor Web App, but when I hove on NavMenu item there's no hover color. How can I make it look like fluentui-blazor website.

**Comment by vnbaaij** [comment]
This can be done with standard CSS styling and variables.

For the demo site (code is here in repository) it is done like this :

nav.sitenav {
    background-color: var(--neutral-layer-1);
    padding: 1.5rem 1rem;
    height: calc(100dvh - 90px);
    width: 18rem;
    overflow-y: auto;
}

**Comment by achmstein** [comment]
@vnbaaij Thank you
