### ISSUE TITLE
fix: valueChanged not work well when user type a value in FluentCombobox

### ISSUE THREAD

**Issue by kamazheng** [microsoft/fluentui-blazor#1559]
FluentCombobox when user type a value (not select from list), the valuechanged event triggered twice, the first time is correct, the second time passed in null value, overwrite the correct value.

```C#

<h4>Combobox</h4>
<FluentCombobox Value="@comboboxValue" ValueChanged="valueChanged" Items="@items">
</FluentCombobox>

@code {
    string? comboboxValue = "Small";
    List<string> items = new List<string> { "Extra Small", "Small", "Medium", "Large", "Extra Large" };

    private void valueChanged(string value)
    {
        comboboxValue = value;
        Console.WriteLine("Value changed");
    }
}

```

![combox](https://github.com/microsoft/fluentui-blazor/assets/49426393/93119f79-e98c-4477-bca5-caf462e8568d)

version of fluent: 
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.3.0" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.DataGrid.EntityFrameworkAdapter" Version="4.3.0" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.3.0" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.3.0" />

**Comment by kamazheng** [comment]
![combox](https://github.com/microsoft/fluentui-blazor/assets/49426393/015a034d-893e-42f3-9c9e-dbbf9937d73e)

**Comment by vnbaaij** [comment]
Your version info shows 4.3 (in the email GH sent). Try it on the latest release first. 
There are more changes coming for Combobox in next release.

As a FYI, we do not do backports of changes/fixes within a main version range, so there will not be a 4.3.x release fixing this. Only latest will get it.

**Comment by vnbaaij** [comment]
Can't replicate the behavior you described. 

When using this code:
```
<h4>Combobox</h4>
<FluentCombobox @bind-Value="@comboboxValue" Items="@items">
</FluentCombobox>
<p>@comboboxValue</p>

@code {
    string? comboboxValue = "";
    List<string> items = new List<string> { "Extra Small", "Small", "Medium", "Large", "Extra Large" };
}
```
The value displayed in the `<p></p>` corresponds with what gets typed in the combo.
