### ISSUE TITLE
fix: Title property not being rendered for DataGrid column header in PropertyColumn

### ISSUE THREAD

**Issue by NickHirras** [microsoft/fluentui-blazor#1561]
# 🐛 Bug Report

When I provide a `Title` property on my `<PropertyColumn...>` tag, there is not Title rendered in the DOM. I am not using a _ColumnBase.HeaderCellItemTemplate_ on this column.

```
    <PropertyColumn Title="Card Last Four" Property="@(c => c!.CardLastFour)" Sortable="true">
      <ColumnOptions>
        <div class="search-box">
          <FluentTextField DisplayName="Card Last Four" @bind-Value="RequestModel.CardLastFour" Label="Card last four"/>
        </div>
      </ColumnOptions>
    </PropertyColumn>
```

## 🤔 Expected Behavior

Expected `Title` attribute to be rendered in DOM.

## 😯 Current Behavior

The `Title` attribute is ignored.

```
<fluent-data-grid-cell cell-id="c5" cell-type="columnheader" grid-column="4" class="column-header col-justify-start" aria-sort="none" scope="col" b-w6qdxfylwy="" tabindex="-1" role="columnheader" style="grid-column: 4;">
...
```

## 🌍 Your Environment

* MacOS arm64
* Chrome latest (arm64)
* .NET 8.0.101

**Comment by vnbaaij** [comment]
The title attribute is not rendered on the fluent-datagrid-cell but on a div inside the cell (class="col-title-text") and only when the Tooltip parameter is set to `true` (see https://www.fluentui-blazor.net/DataGrid#propertycolumn%3Ctgriditem,-tprop%3E-class)
