### ISSUE TITLE
fix: When clicking anywhere on the datagrid, all content within the datagrid disappears, leaving only the border visible.

### ISSUE THREAD

**Issue by liubin3071** [microsoft/fluentui-blazor#1565]
# 🐛 Bug Report
When clicking anywhere on the datagrid, all content within the datagrid disappears, leaving only the border visible.
<img width="1227" alt="fa5caf7f-ce6b-4bd1-bc4b-63f307d519ab" src="https://github.com/microsoft/fluentui-blazor/assets/21308496/504f1f7d-9af6-4b24-a347-4660f185b507">

## 💻 Repro or Code Sample
https://github.com/liubin3071/BlazorApp4

## 🌍 Your Environment
windows

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
You have created your own `PropertyColumn` and `TemplateColumn` components. Sorry, but we don not hav capacity to support you with that.

**Comment by liubin3071** [comment]
> You have created your own `PropertyColumn` and `TemplateColumn` components. Sorry, but we don not hav capacity to support you with that.

```
public class NoneComponent : ComponentBase
{
    [Parameter] public string Id { get; set; }
    [Parameter] public RenderFragment ChildContent { get; set; }

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.AddContent(0, ChildContent);
    }
}
```

```
<FluentDataGrid TGridItem="Person" ItemsProvider="ItemsProvider2">
    <NoneComponent>
        <PropertyColumn TGridItem="Person" TProp="string" Property="@(c => c.Name)"></PropertyColumn>
    </NoneComponent>
</FluentDataGrid>
```

I have done more testing. As per the above code, everything works fine when starting the project with app.MapRazorComponents<App>().AddInteractiveServerRenderMode();. However, when starting the project with _Host.cshtml, a bug occurs."
