### ISSUE TITLE
feat: add Timeout Parameter to FluentSplashScreen

### ISSUE THREAD

**Issue by MxNbrt** [microsoft/fluentui-blazor#1566]
# 🙋 Feature Request

I really like the FluentSplashScreen and use it to display my users that a long running operation is still being processed. But with FluentSplashScreen there is a problem, that it closes after 4 seconds no matter what i do. I want it to stay open forever and close it by calling Dialog.CloseAsync().

## 🤔 Expected Behavior

Splashscreen stays open forever

## 😯 Current Behavior

Splashscreen closes after 4 seconds

## 💁 Possible Solution

Maybe you could introduce a parameter "Timeout" on SplashScreenContent, which regulates how long the Splashscreen will be displayed (default value can stay 4000 milliseconds as already hardcoded in \src\Core\Components\Dialog\ContentComponents\FluentSplashScreen.razor.cs).

## 🔦 Context

Waiting screen for operation running longer than 4 seconds.

**Comment by dvoituron** [comment]
Will be solved via #1570

**Comment by MxNbrt** [comment]
Thats exactly what I was hoping for. Thank you very much for your fast reaction and implementation 😄
