### ISSUE TITLE
I have a "FluentDataGrid" in which i want to get the row data on click for that i am using "OnRowFocus" event which is not working . How i can console the row data on click ?

### ISSUE THREAD

**Issue by prince16288** [microsoft/fluentui-blazor#1568]
# 🐛 Bug Report

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS1503	Argument 2: cannot convert from 'method group' to 'Microsoft.AspNetCore.Components.EventCallback'	BlazorApp3	C:\Users\hp\Downloads\Telegram Desktop\BlazorApp3\BlazorApp3\BlazorApp3\Dummy\Component1.razor	4	

## 💻 Repro or Code Sample

<FluentDataGrid Items="@stock" OnRowFocus="HandleRowFocus">
    <PropertyColumn Property="@(p => p.StockCode)" Sortable="true" />
    <PropertyColumn Property="@(p => p.SKU)" Sortable="true" />
    <PropertyColumn Property="@(p => p.Description)" Sortable="true" />
    <PropertyColumn Property="@(p => p.Price)" Sortable="true" />
    <PropertyColumn Property="@(p => p.QTY)" Sortable="true" />
    <PropertyColumn Property="@(p => p.Total)" Sortable="true" />
    <PropertyColumn Property="@(p => p.D)" Sortable="true" />
</FluentDataGrid>

@code {

    private void HandleRowFocus(FluentDataGridRow<Stock> row)
    {
        var rowData = row.Item; // Access the data associated with the focused row
    }

    private IQueryable<Stock> stock = new[]
    {
          new Stock(false,"10895", "Jean Martin", "Description 1", 10.00m, 5, 50.00m, "D1", "R1"),
        new Stock(false,"10944", "António Langa", "Description 2", 15.00m, 3, 45.00m, "D2", "R2"),
        new Stock(false,"12203", "Julie Smith", "Description 3", 20.00m, 7, 140.00m, "D3", "R3"),
        new Stock(false,"12205", "Nur Sari", "Description 4", 25.00m, 2, 50.00m, "D4", "R4"),
        new Stock(false,"12898", "Jose Hernandez", "Description 5", 30.00m, 4, 120.00m, "D5", "R5"),
        new Stock(false,"12130", "Kenji Sato", "Description 6", 35.00m, 6, 210.00m, "D6", "R6"),

    }.AsQueryable();

  
    // Define your Stock class here
    record Stock(bool message, string StockCode, string SKU, string Description, decimal Price, int QTY, decimal Total, string D, string R);
}

## 🤔 Expected Behavior

On click on row i should get the data on console by the help of "HandleRowFocus" method which fires on "OnRowFocus" 

## 😯 Current Behavior

It shows this error 
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS1503	Argument 2: cannot convert from 'method group' to 'Microsoft.AspNetCore.Components.EventCallback'	BlazorApp3	C:\Users\hp\Downloads\Telegram Desktop\BlazorApp3\BlazorApp3\BlazorApp3\Dummy\Component1.razor	4	

## 💁 Possible Solution

For exapmle if i click on first row i should get the data of first row only in console

## 🌍 Your Environment

* Device :- windows 11
* Browser :-chrome
* .NET :-blazor 8.0

**Comment by vnbaaij** [comment]
This is not an issue with the grid. Going by the error, your method call is not right.

**Comment by vnbaaij** [comment]
See the razor source at https://www.fluentui-blazor.net/DataGrid#templatecolumns2 for an example.
