### ISSUE TITLE
fix: [Async Method name is not async] in [FocusAsync]

### ISSUE THREAD

**Issue by darcome** [microsoft/fluentui-blazor#1569]
# 🐛 Bug Report

As you can see from the following screenshot, the FocusAsync method is not async because it does not return a Task

![image](https://github.com/microsoft/fluentui-blazor/assets/18150093/b86082d0-8be0-4edb-9977-fdf3e3bd9ee9)

## 🤔 Expected Behavior

In my opinion it should return a Task if needed, otherwise the Async postfix should be removed because it is misleading.

## 😯 Current Behavior

Since the method name ends in Async I have tried to await it and marked the method as async but the compiler issues an error.

## 🌍 Your Environment

* OS & Device: Windows 11 Home
* Browser Edge
* .NET and FAST Version 8.0.2 and 4.4.1

**Comment by vnbaaij** [comment]
This is know and on the list already.

As noted in the source code:     [SuppressMessage("Style", "VSTHRD200:Use `Async` suffix for async methods", Justification = "#vNext: To update in the next version")]
