### ISSUE TITLE
fix: firefox word-wrap in FluentTooltip

### ISSUE THREAD

**Issue by MxNbrt** [microsoft/fluentui-blazor#1572]
# 🐛 Bug Report

When using the FluentTooltip with a long text, the text does not wrap in firefox.

## 💻 Repro or Code Sample

```
@page "/"
@rendermode InteractiveServer
@using Microsoft.FluentUI.AspNetCore.Components

<div style="display: flex">
    <FluentInputLabel Label="my custom label" Required />
    <FluentIcon Id="infoIcon" Value="@(new Icons.Regular.Size16.Info())" Style="margin-left: 5px; margin-bottom: 4px;" />
    <FluentTooltip Anchor="infoIcon" Position="TooltipPosition.Right">
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    </FluentTooltip>
</div>
```

## 🤔 Expected Behavior

In Chrome, the tooltip wraps at 500px:
![image](https://github.com/microsoft/fluentui-blazor/assets/21066449/585364dc-2b33-420b-ba74-44eca946db74)

## 😯 Current Behavior

In Firefox, it does not wrap:
![image](https://github.com/microsoft/fluentui-blazor/assets/21066449/eff959db-6cf0-4a4c-8372-5a793850c129)

## 💁 Possible Solution

I can't tell what the real problem here is. Maybe you can ;)

## 🔦 Context

The issue is that firefox does not recognize "text-wrap: wrap;" as a valid value even though this is an allowed value in the docs https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap

![image](https://github.com/microsoft/fluentui-blazor/assets/21066449/f34c73b1-02c2-4e8a-a5c6-98f5588cc81c)

## 🌍 Your Environment

* OS & Device:  Windows on PC
* Browser: Mozilla FireFox, latest version
* .NET 8 with fluentui-blazor 4.4.1

**Comment by todarko** [comment]
Found a similar issue with the Data Grid in the **Project Templates** provided with the project. For a long text cell it no longer shortens with an ellipsis (...), it displays each rows columns as individual rows. 

![image](https://github.com/microsoft/fluentui-blazor/assets/41561202/de519006-faca-47d4-b38e-e78eb726b096)

Fix was, created a new Blazor server app and manually set up FluentUI for the project and everything worked as expected.

**Comment by vnbaaij** [comment]
For the Tooltip, it works with the latest Firefox Developer Edition (124b4):
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/6bf54018-02a8-4817-b34b-3822e466b1af)

@todarko please create a new issue with minimal working reproduction code. We can't debug/troubleshoot based of an image...
