### ISSUE TITLE
feat: 🔍 Add Search bar to Docs site

### ISSUE THREAD

**Issue by Hona** [microsoft/fluentui-blazor#1578]
# 🙋 Feature Request

> [!NOTE]  
> I am happy to implement MVP solution but want sign off & a point in the right direction first as a first contribution :)

There are a lot of component pages & articles in the docs site & it is sometimes hard to jump to the correct component.
A search bar/button at the top would assist greatly

![image](https://github.com/microsoft/fluentui-blazor/assets/10430890/01b22d99-30e2-47e8-a2d3-8d1c08fc91e6)
**Figure: Great spot for a search button**

## 🤔 Expected Behavior

MVP: Search Nav Menu links
Non-MVP: Search page content as well

## 😯 Current Behavior

No search ability, beyond control + f, but sometimes menus are collapsed :(

## 💁 Possible Solution

MVP: Some injected menu, & string search the entries
Non-MVP: More thought to be had, do we use a 3rd party tool?

## 🔦 Context

As a developer working with Fluent UI Blazor
I want to navigate the docs site quickly
So that I can develop my solutions

## 💻 Examples

![image](https://github.com/microsoft/fluentui-blazor/assets/10430890/19f3c0a7-7190-45a8-8caa-1cbdd2379546)
Figure: https://mudblazor.com/

![image](https://github.com/microsoft/fluentui-blazor/assets/10430890/0d8f0019-3add-46ea-b05f-7b4a70de26a5)
Figure: https://antblazor.com/

**Comment by pk9r327** [comment]
I like this

**Comment by vnbaaij** [comment]
Hi Luke,

Would be GREAT if you can contribute this! Think what you described as MVP is a very good starting point and would be a really usefull addition to the site.
Looking forward to your PR!
