### ISSUE TITLE
fix: When clicking anywhere on the datagrid, all content within the datagrid disappears, leaving only the border visible.

### ISSUE THREAD

**Issue by liubin3071** [microsoft/fluentui-blazor#1581]
# 🐛 Bug Report

## 💻 Repro or Code Sample
https://github.com/microsoft/fluentui-blazor/issues/1565#issuecomment-1964721858
```
public class NoneComponent : ComponentBase
{
    [Parameter] public RenderFragment ChildContent { get; set; }

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.AddContent(0, ChildContent);
    }
}
```

```
<FluentDataGrid TGridItem="Person" ItemsProvider="ItemsProvider2">
    <NoneComponent>
        <PropertyColumn TGridItem="Person" TProp="string" Property="@(c => c.Name)"></PropertyColumn>
    </NoneComponent>
</FluentDataGrid>
```

I have done more testing. As per the above code, everything works fine when starting the project with app.MapRazorComponents<App>().AddInteractiveServerRenderMode();. However, when starting the project with _Host.cshtml, a bug occurs."

## 🔦 Context
.net8.0  version: 4.4.1

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
You are still creating your own component to use in the DataGrid. That is absolutely fine, but we just can't support you with that.
Take a look at the DatGrid source to see how PropertyColumn and TemplateColumn have been defined. You will need to take that as a guidance (ie inherit from ColumnBase).
