### ISSUE TITLE
feat: Make FluentSearch allow Generic Type arguments

### ISSUE THREAD

**Issue by Hona** [microsoft/fluentui-blazor#1585]
At the moment the fluent search box only allows string.

It would be nice if we could provide a generic value & customise display/search field.

Unsure if this goes against the library's philosophy.

**Comment by vnbaaij** [comment]
Not sure how a user would then input the generic info to search on. Do you have an example to illustrate the issue you would solve with this?

**Comment by Hona** [comment]
Honestly - it seems to be the FluentAutocomplete covers this behaviour. But I also then feel that FluentSearch is not needed because of this. What is the main difference?

**Comment by vnbaaij** [comment]
Fluent Search is just a simple wrapper of the same-named web component that does not offer the capabilities of the Autocomplete (which is native to the Blazor library).

Closing this issue then.
