### ISSUE TITLE
fix: page background colour not changing

### ISSUE THREAD

**Issue by lettuceDestroyer** [microsoft/fluentui-blazor#1589]
# 🐛 Bug Report

## 💻 Repro or Code Sample

[Repo](https://github.com/lettuceDestroyer/fluentui_app) with example project

## 🤔 Expected Behavior

When I change the browser theme from light to dark, the text colour changes to white and the background gets dark.

## 😯 Current Behavior

When I change the browser theme from light to dark, the text colour changes to white but the background stays white. This
makes it hard to read the text.

light mode:
![image](https://github.com/microsoft/fluentui-blazor/assets/110594766/3d7237be-6d8e-4062-bf0c-e0040ebe55a3)

dark mode:
![image](https://github.com/microsoft/fluentui-blazor/assets/110594766/7403ad26-31d7-418e-940b-ec356af3f9ba)

## 🌍 Your Environment

* OS & Device: Windows 10 Enterprise 22H2 on Dell Lattitude
* Browser: Microsoft Edge
* .NET V8.0 and Microsoft.FluentUI.AspNetCore V4.4.1

**Comment by vnbaaij** [comment]
You'll have to implement some code to make the theme swithching work. See the demo site source (part of the repo) and the information in https://www.fluentui-blazor.net/DesignTheme

**Comment by lettuceDestroyer** [comment]
@vnbaaij  I followed the instructions but the background is still white. Do you think you could have a look at my repo?

**Comment by vnbaaij** [comment]
Sorry, I don't have time to do that. I would recomment to watch out .NET Conf talk and take a look at the source we showed there. 
- Link to video: https://youtu.be/a0xOqNemRoY
- Source used: https://github.com/dvoituron/dotnetconf-2023-fluentui-blazor?tab=readme-ov-file#8-add-themes-colors-dark-and-light

**Comment by lettuceDestroyer** [comment]
@vnbaaij I was able to solve the problem, thank you 😁
