### ISSUE TITLE
FluentInput manual upload fails with following error on page load

### ISSUE THREAD

**Issue by Nehakrg** [microsoft/fluentui-blazor#1590]
# 🐛 Bug Report

<html>
<body>
<h1 style="color: var(--color-heading-main); margin: 15px 0px; font-family: &quot;Segoe UI&quot;, Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An unhandled exception occurred while processing the request.</h1><div class="titleerror" style="padding: 3px 3px 6px; display: block; font-size: 1.5em; font-weight: 100; color: rgb(34, 34, 34); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.</div><p class="location" style="margin: 3px 0px 10px 30px; color: rgb(34, 34, 34); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, Helvetica, sans-serif; font-size: 13.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(long asyncHandle, string identifier, string argsJson, JSCallResultType resultType, long targetInstanceId)</p><ul id="header" style="font-size: 18px; padding: 15px 0px; border-top: 1px solid var(--color-border); border-bottom: 1px solid var(--color-border); margin-bottom: 0px; color: rgb(34, 34, 34); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li id="stack" tabindex="1" class="selected" style="display: inline; margin: 5px; padding: 5px; color: var(--color-tab-selected); cursor: pointer; background: var(--color-tab-selected-background);">Stack<span> </span></li><li id="query" tabindex="2" style="display: inline; margin: 5px; padding: 5px; color: var(--color-tab-link); cursor: pointer;">Query<span> </span></li><li id="cookies" tabindex="3" style="display: inline; margin: 5px; padding: 5px; color: var(--color-tab-link); cursor: pointer;">Cookies<span> </span></li><li id="headers" tabindex="4" style="display: inline; margin: 5px; padding: 5px; color: var(--color-tab-link); cursor: pointer;">Headers<span> </span></li><li id="routing" tabindex="5" style="display: inline; margin: 5px; padding: 5px; color: var(--color-tab-link); cursor: pointer;">Routing</li></ul><div id="stackpage" class="page" style="color: rgb(34, 34, 34); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, Helvetica, sans-serif; font-size: 13.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><ul style="list-style: none; padding-left: 0px; margin: 0px;"><li><h2 style="margin: 10px 5px 0px 0px; padding: 5px; border-bottom: 1px solid var(--color-border);">InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.</h2><ul style="list-style: none; padding-left: 0px; margin: 0px;"><li class="frame" id="frame1" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(long asyncHandle, string identifier, string argsJson, JSCallResultType resultType, long targetInstanceId)</h3></li><li class="frame" id="frame2" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.JSInterop.JSRuntime.InvokeAsync&lt;TValue&gt;(long targetInstanceId, string identifier, CancellationToken cancellationToken, object[] args)</h3></li><li class="frame" id="frame3" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.JSInterop.JSRuntime.InvokeAsync&lt;TValue&gt;(long targetInstanceId, string identifier, object[] args)</h3></li><li class="frame" id="frame4" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">System.Threading.Tasks.ValueTask&lt;TResult&gt;.get_Result()</h3></li><li class="frame" id="frame5" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.FluentUI.AspNetCore.Components.FluentInputFile.OnInitializedAsync() in<span> </span><code title="/_/src/Core/Components/InputFile/FluentInputFile.razor.cs" style="font-family: Consolas, &quot;Courier New&quot;, courier, monospace; font-weight: bold;">FluentInputFile.razor.cs</code></h3></li><li class="frame" id="frame6" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()</h3></li><li class="frame" id="frame7" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)</h3></li><li class="frame" id="frame8" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)</h3></li><li class="frame" id="frame9" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasksWithErrorHandling(Task task, ComponentState owningComponentState)</h3></li><li class="frame" id="frame10" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)</h3></li><li class="frame" id="frame11" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)</h3></li><li class="frame" id="frame12" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(ref DiffContext diffContext, int frameIndex)</h3></li><li class="frame" id="frame13" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(ref DiffContext diffContext, int frameIndex)</h3></li><li class="frame" id="frame14" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(ref DiffContext diffContext, int newFrameIndex)</h3></li><li class="frame" id="frame15" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(ref DiffContext diffContext, int oldStartIndex, int oldEndIndexExcl, int newStartIndex, int newEndIndexExcl)</h3></li><li class="frame" id="frame16" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, int componentId, ArrayRange&lt;RenderTreeFrame&gt; oldTree, ArrayRange&lt;RenderTreeFrame&gt; newTree)</h3></li><li class="frame" id="frame17" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, out Exception renderFragmentException)</h3></li><li class="frame" id="frame18" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)</h3></li><li class="frame" id="frame19" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()</h3></li><li class="frame" id="frame20" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)</h3></li><li class="frame" id="frame21" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()</h3></li><li class="frame" id="frame22" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()</h3></li><li class="frame" id="frame23" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(int componentId, RenderFragment renderFragment)</h3></li><li class="frame" id="frame24" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)</h3></li><li class="frame" id="frame25" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()</h3></li><li class="frame" id="frame26" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()</h3></li><li class="frame" id="frame27" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()</h3></li><li class="frame" id="frame28" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)</h3></li><li class="frame" id="frame29" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)</h3></li><li class="frame" id="frame30" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasksWithErrorHandling(Task task, ComponentState owningComponentState)</h3></li><li class="frame" id="frame31" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)</h3></li><li class="frame" id="frame32" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)</h3></li><li class="frame" id="frame33" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(int componentId, ParameterView initialParameters)</h3></li><li class="frame" id="frame34" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)</h3></li><li class="frame" id="frame35" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(Type componentType, ParameterView initialParameters)</h3></li><li class="frame" id="frame36" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, bool waitForQuiescence)</h3></li><li class="frame" id="frame37" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">System.Threading.Tasks.ValueTask&lt;TResult&gt;.get_Result()</h3></li><li class="frame" id="frame38" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)</h3></li><li class="frame" id="frame39" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)</h3></li><li class="frame" id="frame40" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+&lt;&gt;c+&lt;&lt;InvokeAsync&gt;b__10_0&gt;d.MoveNext()</h3></li><li class="frame" id="frame41" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)</h3></li><li class="frame" id="frame42" style="padding: 0px; margin: 0px 0px 0px 30px;"><h3 style="color: var(--color-heading-stacktrace); margin: 0px; font-weight: normal; padding: 2px;">Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)</h3></li></ul></li><li><br><div class="rawExceptionBlock" style="font-size: 1.2em; border-top: 1px solid var(--color-border); border-bottom: 1px solid var(--color-border);"><button class="showRawException" data-exceptiondetailid="exceptionDetail1" style="display: inline-block; color: var(--color-link); background: transparent; font: inherit; border: 0px; padding: 10px 0px; cursor: pointer;">Show raw exception details</button><div id="exceptionDetail1" class="rawExceptionDetails"><pre class="rawExceptionStackTrace">System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.FluentUI.AspNetCore.Components.FluentInputFile.OnInitializedAsync() in /_/src/Core/Components/InputFile/FluentInputFile.razor.cs:line 193
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasksWithErrorHandling(Task task, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext&amp; diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext&amp; diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext&amp; diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext&amp; diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception&amp; renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasksWithErrorHandling(Task task, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(Type componentType, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.&lt;&gt;c.&lt;&lt;InvokeAsync&gt;b__10_0&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)</pre></div></div></li></ul></div><div id="querypage" class="page" style="color: rgb(34, 34, 34); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, Helvetica, sans-serif; font-size: 13.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p>No query string data.</p></div><div id="cookiespage" class="page" style="color: rgb(34, 34, 34); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, Helvetica, sans-serif; font-size: 13.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Variable | Value
-- | --
.AspNetCore.Antiforgery.NA68t7evpik | CfDJ8FUXtKsCij1Hj9Ih_NWrXJ0RzlhcOxcYKWa9oZELilBfZmiMbG1BKHXRkeyjcY5lOo69RVFLgEt-APjdb9i3jSdTUN-3NKjcOx3htEbdCHjQ8X9MUhUhGWBFbd8bIEWB4K0MN43KA9n0b2UtbnIZHhE

<h2 style="margin: 10px 5px 0px 0px; padding: 5px; border-bottom: 1px solid var(--color-border);">Route Values</h2><p>No route values.</p></div>
</body>
</html>
## 💻 Repro or Code Sample
[Repo](https://github.com/Nehakrg/FluentUI)

Links for Default Upload and Manual Upload have been incorporated into the navbar. The Default Upload functionality is operating as expected, however, the Manual Upload is encountering issues due to a JavaScript interop failure.

## 🤔 Expected Behavior

Page should load 

## 😯 Current Behavior

Manual Upload is encountering issues due to a JavaScript interop failur

## 🌍 Your Environment

FluentUI 4.4.1
Windows 10
.Net8 Blazor

**Comment by vnbaaij** [comment]
This is not a component error. You are trying to run a JSinterop method before the component is actually rendered. You can't do that in a Blazor Server app. You need to use `OnAfterRenderAsync` to call the interop
