### ISSUE TITLE
Menu Button: Appearance Parameter

### ISSUE THREAD

**Issue by Rocky-25** [microsoft/fluentui-blazor#1593]
# 🙋 Feature Request

Can Menu button be updated to allow Appearance to be passed so it's not always accent?

**Comment by dvoituron** [comment]
There are several **Appearance** available: https://fluentui-blazor.net/button
The menu is linked to the button using `Anchor`.

```xml
    <FluentButton>Button</FluentButton>
    <FluentButton Appearance="Appearance.Accent">Accent</FluentButton>
    <FluentButton Appearance="Appearance.Lightweight">Lightweight</FluentButton>
    <FluentButton Appearance="Appearance.Outline">Outline</FluentButton>
    <FluentButton Appearance="Appearance.Stealth">Stealth</FluentButton>
    <FluentButton BackgroundColor="var(--highlight-bg)" Color="var(--info)">Colored</FluentButton>
    <FluentButton Loading="@loading" OnClick="@StartLoadingAsync" Appearance="Appearance.Accent">Loading</FluentButton>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/d91c6512-7a23-4e5e-8c18-007556c6f98f)

**Comment by Rocky-25** [comment]
Hi,

Yes thanks I know I can restyle a button, but your MenuButton component doesn't allow this for some reason? Why can't the appearance be passed here too?

`
<div class="fluent-menubutton-container">
    <FluentButton @ref="Button" **Appearance="Appearance.Accent"** Style=@ButtonStyle aria-haspopup="true" aria-expanded="@_visible" @onclick=ToggleMenu @onkeydown=OnKeyDown>
        @Text
        <FluentIcon Value="@(new CoreIcons.Regular.Size24.ChevronDown())" Slot="end" Color="@Color.Fill" />
    </FluentButton>
    <FluentMenu @ref="Menu" aria-labelledby="button" Style="@MenuStyle" @bind-Open=@_visible @onmenuchange=OnMenuChangeAsync>
        @foreach (KeyValuePair<string, string> item in Items)
        {
            <FluentMenuItem Id="@item.Key">@item.Value</FluentMenuItem>
        }
    </FluentMenu>
</div>
`

**Comment by dvoituron** [comment]
Oh. I hadn't understood that. Indeed it could be interesting
