### ISSUE TITLE
Menu Button clicking away once menu open

### ISSUE THREAD

**Issue by Rocky-25** [microsoft/fluentui-blazor#1594]
# 🐛 Bug Report

When clicking on a menu button the menu shows, however when clicking anywhere else on the page the menu button stays visible. Shouldn't it close in a similar way a combo box does?

**Comment by dvoituron** [comment]
This is already the case. If you go to https://fluentui-blazor.net/menu and click on the "Open menu" button, it closes when you click outside the menu (on the page). The only case that wasn't handled until this morning is Right-Click, and this will be the case in the next version: #1574

**Comment by Rocky-25** [comment]
Hi, 
I was talking about MenuButton not Menu. This doesn't close once opened.
https://fluentui-blazor.net/MenuButton

**Comment by vnbaaij** [comment]
Hi, 

I'll create a PR which adds an Overlay (Fullscreen, Transparant) to the MenuButton. That way, once the menu is shown, you can click outside of it to close it:

![issue-#1594](https://github.com/microsoft/fluentui-blazor/assets/1761079/24496844-9370-4984-b17b-db3af7342eaf)
