### ISSUE TITLE
fix: Invalid inline style in FluentButton

### ISSUE THREAD

**Issue by tlmii** [microsoft/fluentui-blazor#1598]
# 🐛 Bug Report

FluentButton has some logic that outputs a custom style block when either BackgroundColor or Color are set directly on the button. This block can generate invalid styles though:

https://github.com/microsoft/fluentui-blazor/blob/bb9b53df10b84f97a0653b4b0d7e92cb7853001c/src/Core/Components/Button/FluentButton.razor.cs#L191-L200

If _only_ BackgroundColor is specified, then line 194 is just `color: ;` which is not valid. If _only_ Color is specified, then line 193 is just `background: padding-box linear-gradient(, ), border-box ;` which is also not valid.

## 💻 Repro or Code Sample

Any FluentButton with just one of those two parameters specified will exhibit this issue. 

## 🤔 Expected Behavior

The style block is properly formed.

## 😯 Current Behavior

The style block is not properly formed and errors are present in DevTools.

## 🔦 Context

This does not seem to cause any actual rendering/runtime issues at all. So its not critical. But we should make the style block properly formed when we have a chance.

## 🌍 Your Environment

Microsoft.FluentUI.AspNetCore.Components 4.4.2-preview.24048.2 (though the link to the code above is from dev branch)
Edge 122
Win 11

**Comment by dvoituron** [comment]
That's correct, we have now a new helper class to do that: `InlineStyleBuilder`

**Comment by dvoituron** [comment]
Fixed for the next release, with this PR #1603
