### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by ianclough** [microsoft/fluentui-blazor#1610]
# 🐛 Bug Report

Module javascript fails to load when FluentUI project is packaged in a solution

## 💻 Repro or Code Sample

I created a new FluentUI project and this works fine as a standalone project. When I include this project within a solution some FluentUI aspects fail to load.

## 🤔 Expected Behavior

A FluentUI project should continue to load correctly when included within a solution.

## 😯 Current Behavior

An exception is thrown when Fluent components requires dynamically load java script modules.
Failed to fetch dynamically imported module: http://localhost:5000/_content/Microsoft.FluentUI.AspNetCore.Components/Components/Accessibility/FluentKeyCode.razor.js

## 🔦 Context

My solution includes a FluentUI project and several back end projects

## 🌍 Your Environment

* OS & Device: [Windows] on [Mac with Parallels VM]
* Browser [Microsoft Edge]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Hi,

We really need code, project, solution or repository with which we ca nreproduce the issue. We do not have time to rebuild/recreate issues. The volume is too high for that. Please help us to help you.

**Comment by ianclough** [comment]
Unable to reproduce with a minimal solution. I re-created my original solution with the same projects and the issue has disappeared. Annoyingly I can't determine what was breaking this but happy to close this issue.
