### ISSUE TITLE
New webassembly project only creates one folder

### ISSUE THREAD

**Issue by Awide** [microsoft/fluentui-blazor#1612]
Newest Blazor webassembly projects create two folders, one for the server and a project.client. Using fluentui templates the WASM only has one which is not up to the new standard.

**Comment by vnbaaij** [comment]
Hi,

No, they don't. The Web App template creates two projects. One for Server and one for Client. WebAssembly is still one project.

PS, Our templates are 100% copies of the standard Blazor templates...

**Comment by Awide** [comment]
It may have been a copy of the old template but not the current ones. Please check,  there is no index.html.
I have made a new blazor project and tried the manual installation, though it is not working, and the manual installation guide is asking me to edit files that are not in the latest blazor projects either.

**Comment by vnbaaij** [comment]
I'm pretty sure I've copied the current one's...

You have perhaps started from the worng template. For .NET 8 you choose eiter 'Blazor Web App' or 'Blazor WebAssembly Standalone App':
<img width="491" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/0d865c70-e24f-45f8-a9ac-023adbd5921b">
Thosare the **ONLY** .NET 8 templates that are available.

If you have insalled our template packe, you will also find Fluent versions of those two templates which, again, are 100% copies of the source coming from the AspNetCore repo.

**Comment by Awide** [comment]
I used CLI to start a new webassembly project.
`dotnet new blazor --interactivity WebAssembly --auth Individual`

I immediately get two folders, project and project.Client. If I use your template I only get one folder.

After going through manual installation I get the following errors.
`/sageapp/sageapp.Client/Program.cs(10,18): error CS1061: 'IServiceCollection' does not contain a definition for 'AddFluentUIComponents' and no accessible extension method 'AddFluentUIComponents' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) [/sageapp/sageapp.Client/sageapp.Client.csproj]`

I realize I may be doing something wrong but maybe you are not getting the newest wasm template? Anyway, what could I do to not get errors related to IServiceCollection?

Thank you very much for all help! Really want to try the latest fluentui but I keep running into these core issues. :(

**Comment by vnbaaij** [comment]
That is not the right template. You need to use `blazorwasm`. 

Just install our template package and use `fluentblazorwasm` an everything will be already set up for you! See https://www.nuget.org/packages/Microsoft.FluentUI.AspNetCore.Templates#readme-body-tab

Stop saying I am using the wrong template . You are! (😉)

**Comment by Awide** [comment]
> That is not the right template. You need to use `blazorwasm`.
> 
> Just install our template package and use `fluentblazorwasm` an everything will be already set up for you! See https://www.nuget.org/packages/Microsoft.FluentUI.AspNetCore.Templates#readme-body-tab
> 
> Stop saying I am using the wrong template . You are! (😉)

You are right! I was using the wrong template. Is it possible to start a fluent template that has the built-in individual authentication and authorization system of Microsoft?

**Comment by vnbaaij** [comment]
Yes. All the same parameters as the standard templates are supported (as they are 100% copies)
