### ISSUE TITLE
fix: browser autocomplete in FluentCombobox

### ISSUE THREAD

**Issue by JopMaarse** [microsoft/fluentui-blazor#1618]
# 🐛 Bug Report

Currently in FluentCombobox you can define autocomplete behaviour using ComboboxAutocomplete.Both, ComboboxAutocomplete.Inline or ComboboxAutocomplete.List. However browser [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) cannot be customised like you can with a FluentTextField.
Normally autocomplete doesn't show up for comboboxes, however when you bind the FluentCombobox to a property of an object (and maybe in other situations) the browser autocomplete kicks in.

## 💻 Repro or Code Sample

```
@page "/"

<PageTitle>Home</PageTitle>

<EditForm Model=DataObject OnSubmit=Submit FormName="Form">
    <FluentCombobox Id="combobox"
                    Label="Value:"
                    Items=@Content
                    @bind-Value=DataObject.Value
                    Autocomplete=ComboboxAutocomplete.Both
                    TOption=string
                    Required=true />
    <FluentButton Type=ButtonType.Submit>Submit</FluentButton>
</EditForm>

@code{
    record Data
    {
        public string? Value { get; set; }
    }        

    [SupplyParameterFromForm]
    private Data DataObject { get; set; } = new();

    public List<string> Content { get; set; } = ["Value 1", "Value 2", "Value 3"];

    private void Submit() { }
}
```

## 🤔 Expected Behavior

Either no autocomplete, or the option to explicitly set the autocomplete field, like on a FluentTextField.

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/9058620/5c81215b-56a5-4095-85cb-11b1899318f0)
This is the generated input element of the combobox. As you can see it has no autocomplete field, so the browser decides.
```
<input aria-haspopup="listbox" class="selected-value" part="selected-value" role="combobox" type="text" aria-controls="" aria-disabled="false" aria-expanded="false" aria-label="Value:">
```

## 💁 Possible Solution

Add `autocomplete="off"` to the generated `<input>` or allow it to be set using a new property on FluentCombobox.

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Google Chrome
* .NET and Fluent UI Blazor library Version: 8.0.1 and 4.4.2-preview.24058.32

**Comment by vnbaaij** [comment]
Will be fixed with PR mentioned above.
