### ISSUE TITLE
rfc: add Filtered Indicator to FluentDataGrid in ColumnOptions

### ISSUE THREAD

**Issue by NickHirras** [microsoft/fluentui-blazor#1620]
# 💬 RFC

I'm using the ColumnOptions render fragment in FluentDataGrid to give my users a filter control on columns. There is a usability concern, that it is not easy to identify which (if any) columns have filtering applied. 

I would like to be able to pass-in some parameter (maybe a boolean such as `<ColumnOptions Filtered="true">`.  Depending on the value of Filtered, it would render the icon on the filter button differently.  

I'm looking in `ColumnBase.razor` ~ lines 23 and 56. Instead of just rendering a single possible FluentIcon, I would prefer an optional difference based on the new Filtered boolean:

existing code: 

```
<FluentButton Appearance="Appearance.Stealth" class="col-options-button" @onclick="@(() => Grid.ShowColumnOptionsAsync(this))" aria-label="Filter this column">
    <FluentIcon Value="@(new CoreIcons.Regular.Size24.Filter())"/>
</FluentButton>
```

would change to:

```
<FluentButton Appearance="Appearance.Stealth" class="col-options-button" @onclick="@(() => Grid.ShowColumnOptionsAsync(this))" aria-label="Filter this column">

    @if(Filtered) 
    {
        <FluentIcon Value="@(new CoreIcons.Regular.Size24.Filter())"/>
    }
    else
    { 
        <FluentIcon Value="@(new CoreIcons.Regular.Size24.Filter())" Color="@Color.Disabled" />
    }
</FluentButton>

```

Or maybe Color.Neutral instead of Disabled.  

In the end, if the user has a screen with several filterable columns, I'd like to be able to visually indicate which ones have a filter value applied, and which ones have an empty filter. 

## 🔦 Context

I would like a clear visual indication that filterable columns have a filter value applied, or not.

## 💻 Examples

For example, say I have this screen with 5 columns.  Out of the 5 filterable columns, only 2 have any values applied to the filter, the Client Name, and the Tags columns.  

Currently, all columns show the same color Filter icon, and there's no easy way to see which columns are affected the results returned.  

![image](https://github.com/microsoft/fluentui-blazor/assets/3911628/ef06f7a8-40d6-482f-8abb-de291d15f7e2)

What I would prefer, in this example, it is clearly indicated which fields are affecting the results and which ones are not.

![image](https://github.com/microsoft/fluentui-blazor/assets/3911628/e04d0980-c9f2-4588-aee9-f6f1658432ee)

**Comment by vnbaaij** [comment]
I think this is a good idea. But instead of working with different icon colors I think adding a small badge is perhaps a better solution. 
Going on your second screenshot, it gives me the impression that you can not apply filtering to the columns that have the gray color. They look disabled.

Having them all the same but applying an accent like a badge seems more clear to me. What do you think?

We can probably use our existing badge component for this.

Would be great if you can work on this!

**Comment by NickHirras** [comment]
I like that idea.  I'll start working on it. I'm thinking I'll need to replace the ColumnOptions, it's currently a RenderFragment, I think I'll need to make a ColumnOptions component to contain the `Filtered` parameter?

**Comment by NickHirras** [comment]
Looking for other examples of this type of UI, there's a demo here:
https://www.ag-grid.com/javascript-data-grid/filtering/

In this component set, when there is no filter applied the Filter button is only visible on hover. When there is a filter applied, the button stays visible.

**Comment by vnbaaij** [comment]
Closing this one in favor of the PR. We can discus further there.
