### ISSUE TITLE
fix: Toast does not show after NavigationManager redirect

### ISSUE THREAD

**Issue by knightmeister** [microsoft/fluentui-blazor#1622]
# 🐛 Bug Report

I am moving my Blazor app from using Bootstrap services (via `Blazor.Bootstrap`) to FluentUI Blazor. The porting process was fairly trivial, however I can't get one of my use cases to work.

My entity new/edit page performs a redirection to itself when creating a new entity. The following routes are defined on the page:

```
@page "/items/{ItemId}"
@page "/items/new"
```

EditForm save method:

```
...
            if (itemCreated)        // If we created an item, redirect the URI
            {
                _navigationManager.NavigateTo($"/items/{createdItemId}");
                Model.Id = createdItemId;
                Title = string.Format(WebAppResources.NewEditPageTitle, Fields.Edit, Fields.Item);
            }

            _toastService.ShowSuccess(string.Format(WebAppResources.Message_EntityUpdated_Title, Model.Title, (itemCreated ? Fields.Created: Fields.Updated).ToLower()));
...
```

When an item is updated, the success is shown as I would expect. If an item is created, the success toast does not show. Even introducing an artificial delay (via `Task.Delay`) before `ShowSuccess` doesn't work.

I have `<FluentToastProvider />` in my `MainLayout.razor` file.

## 💻 Repro or Code Sample

See above.

## 🤔 Expected Behavior

Toast should show after navigation manager navigates the page.

## 😯 Current Behavior

When editing an item, the toast is shown as expected.
When creating an item, the toast **is not** shown. I expect this has something to do with the navigation manager moving the page.

## 🔦 Context

I'm trying to display a notification to the user when they create an item using the toast service which is consistent with the rest of my application.

## 🌍 Your Environment

Blazor Server on .NET 8. Browser = Edge current. Library version = 4.4.1.

**Comment by vnbaaij** [comment]
Hi,

In order to investigate this, please supply us with a working reproduction. Can be a ready-to-run copy/paste or a repository. 

The repro code you posted is insufficient as we would need to create a model, form, etc. We do not have capicity for that. Help us to help you. Thanks.

**Comment by dvoituron** [comment]
Have you tried setting the `RemoveToastsOnNavigation` property to false?
If not, every time you navigate to a new page, the toast disappears.

And maybe you need to display the Toast before navigating to another page.

**Comment by knightmeister** [comment]
> Have you tried setting the `RemoveToastsOnNavigation` property to false? If not, every time you navigate to a new page, the toast disappears.
Thanks, this was exactly what it was. Sorry guys, I did check the docs before I raised the issue, clearly not well enough.

Thanks @dvoituron!

**Comment by Anton4111987** [comment]
For some reason, it still does not work to display notifications when the current page is reloaded! 
Could you find a mistake for me?

**Comment by Anton4111987** [comment]
@page "/Confidant"

 _listConfidants.Delete(confidant);
 toastService.ShowInfo("Удалено доверенное лицо {" + confidant.LastName + " " + confidant.Name + " " + confidant.SurName + "}");
 navigationManager.NavigateTo("/Confidant", true);

**Comment by Anton4111987** [comment]
@inherits LayoutComponentBase
@using Blazored.Toast.Configuration


<BlazoredToasts Position="Blazored.Toast.Configuration.ToastPosition.TopRight"
                RemoveToastsOnNavigation=false
                Timeout="10"
                IconType="Blazored.Toast.Configuration.IconType.FontAwesome"
                SuccessClass="success-toast-override"
                SuccessIcon="fa fa-thumbs-up"
                ErrorIcon="fa fa-bug"
                WarningIcon="fa fa-warning"
                InfoIcon="fa fa-info-circle">
</BlazoredToasts>

**Comment by Anton4111987** [comment]
<BlazoredToasts Position="Blazored.Toast.Configuration.ToastPosition.TopRight"
                RemoveToastsOnNavigation=false
                Timeout="10"
                IconType="Blazored.Toast.Configuration.IconType.FontAwesome"
                SuccessClass="success-toast-override"
                SuccessIcon="fa fa-thumbs-up"
                ErrorIcon="fa fa-bug"
                WarningIcon="fa fa-warning"
                InfoIcon="fa fa-info-circle">
</BlazoredToasts>

**Comment by Anton4111987** [comment]
RemoveToastsOnNavigation=false added to MainLayOut!

**Comment by Anton4111987** [comment]
`@page"/ Доверенное лицо"

_listConfidants.Delete(доверенное лицо);
toastService.ShowInfo("Удалено доверенное лицо {" + доверенное лицо.Фамилия + " " + доверенное лицо.Имя + " " + доверенное лицо.Фамилия + "}");
NavigationManager.NavigateTo("/Confidant", true);`
