### ISSUE TITLE
fix: Exception thrown when using MessageBox in DialogService on a published Blazor WebAssembly app

### ISSUE THREAD

**Issue by Vince640** [microsoft/fluentui-blazor#1626]
# 🐛 Bug Report

Maybe I'm doing something wrong, but when I try to call DialogService.ShowConfirmationAsync in a published Blazor app, I still get this exception:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type 'Microsoft.FluentUI.AspNetCore.Components.MessageBox' declares a parameter matching the name 'Content' that is not public. Parameters must be public.
System.InvalidOperationException: The type 'Microsoft.FluentUI.AspNetCore.Components.MessageBox' declares a parameter matching the name 'Content' that is not public. Parameters must be public.
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.WritersForType..ctor(Type )
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& , Object )
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object )
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView )
```
It works fine in debug mode tough.

## 💻 Repro or Code Sample

You can find a light code example on the following [GitHub repository](https://github.com/Vince640/FluentDialogProvider-PublishTrimmed-Example/blob/master/BlazorApp001/Pages/Home.razor) and a deployed application on [this Azure SWA](https://agreeable-ocean-0efd20f10-preview.centralus.4.azurestaticapps.net/).

## 🤔 Expected Behavior

Confirmation Dialog should be displayed without throwing error in production.

## 😯 Current Behavior

Confirmation Dialog throwing error in production.
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type 'Microsoft.FluentUI.AspNetCore.Components.MessageBox' declares a parameter matching the name 'Content' that is not public. Parameters must be public.
System.InvalidOperationException: The type 'Microsoft.FluentUI.AspNetCore.Components.MessageBox' declares a parameter matching the name 'Content' that is not public. Parameters must be public.
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.WritersForType..ctor(Type )
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& , Object )
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object )
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView )
```
![image](https://github.com/microsoft/fluentui-blazor/assets/77515765/0fe3c52f-6fb6-4d65-9c2f-ce3a35a57ca4)

## 🔦 Context

I created this publish profile:
![image](https://github.com/microsoft/fluentui-blazor/assets/77515765/a2040bea-a7ef-4913-8aeb-b2f63c50fb5b)
![image](https://github.com/microsoft/fluentui-blazor/assets/77515765/21f95edc-d23c-488a-bbdb-77acee3e8772)
![image](https://github.com/microsoft/fluentui-blazor/assets/77515765/9a32b7bd-7559-4cd2-9144-9642ebd2d6cb)

I tried these workarounds, but the issue persists:
In the csproj : `<ItemGroup> <TrimmerRootAssembly Include="Microsoft.FluentUI.AspNetCore.Components" /> </ItemGroup>`
Anywhere : `var temp1 = new MessageBox() { Content = new() { Message = "abc" } };`

I know it's a duplicate of #1255 and #1354 but the problem still seems to persist.

## 🌍 Your Environment

* Windows 11
* Google Chrome
* .NET 8.0.101
* Fluent UI Blazor library 4.4.1

**Comment by vnbaaij** [comment]
Take a look at our demo client and demo shared projects here in the repo. We have this configuration working for the demo site (WASM) on Azure Static Web Apps ourselves.
CLosing this as it is not actionable from our side.

**Comment by Vince640** [comment]
@Skintkingle the workaround is to add "<TrimmerRootAssembly Include="Microsoft.FluentUI.AspNetCore.Components" />" to your csproj. The issue I encountered was that despite cleaning, deleting bin/obj folders and regenerating the solution, my publication was still "overly" trimmed. I'm not sure why it wasn't taken into account on the first attempt.

**Comment by kowgli** [comment]
The workaround didn't work for me. What did is changing the publish configuration to use the debug build. It's a smallish internal use CRUD app, so I don't see any practical performance difference.

**Comment by martin-hirsch** [comment]
@kowgli, the workaround worked for me. Correct me if I'm wrong: Wasn't there a PR supposed to provide a fix? Unfortunately, I can't follow the tickets well enough to understand if the issue has been resolved.

**Comment by guimabdo** [comment]
This workaround works:
```
var temp1 = new MessageBox() { Content = new() { Message = null } };
```
But I guess that it should be placed in some place/method that will not be trimmed.

I think this should be fixed in the library, intializing Content in this line:
https://github.com/microsoft/fluentui-blazor/blob/312d11ec450e456e69daa2b8810c05d2f6a9519e/src/Core/Components/Dialog/FluentDialogProvider.razor.cs#L25

**Comment by vnbaaij** [comment]
> This workaround works:
> 
> ```
> var temp1 = new MessageBox() { Content = new() { Message = null } };
> ```
> 
> But I guess that it should be placed in some place/method that will not be trimmed.
> 
> I think this should be fixed in the library, intializing Content in this line:
> 
> https://github.com/microsoft/fluentui-blazor/blob/312d11ec450e456e69daa2b8810c05d2f6a9519e/src/Core/Components/Dialog/FluentDialogProvider.razor.cs#L25

Have you tried the `TrimmerRootAssembly` method mentioned in earlier comments?

**Comment by guimabdo** [comment]
> > This workaround works:
> > ```
> > var temp1 = new MessageBox() { Content = new() { Message = null } };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I guess that it should be placed in some place/method that will not be trimmed.
> > I think this should be fixed in the library, intializing Content in this line:
> > https://github.com/microsoft/fluentui-blazor/blob/312d11ec450e456e69daa2b8810c05d2f6a9519e/src/Core/Components/Dialog/FluentDialogProvider.razor.cs#L25
> 
> Have you tried the `TrimmerRootAssembly` method mentioned in earlier comments?

Yes, this works either. 

But I prefer the `new MessageBox` workaround, so the unreferenced parts of the assembly can be trimmed.
