### ISSUE TITLE
ImmediateDelay on FluentNumberField does not apply to changes made by arrow-up & arrow-down or step buttons.

### ISSUE THREAD

**Issue by simsan96** [microsoft/fluentui-blazor#1628]
# 🐛 Bug Report

ImmediateDelay on FluentNumberField does not apply to changes made by arrow-up & arrow-down or step buttons. 

## 💻 Repro or Code Sample

```
<FluentNumberField
    TValue="int"
    Value="_myValue"
    ValueChanged="newVal=> HandleValueChange(newVal)"
    Immediate="true"
    ImmediateDelay="500" />
```

## 🤔 Expected Behavior

When increasing / decreasing the value using arrow keys or steppers the ValueChanged callback should be debounced the same way it is if entered by typing the value.

## 😯 Current Behavior

The ValueChanged callback is invoked instantly and for every change without being debounced. Holding the arrow up key triggers HandleValueChange() multiple times a second.

## 💁 Possible Solution

Debounce stepper & arrow key events the same way number typing events.

## 🔦 Context

I'm currently using a FluentNumberField that in turn updates some state in a blazor server application. All other clients subscribe to said state, and re-renders when the value is changed by one client.

With this current behaviour this change event is triggered multiple times every second, thus triggered unnecessary re-renders.

## 🌍 Your Environment

Windows 11
Chrome
.NET and Fluent UI Blazor library Version 8.0.2

**Comment by vnbaaij** [comment]
I don't think we can intercept clicks on those buttons. They are handled by browser. Web components script just emits a change event, so then the click has already been 'processed'.

**Comment by vnbaaij** [comment]
Closing this as it is not actionable from our side.
