### ISSUE TITLE
fix: [Fluent Blazur Web App Template will not compile]  syntax error in [Weather.razor line 17]

### ISSUE THREAD

**Issue by wolfgangschneider** [microsoft/fluentui-blazor#1636]
# 🐛 Bug Report

Line 18
 ` <FluentDataGrid Id="weathergrid" Items="@forecasts"" GridTemplateColumns="1fr 1fr 1fr 2fr" TGridItem="WeatherForecast">`
  schould be
  `<FluentDataGrid Id="weathergrid" Items="@forecasts" GridTemplateColumns="1fr 1fr 1fr 2fr" TGridItem="WeatherForecast">`

Version
Microsoft.FluentUI.AspNetCore.Templates Version 4.4.1

**Comment by vnbaaij** [comment]
Reported and fixed already. Will be in 4.5.0

**Comment by kzu** [comment]
4.5 shipped a couple hours ago, but templates didn't: https://www.nuget.org/packages/Microsoft.FluentUI.AspNetCore.Templates

**Comment by vnbaaij** [comment]
Working on it... 😁
