### ISSUE TITLE
feat: Customize Search logic for Combobox

### ISSUE THREAD

**Issue by martinbu** [microsoft/fluentui-blazor#1639]
Something that would be really helpful is a `OnOptionsSearch ` callback for the FluentCombobox, as the FluentAutocomplete already has. Additionally, it would be great to ensure that always one valid value is selected. Therefore, that the last valid value is selected again if a search text is typed with zero search results after leaving the combobox focus.

But I am afraid that the logic from the FluentAutocomplete cannot be simply taken for the FluentCombobox because the web component itself is handling the filtering... When I debug the FluentCombobox, i can see that the `OnChangedHandlerAsync ` is called only when the final value is updated. Therefore, I think it is not that straightforward to add the filter logic inside the C# part of the component like in FluentAutocomplete...

**Comment by vnbaaij** [comment]
We are not going to implement that for the Combobox. It already has three different autocomplete settings which offer a firm of search capabilities

**Comment by martinbu** [comment]
My question here is why the Autocomplete component have the possibility to specify an OnOptionsSearch callback and the Combobox component does not? The Combobox default behaviour is not sufficient as it only search the items from the beginning which is a huge limitation for a search capability...

From my point of view, the Autocomplete and Combobox components are exact the same controls regarding functionality. These are
1. Selected item/items
2. Show an overlay with all bound items 
3. Filter / Search for items

The only difference is that the Autocomplete can select multiple items. I would go even one step further that Autocomplete, Combobox, Listbox and Select are the same controls with options for configuring search/filter, overlay or not, single/multi select.

**Comment by neoix** [comment]
@vnbaaij by looking at Aspire dashboard, the FluentCombobox is using a 'contains' filter and not 'startsWith'. I'm not sure if they customised/enhanced the component. I'd suggest to reconsider reopening this issue.

**Comment by vnbaaij** [comment]
In Aspire it is done as follows:

```razor
<FluentCombobox TOption="SelectViewModel<FieldValue>"
                            @bind-Value="_formModel.Value"
                            @bind-Value:after="ValueChanged"
                            Items="@_filteredValues"
                            Width="100%"
                            Height="400px"
                            OptionText="@(c => c.Name)"
                            OptionValue="@(c => c.Name)"
                            Immediate="true"
                            ImmediateDelay="@FluentUIExtensions.InputDelay"
                            Label="@Loc[nameof(Dialogs.FilterDialogTextValuePlaceholder)]">
```

```csharp
private void ValueChanged()
    {
        if (_allValues != null)
        {
            IEnumerable<SelectViewModel<FieldValue>> newValues = _allValues;
            if (_formModel.Value is { Length: > 0 } value)
            {
                newValues = newValues.Where(vm => vm.Name.Contains(value, StringComparison.OrdinalIgnoreCase));
            }

            // Limit to 1000 items to avoid the combo box have too many items and impacting UI perf.
            _filteredValues = newValues.Take(1000).ToList();
        }
        else
        {
            _filteredValues = [];
        }
    }
```

I suggest you try an approach like that.

**Comment by neoix** [comment]
Super! Thanks a lot for the suggestion 👍🏻
