### ISSUE TITLE
FluentNavMenu ignores the @onmouseover event

### ISSUE THREAD

**Issue by JasonWeise** [microsoft/fluentui-blazor#1642]
I've come across a need to use the @onmouseover even on the FluentNavMenu but have found regardless of what I do it doesn't trigger the event.

`
<FluentNavMenu @bind-Expanded="@expanded" Width="250" Title="Custom navigation menu" Collapsible="true" @onmouseover="OnHover">
`

Is ther some other way I can use the mouseover / mouseenter / mouseout events with the FluentNavMenu?
Note this is using v4.4.1

**Comment by vnbaaij** [comment]
Hi,

We have not hooked up those events in the FluentNavMenu component and have no plans to do so in the future.

Don't think there is anything your can do to hook those events up yourself. Sorry.
