### ISSUE TITLE
docs: fix FluentWizard documentation

### ISSUE THREAD

**Issue by StevenRasmussen** [microsoft/fluentui-blazor#1655]
# 🙋 Documentation Request

I'm guessing some documentation should be available for the `FluentWizard` component?  When I click on the link on the documentation site it goes to the URL: [https://www.fluentui-blazor.net/new%20Icons.Regular.Size20.ArrowStepInRight()](https://www.fluentui-blazor.net/new%20Icons.Regular.Size20.ArrowStepInRight())

This is what displays:

![image](https://github.com/microsoft/fluentui-blazor/assets/11198735/d725cfc8-ff6e-49c8-9acb-82487578deec)

**Comment by vnbaaij** [comment]
Fixed. Link is working again. Closing this.
