### ISSUE TITLE
fix: autocomplete when more than 9 items are available

### ISSUE THREAD

**Issue by StevenRasmussen** [microsoft/fluentui-blazor#1658]
# 🐛 Bug Report

The autocomplete popup does not display more than 9 items and does not show a scroll bar.  The autocomplete in the example below has 20 items in it.

## 💻 Repro or Code Sample

You can download code to reproduce the issue here: [https://github.com/StevenRasmussen/FluentAutoCompleteIssue](https://github.com/StevenRasmussen/FluentAutoCompleteIssue)

Simply run the project and the issue is demonstrated on the Home page.

## 🤔 Expected Behavior

The popup should show a scroll bar if more than 9 items are available.

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/11198735/ff825e0c-3bc0-4bfe-89ea-26e191123d87)

## 🔦 Context

I'm unable to select options that are available.

## 🌍 Your Environment

v4.5.0

**Comment by dvoituron** [comment]
Did you set the `MaximumOptionsSearch` property ? Default value is 9.

**Comment by vnbaaij** [comment]
Yes, setting that option solves the issue:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/21bf1a9d-5d29-48a6-bca4-fe5214f9dd02)
Closing this one.
