### ISSUE TITLE
DataGrid Export to Excel!

### ISSUE THREAD

**Issue by SoftGod4MrLi** [microsoft/fluentui-blazor#1667]
How to export DataGrid to Excel?

**Comment by dvoituron** [comment]
We don't have an existing method to do that, an that is not on our roadmap. 

But you can use tools like Open XML SDK (or other commercial SDK) to create an Excel file. 

https://github.com/dotnet/Open-XML-SDK

**Comment by michaelc06** [comment]
You can try open source library: ClosedXML - very easy to used.

https://github.com/ClosedXML/ClosedXML

**Comment by SoftGod4MrLi** [comment]
Thanks!
