### ISSUE TITLE
fix: Set Expanded property to false on FluentAccordionItem from code after manual expand., not working.

### ISSUE THREAD

**Issue by darcome** [microsoft/fluentui-blazor#1678]
# 🐛 Bug Report

Set Expanded property to false on FluentAccordionItem from code after manual expand., not working.

## 💻 Repro or Code Sample

You can check the following repository and follow the on screen instructions:

https://github.com/darcome/AccordionTest

The instructions are to open the accordion manually and then press the Close Accordion button.

## 🤔 Expected Behavior

After pressing the Close Accordion button, the accordion should collapse.

## 😯 Current Behavior

The accordion doesn't collapse.

## 🌍 Your Environment

* OS & Device: Windows 11 Home fully updated
* Browser Microsoft Edge fully updated
* .NET and Fluent UI Blazor library Version 8.0.2 and 4.5.0.

**Comment by vnbaaij** [comment]
I don't know why setting `accordionOpen = false` does not work (in your code). If I change it to: 
```
private void CloseAccordion ()
{
	accordionOpen = !accordionOpen;
	StateHasChanged();
}
```
The button works as a charm (as a toggle button). Is that something you can work with?

**Comment by darcome** [comment]
Yes, probably I can, but it seems like an hack to me. I think it should be fixed.

However, thank you for the response.

**Comment by c0g1t8** [comment]
@darcome 

>  The accordion doesn't collapse.

The accordian is in a collapsed state when the page is initialized.

        private bool accordionOpen { get; set; }

In [line 21](https://github.com/darcome/AccordionTest/blob/b4cedef8038ca1d998a510da75c7b6c78994d69b/AccordionTest/Pages/Home.razor#L21), **accordianOpen** defaults to **false**. Clicking on the button doesn't change **accordianOpen**. 😄 

One more thing, you don't need the extra **StateHasChanged()**. Changing a parameter for a component will cause it to re-render.  This should be all you need.

 ```csharp
@code
{
    private bool accordionOpen { get; set; } = true;

    private void CloseAccordion()
    {
        accordionOpen = !accordionOpen;
    }
}
```

**Comment by darcome** [comment]
> In [line 21](https://github.com/darcome/AccordionTest/blob/b4cedef8038ca1d998a510da75c7b6c78994d69b/AccordionTest/Pages/Home.razor#L21), **accordianOpen** defaults to **false**. Clicking on the button doesn't change **accordianOpen**. 😄
> 

This is not correct, because as I wrote in the instructions, the first thing to do is to open the accordion, and since the **accordionOpen** variable is bound to the **Expanded** property it should be set to true by the time the button is clicked.

> One more thing, you don't need the extra **StateHasChanged()**. Changing a parameter for a component will cause it to re-render. This should be all you need.

Infact in my code there is no **StateHasChanged()**.

**Comment by vnbaaij** [comment]
Expanded is not a 2-way bound parameter. There is no ExpandedChanged defined in the component. So Gary's explanation is correct. 
Not sure why not having ExpandedChanged does not raise a compile time error though

**Comment by darcome** [comment]
Sorry, I didn't know that. Yes, since I didn't receive any error, I assumed it was 2way.

**Comment by vnbaaij** [comment]
No worries. 


I'll see if I can add the 2-way binding. And if it works with the underlying web component (which I think it does because it reasons to setting it manually)

**Comment by vnbaaij** [comment]
Fixed with the PR mentioned above. Will be in next release. We also added a new example to show this behavior. See https://preview.fluentui-blazor.net/Accordion#controlfromcode. (will be on regular demo site after release). 

A new preview package that you can use to test this will be available on NuGet tomorrow.

Just a heads-up, the type of the `Expanded` parameter on the AccordionItem has been changed from `bool?` to `bool`
