### ISSUE TITLE
fix: app freeze when using InputFileMode.Stream in FluentInputFile

### ISSUE THREAD

**Issue by ihavenokia** [microsoft/fluentui-blazor#1683]
# 🐛 Bug Report

I createad a simple file upload using `FluentInputFile` component. After the files are uploaded, I can't navigate to other pages nor execute methods within the same page. I'm new to Blazor, so can't tell much what is going on, but after a while I get an error:

On screen:
**An unhandled exception has occurred. See browser dev tools for details.**

In dev console:
 **Error: System.TimeoutException: Did not receive any data in the allotted time.
 Error: Cannot send data if the connection is not in the 'Connected' State.**

## 💻 Repro or Code Sample
```
    <FluentInputFile Id="my-file-uploader"
                     Mode="InputFileMode.Stream"
                     Multiple="false"
                     MaximumFileSize="@(10*1024*1024)"
                     Accept="pdf"
                     OnCompleted="@((IEnumerable<FluentInputFileEventArgs> files) => OnCompletedAsync(files))"
                     Style="height: 300px; border: 1px dashed var(--accent-fill-rest);">
    </FluentInputFile>
```
`OnCompletedAsync` is empty.

## 🤔 Expected Behavior
Being able to navigate/execute actions as normal

## 😯 Current Behavior
Application freezes. The buttons work visualy, url changes, but the screen itself dont move.

## 🔦 Context
I'm working on a side project to learn Blazor and Fluent UI. I previously uploaded files with no problem using blazor native component, and then I uploaded them to azure storage account as a blob.

## 🌍 Your Environment

* OS & Device: Windows 11, VS2022
* Browser: Edge
* .NET 8.0.2 and Fluent UI Blazor library Version 4.4.1 and 4.5.0

**Comment by vnbaaij** [comment]
Hi,

We can't repro your issue with the code sample you provided. We need details on type of interactivity, Server/Wasm/SSR, etc. Please supply us with a ready-to-run- project or repository. Help us to help you.

**Comment by ihavenokia** [comment]
I found a fix for this. I dont know if you want this here, but I added this code and it is working now:
In `FluentInputFile` component:

` OnFileUploaded="@OnFileUploadedAsync"`

In code:
```
async Task OnFileUploadedAsync(FluentInputFileEventArgs file)
{
    progressPercent = file.ProgressPercent;
    progressTitle = file.ProgressTitle;

    var localFile = Path.GetTempFileName() + file.Name;
    Files.Add(localFile);

    // Write to the FileStream
    // See other samples: https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads
    await using FileStream fs = new(localFile, FileMode.Create);
    await file.Stream!.CopyToAsync(fs);
    await file.Stream!.DisposeAsync();
}
```

I believe it has something to do with the last two lines:
```
await file.Stream!.CopyToAsync(fs);
await file.Stream!.DisposeAsync();
```

Thanks!
