### ISSUE TITLE
feat: add Content Security Policy Header in Security

### ISSUE THREAD

**Issue by cheriansk** [microsoft/fluentui-blazor#1684]
# 🙋 Feature Request

Content Security Policy header  - Framework is adding inline styles and having a strict header policy is causing the components to stop working. 
For instance below code , adds inline css styles

<FluentGrid Spacing="0">
    <FluentGridItem xs="2"></FluentGridItem>
    <FluentGridItem xs="8" sm="7">
    </FluentGridItem>
</FluentGrid>
<FluentDivider Class="my-3"></FluentDivider>

## 🤔 Expected Behavior
Strict security header to be allowed

## 😯 Current Behavior

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='

**Comment by vnbaaij** [comment]
Is this related to https://github.com/dotnet/aspnetcore/discussions/53665#discussioncomment-8270054?

If not, please elaborate and give some concrete examples on wehre issues occur and what would need to done to prevent those. Thanks.

**Comment by cheriansk** [comment]
> Is this related to [dotnet/aspnetcore#53665 (comment)](https://github.com/dotnet/aspnetcore/discussions/53665#discussioncomment-8270054)?
> 
> If not, please elaborate and give some concrete examples on wehre issues occur and what would need to done to prevent those. Thanks.

let me try this out. Not sure what happened with the original post i made (had all the logs and screenshots but its missing now) 

basically am trying to get rid of the usage of "unsafe-inline" directive from the CSP headers.

**Comment by vnbaaij** [comment]
Javier and Damien know way more about this than me. If they both use that piece of code, I'm pretty sure you can not circumvent that. Just as we can't circumvent to have I line styles at a couple of places.

Sorry we can't be of more help. Closing this as there is no action from our side at this time.
