### ISSUE TITLE
fix: Columns out of sync with header in FluentDatagrid

### ISSUE THREAD

**Issue by trondjun** [microsoft/fluentui-blazor#1685]
I have encountered an error, which seems to be somewhat consistent, on the Fluent DataGrid. 
If you have a data grid that is to wide (not dependent on the area where it is displayed) there becomes out of sync values in the data part of the grid and the headlines of each column.

Data in the grid does not match the headlines.

See the image her:
![image](https://github.com/microsoft/fluentui-blazor/assets/1239565/93a42203-5d19-4836-b592-8113c319cc76)
 
The last there column of data are supposed to be on each of the three headlines in the image.
They are gathered in the end, underneath the last one.
The two first columns of data should be under the two previous headlines.

The column has in total 14 columns with various name lengths, but the issue seems to appear around 9-10 columns.
The size of the data fields doesn't seem to be the issue, as this is mostly single digit numbers in my Datagrid.

I have seen this issue on another table earlier, but did changes to the number of columns and did not think anymore around this.

Let me know if I can do anything further to help you reproduce the issue.

Kind regards,
Trond J. Undrum

**Comment by vnbaaij** [comment]
Are you setting any widths with the `GridColumnsTemplate` parameter?

To be able to reproduce, we need ready-to-run project or repo. Or at least code we can copy paste.

**Comment by trondjun** [comment]
Nope, this is plain PropertyColumns with only Title and Property.
The first column is sortable, the other columns are not sortable. 

The project is a part of a larger solution, but I can try to past some code:

This is the actual data grid:
` <FluentDataGrid Items="@RecentResourcePlans.AsQueryable()" >
     <PropertyColumn Title="Skole" Sortable="true" Property="@(rp => rp.SchoolOrganization.Name)" />
     <PropertyColumn Title="Plannavn" Property="@(rp => rp.PlanTitle)" />
     @if (VisualLastModified)
     {
         <PropertyColumn Title="Sist endret" Property="@(rp => rp.LastModified)" />
     }
     @if(VisualResources)
     {
         <PropertyColumn Title="Tildelt ass.hjemler" Property="@(rp => Math.Round(rp.ResourcePlannerSummary.AssingedAssistantResources,1))" />
         <PropertyColumn Title="Benyttet ass.hjemler" Property="@(rp => Math.Round(rp.ResourcePlannerSummary.UsedAssistantResources, 1))" />
         <PropertyColumn Title="Tildelte ped.hjemler" Property="@(rp => Math.Round(rp.ResourcePlannerSummary.AssingedTeacherResources,1))" />
         <PropertyColumn Title="Benyttet ped.hjemler" Property="@(rp => Math.Round(rp.ResourcePlannerSummary.UsedTeacherResources,1))" />
     }
     @if(VisualGroupSize)
     {
         <PropertyColumn Title="Gr.Str 1-4" Property="@(rp => Math.Round(rp.ResourcePlannerSummary.GroupSize1To4,1))" />
         <PropertyColumn Title="Gr.Str 5-7" Property="@(rp => Math.Round(rp.ResourcePlannerSummary.GroupSize5To7,1))" />
         <PropertyColumn Title="Gr.Str 8-10" Property="@(rp => Math.Round(rp.ResourcePlannerSummary.GroupSize8To10,1))" />
     }
     @if(VisualStudentCount)
     {
         <PropertyColumn Title="Elever med lærervedtak alene" Property="@(rp => rp.ResourcePlannerSummary.StudentsWithTeacherHoursAlone)" />
         <PropertyColumn Title="Elever med assistentvedtak alene" Property="@(rp => rp.ResourcePlannerSummary.StudentsWithAssistantHoursAlone)" />
         <PropertyColumn Title="Elever med gruppevedtak" Property="@(rp => rp.ResourcePlannerSummary.StudentGroupResolutions)" />
         <PropertyColumn Title="Elever med språkvedtak" Property="@(rp => rp.ResourcePlannerSummary.StudentsWithLanguageResolutions)" />
     }
 </FluentDataGrid>`

Will this help?

**Comment by vnbaaij** [comment]
I would suggest to first try the `GridColumnTemplates` parameter I mentioned. This allows you to 'hard code' the  column widths like:
```
<FluentDataGrid @ref="grid" Items=@items GridTemplateColumns="1fr 1fr 1fr 1fr" Style="height: 100%;">
```

**Comment by vnbaaij** [comment]
Closing this a no further action planned
