### ISSUE TITLE
feat: add ToHexColor to Swatch

### ISSUE THREAD

**Issue by Skintkingle** [microsoft/fluentui-blazor#1690]
# 🙋 Feature Request

Provide a mechanism to go from a `Swatch` to a hex colour string.

## 🤔 Expected Behavior

To be able to, with a single method call, get a Hex colour string from a Swatch

## 😯 Current Behavior

Not built in to the framework.

## 💁 Possible Solution

Currently we use this extension method:

    private string? ToColourHex(this Swatch swatch)
    {
        int rVal = (int)(swatch.R * 255);
        int gVal = (int)(swatch.G * 255);
        int bVal = (int)(swatch.B * 255);
        var hexVal = $"#{rVal:X2}{gVal:X2}{bVal:X2}";
        return hexVal;
    }

but this only covers our needs. It doesn't consider anything about how RelativeLuminance would affect the result, or any alpha elements.

## 🔦 Context

We have a Swatch from 1 Design Token and wish to set the colour of other elements to that same colour. There is no in-framework way to nicely get this Colour hex string.

## 💻 Examples

    AccentForegroundRest.GetValueFor(_myElementReference!.Element).ToColourHex();
    AccentForegroundRest.GetValueFor(_myElementReference!.Element).ToColourHex();
    <FluentProgressRing Color=@(PredefinedSwatch.ToColourHex()) />

**Comment by vnbaaij** [comment]
I don't think alpha is being used. The RelativeLuminance value can be retrieved from te Swatch itself.

I'll add the extension method for a next release. Will be using the US spelling thoug (to stay in line with the rest of the lib)
