### ISSUE TITLE
FluentSelect and FluentCombobox: Clicking an item does not select it in hybrid app (Windows).

### ISSUE THREAD

**Issue by garrenf** [microsoft/fluentui-blazor#1694]
FluentSelect and FluentCombobox work fine in a Blazor web app, but do not work in a hybrid app when launched on the Windows machine. The problem is that trying to select an item from the drop down list does not work. The list just closes, and the item is not selected. However, using the directional arrows seems to select items from the list just fine. This is only happening on the Windows machine.

**Comment by vnbaaij** [comment]
Please supply us with a project or repository to reproduce this.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

Help us to help you. Thanks

**Comment by garrenf** [comment]
Hi Vincent,
I do apologize for that. Here are the steps to reproduce this bug:

1. Create a .NET MAUI Blazor Hybrid App
2. Add the FluentUI components
3. Take the code from any example show on the Select or Combobox page and add it to your project: https://www.fluentui-blazor.net/Select
4. Run the project on the Windows machine

You will notice that trying to select any item via mouse clicks does not work, however, the item can be selected with the directional arrows. I have attached a file that contains a project showing this bug.
[FluentSelect-and-FluentCombobox.zip](https://github.com/microsoft/fluentui-blazor/files/14616439/FluentSelect-and-FluentCombobox.zip)

**Comment by vnbaaij** [comment]
Unfortunately, none of my Visual Studio installations (yes, I have more than one 😀) is running the project. I don't have time at the moment to fix that. Will keep the issue open so we won't forget, but it might take a while. Blazor Hybrid/MAUI is not our main focus area.

**Comment by gulatir** [comment]
> Unfortunately, none of my Visual Studio installations (yes, I have more than one 😀) is running the project. I don't have time at the moment to fix that. Will keep the issue open so we won't forget, but it might take a while. Blazor Hybrid/MAUI is not our main focus area.

**Comment by gulatir** [comment]
I was able to run the solution from @garrenf using "Windows Machine" AS IS and indeed see the issue. The dropdown selection does not happen via the mouse, but works when using the keyboard.  BTW I am using Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.9.3

**Comment by vnbaaij** [comment]
Sorry, I wasn't implying the source is incorrect. I meant my VS installations are not in a 'capable of running MAUI apps'-state

**Comment by vnbaaij** [comment]
Ok, got my VS install to behave again. MAUI apps are working as they should...

I changed the project file so it use the latest MAUI packages:

```
<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)" />
```

And in `index.html` it needs to be like this:

```
<script app-name="MauiApp1" src="./_content/Microsoft.FluentUI.AspNetCore.Components/js/initializersLoader.webview.js"></script>
<script src="_framework/blazor.webview.js" autostart="false"></script>
```

You commented out the `autostart=false` line but that was wrong. It needs to be like generated in the template but you copied from our docs both of the lines instead of only the initializer one.

After these changes and a rebuild, the list are working for me:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/05fe784c-6723-496e-b40e-44451c9374f7)

**Comment by vnbaaij** [comment]
I'm not that deep into MAUI so no, can't help with that. It was my assumption that using that variable would the include the latest packages. But guess that is why they say what they say about assumptions...😀

**Comment by garrenf** [comment]
No problem, Vincent. I ended up narrowing it down to these two packages:
![image](https://github.com/microsoft/fluentui-blazor/assets/144177629/bb9f48cd-c9c7-4236-bd15-597cecacde45)
Updating to the latest (8.0.10) breaks the components, but anything before allows them to work properly which you've help me figure out. Thanks again!
