### ISSUE TITLE
FluentAppBarItem Add Click Event

### ISSUE THREAD

**Issue by SoftGod4MrLi** [microsoft/fluentui-blazor#1696]
# 🙋 Feature Request

FluentAppBarItem Add Click Event

## 🤔 Expected Behavior

I hope FluentAppBarItem can have a click event, for example, when used as a primary menu, clicking FluentAppBarItem can refresh the submenu.
![屏幕截图 2024-03-15 162946](https://github.com/microsoft/fluentui-blazor/assets/89335285/c6cacf85-f320-4b00-97e6-1eac80b339bd)

## 😯 Current Behavior

There are currently no click events.

**Comment by vnbaaij** [comment]
Will be in next release

**Comment by SoftGod4MrLi** [comment]
Oh，Thanks!
