### ISSUE TITLE
feat: add freeform property to FluentCombobox

### ISSUE THREAD

**Issue by lettuceDestroyer** [microsoft/fluentui-blazor#1697]
# 🙋 Feature Request

I'd like the `freeform` property to be added to the FluentCombobox in blazor. The React version has the property [`freeform`](https://react.fluentui.dev/?path=/docs/components-combobox--default&globals=storybook_fluentui-react-addon_dir:ltr#freeform) which allows the programmer to decide whether or not custom values should be allowed.

## 🤔 Expected Behavior

The user should not be allowed to enter custom values.

## 😯 Current Behavior

Currently it is not possible to disallow the user to type custom values.

**Comment by dvoituron** [comment]
At the moment, we don't support this feature, but you could use the `FluentAutocomplete` component with the `ValueText` property.
