### ISSUE TITLE
fix: FluentDataGrid becomes vertically stacked on navigation

### ISSUE THREAD

**Issue by akanieski** [microsoft/fluentui-blazor#1699]
# 🐛 Bug Report

FluentDataGrid becomes vertically stacked on navigation. I have attached a zip with a repro.

## 💻 Repro or Code Sample

- Run attached demo project
- Note the table is rendered correctly on initial load
- Click the "Demo" link on the navbar
- Note the table is now no longer rendered correctly

https://github.com/microsoft/fluentui-blazor/assets/595427/785f432b-f035-46dd-8db2-13e182a7cd44

## 🤔 Expected Behavior
The table formatting should be rendered the same while navigating and full page refresh

## 😯 Current Behavior
The table formatting is rendered vertically.

## 🔦 Context
Cannot use the FluentDataGrid if it behaves this way.

## 🌍 Your Environment

* Microsoft.FluentUI.AspNetCore.Components @ 4.5.0
* Microsoft.FluentUI.AspNetCore.Components.Icons @ 4.5.0
* Windows 11 Version	10.0.22631 Build 22631
* Edge Version 122.0.2365.80 (Official build) (64-bit)
* .NET 8.0.2 

[FluentDataGrid_Issue.zip](https://github.com/microsoft/fluentui-blazor/files/14616189/FluentDataGrid_Issue.zip)

**Comment by vnbaaij** [comment]
Not a library issue. The Demo/Home page (`Releases.razor`) is using the **default** .NET 8 SSR rendering. The grid initially displays well but doesn't do anything (like sorting) and just gets lost on re-rendering. 

For the grid to be functional, it **must have** interactivity. You can do that by adding `@rendermode InteractiveServer` just below the `@page` directives.

ps The interactivity bit is mentioned on the https://www.fluentui-blazor.net/Templates page
