### ISSUE TITLE
feat: add lazy loading to FluentTabs

### ISSUE THREAD

**Issue by gkizior** [microsoft/fluentui-blazor#1700]
# 🙋 Feature Request

### Lazy Loading option for `FluentTabs`

My understanding of `DeferredLoading` on `FluentTab` class is that it prevents rendering of the tab content until you select that tab. 

It would be great if each tab content is _only_ rendered/loaded the _first_ time it is selected.

## 🤔 Expected Behavior

Consider a web page with multiple tabs, where each tab’s content takes approximately 1-2 seconds to load. With this enhancement, users would experience faster tab switching when revisiting previously loaded tabs.

## 😯 Current Behavior

Revisiting a tab causes reload of the tab content

---

Thanks!

**Comment by vnbaaij** [comment]
Hi,

We can't prevent the re-rendering. Blazor needs to do that to account for the chages that (might) have occured in the DOM. 

With regards to the data being shown on a tab and the time it takes to load that data, I don't think it is the responsibility of the library to do anything there. You can (and should) create and use your own caching strategy for that.
