### ISSUE TITLE
fix: FluentButton broke External Login

### ISSUE THREAD

**Issue by BetoMees** [microsoft/fluentui-blazor#1702]
# 🐛 Bug Report

There seems to be an issue with using FluentButton when submitting data. Due to its design, FluentButton creates two buttons, resulting in an array submission with duplicate values like ["Facebook", "Facebook"]. This can lead to problems finding the correct handler for the intended action.
![image](https://github.com/microsoft/fluentui-blazor/assets/15331041/33da9466-112e-47f6-b3a7-ceec2aa733d0)
![image](https://github.com/microsoft/fluentui-blazor/assets/15331041/3ec88f48-e895-4628-90bc-423ddc37eac1)
![image](https://github.com/microsoft/fluentui-blazor/assets/15331041/76feb108-3eaa-4aef-90ec-f1b3ddd62136)

## 💁 Possible Solution

You could change the FluentButton designer or prevent multiples values on the MapPost of PerformExternalLogin

## 🌍 Your Environment

* OS & Device: Windows
* Browser: [Google Chrome, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.3 and 4.5.1-preview.24073.1]

**Comment by BetoMees** [comment]
For some reason the Fluent UI template isn't using the last version of the template, [here](https://github.com/microsoft/fluentui-blazor/commit/a816ef89da18bcaa3ae0e18cc65421168127853d) you can see the workaround for this problem

**Comment by vnbaaij** [comment]
> For some reason the Fluent UI template isn't using the last version of the template, [here](https://github.com/microsoft/fluentui-blazor/commit/a816ef89da18bcaa3ae0e18cc65421168127853d) you can see the workaround for this problem

I don't understand what you mean. The workaround is not in the template? Are you sure you installed the latest **template** (4.5.0) package?

**Comment by BetoMees** [comment]
Sorry a was using version 4.1.1
