### ISSUE TITLE
FluentAutocomplete SelectedOptionChanged not work

### ISSUE THREAD

**Issue by 282030166** [microsoft/fluentui-blazor#1704]
FluentAutocomplete SelectedOptionChanged not work

`<FluentAutocomplete TOption="Country"
                    AutoComplete="off"
                    Autofocus="true"
                    Label="Select a country"
                    Width="250px"
                    Placeholder="Select countries"
                    OnOptionsSearch="@OnSearch"
                    MaximumSelectedOptions="5"
                    OptionText="@(item => item.name)"
                    SelectedOptionChanged="ontest" />`

`
@code {
      public void ontest(Country c)
      {
          Console.WriteLine(c.name);
  
      }
    }
`

**Comment by StevenRasmussen** [comment]
The code above is not fully functional.  Are you able to provide the code for the `Country` object and the `OnSearch` method?  Or even better, provide a link to a repo that reproduces the issue?

**Comment by dvoituron** [comment]
You need to use the `SelectedOptionsChanged` event (with `s`) because the Autocomplete can select multiple items. 
And so, as described in the documentation, "Called whenever the selection changed.. Only available if Multiple = false".

**Comment by farazp** [comment]
> s

Document of that isn't competed and fully describe of that
