### ISSUE TITLE
Fix keyboard navigation in menus

### ISSUE THREAD

**Issue by danieldegtyarev** [microsoft/fluentui-blazor#1709]
# 🐛 Bug Report

Keys Up, Down, Right, Left must change selected item in the menus.
Enter must click menu item.

## 💻 Repro or Code Sample

Go to https://www.fluentui-blazor.net/Menu
For ex., scroll to "Simple context menu" and try to press Up / Down / Enter

## 🤔 Expected Behavior

Keys Up, Down, Right, Left must change selected item in the menus.
Enter must click menu item.

## 😯 Current Behavior

Viewport is scrolled, enter does not click

**Comment by dvoituron** [comment]
This works, but you need to activate the 'Menu' section first, using the Tab key for example.

![peek_1](https://github.com/microsoft/fluentui-blazor/assets/8350694/5ec5839c-9f80-40ee-b63d-c7255e50abe8)
