### ISSUE TITLE
feat: add Format property to FluentNumberField

### ISSUE THREAD

**Issue by Skintkingle** [microsoft/fluentui-blazor#1715]
# 🙋 Feature Request

Ability to format the displayed value in the FluentNumberField. Mainly so I can make a currency look like a currency and always format with 2 decimal places.

## 🤔 Expected Behavior

To be able to configure a string format to the FluentNumberField

## 😯 Current Behavior

Doesn't exist.

## 💁 Possible Solution

<FluentNumberField @bind-value=MyCurrencyValue Format="N2" />

## 🔦 Context

When working with currencies it's normal to see trailing0s to the expected decimal places in the currencies denomination. It's currently not possible to get the FluentNumberField to display a certain level of decimal places. if a value is 12 I want to see 12.00, currently I just see 12.

**Comment by vnbaaij** [comment]
Hi, 

This is not supported by the underlying web component (I would also strongly advise to not use a NumberField for a currency input, but that is a different story, see #1127 ). so we are not going to supply this out of the box
 
I think you can achieve this by 'subclassing' the `FluentTextField` (see https://www.meziantou.net/bind-an-inputnumber-on-input-with-decimal-numbers-in-blazor.htm for some inspiration). The `FluentTextField` recently also added support for setting an `InputMode` parameter, so you perhaps have what you need with setting that to "Decimal" or "Numeric".

**Comment by Skintkingle** [comment]
Loud and clear that it won't be supported if the underlying framework doesn't support it. Initially an interesting read on that blog post on #1127. I'll absorb that a bunch more and implement something else. Thank you.
