### ISSUE TITLE
fix: FluentAppBar hiding items randomly and pop-over looks broken in Blazor (hybrid and PWA) app

### ISSUE THREAD

**Issue by nd1012** [microsoft/fluentui-blazor#1717]
# 🐛 Bug Report

I want to use the `FluentAppBar` as menu in the `MainLayout.razor`. For this I use a horizontal `FluentStack` to wrap the `FluentAppBar` and a `FluentBodyContent` element, which shows the body. The menu has 3 items, which is way less than the available space, so I assume that none of the items should be hidden per default. But one or two items, sometimes ALL items are being hidden and only accessable by clicking "..." to open the pop-over. The pop-over does not fit well into the view, the top is overflowing out to the top of the window, and the items are not being displayed properly (it seems they are overlayed), so it's only possible to reach one item. Also if only one item is hidden, in the pop-over it looks like another item is behind the hidden item.

## 💻 Repro or Code Sample

You can find the whole Visual Studio 2022 solution here: https://github.com/nd1012/wan24-I8NGUI

This is the current `MainLayout.razor`:

```cshtml
@inherits LayoutComponentBase
<FluentDesignTheme StorageName="theme" />
<FluentStack Orientation="Orientation.Horizontal"
                HorizontalAlignment="HorizontalAlignment.Left"
                VerticalAlignment="VerticalAlignment.Top"
                Style="width: 100%; height:100%">
    <FluentAppBar Style="width: 100px; height:100%;">
        <NavMenu />
    </FluentAppBar>
    <FluentBodyContent Style="height: 100%">
        @Body
    </FluentBodyContent>
</FluentStack>
<FluentToastProvider />
<FluentDialogProvider />
<FluentTooltipProvider />
<FluentMessageBarProvider />
```

And the `NavMenu.razor`:

```cshtml
<FluentAppBarItem 
    Href="" 
    Match="NavLinkMatch.All" 
    IconRest="HomeIcon()" 
    IconActive="HomeIcon(active: true)" 
    Text="@_("Home")" />

<FluentAppBarItem 
    Href="counter" 
    Match="NavLinkMatch.All" 
    IconRest="CounterIcon()" 
    IconActive="CounterIcon(active: true)"
    Text="@_("Counter")" />

<FluentAppBarItem 
    Href="weather" 
    Match="NavLinkMatch.All" 
    IconRest="WeatherIcon()" 
    IconActive="WeatherIcon(active: true)"
    Text="@_("Weather")" />

@code {
    private static Icon HomeIcon(bool active = false)
            => active
                ? new Icons.Filled.Size24.Home()
                : new Icons.Regular.Size24.Home();

    private static Icon CounterIcon(bool active = false)
            => active
                ? new Icons.Filled.Size24.ArrowCounterclockwise()
                : new Icons.Regular.Size24.ArrowCounterclockwise();

    private static Icon WeatherIcon(bool active = false)
            => active
                ? new Icons.Filled.Size24.Cloud()
                : new Icons.Regular.Size24.Cloud();
}
```

The project is a very early prototype and seems to have a bug in the Hybrid Blazor project `wan24-I8NGUI`, which prevents the app from loading the MAUI GUI randomly (simply stop the debugger and restart debugging, if that happens). But you can also run the `wan24-I8NGUI Web` project, it's a Blazor PWA app.

## 🤔 Expected Behavior

I assumed that all items should be visible in the `FluentAppBar`, since the height is at 100%, and the view actually has space for displaying many more items without having to hide anything in the pop-over.

I also assumed the pop-over to look as nice as seen here: https://www.fluentui-blazor.net/AppBar

## 😯 Current Behavior

The `FluentAppBar` hides items randomly, even here's enough space to display all.

The pop-over display looks completely broken in my app.

![image](https://github.com/microsoft/fast/assets/10883272/8b45456b-4691-4be8-a23e-30b114cf3c09)

![image](https://github.com/microsoft/fast/assets/10883272/36928cef-d8cb-477a-863a-57a4e0e07ab1)

By hitting F5 sometimes all items are hidden, sometimes one, sometimes two - but never all items are visible.

## 💁 Possible Solution

I'd say I'm a bloody beginner with ASP.NET, Blazor and FAST - not sure, if I'm a great help...

## 🔦 Context

I want to use FAST in a Blazor Hybrid app, and also in a Blazor PWA app. There I want to use the `FluentAppBar` as main menu in the `MainLayout.razor`.

## 🌍 Your Environment

* OS & Device: Windows 10 Pro 22H2 on 64bit PC
* Browser WebView2 and Edge
* Version WebView version 2, Edge version 122.0.2365.80 (official build) (64-Bit)
* Visual Studio 2022 Community 17.10.0 Preview 2.0
* Blazor Hybrid and PWA app using .NET 8

**Comment by vnbaaij** [comment]
You are using a `FluentStack` in your `MainLayout.razor` with a height of 100%. The stack is using `display: flex` so 100% height then equals the height the biggest part of the stack and ** NOT**  the total height of the app frame. In this case the height is determined by the body content. See the image below. In this situation there is not nough space for the app bar items

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/93fd7e02-7667-452f-8f91-0a0ca2e69a69)

(You can use F12 to show Dev Tools in a Hybrid app)

It can easily be solved by setting the height of the stack to somethng like 100vh or 100dvh:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/dae3754c-11bd-463f-ba23-9828eacd008c)

On the AppBar itself, you only need to set a height. Setting a witdh is what causes the issues in the popover.

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/9e3cb2a7-ba99-4b9b-a53d-729641b4508b)

**Comment by vnbaaij** [comment]
It looks like that because you are still using the Bootstrap css (linked from `index.html`)

**Comment by vnbaaij** [comment]
You don't 'have to' but in some situations it might lead to clashes like this one
