### ISSUE TITLE
feat: add posibility to change column order in DataGrid

### ISSUE THREAD

**Issue by Wuz3t** [microsoft/fluentui-blazor#1724]
# 🙋 Feature Request

Some way of editing the order of columns would be great. 

## 🤔 Expected Behavior

You can drag the column header and move it to left/right and after dropping the order of columns and data changes.

## 🔦 Context

For tables with lots of columns ability to have them in your order is important. 

## 💻 Examples

Probably something similar to:
https://www.fluentui-blazor.net/SortableList
or 
https://www.fluentui-blazor.net/Drag

**Comment by vnbaaij** [comment]
I don't think e will be adding this anytime soon. Will take a large amont of development time (which we do not have). We do accept PR's...
