### ISSUE TITLE
fix: FluentSelect does not display the correct value when the component is initialized

### ISSUE THREAD

**Issue by markovicb85** [microsoft/fluentui-blazor#1725]
# 🐛 Bug Report

FluentSelect does not display the correct value when initializing the component.
This happens when the SelectedOption parameter is an instance of the class.

## 💻 Repro or Code Sample

It may be easier to check this on your own example in the file SelectedDefault.razor
You need to change the Person type from record to class and create object that match object from list of Items

`@inject DataSource Data
<FluentSelect TOption="Person"
              Label="Select a person"
              Items="@Data.People.WithVeryLongName()"
              Id="people-listbox"
              Width="200px"
              Height="250px"
              OptionValue="@(p => p.PersonId.ToString())"
              OptionText="@(p => p.LastName + ", " + p.FirstName)"
              @bind-SelectedOption="@SelectedPerson" />

<p>
    Selected person (strongly typed): @SelectedPerson?.ToString()
</p>

@code
{
    //Change Person to be class instead of record 
    Person? SelectedPerson = new Person
    {
        PersonId = 4,
        FirstName = "Nur",
        LastName = "Sari",
        CountryCode = "ID",
        BirthDate = new DateOnly(1922, 4, 27),
        Picture = "data:image/jpeg;base64,/9j/4AAQSk....../NFbiP/Z"
    };`

## 🤔 Expected Behavior

It should set Sari, Nur in FluentSelect component.
This worked in version 4.4.1

## 😯 Current Behavior

Returns the first value from the list, in this case Martin, Jean

## 🔦 Context

This is the code snippet from my project that worked until I updated to version 4.5

`<FluentSelect Class="w-100"
              Label="Seniority"
              Appearance="Appearance.Filled"
              Position="SelectPosition.Below"
              TOption="SeniorityTypeDto"
              Items="SeniorityTypes"
              Height="250px"
              OptionValue="@(p => p.Id.ToString())"
              OptionText="@(p => p.Name)"
              @bind-SelectedOption="@ResourceContent.Seniority" />

@code {
            [Parameter]
            public SaveResourceModel ResourceContent { get; set; }
    }
    
    Where Seniority is:
    public class SeniorityTypeDto
    {
        public int Id { get; init; }
        public string Name { get; init; }
    }
    
    When convert class to record it is working
    public record SeniorityTypeDto(int Id, string Name)
`

## 🌍 Your Environment

* OS & Device: [Windows, Linux] on [PC]
* Browser [Microsoft Edge, Google Chrome]
* .NET and Fluent UI Blazor library Version [e.g. 8.0 and 4.5.0]

**Comment by vnbaaij** [comment]
Hi,

This is not really a bug. 

In C#, with a `record` you automatically get a value-based equality comparison. With a `class` however, you get a reference-based (so are they using the same memory location). 

To determine which option needs to be selected, we aredoing an equality check and that wil not pass when using a class . it is possible to make it work be overriding the default `Object.Equals` implementation in your class. For `Person' this could look like:
```
public override bool Equals(object? obj) => obj is Person person && person.PersonId == PersonId;
```
Very simplistic of course as we are only taking the id into account here. But adding this to the Person class in the demo will select the correct person again. 

So, it is very well possible to use a class instance but you will need to do some work for that in your class code.

Closing this as this is not actionable from our side.

**Comment by markovicb85** [comment]
Ok, thanks for the quick reply.
