### ISSUE TITLE
fix: [FluentTab @bind-ActiveTabId="@SelectedTabId" does not work  if a new Tab was created]

### ISSUE THREAD

**Issue by joerguth** [microsoft/fluentui-blazor#1726]
# 🐛 Bug Report
If you create a new tab at runtime and set the SelectedTabId to the new tab, the new tab will not be activated.
This Error comes with version 4.5.0
Can be reproduced very easily with the Dynamic example on the page https://www.fluentui-blazor.net/Tabs 

## 💻 Repro or Code Sample
Just test with AddAndSelect in the sample Page

**Comment by vnbaaij** [comment]
The sample never did that befor, I believe. It seems the underlying web component messes up sometimes in determining which grid column to set the indicator on. Afraid we can't fix that here.

By making the `AddAndSelect` method async, it works 'sort of'...about 1 out of every 3 times a tab is added, it is also showing the active bar. It does always set the tab in a selected state then.
```
 async Task AddAndSelect()
    {
        i++;
        var item = new DataSource.MonthItem()
            {
                Index = $"{i:00}",
                Name = $"New {i:00}",
            };
        Items.Add(item);
        await Task.Delay(1);
        SelectedTabId = $"tab-{item.Index}";
    }
```

When going with a static set of tabs, this works:
```
<FluentTabs @ref="tabs" @bind-ActiveTabId="@_selectedTabId">
    <FluentTab Label="Foo" Id="foo">
        <FluentTextField Label="Foo" />
    </FluentTab>
    <FluentTab Label="Bar" Id="bar">
        Bar
    </FluentTab>
</FluentTabs>

<FluentButton OnClick="Next">Next ></FluentButton>

@code {
    private FluentTabs? tabs;
    private string _selectedTabId = "foo";

    private async Task Next()
    {
        await tabs!.GoToTabAsync("bar");
    }
}
```
See also #1314  for more background. As this is a bit of a niche cache, I won't go deepre on it and I'll close this issue.
