### ISSUE TITLE
fix: Image scale in FluentPersona on different browsers

### ISSUE THREAD

**Issue by joriverm** [microsoft/fluentui-blazor#1727]
# 🐛 Bug Report

Ok, sit on back, this is a doozy haha
the current implementation of the FluentPersona uses an img element to display the image it was given in the circle.
together with an `aspect-ratio` css tag to give the image an aspect-ratio to fit the circle.
this works great in chrome, but chrome is ignoring the `aspect-ratio` css specs a bit.
[apparently, `aspect-ratio` is only a suggestion in css, or 'preferred' aspect-ratio](https://www.w3.org/TR/css-sizing-4/#aspect-ratio), and if the loaded content has an aspect ratio it is suppose to use that instead. ([src](https://stackoverflow.com/a/70160430/14661514))
with divs it seems to work fine on browsers that do follow the specs and work fine, but that gives me other issues because of background css needing to be used.

## 💻 Repro or Code Sample

I reproduced the fluentUI persona in a jsfiddle so i could easily test some css as i was going through the specs and ideas. it also has some testing by replacing the img tag with div : https://jsfiddle.net/x64y20vp/

## 🤔 Expected Behavior

TBD, i have no idea what is wanted here..

## 😯 Current Behavior

images that don't have a 1/1 scale are not stretched in a browser engine that correctly uses `aspect-ratio` on an image.
this was tested on firefox.
the first image is an image that is longer than wide, so no 1/1 scale

![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/2d6c8ea5-b4e8-44ec-a9b5-89d96bff167d)

## 💁 Possible Solution
Websites, the specs and some googling says to at least give height or width a value, like 100% with the encapsulating container setting the constraint. However, with the jsfiddle i linked i get the following 

![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/e88805e5-5104-43db-b10f-61119234f651)

the images look great, but because content is now , consistently, being stretched to the requested aspect-ratio the anonymous image, which is 25x25 is also stretched and no longer looks like before
this might not be the requested result either?

It looks like other libraries all stretch, but i only looked at radzen, mudblazor and this fluent haha

## 🔦 Context
the issue is a minor one to us, as it only affects a minor part of the users atm, and we can fix this in our own css of the website to always stretch to the requested aspect ratio.

## 🌍 Your Environment

* OS & Device: W10
* Browser Google Chrome & Mozilla FireFox
* .NET and Fluent UI Blazor library Version 8.0.2 and 4.5.0

**Comment by vnbaaij** [comment]
I think we have use sort of the optimum values for this. If the source images are 'crap' then yes, it doesn't look super. But as you say, it can be solved in your own CSS so I don't think we are going to make changes on our end right now. Does that sound reasonable?

**Comment by joriverm** [comment]
hey vincent,

ye that sounds very reasonable. personally i find it kinda of annoying that this works differently depending on the browser. specially with chromium *kinda* breaking the rules.
but to do this right, i think it would need to check the image size and change some things depending on it etc.
aka, a lot of work so its very reasonable that this isn't quickly addressed hehe.

for now ive added the following css to our app.css, which forces it to always stretch
```
.fluent-persona .initials img {
    width: inherit !important;
}
```

**Comment by vnbaaij** [comment]
Ok, closing this one then as you have a workaround
