### ISSUE TITLE
Add MultiSelect to FluentDataGrid

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fluentui-blazor#173]
# 🙋 Feature Request

MultiSelect in FluentDataGrid would send multiple rows of data for bulk actions. Running the same action one row at a time would take a lot of time.

## 🤔 Expected Behavior

A user should be able to select multiple rows or deselect a selected row and be able to save the selected rows in a list that can be passed inside a method for bulk operation.

## 😯 Current Behavior

Currently you can only select one row, when you select another row, the previous row is no longer selected, and the data cannot be used anymore.

## 🔦 Context

I am migrating an existing application from the old blazor fluent nugget package to Blazor fast. I have a few grids that have a lot of rows. The rows are passed to a function that executes actions based on information that is passed from the row. A lot of rows need to be passed every day and every action needs sometimes to finish. It is better to pass multiple rows so that the action can run multiple times without the user needing to initiate it for every row and check if the previous row action is completed.

**Comment by EisenbergEffect** [comment]
Official row selection including multiple row selection is in development now.  I saw a demo of it yesterday myself, including full keyboard support. 😄

**Comment by chigivigi** [comment]
Will it be part of the new nugget version? When will it be released?

**Comment by EisenbergEffect** [comment]
The PR for selection in foundation is under review here: https://github.com/microsoft/fast/pull/5786 Once that is merged in, the Fluent UI Web Components will be updated, and then the Blazor wrappers. 

@vnbaaij Can you review the PR to make sure there's a path to enable this quickly for Blazor? I'm not sure if we'll need to do special interop or if it will "just work".

**Comment by LuohuaRain** [comment]
> The PR for selection in foundation is under review here: [microsoft/fast#5786](https://github.com/microsoft/fast/pull/5786) Once that is merged in, the Fluent UI Web Components will be updated, and then the Blazor wrappers.
> 
> @vnbaaij Can you review the PR to make sure there's a path to enable this quickly for Blazor? I'm not sure if we'll need to do special interop or if it will "just work".

It is merged in! 😍

**Comment by Seanxwy** [comment]
When will it be officially released?

**Comment by vnbaaij** [comment]
You'd need to ask in the Fluent UI Web Components repo when this will be in their script..

**Comment by sardar97** [comment]
since 2023 we are waiting for this 🤦‍♂️

**Comment by vnbaaij** [comment]
Come on guys...bit of a lame reaction. There are more important things in the world than just a bit of software.

You can go ask in the Fluent UI repo about the status but my guess is this won't come to the v2 (which we are using) version anymore...

**Comment by sardar97** [comment]
but @vnbaaij  this is very very important Feature! we love Blazor we love Fluent UI we want to improve it and use it instead of
other components and you need you to support it so please be kind with issues and Feature requests 🙏

**Comment by vnbaaij** [comment]
Well, we don't really _need_ to do anything. This is 'just an open source project that we are maintaining (with love) as good as we can. It is not a funded Microsoft product for which you can open a support ticket.

I don't think it is fair to say we are not open to requests and unkind to issues. We're pretty responsive I believe. And sometimes 'no' is also an answer 😉.

If you wanttthis feature, make it know to where it needs tocome from, ie the web components. It helps if other people beside us are more vocal there.

**Comment by vnbaaij** [comment]
> if I create a pull request to add **MultiSelect** for **FluentDataGrid** with _Branch_ shall I use?

We always work on the `dev` branch. `main` is where we merge to to build the release packages.

**Comment by sardar97** [comment]
hahaha ok i will try a pull request ❤️😅
