### ISSUE TITLE
fix: Assembly scanning directive in program.cs (using interactive auto template)

### ISSUE THREAD

**Issue by swegele** [microsoft/fluentui-blazor#1732]
# 🐛 Bug Report

When using the template with auto interactive on each page...
I _believe_ I found a bug where this line `.AddAdditionalAssemblies(typeof(Counter).Assembly);` from your template in program.cs file  scans and finds components in the server side project which ends up causing them to act like wasm/auto components even if they are marked with `@rendermode InteractiveServer`

## 💻 Repro or Code Sample

- Use your project template for fluent blazor selecting auto interactive and on each page.
- Copy "Pages\Counter.razor" from WASM project up into the server project.
- Rename it to "Pages\CounterServer.razor"
- Change it's render mode to `@rendermode InteractiveServer`
- Add a line for it in Change the NavMenu.razor appropriately
- run

## 🤔 Expected Behavior

The CounterServer.razor renders server side with circuit.

## 😯 Current Behavior

The CounterServer.razor renders as wasm.

## 💁 Possible Solution

I believe I fixed it by using changing that line in program to be like how it is when using the matching MS Blazor template:
`.AddAdditionalAssemblies(typeof(FluentBlazorAppAuto.Client._Imports).Assembly);`
I'm assuming that somehow limits the scope of the assembly scan?

```
<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.*-* " />
<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.*-* " />
```

**Comment by vnbaaij** [comment]
The change to look at `_Imports` in the standard template was made quite recently. See https://github.com/dotnet/aspnetcore/pull/54048. It also shows the reason for this:
>Always use typeof(Namespace._Imports).Assembly instead of typeof(Counter).Assembly so the compilation does not break when the sample Counter component is removed, and so the code is more consistent with how it is when no sample content is generated

So it won't limit the scope but just make it more resilient. I'll change it in our template as well.

I think your problem is just simply that the first Counter found is the WASM one. In the steps you took, you didn't mention if you are changing the `@page` directive of the counter. As you've not shared the code, I can't verify.

**Comment by swegele** [comment]
OK you are probably right that I either missed the page attribute or the rendermode attribute.  I just fresh demo of this from scratch and it works fine.  Thanks for reply!!
