### ISSUE TITLE
 Blazor Fluent UI Icon Not showing on Button  

### ISSUE THREAD

**Issue by jecojacob** [microsoft/fluentui-blazor#1742]
# 💬 RFC

Blazor Fluent UI Icon Not showing on Button  . I have installed V4.5 of the FluentUi.AspNetCore.Components.Icons 
On the FluentButton space is allocated but no Icon is showing

## 🔦 Context
I am developing an App in Blazor and using the FluentUI for all the UI requirements. 
  I have installed V4.5 of the FluentUi.AspNetCore.Components.Icons  On the FluentButton space is allocated but no Icon is showing. All other components are working fine

No errors are shown in the browser but no Icons are shown

**Comment by dvoituron** [comment]
What code have you written? We cannot find a solution without an example.

You have examples on our demo site and the icons are displayed correctly: https://www.fluentui-blazor.net/Button
```xml
<FluentButton IconStart="@(new Icons.Regular.Size16.Globe())">
    Button
</FluentButton>
<FluentButton IconEnd="@(new Icons.Regular.Size16.Globe())">
    Button
</FluentButton>
```

**Comment by jecojacob** [comment]
Thanks a lot for the quick response. Here is the repo. This is will be a big help for our project where we are getting into Blazor and moving from Angular 

https://github.com/jecojacob/ratesview.git

Thanks in advance.

**Comment by dvoituron** [comment]
In your code, the only place where an icon is used is in this code, and the result seems correct

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/4a5cb550-5f06-4ade-99af-e88d9bdb5a1b)


```xml
<FluentButton Appearance="Appearance.Accent">
    <FluentIcon Value="@(new Icons.Regular.Size20.Globe())" Color="Color.Fill" Slot="start"></FluentIcon>
    Log in
</FluentButton>
```
You can simplify your code using `IconStart`
```xml
<FluentButton Appearance="Appearance.Accent" IconStart="@(new Icons.Regular.Size20.Globe())">
    Log in
</FluentButton>
```
