### ISSUE TITLE
loading progress circle does not apply the theme color from local storage

### ISSUE THREAD

**Issue by franksandersen** [microsoft/fluentui-blazor#1752]
I have implemented FluentDesignTheme with Blazor WASM and it's working fine, except for one thing: the app progress circle defined in app.css (svg class="loading-progress"> in index.html) is always displayed in the **blue color** even if the theme is set to Excel or Powerpoint. Does anyone know how to let the loading progress circle use the theme color from local storage ?

**Comment by vnbaaij** [comment]
The css variables needed are not yet known at that time so they can't be used to style that ring.
If you know you are going to use Excel or PowerPoint accent color, you can hard code that value in the class you mentioned.
