### ISSUE TITLE
fix: Server version of demo site does not show whats new page on second visit

### ISSUE THREAD

**Issue by c0g1t8** [microsoft/fluentui-blazor#1770]
# 🐛 Bug Report

The server version of the demo site does not show the **WhatsNew** page on the second visit or subsequent visits. 

## 💻 Repro or Code Sample

Below is a video of the behaviour.

https://github.com/microsoft/fluentui-blazor/assets/23250332/c53af8df-b766-458d-b306-a7e04c4fda41

Starting the site with the cache clear shows the **WhatNew** page. Navigating away and then back shows the 'rendering hanging', then the **WhatsNew** page without content.

## 🤔 Expected Behavior

Demo site should have the same behaviour as the client version. 

## 😯 Current Behavior

At 24 second mark, rendering appears to hang and only the page title appears.

## 💁 Possible Solution

I've isolated the issue to how the caching mechanism works.

## 🔦 Context

Issue was not apparent until the size of the **WhatsNew.md** got larger. **This is not an issue on the client version**.

## 🌍 Your Environment

* OS & Device: Windows 10/11
* Browser: Edge and Chrome
* .NET and Fluent UI Blazor library Version: 8.0.2 and 4.6.0

**Comment by c0g1t8** [comment]
Additional information,

![image](https://github.com/microsoft/fluentui-blazor/assets/23250332/d4d9d59c-47e9-42f0-a509-83ee8abb81f5)

appears in the browser console, when visiting the **WhatsNew** page after initial visit.

**Comment by BetoMees** [comment]
Apparently the problems is with the [Size limits on JavaScript interop calls](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#size-limits-on-javascript-interop-calls) when you visit the second time it tries to call the `./_content/FluentUI.Demo.Shared/docs/WhatsNew.md` from the cache with is almost 41KB

**Comment by c0g1t8** [comment]
> It seems that the issue lies with the [Size limits on JavaScript interop calls](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#size-limits-on-javascript-interop-calls). When you visit for the second time, it attempts to call `./_content/FluentUI.Demo.Shared/docs/WhatsNew.md` from the cache, which is almost 41KB.

@BetoMees 

I was suspecting that it was something like that. I debugging was showing an exception `Task cancelled`  when executing
https://github.com/microsoft/fluentui-blazor/blob/17e677b0ab8ff710ec772d80094c3eeb12e5b45b/examples/Demo/Shared/Infrastructure/CacheStorageAccessor.cs#L31

The link you provided confirms that is the root cause. 🙏

**Comment by c0g1t8** [comment]
@vnbaaij @dvoituron 

I created some test spikes and it appears the best options is to disable the use of caching when running the server version of the demo site. The transfer of the cached item from the browser back to the server so it can be rendered generates extra traffic over the internet.

I believe that adding an option to the **AddFluentDemoServices()** would be best. That way it could be configured when the ServiceCollection is built. I'm thinking of an option parameter named **UseBrowserCache**. It would be set to true for a WebAssembly Host and false for a WebApplication.

Thoughts?

**Comment by vnbaaij** [comment]
That is an option. But I'd also (first) like to look at the guidance given at https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#maximum-receive-message-size wrt streaming the response. That way we can keep using the cache in both situations.

Your suggestion might be good to implement as well anyway but then specifically for when running the site in debug mode (like the error page information setup)

**Comment by c0g1t8** [comment]
>That is an option. But I'd also (first) like to look at the guidance given at https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#maximum-receive-message-size wrt streaming the response. That way we can keep using the cache in both situations.

I don't believe adding the ability to stream larger cached items would be helpful in the long run. Fundamentally, the cache storage is on the client. It does improve access time when Blazor is running in the client since it negates the need for another trip to the server once cached.  But when Blazor is running in the server, the cached item is sent from the client to the server for it to be rendered first. The rendered output is now streamed back to the client.  The same item could have been retrieved locally on the server.

IMO - If in the future the demo site is converted to a full Blazor Web App to take advantage of static SSR, how caching could be leveraged would likely require some more thought and rearchitecture.

> Your suggestion might be good to implement as well anyway but then specifically for when running the site in debug mode (like the error page information setup)

I originally discovered this issue while testing some other **MarkdownSection** fixes. I testing in the server version because it was simply faster. 

I'll submit a draft PR with an option later tdoay for review.
