### ISSUE TITLE
fix: Hide tip if the pull is not completed in PullToRefresh

### ISSUE THREAD

**Issue by f4n0** [microsoft/fluentui-blazor#1784]
# 🐛 Bug Report
When using the pull to refresh feature with the Tip hidden, if you start a refresh but not drag it far enough, the tip will remain visible

## 💻 Repro or Code Sample
Pull Down template on demo site

## 🤔 Expected Behavior
If the drag is not completed, hide the tip

## 😯 Current Behavior

https://github.com/microsoft/fluentui-blazor/assets/36199751/67c39ca1-7bd4-4aad-b8d6-3892f0b0b904

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Fix will be in v4.6.1 release. See https://preview.fluentui-blazor.net/PullToRefresh for the result
