### ISSUE TITLE
FluentFooter on Android does not stick to the bottom

### ISSUE THREAD

**Issue by michelmoorlag** [microsoft/fluentui-blazor#1798]
# 🐛 Bug Report

I have created a "Fluent Blazor Web App" using the Fluent template. I have added a Maui Hybrid project and a Razor Class Lib and moved most of the ui to the Razor Class Lib so the ui can be shared and run Fluent on all platforms
This works fine for web and iOS but on Android the footer does not stick to the bottom.

## 💻 Repro or Code Sample

[Sample.zip](https://github.com/microsoft/fluentui-blazor/files/14866269/Sample.zip)

## 🤔 Expected Behavior

I would expect the FluentFooter to stay on the bottom on all platforms, also on Android

## 😯 Current Behavior

The FluentFooter sticks to the bottom of the content and not to the bottom of the page.
![image](https://github.com/microsoft/fluentui-blazor/assets/14913939/04c2b926-1428-419e-81dd-44e5073ac1aa)

## 💁 Possible Solution

I tried to fidle a bit with the css and styles but did not find a solution. The things is in web you can right click and inspect the dom. On Android this is not possible so it is hard to see what is wrong here. Any suggestion how you can see the html code in Maui Hybrid?
Also not sure if this is a Fluent or Maui Hybrid/BlazorWebView issue ?

## 🔦 Context

We want to build a new app/web application and share the ui using Fluent ui but this is kind of an issue.

## 🌍 Your Environment

OS: Windows 11
VS: Version 17.9.5
Browser: Chrome Versie 123.0.6312.105 (Officiële build) (64-bits)
.Net 8.0.202
Microsoft.FluentUI.AspNetCore.Components 4.6.0
Android Pixel 5 api 33 emulator, but i have noticed it on other Android devices/api's too.

**Comment by vnbaaij** [comment]
> I tried to fidle a bit with the css and styles but did not find a solution. The things is in web you can right click and inspect the dom. On Android this is not possible so it is hard to see what is wrong here. Any suggestion how you can see the html code in Maui Hybrid?
> Also not sure if this is a Fluent or Maui Hybrid/BlazorWebView issue ?

Also not sure where the issue lies. As you have it  setup already, it would be helpfull if you can try to debug it. Wrt getting info from th webview, please see https://stackoverflow.com/questions/71919608/how-to-inspect-and-debug-the-maui-hybrid-blazor-webview-on-android.

**Comment by vnbaaij** [comment]
Hi, 

I found the issue...On Android the CSS `dvh` unit is apparently not supported (yet?).

If you go to `Shared\app.ccs` line 16 andchange it to ` min-height: calc(100vh - 86px);`, it starts working on android:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/5eb40804-fbaa-49a6-8798-a267a10567e8)

**Comment by vnbaaij** [comment]
ps Windows (still) works as well ater making that change:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/723bc4f8-4a32-41cc-a4da-4273807b7c70)

**Comment by michelmoorlag** [comment]
Works perfectly, Thank you so much!
Also the tip how to inspect the html code on android is very very usefull.
