### ISSUE TITLE
fix: Icon-only button not converting to icon-only loading

### ISSUE THREAD

**Issue by pmi24** [microsoft/fluentui-blazor#1801]
# 🐛 Bug Report

When an icon-only `<FluentButton>` has `Loading="true"`, the resulting button is not icon-only. It results in an asymmetrical button.

## 💻 Repro or Code Sample

```
<FluentButton Appearance="Appearance.Accent" Loading="false" IconStart="@(new Icons.Regular.Size16.ArrowDownload())" />
<FluentButton Appearance="Appearance.Accent" Loading="true" IconStart="@(new Icons.Regular.Size16.ArrowDownload())" />
```

![image](https://github.com/microsoft/fluentui-blazor/assets/164189723/abd81ddc-ab9d-4ac5-87f8-06b85a78adbd)

## 🤔 Expected Behavior

The `fluent-progress-ring` should be in the content slot, instead of the start slot when the button has no content. 

## 😯 Current Behavior

When `Loading="true"`, the `fluent-progress-ring` is always in the start slot of the `<FluentButton>`.

**Comment by dvoituron** [comment]
What version of Lib are you using?

With version 4.6, the result is correct.
![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/d49de660-34ad-4195-a082-a13935b89bdf)

**Comment by vnbaaij** [comment]
We indeed included a fix for that. See #1714

**Comment by pmi24** [comment]
Indeed, updating from 4.5.0 to 4.6.0 resolved the issue. Please excuse the oversight.
