### ISSUE TITLE
fix: FluentHeader has a 100% width without account for margines

### ISSUE THREAD

**Issue by TMUNYU** [microsoft/fluentui-blazor#1802]
# 🐛 Bug Report
Adding `FluentHeader` will cause overflows dues to the overflows

## 💻 Repro or Code Sample
```html
<FluentHeader>Header</FluentHeader>
```
## 🤔 Expected Behavior
No overflow

## 😯 Current Behavior
x axis overflow

## 💁 Possible Solution
width needs to account for the margins else we will have overflow issues.
The following proposal is for [FluentHeader.css](https://github.com/microsoft/fluentui-blazor/blob/6ce5081502dfcdcf3cf1000b1a64069a42386f8a/src/Core/Components/Header/FluentHeader.razor.css#L17)

```css
.header .header-gutters {
...
width: calc(100% - 3rem)
...
}
```

I am not convicted you actually need this width at all

## 🔦 Context
Just trying to do a simple site layout

## 🌍 Your Environment
* OS & Device: Windows 11 PC
* Browser Microsoft Edge
* .Net 8 and Microsoft.FluentUI.AspNetCore.Components Version="4.5.0"

**Comment by vnbaaij** [comment]
Sorry, it is not clear what you mean with this. See for example https://www.fluentui-blazor.net/Header which has no overflow.

Maybe post an image and code of your situation?

**Comment by vnbaaij** [comment]
Closed due to inactivity
