### ISSUE TITLE
feat: Prevent SplashScreen from getting focus

### ISSUE THREAD

**Issue by emetrix** [microsoft/fluentui-blazor#1804]
# 🙋 Feature Request

In my opinion a splashscreen should not be able to get the focus !?
When the splashscreen is displayed at application startup it gets the black focus rectangle which does not look very nice.

## 🤔 Expected Behavior

The black focus rectangle should at least not be displayed.

## 😯 Current Behavior

A SplashScreen dialog can get the focus.

## 💁 Possible Solution

Not really sure: Maybe tabindex can be ignored or the style for the focus can be changed ?

## 💻 Examples

![SplashScreen focus rectangle](https://github.com/microsoft/fluentui-blazor/assets/13239872/cd5c0990-0c61-4976-a81a-93fddd0d3182)

**Comment by emetrix** [comment]
A sample demonstrating the behaviour is available at https://github.com/emetrix/Samples.BlazorFluentUI-Splashscreen

**Comment by dvoituron** [comment]
Probably better to have a style to avoid this visual border. But to avoid accessibility issues, it could be better to keep the component focusable.

**Comment by emetrix** [comment]
As I'm not very familiar with CSS can you perhaps help me at least which element has to be styled for a splashscreen ?

**Comment by vnbaaij** [comment]
You can use the Dev Tools in your browser to find the element. Most likely will be 'fluent-dialog'

**Comment by emetrix** [comment]
If already tried (according to my sample in LoadScreen.razor.css as well as in app.css):

```
fluent-dialog:focus-visible {
    outline: none !important;
    /* outline: 3px dashed; */
    border: none !important;
}

fluent-dialog:focus {
    outline: none !important;
    /* outline: 3px dashed; */
    border: none !important;
}
```

but behaviour is still the same.

**Comment by emetrix** [comment]
Seems I've got it now:

```
fluent-dialog::part(control) {
    outline: none !important;
}
```

does the trick !

**Comment by vnbaaij** [comment]
Closing this one then.
