### ISSUE TITLE
MSBuild Error DEP1000: Cannot copy file

### ISSUE THREAD

**Issue by joshbartley** [microsoft/fluentui-blazor#1805]
# 🐛 Bug Report

Followed the Getting Started for an existing Blazor Hybrid app.

`dotnet add package Microsoft.FluentUI.AspNetCore.Components`

Added this to the index.html as it contained the blazor.webivew.js from the VS template.
`<script app-name="MyAppName" src="./_content/Microsoft.FluentUI.AspNetCore.Components/js/initializersLoader.webview.js"></script>`  

## 🤔 Expected Behavior

Project builds and can start debugging

## 😯 Current Behavior

```
DEP1000: Cannot copy file "C:\Users\me\.nuget\packages\microsoft.fluentui.aspnetcore.components\4.6.0\staticwebassets\Microsoft.FluentUI.AspNetCore.Components.lib.module.js.LEGAL.txt" to layout "C:\Users\me\source\reposMyAppName\src\MyAppName\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\wwwroot\_content\Microsoft.FluentUI.AspNetCore.Components\Microsoft.FluentUI.AspNetCore.Components.lib.module.js.LEGAL.txt". DirectoryNotFoundException - Could not find a part of the path 'C:\Users\me\source\repos\MyAppName\src\MyAppName\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\wwwroot\_content\Microsoft.FluentUI.AspNetCore.Components\Microsoft.FluentUI.AspNetCore.Components.lib.module.js.LEGAL.txt'. [0x80070003]
 
## 🌍 Your Environment

Windows 11, Visual Studio 17.9.5
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]
```
        <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.14" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.14" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="8.0.14" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
        <PackageReference Include="Microsoft.Maui.Essentials" Version="8.0.14" />
        <PackageReference Include="MudBlazor" Version="6.19.1" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.0" />
```

**Comment by vnbaaij** [comment]
Did you copy the error message? If so, there seems to be a '\' missing in the path after layout.
Not sure if that is a library issue or just something in your configuration.

**Comment by vnbaaij** [comment]
Closed due to inactivity

**Comment by joshbartley** [comment]
I think this is related to https://github.com/TobiasBuchholz/Plugin.Firebase/issues/199 as looking at the file path it's over 400 characters long including the project name I stripped out of the bug report.
