### ISSUE TITLE
fix: Event CurrentPageIndexChanged does not exist in FluentPaginator

### ISSUE THREAD

**Issue by petermanesis** [microsoft/fluentui-blazor#1808]
In documentation of DataGrid in section of FluentPaginator (https://fluentui-blazor.net/DataGrid#fluentpaginator-class) it mentions that there is a EventCallback "CurrentPageIndexChanged" but when using the FluentPaginator this event does not exists.  Current version is 4.6

**Comment by vnbaaij** [comment]
Hi,

The documentation comes directly from going through the classes with reflection and then gets the desriptions from XML comments in the source code, so pretty accurate.

The callback is there in the source: https://github.com/microsoft/fluentui-blazor/blob/6ce5081502dfcdcf3cf1000b1a64069a42386f8a/src/Core/Components/Pagination/FluentPaginator.razor.cs#L14

It gets called (if a delegate has been defined) in the `GoToPageAsync` method. That method gets called from `GotoFirstAsync`, `GotoNextAsync`, etc.

**Comment by petermanesis** [comment]
Hi Vincent,

Sorry for the trouble and the stupid "issue", I am afraid that I was checking the PaginationState object instead of Pagination, so this is way I couldn't find it. Sorry for wasting your time.
By the way I want to tell you that I love FluentUI libary. I am creating a Hybrid Blazor application with FluentUI, so as the same app to be deployed in web, android, iPhone and windows desktop. It is fantastic that with FluentUI,  I don't have to spend any time for styling and designing. I am just using FluentUI and the app is beautiful.
There are more benefits with FluentUI but I don't want to get you tired...

Thanks and Best Regards,
Petros
________________________________
Από: Vincent Baaij ***@***.***>
Στάλθηκε: Κυριακή, 7 Απριλίου 2024 11:23
Προς: microsoft/fluentui-blazor ***@***.***>
Κοιν.: petermanesis ***@***.***>; Author ***@***.***>
Θέμα: Re: [microsoft/fluentui-blazor] fix: Event CurrentPageIndexChanged does not exist in FluentPaginator (Issue #1808)


Hi,

The documentation comes directly from going through the classes with reflection and then gets the desriptions from XML comments in the source code, so pretty accurate.

The callback is there in the source: https://github.com/microsoft/fluentui-blazor/blob/6ce5081502dfcdcf3cf1000b1a64069a42386f8a/src/Core/Components/Pagination/FluentPaginator.razor.cs#L14

It gets called (if a delegate has been defined) in the GoToPageAsync method. That method gets called from GotoFirstAsync, GotoNextAsync, etc.

**Comment by vnbaaij** [comment]
No worries. Glad you found it. And happy that you like it so much. Please, don't hold back on reporting stuff. Getting things documented here is helpful for the whole community!
