### ISSUE TITLE
feat: add Year/month pick only to FluentDatePicker

### ISSUE THREAD

**Issue by Skintkingle** [microsoft/fluentui-blazor#1812]
# 🙋 Feature Request

Similar to how the FluentCalendar can have a `View=CalendarView.Months` which restricts the picker to just a Months resolution. It would be nice to have the FluentDatePicker have a similar function.

## 🤔 Expected Behavior

<FluentDatePicker @bind-Value=@MyMonthOnlyResolution View=CalendarView.Months />

## 😯 Current Behavior

Unable to do this or similar

## 💁 Possible Solution

Assuming the popup from the FluentDatePicker is a FluentCalendar, it could be as simple as passing the CalenderView to the hosted FluentCalendar

## 🔦 Context

As part of some data entry, we only need a Month in a year select, however the users currently need to pick a day in that month, for the FluentDatePicker to be happy.

**Comment by dvoituron** [comment]
This is not currently planned, mainly because the `FluentDatePicker` component displays the day of the date selected in the component. And there is currently no formatting of this date (e.g. dd-yyyy).

**Comment by Skintkingle** [comment]
Is that not something that could be added as well? When it's configured into "Month resolution", or such?

**Comment by vnbaaij** [comment]
If we allow it to only select only a month or a year, then it would not be a 'date' picker anymore. Think it would be confusing for people to have the same component do different things like that. 
I can image we add a `FluentMonthPicker` and or a `FluentYearPicker` that specifically support this scenario in the future, but is not currently in the planning. 

If we were to add such components, what would the expected data type be then? Int or string? Or DateOnly with indeed 1st of the month selected in a month picker and 1-1-xxxx in a year picker?

**Comment by Skintkingle** [comment]
I'm don't think it's that confusing. `FluentCalendar` allows to select only Month or Year and they effectively output a Date with 1 Day (or 1 Month) depending on its resolution. Instead of having different data structures. 

Arguably Your current `FluentDatePicker` should already be `DateOnly` data Type as it's not a DateTimePicker ;) so I have no objection to that change at all. I think breaking it down to primitives is a little extreme though.

I don't see an issue with the introduction of a `FluentMonthPicker` or a `FluentYearPicker` but I think it's a little over the top. That's up to you though. I would like to see this feature introduced in some manner. And I think it's reasonable to have this as an extension/configurable aspect of the `FluentDatePicker`. It would not be confusing.

**Comment by vnbaaij** [comment]
Ok, fair comment on the data type. We have that from legacy .NET 5 era (DateOnly was introduced in .NET 6). Changing it would be a breaking change which w don't want to do now.

The way it would work as described in your last paragraph makes sense. But as said, we don't have it on our list yet. We are a small team working on this as a side project. We do take PRs. Fancy submitting one? We will be happy to review and merge if standards are met, tests are provided, etc.

**Comment by michaelc06** [comment]
I needed a month picker too and ended up making a simple component using `FluentTextField` , `FluentPopover` and `FluentCalendar` for now as I don't have the time to modify the  `FluentDatePicker` or create a new component. Not all features are supported like clearing after selecting or entering via the `FluentTextField`. Happy to share the code if anyone is interested.

![image](https://github.com/microsoft/fluentui-blazor/assets/86220341/79084429-1537-48ef-b561-d46b00625c94)

![image](https://github.com/microsoft/fluentui-blazor/assets/86220341/8aa08f31-b53e-469e-bfea-fe57d8cd8d6f)
