### ISSUE TITLE
'@inject AccentBaseColor' throws error in combination with '@rendermode InteractiveWebAssembly'

### ISSUE THREAD

**Issue by michelmoorlag** [microsoft/fluentui-blazor#1815]
# 🐛 Bug Report

I saw the video about setting the theme and light/dark mode and added this code to my Blazor united test project using the fluentui template. When I set the rendermode to 'InteractiveServer it al works fine but when I use rendermode 'InteractiveWebAssembly' The page throw this error:

"Error: One or more errors occurred. (Cannot provide a value for property 'AccentBaseColor' on type 'DropdownSpace.Client.Pages.Counter'. There is no registered service of type 'Microsoft.FluentUI.AspNetCore.Components.DesignTokens.AccentBaseColor'.)"

## 💻 Repro or Code Sample

[DropdownSpace.zip](https://github.com/microsoft/fluentui-blazor/files/14914694/DropdownSpace.zip)
On the homepage with rendermode InteractiveServer it al works fine but on the counterpage with rendermode InteractiveWebAssembly it throws the error. Changing the rendermode will change the behavior (crash or not)

## 🤔 Expected Behavior

I would expect I can always inject (and use) the AccentBaseColor service independend of the rendermode.

## 😯 Current Behavior

When I combine AccentBaseColor with rendermode InteractiveWebAssembly in a razorpage/component I get this error:

"Error: One or more errors occurred. (Cannot provide a value for property 'AccentBaseColor' on type 'DropdownSpace.Client.Pages.Counter'. There is no registered service of type 'Microsoft.FluentUI.AspNetCore.Components.DesignTokens.AccentBaseColor'.)"

## 💁 Possible Solution

A workaround is to not use rendermode InteractiveWebAssembly.

## 🔦 Context

I was trying the theming possibilities of the framework in different render modes and observed this issue.

## 🌍 Your Environment

OS: Windows 11
VS: Version 17.9.5
Browser: Chrome Versie 123.0.6312.105 (Officiële build) (64-bits)
.Net 8.0.202
Microsoft.FluentUI.AspNetCore.Components 4.6.0

**Comment by vnbaaij** [comment]
You need to add 
```
builder.Services.AddFluentUIComponents();
```
to the `Program.cs` on the client side to make the services etc available on the Client side...

**Comment by michelmoorlag** [comment]
Yes this makes sense. Could have figured out my self :(

**Comment by michelmoorlag** [comment]
@vnbaaij Thinking about it, is it an idea to add this to the project template?
