### ISSUE TITLE
Freeze parameter for FluentFooter

### ISSUE THREAD

**Issue by michelmoorlag** [microsoft/fluentui-blazor#1817]
# 🙋 Feature Request

It would be very nice if the FluentFooter got a 'freeze' parameter. 

## 🤔 Expected Behavior

Now the footer is always pushed to the bottom of the content. So when the content is very long the footer will scroll out of view. This would be the behavior of the value of the freeze parameter when is set to its default value of false. When this parameter is set to true the FluentFooter should freeze to the bottom of the screen. So it is always visable and the content will scroll onder the footer.

## 😯 Current Behavior

The footer does not have a freeze parameter

## 💁 Possible Solution

see expected behavior.

## 🔦 Context

We would like to use Fluent ui both for web and in a Maui Hybrid solution. In mobile the footer is mostly frozen with a tab menu and we would like to simulate this behavior with Fluent Ui

## 💻 Examples

It is possible to simulate this behavoir by setting the body-content height to `height: calc(100vh - 86px) !important;` in app.css.

**Comment by vnbaaij** [comment]
We have no plan to implement this. It is left as something that needs to be part of the site/app design and needs to be configured/set up accordingly (which is fairly easy to do).
