### ISSUE TITLE
feat: add WYSIWYG editor

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#1818]
# 🙋 Feature Request

It would be great if this library would have some sort of WYSIWYG editor like CKEditor.

## 🔦 Context

Sometimes you'll need to format text in different styles or add basic images. It would be great if there is no need for another library which doesn't fit into fluent-ui's design scheme.

## 💻 Examples
https://ckeditor.com/ckeditor-5/demo/feature-rich/

**Comment by vnbaaij** [comment]
Hi,

We will not be including any 3rd party libraries in our package in the near future. If we choose CK, people will say 'we want TinyMCE'. If we choose tiny others will cry for some other solution. No way we can make everyone happy with this. Lots of issues wrt legal aspects involved as well. 

If we would supply something for this, it would most probably not be part of the core package but be an extension and based on Microsoft technology.

**Comment by MarvinKlein1508** [comment]
@vnbaaij I don't want CKEditor included. I just put it up as a reference.

**Comment by dvoituron** [comment]
@MarvinKlein1508 We've already had this discussion here #738 and here #359.

We believe that excellent third-party HTML editor solutions exist, and that there's no need to add a new one to this library at present. In my opinion, the main problem will be : (1) what format to propose (HTML, Markdown, ...) and (2) what functional limits to bring (bold/italic/bullets/...)

It's a huge job, and unfortunately we don't have the time to get into it right now (creation, follow-up, maintenance, Accessibility issues, etc.).

**Comment by MarvinKlein1508** [comment]
Hi @dvoituron 

surely this ain't a easy task. But this library would even benefit from a very basic editor. Sure there are plenty of editors out there but as you've mentioned they don't follow the design principle of fluent-ui.

I think even a very basic editor would be a huge benefit for this component library. With basic I mean:
- bold
- italic
- underline
- headings
- links
- lists


I think with HTML and Markdown you would have covered like most of all use-cases.

**Comment by vnbaaij** [comment]
@MarvinKlein1508 I did not assume you meant CK specifically. Just went with your example and to make clear that if we choose that one, only some would be happy.

IT is not about theuse cases you mention. That part is clear. As I sai, it is about including 3rd party libraries. For both HTML and Markdown we would need additional tools (like MarkDig) and we can't do that from a legal perspective
