### ISSUE TITLE
fix: [what is the issue? Blazor SSR CRUD Pages develop is not working with Fluent] in [where is the issue? Blazor Server Fluent Project]

### ISSUE THREAD

**Issue by marc5walt** [microsoft/fluentui-blazor#1819]
# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Sorry, but this is not an issue report we can (or want to) work with.

You expect us to help you, so we equally expect you to help us by using the template, giving us reproduction steps, etc.

Closing this one.
