### ISSUE TITLE
fix: FluentSelect not setting initial selected values correctly

### ISSUE THREAD

**Issue by OLVA1993** [microsoft/fluentui-blazor#1828]
# 🐛 Bug Report

When a SelectedOptions are deselected, the item is **added** to the list of initially selected items instead of being removed.

## 💻 Repro or Code Sample

See repository: [Fluent-Select](https://github.com/OLVA1993/fluent-select-)

When running the project navigate to the weather page

## 🤔 Expected Behavior

When an item is deselected, it should be removed from the list.

## 😯 Current Behavior

When initially 4 items were selected and we deselect 2 of them the list now contains 6 items instead of the 2 remaining items.

The list is of citites is populate on dialog opened and the selected options are set for the item it received.

![fluentselectbug-ezgif com-video-to-gif-converter](https://github.com/microsoft/fluentui-blazor/assets/83395176/b27474bd-3b6b-4436-b288-464d126ece3b)

## 🔦 Context

I have a FluentDataGrid with items of type Forecasts when clicking the update button, a Panel is opened with the context of the item of the Forecast clicked. This forecast contains a List of items Cities that are applicable to it. In the panel I would like to update the List of cities, when the panel is closed I need to save the results in a database. 

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* .NET and Fluent UI Blazor library Version 8.0.3 and 4.6.1

**Comment by vnbaaij** [comment]
You are using Resources.Cities and local defined Cities together in the EditPanel...
Changing the code to
```
 <FluentSelect TOption="City"
               Open="false"
               Id="CustomerSelectBox"
               Label="Cities:"
               Items="@Resources.Cities"
```
makes it work.
