### ISSUE TITLE
fix: NotifyFieldChanged is called Twice in FluentInputBase.ChangeHandlerAsync

### ISSUE THREAD

**Issue by Mike-E-angelo** [microsoft/fluentui-blazor#1830]
# 🐛 Bug Report

When `FluentInputBase.ChangeHandlerAsync` is called and the input is valid, it calls `SetCurrentValueAsync` [here](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Base/FluentInputBaseHandlers.cs#L34), which calls the `EditContext.NotifyFieldChanged` [here](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Base/FluentInputBase.cs#L162).  It then carries on to call `NotifyFieldChanged` again [here](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Base/FluentInputBaseHandlers.cs#L48).

This results in two notification calls in the same change. 

## 💻 Repro or Code Sample

Using a FlientTextField as such:

```
<FluentTextField Name="name" @bind-Value="Input.Name" Immediate="true" ImmediateDelay="750" Label="Name" Required Maxlength="64" />
```

After typing and the update fires, I get two calls to listeners listening to the `Name` property change.

## 🤔 Expected Behavior

Ideally, only one call should happen per control state change.

## 😯 Current Behavior

Currently two calls are made per control state change.

## 💁 Possible Solution

Reporting here to ensure I am not misunderstanding something fundamental here.

## 🔦 Context

I am learning this library and everything else has been working wonderfully. :)  Thank you for your efforts out there. 🙏

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Edge/Chrome
* .NET and Fluent UI Blazor library Version `Microsoft.FluentUI.AspNetCore.Components, Version=4.5.0.24067, Culture=neutral, PublicKeyToken=null`

**Comment by vnbaaij** [comment]
Hi,

Thanks for reporting. Good analysis and definitely a bug.

See the PR for changes made

**Comment by Mike-E-angelo** [comment]
Awesome!  Thank you @vnbaaij ... is there a pre-release feed I can try this from, by chance?  Thank you for your efforts!
