### ISSUE TITLE
fix: can't scroll on the site

### ISSUE THREAD

**Issue by Doofenshmirttz** [microsoft/fluentui-blazor#1832]
Apparently is impossible to scroll on the what's new site

**Comment by Doofenshmirttz** [comment]
The problem is only visible on Edge. Chrome working fine

**Comment by c0g1t8** [comment]
@Doofenshmirttz 

I've not been able to reproduce.  I am using an updated version of Edge Version 123.0.2420.81 (Official build) (64-bit).

Can you clear the cache and try again?

**Comment by Doofenshmirttz** [comment]
Thanks, solved it!

**Comment by Doofenshmirttz** [comment]
Thanks. Working fine now
