### ISSUE TITLE
docs: fix expand button in docs header overlapping with FluentProfileMenu

### ISSUE THREAD

**Issue by digitaldirk** [microsoft/fluentui-blazor#1838]
# 🙋 Documentation Request

When the docs website is constrained to a small width, the nav menu expander button overlaps with the profile menu.
Similar to discussion: #1837

![image](https://github.com/microsoft/fluentui-blazor/assets/22691956/ba6a7274-ae80-48b8-974f-09f725360491)

## 💁 Possible Solution
Place expander elsewhere, or rework header?

Thank you

**Comment by c0g1t8** [comment]
Looks like a duplicate of #1831

**Comment by digitaldirk** [comment]
@c0g1t8 Thank you, my bad closing.
