### ISSUE TITLE
Add link buttons

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#1843]
# 🙋 Feature Request

There should be an option to display a link as button. Sometimes you'll need to only display a link in button style to redirect the user to a new page, for example when you you want to edit or create a new user.

Right now there is no way to render `FluentButton` as `a`. In order to redirect you'll need to add an `OnClick` handler and do it it by injecting navigationmanager into the page.

For example:
https://getbootstrap.com/docs/5.3/components/buttons/#button-tags

**Comment by MarvinKlein1508** [comment]
Nevermind. This can be achieved by wrapping the a tag aroudn the button like this

```asp
<a href="/Admin/Users/Edit">
    <FluentButton IconStart="@(new Icons.Regular.Size20.PersonAdd())"
                  Appearance="Appearance.Accent">

        New User
    </FluentButton>
</a>
```

**Comment by dvoituron** [comment]
@MarvinKlein1508 You could also use `FluentAnchor`

```xml
<FluentAnchor Href="/Admin/Users/Edit"
              IconStart="@(new Icons.Regular.Size20.PersonAdd().WithColor(Color.Fill))"
              Appearance="Appearance.Accent">
    New User
</FluentAnchor>
```

**Comment by vnbaaij** [comment]
~Or you can use https://www.fluentui-blazor.net/Anchor#appearance~ @dvoituron beat me to it...😂

**Comment by MarvinKlein1508** [comment]
@dvoituron thanks for pointing this out to me. However there seems to be a difference in using the `FluentAnchor` over the `FluentButton`.

Take a look on this:

![grafik](https://github.com/microsoft/fluentui-blazor/assets/32510006/cbb66b75-bdf1-4fcd-9a64-75a409ed37a8)

code:
```asp
<FluentAnchor Href="/Admin/Users/Edit" Appearance="Appearance.Accent" IconStart="@(new Icons.Regular.Size20.PersonAdd())">
    Neuer Benutzer
</FluentAnchor>
<a href="/Admin/Users/Edit">
    <FluentButton IconStart="@(new Icons.Regular.Size20.PersonAdd())"
                  Appearance="Appearance.Accent">

        Neuer Benutzer
    </FluentButton>
</a>
```

**Comment by dvoituron** [comment]
Yep... reason why I added `.WithColor(Color.Fill)` in my example.

But you can choose you better solution :-)
