### ISSUE TITLE
How to change default color of FluentMenuButton

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#1844]
# 🙋 Documentation Request

The docs are showing how to change the default color for a `FluentMenuButton` in runtime but not how to do change the default colors.

I've tried all possible `Style` parameters already.

```asp
<FluentMenuButton @ref=menubutton Text="Optionen" Items="@items" OnMenuChanged="HandleOnMenuChanged" ButtonStyle="background-color: #D83B01;" />
```

**Comment by vnbaaij** [comment]
You need to do that in the same way, ie. with the Design Token. Look at the razor tab at https://www.fluentui-blazor.net/MenuButton#menubuttontoselectac but you would need the `HandleOnMenuChanged` code in `OnAfterRenderAsync` and use the color you want of course. 

Probably wise to read up on how the desing tokens work: https://www.fluentui-blazor.net/DesignTokens.

Closing this as it is not actionable from our side.
