### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Seanxwy** [microsoft/fluentui-blazor#1851]
# 🐛 Bug Report

## 💻 Repro or Code Sample

![image](https://github.com/microsoft/fluentui-blazor/assets/15828095/b8f7d307-ba89-4542-baaa-37d8841cf128)

![image](https://github.com/microsoft/fluentui-blazor/assets/15828095/eb7c8fd5-592b-40ce-a2d8-95b8876aeacf)

[https://github.com/Seanxwy/FluentBlazorApp1/blob/master/FluentBlazorApp1/FluentBlazorApp1/Components/Pages/Home.razor](url)
## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Please supply proper reproduction code ans steps

**Comment by Seanxwy** [comment]
@vnbaaij https://github.com/Seanxwy/FluentBlazorApp1/blob/master/FluentBlazorApp1/FluentBlazorApp1/Components/Pages/Home.razor

**Comment by Seanxwy** [comment]
Will lead to FluentDesignSystemProvider cannot take effect at the same time

**Comment by vnbaaij** [comment]
You can't use the `FluentDesignTheme` and the `FluentDesignSystemProvider` together. Remove that one from https://github.com/Seanxwy/FluentBlazorApp1/blob/32ee0d3cb5346b5a9b63b577353f47d0c2acf82f/FluentBlazorApp1/FluentBlazorApp1/Components/Routes.razor#L1 and the error is gone

**Comment by Seanxwy** [comment]
Can't be used at the same time? Can you specify details like colors and fonts when using FluentDesignTheme?

**Comment by Seanxwy** [comment]
I tried to delete FluentDesignTheme FluentDesignSystemProvider reserved. Then launch my program. The problem remains. It works as designed the first time it starts up. When I go to the page with the card component and hit F5. There was a problem. The problem is not solved. How did you close issues

**Comment by vnbaaij** [comment]
> Can't be used at the same time? Can you specify details like colors and fonts when using FluentDesignTheme? Or when using FluentDesignSystemProvider, also can more easily switch the implementation of the theme

No, you can't change those settings (like font ans size) with the FluentDesignTheme. You should use the [DesignTokens](https://fluentui-blazor.net/DesignTokens) for that.

The FluentDesignSystemProvider does not have any notion of a theme and cannot be used for that. As mentioned on the linked page:

Another way to customize the design in Blazor is to wrap the entire block you want to manipulate in a <FluentDesignSystemProvider>. This special element has a number of properties you can set to configure a subset of the tokens. Not all tokens are available/supported and we recommend this to only be used as a fall-back mechanism. The preferred method of working with the design tokens is to manipulate them from code.

**Comment by Seanxwy** [comment]
Globally configures color, spacing, and font-size related content. I can see the FAST case.
So how should DesignTokens on blazor be used? The documentation is not clear

**Comment by vnbaaij** [comment]
What do you mean with 'I can see the FAST  case'? 

You need to use the tokens as described in the https://fluentui-blazor.net/DesignTokens#using-design-tokens-from-code section. You can do that in OnAfterRenderAsync in MainLayout. See the the demo site source code (in the examples folder here in the repo) for more reference.

**Comment by Seanxwy** [comment]
Well. Let me look for examples. See the bottom should be correct to operate. I just wanted to set some colors and font sizes, spacing and things like that globally.

**Comment by vnbaaij** [comment]
I understand that you want to do that. 

But also please understand that we support the Fluent Design System, we try to follow that closely. We are not, and are not trying to be, a CSS framework like Bootstrap or Taiilwind
Changing font an size will quickly make you 'break' the system. That is the main reason we do not make it too easy to change everything.

**Comment by Seanxwy** [comment]
I really understand that Fluentui-blazor is based on Fluent. Our design is also based on the Fluent design system to design. However, we have some differences from the default in some colors, fonts, and margins. Because our system is implemented through configuration. To make our system look more comfortable and in line with customer expectations

**Comment by Seanxwy** [comment]
For example, the default font is 14px and our design is 15px. There are lots of differences like that. Our design is also strictly following Fluent's design specifications. But we have to adapt according to the customer scenario and system experience.

**Comment by Seanxwy** [comment]
We also plan to continue Fluent's design system on MAUI BLAZOR. So hopefully we can get support in this area. This allows us to develop more good cases

**Comment by vnbaaij** [comment]
And you can definitely do that with the DesignToken implementation we have in the library

**Comment by Seanxwy** [comment]
I got the code and couldn't find the application in the example. I still don't know how to use DesignTokens to achieve my needs, I hope there is a similar example to help other developers with similar needs like mine. It's also good for everyone to promote Fluentui-blazor.

**Comment by vnbaaij** [comment]
Look, I am all about making you an others) successful with the library and willing to help. I'm doing nothing else but promoting it 
But I am not going to write your code for you. Show me what you have tried. What part is unclear, etc.

**Comment by Seanxwy** [comment]
@vnbaaij 
I don't really understand why use FluentDesignSystemProvider can be a problem. And do you recommend I use DesignTokens, about FluentDesignSystemProvider instructions are included in the document, use very convenient. Although DesignTokens has a lot of description, it is very unclear. FluentDesignSystemProvider can be set for global. It seems that DesignTokens can only be set for one element or component. There are no specific examples to show that DesignTokens is more flexible and convenient. If officials don't think is I use the relevant problems caused, do not recommend using FluentDesignSystemProvider, why do they provide the usage. If this is provided, then the issue should be a bug.

**Comment by Seanxwy** [comment]
![image](https://github.com/microsoft/fluentui-blazor/assets/15828095/79d8fda0-af0c-489b-954a-f3f9a006b72b)

I tried to code it according to the documentation, but it didn't work

**Comment by vnbaaij** [comment]
Well, you can see why using it is a problem in your usecase. It does not work well together with other components (like the FluentDesignTheme). The component is there because it is present in the web components script. 
We say in the docs that it should only be used as a fallback mechanism. We can't just remove it because that would be a breaking change. Other users may be relying on it to be there.

**Comment by Seanxwy** [comment]
I can understand the differences that need to be kept in the FluentUI-Blazor iteration because of Fast. However, an effective Demo should be provided for DesignTokens. I tried it as described in the documentation. It really didn't work.
Due to the lack of documentation, I don't know what went wrong with my code. It looks fine, compiles and runs, but it doesn't have the desired effect at all

**Comment by vnbaaij** [comment]
> ![image](https://private-user-images.githubusercontent.com/15828095/322257468-79d8fda0-af0c-489b-954a-f3f9a006b72b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwODI5NTAsIm5iZiI6MTcxMzA4MjY1MCwicGF0aCI6Ii8xNTgyODA5NS8zMjIyNTc0NjgtNzlkOGZkYTAtYWYwYy00ODliLTk1NGEtZjNmOWEwMDZiNzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDA4MTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MzA5NzJlNDkzNGY2MmI3ZGRjZmIyZjljYTM2YTdkYjMwMGJiZjg0ODZhMTZmZGNhYWFhNWFkZTlmN2NjZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JQ1BuA9Pey5PIDgjTuU4EPuqrltj_lt0WASF1JJHDMk)
> 
> I tried to code it according to the documentation, but it didn't work

Look at https://www.fluentui-blazor.net/DesignTokens#using-design-tokens-from-code and see where is says:

```
// If you would like to change the BaseLayerLuminance  value for the whole site, you can use the WithDefault method
await BaseLayerLuminance.WithDefault((float)0.15);
```
That is what you need/want to use in your case. Don't set the value for a specific element but for the whole design system use

**Comment by Seanxwy** [comment]
![image](https://github.com/microsoft/fluentui-blazor/assets/15828095/e3538bd4-8f2e-460b-aeaf-e40b133559f5)

I'll do what you said. Write the corresponding code in the OnAfterRenderAsync method of MainLayout. But nothing has changed in operation.

**Comment by vnbaaij** [comment]
Is it in the repo you provided earlier? I don't see it so cant reproduce then...

ps please don't use images for code. Can't copy/paste from those. Just place the text here in three ` chararcters to format as a code block (like I did in my previous comment)

**Comment by Seanxwy** [comment]
I'm sorry. I've updated the code base now

https://github.com/Seanxwy/FluentBlazorApp1/blob/master/FluentBlazorApp1/FluentBlazorApp1/Components/Layout/MainLayout.razor

**Comment by vnbaaij** [comment]
I'll take a look later. I'm pretty sure it has to do with SSR being used (as Blaor does by default). The `OnAfterRenderAsync` will not gelled called.

**Comment by Seanxwy** [comment]
I'm using Auto Render, so I'm bound to run into SSR, Server, and Wasm. I hope it can be resolved soon

**Comment by Seanxwy** [comment]
@vnbaaij Can you use DesignTokens as parameters to FluentDesignTheme? This can be very convenient and easy to use

**Comment by vnbaaij** [comment]
No, that is not possible. Could be a nice addition indeed. Will put it on the ToDo list

**Comment by Seanxwy** [comment]
Anyway, I believe you will have a good solution, and I hope it can be fixed in the next version release

**Comment by vnbaaij** [comment]
For getting the design tokes to work in SSR mode, you'll have to revert to javascript. What you can do to make it work is:
1) Add a `MainLayout.razor.js` file which contains:
```
import {
    baseLayerLuminance,
    typeRampBaseFontSize,
    accentBaseColor,
    direction,
    SwatchRGB,
    parseColorHexRGB
} from '../../_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js';

export function onLoad() {
    baseLayerLuminance.withDefault(0.23);
    typeRampBaseFontSize.withDefault('20px');
    accentBaseColor.withDefault(SwatchRGB.from(parseColorHexRGB('#cd00ab')));
    direction.withDefault('rtl');
}
```
2) In `Mainayout.razor` add:
```
<FluentPageScript Src="/Components/Layout/MainLayout.razor.js"></FluentPageScript>
```

This will give you:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/6642bcc2-a324-4e96-81d3-bac95f01fab3)

In the current version of the library the `parseColorHexRGB` function is not yet available (it will be in the next release). Till then you would need to use `SwatchRGB.create(0.x, 0.y, 0.z)` where x,y and z represent the amount of R, G and B you want to use between 0 (= 0 in dec / 00 in hex) and 1 (=255 in dec / FF in hex)

**Comment by Seanxwy** [comment]
Reverting to js is very inelegant and lame. It wouldn't be as elegant as adding the DesignTokens parameter to FluentDesignTheme. If I had to do it in js, I would choose to do it directly in the style. In the actual development of the project, there is still a lot of custom styling that needs to be done to handle the details. So why go for the crappy js approach. The way I currently handle this is to create a new app.css and set the corresponding value in the body style, something like this:

``` 
@import '/_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css';

body { 
--body-font: "Segoe UI Variable", "Segoe UI", sans-serif;
--type-ramp-base-font-size:15px;


font-family: var(---body-font); 
font-size: var(--type-ramp-base-font-size); }

```

I highly recommend adding the DesignTokens parameter to FluentDesignTheme for uniformity, as it allows c# to control it dynamically and is very elegant.

**Comment by vnbaaij** [comment]
> Reverting to js is very inelegant and lame. It wouldn't be as elegant as adding the DesignTokens parameter to FluentDesignTheme. If I had to do it in js, I would choose to do it directly in the style. 

 We are wrapping the DesignToken implementation from the web components **script**. It is always calling into js at a certain moment. So when you want to call our Blazor `AccentBaseColor.WithDefault...`, that also cannot be done until `OnAfterRenderAsync` is executed. Because of SSR we **CAN NOT** use Blazor to call into js because `OnAfterRenderAsync` **DOES NOT** get called. 

>In the actual development of the project, there is still a lot of custom styling that needs to be done to handle the details. So why go for the crappy js approach. The way I currently handle this is to create a new app.css and set the corresponding value in the body style, something like this:
> 
> ```
> @import '/_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css';
> 
> body { 
> --body-font: "Segoe UI Variable", "Segoe UI", sans-serif;
> --type-ramp-base-font-size:15px;
> 
> 
> font-family: var(---body-font); 
> font-size: var(--type-ramp-base-font-size); }
> ```
> 
Yes, for a number of tokens that is an alternative approach as well. But not all/every token just translate into a CSS variable. There are alsos thing like subscribing to changes of values involved. Or things like changing the accent base color which needs to be reflected in at least 4 different CSS variables.

> I highly recommend adding the DesignTokens parameter to FluentDesignTheme for uniformity, as it allows c# to control it dynamically and is very elegant.
For SSR this will **not** be a viable option because, again, you can not call into javascript. 


PS, please refrain from using terms lake 'lame' and 'crapy'. Thanks.

**Comment by vnbaaij** [comment]
It 100% works.
If you are using auto rendermode, `MainLayout needs to be in the Client project. Did you move it there...?

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/90e17e5b-2f5a-49f1-8291-630a12720ffa)

**Comment by Seanxwy** [comment]
MainLayout to be moved to Client? Seems to have found the problem. I did not move to the Client project. Thanks for the heads up.

**Comment by Seanxwy** [comment]
I think I have found a solution to my problem. Hopefully in the future there will be a better program that can support SSR. thank you very much for your patience. Much appreciated.

**Comment by iamshen** [comment]
> MainLayout to be moved to Client? Seems to have found the problem. I did not move to the Client project. Thanks for the heads up.

The project template `MainLayout` generated according to the blazor web app (auto server and client) is located in server-site /Components/Layout.
Why should it be moved to Client ? 
This issue doesn't seem to mention why, or maybe I'm just missing the point.

**Comment by iamshen** [comment]
> > MainLayout to be moved to Client? Seems to have found the problem. I did not move to the Client project. Thanks for the heads up.
> 
> The project template `MainLayout` generated according to the blazor web app (auto server and client) is located in server-site /Components/Layout. Why should it be moved to Client ? This issue doesn't seem to mention why, or maybe I'm just missing the point.

Alright, I understand now why this issue is occurring. In the context of the problem I'm facing:

When creating a `Blazor Web App`, there's an option called `Interactivity location`:

- `Global`: This places the generated `MainLayout` in server-side``/Components/Layout`.
- `Per page/component`: The `MainLayout` will be located in `/Layout` on the client-side.

I've noticed that only when selecting Per page/component, certain components won't trigger the error mentioned in the issue title.
