### ISSUE TITLE
FluentDesignSystemProvider cause abnormal card component

### ISSUE THREAD

**Issue by Seanxwy** [microsoft/fluentui-blazor#1853]
# 🐛 Bug Report

After using FluentDesignSystemProvider card is unusual, to the normal page cannot use Design tokens associated Settings. This can be used if other pages without card components are reloaded by pressing F5. If again jump to have card components page, press F5 again, after FluentDesignSystemProvider Settings will not take effect. You can also see the browser error Uncaught RangeError: Maximum call stack size exceeded

![image](https://github.com/microsoft/fluentui-blazor/assets/15828095/8a3c3772-69f3-4169-b03e-583c16fd2be6)

[https://github.com/Seanxwy/FluentBlazorApp1/blob/master/FluentBlazorApp1/FluentBlazorApp1/Components/Pages/Home.razor](url)

Similar questions
#1851 
## 💻 Repro or Code Sample

[[https://github.com/Seanxwy/FluentBlazorApp1/blob/master/FluentBlazorApp1/FluentBlazorApp1/Components/Pages/Home.razor](https://github.com/microsoft/fluentui-blazor/issues/url)](url)

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
See my comment on #185. Not a library issue. Do not use the FluentDesignSystemProvider for those changes you want
