### ISSUE TITLE
FluentCalendar behaves incorrect when setting Culture

### ISSUE THREAD

**Issue by vrassouli** [microsoft/fluentui-blazor#1854]
# 🐛 Bug Report
When setting `Culture` property of the `FluentCalendar`, it does not behave correctly. Infact, after reviewing the source code, I noticed that it uses the `Culture` property only for looking up the names (names of days and monthes) and not for the calulations.
 
## 💻 Repro or Code Sample

`<FluentCalendar Culture="_culture"></FluentCalendar>`
`@code
{
    private CultureInfo _culture = new CultureInfo("fa-IR");
}`

## 😯 Current Behavior

The provided code, produces the following output:

![image](https://github.com/microsoft/fluentui-blazor/assets/4676021/67a38289-1462-4185-adf6-87d29800fcf1)

Date of today (int this output) is 04/14/2024 in Gregorian calendar, which equals to 01/26/1403 in Persian calendar.

As you see in the image:

1. the year is still 2024
2. month name is in Persian, but the name 'نیر' is the 4th month
3. the calendars first day of month displays 13

## 🤔 Expected Behavior

1. The year should display 1403
2. Month name should display 'فروردین'
3. First day of month should be 1

## 💁 Possible Solution

The calculations should use the `Calendar` property of the `CultureInfo`.
For example the `GetMonthNameAndYear` method of the `CalendarExtended` class is implemented as following:
`var result = $"{GetMonthName(Date)} {Date.Year}";`
and should be changed to:
`var result = $"{GetMonthName(Date)} {Culture.Calendar.GetYear(Date)}";`

## 🔦 Context
For multi-language applications, to support better user experience, it's vital to make use of the features provided by the CultureInfo and the Calendar

## 🌍 Your Environment
Windows 11, Android, iOS
Edge, Chrome, Firefox

**Comment by vrassouli** [comment]
By the way, I can fix it and do a PR if required.
Thanks

**Comment by vnbaaij** [comment]
As you understand the intricacies of such a calendar **much** better than we can, yes please supply a PR for this!

Would be extra great is you can also add some unit tests for those cultures so we can monitor if we don't break stuff in the future (whichever culture we use).

**Comment by dvoituron** [comment]
@vrassouli I agree with Vincent. It would be great to offer a PR that manages this culture too.

**Comment by vrassouli** [comment]
I'd be glad to
I think it would be better to have some extension methods for DateTime to handle the calculations with the CultureInfo.
If you agree, I will extend the DateTimeExtensions class with the required methods

**Comment by dvoituron** [comment]
Sure but to include in the component. If I correctly understand, depending of the Culture, the display values must be adapted. 

Correct ?

**Comment by vrassouli** [comment]
For example, there is a method named FirstDayOfMonth in FluentCalendar.razor.cs file, which returns the first day of month (and not using the culture)
This method should be replace with already-existing StartOfMonth extension method of the DateTimeExtensions, which uses CultureInfo.
As I see, StartOfMonth is implemented, but not referenced anywhere.
I've not reviewd all the methods yet, but some required ones may be already implemented and some might not.

If you agree, I want to use these extensions and implement any missing ones.

**Comment by dvoituron** [comment]
Yes. Sure. The best is to create or adapt the code and we will discuss in the PR with the concrete code. 

We trust in you.
