### ISSUE TITLE
feat: add [elevation] to/in [Most of the Components]

### ISSUE THREAD

**Issue by sardar97** [microsoft/fluentui-blazor#1869]
I would like to see elevation property on fluent ui components like the mudblazor have done.
adding elevation property for the components would really helpful specifically for (FluentCard,FluentSelect).

**Comment by vnbaaij** [comment]
We are not planning on adding any specific functionality for that atm because most web components don't expose it. 

You can use it on components that do have it by modifying their outputted css variables.
