### ISSUE TITLE
fix: data picker calendar popup getting cut off

### ISSUE THREAD

**Issue by swilkodev** [microsoft/fluentui-blazor#1875]
# 🐛 Bug Report

Data picker calendar pop-up shows with top cut-off when placed on a Fluent Tab component.

![image](https://github.com/microsoft/fluentui-blazor/assets/61414309/a97c4abb-2ff8-4227-8568-0eefa3e32a64)

## 💻 Repro or Code Sample

See repo. https://github.com/swilkodev/fluentui-date-picker

Date 1 calendar popup outside of tab component will always show correctly. Date 2 calendar popup will show correctly when the app is only full screen. Date 3 calendar popup will always show with top cut-off.

## 🤔 Expected Behavior

Calendar pop up should display in full.

## 😯 Current Behavior

Calendar pop up is cut-off.

## 🌍 Your Environment

OS & Device: [VS 2022 Preview, Win11 ]
Browser [Edge]
.NET and Fluent UI Blazor library Version [.NET 8.0.300-preview.24203.14 Fluent 4.6.1]

**Comment by vnbaaij** [comment]
Isn't that just a case of the AreaRestricted: https://fluentui-blazor.net/Card#arearestrictedexampl

**Comment by swilkodev** [comment]
@vnbaaij Yes your right.... I forgot about that setting, that fixed it. Thanks for the prompt reply.

**Comment by dvoituron** [comment]
As Vincent explained, you need to add `AreaRestricted="false"` to solve your problem.

Example:

```html
<FluentCard Style="width: 200px; height: 200px;">
    <h3>Hello</h3>
</FluentCard>
<FluentCard Style="margin: 16px 0; padding: 16px; width: 1000px; height: 500px;" AreaRestricted="false">  <!-- 👈 -->
    <FluentDatePicker Label="Date1" />
    <FluentTabs ActiveTabId="tab-1">
        <FluentTab Label="Tab-1" Id="tab-1">
            <FluentDatePicker Label="Date2"/>
        </FluentTab>
        <FluentTab Label="Tab-2" Id="tab-2">
            <div>
                <strong>Select</strong>
                <FluentRadioGroup TValue="string">
                    <FluentRadio Value="@("One")">One</FluentRadio>
                    <FluentRadio Value="@("Two")">Two</FluentRadio>
                </FluentRadioGroup>
                <FluentDatePicker Label="Date3"/>
            </div>
        </FluentTab>
    </FluentTabs>
</FluentCard>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/d2ab34b7-80db-4862-996b-8f321860341b)
