### ISSUE TITLE
Replacing default font

### ISSUE THREAD

**Issue by grumpykiwi** [microsoft/fluentui-blazor#1880]
Hi

Our design department has asked that I replace the font on a site I built with Fluent with the Montserrat font.

I have tried adding the font declaration in app.razor

```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,400;0,700;1,900&display=swap" rel="stylesheet">
```
 And then overriding the --body-font variable in app.css

```
:root {
	--body-font: 'Montserrat', sans-serif;
}
body {
	font-family: "Montserrat"!important;
}
```

Unfortunately I get sporadic replacement of Segoe UI.   The class "fluent-nav-text" for example, seems to completely ignore the new font.

Am I not doing this right? I have googled for a solution but have not found anything that works consistently across the entire site.

Any help is greatly appreciated.

**Comment by vnbaaij** [comment]
Hi,

You need to make this change by using the DesignTokens. The web components use these to make changes not just to CSS variables, but also do other internal housekeeping (like notifying components of changes). We have implemented the support for DesignTokens on the C# side as well.

There is an example at https://www.fluentui-blazor.net/DesignTokens#using-design-tokens-from-code. In fact, there is a sepecific line in that code that sets the font for 1 button. In your case however, you would want to use the `WithDefault` method to set it for the whole application.

**Comment by vnbaaij** [comment]
Closing this as proposed olution works on the demo site.
