### ISSUE TITLE
feat: add default tab displayed on page load

### ISSUE THREAD

**Issue by tbasallo** [microsoft/fluentui-blazor#1882]
# 🙋 Feature Request

Ability to set the active tab when the page loads. I tried using various documented methods but none seem to work for page load.

With and without @ref

I tried setting the tab in OnInit, AfterRender and ParameterSet, with and without @ref, using the method and just the ID. With and without bind-

```
    <FluentTabs @bind-ActiveTabId="@activeid" @ref="tabs">
        <FluentTab Label="Attendance" Id="tab-1">
        <FluentTab Label="Attendance" Id="tab-2">

  await tabs!.GoToTabAsync("tab-2");
activeid = "tab-2"

```

I am not sure it's supported.

.net 8
Fluent UI: 4.6

**Comment by vnbaaij** [comment]
You almost found it! 😀

See this example: https://www.fluentui-blazor.net/Tabs#extracontent (set the `ActiveTab` on `FluentTabs`)

**Comment by tbasallo** [comment]
That's odd. I am ~~100%~~ (now) 99% sure I did that, because it makes perfect sense...

As always thanks for the quick response.
