### ISSUE TITLE
fix: [Uncaught RangeError: Maximum call stack size exceeded] when using FluentDesignSystemProvider together with FluentCard

### ISSUE THREAD

**Issue by awlc** [microsoft/fluentui-blazor#1886]
# 🐛 Bug Report

As mentioned on title, when using FluentDesignSystemProvider with a parameter like AccentBaseColor="#123456", together with FluentCard, it generates js error [Uncaught RangeError: Maximum call stack size exceeded].

## 💻 Repro or Code Sample
in MainLayout.razor
```
@inherits LayoutComponentBase

<FluentDesignSystemProvider AccentBaseColor="#6f9f8f">
    <FluentLayout>
        <FluentHeader>
            <Header />
        </FluentHeader>

        <FluentStack Orientation="Orientation.Horizontal" Width="100%">
            <div>
                <NavMenu />
            </div>
            <div style="width: 100%;">
                <div>
                    <FluentBodyContent>
                        @Body
                    </FluentBodyContent>
                </div>
            </div>
        </FluentStack>
    </FluentLayout>
</FluentDesignSystemProvider>

<FluentToastProvider />
<FluentDialogProvider @rendermode="InteractiveServer" />
<FluentTooltipProvider />
<FluentMessageBarProvider />

<div id="blazor-error-ui">
    An unhandled error has occurred.
    <a href="" class="reload">Reload</a>
    <a class="dismiss">🗙</a>
</div>
```

then in a component when page is loaded the first time (such as Home.razor), add
```
<FluentCard>
    <h2>Hello, world!</h2>
    <FluentButton Appearance="Appearance.Neutral">Neutral</FluentButton>
    <FluentButton Appearance="Appearance.Accent">Accent</FluentButton>
    <FluentButton Appearance="Appearance.Lightweight">Lightweight</FluentButton>
    <FluentButton Appearance="Appearance.Outline">Outline</FluentButton>
    <FluentButton Appearance="Appearance.Stealth">Stealth</FluentButton>
</FluentCard>

```

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/8199924/6b158b65-af7b-4b0a-b665-ee86a9a9b86c)

## 🌍 Your Environment

.NET 8, BlazorServer (MainLayout static SSR)

**Comment by vnbaaij** [comment]
This has been discussed before. 

We advise to not use the FluentDesignSystemProvider. It is an older (deprecated) component. Use the design tokens to set the color as shown on the demo site page https://www.fluentui-blazor.net/DesignTokens

**Comment by awlc** [comment]
Thx for the update.

I tried using Design Tokens by code to change the global Accent color using AccentBaseColor.WithDefault() but the problem is that the default blue color will always be shown first.  Although it's just like a flick in about 1/3 of a second but that effect isn't as good as using FluentDesignSystemProvider.  Are you guys having plan to remediate this?

**Comment by vnbaaij** [comment]
We have a solution for that already by using the `FluentDesignTheme` component and the `loading-theme` web component.  When using that, you can specify the accent color on the the itself. You don't need to use the DesignToken then. See See https://www.fluentui-blazor.net/DesignTheme and specifically the [How to remove the "bright flash" on loading](https://www.fluentui-blazor.net/DesignTheme and #how-to-remove-the-%22bright-flash%22-on-loading) part.

**Comment by awlc** [comment]
Thank you thank you thank you!!!
Just tried and this works great!
Very much appreciated with the work from you guys.
Oh and praised for your quick response too.
Keep up the great work!
