### ISSUE TITLE
fix: @bind-Value doesn't update the UI when changing Items at the same time in FluentCombobox

### ISSUE THREAD

**Issue by haefele** [microsoft/fluentui-blazor#1900]
# 🐛 Bug Report

I'm using the `FluentCombobox` to display a list of strings - in my case, a list of databases.
Additionally, I have a button to create a new database, which should automatically be selected afterward.
Unfortunately, adding a new database to the `Items` and then setting the `@bind-Value` doesn't update the UI correctly.

The `FluentCombobox` still displays the previously selected value.

## 💻 Repro or Code Sample

```razor
<FluentCombobox Items="@Databases" @bind-Value="@SelectedDatabase" Label="Database"></FluentCombobox>
<FluentButton OnClick="@CreateNewDatabase">Create new database</FluentButton>
```

```csharp
public string[] Databases { get; set; } = ["postgres", "some_database", "warehouse", "messenger"];
public string? SelectedDatabase { get; set; }

private void CreateNewDatabase()
{
    // Simulate creating a new database
    var newDatabase = Random.Shared.NextInt64().ToString();
     
    // After it was created, add it to the list and select it
    Databases = [..Databases, newDatabase];
    SelectedDatabase = newDatabase;
}
```

## 🤔 Expected Behavior

The newly created database should be selected in the `FluentCombobox`.

## 😯 Current Behavior

The previously selected database is still shown in the UI, even tho the `SelectedDatabase` property contains the new database.

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Browser Microsoft Edge
* .NET SDK 8.0.204 and Fluent UI Blazor library Version 4.6.1

**Comment by vnbaaij** [comment]
I think the error is in line 339 in `ListComponentBase.razor.cs` (`OnParameterSet`). Currently it reads:

```
if (InternalValue is null && Value is not null ) // || InternalValue != Value)
```

No, we do not have any idea anymore why that last part is commented out 🤷‍♀️.

If I change it to 
```
 if (Value is not null &&  (InternalValue is null || InternalValue != Value))
```

Your code works flawlessly. All tests still pass as well, so I t'm going to check this in for the next release.

**Comment by haefele** [comment]
What a quick turnaround time. Amazing. Thank you very much!
