### ISSUE TITLE
fix: Button for responsive menu overlaps with profile menu in demo website

### ISSUE THREAD

**Issue by thomas-erdoesi** [microsoft/fluentui-blazor#1907]
# 🐛 Bug Report

When reducing the width of the browser window to switch to the responsive menu, the menu button appears right on top of the profile menu.

## 💻 Repro or Code Sample

Open the demo website and reduce the width of the browser window. The menu button on the top right of the page will appear on top of the profile menu.
![image](https://github.com/microsoft/fluentui-blazor/assets/32267796/9a11e671-82d9-486b-b4da-051284410dd3)

## 🤔 Expected Behavior

The right margin of the header should be adjusted to make some space for the additional button when switching to the responsive menu.

## 😯 Current Behavior

The menu button on the top right of the page appears right on top of the profile menu (see screenshot above).

## 💁 Possible Solution

The right margin of the FluentHeader component should be adjusted to make some space for the additional button when switching to the responsive menu.

## 🔦 Context

It's just an unexpected UI behavior that should be fixed, because developers might use this code as a starting point for their own projects.

## 🌍 Your Environment

Windows 11 / Microsoft Edge

**Comment by vnbaaij** [comment]
This is already fixedfor the next release...
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/c61e1ad8-f24d-437a-bf1f-80a73d64b16a)
