### ISSUE TITLE
GlobalState is set to default on wasm startup

### ISSUE THREAD

**Issue by StephenOTT** [microsoft/fluentui-blazor#1908]
Using 4.6.1

using wasm, if you inject Global state such as:

`@inject GlobalState Theme`

and then 

```csharp
...
    protected override Task OnAfterRenderAsync(bool firstRender)
    {
        Console.WriteLine(Theme.Luminance);
        return base.OnAfterRenderAsync(firstRender);
    }
...
```

When the app first starts up, the Luminance is set to the default value instead of the stored local storage value.

Once i navigate to a page or component that contains the `FluentDesignTheme` component then the GlobalState contains the proper luminance value.

I would add `FluentDesignTheme` into the main layout so it auto-loads on startup, but other issues have directed to NOT put the FluentDesignTheme into the mainlayout.

---

and in the event that my usage above is incorrect; I am looking for the way i can programatically determine if i am in Light or Dark mode.

**Comment by vnbaaij** [comment]
Luminanceneeds to have a default value. We set it to LightMode. We can only change it once JavaScript is available so in `OnAfterRenderAsync`

You can use the loading-theme webcomponent to read/work with it earlier. See https://www.fluentui-blazor.net/DesignTheme for more information

**Comment by StephenOTT** [comment]
@vnbaaij it would seem like GlobalState should have a method that provides similar functionality to: https://github.com/microsoft/fluentui-blazor/blob/eea55eae82cb28d8b1e009bb80e62f6a2e68fb61/src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.cs#L196-L204  so we can get the state earlier.

This seems to be a gap: several issues state not to put the FluentDesignTheme into the main layout, but in order for the GlobalState to have an actual valid value we need FluentDesignTheme to be active.  But FluentDesignTheme is only used (currently) to edit the theme configs.

If a user never navigates to a page with FluentDesignTheme, how would the page ever detect programmatically that the theme is in Light vs dark mode?

**Comment by vnbaaij** [comment]
We can't get the mode earlier. As you can see in line 196, we need JS to get the luminance. 

As said in my previous comment, you can use the **loading-theme** web component. See https://www.fluentui-blazor.net/DesignTheme#how-to-remove-the-%22bright-flash%22-on-loading

**Comment by StephenOTT** [comment]
How does having the loading theme in the index.html provide general component access to which luminance/isDark status?

**Comment by vnbaaij** [comment]
It doesn't but together with the `<fluent-design-theme>` **web component** it can read from local storage and manipulate the Design Tokens **before** Blazor starts.

**Comment by dvoituron** [comment]
@StephenOTT 
> If a user never navigates to a page with FluentDesignTheme, how would the page ever detect programmatically that the theme is in Light vs dark mode?

You can also capture `OnLoaded` or `OnLuminanceChanged` events to be informed of theme changes.
```xml
<FluentDesignTheme Mode="@DesignThemeModes.System" 
                   OnLoaded="@(e => Console.WriteLine(e.Mode))" 
                   OnLuminanceChanged="@(e => Console.WriteLine(e.Mode))" />
```

**Comment by StephenOTT** [comment]
@dvoituron would this be done on any page where we need this info? Or you expect it to be configured at a mainlayout/app level and the info stored in a global singleton.

**Comment by dvoituron** [comment]
You'll find the explanation [on this page](https://www.fluentui-blazor.net/DesignTheme): 
1. You have the Blazor component `FluentDesignTheme` to manage the theme in Blazor
2. But you also have the web component `fluent-design-theme` that can be used before Blazor loads all the assemblies.

## FluentDesignTheme
**FluentDesignTheme** is a Blazor component. It comes with an additional web component (fluent-design-theme) that can be used in HTML before Blazor has started and components are rendered. This avoids a "flash" of dark or white at page startup. Particularly so when using a WebAssembly project, which in general requires more time to download the assemblies needed to run the application.

Example in HTML
```xml
<fluent-design-theme mode="dark" primary-color="word" />
<fluent-design-theme mode="light" primary-color="#ff0000" />
```

Example in Blazor
```xml
<FluentDesignTheme Mode="DesignThemeModes.Dark" OfficeColor="OfficeColor.Word" />
<FluentDesignTheme Mode="DesignThemeModes.Light" CustomColor="#ff0000" />
```

**Comment by dvoituron** [comment]
Is it not possible for you to use `OnLuminanceChanged` to get the applied `Mode`? What is the problem about that?
Of course, this value will be received after the Blazor loading, but before that you don't have a simple way to have this info (except using JavaScript).

```xml
<FluentDesignTheme Mode="@DesignThemeModes.System" 
                   OnLoaded="@(e => Console.WriteLine(e.Mode))" 
                   OnLuminanceChanged="@(e => Console.WriteLine(e.Mode))" />
```

**Comment by StephenOTT** [comment]
@dvoituron Mode is System, Light and Dark.  Where System could mean Light or Dark.  One must use isDark to figure out the final condition.

When rendering how would you determine the difference between the default Luminance and the actual luminance?

GlobalState is already a state container holding this info.  But it would seem we then need to duplicate the usage of GlobalState to re-store the same information and then start tracking changes and loads.

If you had a overlay such as:

```
<FluentOverlay Visible="true" Opacity="0.5" Dismissable="false" FullScreen="true" BackgroundColor="@(()=> isDark == true ? "#someDarkColor" : "#someLightColor")">

```

The isDark custom method would not have to also implement on the page the FluentDesignTheme, a additional handler to luminanceChanged, a storage for updating this value and likely  a if statement around the overlay to not load the value until the isDark value has been set / equals not null.

If this is correct, is this not excessive work for a extremely common need to know globally at any time "Is the app in light or dark mode?"
