### ISSUE TITLE
feat: Provide fragment to extend Profile Menu Button

### ISSUE THREAD

**Issue by StephenOTT** [microsoft/fluentui-blazor#1910]
Consider the azure admin portal, where a similar Profile Menu is shown but with additional contextual info (the current username/email/ID and tenant) to the left of the profile menu button.

Would be good to have the ability to add a fragment to the left/right of the profile menu and have the clickable area be part of the extended fragment.

**Comment by dvoituron** [comment]
You can do that using a code like this:

```html
<FluentStack VerticalAlignment="VerticalAlignment.Center">
    <div>
        <FluentLabel Style="font-size: 11px; line-height: 14px;">Denis Voituron</FluentLabel>
        <FluentLabel Style="font-size: 11px; line-height: 14px;">Microsoft</FluentLabel>
    </div>
    <FluentProfileMenu Image="@DataSource.ImageFaces[3]"
                        Status="@PresenceStatus.Available"
                        TopCorner="true"
                        Initials="OS"
                        FullName="Olivia Smith"
                        EMail="sam@my-company.com"
                        Style="min-width: 330px;">
                        <HeaderTemplate><FluentLabel Typo="Typography.Body">My Company Corp</FluentLabel></HeaderTemplate>
                        <FooterTemplate></FooterTemplate>
    </FluentProfileMenu>
</FluentStack>
´``

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/a4942d13-f5cf-4944-bcc5-9d1bfb2fac7e)

**Comment by StephenOTT** [comment]
@dvoituron  agreed that is an option.  What i was looking for was to wrap the "Denis" text into the clickable area.  So the user could click on the Profile head or the text (similar to azure admin ui)

**Comment by vnbaaij** [comment]
Could be a nice option to add some parameter like `DisplayTemplate` (of type RenderFragment?) with wich you can define what is shown in front of the image.

Seems like somthing that could be done with a community contribution. Any takers?

**Comment by ID-JA** [comment]
besides the `DisplayTemplate` parameter, there could be an option to select the content's position.

**Comment by dvoituron** [comment]
See #2010

**Comment by vnbaaij** [comment]
Fixed with PR mentioned above
