### ISSUE TITLE
 Add DI Registration for IToastService, IMesssageService, IDialogServicedocs to the documentation 

### ISSUE THREAD

**Issue by jrod730** [microsoft/fluentui-blazor#1911]
The following services need to be registered.:  IToastService, IMesssageService, IDialogService 

However, these are not listed in the documentation.

**Comment by vnbaaij** [comment]
These services are added with our AddFluentUIComponents() extension method. See https://github.com/microsoft/fluentui-blazor/blob/dev/src%2FCore%2FExtensions%2FServiceCollectionExtensions.cs#L18-L20.

It is written in the docs in the code setup page that you need to add a call to this method. See https://fluentui-blazor.net/CodeSetup#register-services
