### ISSUE TITLE
fix: DataGrid GridTemplateColumns not working

### ISSUE THREAD

**Issue by f4n0** [microsoft/fluentui-blazor#1915]
my code:
![image](https://github.com/microsoft/fluentui-blazor/assets/36199751/c36297f6-23fb-4932-8434-8151d8811710)

results:
![image](https://github.com/microsoft/fluentui-blazor/assets/36199751/93802d5f-f6a4-4f0c-ae9e-8b03f21a3f00)

inspection:
![image](https://github.com/microsoft/fluentui-blazor/assets/36199751/85a0dfbe-0fd3-412f-8095-06fbc24eaf38)
as see in the inspection, no GridTemplateColumns where found on header, and in the rows they are wrong!

# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC] any
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox] any
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1] 4.7.0

**Comment by vnbaaij** [comment]
We CAN NOT repo it like this. Please supply code! Also, your value for `GridTemplateColumns` seems to have way less information than the number of columns that is actually there.

**Comment by vnbaaij** [comment]
I don't see anything wrong. The `fluent-data-grid` itself never shows the `grid-template-columns` value. The first `fluent-data-grid-row` contains the header and has the values set. Then each following row has the value set as well.

If you are not seeing the values you want, then there is most probably an issue in your `GetCssGridTemplate` code

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/365d6b62-1e8f-49a9-a5de-abb4f9957134)

**Comment by vnbaaij** [comment]
Ok, that seems to be a regression then. We'll investigate!

**Comment by vnbaaij** [comment]
v4.7.1 is on NuGet now.
