### ISSUE TITLE
fix: `Virtualize=true` conflicts with `Class="multiline-text"` in FluentDataGrid

### ISSUE THREAD

**Issue by tommyvct** [microsoft/fluentui-blazor#1918]
# 🐛 Bug Report

According to https://www.fluentui-blazor.net/DataGrid, both props are valid to put in a `PropertyColumn`.  
However, `Virtualize=true` will ruin `Class="multiline-text"`. In another word, if there are too many chars, it will overwrite on other things.

## 💻 Repro or Code Sample

```razor
<FluentDataGrid Items="@filteredMaintenanceRecords" Virtualize=true GenerateHeader="@GenerateHeaderOption.Sticky">
    <ChildContent>
        <PropertyColumn Property="@(c => c.ID)" Title="ID" Sortable="true" InitialSortDirection="@SortDirection.Descending" IsDefaultSortColumn  Tooltip="true" />
        <PropertyColumn Property="@(c => c.equipment.Manufacturer)" Title="生产厂家" Tooltip="true" />
        <PropertyColumn Property="@(c => c.equipment.Description)" Title="设备名称" Tooltip="true" />
        @* Maybe more columns here *@
        <PropertyColumn Property="@(c => c.DateTimeReportedOn)" Title="报修日期时间" Tooltip="true" Class="multiline-text" />
        <PropertyColumn Property="@(c => c.DescriptionOfMalfunction)" Title="故障现象" Tooltip="true"  Class="multiline-text" />
        <PropertyColumn Property="@(c => c.DateTimeEstimatedComplete)" Title="预计完成时间" Tooltip="true" Class="multiline-text" />
        <PropertyColumn Property="@(c => c.DateTimeCompleted)" Title="实际完成时间" Tooltip="true" Class="multiline-text" />
        <PropertyColumn Property="@(c => c.MaintenancePerformedBy)" Title="维修工程师" Tooltip="true" Class="multiline-text" />
    </ChildContent>
    <EmptyContent>
        <p>没有数据</p>
    </EmptyContent>
</FluentDataGrid>

```

## 🤔 Expected Behavior
![image](https://github.com/microsoft/fluentui-blazor/assets/7903172/1dd884a0-0c82-44ba-b1dc-18f056d87e04)

## 😯 Current Behavior
![image](https://github.com/microsoft/fluentui-blazor/assets/7903172/e6a519d1-583d-4821-946e-e74cfd95c93b)

## 💁 Possible Solution
Upon inspection from the client side, there are 2 key attributes that are culprit:
![image](https://github.com/microsoft/fluentui-blazor/assets/7903172/6613cfb6-cfc1-484a-b3b5-d2a89612334a)
Disabling them on the rows will fix it
![image](https://github.com/microsoft/fluentui-blazor/assets/7903172/b71a6953-7339-495f-aa1d-5c7c7915dadd)
Notice that I only disabled these props on the first 3 rows, other rows are still cramped.

## 🔦 Context
I want to have virtualize loading with EF Core and multiline-text at the same time.

## 🌍 Your Environment

* OS & Device: Windows PC
* Browser Microsoft Edge, Google Chrome
* .NET 8.0.300-preview.24203.14 and Fluent UI Blazor library Version 4.6.1 and 4.7.0

**Comment by vnbaaij** [comment]
It can work I think, buy you **must** set ItemSize. For virtualize to work, all rows need to be the same height

**Comment by tommyvct** [comment]
> For virtualize to work, all rows need to be the same height

That's where the problem is. It would be really ugly that some rows will make use of the height while others only take 1 or 2 lines, leaving ugly large blank areas.

**Comment by vnbaaij** [comment]
> That's where the problem is. It would be really ugly that some rows will make use of the height while others only take 1 or 2 lines, leaving ugly large blank areas.

Understood. But tha is a Blazor limitation, not a Fluent UI issue.

**Comment by tommyvct** [comment]
How unfortunate, but thanks anyway.
