### ISSUE TITLE
Regression in Theme sample after update to 4.7,1

### ISSUE THREAD

**Issue by coderdnewbie** [microsoft/fluentui-blazor#1920]
This worked before the update to 4.7.1., in the theme example:

```
                        <FluentIcon Value="@(new Icons.Filled.Size20.RectangleLandscape())"
                                    Color="Color.Custom"
                                    CustomColor="@(@context.ToAttributeValue() != "default" ? context.ToAttributeValue() : "#036ac4" )" 
                                    />
```

However, now it throws an error no accessible extension method 'ToAttributeValue'.

Has ToAttributeValue been removed?

**Comment by vnbaaij** [comment]
What is your `@context`?. You can only use `ToAttributeValue` on an enum. My guess is this is not a regression. `CustomColor` should be supplied with an actual color value.

**Comment by AJ1000** [comment]
In Version="4.7.1", I have to comment out the code to make it work, as in this screenshot:

![commentedoutworksin471](https://github.com/microsoft/fluentui-blazor/assets/4085891/31a6dbe6-9b12-4582-b376-fec122478eb4)

**Comment by vnbaaij** [comment]
I think you are running into the breaking change we mentioned in the blogs, WhatsNew and upgrade guide...
Extension methods are moved to a new namespace. Add that new namespace to the _Imports file and it should be fine.

**Comment by coderdnewbie** [comment]
Yes, I missed that I had to add the following namespace to the _Imports.razor file.

`@using Microsoft.FluentUI.AspNetCore.Components.Extensions`

It now works the same as 4.6.1.

My name is Jay Tandon, and would like to thank you for your work on this project. I will close this as completed. The Split Button I was asking for is the same as the 'Close with Comment' split button on this page, which is the only type of button that is missing for my upgrade from MVC to Blazor. The demo was good, and you do have a navbar, whih is called Header in the Layout page of your examples.
