### ISSUE TITLE
feat: add horizontal nav menu component

### ISSUE THREAD

**Issue by Hona** [microsoft/fluentui-blazor#1922]
![fluentuiblazor horizontalnavmenu](https://github.com/microsoft/fluentui-blazor/assets/10430890/c066f3fd-ffdb-47de-bcec-ed780807b071)

I've created a horizontal nav menu inside of my [TempusHub2 project](https://github.com/Hona/TempusHub2)

I could fit back the horizontal nav back into the component library, but only if the maintainers agree :)

The preview of that site is at https://preview.tempushub.xyz

Let me know, and I'm happy to make a proper PR :)

The code example would look like this:

```cshtml
<NavMenuButton Text="Dashboard"
                   Icon="@(new Icons.Regular.Size16.Grid())">
        <MenuItems>
            <NavMenuItem Text="Overview"
                         Icon="@(new Icons.Regular.Size16.Flowchart())"
                         Href="/dashboard"/>
        </MenuItems>
    </NavMenuButton>
    <NavMenuButton Text="Leaderboards"
                   Icon="@(new Icons.Regular.Size16.Trophy())">
        <MenuItems>
            <NavMenuItem Text="Maps"
                         Icon="@(new Icons.Regular.Size16.Map())"
                         Href="/leaderboard/maps"/>
            <NavMenuItem Text="Players"
                         Icon="@(new Icons.Regular.Size16.Person())"
                         Href="/leaderboard/players"/>
        </MenuItems>
    </NavMenuButton>
```

**Comment by coderdnewbie** [comment]
The navbar that I use is called Header in the layout section of the example and is the <FluentHeader> tag. Does this help you?

**Comment by dvoituron** [comment]
That would be a very good idea, I think.
Why not improve the existing `FluentMenuButton` component?
By adding the properties `IconStart`, `IconEnd`, `Href` and updating the (not very fine) "drop down" icon :-)

```xml
<FluentStack>
    <FluentMenuButton Text="Dashboard" ButtonAppearance="Appearance.Stealth">
        <FluentMenuItem>Overview</FluentMenuItem>
    </FluentMenuButton>
    <FluentMenuButton Text="Leaderboards" ButtonAppearance="Appearance.Stealth">
        <FluentMenuItem>Maps</FluentMenuItem>
        <FluentMenuItem>Players</FluentMenuItem>
    </FluentMenuButton>
    <FluentMenuButton Text="Play" ButtonAppearance="Appearance.Stealth" />
</FluentStack>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/1500c3de-c3d1-4b7f-9ebc-0c630bad5a93)

**Comment by Hona** [comment]
Sounds good. I'll look into that tonight @dvoituron

**Comment by vnbaaij** [comment]
Hi Luke, 
Any update on this?

**Comment by f4n0** [comment]
Hi @Hona 
I was looking for this feature too, have you done something?

**Comment by vnbaaij** [comment]
Closing this as no progress made.
