### ISSUE TITLE
Allow for FluentTextField to inherit font-weight

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#1928]
# 🙋 Feature Request

I want to be able to apply font-weight bold to the text within a `FluentTextField`. Right now this is not possible because the font-weight is not being inherited by `.control`.

```asp
<FluentTextField Value="@("Hello World")" Class="w-auto main-language" Style="font-weight: bold !important; color: deeppink !important;" Disabled />
```

I tried it by providing a custom class (main-language) to the text field and by applying custom style but in both cases font-weight will be ignored.

When adding `font-weight: inherit;` to the constructed `.control` class then I can override the font-weight as expected. But I'm not sure if this has any consequences for any other part of this library.

**Comment by MarvinKlein1508** [comment]
@vnbaaij alright. It would be cool to add it to the CSS. I would do it myself but I cannot find the file for this in this repository. The inherit for font-weight is needed here:
![grafik](https://github.com/microsoft/fluentui-blazor/assets/32510006/5d9529ad-f184-49a9-b191-e4884cccba9f)

**Comment by vnbaaij** [comment]
Which CSS do you mean? 

If you want to do this in your app, you can target that specific element with something like:
```
<style>
     fluent-text-field::part(control) {
    ...your styles here...
    }
</style>
```

**Comment by vnbaaij** [comment]
That is all done in/from the we components script

**Comment by MarvinKlein1508** [comment]
can you link it?

**Comment by vnbaaij** [comment]
We don't include it directly in the library. We have the core assets project that Imports the script into our build output.
Easiest way to take a look at it would be to go to https://www.npmjs.com/package/@fluentui/web-components/v/2.6.1?activeTab=code and ten find the dist/web-components.js file. Or you go to the microsoft/fluentui repo and then packages/web-components where you can find the individual TypeScript files the web components library is built from
