### ISSUE TITLE
fix: Selected option retained ordinal position after items changed in FluentSelect

### ISSUE THREAD

**Issue by KaineVarley** [microsoft/fluentui-blazor#1929]
# 🐛 Bug Report

After an initial option within a `FluentSelect` is chosen, then the bound collection is replaced with another collection, including specifying a selected option in the new collection, the new explicitly selected option is ignored in favour of the option that now occupies the ordinal position of the previously selected option.

## 💻 Repro or Code Sample

**Repro steps**
1. Choose Make: `Audi`
2. Choose Model: `A6`
3. Change Make: `BMW`
4. Model now reflects `4 Series` despite changing the options collection and explicitly setting the selected option to be the first in the list.

**Vehicles.razor**
```HTML+Razor
@page "/Vehicles"
@rendermode InteractiveServer

<h3>Vehicles</h3>

<FluentDropDown Label="Make:" Placeholder="Select a make..." Items="@Makes" OnValueChanged="MakeValueChanged" Disabled="@MakesEmpty" />
<br/>
<FluentDropDown Label="Model:" Placeholder="Select a model..." Items="@Models" OnValueChanged="ModelValueChanged" Disabled="@ModelsEmpty" />
<br />
<FluentButton @onclick="OnSearchClick" Disabled="@SearchDisabled">Search</FluentButton>

@code {
    public string Make { get; set; } = string.Empty;
    public string Model { get; set; } = string.Empty;

    private IEnumerable<string> Makes { get; set; } = [];
    private IEnumerable<string> Models { get; set; } = [];

    private IDictionary<string, IEnumerable<string>> MakesModels { get; set; } = new Dictionary<string, IEnumerable<string>>
    {
        { "Audi", new string[] { "A4", "A6", "A8" } },
        { "BMW", new string[] { "3 Series", "4 Series", "6 Series" } },
        { "Volvo", new string[] { "C30", "C40", "C70" } },
    };

    private bool MakesEmpty { get { return this.Makes.Count() == 0; } }
    private bool ModelsEmpty { get { return this.Models.Count() == 0; } }
    private bool SearchDisabled { get { return this.Model.Length == 0; } }

    private void LoadMakes()
    {
        // ... do stuff...
        this.Makes = this.MakesModels.Keys;
    }

    private void LoadModels(string make)
    {
        this.Models = [];
        this.Model = string.Empty;

        // ... do stuff...
        this.Models = this.MakesModels[make];
        this.Model = string.Empty;
    }

    private void MakeValueChanged(string make)
    {
        if (string.IsNullOrEmpty(make))
        {
            return;
        }

        this.Make = make;
        this.LoadModels(this.Make);
    }

    private void ModelValueChanged(string model)
    {
        this.Model = model;
    }

    private void OnSearchClick()
    {
        Console.WriteLine($"Searching for make '{this.Make}' and model '{this.Model}'");
    }

    protected override void OnInitialized()
    {
        this.LoadMakes();
    }
}

```

**FluentDropDown.razor**
```HTML+Razor

<FluentSelect
    Label="@Label"
    Items="@OptionItems"
    TOption="Option<string>"
    OptionText="@(i => i.Text)"
    OptionValue="@(i => i.Value)"
    OptionSelected="@(i => i.Selected)"
    OptionDisabled="@(i => i.Disabled)"
    ValueChanged="OnValueChanged"
    Disabled="@Disabled" />

@code {

    private IEnumerable<string> _items = [];
    private List<Option<string>> OptionItems = [];

    [Parameter]
    public bool Disabled { get; set; }

    [Parameter]
    public IEnumerable<string> Items 
    {
        get { return _items; }
        set
        {
           // I realise that this may not be the best way to implement something like this.. :-/
            _items = value;
            OptionItems = new()
            {
//                { new() { Disabled = true, Selected = true, Text = Placeholder, Value = string.Empty } },
                { new() { Selected = true, Text = Placeholder, Value = string.Empty } },
            };

            var options = _items.Select(item => new Option<string> { Text = item, Value = item });
            OptionItems.AddRange(options);

        }
    }

    [Parameter]
    public string Label { get; set; } = string.Empty;

    [Parameter]
    public string Placeholder { get; set; } = string.Empty;

    [Parameter]
    public string Value { get; set; } = string.Empty;

    [Parameter]
    public EventCallback<string> OnValueChanged { get; set; }

}

```

## 🤔 Expected Behavior

My expectation (rightly or wrongly) was for the `Placeholder` option, the first option in the list, would have been selected.

## 😯 Current Behavior

The option matching the ordinal position of the previously selected option, before the collection as changed, is selected, despite explicitly setting the new option as the 'selected' option.

## 💁 Possible Solution

If this is intended behaviour, please accept my apologies. I would welcome some guidance on how to achieve my desired behaviour outcome though... ;-)

## 🔦 Context

Ultimately, I am trying to develop an Blazor app that queries a RESTful API for the values in each drop-down, with the previous drop-down's selection defining the set of values for the next. In my contrived example, there are only 2 drop-downs but, in reality, there are many more, each relying on the input selection of the previous.

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser Google Chrome
* .NET and Fluent UI Blazor library Version net8.0 and 4.7.1

**Comment by vnbaaij** [comment]
It works if you change the code to:

**page.razor**
```
<h3>Vehicles</h3>

<FluentDropdown Label="Make:" Placeholder="Select a make..." Items="@Makes" @bind-Value=Make @bind-Value:after="MakeValueChanged" Disabled="@MakesEmpty" />
<br/>
<FluentDropdown Label="Model:" Placeholder="Select a model..." Items="@Models" @bind-Value=Model  Disabled="@ModelsEmpty" />
<br />
<FluentButton @onclick="OnSearchClick" Disabled="@SearchDisabled">Search</FluentButton>

@code {
    public string Make { get; set; } = string.Empty;
    public string Model { get; set; } = string.Empty;

    private IEnumerable<string> Makes { get; set; } = [];
    private IEnumerable<string> Models { get; set; } = [];

    private IDictionary<string, IEnumerable<string>> MakesModels { get; set; } = new Dictionary<string, IEnumerable<string>>
    {
        { "Audi", new string[] { "A4", "A6", "A8" } },
        { "BMW", new string[] { "3 Series", "4 Series", "6 Series" } },
        { "Volvo", new string[] { "C30", "C40", "C70" } },
    };

    private bool MakesEmpty { get { return this.Makes.Count() == 0; } }
    private bool ModelsEmpty { get { return this.Models.Count() == 0; } }
    private bool SearchDisabled { get { return this.Model.Length == 0; } }

    private void LoadMakes()
    {
        // ... do stuff...
        this.Makes = this.MakesModels.Keys;
    }

    private void LoadModels(string make)
    {
        this.Models = [];
        StateHasChanged();
        Task.Delay(5);
        this.Model = string.Empty;

        // ... do stuff...
        this.Models = this.MakesModels[make];
        this.Model = string.Empty;
    }

    private void MakeValueChanged()
    {
        // if (string.IsNullOrEmpty(make))
        // {
        //     return;
        // }

        // this.Make = make;

        this.LoadModels(Make);
        return;
    }

    private void ModelValueChanged(string model)
    {
        this.Model = model;
    }

    private void OnSearchClick()
    {
        Console.WriteLine($"Searching for make '{this.Make}' and model '{this.Model}'");
    }

    protected override void OnInitialized()
    {
        this.LoadMakes();
    }
}
```
FluentDropdown.razor
<FluentSelect Label="@Label"
              Items="@OptionItems"
              TOption="Option<string>"
              OptionText="@(i => i.Text)"
              OptionValue="@(i => i.Value)"
              OptionSelected="@(i => i.Selected)"
              OptionDisabled="@(i => i.Disabled)"
              ValueChanged="ValueChanged"
              Value="@Value"
              Disabled="@Disabled" />

@code {
    
    private IEnumerable<string> _items = [];
    private List<Option<string>> OptionItems = [];

    [Parameter]
    public bool Disabled { get; set; }

    [Parameter]
    public IEnumerable<string> Items
    {
        get { return _items; }
        set
        {
            // I realise that this may not be the best way to implement something like this.. :-/
            _items = value;
            OptionItems = new()
            {
//                { new() { Disabled = true, Selected = true, Text = Placeholder, Value = string.Empty } },
                { new() { Selected = false, Text = Placeholder, Value = string.Empty } },
            };

            var options = _items.Select(item => new Option<string> { Text = item, Value = item });
            OptionItems.AddRange(options);

        }
    }

    [Parameter]
    public string Label { get; set; } = string.Empty;

    [Parameter]
    public string Placeholder { get; set; } = string.Empty;

    [Parameter]
    public string Value { get; set; } = string.Empty;

    [Parameter]
    public EventCallback<string> ValueChanged { get; set; }

}
```

**FluentDropdown.razor**
```

<FluentSelect Label="@Label"
              Items="@OptionItems"
              TOption="Option<string>"
              OptionText="@(i => i.Text)"
              OptionValue="@(i => i.Value)"
              OptionSelected="@(i => i.Selected)"
              OptionDisabled="@(i => i.Disabled)"
              ValueChanged="ValueChanged"
              Value="@Value"
              Disabled="@Disabled" />

@code {
    
    private IEnumerable<string> _items = [];
    private List<Option<string>> OptionItems = [];

    [Parameter]
    public bool Disabled { get; set; }

    [Parameter]
    public IEnumerable<string> Items
    {
        get { return _items; }
        set
        {
            // I realise that this may not be the best way to implement something like this.. :-/
            _items = value;
            OptionItems = new()
            {
//                { new() { Disabled = true, Selected = true, Text = Placeholder, Value = string.Empty } },
                { new() { Selected = false, Text = Placeholder, Value = string.Empty } },
            };

            var options = _items.Select(item => new Option<string> { Text = item, Value = item });
            OptionItems.AddRange(options);

        }
    }

    [Parameter]
    public string Label { get; set; } = string.Empty;

    [Parameter]
    public string Placeholder { get; set; } = string.Empty;

    [Parameter]
    public string Value { get; set; } = string.Empty;

    [Parameter]
    public EventCallback<string> ValueChanged { get; set; }

}
```

It is more a question of Blazor workings in general than Fluent UI library in particular.
I changed the `FluentDropdown` to have a 2-way bindable value. That way a change to that automatically re-renders it. In the page I bound thes values to the selections being made. I have not done anything ith the rest of the code, but I think some optimization can be achieved there as well 😉

**Comment by KaineVarley** [comment]
Thank you @vnbaaij, that is very kind of you. I really appreciate your help.
