### ISSUE TITLE
fix: DataGrid OnRowFocus is currently only applying to the cell area and now the row area

### ISSUE THREAD

**Issue by StephenOTT** [microsoft/fluentui-blazor#1932]
Consider a DataGrid with a defined height.

If you apply onrowFocus to the data grid, the clickable area is currently set to the cell value:

<img width="254" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1994838/ce655d05-ac5f-4b61-bca9-6ce0a026c7c0">

So if you have a DataGrid with 120px height and the cell content does not take up 120px, then you end up with:

<img width="206" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1994838/d662988c-335b-46ee-a7f1-e991dde73885">

where only the center area is clickable.

Anywhere within the row should be clickable

**Comment by vnbaaij** [comment]
Hi Stephen,

I appreciate you raising these issues, but please follow the issue template and provide reproduction steps/code. We really do not have the capacity to craft a repro situation for every issue. 

In this case, I would need to create a grid, get the styles right, etc.

We want to help you but in return please help us by supplying actionable steps and/or code. It doesn't have to be a complete project. Just someting we can copy/paste and run.

Thanks, Vincent

**Comment by StephenOTT** [comment]
No problem buddy

@vnbaaij  here a snippet:

```razor
            <div style="height: 500px; overflow:auto;">
                <FluentDataGrid
                    TGridItem="MyData"
                    Loading="true"
                    Virtualize="true"
                    ItemsProvider="@_myData"
                    ItemSize="80"
                    GenerateHeader="GenerateHeaderOption.Sticky"
                    ResizableColumns="true"
                    OnRowFocus="@HandleRowClick">
                    <PropertyColumn Property="@(p => p.Name)" Sortable="true"/>
                </FluentDataGrid>
            </div>


@code{
    private void HandleRowClick(FluentDataGridRow<Workspace> obj)
    {
        Console.WriteLine("Clicked!!");    
    }
}
```

Upon further testing I can see that it actually seems to be a first click issue:

1. If click in the non-cell space the click does not work
2. If you click the cell space the click works
3. If you then click in the non-cell space (after doing step 2) the click now works in the entire row

**Comment by StephenOTT** [comment]
Here is an example using the sample from the docs:

```razor
            <FluentDataGrid Virtualize="true" ItemSize="120" OnRowFocus="HandleRowClick" TGridItem="Person" ItemsProvider="PeopleData">
                <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" />
                <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
                <PropertyColumn Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
            </FluentDataGrid>

@code{
    record Person(int PersonId, string Name, DateOnly BirthDate);

    List<Person> people =
    [
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9))
    ];

    GridItemsProvider<Person>? PeopleData;
    
    protected override Task OnInitializedAsync()
    {
        PeopleData = async req => GridItemsProviderResult.From(
            items: people,
            totalItemCount: people.Count());
}

}
```

**Comment by StephenOTT** [comment]
@vnbaaij  if you could reopen this issue as well: https://github.com/microsoft/fluentui-blazor/issues/1066 as the same reproducer can be used to demonstrate the virtualize double loading/calling of the data provider.

**Comment by vnbaaij** [comment]
I'm fixing this by appling the height of the row in cell style as well. If no custom cell style is provided, `align-content: center` will also be applied automatically. You can then click anywhere in the cell from the first time to call the `OnRowFocus` handler.

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/290e430a-1004-4bc1-9210-eea98c710b6c)
