### ISSUE TITLE
When can we achieve rounded corners like button and input? 

### ISSUE THREAD

**Issue by Seanxwy** [microsoft/fluentui-blazor#1935]
![image](https://github.com/microsoft/fluentui-blazor/assets/15828095/e1aa9ffa-e5a9-4fee-b7e4-8bcc95c452d8)

When can we achieve rounded corners like button and input? I don't see an example of this in the documentation

**Comment by LuohuaRain** [comment]
You mean?
![image](https://github.com/microsoft/fluentui-blazor/assets/37979368/f170807c-4515-4a38-ad50-464e94ddde24)

**Comment by Seanxwy** [comment]
I don't see an example of this at https://www.fluentui-blazor.net/TextField. What properties are you setting to achieve this?
Perhaps the docs example should be made more comprehensive
