### ISSUE TITLE
Problems with body-content styling

### ISSUE THREAD

**Issue by Seanxwy** [microsoft/fluentui-blazor#1937]
```
.body-content[b-9l28a7kahd] {
    margin: 0;
    overflow-y: auto;
    overflow-x: hidden;
    align-items: flex-start;
    height: 100%;
    width: 100%;
    font-family: var(--body-font);
    font-weight: normal;
    font-size: var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
}
```

```
.body-content {
    overflow: visible !important;
}
```
Styling overflow in the parent's body-content causes position:sticky; top:0;  Invalidation.
If you remove (override) overflow from body-content. sticky can take effect. But when the popver component runs, the browser X-axis scrollbar blinks. Is there any way to solve this visually unfriendly problem?

Whether it is possible to remove the overflow setting in body-content by default to keep other menus and popovers friendly at the edge of the browser.

Demonstrable code repository

https://github.com/Seanxwy/FluentBlazorApp1/blob/master/FluentBlazorApp1/FluentBlazorApp1.Client/Layout/Head.razor

**Comment by vnbaaij** [comment]
With version 4.7.1 we added the `FixedPlacement` parameter to the Popover component. I believe that fixes your issue

**Comment by Seanxwy** [comment]
menu Whether FixedPlacement can also be added. menu doesn't fit well into popver, after all

**Comment by vnbaaij** [comment]
Menu will not work with a Popover. It already has its own Overlay and AnchoredRegion. You just need to bind it to the right `Anchor`
