### ISSUE TITLE
Scheduler Component

### ISSUE THREAD

**Issue by MAHarby** [microsoft/fluentui-blazor#1940]
# 🙋 Feature Request

Do you have any plans to implement a Scheduler component ?

We are just about to start a new Blazor project and have started testing with the Radzen suite as we need a fully featured Schedular component as the main SPA page.

Have just watched the Community Standup and love what you are doing with the FluentUI stuff in Blazor.

**Comment by vnbaaij** [comment]
Hi,

We dont't have any plans currently to add such a Schedular component.
