### ISSUE TITLE
fix: `FluentDataGrid` lags badly

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#1941]
# 🐛 Bug Report

The `FluentDataGrid` seems to struggle with lag when it displays a lot of rows (and by a lot I don't mean hundreds of thousands, not even a hundred is enough to cause this behavior).
When using tab/arrow keys to navigate through the grid, it appears that the grid gets re-rendered every time the active cell changes.
This might potentially happen with other actions as well (for example when clicking on the grid).
This becomes more apparent the more rows a grid has (since it needs to re-render more rows each time).

## 💻 Repro or Code Sample

In the official documentation, remove the `Pagination` parameter from the `FluentDataGrid` in the `DataGridTypical.razor` example.
Then use tab to focus the grid and hold down the downwards arrow key on your keyboard.
This causes the whole page to freeze until the focus caught up.

## 🤔 Expected Behavior

No lag.

## 😯 Current Behavior

A lot of lag.

## 💁 Possible Solution

Not a real solution but like I have written, it appears that the grid tries to re-render too often.
This should probably be limited somehow.

**Comment by Ajay100000** [comment]
Have you looked at the virtualise feature of the datagrid. I think that is what you need to use.

**Comment by hksalessio** [comment]
Are you using Chrome as well? Otherwise I have no idea why it looks like this to me:

https://github.com/microsoft/fluentui-blazor/assets/143792830/c667fdbb-918a-4083-b4da-a5f11b7dd08a

**Comment by hksalessio** [comment]
> Have you looked at the 'Virtualized grid' feature of the datagrid. I think that is what you need to use. It is in the samples of the datagrid.

I know of this feature but our requirement is to use pagination and we want to show around 250 items per page

**Comment by vnbaaij** [comment]
> Are you using Chrome as well? Otherwise I have no idea why it looks like this to me:
> 
Tested on Edge Canary (Version 126.0.2547.0 (Official build) canary (64-bit)) and Firefox Developer Edition (Version 126.0b5). Both work perfectly fine.

Which Chrome version?

**Comment by hksalessio** [comment]
> Which Chrome version?

Version 124.0.6367.92 (Official build) (64-Bit)

I did try with Edge as well (124.0.2478.51 (Official build) (64-Bit)) and the same happens. Looks like you are some versions ahead but for me it says those are the latest versions 🤔

> And perhaps try with QuickGrid as well(https://aspnet.github.io/quickgridsamples/)

It seems that with QuickGrid the cells are not focusable.

**Comment by vnbaaij** [comment]
Sorry. But if we can't reproduce it, we can't investigate it.

> It seems that with QuickGrid the cells are not focusable.

Ah, right! We are quite focused on the whole a11y thing as we find that important.

**Comment by hksalessio** [comment]
No worries, it's just kind of weird :D
