### ISSUE TITLE
Allow to input other decimal separators in FluentNumberField

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#1942]
# 🙋 Feature Request

In some countries decimals are separated with a different symbol besides `.` for example in Germany we use `,`. The `FluentNumberField` only allows to enter decimals with `.` though and not with other symbols for other CultureInfos. This makes it much harder for users to use the component when they type numbers with the numpad for example.

## 🤔 Expected Behavior

This component should support other decimal separators as well and converts them into `CultureInfo.InvarientCulture`

**Comment by vnbaaij** [comment]
This is not supported by the underlying input type. 

The `FluentNumberField` is **not** a good component. I would advise you **not** to use it. 

In a lot of cases it is not even a nice way of inputting a value. My advise is to use a `FluentTextField` with the `InputMode="InputMode.Numeric"` settin. Gives you a nice number keyboard on a mobile device (and adapts to regional settings):
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/4368f1fb-0e95-4d15-b32a-ab966cea38bd)

**Comment by MarvinKlein1508** [comment]
@vnbaaij but how would you bind to anything else besides a string then?

**Comment by vnbaaij** [comment]
You'll have to do the conversion yourself then. Not ideal, I know but `FluentNumberField` or actually `fluent-number-filed` is really broken at the core and I'm not expecting fixes unitl v3 of the web components
