### ISSUE TITLE
Add floating labels

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#1949]
# 🙋 Feature Request

It would be a nice addition if fluent-ui could support floating labels. Displaying a label for every text field makes the UI grow really fast. Take a look on this for comparison:

With floating labels:
![grafik](https://github.com/microsoft/fluentui-blazor/assets/32510006/71d7b72e-d7fd-4643-8468-d9f99d3cc71a)

Without floating labels:
![grafik](https://github.com/microsoft/fluentui-blazor/assets/32510006/1e3939a9-cacf-4806-9619-b038410e0481)

**Comment by dvoituron** [comment]
It doesn't seem to respect the FluentUI design. This is not currently planned

**Comment by vnbaaij** [comment]
As Denis said. We follow the Fluent Design System (in this case https://fluent2.microsoft.design/components/web/react/field/usage#layout)
