### ISSUE TITLE
Add support for OnRowClick & OnRowDblClick in Fluent Data Grid

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#1953]
# 🙋 Feature Request

I want to be able to trigger certain actions when I click once on a row within a `FluentDataGrid` To achive click I can use `OnRowFocus` but there is no option for double click available.

Basically what I want to do:
One click = trigger a bool to display more information (Works with `OnRowFocus`). 
Double click = do something with the row item (in my case return it to a different component)

I know that I can add custom buttons into the data grid but I want my user to be able to double click the row from everywhere. For example when I have a lot of columns the user needs to scroll horizontally before he could see the buttons.

**Comment by dvoituron** [comment]
We are adding an "OnClick" event via PR #1952. We could include the Double-click which seems to be a similar modification.

**Comment by MarvinKlein1508** [comment]
@dvoituron perhaps even for cells. WOuld highly appreciate it.

**Comment by dvoituron** [comment]
@MarvinKlein1508  I don't think so :  a double-click on a row will be associated with "highlighted selection".
But to add an action on a cell, a button/link would probably be more appropriate.

**Comment by MarvinKlein1508** [comment]
@dvoituron ah yes, you are right.

**Comment by vnbaaij** [comment]
Beware of a11y! We will need to define how the double click can be initiated without actually clicking (ie keyboard user)

Maybe OnClick=>Enter, OnDblClick=>Shift+Enter od Ctrl+Enter?
