### ISSUE TITLE
fix: error when sorting a DataGrid column with mixed types

### ISSUE THREAD

**Issue by verdie-g** [microsoft/fluentui-blazor#1957]
# 🐛 Bug Report

Assuming you have a column with ints and string, clicking on the header on the column to sort it will throw a `System.ArgumentException: Object must be of type Int32.`

## 💻 Repro or Code Sample

```
<FluentDataGrid Items="@people">
    <PropertyColumn Property="@(p => p.O)" Sortable="true" />
</FluentDataGrid>

@code {

    record Person(object O);

    IQueryable<Person> people = new[]
    {
        new Person(10895),
        new Person(10944),
        new Person(""),
    }.AsQueryable();

}
```

## 🤔 Expected Behavior

Not sure, but the component should probably not crash.

## 😯 Current Behavior

Blank page with an error
![image](https://github.com/microsoft/fluentui-blazor/assets/9092290/dcaaca97-31b2-45e6-9d1c-d45d0826263c)

## 💁 Possible Solution

I suppose it can be considered as a mistake of the developer to have mixed types in a sortable column so maybe the exception should be caught and the sort canceled.

## 🔦 Context

I have a table of logs, and some logs may not contain all the fields so a `""` value is used. I realize that a `null` value work around the issue.

## 🌍 Your Environment

* OS & Device: Windows
* Browser Google Chrome
* .NET and Fluent UI Blazor library Version: 8.0.4 and 4.6.1

**Comment by vnbaaij** [comment]
Yeah, I don't think we are going to cater for that. It is indeed a mistake of the developer which they can (and should) work around. Canceling the sort is not that easy
