### ISSUE TITLE
fix: NavMenu labels do not show if navmenu is collapsed before going into mobile (using wasm template)

### ISSUE THREAD

**Issue by StephenOTT** [microsoft/fluentui-blazor#1958]
# 🐛 Bug Report

this was previously broken in https://github.com/microsoft/fluentui-blazor/issues/1183 and fixed.

But looks broken again

## 💻 Repro or Code Sample

Using latest release template for WASM

## 🤔 Expected Behavior

The labels of the menu should also show when in mobile menu view

## 😯 Current Behavior

Labels are hidden if they were hidden in desktop view.

![brokne-nav](https://github.com/microsoft/fluentui-blazor/assets/1994838/8f1566ee-ac2f-437d-8e6c-9cde0651021b)

**Comment by vnbaaij** [comment]
Fixed for next release. I added a CSS media rule for `max-width: 600px` (same as used in SSR script to determine breakpoint) to always show the text then
