### ISSUE TITLE
How to implement a tree select

### ISSUE THREAD

**Issue by Seanxwy** [microsoft/fluentui-blazor#1967]
# 🙋 Feature Request
![动画](https://github.com/microsoft/fluentui-blazor/assets/15828095/0614b70f-0104-4ab0-a418-2db261256981)

I want to achieve this effect, please ask how to do it. Can you do this using select + treeview?

## 🤔 Expected Behavior

select loads tree-structured data and can perform selection operations

**Comment by vnbaaij** [comment]
No, this can not be done with the current select. It expects (Fluent)Option elements as it's child content.

Should not be too hard/difficult to build something yourself that can wrap the FluentTreeView. We do not plan to build this as part of the library as it is not a much requested option. (In fact, you are the first)
