### ISSUE TITLE
Issues in Fluent Autocomplete and Fluent Dialog controls

### ISSUE THREAD

**Issue by PraleshGitHub** [microsoft/fluentui-blazor#1972]
# 🐛 Bug Report
1. On tab key, it doesn't go to the close button in Fluent Autocomplete control. 
2. Also when press the down arrow button at the end of the populated list of Fluent autocomplete control, it continuously pronounce text in input box in NVDA.
3. Tooltip is required on focus to close button in Fluent dialog.

## 💻 Repro or Code Sample

Go to fluent blazor demo URL: https://www.fluentui-blazor.net/Autocomplete

## 🤔 Expected Behavior

1. On keyboard tab key, Focus should move to the close button in Fluent Autocomplete control. 
2. Also when press the down arrow button at the end of the populated list of Fluent autocomplete control, it should not pronounce text in NVDA when arrow reach the end of the list.
3. Tooltip is required on focus to close button in Fluent dialog using keyboard tab key.

## 😯 Current Behavior

1. On tab key, it doesn't go to the close button in Fluent Autocomplete control. 
2. Also when press the down arrow button at the end of the populated list of Fluent autocomplete control, it continuously pronounce text in input box in NVDA.
3. Tooltip is not keyboard accessible, when mouse hover on the control, tooltip is displayed.

## 🔦 Context

We are trying to achieve grade A accessibility level. however these issues are stopping to achieve the same.

## 🌍 Your Environment

* OS & Device: [Windows] on [PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET 6 and Fluent UI Blazor library Version [3.5.5]

**Comment by vnbaaij** [comment]
Update: we just released v3.7.0 : https://www.nuget.org/packages/Microsoft.Fast.Components.FluentUI. First try this version and then re-submit any issues separately once tested and nt resolved. Thanks
