### ISSUE TITLE
fix: AppBar shows active menu apps for onClick with `href="@(null)"`

### ISSUE THREAD

**Issue by StephenOTT** [microsoft/fluentui-blazor#1974]
# 🐛 Bug Report

Based on the docs for AppBar, it would seem to indicate that using Href="@(null)" will let you use the OnClick function.

But doing this on the main page of a app where there is no path, other than the domain, causes the href=null "apps" to show as active.

<img width="403" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1994838/bdd400de-f56f-4e52-a679-6a49dca8e366">

## 💻 Repro or Code Sample

Use the demo app bar (https://www.fluentui-blazor.net/AppBar#withonclickevent)  on a `/` page:

such as

```
@page "/"
@inject IDialogService DialogService

<PageTitle>Home</PageTitle>

<FluentStack Orientation="Orientation.Vertical" Style="height: 330px;">
    <FluentAppBar Style="height: 100%;">
        <FluentAppBarItem Href="/"
                          Match="NavLinkMatch.All"
                          IconRest="HomeIcon()"
                          IconActive="HomeIcon(active: true)"
                          Text="Home"
                          OnClick="HandleOnClick" />
        <FluentAppBarItem Href="/AppBar"
                          IconRest="AppBarIcon()"
                          IconActive="AppBarIcon(active: true)"
                          Text="AppBar"
                          OnClick="HandleOnClick" />
        <FluentAppBarItem Href="@(null)"
                          IconRest="WhatsNewIcon()"
                          IconActive="WhatsNewIcon(active: true)"
                          Text="What's New'"
                          OnClick="ShowSuccessAsync" />
        <FluentAppBarItem Href="@(null)"
                          IconRest="IconsIcon()"
                          IconActive="IconsIcon(active: true)"
                          Text="Icons"
                          OnClick="ShowWarningAsync" />
        <FluentAppBarItem Href="/Dialog"
                          IconRest="DialogIcon()"
                          IconActive="DialogIcon(active: true)"
                          Text="Dialog"
                          OnClick="HandleOnClick" />
    </FluentAppBar>
</FluentStack>

...


```

## 🤔 Expected Behavior

using the null for href should not activate the "app".

------

on a related note, is there a way through runtime code to set the active/inactive status of a app item?

**Comment by dvoituron** [comment]
@vnbaaij The `Href` property could be "not required" and "nullable". What do you think?

```csharp
[Parameter]
public required string? Href { get; set; }
```

**Comment by vnbaaij** [comment]
> @vnbaaij The `Href` property could be "not required" and "nullable". What do you think?
> 
> ```cs
> [Parameter]
> public required string? Href { get; set; }
> ```

Yes, we can do that. It was this way when we adopted from Aspire but think it is better to change it (and it still works if you do specify a null value).

Also have a nice fix for the reported issue. PR incoming...

**Comment by sebitsi** [comment]
@vnbaaij Hi Vincent.

I tried to use AppBar with items defined. ("from list of apps" example). - version 4.7.2

How this component should work in case of href is null, empty string or "/" ?

Current state:

**href is null**
Click on this item doesn't navigate anywhere, When app is loaded selection of this item is not  visible.

**href is empty string**
Click on this item does navigate to "home page". When app is loaded selection of this item is not  visible.

**href is "/"**
Click on this item does navigate to "home page". When app is loaded selection of this item is visible.
But when click on other items, "home item" is stil rendered as active. (like in picture @StephenOTT posted)

Please advice.

**Comment by vnbaaij** [comment]
Hi @sebitsi,

An AppBarItem is nothing more than a wrapper of a standard Blazor [NavLink](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#navlink-component) component. 

A better example to see what the different options do is perhaps the [AppBar with OnClick](https://www.fluentui-blazor.net/AppBar#withonclickevent) one.

Basically, you have

- href set to '/' or any other valid link: navigation takes place. Item is set as active/selected (through active class of NavLink)
- href set to "": navigation to homepage takes place
- href set + OnClick: navigation + calling of OnClick Handler. See 'Home' item in the example I linked
- href not specified or set to `@(null)` + OnClick: Only OnClick handler gets called. Nothing changes in the previous active state so nothing new will get selected. See 'What's New' and 'Icons' items in the example

**Comment by sebitsi** [comment]
@vnbaaij Thanks for your response. My expectations are the same.

If i set href on first appbar's item then item is still rendered as @StephenOTT posted.

While researching your code I found this in baritem initialization:

```
protected override void OnInitialized()
{
    Owner!.Register(this);

    if (string.IsNullOrWhiteSpace(Href))
    {
        Match = NavLinkMatch.All;
    }
}
```
Shouldn't condition be something like ?

`if (string.IsNullOrWhiteSpace(Href)) || Href == "/") 
`
For "/" fullmatch condition should also be used.

**Comment by vnbaaij** [comment]
You can set the `Match` yourself on the AppBarItem (also shown in the example I mentioned)
