### ISSUE TITLE
docs: How to prevent cutting off values in Data Grid?

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#1979]
# 🙋 Documentation Request

I cannot find any information in the docs to prevent the `FluentDataGrid` to stop cutting off the values. I want them to be written fully out and scrollable on overflow.
![grafik](https://github.com/microsoft/fluentui-blazor/assets/32510006/6a4476e9-6803-4f38-b870-5a5a3edc5c3c)

**Comment by dvoituron** [comment]
This is due to the CSS `fluent-data-grid-cell { text-overflow: ellipsis; }` 
You can override this style, but if you don't have space to display the text, where do you want to put it? :-)

![peek](https://github.com/microsoft/fluentui-blazor/assets/8350694/cf587753-f720-4678-8284-9e4f2f7a9aab)

**Comment by vnbaaij** [comment]
And makking it scrollabel will lead to this:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/814014f7-da38-4098-bcd4-2a50fc67bc2e)

I trust you understand we are not providing on option for that out of the box 😊 You can have a tooltip on the cut-off text to show the total content. See the explenation at https://www.fluentui-blazor.net/DataGrid#typicalusage

**Comment by MarvinKlein1508** [comment]
@dvoituron 
>but if you don't have space to display the text, where do you want to put it?

Basically I want the full text to be displayed and size the columns accordingly. When I run out of screenspace it should overflow-x so I can scroll the table to the right.

**Comment by vnbaaij** [comment]
I don't think that is possible with the way the grid is rendered currently.

**Comment by MarvinKlein1508** [comment]
> I don't think that is possible with the way the grid is rendered currently.

could you take a look on this for a future version maybe? :)
