### ISSUE TITLE
fix: [Nested Tree View Styling] in [FluentDialog]

### ISSUE THREAD

**Issue by beowulf29a** [microsoft/fluentui-blazor#1988]
# 🐛 Bug Report

The root items of a TreeView do not align when nested within a FluentDialog

## 💻 Repro or Code Sample
```

<FluentDialog>
    <FluentTreeView>
        <FluentTreeItem Text="Root item 1">
            <FluentTreeItem Text="Flowers">
                <FluentTreeItem Disabled="true" Text="Daisy" />
                <FluentTreeItem Text="Sunflower" />
                <FluentTreeItem Text="Rose" />
            </FluentTreeItem>
            <FluentTreeItem Text="Nested item 2" />
            <FluentTreeItem Text="Nested item 3" />
        </FluentTreeItem>
        <FluentTreeItem Text="Root item 2" />
        <FluentTreeItem Text="Root item 3" />
        <FluentTreeItem Text="Root item 4">
            <FluentDivider></FluentDivider>
            <FluentTreeItem Text="Flowers">
                <FluentTreeItem Disabled="true" Text="Daisy" />
                <FluentTreeItem Text="Sunflower" />
                <FluentTreeItem Text="Rose" />
            </FluentTreeItem>
            <FluentTreeItem Text="Nested item 2" />
            <FluentTreeItem Text="Nested item 3" />
        </FluentTreeItem>
        <FluentTreeItem Text="Root item 5 - Leaf Erikson" />
    </FluentTreeView>
</FluentDialog>
```

## 🤔 Expected Behavior

Should look like the TreeView when not rendered within a FluentDialog
![image](https://github.com/microsoft/fluentui-blazor/assets/19234386/4932a73b-6d71-4054-8314-6e32bf9821e2)

## 😯 Current Behavior

Align the items with no children with the items with children
![image](https://github.com/microsoft/fluentui-blazor/assets/19234386/b67882a3-1934-4e5d-9fa7-d340d94693f2)

## 💁 Possible Solution

Could manually update the styling

## 🔦 Context

Would like to embed a treeview within a dialog control.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.3 and 4.7.1]

**Comment by beowulf29a** [comment]
Thanks for the update! Hopefully can get resolved in the future :)

**Comment by vnbaaij** [comment]
Closing this as it is not solvable from our side (browser issue).
