### ISSUE TITLE
fix: Content not visible in `FluentPopover`

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#1996]
# 🐛 Bug Report

When a `FluentPopover` is nested in another component, the popover's content is not visible.
It appears that the `FluentAnchoredRegion` used inside the popover does not receive the elements to display in the shadow dom:
![image](https://github.com/microsoft/fluentui-blazor/assets/143792830/53ed1245-2626-4218-99bf-7585ed00c372)

## 💻 Repro or Code Sample

Example page and component to reproduce this issue:

`Test.razor`:
```
@using Microsoft.FluentUI.AspNetCore.Components

@page "/test"

@using Microsoft.FluentUI.AspNetCore.Components

@page "/test"


<FluentButton Id="button_id" OnClick="() => _popoverOpen = !_popoverOpen">
    Toggle Popover
</FluentButton>

<NestedPopover Id="button_id" @bind-Open="_popoverOpen">
    Test text.
</NestedPopover>

@code {
    private bool _popoverOpen = false;
    }
```

`NestedPopover.razor`:
```
@using Microsoft.FluentUI.AspNetCore.Components

<FluentPopover AnchorId="@Id" @bind-Open="Open" AutoFocus="true">
    <Body>
        @ChildContent
    </Body>
</FluentPopover>

@code {
    /// <summary>
    /// Gets or sets popover opened state.
    /// </summary>
    [Parameter] public bool Open { get; set; }

    [Parameter] public string? Id { get; set; }
    /// <summary>
    /// Callback for when open state changes.
    /// </summary>
    [Parameter] public EventCallback<bool> OpenChanged { get; set; }

    /// <summary>
    /// Gets or sets the content to be rendered inside the component.
    /// </summary>
    [Parameter] public RenderFragment? ChildContent { get; set; }
}
```

## 🌍 Your Environment

* Windows
* Google Chrome Version 124.0.6367.93 (Official Build) (64-Bit)
* Blazor WASM .NET 8.0
* Microsoft.FluentUI.AspNetCore.Components 4.7.1

**Comment by vnbaaij** [comment]
You have not 'connected' the Popover to the button. You need to use the `AnchorId` parameter on the `FluentPopover` for that. 

I've editted the code in your issue above. You'll get this then:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/869655f3-4905-4635-954f-b2605b816c57)

**Comment by hksalessio** [comment]
Ahh okay, thank you! Maybe you should update the documentation to include this information? In retrospect it seems pretty obvious but I thought I was going crazy :D
