### ISSUE TITLE
FluentProfileMenu - Page content is resizing each time profile menu is opening

### ISSUE THREAD

**Issue by gryzorr** [microsoft/fluentui-blazor#1997]
# 🐛 Bug Report

Each time I'm opening profile menu, page's content is resizing because scrollbars are showing for a moment. On attached video it blinks only once but it's not true. It blinks every time.

## 💻 Repro or Code Sample

Code is generated using Your Template "Fluent blazor Web App"
Control is placed in MainLayout.

<FluentHeader>
    <FluentStack HorizontalAlignment="HorizontalAlignment.End"
                 VerticalAlignment="VerticalAlignment.Center">
        <FluentProfileMenu 
                   Status="@PresenceStatus.Available"
                   HeaderLabel="Microsoft"
                   Initials="BG"
                   FullName="Bill Gates"
                   EMail="bill.gates@microsoft.com"
                   Style="min-width: 330px;" />
    </FluentStack>
</FluentHeader>

https://github.com/microsoft/fluentui-blazor/assets/77838774/0f8ac5a7-c2d8-4bf8-9efe-4ad7d3eb80e2

_Originally posted by @gryzorr in https://github.com/microsoft/fluentui-blazor/issues/1850#issuecomment-2088478487_

**Comment by gryzorr** [comment]
Microsoft.FluentUI.AspNetCore.Components 4.7.1

**Comment by vnbaaij** [comment]
> Which FluentUI-Blazor lib version are you using?
> 
> @vnbaaij We've already solved this problem. Do you remember the work item number?

It was added in PR #1795

**Comment by gryzorr** [comment]
Indeed. TopCorner="true" do the job. Thx.
