### ISSUE TITLE
feat(docs): hotkey to jump to search box

### ISSUE THREAD

**Issue by Hona** [microsoft/fluentui-blazor#1998]
for faster navigation of the docs site, pressing `/` from anywhere, or maybe `Ctrl + K` should jump to the search box.

Again, I'm happy to implement, just need confirmation :)

**Comment by dvoituron** [comment]
`/` is probably dangerous when you will use some examples.
But `Ctrl+K` could be added.

**Comment by vnbaaij** [comment]
I think `/` is okay to add too. GithuB is using it now as a shortcut to search as well

**Comment by vnbaaij** [comment]
Hi Luke, 
Any update on this?

**Comment by vnbaaij** [comment]
Done
