### ISSUE TITLE
 In Fluent Autocomplete control, From keyboard, On tab key, it doesn't go to the close button.

### ISSUE THREAD

**Issue by PraleshGitHub** [microsoft/fluentui-blazor#2002]
# 🐛 Bug Report

On tab key, it doesn't go to the close button in Fluent Autocomplete control.

## 💻 Repro or Code Sample

Go to fluent blazor demo URL: https://www.fluentui-blazor.net/Autocomplete

## 🤔 Expected Behavior

On keyboard tab key, Focus should move to the close button in Fluent Autocomplete control.

## 😯 Current Behavior

On tab key, it doesn't go to the close button in Fluent Autocomplete control.

## 🌍 Your Environment

OS & Device: [Windows] on [PC]
Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
.NET 6 and Fluent UI Blazor library Version [3.7]

**Comment by dvoituron** [comment]
Will be solved via #2007
