### ISSUE TITLE
when press the down arrow button at the end of the populated list of Fluent autocomplete control, it continuously pronounce text in input box in NVDA.

### ISSUE THREAD

**Issue by PraleshGitHub** [microsoft/fluentui-blazor#2003]
# 🐛 Bug Report

when press the down arrow button at the end of the populated list of Fluent autocomplete control, it continuously pronounce text in input box in NVDA.

## 💻 Repro or Code Sample
Go to fluent blazor demo URL: https://www.fluentui-blazor.net/Autocomplete

## 🤔 Expected Behavior

when press the down arrow button at the end of the populated list of Fluent autocomplete control, it should not pronounce text in NVDA when arrow reach the end of the list.

## 😯 Current Behavior

when press the down arrow button at the end of the populated list of Fluent autocomplete control, it continuously pronounce text in input box in NVDA.

same is happening for up arrow.

## 🌍 Your Environment

* OS & Device: [Windows] on [PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET 6 and Fluent UI Blazor library Version [3.7]

**Comment by dvoituron** [comment]
See #2019 2019
