### ISSUE TITLE
Escape keypress does not cancel the last/top-level dialog in case of nested dialog or message box.

### ISSUE THREAD

**Issue by KrystofZacek** [microsoft/fluentui-blazor#2011]
If I display a messagbox or a dialog from a parent dialog then pressing Escape cancels the parent dialog (the one in the background) instead of propely cancelling the top-level child dialog or message box.

Environment:
Microsoft.FluentUI.AspNetCore.Components, version 4.7.2
Chrome on Windows

![image](https://github.com/microsoft/fluentui-blazor/assets/50835188/cdfea901-7ffb-4a49-befb-c12745cb976b)

**Comment by vnbaaij** [comment]
We have not tested nested Dialogs nor have we claimed that these work. It is unsupported for now.

Closing this.

**Comment by KrystofZacek** [comment]
But the nested dialogs DO work fine and it is a very useful feature. There is just this problem with Escape closing wrong modal. Would it not be be better to simply fix it?

Some other frameworks like MudBlazor support nested dialogs just fine.

Dne 5. 5. 2024 18:34 napsal uživatel Vincent Baaij ***@***.***>:

We have not tested nested Dialogs nor have we claimed that these work. It is unsupported for now.

Closing this.

**Comment by vnbaaij** [comment]
Yes, most of it works fine. But like I said, we haven't properly tested yet. It's it turns out to be easily fixed, we will fix it. But until we do and sat that out works, it is unsupported. And we have not planned to work on this yet, so no clear eta.

Don't want to turn you down or away, just want to set expectations straight.

**Comment by KrystofZacek** [comment]
Ok. Thanks for your response. Overall I find fluentui-blazor a very promissing library for our next applications and hope it will continue to grow and  improve.
Regards, Krystof.

Dne 5. 5. 2024 21:04 napsal uživatel Vincent Baaij ***@***.***>:

Yes, most of it works fine. But like I said, we haven't properly tested yet. It's it turns out to be easily fixed, we will fix it. But until we do and sat that out works, it is unsupported. And we have not planned to work on this yet, so no clear eta.

Don't want to turn you down or away, just want to set expectations straight.
