### ISSUE TITLE
change Items property in Data Grid

### ISSUE THREAD

**Issue by ProgramGeek02** [microsoft/fluentui-blazor#2027]
# 🙋 Feature Request

When you pass data to a FluentDataGrid now you have to pass an IQuerable that is quite inconvenient.
Why don't you ask for an IEnumerable and internally convert to an IQuerable?

In this way users can pass directly a list or any other implementation of IEnumerable that is a lot better when using an external framework.

**Comment by vnbaaij** [comment]
We followed what was there already in the QuickGrid code.

Usually it is sufficient to just add `.AsQueryable()`. Not such a big inconvenience, we think. At least not big enough to make a breaking change for it.

Closing this as we do not plan to do this.
