### ISSUE TITLE
feat: add dynamically recognized type to FluentSelect bind-Value

### ISSUE THREAD

**Issue by efonsecab** [microsoft/fluentui-blazor#2031]
# 🙋 Feature Request
Add dynamically recognized type to FluentSelect bind-Value, such as the Blazor's InputSelect "@bind-Value" does

We are in the process of converting some of our application to Fluent UI.
We want to convert from InputSelect to FluentSelect, however, FluentSelect seems not to follow the basic standard Blazor controls design, in which bind-Value usually recognizes the type based on the bound property.
![image](https://github.com/microsoft/fluentui-blazor/assets/3481899/4a9a6e59-3ff3-477e-a60e-0661f463ae50)

FluentSelect seems to always want a string, which means you require to do calls to .ToString() and Convert.ToXXXXX() when the source data is not a string, just as in the samples

This is a sample page we want to update.
https://github.com/pticostaricags/FairPlayCombined/blob/development/src/FairPlayCombinedSln/FairPlayDating/Components/Pages/MyUserProfile.razor

## 🤔 Expected Behavior

Make FluentSelect work similar to Blazor's InputSelect, by having @bind-Value support types other than strings, and recognizable based on the bound property.

## 😯 Current Behavior

You are forced to do lots of calls to ToString(), Convert.ToXXXX, or even create additional SelectItemProperties wrapping the code to set and get a property in another model.

## 💁 Possible Solution

Making it work as Blazor's InputSelect should be enough.

**Comment by vnbaaij** [comment]
We do not use the InputSelect as our base component and we do not follow the standard Blazor components by default.

We have your request on the ToDo list as it has been asked before (so closing this as a duplicate). Not 100% sure we will be able to put this in and definitely no ETA.
