### ISSUE TITLE
feat: add ability to pass in RenderFragment to Toast

### ISSUE THREAD

**Issue by DanielCordell** [microsoft/fluentui-blazor#2036]
# 🙋 Feature Request

It would be useful if we could pass in a RenderFragment into an overload of ShowToast, instead of requiring a generic component.

## 😯 Current Behavior

Currently this is not possible, we would need to create our own "dummy" component just to contain the content we want it to. This is speicificailly useful for static content that requires more than just a simple string e.g. formatting.

**Comment by vnbaaij** [comment]
Hi,

It would also open up the possibility to render any kind of content in the Toast which is not in line with the Fluent Design System and there is no way for us to prevent that then.
