### ISSUE TITLE
fix: dynamic tabs are not working correctly

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2043]
# 🐛 Bug Report

It looks like the dynamic tabs are broken in some way.  
https://www.fluentui-blazor.net/Tabs

Add and select seems to be broken. 

Please take a look on this video:
https://www.youtube.com/watch?v=Z3_ybHmoBkE

As you can see the first time I press the button it selects the correct tab but the indicator does not change. When I add another tab the correct tab gets selected and teh indicator changes accordingly. When I add another tab then tab 23 gets selected but the indicator jumps back to tab 21. And then the process repeats itself.

## 🤔 Expected Behavior

I would expect the correct tab to be selected with proper indication.

## 🌍 Your Environment

Tested in both Edge and Firefox

**Comment by vnbaaij** [comment]
That behavior is coming from the underlying web component and we can't fix on our side unfortunately.
