### ISSUE TITLE
fix: FluentSelect is always open when Multiple="true"

### ISSUE THREAD

**Issue by Paxol** [microsoft/fluentui-blazor#2044]
# 🐛 Bug Report

FluentSelect shows as always open when Multiple="true"

## 💻 Repro or Code Sample

This is visible in the documentation page: [https://fluentui-blazor.net/Select](https://fluentui-blazor.net/Select)

## 🤔 Expected Behavior

It should be possible to open and close the popup with options like when `Multiple` is `false`, or at least make it obvious with an explaination in the documentation + an example with the explained behavior

## 🌍 Your Environment

* OS & Device:Windows PC
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version: 4.7.2

**Comment by vnbaaij** [comment]
Unfortunately, that behavior is not supported by the underlying web component. Multiple = always open/expanded.

**Comment by Paxol** [comment]
What about the documentation part?

**Comment by vnbaaij** [comment]
What do you mean?

**Comment by Paxol** [comment]
I said in the issue that this behavior, the select always open when multiple is true, should be written in the documentation page that I linked

**Comment by vnbaaij** [comment]
I think all multiple selection examples being shown in the same way is a good indication that that is the default behavior. But I'll add a note somewhere.

**Comment by vnbaaij** [comment]
I've never gotten round to actually updating the docs. Finally doing that. It will show:
![Image](https://github.com/user-attachments/assets/679bedd8-85ee-4efb-8529-6908ad634ede)

after the PR is merged
