### ISSUE TITLE
Fluent emoji nuget package increases ram and disk usage to %100

### ISSUE THREAD

**Issue by Doc415** [microsoft/fluentui-blazor#2056]
# 🐛 Bug Report

After installing and adding 5 emojies, ram and disk usage jumps to 100% and compuler slows down

## 💻 Repro or Code Sample

just installing the package causes problem

## 🤔 Expected Behavior

Normal disk and ram usage

## 😯 Current Behavior

Compter slow down, nearly lock up

## 💁 Possible Solution

Possible memory leakage 
When i uninstall the package, things goes back to normal

## 🌍 Your Environment

Windows 11
Visual studio 2022 Version 17.9.7
Latest fluent ui emoji pack nuget (installed via vs)
![image](https://github.com/microsoft/fluentui-blazor/assets/94632226/a92ba6ef-a9da-4216-a3aa-8ab6e3030617)

**Comment by dvoituron** [comment]
Is this a problem in Visual Studio?
Can you check if you have the latest version of VS2022?
Can you check whether your anti-virus software would take time to scan the contents of this package?

This is probably a problem related to your machine configuration, as we use it regularly and it is also used on https://www.fluentui-blazor.net/Emoji

**Comment by Doc415** [comment]
> Is this a problem in Visual Studio? Can you check if you have the latest version of VS2022? Can you check whether your anti-virus software would take time to scan the contents of this package?
> 
> This is probably a problem related to your machine configuration, as we use it regularly and it is also used on https://www.fluentui-blazor.net/Emoji

Yes it happened on Visual Studio  and i have the latest version
I have stopped and restarted the antivirus and the problem seems to be resolved
Thanks for the support.

**Comment by Doc415** [comment]
Antivirus program caused the problem
