### ISSUE TITLE
fix: Column separator can get hidden when resizing columns in DataGrid

### ISSUE THREAD

**Issue by msb-incom** [microsoft/fluentui-blazor#2058]
# 🐛 Bug Report

When resizing columns in a resizable DataGrid, the column separators can become hidden making it impossible to re-extend the columns without refreshing the page.

## 💻 Repro or Code Sample

This is reproducible in the samlples at https://www.fluentui-blazor.net/DataGrid

## 🤔 Expected Behavior

I would expect the separators to stay visible so I can always resize a column back to its original width.

![image](https://github.com/microsoft/fluentui-blazor/assets/97457019/3b0f36a3-d615-4e3b-8e88-13dc782a9939)

## 😯 Current Behavior

When making a column narrower, I can do it to a point where the separator becomes invisible. Doing so will make me unable to re-size the column.

![image](https://github.com/microsoft/fluentui-blazor/assets/97457019/50c0b2d2-afdf-4438-9116-d61e565c81f8)

## 💁 Possible Solution

I believe this can be fixed by making the drag-handle `sticky` in its position.

## 🔦 Context

Possible bad user-experience when using the resizable columns feature of the DataGrid component.

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Microsoft Edge
* .NET 8.0.2 and Fluent UI Blazor library 4.7.2

**Comment by vnbaaij** [comment]
If you have a concrete solution that we can implement, that would be great. I was not able to get it fixed.

With one of the latest releases we introduced resizing per keyboard. `+` and `-` will increase/decrease focused column width in steps of 10 pixels. More importantly in your case, `Shift+r` will reset all widths to their default initial value. No need to refresh the page!

**Comment by vnbaaij** [comment]
Will test with your PR. Thanks

**Comment by vnbaaij** [comment]
PR merged. Will be in next release
