### ISSUE TITLE
Wizard in Dialog not editable

### ISSUE THREAD

**Issue by franklupo** [microsoft/fluentui-blazor#2069]
# 🐛 Bug Report

If you create a dialog with a wizard the fields are not editable

## 🤔 Expected Behavior

Fields in wizard editable

## 😯 Current Behavior

Fields in wizard not editable editable

## 🌍 Your Environment

* OS & Device:  [Windows]
* Browser [Google Chrome]
* .NET and Fluent UI Blazor library Version [8.0.2 and v4.7.2]

**Comment by vnbaaij** [comment]
This is not an issue report we can work with.
- **No** reproduction steps
- **No** reproduction code or repo
- **No** possible solution
- **No** context

Closing this. You can try again when you're ready to help us helping you.
