### ISSUE TITLE
feat: add possibility to change field's cursor icon when ReadOnly/Not Editable

### ISSUE THREAD

**Issue by f4n0** [microsoft/fluentui-blazor#2078]
# 🙋 Feature Request
add possibility to change field's cursor icon when ReadOnly/Not Editable

## 😯 Current Behavior
Right now, with ShadowRoots, it is quite impossible to change the expected styles
And for my App, having the cursor to "Not Allowed" is ugly and wrong!

**Comment by vnbaaij** [comment]
Hi,

We are not going to change these as ther are being set by the underlying web components script.

It is definitely not _quite impossible_ to change this to something of your liking. Doing something like 
```
fluent-text-field::part(control) {
   cursor: all-scroll;
}
```
should be enough.

If you want to style things outside of the Fluent Design, you will **have to** learn and know how to work with the part selector. 

See also #2070 for some more information.
