### ISSUE TITLE
Autocomplete with virtualisation shows just a blank list no items are shown in firefox, works fine in chrome and edge browser.

### ISSUE THREAD

**Issue by thanseer-pk** [microsoft/fluentui-blazor#2079]
# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
See #1978
