### ISSUE TITLE
fix: `FluentInputFile` cannot accept dragged files when nested inside a `FluentDropZone`

### ISSUE THREAD

**Issue by ApacheTech** [microsoft/fluentui-blazor#2080]
# 🐛 Bug Report

When nesting a `FluentInputFile` within a `FluentDropZone`, it loses the ability to accept dragged files as input.

## 🔦 Context

The concept for this is dashboard widgets. We are creating re-usable components, and then we are able to display them either as stand-alone pages, as part of a composite page, or in this case, as a tilable widget that can be displayed on the dashboard, when the user logs in. Think, Grafana, WordPress Admin, etc.

This involves being able to host a dynamic component within a `FluentDropZone` cell. These are rendered within a grid on the dashboard, with logic to be able to move them around, lock them in place, etc.

## 💻 Contextual Code Sample

**Index Page**
```HTML
    <FluentDragContainer TItem="object" OnDropEnd="OnDropEnd">
        @* ... *@
        <FluentDropZone Id="@cell.TypeName" Draggable="@cell.Draggable">
            <DashboardWidget Cell="@cell" OnCellChangeAsync="RefreshWidgetsAsync" />
        </FluentDropZone>
        @* ... *@
    </FluentDragContainer>
```

**Within File Upload Widget**
```HTML
            <FluentInputFile Id="file-uploader"
                             Mode="InputFileMode.Stream"
                             Multiple="false"
                             MaximumFileSize="@(1024 * 1024 * 1024)"
                             DragDropZoneVisible="true"
                             Accept=".csv, .xlsx, .zip"
                             Class="p-4"
                             Style="border: dashed 1px"
                             OnCompleted="@OnCompleted">

                <ChildContent>
                    <div class="w-full h-full flex flex-col items-center justify-center">
                        <label for="file-uploader">
                            <FluentIcon Value="new Icons.Regular.Size24.ArrowUpload()" />
                        </label>
                        <div>
                            Drag a file here to upload or
                            <label for="file-uploader">browse</label>
                            for them <span class="text-red-500">*</span>
                        </div>
                    </div>
                </ChildContent>

                <ProgressTemplate>
                    <div class="progress custom-progress">
                        <FluentProgress Visible="@(_progressPercent is not null)"
                                        Min="0"
                                        Max="100"
                                        Value="@_progressPercent" /><br />
                        @_progressTitle
                    </div>
                </ProgressTemplate>

            </FluentInputFile>
```

## 💻 Minimal Reproduction

```html
<FluentDragContainer TItem="object">
    <FluentDropZone Draggable="false" Droppable="true">
        <FluentInputFile Mode="InputFileMode.Stream"
                         Multiple="false"
                         DragDropZoneVisible="true"
                         Style="border: dotted 1px; padding: 1rem;"
                         OnCompleted="args => { Console.WriteLine(args.Single().Name); }">
            <ChildContent>
                <label for="file-uploader">
                    <FluentIcon Value="new Icons.Regular.Size24.ArrowUpload()" />
                </label>
                <div>
                    Drag a file here to upload or
                    <label for="file-uploader">browse</label>
                    for them
                </div>
            </ChildContent>
        </FluentInputFile>
    </FluentDropZone>
</FluentDragContainer>
```

## 🤔 Expected Behaviour

The drag and drop zone for the file upload component should take precendence over the `FluentDropZone` for dragged files.

## 😯 Current Behaviour

Any files that are dragged into the drag and drop area of the `FluentInputFile` are ignored. The `FluentDropZone` flickers as if indicating it can be dropped onto, but only intermittently. Other times, it acts as if the file has been dropped into the browser window, not onto the page, and tries to open/download the file locally.

## 💁 Possible Solution

I'm not sure where the conflict lies.

## 🌍 Your Environment

- OS: Windows 11
- Browsers: Firefox, Chrome, Opera, Edge
- Framework: .NET CoreCLR 8.0
- FluentUI: v4.7.2

**Comment by vnbaaij** [comment]
Hi Peter,

Please supply us with **ready to run** reproduction code in the form of a project or repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will get closed automatically in **3** days

Help us to help you. Thanks

**Comment by ApacheTech** [comment]
Added: minimal reproduction

```html
<FluentDragContainer TItem="object">
    <FluentDropZone Draggable="false" Droppable="true">
        <FluentInputFile Mode="InputFileMode.Stream"
                         Multiple="false"
                         DragDropZoneVisible="true"
                         Style="border: doted 1px; padding: 1rem;"
                         OnCompleted="args => { Console.WriteLine(args.Single().Name); }">
            <ChildContent>
                <label for="file-uploader">
                    <FluentIcon Value="new Icons.Regular.Size24.ArrowUpload()" />
                </label>
                <div>
                    Drag a file here to upload or
                    <label for="file-uploader">browse</label>
                    for them
                </div>
            </ChildContent>
        </FluentInputFile>
    </FluentDropZone>
</FluentDragContainer>
```

**Comment by dvoituron** [comment]
I don't think it's possible to combine the two Drop zones easily.
Perhaps you could add an `Edit` button that would activate the **FluentDragContainer** mode?

**Comment by ApacheTech** [comment]
That's what I've done as a work-around. I've got a toggle for "Edit Mode", and "Display Mode".

Some observations / brain dump:

You can combine Drop Zones to the point that you can create cells within a grid, with the `FluentDropZone`s. I have three columns, and different amounts of items within each column. Each column is a drop zone, and each cell is a draggable DropZone within a droppable DropZone. Each cell is given a column/row assignment. The cells drop zones take precedence over the column drop zones, so I can move the contents of each cell around by dragging them. I have a gap between each cell, and dropping into the gaps will drop into the column. 

This shows, at least, that the drop zones do have a hierarchy between them. But this hierarchy doesn't seem to translate to the file uploader within the cell. The file uploader doesn't currently use a `FluentDragContainer`; it uses the vanilla attributes:

```html
<div class="@ClassValue"
     style="@StyleValue"
     drop-files="@DropOver"
     disabled="@Disabled"
     @ondragenter="@(e => DropOver = true)"
     @ondragenter:stopPropagation
     @ondragover="@(e => DropOver = true)"
     @ondragover:stopPropagation
     @ondragleave="@(e => DropOver = false)"
     @ondragleave:stopPropagation
     @ondragend="@(e => DropOver = false)">
```

I'm wondering whether changing this to use the Fluent drag and drop system would put it into the hierarchy that already exists.

Failing all of that, it would still be useful to add the limitations to the docs for both the drag and drop system, and for any component that has a drag and drop capability that gets disabled by the drop zones.

**Comment by vnbaaij** [comment]
I experimented a bit with trying to get this to work and succeeded.  What I dis is I added a ``FluentInputFileDropZone which is basically a copy of the standard dropzone but with all the `preventDefault`'s removed.

As this is a bit of a niche/edge case, I won't be adding this as a component to the library, but you can use it as a solution in your own project.
