### ISSUE TITLE
Add missing values to FluentStack/HorizontalAlignment property type

### ISSUE THREAD

**Issue by JarJasAskom** [microsoft/fluentui-blazor#2084]
FluentStack is using flex display css style to stack its children. 

FluentStack is using justify-content css style to horizontally align childrn.

It's HorizontalAlignment property is missing three values: space-evenly, space-around, space-between.

**Comment by dvoituron** [comment]
The goal of **FluentStack** is not to reproduce the `flex` style, but to provide a simple, easy-to-use component.
You can use the **FluentSpacer** to add space between elements.
You can also add a `Style="justify-content: space-around"` to customize your rendering.

**Comment by JarJasAskom** [comment]
I've added this Style in my code. 

But maybe somehow adding space-between to HorizontalAlignment will not make HorizontalAlignment not simple and not easy-to-use?

**Comment by dvoituron** [comment]
I understand your request, but this is not currently planned.
What's more, `HorizontalAlignment` and `VerticalAlignment` are used by other components that don't support these properties: Dialog, Label, DataGrid.
