### ISSUE TITLE
FluentTree - CurrentSelected does not change if you have an element in the FluentTreeItem

### ISSUE THREAD

**Issue by Valkozaur** [microsoft/fluentui-blazor#2085]
🐛 Bug Report
Description
When using a span or a div inside of the FluentTreeItem content, the child element is not always being selected.

Reproduction Steps
Include the following code in your project:
```
<FluentTreeView>
    @foreach (var group in _groups)
    {
        <FluentTreeItem>
            <span>@group.Name</span>
            @foreach (var item in group.items)
            {
                <FluentTreeItem>
                    <span>@item.Name</span>
                </FluentTreeItem>
            }
        </FluentTreeItem>
    }
</FluentTreeView>
```
Run the project and observe the behavior.

Expected Behavior
When there is a span inside of the FluentTreeItem, the node should still be selectable.

Current Behavior
The tree node is not being selected when a span is present inside the FluentTreeItem.

Additional Information
This issue can be noticed when using the provided code.

**Comment by vnbaaij** [comment]
Example is not ready-to-run. Don't nknow what is in `_groups` and how it is defined. Please add additional repro steps.

**Comment by dvoituron** [comment]
This is the behavior expected by the web component used in the background.
We cannot modify this behavior.

But, the next Release will feature an `Items` property and an `ITreeViewItem` interface to manage lists of items like yours.
https://preview.fluentui-blazor.net/TreeView
