### ISSUE TITLE
fix: FluentEditForm fields are non editable when wrapped in FluentTab and using version 4.7.2

### ISSUE THREAD

**Issue by miszelek** [microsoft/fluentui-blazor#2089]
# 🐛 Bug Report

FluentEditForm fields are non editable when wrapped in FluentTab and using version 4.7.2

Below code is not working in latest 4.7.2 version but is correctly working in versions 4.6.0-4.7.1.

Tried different scenario's that also work:
- remove the @onkeydown part
- remove the FluentTab part

## 💻 Repro or Code Sample

```
<FluentTabs>
    <FluentTab Label="Unit" Icon="@(new Icons.Regular.Size24.LeafOne())" Id="tab-unit">
        <FluentCard>
            <FluentEditForm Model="_productSearch" FormName="Product" OnSubmit="searchProducts" @onkeydown:preventDefault="true">
                <h3>Product:</h3>
                <FluentGrid>
                    <FluentGridItem sm="12">
                        <FluentTextField Class="w-100" Label="Name" @bind-Value="_productSearch.Name" />
                    </FluentGridItem>
                </FluentGrid>
            </FluentEditForm>
        </FluentCard>
    </FluentTab>
</FluentTabs>
```

## 🤔 Expected Behavior

Fields inside the FluentEditForm should be editable

## 😯 Current Behavior

Fields inside the FluentEditForm are not editable

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Browser: Google Chrome
* .NET and Fluent UI Blazor library Version:  8.0.2 and 4.7.2

**Comment by vnbaaij** [comment]
There is no ready to run reproduction code provided.  Please supply us with reproduction code in the form of a project or repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will get closed automatically in **3** days

Help us to help you. Thanks

**Comment by miszelek** [comment]
[ReproBlazorFluentUI.zip](https://github.com/microsoft/fluentui-blazor/files/15489521/ReproBlazorFluentUI.zip)

Included a repro solution. Index.razor contains sample code above.
Change the FluentUI Components version to 4.7.2 to see the described issue.

If you need more info, please let me know. Thanks.

**Comment by vnbaaij** [comment]
I can't find what commit would have caused this behavior to change. In your (Bootstrap based) demo, removing the Tab works indeed. But trying that in our demo environment does not make it work. 

What does work in both cases is removing the `@onkeydown:preventDefault="true"` and I'm not understanding why you would even want to have that on the `(Fluent)EditForm`.  (`FluentEditForm` is just a thin wrapper for `EditForm` which only does something useful when used in combination with the Wizard component)

So, as there is a workaround by not using the `@onkeydown`, I'm closing this issue.

**Comment by miszelek** [comment]
OK, thanks for the information and investigation.

The EditForm gives me input validation before Submit. My reason for the @onkeydown was to prevent the OnSubmit to fire when the Enter key was pressed.

But perhaps there is another (and better) way to prevent that?

**Comment by miszelek** [comment]
Did some more research and found a way to prevent OnSubmit fire after Enter.
The ```@onkeydown:preventDefault``` does not work, but handling it yourself does.

```
public static class Form
{
    private static bool _allowSubmit = true; 

    public static void HandleKeyDown(KeyboardEventArgs args)
    {
        _allowSubmit = args.Key != "Enter";
    }

    public static bool AllowSubmit()
    {
        if (_allowSubmit) return true;
        _allowSubmit = true;
        return false;
    }
}
```

Usage: Set ```@onkeydown="Form.HandleKeyDown"``` on the EditForm and do this in Submit() handler: ```if (!Form.AllowSubmit()) return;```

Btw, I love FluentUI, keep up the good work!
