### ISSUE TITLE
fix: Double click needed for expanding/collapsing child elements in FluentNavGroup when prerendering is turned off

### ISSUE THREAD

**Issue by emetrix** [microsoft/fluentui-blazor#2097]
# 🐛 Bug Report

In a Blazor SSR project with PreRendering turned off when I first click on a FluentNavGroup Expand Icon the subitems are expanded or collapsed as they should.
But when I then click on the FluentNavGroup Title Text a short flickering occurs and the subitems are not expanded nor collapsed.
The displaying or hiding of the subitems occurs correctly when I click on the Title a second time.

## 💻 Repro or Code Sample

Turn off prerendering for HeadOutlet and Routes:

`@rendermode="new InteractiveServerRenderMode(prerender: false)`

1) Click the expand icon
![image](https://github.com/microsoft/fluentui-blazor/assets/13239872/2632fc5b-7288-4509-9ef5-fdb5c816550f)

2) Child items are expanded
![image](https://github.com/microsoft/fluentui-blazor/assets/13239872/3aa3538f-935e-442c-88a9-2b38e2f7d006)

3) Click the Title Text
![image](https://github.com/microsoft/fluentui-blazor/assets/13239872/8be27ac2-7e9f-40b1-a4be-6e50c5202cfa)

4) A flickering occurs but child item are NOT being collapsed
![image](https://github.com/microsoft/fluentui-blazor/assets/13239872/3aa3538f-935e-442c-88a9-2b38e2f7d006)

5) Click the Title Text a second time 
![image](https://github.com/microsoft/fluentui-blazor/assets/13239872/0f0bf53b-f513-4737-a5d7-e73c7e194e7a)

6) Now the child items are collapsed
![image](https://github.com/microsoft/fluentui-blazor/assets/13239872/fbd6bad8-28db-4721-8376-2e9643ddaeaa)

This also happens vice versa: When I collapse sub items by the expand icon two clicks on the title text are neccessary to expand the sub items again...

When Blazor Server pre-rendering is turned on it works as expected. But due to different circumstances I can't/don't want to use pre-rendering in my project.  

## 🤔 Expected Behavior

Expanding / Collapsing child items should be done with one click.

## 😯 Current Behavior

see bug description

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Browser Microsoft Edge
* .NET 8.0.4 and Fluent UI Blazor library Version 4.7.2

**Comment by vnbaaij** [comment]
I can't reproduce it. Please supply a ready-to-run repo sample or more refined steps on how to reproduce.

For reproducing, I created a new project based on our template with interactivity render mode=server and interactivity location set to global. I added the rendermode change you supplied and added a group with items to the nav menu.

**Comment by emetrix** [comment]
Thank you Vincent, please see the sample "https://github.com/emetrix/Samples.BlazorFluentUI-FluentNavGroup". As far as I remember I only modified the files App.razor (for rendermode) and NavMenu.razor (for adding FluentNavGroup with subitems).

I hope that makes it possible to reproduce the issue. Otherwise please let me know...

**Comment by emetrix** [comment]
Hi Vincent, do you think a fix will be possible in one of the next releases or is the mentioned workaround a permanent one ?

**Comment by vnbaaij** [comment]
I'm guessing the workaround will be permanent. 

There are not that many case where prerendering is not being used while the effort we need to take to solve in a good and solid way is pretty high.
