### ISSUE TITLE
feat: add support for Virtualize for FluentCombobox

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2103]
# 🙋 Feature Request

`FluentCombobox` should support `Virtualize` just like the `FluentAutocomplete` component. 

## 🔦 Context
I'm using this component to allow the user to filter a list of countries (in my case 250 countries). The large amount of countries results in a noticeable rendertime for the page.

**Comment by vnbaaij** [comment]
With the autocomplete, we control the rendering of the 'list'. That is why we can do the virtualization. For the combobox the list comes from the web component. We can't get in that render process. @dvoituron correct?

**Comment by dvoituron** [comment]
Yes. Exactly. 

If you have a large list of items, ˋFluentAutocompleteˋ would be better.

**Comment by MarvinKlein1508** [comment]
Hey @vnbaaij & @dvoituron thanks for your input on this topic! :)

My problem with the `FluentAutocomplete` component is the extra amount of work which is required in order to get a 1:1 realtionship. Although the component exposes `@bind-SelectedOption` this option is not supported. In order to get it working for just 1 item all of this is necessary: 

1. Set `MaximumSelectedOptions="1"`
2. Define an IEnenumerable<TOption> as a property
3. Bind `@bind-SelectedOptions` to an IEnumerable<TOption>
4. Bind `@bind-SelectedOptions:after` and do manual mapping
5. On pageload the TOption from your actual model needs be assigned to your IEnumerable of step 2.

Or when we talk in code:
```aspnet
@code {
    private IEnumerable<Country> CountryAutocomplete { get; set; } = [];
    
    // Assume MyInput contains Country and CountryId
    public MyInput? Input { get; set; } 
    protected override async Task OnInitializedAsync()
    {

        Input = await GetInputAsync(); 
        if (Input is not null)
        {
            if(Input.Country is not null)
            {
                CountryAutocomplete = [Input.Country];
            }
        }
    }

    private void OnCountryChanged()
    {
        if (Input is null)
        {
            return;
        }

        var _country = KostenstelleAutocomplete.FirstOrDefault();
        
        Input.Country = _country;
        Input.CountryId = _country?.CountryId;   
    }
}
```

It would be great if this process would be as easy as with the `FluentCombobox` where I only need to bind to the actual property of my object.

**Comment by MarvinKlein1508** [comment]
Also aren't the options rendered here?
https://github.com/microsoft/fluentui-blazor/blob/758dce12b21e91021d67d05d7ddc0268f4266191/src/Core/Components/List/ListComponentBase.razor#L11

**Comment by vnbaaij** [comment]
It's not about the rendering of the options, it is about the list the options are rendered in.

**Comment by dvoituron** [comment]
You can find an example of using Autocomplete with 1 item on this page, section "Culture"

https://www.fluentui-blazor.net/DateTime

**Comment by MarvinKlein1508** [comment]
@dvoituron yes as you can see it's quite hard to do. Now throw a new object instance from the database into the pot as well and it will drive you crazy! :)
