### ISSUE TITLE
docs: fix/add Toast / Custom component example / Razor code

### ISSUE THREAD

**Issue by JarJasAskom** [microsoft/fluentui-blazor#2105]
# 🙋 Documentation Request

Toast documentation, "Custom component" example.

Toast example contains line:

 ToastService.ShowToast<MyToastComponent, MyToastData>(new ToastParameters<MyToastData>()

but 

Example code does not contain source of MyToastComponent and MyToastData .

## 💁 Possible Solution

Add MyToastComponent razor code and MyToastData C# code.

**Comment by dvoituron** [comment]
It would be a good idea to add these files to the documentation.

You can find the code in the GitHub repo and [this page in particular](https://github.com/microsoft/fluentui-blazor/blob/758dce12b21e91021d67d05d7ddc0268f4266191/examples/Demo/Shared/Pages/Toast/Examples/MyToastComponent.razor#L4).

**Comment by vnbaaij** [comment]
Fixed in next release. Files added to example
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/2f7ac156-4eaf-455d-9c08-3f3ddfa8449a)
