### ISSUE TITLE
Add CultureInfo.InvariantCulture to ToString("0.00")

### ISSUE THREAD

**Issue by adospace** [microsoft/fluentui-blazor#2107]
Hi,

I think there is a problem with the following line:

https://github.com/microsoft/fluentui-blazor/blob/758dce12b21e91021d67d05d7ddc0268f4266191/src/Core/Components/Progress/FluentProgress.razor.cs#L93

Opening the web app with a culture different from US (i.e. Italian) the FluentProgress height in Indeterminate mode is set to 0.
The problem is that using my culture "--stroke-width" variable is set to, for example, 1,67 instead of 1.67 causing the browser to be unable to interpret the value as a correct float.

I've verified that all other ToString("...") correctly pass the InvariantCulture so I believe the problem is only in the above line.

I'll be happy to create a PR if required,

Thanks

**Comment by dvoituron** [comment]
You're right. The `ToString("0.00")` should be updated to `ToString("0.00", CultureInfo.InvariantCulture)`.

Yes, please create a PR :-)
