### ISSUE TITLE
fix: clicking ColumnOptions in FluentDataGrid throws exception

### ISSUE THREAD

**Issue by joriverm** [microsoft/fluentui-blazor#2108]
# 🐛 Bug Report

My Coworker pointed out that in our WPF/Hybrid application clicking on the filter button in the fluent data grid caused it to throw an exception. after some investigation i noticed that it is throwing the exception due to DataGrid javascript having a mistake.

Code : https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/DataGrid/FluentDataGrid.razor.js#L69
the function is triggered with `GridElement` set to the fluent-data-grid, but it does not have any property called `_rowItems`, causing it to throw an exception.

However, when running the website in the browser, it looks like the javascript exception is caught and 'handled' (by the wasm blazor framework?).
when i run the website in firefox, which can pause execution even if the exception is handled, it clearly shows it can't find _rowItems
![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/152971ab-1dee-42e1-b087-bec69a69a341)

but its marked handled and doesn't trigger any exception handlers.
in WPF/Hybrid we get the following : 
![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/4b5262f6-c8c0-4256-b229-6728b46cfd2b)
which is unhandled and throws an exception inside our application.

## 💻 Repro or Code Sample

just clicking on the filter button in the demo site is enough to trigger the javascript exception
![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/e7841c7b-4f02-4d68-b950-7702c95ff2a0)

## 🤔 Expected Behavior

no exception to happen

## 😯 Current Behavior

an exception is thrown in javascript which is handled in browser, but not inside an hybrid app. see analysis above

## 💁 Possible Solution

an added check to see if `_rowItems` exists before accessing it prevents the exception from being thrown, but before making a PR i wanted to check what it was for and if it can be replaced with `_rowElements` which does seem to exist and (seems) to have the rows. then again, if the function never worked because it threw an exception, is it even needed?
any comments about this code @vnbaaij before i make a PR?

## 🔦 Context
constant errors are thrown in the Hybrid Application when rendering the datagrid in question

## 🌍 Your Environment

* OS & Device: Windows 10 on PC
* Browser : Microsoft Edge, Google Chrome, Mozilla FireFox
* .NET and Fluent UI Blazor library Version : 8.0.2 and 4.4.1

**Comment by vnbaaij** [comment]
I think it can be replaced with `_rowElements`. It needs to be tested if that is indeed the case. The function is needed to make sue the options windows is positioned right. Perhaps no one has run into situations where that happens incorrectly yet

**Comment by joriverm** [comment]
thanks for the quick response & merging! 
ill keep an eye on when the next version is posted and update our internal references :)
