### ISSUE TITLE
docs: Make Aside (In this article) scrollable

### ISSUE THREAD

**Issue by f4n0** [microsoft/fluentui-blazor#2111]
# 🙋 Documentation Request
In the DataGrid Page, the aside is too long, and difficult to see everything without scrolling the entire page. 

## 💁 Possible Solution
to the aside tag add the following CSS:
```
max-height: calc(100dvh - 90px); //get from body-content CSS
overflow-y: auto;
```

**Comment by vnbaaij** [comment]
This will be rolled out to the demo site with next release.
