### ISSUE TITLE
feat: add multi-column to/in combobox

### ISSUE THREAD

**Issue by petermanesis** [microsoft/fluentui-blazor#2124]
It would be very nice if existing Combobox support multi column in dropdown list. It is very common in applications where the field for selecting for example a customer need to provide more details than a name, (e.g. to also include: phone, email, social number e.t.c. ). The same happens with products, more columns are needed so as to identify and select the correct product. Attached is a sample screenshot of a multicolumn combobox I used in a windows desktop application, that makes more clear.
![demo](https://github.com/microsoft/fluentui-blazor/assets/57197153/47edcd2b-4237-4588-b035-cb121032dbd8)
Please contact me for any details. Thanks!

**Comment by dvoituron** [comment]
You could use `OptionTemplate` to customize each items. And to define your table cells.

**Comment by petermanesis** [comment]
Thanks Denis, I didn't know that way. I will try it.
Once more... congratulations for this beautiful library.
