### ISSUE TITLE
feat: add [required] to [Label]

### ISSUE THREAD

**Issue by Aloento** [microsoft/fluentui-blazor#2128]
# 🙋 Feature Request

add [required] to [Label] like:

https://react.fluentui.dev/?path=/docs/components-label--default#required

**Comment by vnbaaij** [comment]
Already supported.

**Comment by Aloento** [comment]
@vnbaaij Where?
https://www.fluentui-blazor.net/Label

**Comment by vnbaaij** [comment]
Look at example in https://www.fluentui-blazor.net/Forms 
It is offered by the `FluentInputLabel` component.
