### ISSUE TITLE
Maximum call stack size exceeded when using FluentDesignSystemProvider and a FluentCard

### ISSUE THREAD

**Issue by jaydeboer** [microsoft/fluentui-blazor#2129]
# 🐛 Bug Report

Using a `FluentCard` in a Blazor Server app that uses `FluentDesignSystemProvider` to set the accent color causes a `RangeError: Maximum call stack size exceeded` exception on the javascript console.

## 💻 Repro or Code Sample

Starting with a default .net 8 Blazor server app then change:

`App.razor` Wrap routes with a FluentDesignSystemProvider

```csharp
@using Microsoft.FluentUI.AspNetCore.Components
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <base href="/"/>
    <link rel="stylesheet" href="bootstrap/bootstrap.min.css"/>
    <link rel="stylesheet" href="app.css"/>
    <link rel="stylesheet" href="BlazorApp1.styles.css"/>
    <link rel="icon" type="image/png" href="favicon.png"/>
    <HeadOutlet/>
</head>

<body>
<FluentDesignSystemProvider AccentBaseColor="#FF1200" > 
    <Routes/>
</FluentDesignSystemProvider>
<script src="_framework/blazor.web.js"></script>
</body>

</html>
```

Then change `Home.razor` to

```csharp
@page "/"
@using Microsoft.FluentUI.AspNetCore.Components

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<FluentCard>
    
</FluentCard>
```

## 🤔 Expected Behavior

No Errors on the javascript console in the developer tools.

## 😯 Current Behavior

The javascript console contains the following error.
```
web-components.js:17803 Uncaught RangeError: Maximum call stack size exceeded
    at i.toStringHexRGB (web-components.js:17803:3)
    at f (web-components.js:18704:73)
    at lt (web-components.js:18724:36)
    at Ll (web-components.js:18731:11)
    at Object.evaluate (web-components.js:19271:12)
    at h.<anonymous> (web-components.js:19275:140)
    at h.observe (web-components.js:534:27)
    at jn.handleChange (web-components.js:10582:51)
    at h.notify (web-components.js:389:14)
    at h.call (web-components.js:585:14)
```

## 🌍 Your Environment

* Windows and MacOS
* Browser [Microsoft Edge, Brave]
* .NET 8.0.6 and Fluent UI Blazor 4.7.2

**Comment by jaydeboer** [comment]
I am so sorry, I changed to `<FluentDesignTheme CustomColor="#FF1200" Mode="DesignThemeModes.Light" />` and that fixes the issue.

**Comment by dvoituron** [comment]
We will verify this error. But you probably could solve that using the `MinimalStyle` attribute.

**Comment by martingagne** [comment]
I am having the exact same problem, but even when specifying the CustomColor and Mode. :(

<FluentDesignTheme StorageName="my-theme" CustomColor="#1fad90" Mode="DesignThemeModes.Light" />

**Comment by paule96** [comment]
That's still an Issue. I have it in dark mode with the custom color: `#1B263B`
