### ISSUE TITLE
feat: [DataGrid] Deselect all other items when row is clicked (not checkbox)

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#2130]
# 🙋 Feature Request

Sorry for the title, I didn't really know how to express myself better.

I would like the `FluentDataGrid` to have an option for deselecting all items when a row is clicked and only keeping this row as selected. This is not the same as single select mode. The following video might be better at explaining things than I am:

https://github.com/microsoft/fluentui-blazor/assets/143792830/99c428cd-957d-434e-bf7b-7f274696a59f

The video was taken in the Microsoft admin center, so I guess if this is something Microsoft is using, it might be worth adding to the Library :D

**Comment by hksalessio** [comment]
Maybe I could get around a new feature for this if you provided a "OnCellClick" event. I mean, "OnCellFocus" exists as well, so why not add it for the sake of completeness.

**Comment by vnbaaij** [comment]
We are not going to implement that (for now). It is difficult to do because the web component does not have a click event on the cell

**Comment by hksalessio** [comment]
But wasn't the "OnRowClick" functionality implemented without the web component's click event as well? I could provide a feature request but only if you would be willing to add it to the library

**Comment by vnbaaij** [comment]
Yes, that is true. But implementing that for all cells as well will lead to performance challenges, I think.

If you want to work on this and it turns out performance stays on par then we will want to merge it.
