### ISSUE TITLE
FluentCheckbox issue

### ISSUE THREAD

**Issue by 282030166** [microsoft/fluentui-blazor#2132]
The onchange event of FluentCheckbox cannot correctly obtain value, but the native input can obtain it correctly.

    <input type="checkbox" checked="@c1" @onchange="onchange1" />     
    <FluentCheckbox Value="@c2" @onchange=@onchange2></FluentCheckbox>  // issue

    bool c1 = true;
    bool c2 = false;

    public void onchange1(ChangeEventArgs c1)
    {
        Console.WriteLine(c1.Value);
    }

    public void onchange2(ChangeEventArgs c2)
    {
        Console.WriteLine(c2.Value);
    }

**Comment by dvoituron** [comment]
**FluentCheckbox** is a component that wraps the `fluent-checkbox` WebComponent. 
It does not work like the default HTML input element and does not contain the `onchange` attribute.

You need to bind the value and you can use `:after` to call a method if you wish.

```razor
<input type="checkbox" checked="@v1" @onchange="OnChange1" />
<FluentCheckbox @bind-Value="@v2" @bind-Value:after="@OnChange2"></FluentCheckbox>

@code
{
    bool v1 = true;
    bool v2 = false;

    public void OnChange1(ChangeEventArgs c1)
    {
        Console.WriteLine(c1.Value);
    }

    public void OnChange2()
    {
        Console.WriteLine(v2);
    }
}
```
