### ISSUE TITLE
Tree component

### ISSUE THREAD

**Issue by 282030166** [microsoft/fluentui-blazor#2134]
Do you have any plans to implement the components shown in the following diagram.

![image](https://github.com/microsoft/fluentui-blazor/assets/22317927/edff9f09-e5a8-4527-9cd4-9901fc3cbda5)

**Comment by vnbaaij** [comment]
No, no plans for that. There are too many issues with using the tree web components like that.

**Comment by dvoituron** [comment]
No... But using the new `ItemTemplate`, you could develop it yourself.
https://preview.fluentui-blazor.net/TreeView#withitems
