### ISSUE TITLE
Fluent Blazor Web App bogus focus on first body element

### ISSUE THREAD

**Issue by kjkrum** [microsoft/fluentui-blazor#2136]
1. Install Fluent templates as per the docs, getting whatever version is current as of today:

>dotnet new install Microsoft.FluentUI.AspNetCore.Templates

2. Create a Fluent Blazor Web App with the following settings:

![FluentTemplateOptions](https://github.com/microsoft/fluentui-blazor/assets/1007080/d88ec83e-74f6-4a96-98e3-5e021b06d6be)

3. Launch it.

The first element of the home page has a box around it as if it's focused:
![blazor-fluent-focus](https://github.com/microsoft/fluentui-blazor/assets/1007080/a509a9a9-2af0-4a42-8e6e-8ce0cd252714)

Clicking anywhere or pressing tab removes the box. The box does not appear when navigating to another page in the same circuit. However, opening a page in a new circuit by right-clicking it in the nav menu and opening in a new tab does display the box.

I'm seeing this in Firefox and Edge. The standard Blazor Web App template does not exhibit this behavior.

**Comment by dvoituron** [comment]
Do you have this in your App.razor?

ˋ<FocusOnNavigate RouteData="@routeData" Selector="h1" />ˋ

See https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#focus-an-element-on-navigation

**Comment by kjkrum** [comment]
This seems to be caused by the following line in `Routes.razor`:

```
<FocusOnNavigate RouteData="routeData" Selector="h1" />
```

**Comment by vnbaaij** [comment]
Yes, it comes from that line. We copied that over from the standard templates.

Closing this as it is not really an issue and can be 'fixed' easily.

**Comment by kjkrum** [comment]
Ah, so it's a difference in style. Oddly it doesn't appear when you navigate, only on the first page of a new circuit.
