### ISSUE TITLE
fix: expanding & collapsing in FluentNavMenu

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2141]
# 🐛 Bug Report

When using a `FluentNavGroup` and tap on it in mobile view it closes the opened navigation. When you use the dropdown buttons instead the navigation will open just like expected without closing the mobile menu.

See this video for demonstration
https://github.com/microsoft/fluentui-blazor/assets/32510006/ddb5f28b-c695-419b-b262-cdaa008a96d1

## 💻 Repro or Code Sample

I've created a small sample repo which can be found here: https://github.com/MarvinKlein1508/ExpandBugFluentUi

## 🤔 Expected Behavior

I would expect the navigation to expand/collapse without being closed

## 😯 Current Behavior

The navigation expands/collapses but also closes the mobile menu

## 🔦 Context

For some reason it seems to work in the demo app. But I couldn't figure out why.

## 🌍 Your Environment
.NET 8.0.6
Firefox latest version
Safari on iOS 17.5.1

**Comment by vnbaaij** [comment]
To get the same working as on the demo site, line 4 of NavMenu.razor should be changed to:
```
<nav class="sitenav" aria-labelledby="main-menu" >
```

(ie remove the onclick code)

**Comment by MarvinKlein1508** [comment]
@vnbaaij in doing so, the nav won't close at all unless you close it manually. Is there any easy way to only close it when you click on an element which has an href defined?

**Comment by coderdnewbie** [comment]
Vincent,

I have a theoretical solution to this problem. 

Keep the onclick code in class="sitenav" but have a StopPropagation attribute in FluentNavGroup so that the event is not bubbled up. Therefore for this to work a StopPropagation attribute would be needed in the FluentNavGroup like it is in the FluentKeyCode.

Is this possible? What do you think?

Thanks.

**Comment by vnbaaij** [comment]
@MarvinKlein1508, @coderdnewbie see PR #2183 for a better solution for both demo and template generated sites
