### ISSUE TITLE
fix: navigation does not expand when navigating through the page by bookmark or link

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2142]
# 🐛 Bug Report

When navigating to a certain page which is nested underneith a `FluentNavGroup` the correct item will get the active class but the `FluentNavGroup` will be collapsed by default. This is really annoying when you come from bookmarks or external links to your website.

Please see this video for a demonstration:
https://github.com/microsoft/fluentui-blazor/assets/32510006/cb3d385d-4de1-4a79-81cf-0232f2bc3a40

## 💻 Repro or Code Sample
I'Ve created a small sample repo. Simply click on Show weather in Home.razor

https://github.com/MarvinKlein1508/ExpandBugFluentUi

## 🤔 Expected Behavior

I would expect `FluentNavGroup` to be expaned when visiting /weater through the link on Home.razor

## 😯 Current Behavior

More is collapsed but the item underneith More has active classes.

## 🌍 Your Environment

.NET 8.0.6
Firefox latest version

**Comment by vnbaaij** [comment]
We have no notion of a 'parent/child' relationship in the current `NavMenu`. I don't see a way how we could do this at the moment.
Any ideas?

**Comment by vnbaaij** [comment]
Closing this as we do not have a solution for this for the foreseeable future
