### ISSUE TITLE
Weather sample page regenerates data on sort

### ISSUE THREAD

**Issue by kjkrum** [microsoft/fluentui-blazor#2143]
The weather sample page regenerates its random data every time the sort order is changed on a DataGrid column. This is easily fixed by adding `ToList()` before `AsQueryable()`.

On one hand, this looks like a bug. On the other hand, it's instructive for anyone who notices it.

**Comment by vnbaaij** [comment]
Not really a bug indeed. 
We are aware this happens but did not invest time in solving it. It is just a simple example that everyone removes anyway.

Feel free to fix this and submit a PR if you want...
