### ISSUE TITLE
RefreshDataAsync ignored with Virtualize=true

### ISSUE THREAD

**Issue by Trapulo** [microsoft/fluentui-blazor#2145]
# 🐛 Bug Report

I have a FluentDataGrid connected with ItemsProvider to a GridItemsProvider. Then I have a function that calls RefreshDataAsync (after a filter has changed).
Using Virtualize=true, RefreshDataAsync does NOT invoke the request for new data. Using Virtualize=false, same code works

## 💻 Repro or Code Sample

```
 protected override async Task OnInitializedAsync()
 {
     await base.OnInitializedAsync();

    customersProvider = async req =>
    {
        var customersGetList = await _coreClient.GetCustomersAsync(Filter.Name, Filter.CustomerGuid, 50, req.StartIndex, Filter.OrderByField, Filter.OrderByReverse);
    
        return GridItemsProviderResult.From<Dto.Customer>(
            items: customersGetList!.Data.ToList(),
            totalItemCount: customersGetList!.TotalItems);
    };
}

protected async Task OnFilterChanged()
{
    await customersGrid!.RefreshDataAsync();
}
```

## 🤔 Expected Behavior

Calling customersGrid!.RefreshDataAsync() may start data fetching and _coreClient.GetCustomersAsync may be executed

## 😯 Current Behavior

Using Virtualize=true, RefreshDataAsync does NOT invoke the request for new data. Using Virtualize=false, same code works

## 🌍 Your Environment

* OS & Device: Windows
* Browser Mozilla FireFox
* .NET and Fluent UI Blazor library Version 8.0.6 and 4.7.2

**Comment by Trapulo** [comment]
It seems that "Loading="true" is related to the problem. Removing it, it seems that the problem is solved.

**Comment by vnbaaij** [comment]
Closing this as a workaround is available.
