### ISSUE TITLE
fix: Cannot control the Value of a FluentTextField or a FluentTextArea.

### ISSUE THREAD

**Issue by denispaluca** [microsoft/fluentui-blazor#2146]
# 🐛 Bug Report

Cannot control the `Value` of a `FluentTextField` or a `FluentTextArea`.

## 💻 Repro or Code Sample

Bind a `FluentTextField` with a property with custom setter or with bind `Value` and `ValueChanged` separately. Have the setter/ValueChanged method change the `Value` which is used on the `FluentTextField`.
For example: If the user types 'no' it should be changed to 'yes'.

Example with Enum:
```c#
@using Microsoft.FluentUI.AspNetCore.Components

<FluentTextField
    Value="@_value.ToString()"
    ValueChanged="@ChangeValue" />

@code {
    private RandEnum _value;

    private void ChangeValue(string newValue)
    {
        switch(newValue)
        {
            case "A":
                _value = RandEnum.A;
                break;
            case "C":
                _value = RandEnum.C;
                break;
            default:
                _value = RandEnum.A;
                break;
        }
    }

    public enum RandEnum {
        A,
        B,
        C
    }
}
```

## 🤔 Expected Behavior

The user enters 'no' in the `FluentTextField`. After the user exits/unfocuses the `FluentTextField` , 'yes' is shown in the `FluentTextField`.

## 😯 Current Behavior

After the user enters 'no' and exits/unfocuses the `FluentTextField`, the value in it does not changed. Even though the value in the component using the `FluentTextField` has been changed to 'yes'.

## 🔦 Context

I am trying to build a text field which only accepts Absolute Urls. Meaning if the user enters a wrong string, the value should be reset.

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version 8 and 4.7.2

**Comment by vnbaaij** [comment]
Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will get closed in **3** days

Help us to help you. Thanks.

**Comment by denispaluca** [comment]
@vnbaaij Apperantly when you pass a value using `ToString`, it does not work correctly.
Example as above
```c#
@using Microsoft.FluentUI.AspNetCore.Components

<FluentTextField
    Value="@_value.ToString()"
    ValueChanged="@ChangeValue" />

@code {
    private RandEnum _value;

    private void ChangeValue(string newValue)
    {
        switch(newValue)
        {
            case "A":
                _value = RandEnum.A;
                break;
            case "C":
                _value = RandEnum.C;
                break;
            default:
                _value = RandEnum.A;
                break;
        }
    }

    public enum RandEnum {
        A,
        B,
        C
    }
}
```

**Comment by vnbaaij** [comment]
Yeah, I'm not surprised this is not working. `_value` is of type `enum` where as TextField only supports binding to a `string`. This should not even compile...

**Comment by vnbaaij** [comment]
If you change the code to this, it sort of works:

```
@using Microsoft.FluentUI.AspNetCore.Components

<FluentTextField Value="@_value.ToString()"
                 ValueChanged="@ChangeValue" ValueExpression="@(() => s)" />

@code {
    private RandEnum _value;
    private  string? s;

    private void ChangeValue(string newValue)
    {
        s = string.Empty;
        switch (newValue)
        {
            case "A":
                _value = RandEnum.A;
                break;
            case "C":
                _value = RandEnum.C;
                break;
            default:
                _value = RandEnum.A;
                break;
        }
        s = _value.ToString();
    }

    public enum RandEnum
    {
        A,
        B,
        C
    }
}
```

With 'sort of' I mean it works if you change for A->xyz->C->ghj->etc. If you just change from ne value that resolves to A to another that resolves to A again, the field will not update.

As this is a bit of a strange usage, I'm closing this issue. Hope the provided code will help you further.
