### ISSUE TITLE
fix: [FluentNumberField Required validation error?] in [EditForm?]

### ISSUE THREAD

**Issue by kamazheng** [microsoft/fluentui-blazor#2147]
If you delete all the content of FluentNumberField, and input again, the validation error will not disappear.

```
@page "/test"

<EditForm EditContext="EditContext">
    <DataAnnotationsValidator />

    <FluentNumberField Required @bind-Value="MyModel.MyInt" Label="My Int" Immediate="true" />
    <FluentValidationMessage For="() => MyModel.MyInt" />
</EditForm>

@code {
    Model MyModel { get; set; } = new();
    EditContext EditContext { get; set; } = default!;

    protected override void OnInitialized()
    {
        base.OnInitialized();

        EditContext = new(MyModel);
    }

    public class Model
    {
        public int MyInt { get; set; }
    }
}

```
![image](https://github.com/microsoft/fluentui-blazor/assets/49426393/183d77b7-44b4-4f2e-8cac-79098e877d9c)
![image](https://github.com/microsoft/fluentui-blazor/assets/49426393/9a2242e3-b5a8-4529-a044-ee842252f465)

**Comment by vnbaaij** [comment]
This is already known a long long time. Use the search. 
We can't fix because the web component is severely broken
