### ISSUE TITLE
DataGrid: add access to columns

### ISSUE THREAD

**Issue by ksbecker** [microsoft/fluentui-blazor#2148]
# 🙋 Feature Request

Give developers access to the collection of columns in a DataGrid.

## 🤔 Expected Behavior

In order to programmatically set the sort, remove sort, or show column options, you need to pass in a `ColumnBase<TGridItem>` into one of the methods, `RemoveSortByColumnAsync`, `ShowColumnOptionsAsync`, and `SortByColumnAsync`. As far as I can tell, there is no way to get a reference to the columns.

## 😯 Current Behavior

Currently there is way to access this collection.

## 💁 Possible Solution

There is a [private field](https://github.com/microsoft/fluentui-blazor/blob/5a65947e464d4e2f48411da65b8eb651606d2943/src/Core/Components/DataGrid/FluentDataGrid.razor.cs#L191) that contains a list of `ColumnBase<TGridItem>` that could be exposed through a getter property.

## 🔦 Context

What I'm trying to accomplish is to store the state of the DataGrid and restore it when navigating back to the page. I have filters and paging working, now I need to be able to restore the previous sort order. I can accomplish this by storing an index/unique id of the column that was sorted and then applying the `SortByColumnAsync` method.

## 💻 Examples

I think this is fairly straight-forward. Basically add a new property in `fluentui-blazor/src/Core/Components/DataGrid/FluentDataGrid.razor.cs`

`public List<ColumnBase<TGridItem>> Columns { get => _columns; }`

Alternatively, methods could be created to give access to these columns, `GetColumnByTitle` or `GetColumnByIndex`

**Comment by vnbaaij** [comment]
By exposing a getter, you would have _read only_ access to the _collection_ of columns. But then nothing would stop you from manipulating the _individuial_ columns from that collection, right?

I see more value in providing the other type of methods you mention. 

As we only have limited time for working on this, care to work on a PR?
