### ISSUE TITLE
fix: NotFound component not rendering when included in Routes component in Blazor Hybrid App.

### ISSUE THREAD

**Issue by parko65** [microsoft/fluentui-blazor#2152]
# 🐛 Bug Report

When trying to navigate to a route that doesn't exist the app throws an exception as indicated by the yellow bar. I know you might say well the standard BlazorHybrid template doesn't include the NotFound component by default but it is available and can be used as in a standard Blazor App.

## 💻 Repro or Code Sample

[Here is a sample app to test this](https://github.com/parko65/FluentHybrid) just click on the NotFound Navlink to see result.

## 🤔 Expected Behavior

I would expect the NotFound component to be rendered as in the standard BlazorHybrid app.

## 😯 Current Behavior

A yellow bar is displayed and using dev tools this is the error in the console:

![image](https://github.com/microsoft/fluentui-blazor/assets/50332047/3b51bc20-344c-49dc-8d86-4f9892c7e05c)

## 🔦 Context

Consider a scenario where a user may have to copy a link into a InputText component and after completion the user clicks a button to process that link and redirect the user to another component in the app. If the user fails to copy the link correctly the app will throw an exception. This doesn't happen in a standard Hybrid app.

## 🌍 Your Environment

* OS & Device: Windows 11 PC
* Browser Microsoft Edge, Google Chrome, Mozilla FireFox
* .NET 8.0.6 and Fluent UI Blazor library 4.7.2]

**Comment by vnbaaij** [comment]
The not rendering of the NotFound parameter is caused by an AspNetCore issue. Does not have any relation with using the library. See https://github.com/dotnet/aspnetcore/issues/52119

We can't change anything on our side until this is fixed.
