### ISSUE TITLE
fix: TimePicker flickers in InteractiveServer rendermode

### ISSUE THREAD

**Issue by TheLever** [microsoft/fluentui-blazor#2154]
For the time picker we are actually falling back to the default browser component. Perhaps you are running into some issues with that input not being fully supported by the browsers you are using there (https://caniuse.com/input-datetime).

This is what I am seeing on my Edge Canary version:

![timepicker](https://github.com/microsoft/fluentui-blazor/assets/1761079/aa751cf1-9144-4323-8d36-03a520a9e2b2)

_Originally posted by @vnbaaij in https://github.com/microsoft/fluentui-blazor/issues/2153#issuecomment-2149948570_

**Comment by TheLever** [comment]
I think this was closed a bit too fast. Could not find a way to reopen, so creating a new one.

It seems odd to me that a browser which has 65% of the market share is not supported, and as I read the data in the link provided, my versions (both Edge and Chrome) should be supported.

Can you confirm you are using `@rendermode InteractiveServer`?

**Comment by dvoituron** [comment]
There is no need to re-create identical Issues. We continue to see and share comments even when an Issue is closed.
Closing an issue simply means that we haven't been able to reproduce the problem, or that no solution exists. If it has been closed by mistake, we can of course re-open it and work on it later.

**Comment by vnbaaij** [comment]
I'm not saying anything is not supported. I'm saying we are using a default browser component for this functionality. 

I created a new project from our template as you described. Pasted your repro code and ran it (on Windows). As can be seen from the screengrab, it seems to work there as expected. ANd yes, that new project is using InteractiveServer.

**Comment by dvoituron** [comment]
I used your code and got exactly the same result as Vincent.

![peek](https://github.com/microsoft/fluentui-blazor/assets/8350694/c7bd45d4-12ca-4761-8be6-a331d9868321)

**Comment by vnbaaij** [comment]
I'm closing this one as we are otherwise lacking the context and code from the original posted issue. @dvoituron please repost your comment in #2153
