### ISSUE TITLE
[FluentTextArea] When the input data is too large, it will automatically disconnect and lose data

### ISSUE THREAD

**Issue by CVBuddha** [microsoft/fluentui-blazor#2157]
# 🐛 Bug Report

When I use FluentTextArea, most of the time it's fine, but when I paste 55827 characters, it disconnects from auto and loses data. I didn't test how many characters FluentTextArea can tolerate at most.

## 💻 Repro or Code Sample
```
<FluentTextArea @bind-Value=jsonString Placeholder="↓↓↓The data is pasted here↓↓↓" Rows="30" class="kzl_full_width margin_top">
```
![微信图片_20240606013208](https://github.com/microsoft/fluentui-blazor/assets/171428319/da79a4d6-b2e0-4d90-b8e4-959664873d6b)

## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge (124.0.2478.109 )
* .NET 8, FluentUI (last)

**Comment by vnbaaij** [comment]
This is not a library issue. The standard Blazor Signal R connection has a maximum message size. See also https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-8.0&tabs=dotnet#configure-server-options
