### ISSUE TITLE
fix: Value "[object Object]" is set to css variable when using WithDefault/ToSwatch

### ISSUE THREAD

**Issue by guimabdo** [microsoft/fluentui-blazor#2158]
# 🐛 Bug Report

When using `.WithDefault` on a color value Design Token, the related css variable is set with an invalid value `[object Object]`
![image](https://github.com/microsoft/fluentui-blazor/assets/16648655/6fd6d919-514e-4582-bfb1-66a7968cfa55)

## 💻 Repro or Code Sample

```razor
<FluentCard>
    Test
</FluentCard>
<FluentDivider />
<FluentButton OnClick="ChangeUsingCsharp">
    WithDefault (C#)
</FluentButton>
<FluentButton OnClick="ChangeUsingJs">
    WithDefault (JS)
</FluentButton>
@code {
    [Inject]
    public NeutralStrokeLayerRest NeutralStrokeLayerRest { get; set; } = default!;
    [Inject]
    public IJSRuntime JSRuntime { get; set; } = default!;

    // This produces invalid css variable value
    private async Task ChangeUsingCsharp()
    {
        await NeutralStrokeLayerRest.WithDefault("red".ToSwatch());
    }

    // This one works correctly
    private async Task ChangeUsingJs()
    {
        var module = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js");
        await module.InvokeVoidAsync("neutralStrokeLayerRest.withDefault", "red");
    }
}
```

## 🤔 Expected Behavior

When clicking "WithDefault (C#)" the `--neutral-stroke-layer-rest` should be set to `red`:
![image](https://github.com/microsoft/fluentui-blazor/assets/16648655/3def6f4f-74d1-4217-932b-a76611a9fff2)

## 😯 Current Behavior
 `--neutral-stroke-layer-rest` is set to `[object Object]`
![image](https://github.com/microsoft/fluentui-blazor/assets/16648655/6fd6d919-514e-4582-bfb1-66a7968cfa55)

## 💁 Possible Solution

I currently don't have a  suggestion for the fix.
But as a warkaround it is possible to load the JS module and call the design token `.withDefault` directly:

```csharp
var module = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js");
await module.InvokeVoidAsync("neutralStrokeLayerRest.withDefault", "red");
```

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser: Microsoft Edge
* .NET 8.0.x and Fluent UI Blazor 4.7.2

**Comment by vnbaaij** [comment]
As described on https://fluentui-blazor.net/DesignTokens:

>For Design Tokens that work with a color value, you must call the ToSwatch() extension method on a string value or use one of the Swatch constructors. This makes sure the color is using a format that Design Tokens can handle. A Swatch has a lot of commonality with the System.Drawing.Color struct. Instead of the values of the components being between 0 and 255, in a Swatch the components are expressed as a value between 0 and 1.

What it does not mention but should bee clear, is that this won't work on a 'named' color. So instead of "red" use "#ff0000" and it should work.

**Comment by vnbaaij** [comment]
Apparently, there is an issue when passing a Swatch to WithDefault. I addded an overload that takes a string value (see PR #2159). Your code will work once this addition is released.
