### ISSUE TITLE
DataGrid - Allow Render Fragment to override Filter and Sort Icons

### ISSUE THREAD

**Issue by iguanaware** [microsoft/fluentui-blazor#2162]
# 🙋 Feature Request

<img width="436" alt="Screenshot 2024-06-06 112416" src="https://github.com/microsoft/fluentui-blazor/assets/1970566/23bc8b1d-12b5-4242-bcc1-bb2f1a65d968">

In a datagrid my users think the Filter Icon looks more like a sorted list.  I would like to be able to override just the line of code for the icons without the whole thing:

```csharp
--ColumnBase.Razor--
private void RenderDefaultHeaderContent(RenderTreeBuilder __builder)
ln 25 for example <FluentIcon Value="@(new CoreIcons.Regular.Size24.FilterDismiss())" />
```

## 🤔 Expected Behavior

Change the icons without overriding the entire template

## 😯 Current Behavior

Forces to override the entire HeaderCellItemTemplate

## 💁 Possible Solution
```html
<ColumnOptionsOpen>  ...My UI </ColumnOptionsOpen>
<ColumnOptionsDismiss>  ...My UI </ColumnOptionsDismiss>
```

**Comment by vnbaaij** [comment]
Hi,

The name of the icon being used is literally                         `<FluentIcon Value="@(new CoreIcons.Regular.Size24.Filter())" />`

We offer a way to change it through the header template and do not see any value in refining that even further.

**Comment by iguanaware** [comment]
I understand your reasoning.  Thank you
