### ISSUE TITLE
Response DataGrid Columns

### ISSUE THREAD

**Issue by Rocky-25** [microsoft/fluentui-blazor#2165]
Is there a way with data grid to have columns only show on certain screen sizes so as the screen gets smaller less important columns are removed?

**Comment by vnbaaij** [comment]
No, we don't have any special functionality built in for that. But in the end it is all styled with CSS so there shouldn't be any issues with hooking that up yourself.

**Comment by dvoituron** [comment]
You could use `FluentGrid` to detect the screen size and add two "DataGrid" adapted with your design.
