### ISSUE TITLE
Side effect to blazor.server.js when run with WPE/COG browser on Raspberry Pi 4

### ISSUE THREAD

**Issue by melihercan** [microsoft/fluentui-blazor#2166]
# 🐛 Bug Report

We are running a Blazor application on the Raspberry Pi 4 (Bookworm). We access a Blazor page using the [WPE/COG](https://wpewebkit.org/) browser and display it in a full-screen (kiosk) via a Linux service.
We realize the WPE/COG browser display is not refreshing after the initial read.
When we examined the debug logs, we found the following error:
```
Cog-Core-Message: 18:57:58.326: <http://localhost:7012/> Loading...
Cog-Core-Message: 18:57:58.441: <http://localhost:7012/> Loaded successfully.
http://localhost:7012/_framework/blazor.server.js:1:149613: CONSOLE JS ERROR Unhandled Promise Rejection: TypeError: Illegal constructor
```
The kiosk works as expected when we comment out the FluentUI components and the reference to the NuGet packages in the project file.
So FluentUI is interacting with the Blazor JS file and causing a failure. 

## 💻 Repro or Code Sample

Unfortunately, I cannot disclose any code due to copyright protection. I hope the above error message can help you solve the issue.

## 🤔 Expected Behavior

The Kiosk page should reflect any changes on the Blazor page.

## 😯 Current Behavior
It is not refreshing the page anymore after the initial content load. The debug logs reveal the following error:
```
Cog-Core-Message: 18:57:58.326: <http://localhost:7012/> Loading...
Cog-Core-Message: 18:57:58.441: <http://localhost:7012/> Loaded successfully.
http://localhost:7012/_framework/blazor.server.js:1:149613: CONSOLE JS ERROR Unhandled Promise Rejection: TypeError: Illegal constructor
```
## 💁 Possible Solution
I don't know the internals of FluentUI, but can it be that the original `blazor.server.js` file is replaced or overwritten?

## 🌍 Your Environment

* OS & Device: Raspberry Pi, Bookworm OS
* Browser: WPE/COG/Wayland
* .NET and Fluent UI Blazor library Version: [ 8.0.6 and 4.7.2]

**Comment by vnbaaij** [comment]
Hi,

No, we do not replace the original `blazor.server.js` file. We hook into the Blazor startup events to inject scripts and styles. I'm assuming that is were things go wrong.  

You say it works correctly when commenting out the Fluent packages, etc. But is Blazor still doing anything then?

As you can imagine, we do not have any testing capabilities lined up and ready to roll on a Pi with Bookworm, nor de we have capacity to set up something like that. Not really sure how we can help you with this.

**Comment by melihercan** [comment]
> You say it works correctly when commenting out the Fluent packages, etc. But is Blazor still doing anything then?
Yes, Blazor works correctly in both cases. I can confirm that by checking with my PC's Chrome browser.

> As you can imagine, we do not have any testing capabilities lined up and ready to roll on a Pi with Bookworm, nor de we have capacity to set up something like that. Not really sure how we can help you with this.
I understand. Well, I am not sure if this can be replicated on a Linux machine.
Thanks anyway...

**Comment by vnbaaij** [comment]
> Yes, Blazor works correctly in both cases. I can confirm that by checking with my PC's Chrome browser.

How did you check? By connecting to the site on the PI?

**Comment by melihercan** [comment]
> How did you check? By connecting to the site on the PI?

Exactly

**Comment by melihercan** [comment]
The funny thing is that even when we don't use any components from FluentUI (all commented out) and just leave the NuGet package active in the project file, it creates the same issue.

**Comment by vnbaaij** [comment]
Like I said, we hook into the Blazor startup sequence. Just having the DLL in the bin folder is enough

**Comment by c0g1t8** [comment]
@melihercan 

Out of curiosity, have you tried using another browser?

**Comment by melihercan** [comment]
> @melihercan
> 
> Out of curiosity, have you tried using another browser?

I'm sorry for not getting back to you sooner. As I mentioned above, I have tried Chrome on my PC (Windows) and the default browser of the desktop PRi OS which is Firefox I guess.

**Comment by c0g1t8** [comment]
> > @melihercan
> > Out of curiosity, have you tried using another browser?
> 
> I'm sorry for not getting back to you sooner. As I mentioned above, I have tried Chrome on my PC (Windows) and the default browser of the desktop PRi OS which is Firefox I guess.

Sorry, it's still unclear to me.  From the description above, I assumed that you have .net 8 Blazor application running on a Raspberry Pi 4 that is server rendered. This application is being accessed by a browser on the same Pi via a localhost connection.

My first instinct is to eliminate the WPE/COG browser as a factor. Open a port on the Raspberry Pi and attempt to access the application from a PC or MAC with Chrome, Edge, Firefox, or Safari. From your last statement above, it appears that is what you did. Were these tests successful?

**Comment by melihercan** [comment]
> Sorry, it's still unclear to me. From the description above, I assumed that you have .net 8 Blazor application running on a Raspberry Pi 4 that is server rendered. This application is being accessed by a browser on the same Pi via a localhost connection.

Correct



> My first instinct is to eliminate the WPE/COG browser as a factor. Open a port on the Raspberry Pi and attempt to access the application from a PC or MAC with Chrome, Edge, Firefox, or Safari. From your last statement above, it appears that is what you did. Were these tests successful?

Yes, they were all successful. It is only the WPE/COG browser that is failing.

**Comment by vnbaaij** [comment]
Then it seams to be an issue in that browser and not necissarily in the library.

As it is a very hard issue to replicate (for us), I don't think we will be able to do anything with it in a short term.

I'm sorry we can't help with this but I don't think we need to keep this issue open. Agreed?

**Comment by vnbaaij** [comment]
> As a side note, the other two UI frameworks, AntDesign and Radzen work without any issues.

Yes, but with those you probably have to add scripts and stylesheets manually to make them work. We do that for you and my guess is that is where the issue originates from.

**Comment by c0g1t8** [comment]
@melihercan 

This issue has piqued my interest 😄. Your results confirmed my suspicion that the issue was likely due to some interaction in the WPE/COG browser.

If you have the time or interest, you could build the fluentui-blazor library locally. There is a server version of the demo site included. Attempt to connect to that from the WPE/COG browser from the Raspberry Pi. A quicker test would be to point the browser at www.fluentui-blazor.net but that is the web assembly version and is not be representative of your application.

The rationale for this additional test is to see if the issue is specifically due to fluentui-blazor working in the WPE/COG browser. If there is an issue, isolating the issue would be much easier.

**Comment by melihercan** [comment]
Sure, I will give it a shot when I find some time and provide feedback here.
