### ISSUE TITLE
fix: FluentSelect does not work inside FluentDataGrid

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#217]
# 🐛 Bug Report

When using FluentSelect inside FluentDataGrid dropdown is not shown.

## 💻 Repro or Code Sample

Based on these examples:

https://brave-cliff-0c0c93310.azurestaticapps.net/SelectPage

https://brave-cliff-0c0c93310.azurestaticapps.net/DatagridPage

I would also like some better examples working with enum values and select. I had to write my own code but I think this should be documented better. Added `MatSelectItem` as example since it works with `FluentDataGrid`. Select works fine with Enum when not used in `FluentDataGrid`

    <p>
        <MatSelectItem @bind-Value="@threatDto.Severity" Label="Severity" Items="@SeverityValues" FullWidth="true" Required="true">
        </MatSelectItem>
    </p>
    <p>
        <FluentSelect @bind-Value="@threatDto.Severity" Options="@SeverityOptionList" Required="true">
        </FluentSelect>
    </p>

    <FluentDataGrid id="ExternalLinksGrid" RowsData=RowsGrid1 ColumnDefinitions=ExternalLinkColumns GridTemplateColumns="1fr 1fr" TItem=ExternalLink Context="tableRowContext">
        <RowItemTemplate>
            <FluentDataGridRow>
                <FluentDataGridCell GridColumn=1>
                    <FluentTextField @bind-Value=@tableRowContext.Link></FluentTextField>
                </FluentDataGridCell>
                <FluentDataGridCell GridColumn=2>
                    <FluentSelect @bind-Value="@tableRowContext.LinkType" Options="@LinkTypeOptionList" Required="true">
                    </FluentSelect>
                </FluentDataGridCell>
                <FluentDataGridCell GridColumn=3>
                    <MatSelectItem @bind-Value="@tableRowContext.LinkType" Label="LinkType" Items="@LinkTypeValues" Required="true">
                    </MatSelectItem>
                </FluentDataGridCell>
            </FluentDataGridRow>
        </RowItemTemplate>
    </FluentDataGrid>
			

    public List<ColumnDefinition<ExternalLink>> ExternalLinkColumns = new();			

	List<Severity?> SeverityValues = Enum.GetValues(typeof(Severity)).Cast<Severity?>().Where(x => x != Severity.None).ToList();

	List<LinkType?> LinkTypeValues = Enum.GetValues(typeof(LinkType)).Cast<LinkType?>().Where(x => x != LinkType.None).ToList();

	List<Option<Severity?>> SeverityOptionList = Enum.GetValues(typeof(Severity)).Cast<Severity?>().Where(x => x != Severity.None).Select(x => new Option<Severity?> { Key = x.Value, Value = x.Value }).ToList();

	List<Option<LinkType?>> LinkTypeOptionList = Enum.GetValues(typeof(LinkType)).Cast<LinkType?>().Where(x => x != LinkType.None).Select(x => new Option<LinkType?> { Key = x, Value = x }).ToList();

    List<ExternalLink> RowsGrid1 = new()
    {
        new ExternalLink(){ Link = "123", LinkType = LinkType.JiraRisk},
        new ExternalLink(){ Link = "12345", LinkType = LinkType.OtherHyperlink},
    };

    protected override void OnInitialized()
    {
        ExternalLinkColumns.Add(new ColumnDefinition<ExternalLink>("Link", x => x.Link));
        ExternalLinkColumns.Add(new ColumnDefinition<ExternalLink>("Link Type", x => x.LinkType));
        ExternalLinkColumns.Add(new ColumnDefinition<ExternalLink>("Link Type MatSelectItem", x => x.LinkType));
    }
	
Classes:

    [Required, EnumDataType(typeof(Severity))]
    public Severity? Severity { get; set; }		
	
    public class ExternalLink : Entity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [MaxLength(2048)]
        public string Link { get; set; }

        [Required, EnumDataType(typeof(LinkType))]
        public LinkType? LinkType { get; set; }

    }

    public enum LinkType
    {
        None = 0,
        OtherHyperlink = 1,
        JiraIssue = 2,
        JiraRisk = 3,
    }

## 🤔 Expected Behavior

Should render drop down on click

## 😯 Current Behavior

No drop down is visible

## 🔦 Context

I can not use Fluent UI alone

## 🌍 Your Environment

* OS & Device: Windows
* Browser Chrome
* .NET and FAST Version .NET 6, Microsoft.Fast.Components.FluentUI 1.5.1 @fluentui/web-components 2.5.4

**Comment by vnbaaij** [comment]
I believe this is an issue in the underlying web components. Have raised an issue there,

**Comment by ehsangfl** [comment]
did you have find any solution?

**Comment by vnbaaij** [comment]
I believe it is solved on the FAST side. Need to wait till it is incorporated in the Fluent dcript. @chrisdholt do you know the schedule for that?

**Comment by chrisdholt** [comment]
> I believe it is solved on the FAST side. Need to wait till it is incorporated in the Fluent dcript. @chrisdholt do you know the schedule for that?

This was part of our current Alpha breaking changes - it will show up in the vNext of Fluent, which will be aligned to Fluent 2 specs. We've currently started work on this, but again, it's part of a larger breaking change. There's a whole history of "why" this previously wasn't working/supported/etc which can provide additional details. One thing you could do in the meantime if you _absolutely_ know and control the stacking context of your application, would be to target the listbox part and use fixed positioning...that would likely allow it to break out.

**Comment by vnbaaij** [comment]
We can't fix it properly with the current Fluent UI Web Components implementation. As a workaround apply the suggested fixed positioning css

**Comment by vnbaaij** [comment]
Hi Oscar, 

As explained, this is an issue in the underlying web components, We can't really fix it on the Blazor side. 
As @chrisdholt said, if you absolutely know and control the stacking context of your application, target the listbox part and use fixed positioning. 
Because we can be sure of this on the Blazor side, we can't fix it like this for everyone. 

Trying it locally at least makes it functional: 
<img width="177" alt="image" src="https://user-images.githubusercontent.com/1761079/230109570-a4554f1e-3fea-41e5-ba0c-56e8a02fa4b7.png">

This is what I changed in the style:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/1761079/230109950-f27c1109-9a8e-424f-83cc-52b59a59d23e.png">

**Comment by Ogglas** [comment]
Hello Vincent,

I understand. As I understood it this would be fixed in the Fluent 2 specs and therefore it could be fixed here as well. I did check the issue you opened in the FAST monorepo https://github.com/microsoft/fast/issues/6373 and I will continue to monitor there if anything happens. I will try fixed positioning in the meantime then.

**Comment by Ogglas** [comment]
@vnbaaij Trying `position: fixed;` with `Microsoft.Fast.Components.FluentUI` `2.3.3` does not work anymore unfortunately. Looks like this for me with the code above. Any idea on how to get around this now?

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/84bc95be-691a-419b-b8cf-85ed731e3950)

Code would be appreciated given that it is a shadow-root element so it requires an override for the constructed stylesheet.

This [PR ](https://github.com/microsoft/fast/pull/6452) closed your [issue](https://github.com/microsoft/fast/issues/6373). Anything there that can be used to fix this issue permanently?

**Comment by vnbaaij** [comment]
Best I can come up with in short term is to go with `position: sticky` in overridden CSS

**Comment by vnbaaij** [comment]
Ok, best I can doin short term is:

position: fixed;
left: unset;
top: auto;

**Comment by Ogglas** [comment]
@vnbaaij `position: sticky` works in some cases but if you have a virtualized data grid with fixed height it wont work. 

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/2938901d-e4b8-4ba6-91d3-e75ee2bc3712)

Source enum with None filtered:

    public enum Severity
    {
        None = 0,
        Critical = 1,
        High = 2,
        Medium = 3,
        Low = 4
    }

I think this issue should be reopened and if this is related to the FAST side I think a new issue should be opened there given that they closed your original issue https://github.com/microsoft/fast/issues/6373 as completed.

**Comment by Ogglas** [comment]
I understand! :) 

Should the issue be reopened anyway since it is a bug but it can't be fixed now?

**Comment by ehsangfl** [comment]
@vnbaaij how can I override position value to temporarily resolve this issue

**Comment by vnbaaij** [comment]
Hi,

You need to add an isolated css file to your component and then target the listbox part of the select. Something like
```
 :deep .{classname} ::part(listbox) {
   position: sticky
}

**Comment by ehsangfl** [comment]
> @ehsangfl More info here: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-7.0

I'm didn't familiar with ::deep and ::part. so I learned it from you. thank a lot

**Comment by BulldogCTISolutions** [comment]
I'm using the FluentSelect in a DataGrid cell too.  I only see one select option out of many (long list).  When I click the down arrow for the Select I get no additional rows to appear.  Based on this thread,..  do I set the Class property or the Style property.  For the ::deep syntax above, do I say Class="listbox" or Style="listbox"?  Is 'classname' = 'fluent-select'?  and is that a typo for deep, one colon or two?  is 'listbox' the ID of the FluentSelect?

**Comment by martinbu** [comment]
`position: sticky` did not work for me. As a workaround I have added the class `overflow-column` to those `TemplateColumn`s which contains FluentSelect components and added the following component css rule.

```razor
<TemplateColumn Title="Column with overflow content" Class="overflow-column">
    <FluentSelect ... />
</TemplateColumn>
```

```css
::deep fluent-data-grid-cell.overflow-column {
    overflow: visible;
    max-width: 0;
}
```
As a side effect, when there is not enouph space, a horizontal scrollbar will be shown. But that is fine for my use case.

**Comment by vnbaaij** [comment]
Can confirm this is agood workaround:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/a0e4f15f-71ef-4299-bac5-b2dba1132ac0)

Code I tested with (besides css from post above):

```
@page "/IssueTester"

<FluentDataGrid Id="ExternalLinksGrid" Items="RowsGrid1.AsQueryable()" GridTemplateColumns="1fr 1fr 1fr" TGridItem=ExternalLink>
    <PropertyColumn Property="@(c => c.Link)"></PropertyColumn>
    <TemplateColumn Title="Link Type" Class="overflow-column">
        <FluentSelect Items="@LinkTypeOptionList" TOption="Option<LinkType?>" OptionText="@(i => i.Text.ToString())" OptionValue="@(i => i.Value.ToString())" Required="true" SelectedOptionChanged="@((value) => { context.LinkType = value.Value; })">
        </FluentSelect>
    </TemplateColumn>
</FluentDataGrid>

<FluentSelect Items="@LinkTypeOptionList" TOption="Option<LinkType?>" OptionText="@(i => i.Text.ToString())" OptionValue="@(i => i.Value.ToString())" Required="true" SelectedOptionChanged="@((value) => { linkType = value.Value; })">
</FluentSelect>

@code {
    private LinkType? linkType;

    List<Option<LinkType?>> LinkTypeOptionList = Enum.GetValues(typeof(LinkType)).Cast<LinkType?>().Where(x => x != LinkType.None).Select(x => new Option<LinkType?> { Text = x, Value = x }).ToList();
    List<ExternalLink> RowsGrid1 = new()
    {
        new ExternalLink(){ Link = "123", LinkType = LinkType.JiraRisk},
        new ExternalLink(){ Link = "12345", LinkType = LinkType.OtherHyperlink},
    };

    public class ExternalLink
    {
        public int Id { get; set; }
        public string? Link { get; set; }
        public LinkType? LinkType { get; set; }
    }

    public enum LinkType
    {
        None = 0,
        OtherHyperlink = 1,
        JiraIssue = 2,
        JiraRisk = 3,
    }

    public enum Severity
    {
        None = 0,
        Critical = 1,
        High = 2,
        Medium = 3,
        Low = 4
    }
}
```
Closing this issue now that we have 2 possible workarounds.

**Comment by martinbu** [comment]
Maybe some hint or information to this workaround should be added to the documentation of the FluentDataGrid?

**Comment by vnbaaij** [comment]
I don't want to do that because it kind of sends a signal that the grid can be used as a way to directly edit rows of data. It was not built with that in mind, so we do not want to 'promote' that way of working.

**Comment by Ogglas** [comment]
> I don't want to do that because it kind of sends a signal that the grid can be used as a way to directly edit rows of data. It was not built with that in mind, so we do not want to 'promote' that way of working.
 
@vnbaaij Have you tried it with a virtualized data grid?

https://www.fluentui-blazor.net/DataGrid#virtualizedgrid

**Comment by vnbaaij** [comment]
Sorry, tried what? The workaround with the overflow?

**Comment by Ogglas** [comment]
> Sorry, tried what? The workaround with the overflow?
> 
> As I explained, I think having an editable grid is not a good idea in general. But doing it on a virtualized grid with (potentially) a huge amount of rows is definitely a very bad idea. (huge load on the DOM)

Yes exactly. It might technically be a bad idea but inline editing is something that users really like. Like the example with template columns.

https://www.fluentui-blazor.net/DataGrid#templatecolumns2

**Comment by StefanJansson** [comment]
THis example does not work anymore

**Comment by vnbaaij** [comment]
> THis example does not work anymore

We have changed the rendering of a DataGrid to use plain HTML tables. 

Using the code from https://github.com/microsoft/fluentui-blazor/issues/217#issuecomment-1919861463 and the CSS from https://github.com/microsoft/fluentui-blazor/issues/217#issuecomment-1919427222 (without the max-width) gives me:


![Image](https://github.com/user-attachments/assets/80cf73d9-a90d-4b3e-9490-9ea110589119)

**Comment by parsalotfy** [comment]
```
::deep fluent-data-grid-cell.overflow-column {
    overflow: visible;
}
```

I used this css as mentioned in comments, like this:
```
<TemplateColumn Title="mytitle" Class="overflow-column">
    <FluentSelect Items="Enum.GetValues<MyLevels>()" TOption="MyLevels" OptionText="@(i=>i.ToString())" @bind-SelectedOption="context.MyLevel" />
</TemplateColumn>
```

and it doesn't show me the full list, it only shows 1 item, which fits the height of row...

**Comment by StefanJansson** [comment]
Just add style="overflow: visible;" to the TemplateColumn

**Comment by parsalotfy** [comment]
@StefanJansson thank you for answering, I noticed that when I do this it works as you said

```
<TemplateColumn Title="mytitle" Class="columnClass">

.columnClass {
    overflow: visible;
}
```

but when I add **text-align** it ruins it.

```
.columnClass {
    text-align: left;
    overflow: visible;
}
```

Do you know why and how can I fix it?

**Comment by StefanJansson** [comment]
Don't know why but if you put the align left inside a span, it works.

**Comment by jfadiga** [comment]
Tried the fix. After surrounding the FluentDataGrid with div it worked.

page.razor file:
```
@page "/component"

<div>
    <FluentDataGrid Items="@people">
        <PropertyColumn Property="@(p => p.PersonId)" />
        <PropertyColumn Property="@(p => p.Name)" />
        <PropertyColumn Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" />
        <TemplateColumn Context="context" Title="Job" Class="overflow-column">
            <FluentSelect Items=@stringOptions1 OptionText="@(o => o.Text)" OptionValue="@(o => o.Value)" TOption="Option<string>" Position="SelectPosition.Above" @bind-Value="@context.Job"></FluentSelect>
        </TemplateColumn>
    </FluentDataGrid>
</div>

@code {

    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16), "Driver"),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1), "Woodworker"),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10), "Driver"),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27), "Woodworker"),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3), "Doctor"),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9), "Woodworker"),
    }.AsQueryable();

    List<Option<string>> stringOptions1 = new()
    {
        { new Option<string> { Value = "Driver", Text = "Driver" } },
        { new Option<string> { Value = "Doctor", Text = "Doctor" } },
        { new Option<string> { Value = "Woodworker", Text = "Woodworker" } }
    };
}
```

page.razor.css file:
```
::deep .overflow-column {
    overflow: visible !important;
}

```
