### ISSUE TITLE
FluentTreeView is collapsing and expanding continuously if we click on expand button 2 to 3 times

### ISSUE THREAD

**Issue by sarojsahoo2024** [microsoft/fluentui-blazor#2174]
Hi Team, we are using FluentUI 3.0.1 in blazor

When we click on expand button of root node for 2 to 3 times, its continuously collapsing and expanding and re-rendering the fluent tree view items.

We are binding the each FluentTreeItem through foreach loop.

Please look at the attachment in video format.

Thanks for your support.

# 🐛 Bug Report

https://github.com/microsoft/fluentui-blazor/assets/171221969/a3db4356-94bb-4492-8db5-3e1620825d8f

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
We only support the latest shipping versions. If you are indeed using v3.0.1, update to latest v3 version first and then try again.

Also, if the issue then still manifests, we wil need ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

Help us to help you. Thanks.

**Comment by sarojsahoo2024** [comment]
Thank you very much @vnbaaij. 
We found the solution by adding unique id for each tree view item.
