### ISSUE TITLE
fix: Fullscreen property not working in FluentOverlay

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fluentui-blazor#2179]
# 🐛 Bug Report

Fluent Overlay cannot be set to cover a layout component if that component is not Fluent Tab. It will cover the entire screen. Any content inside the Fluent Overlay will not be properly positioned when compared to content it needs to cover. It will block the navigation sidebar which is not acceptable to me. When Fluent Overlay CSS position is set to relative it will display itself on the page, but it will not cover other components on the page that are not inside the Fluent Overlay which is also not acceptable.

## 💻 Repro or Code Sample

To reproduce the issue, use the project provided in previous issue: [project](https://github.com/microsoft/fluentui-blazor/files/14254409/OverlayTest.zip)

In the Home Page inside the div component you can add a Fluent TextField component outside of the Fluent Overlay.
Add CSS position relative for Fluent Overlay, run the project and visit home page. Visible=false property should be changed to true. You can see the overlay which is not in tabs is covering whole body.

## 🤔 Expected Behavior

The Fluent Overlay should only cover the container div (div which holds the Fluent Overlay Component) and disable all the content in it so the user cannot click the components in it.

## 😯 Current Behavior

The Fluent Overlay is shown in full screen when fullscreen property is set to false.

## 🔦 Context

We would use Fluent Overlay to restrict user access to form fields while a save, update, create or delete action is running and show the user that his request is being processed with a progress ring or text in Fluent Overlay.

## 🌍 Your Environment

Windows 11, PC
Microsoft Edge
dotnet 8, Blazor Fluent UI version 4.7.2

**Comment by c0g1t8** [comment]
@chigivigi 

If you provide a publicly accessible repository, it will be much easier to get help. 😄

**Comment by vnbaaij** [comment]
I think there is a small error in the Overlay component where it sets the `position: absolute;` when `Fullscreen=false`. We will fix that for next release.
For now, you need to override the value in you own CSS with a `position: relative;` for the fluent-overlay:
```
.fluent-overlay {
    position:relative!important;
}
```
Of course this only works if you do **not** also have full screen overlays in your app...

**Comment by chigivigi** [comment]
@vnbaaij Thank you for your help.
