### ISSUE TITLE
fix: custom loading indicator in data grid

### ISSUE THREAD

**Issue by ArturMichalak** [microsoft/fluentui-blazor#2187]
# 🐛 Bug Report

Custom loading indicator, larger than the standard one goes outside the data grid area.
![image](https://github.com/microsoft/fluentui-blazor/assets/36608116/177400fc-0e86-447f-b204-4a3280e822d7)

## 💻 Repro or Code Sample

https://github.com/hedge-code/HiddenLoadingIndicatorReproduction

## 🤔 Expected Behavior

The grid should adjust its size to the loading indicator.

## 😯 Current Behavior

Part of the indicator hides under the data grid border.

## 🔦 Context

This is a new regression. In version 4.7.1 it worked fine

## 🌍 Your Environment

OS & Device: Windows on PC
Browser Google Chrome 125.0.x.x
.NET and Fluent UI Blazor library Version 8.0.200 and 4.7.2

**Comment by vnbaaij** [comment]
Fixed in PR mentioned
