### ISSUE TITLE
The option to link external auth to registered user in ExternalLogins.razor page in Components/Account/Manage is not working

### ISSUE THREAD

**Issue by Doc415** [microsoft/fluentui-blazor#2189]
# 🐛 Bug Report

When create a new project with ms identity individual accounts, the function to  link external authentication for a registered user is not working and throwing this exception 
![image](https://github.com/microsoft/fluentui-blazor/assets/94632226/19114d20-01f6-45e2-ad54-27504e1035ff)

## 💻 Repro or Code Sample

https://github.com/Doc415/Fluent-Issue
Details in README

## 🤔 Expected Behavior

it should direct to individual external authentication page

## 😯 Current Behavior

the code does not send the provider name, instead it sends all avaible provider names in a single string

https://github.com/microsoft/fluentui-blazor/assets/94632226/0d3703fb-9c3e-4853-a7c7-2cf4338966c7

## 💁 Possible Solution

Change the form structure. My working solution:

```
@if (otherLogins?.Count > 0)
{
    <h4>Add another service to log in.</h4>
    <hr />
    @foreach (var provider in otherLogins)
    {
        <form class="form-horizontal" action="Account/Manage/LinkExternalLogin" method="post">
            <AntiforgeryToken/>
            <input type="hidden" name="Provider" value="@provider.Name" />
            <div>
                <p>
                    <FluentButton Type="ButtonType.Submit" Appearance="Appearance.Accent">
                        Log in using your @provider.DisplayName account
                    </FluentButton>
                </p>
            </div>
        </form>
    }
}
```

## 🔦 Context
I was trying to give an option to a self registered user to link his microsoft, github, google account 

## 🌍 Your Environment

Vs 2022
Windows 11
core i5 13th gen
16gb ram

**Comment by vnbaaij** [comment]
Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. In this case I would need to dive into the setup of the external providers first. As you have already done that, help us to help you by sharing what you have. Thanks.

**Comment by Doc415** [comment]
> Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.
> 
> We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. In this case I would need to dive into the setup of the external providers first. As you have already done that, help us to help you by sharing what you have. Thanks.

I have Created a repository ready to run. Details are in README. I have added a short video to Issue.
https://github.com/Doc415/Fluent-Issue
Thanks.

**Comment by vnbaaij** [comment]
I've created the database locally and ran the migrations. Running the solution now gives:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/e3944547-04f2-4cc9-9910-2a524711af0c)

Am I missing something in `UserSecrets` perhaps?

**Comment by vnbaaij** [comment]
PS, I see in `program.cs` that you have `builder.Services.AddQuickGridEntityFrameworkAdapter();`

You should change that to use [our own adapter](https://www.nuget.org/packages/Microsoft.FluentUI.AspNetCore.Components.DataGrid.EntityFrameworkAdapter) which works together with the `FluentDataGrid`

**Comment by Doc415** [comment]
> I've created the database locally and ran the migrations. Running the solution now gives: ![image](https://private-user-images.githubusercontent.com/1761079/339737801-e3944547-04f2-4cc9-9910-2a524711af0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjMwNDEsIm5iZiI6MTcxODM2Mjc0MSwicGF0aCI6Ii8xNzYxMDc5LzMzOTczNzgwMS1lMzk0NDU0Ny0wNGYyLTRjYzktOTkxMC0yYTUyNDcxMWFmMGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMTA1OTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU3MmRlZTcxYmRiMGJlODM4NmRhMjY0MjQ5ZDcyMGRiNDYyNTcwMmQ5ZGU5ZWYzZmJhMGNlZjIwYzVmYjFmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.24edUffA7musAb5tTKXuAOpk-8MwSBqZQY9BBO4amf4)
> 
> Am I missing something in `UserSecrets` perhaps?

I have filled dummy id and secret in appsetings. 
I should mention it in the Readme
 I am learning asp.net and not very experineced in github communications.
Anything i should do?

**Comment by vnbaaij** [comment]
> I have filled dummy id and secret in appsetings. I should mention it in the Readme The application runs in my side, and i could not reproduce the error. I am learning asp.net and not very experineced in github communications. Anything i should do?

No worries. We all needed to learn it sometime 😀

I found the error for this. In code you had things like:
```
 googleOptions.ClientId = configuration["Authentication:Google:ClientId"];
 googleOptions.ClientSecret = configuration["Authentication:Google:ClientSecret"];
```
where that was specifiedappsettings as `GoogleClientId` (insteadof ClientId).

Can now debug...

**Comment by vnbaaij** [comment]
Ok, found the issue. Will be changed in the next version of the templates.

For now, you do not need to change the /Account/Manage/ExternalLogins page (but you can if that works for you). 

The fix will be made where the form post is handled, which is `IdentityComponentsEndpointRouteBuilderExtensions.cs`. We already have code in there to fix the /PerformExternalLogin post action. We just need to use the same fix in the /LinkExternalLogin action
1) Add the following at the end of that file:
```
private static string TemporaryFluentButtonFix(string provider)
{
    // Temporary workaround for FluentButton returning a provider value twice
    // Split the comma-separated list of strings
    var providers = provider.Split(',');

    // Find the value that appears twice in the list
    provider = providers.GroupBy(p => p)
                        .Where(g => g.Count() == 2)
                        .Select(g => g.Key)
                        .First();
    return provider;
}
```

2) Remove line 39 and further up until the `var properties = ...` and replace with 
```
 provider = TemporaryFluentButtonFix(provider);
```

3) In /LinkExternalLogin inset 
```
 provider = TemporaryFluentButtonFix(provider);
```
before the line `var properties = ...`

As said, this will be part of the new templates. 

Closing this as a solution is provided an will be fixed in next release

**Comment by Doc415** [comment]
> Ok, found the issue. Will be changed in the next version of the templates.
> 
> For now, you do not need to change the /Account/Manage/ExternalLogins page (but you can if that works for you).
> 
> The fix will be made where the form post is handled, which is `IdentityComponentsEndpointRouteBuilderExtensions.cs`. We already have code in there to fix the /PerformExternalLogin post action. We just need to use the same fix in the /LinkExternalLogin action
> 
> 1. Add the following at the end of that file:
> 
> ```
> private static string TemporaryFluentButtonFix(string provider)
> {
>     // Temporary workaround for FluentButton returning a provider value twice
>     // Split the comma-separated list of strings
>     var providers = provider.Split(',');
> 
>     // Find the value that appears twice in the list
>     provider = providers.GroupBy(p => p)
>                         .Where(g => g.Count() == 2)
>                         .Select(g => g.Key)
>                         .First();
>     return provider;
> }
> ```
> 
> 2. Remove line 39 and further up until the `var properties = ...` and replace with
> 
> ```
>  provider = TemporaryFluentButtonFix(provider);
> ```
> 
> 3. In /LinkExternalLogin inset
> 
> ```
>  provider = TemporaryFluentButtonFix(provider);
> ```
> 
> before the line `var properties = ...`
> 
> As said, this will be part of the new templates.
> 
> Closing this as a solution is provided an will be fixed in next release

Thank you very much
