### ISSUE TITLE
docs: fix links for every component

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#219]
# 🙋 Documentation Request

Every link to examples is broken in documentation. 

https://docs.microsoft.com/en-us/fluent-ui/web-components/components/select?pivots=blazor

Links to:

See example implementations at the [Fast Blazor Github](https://github.com/microsoft/fast-blazor/blob/main/examples/FluentUI.Demo.Shared/Pages/SelectPage.razor) repo.

See working examples at the [Fast Blazor Example](https://brave-cliff-0c0c93310.azurestaticapps.net/SelectPage) site.

Neither of these work

## 💁 Possible Solution

Use correct links, like:

https://github.com/microsoft/fast-blazor/blob/main/examples/FluentUI.Demo.Shared/Pages/Select/SelectPage.razor

https://brave-cliff-0c0c93310.azurestaticapps.net/Select

**Comment by vnbaaij** [comment]
A PR for this has already been submitted: https://github.com/MicrosoftDocs/fluent-ui-web-components-pr/pull/21

**Comment by Ogglas** [comment]
> A PR for this has already been submitted: https://github.com/MicrosoftDocs/fluent-ui-web-components-pr/pull/21

I can't see that PR but very good that it is addressed :)

**Comment by vnbaaij** [comment]
Probably just because the people on the FAST team are really busy and haven't gotten to it  yet. I'll ask around.

**Comment by Ogglas** [comment]
@vnbaaij This is still not fixed. Could you have a look at it again?

**Comment by vnbaaij** [comment]
Looking into it!

**Comment by vnbaaij** [comment]
@Ogglas the https://github.com/MicrosoftDocs/fluent-ui-web-components-pr/pull/21 has been merged in! Changes should be live anytime soon.

Thanks for bringing this to our attention again.

**Comment by Ogglas** [comment]
@vnbaaij Sounds good! However the error is still present today.

**Comment by Ogglas** [comment]
@vnbaaij The error is still there. Please reopen and do not close until it actually works

**Comment by vnbaaij** [comment]
I've reopened this and pinged the maintainers of the actual Docs repo to merge the changes to the 'live' branch.

Just as a side note, you'll probably be better of by using https://aka.ms/fluentui-blazoras a reference for the library. That site is continuously being updated based on the actual source code...

**Comment by Ogglas** [comment]
Thank you! That link leads to Bing but I assume you mean https://aka.ms/fluentui-blazor :)

**Comment by vnbaaij** [comment]
The changes are live! (... finally)
