### ISSUE TITLE
fix: numbered headings off center in wizard component

### ISSUE THREAD

**Issue by MeikTranel** [microsoft/fluentui-blazor#2198]
# 🐛 Bug Report

Numbered items in Wizards are irritatingly off center:
![image](https://github.com/microsoft/fluentui-blazor/assets/6466560/ed38b52b-bd3c-4499-8dd7-f93a995db282)

Very low effort issue creating on my part but its on the demo site and it looks off. Happy to create another issue in the fluent if its an upstream issue. (Rest is looking phenomal - cheers everyone)

## 💻 Repro or Code Sample

* https://www.fluentui-blazor.net/Wizard

## 🤔 Expected Behavior

Obviously text in a circular container should be centered around the bounding box of its contents.

## 😯 Current Behavior

Text seems to be anchored down too much.

## 🌍 Your Environment

* OS & Device: Windows 11 64Bit 22631.3737 - Screens (2x(1920:1090) @ 100%dpiscale  + 2560x1600 @ 150% Scale)
* Version 126.0.2592.56 (Official build) (64-bit)

**Comment by vnbaaij** [comment]
Adding it to 4.8.1
