### ISSUE TITLE
Button with icon in the content (extra space created in right if content is not given)

### ISSUE THREAD

**Issue by satyajit-behera** [microsoft/fluentui-blazor#2199]
When a button is created as mentioned below, it creates little extra space to the right of the icon as shown in the image (note: no content label is given in the button). This is the only way to have a customizable icon inside a button. 
```
 <FluentButton>
    <FluentIcon Value="@(new Icons.Regular.Size16.Delete())" Color="Color.Error" Slot="start" />
</FluentButton>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/10031739/708f10e3-1deb-4f0c-9296-386e5fc49f75)

Otherwise, 
When the button is created as below, it looks very nice with a uniform spacing between the icon and button borders.
```
 <p>With icon in default slot</p>
 <FluentButton IconEnd="@(new Icons.Regular.Size16.Globe())"
               Title="Globe"
               OnClick="@(() => DemoLogger.WriteLine("Button clicked"))" />
```
![image](https://github.com/microsoft/fluentui-blazor/assets/10031739/02fa2653-bfb5-459f-a3ff-44c828834f5b)

Thanks.

**Comment by vnbaaij** [comment]
I don't understand wat you mean with 'This is the only way to have a customizable icon inside a button.'

You can use any icon you want in the `IcondEnd` parameter in your second block of code.

Or if it is about using a custom color, you can just use the first code block, but do not use a `Slot` parameter then:

```
 <FluentButton>
    <FluentIcon Value="@(new Icons.Regular.Size16.Delete())" Color="Color.Error" />
</FluentButton>
```

Gives you: 
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/d1f69f23-6563-4bc0-b7b1-cd36018f0039)

**Comment by satyajit-behera** [comment]
Thanks :-)
