### ISSUE TITLE
fix: Wrong alert theme with Dark Theme

### ISSUE THREAD

**Issue by ItsTheSky** [microsoft/fluentui-blazor#2200]
# 🐛 Bug Report

When using a dark theme, (all) alerts are still displayed using a light theme, thus it's impossible for us to see its content correctly.

## 💻 Repro or Code Sample

https://github.com/ItsTheSky/FUI-WrongAlertThemeBug
(don't mind the wrong name when building the site btw)

> [!NOTE]  
> When specify the (same) theme again in the page where the alert component is used, it works fine

## 🤔 Expected Behavior

The alert should be visible (basically should have the dark theme applied correctly)

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/50667548/c5262a02-64ad-482c-84a7-2f0a1d70589a)

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Brave
* .NET and Fluent UI Blazor library Version: .NET 8 and FUI 4.8.0

**Comment by MarvinKlein1508** [comment]
Hi @ItsTheSky

this seems to be expected. You'll need to add your FluentThemePicker to your `Routes.razor`.

```asp
<FluentDesignTheme Mode="DesignThemeModes.Dark" OfficeColor="OfficeColor.Office" />
<Router AppAssembly="typeof(Program).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)"/>
        <FocusOnNavigate RouteData="routeData" Selector="h1"/>
    </Found>
</Router>
```

**Comment by ItsTheSky** [comment]
> Hi @ItsTheSky
> 
> this seems to be expected. You'll need to add your FluentThemePicker to your `Routes.razor`.
> 
> ```
> <FluentDesignTheme Mode="DesignThemeModes.Dark" OfficeColor="OfficeColor.Office" />
> <Router AppAssembly="typeof(Program).Assembly">
>     <Found Context="routeData">
>         <RouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)"/>
>         <FocusOnNavigate RouteData="routeData" Selector="h1"/>
>     </Found>
> </Router>
> ```

Gotcha, someone on Discord asked me to put it in my MainLayout page and it worked fine too;
However it leads to another question: why does only the alert component have its theme broken? all other components (from what i've seen so far) work fine this way, and the alerts are the only ones impacted (again, I may be wrong, but wanted to point it out anyway :D)

**Comment by vnbaaij** [comment]
The MessageBar (what you call alert) is not a web component in its base so it doesn't respond to the design token changes like a button or a dialog. We had to program that in and that is where the FluentDesignTheme comes in.

PS, that was me on Discord
