### ISSUE TITLE
Javascript error after upgrade to v4.8.0

### ISSUE THREAD

**Issue by coderdnewbie** [microsoft/fluentui-blazor#2201]
I have just upgraded to 4.8.0 and got this error. Is this a known breaking change?

![info](https://github.com/microsoft/fluentui-blazor/assets/74407701/74c4a5af-9e6d-4df7-8a87-af269d044e15)

**Comment by vnbaaij** [comment]
You need to do a hard refresh. JS file is being cached too aggressively

**Comment by coderdnewbie** [comment]
I did that, but no luck, I am still seeing the error.

I have a new project now form the template and that is working fine, so I will start again I think. Thanks.

**Comment by dvoituron** [comment]
@vnbaaij we could add a query string like ?`v=<AssemblyVersion>` during the JS loading?
