### ISSUE TITLE
issue: Fluent Button in Fluent Datagrid template doesnt work on mobile browsers

### ISSUE THREAD

**Issue by auy66** [microsoft/fluentui-blazor#2202]
Hello,

I have a fluentdatagrid with a template column with 2 buttons.  These buttons work fine on the desktop browsers however they do not work on mobile browsers when column width is defined.  When the column width is not defined, they are at the end of the page and can barely be seen however able to click the first button and it works.   If I move this column to the beginning of the grid, then they stop working.  

When the items are inspected it appears that there is a child button element inside the fluent-button however this is missing on the mobile. 

Mobile browser(Safari and Chrome)
![image](https://github.com/microsoft/fluentui-blazor/assets/173095649/df51dc5e-7930-4b30-af2a-1c669d1f8544)

Desktop Browser:
![image](https://github.com/microsoft/fluentui-blazor/assets/173095649/105d7daa-1725-4fb7-9fa4-48256e825289)

Code:

    <FluentDataGrid Items="@FilteredEquipment" Pagination="@pagination"  GridTemplateColumns="140px 160px 100px 100px 100px 140px 140px 125px 125px 150px">
        
        <PropertyColumn Tooltip="true" Title="Equipment Type" Property="@(p => p.EquipmentGroup)" Sortable="true" />
        <PropertyColumn Tooltip="true" Title="Description" Property="@(p => p.EquipmentDescription)" Sortable="true" />
        <PropertyColumn Tooltip="true" Title="Make" Property="@(p => p.Make)"  Sortable="true" />
        <PropertyColumn Tooltip="true" Title="Model" Property="@(p => p.Model)"  Sortable="true" />
        <PropertyColumn Tooltip="true" Title="Serial #" Property="@(p => p.SerialNumber)"  Sortable="true" />
        <PropertyColumn Tooltip="true" Title="Assigned To" Property="@(p => p.AssigneeName)" Sortable="true" />
        <PropertyColumn Tooltip="true" Title="Assigned By" Property="@(p => p.AssignedbyName)" Sortable="true" />
        <PropertyColumn Title="Assigned Date" Property="@(p => p.AssignedDate)" Format="yyyy-MM-dd" Sortable="true" />
        <PropertyColumn Tooltip="true" Title="Status" Property="@(p => p.Status)" Sortable="true" />
    @if (IsAdmin || IsSupervisor)
    {
            <TemplateColumn Tooltip="true" Title="Action" Sortable="true" Context="action_button" Align="@Align.End">
                <span>
                    <FluentButton aria-label="Edit item" IconEnd="@(new Icons.Regular.Size16.Edit())" OnClick="()=> Edit(action_button.inventoryid,
                                                                                        action_button.EquipmentGroup,
                                                                                        action_button.EquipmentDescription,
                                                                                        action_button.Make,
                                                                                        action_button.Model,
                                                                                        action_button.SerialNumber,
                                                                                        action_button.AssetTag,
                                                                                        action_button.Assignedto,
                                                                                        action_button.statusid,
                                                                                        action_button.Status,
                                                                                        SelectedValue,
                                                                                        action_button.EquipmentTypeID
                                                                                        )">Edit</FluentButton>
                    <FluentButton aria-label="Delete item" IconEnd="@(new Icons.Regular.Size16.Delete())" OnClick="()=> Delete(action_button.inventoryid,
                                                                                        action_button.EquipmentGroup,
                                                                                        action_button.EquipmentDescription,
                                                                                        action_button.Make,
                                                                                        action_button.Model,
                                                                                        action_button.SerialNumber,
                                                                                        action_button.AssetTag,
                                                                                        action_button.statusid)">Delete</FluentButton>
                </span>                          

        </TemplateColumn>
        }
</FluentDataGrid>
</div>
<div class="my-4">
    <FluentPaginator State="@pagination" />
</div>

**Comment by auy66** [comment]
Hi,
Thanks for the quick reply.  I continued to troubleshoot this today by adding the horizontol scroll bar as suggested.  After adding that I found that the buttons on about top 10 rows in the grid doesnt work and anything below that works.  I also didnt check for this previously.  always clicked on the top few rows to test.      
If I remove this line from my index.html then the buttons on all rows work but ofcourse this messes up with the CSS every where. I also removed all other controls,  css etc from the razor page and nothing worked which makes me believe that this might be a CSS issue in FluentUI?      Again this is only an issue on mobile browsers, safari and chrome.
<link href="WebUI.styles.css" rel="stylesheet" />

I used an app to inspect the site on Ipad using Safari and here is what I found.
When I click on the button in the top rows to inspect he element the Col-sort-container class is highlighted.  
![image](https://github.com/microsoft/fluentui-blazor/assets/173095649/20d64934-3757-4183-96e2-4fab4f5081ed)

But when I click on the rows past the 10th column or so the highligted item is a button
![image](https://github.com/microsoft/fluentui-blazor/assets/173095649/30244225-8a0b-4add-a7dc-59767c2d3493)

**Comment by vnbaaij** [comment]
There was an issue earlier where on a specific version of Safari (can't remember which one) a column header height would be too high and effectively being shown on top of the buttons for a number of rows.

Which version of the library are you using and which version of Safari are you testing on?

If you want us to look further into this, supply us with working, ready-to-run reproduction code and clear steps in how to investigate and reproduce the issue.
