### ISSUE TITLE
feat: add a property Selectable to the FluentTreeItem

### ISSUE THREAD

**Issue by javadevil1982** [microsoft/fluentui-blazor#2207]
# 🙋 Feature Request

A property that specifies whether a FluentTreeItem is selectable or not.

Currently, in version 4.8.0, every FluentTreeItem is selectable unless it is deactivated. However, there are scenarios in which you do not want the root elements to be selected, for example, because they are only used for grouping, but you only want to be able to select their sub-elements.

## 🤔 Expected Behavior

If I define a FluentTreeItem as non-selectable, I can simply expand and collapse its sub-items. The current selection should not change.

## 😯 Current Behavior

I can select and deselect any FluentTreeItem, even those that I don't want to be selectable. Remembering the previous selection and then setting it again does not seem to work.

## 💁 Possible Solution

A property for activating or deactivating the selectability of a FluentTreeItem.

**Comment by vnbaaij** [comment]
Hi,

I think this a rather big change and not sure if it is ven possible with the current underlying web components. But we will take a look. @dvoituron any thoughts?

**Comment by dvoituron** [comment]
To hide the "selector" you can use this style for your **TreeViewItem** (using an `Id="my-id"`)

```css
#my-id::after {
    background: unset;
}

#my-id::part(positioning-region) {
    background: unset;
}
```
