### ISSUE TITLE
fix: FluentMenu not work when it's inside FluentDataGrid

### ISSUE THREAD

**Issue by MinhTruongDev** [microsoft/fluentui-blazor#2210]
# 🐛 Bug Report
I'm currently trying to make a management page with ``FluentMenu`` as an action menu inside a ``FluentDataGrid`` (image 1), and I found that it doesn't matter which menu button I click, the context will always be the last row (image 2).

## 💻 Repro or Code Sample
```C#
@page "/counter"

@using Microsoft.FluentUI.AspNetCore.Components
@using System.ComponentModel.DataAnnotations
@using System.Diagnostics


<FluentDataGrid Items="@people">
  <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" />
  <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
  <TemplateColumn Title="Actions">
    <FluentButton id="btnOpen1" Appearance="Appearance.Accent" @onclick="@(() => open = !open)">
      Open menu
    </FluentButton>
    <FluentMenu Anchor="btnOpen1" @bind-Open="open" VerticalThreshold="170">
      <FluentMenuItem OnClick="@(() => Edit(context))">
        Edit
      </FluentMenuItem>
      <FluentMenuItem OnClick="@(() => Delete(context))">
        Delete
      </FluentMenuItem>
    </FluentMenu>
  </TemplateColumn>
</FluentDataGrid>


@code {
  bool open = false;

  void Edit(Person p)
  {
    Debug.WriteLine("----------------EDIT----------------");
    Debug.WriteLine(p.PersonId);
    Debug.WriteLine(p.Name);
  }

  void Delete(Person p)
  {
    Debug.WriteLine("----------------DELETE----------------");
    Debug.WriteLine(p.PersonId);
    Debug.WriteLine(p.Name);
  }

  record Person(int PersonId, string Name, DateOnly BirthDate);

  IQueryable<Person> people = new[]
  {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9)),
    }.AsQueryable();
}
```

## 🤔 Expected Behavior
It should have the data of the row I click

## 😯 Current Behavior
Doesn't matter which menu button I click, the context will always be the last row

## 🔦 Context
- Image 1: 
![image](https://github.com/microsoft/fluentui-blazor/assets/104303855/8ca592db-9790-4071-a18b-a64ca1187dcd)

- Image 2: 
![image](https://github.com/microsoft/fluentui-blazor/assets/104303855/c27902ba-c747-4600-ba8e-ea79aa543c84)

## 🌍 Your Environment

* OS & Device: Window 11 
* Browser  Google Chrome
* .NET 8.0.202  and Fluent UI Blazor library Version 4.8.0

**Comment by MinhTruongDev** [comment]
I think it has something to do with the @bind-Open since all the menu is bound to 1 variable so all of them got triggered and the last one is selected because I've tried adding unique id's as you said and this is the result (unless I'm doing it wrong? if so, sorry)

![image](https://github.com/microsoft/fluentui-blazor/assets/104303855/e43a4a07-05c9-4130-8846-f1e386cae0d2)

Sorry if I'm doing something wrong since this is the first time I'm using Blazor

Here is the code sample after the fix like you said
```C#
<FluentDataGrid Items="@people">
  <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" />
  <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
  <TemplateColumn Title="Actions">
    <FluentButton Id="@("btnOpen-" + context.PersonId)" Appearance="Appearance.Accent" @onclick="@(() => open = !open)">
      Open menu
    </FluentButton>
    <FluentMenu Anchor="@("btnOpen-" + context.PersonId)" @bind-Open="open" VerticalThreshold="170">
      <FluentMenuItem OnClick="@(() => Edit(context))">
        Edit
      </FluentMenuItem>
      <FluentMenuItem OnClick="@(() => Delete(context))">
        Delete
      </FluentMenuItem>
    </FluentMenu>
  </TemplateColumn>
</FluentDataGrid>```

Thanks.

**Comment by dvoituron** [comment]
With this code, you use a single `open` variable. When this variable becomes `true`, all FluentMenu will be opened. You could use 1 variable per menu.

**Comment by MinhTruongDev** [comment]
Oh this is my mistake, I should've just used ``Trigger="MouseButton.Left"`` instead of binding an event to the button
Everything works fine now,
Thanks a lot
