### ISSUE TITLE
fix: expand/collapse in FluentNavMenu after upgrading from 4.7.2 to 4.8.0

### ISSUE THREAD

**Issue by ahmedbastawisi** [microsoft/fluentui-blazor#2211]
# 🐛 Bug Report

After upgrading from 4.7.2 to 4.8 the FluentNavMenu component has unexpected behavior where the first FluentNavGroup can not be expanded nor collapsed (only the first FluentNavGroup inside the FluentNavMenu)  

## 😯 Current Behavior

https://github.com/microsoft/fluentui-blazor/assets/32500711/51a204f7-a021-49dc-b402-b2f545563f8a

## 🌍 Your Environment

* OS & Device: Window on PC
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version 8.0.6 and 4.8.0

**Comment by vnbaaij** [comment]
Weird! We'll look into it.

**Comment by MarvinKlein1508** [comment]
@vnbaaij FYI: the issue only exists when the `FluentNavGroup` is expanded by default :)

**Comment by vnbaaij** [comment]
And only when running the WebAssembly version of the demo site...Will dig deeper.

**Comment by vnbaaij** [comment]
Please confirm this is fixed by using a preview NuGet package **later** than Microsoft.FluentUI.AspNetCore.Components 4.8.1-preview.24172.4

**Comment by mustaphaHm** [comment]
@vnbaaij, where can I find the preview NuGet package, please? I also have a problem with the header profile menu aligned to the end; it was working before.

https://github.com/microsoft/fluentui-blazor/assets/37129911/50a41655-ce53-4e73-a2cb-2640ba703681

**Comment by vnbaaij** [comment]
See https://baaijte.net/blog/microsoft-fluentui-aspnetcore.components-4.8/ at the end

**Comment by ahmedbastawisi** [comment]
Just tried the following preview pkgs, but the issue still persist

Microsoft.FluentUI.AspNetCore.Components Version="4.8.1-preview.24172.5"
Microsoft.FluentUI.AspNetCore.Components Version="4.8.1-preview.24172.7"
Microsoft.FluentUI.AspNetCore.Components Version="4.8.1-preview.24173.1"

note: cleaned and rebuild the sln each time.

https://github.com/microsoft/fluentui-blazor/assets/32500711/350cca2e-2774-497f-9845-eb9c6368366d

**Comment by mustaphaHm** [comment]
@ahmedbastawisi it worked for me with this package Install-Package Microsoft.FluentUI.AspNetCore.Components -version 4.8.1-preview.24173.1

**Comment by ahmedbastawisi** [comment]
After some investigation i found that if you have (one and only one FluentNavGroup) like the ex i shared it does not work.

but if i added more FluentNavGroup it weirdly work fine!

**Comment by f4n0** [comment]
I've installed the version 4.8.1 but for me the issue was not resolved. Am I missing something? 

![image](https://github.com/microsoft/fluentui-blazor/assets/36199751/690e1b7f-f81a-4e10-af37-337d02a8d69e)

**Comment by vnbaaij** [comment]
@f4n0 Yes, you missed something. This is not released in v4.8.1. It will be in v4.8.2. See WhatsNew for what was in 4.8.1

**Comment by vnbaaij** [comment]
Soon ™️
