### ISSUE TITLE
fix: Support Safari 15 (and earlier)

### ISSUE THREAD

**Issue by mobinseven** [microsoft/fluentui-blazor#2215]
# 🐛 Bug Report

Looks like this framework does not support Safari 15 and older versions (iOS or macOS.)

## 💻 Repro or Code Sample

Just visit [fluentui-blazor.net](https://www.fluentui-blazor.net/) on the iOS or macOS devices using Safari 15 and older.
I have also created [a minimal repo](https://github.com/mobinseven/FluentUiTestApp) to check.
## 🤔 Expected Behavior

There should be no error and the app should start up correctly.

## 😯 Current Behavior

The app crashes on rendering FluentUi components. Open browser console to see errors.
Safari 15:
```
blazor.web.js:2 Unhandled Promise Rejection: TypeError: Illegal constructor
(anonymous) @ blazor.web.js:2
asyncFunctionResume @ [native code]:1
(anonymous) @ [native code]:1
promiseReactionJobWithoutPromise @ [native code]:1
promiseReactionJob @ [native code]:1
blazor.web.js:2 Unhandled Promise Rejection: TypeError: Illegal constructor
(anonymous) @ blazor.web.js:2
asyncFunctionResume @ [native code]:1
(anonymous) @ [native code]:1
promiseReactionJobWithoutPromise @ [native code]:1
promiseReactionJob @ [native code]:1
blazor.web.js:2 Unhandled Promise Rejection: TypeError: Illegal constructor
(anonymous) @ blazor.web.js:2
asyncFunctionResume @ [native code]:1
(anonymous) @ [native code]:1
promiseReactionJobWithoutPromise @ [native code]:1
```
Safari 11:
```
[Error] Unhandled Promise Rejection: SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
	(anonymous function) (blazor.web.js:1:187184)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
[Error] Unhandled Promise Rejection: SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
	(anonymous function) (blazor.web.js:1:186983)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
[Error] Unhandled Promise Rejection: SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
	(anonymous function) (blazor.web.js:1:150211)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
```

## 🌍 Your Environment

* OS & Device: Any iOS or macOS devices using Safari 15 or older.
* Browser: Safari
* .NET and Fluent UI Blazor library Version: Latest Stable (but I have tested 3.7 also, which had the same issue)

**Comment by dvoituron** [comment]
Could you give us mire details? I'm opening the demo website in my iPhone and it seems correct. 

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/6ead7de0-98af-4592-bbc0-30271b18f451)

**Comment by mobinseven** [comment]
> Could you give us more details? I'm opening the demo website in my iPhone and it seems correct.

Which version of iOS your devices is using?

I have tested with multiple devices with iOS 15.7 and older.

**Comment by dvoituron** [comment]
The last one: 17.5.1 (iPhone12).
Is it possible that you have an extension? Or could you give us the full details of the error, so that we know which component of FluentUI-Blazor is failing?

**Comment by dvoituron** [comment]
> Yes. I have tested iOS 16 and above and there was no issue at all.

For older versions of iOS, I don't think there's anything we can do. :-(

**Comment by vnbaaij** [comment]
Closing this. As stated above, we can only support latest major browser releases.
