### ISSUE TITLE
feat: add Timeline

### ISSUE THREAD

**Issue by franklupo** [microsoft/fluentui-blazor#2222]
# 🙋 Feature Request
In a lot of UI libraries the Timeline is present.

- https://mudblazor.com/components/timeline
- https://mui.com/material-ui/react-timeline/
- https://www.syncfusion.com/blazor-components/blazor-timeline

in (blazor) fluent-ui this is missing, 

## 😯 Current Behavior

Not implemented a.t.m.

## 💻 Examples
https://mudblazor.com/components/timeline

**Comment by dvoituron** [comment]
You have the **FluentWizard**. Maybe you could use it in some situations. 

https://www.fluentui-blazor.net/Wizard

You can always propose a PR to add it to the components 😊

**Comment by vnbaaij** [comment]
The 'problem' with this is that that is no real specification for how this would look like in the Fluent Design. We can of course make some assumption, but you know what they say about those...

We will put it on our internal ToDo list to investigate (and close this one here), but that is **not** a confirmation that we are going to build it
