### ISSUE TITLE
SelectedItemChanged doesn't trigger after updating Items in FluentTreeView

### ISSUE THREAD

**Issue by yermakovsergey** [microsoft/fluentui-blazor#2223]
Tried new feature #1945 , have some problems with SelectedItemChanged after updating Items provided to TreeViewItem

# 🐛 Bug Report

I'm generating some <TreeViewItem> collection, with sub Items, providing this collection to TreeViewItem, tree works fine when I'm just navigating/collapsing/expanding/selecting - SelectedItemChanged event works. 
When I'm moving sub item from one folder(parent item) to another, selecting item stop triggering SelectedItemChanged. 
I've tried second way- after moving sub item tried to generate new <TreeViewItem> collection, binded to TreeViewItem, SelectedItemChanged didn't work also.

## 💻 Repro or Code Sample

Make <TreeViewItem> collection for Items providing, with sub item. After that make some changes in collection- move subitem between items, or make new collection with updated source. after that selection doens't trigger SelectedItemChanged. 

## 🤔 Expected Behavior

I'm expecting that I can do update in Items provider collection and selection will work after that.

## 😯 Current Behavior

after updates in Items provider collection, selecting item doesn't triggered SelectedItemChanged. 

## 💁 Possible Solution

maybe after Items provider update we can call some .Refresh() for FluentTreeView ref.

## 🔦 Context

In my case I'm using SelectedItemChanged to expose some details of selected tree item.
User have a dropdown with items sources selection so I need to have possibility to full update date source in Items.
Also when user can move items in tree. 

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser Google Chrome
* .NET and Fluent UI Blazor library Version 8.0.6 and 4.8.0

**Comment by vnbaaij** [comment]
Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

Help us to help you. Thanks.
