### ISSUE TITLE
fix: Misleading cursor in toast action

### ISSUE THREAD

**Issue by MarkMpn** [microsoft/fluentui-blazor#2229]
# 🐛 Bug Report

A toast has a dismiss icon in the top right corner. There is also an area to the left of the dismiss icon which has the same `cursor: pointer` but does nothing when clicked. To the user this cursor indicates that clicking there should dismiss the toast in the same way as clicking directly on the "x".

## 💻 Repro or Code Sample

Open a toast from the demo site at https://www.fluentui-blazor.net/Toast

Move the mouse over the highlighted area:

![image](https://github.com/microsoft/fluentui-blazor/assets/31017244/c8a7b1be-7bb3-4bf4-8ad7-3e4821d620f2)

## 🤔 Expected Behavior

Either clicking this area should dismiss the toast, or this area should not have the `cursor: pointer` style.

## 😯 Current Behavior

The cursor will change to a hand, but clicking will have no effect.

## 💁 Possible Solution

Either remove the `cursor: pointer` style from the `.fluent-toast ::deep .fluent-toast-action` selector, reduce the width, or make clicking this area dismiss the toast as if the user had clicked the "x"

## 🔦 Context

Users get frustrated trying to dismiss the toasts.

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser Google Chrome
* .NET and Fluent UI Blazor library Version 8.0.4 and 4.6.0

**Comment by vnbaaij** [comment]
The Icon is already getting a cursor set because of the `OnClick` handler. The cursor from the fluent-toast-action area is now removed
