### ISSUE TITLE
feat: set Items as optional in ItemsProvider

### ISSUE THREAD

**Issue by ArturMichalak** [microsoft/fluentui-blazor#2232]
# 🙋 Feature Request

The ResolveItemsRequestAsync method assumes that the Items from the ItemsProvider can be null, but the GridItemsProviderResult type forces the list. Loading indicator terminates even if no satisfactory results are received.

## 🤔 Expected Behavior

It is possible to specify null as Items.

## 😯 Current Behavior

Items must be a list.

## 🔦 Context

DataGrid with Virtualize parameter when first running ItemsProvider gives req.Count as null.

**Comment by vnbaaij** [comment]
No, we are not going to change that logic. Even if the result is that no rows are being returned, the grid is then no longer in a Loading state. It is not on us to interpretate if that is a satisfactory result or not.

**Comment by ArturMichalak** [comment]
Do you have any other idea to bypass the problem with req.Count as null?

**Comment by vnbaaij** [comment]
I think that is something that needs to be handled on 'your' side. We can't determine what is right or wrong when null is returned.

**Comment by ArturMichalak** [comment]
Perhaps there was a small misunderstanding.
I would like to deal with invalid input parameters on "my side" (e.g. req.Count is null) but I can't as after every ItemsProvider call the loading indicator disappears and doesn't open when ItemsProvider called again.

```c#
private GridItemsProvider<RowDto> InitialProvider => async req =>
{
    try
    {
        _grid.SetLoadingState(true);
        if (req.Count is null) throw new OperationCanceledException();
        var results = await new GridCommand(args).Execute(req.CancellationToken);
        return GridItemsProviderResult.From(
            items: results.Items,
            totalItemCount: results.TotalItemCount
        );
    }
    catch (OperationCanceledException ex) {}

    return GridItemsProviderResult.From(
        items: Array.Empty<RowDto>(),
        totalItemCount: -1
    );
};
```

**Comment by vnbaaij** [comment]
The disappearing of the loading indicator is by design. The provider has retuned, so loading is done.

**Comment by ArturMichalak** [comment]
So in the case of using the Virtualize parameter, which gives req.Count as null on the first load? Should I use an external loading indicator?

**Comment by vnbaaij** [comment]
No, you should anticipate on that first request returning null. You know that will always be the case.

**Comment by ArturMichalak** [comment]
At this moment, I have no way to handle it.
I tried with OnAfterRender, loading flags, etc., but nothing worked.

**Comment by vnbaaij** [comment]
Sorry to hear that. Up until now, there has been no issues/discussions around this. You must have a pretty unique use case.

**Comment by ArturMichalak** [comment]
I will make a reproduced example and report the bug issue if it is not a problem.

**Comment by vnbaaij** [comment]
Sure, no problem. But as this is one of the most used (and most complex) components, we will be very careful to not have any breaking changes. So no guarantee that your issue can or will be resolved.

**Comment by ArturMichalak** [comment]
Of course!
