### ISSUE TITLE
fix: Menu outside of the screen in `FluentMenu`

### ISSUE THREAD

**Issue by LucaQuaranta** [microsoft/fluentui-blazor#2234]
# 🐛 Bug Report

Depending on the screen size and menu item labels lenght, the `FluentMenu` may go outside the screen bounds.

## 💻 Repro or Code Sample

This is observable in the example on the demo page: https://www.fluentui-blazor.net/Menu.

## 🤔 Expected Behavior

View the entire menu and its menu items.

## 😯 Current Behavior

On small screens, such as on mobile devices, when menu item labels are too long, the `FluentAnchoredRegion` related to the Menu go outside of the screen. 
![image](https://github.com/microsoft/fluentui-blazor/assets/173358577/b8ac948d-cfc7-400c-90d5-735e54c6407e)

This also happens for nested menus for menu items that have `MenuItems` property set.
![image](https://github.com/microsoft/fluentui-blazor/assets/173358577/16f5e52a-4625-4b17-906c-88c0089bbefe)

## 💁 Possible Solution

- Repositioning the inner `FluentAnchoredRegion` to the top/bottom when screen width doesn't allow to show inner Menu next to the main menu.
- Set max width to `FluentAnchoredRegion` to allow menu item labels to display on multiple lines.

## 🌍 Your Environment

* Microsoft Edge, Google Chrome, Apple Safari
* .NET 8 and Fluent UI Blazor library Version 4.7.2 and 4.8.0

**Comment by vnbaaij** [comment]
Hi,

There is only an anchored region if the menu is anchored to a specific element. 

The long text is something I feel you as the developer need to control yourself. 

With regards to the nested menu, I would strongly advice to **not** use that in a mobile display variant. On a touch screen device it will be virtually impossible topen the sub menu as you do not have the hover capability and as a click/touch event on the main items will make that selection and close the menu itself.

You could use or Grid to display/hide certain parts of the ui based on display size or do it yourself based on media queries ind other standard CSS capabilities.
