### ISSUE TITLE
fix: Selected option not initially set in FluentSelect only in version 4.8.0

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fluentui-blazor#2235]
# 🐛 Bug Report

## 💻 Repro or Code Sample

I have a FluentSelect component on my page where the initial selected option is set to null despite the property being used as the bind-Value property of the FluentSelect component and passing the Items property where I have defined one options as selected. The issues occurred after updating the nugget package from version 4.7.2 to version 4.8.0.

```
<FluentSelect Label="Language:" Items="@languages" OptionText="@(i => i.Text)" OptionValue="@(i => i.Value)" OptionSelected="@(i => i.Selected)" @bind-Value="@language" TOption="Option<string>" />
...
private string language;
private static List<Option<string>> languages = new()
{
    { new Option<string> { Value = "DE", Text = "German" } },
    { new Option<string> { Value = "EN", Text = "English", Selected = true }},
};
```
## 🤔 Expected Behavior

The bind value should be populated without me having to change the dropdown value. (only setting the value other than initial works)

## 😯 Current Behavior

Component itself shows that value is selected but language is null at the moment of use.

## 💁 Possible Solution

-

## 🔦 Context

The user should not be forced to deselect and the select the option so that the property is populated.

## 🌍 Your Environment

* OS & Device: Windows 11 PC
* Browser  Microsoft Edge latest
* .NET version 8.0.6  and Fluent UI Blazor library Version 4.8.0

**Comment by vnbaaij** [comment]
It can be that this behavior has changed between previous version and v4.8. We overhauled the list components to inherit from `FluentinputBase`

What has not changed is how this situation _should_ be implemented. When you want to bind to the Value, you should use the OptionValue to determine if an item is selected. When you bind to SelectedOption, you should use the OptionSelected to determine if an option is selected. See https://www.fluentui-blazor.net/Select#default for the 'value variant'. See below for the 'SelectedOption variant'

```
<FluentSelect Label="Language:"
              Items="@languages"
              OptionText="@(i => i.Text)"
              OptionValue="@(i => i.Value)"
              OptionSelected="@(i => i.Selected)"
              @bind-SelectedOption="@language" TOption="Option<string>" />

<p>Selected language: @language?.Text</p>

@code {
    private Option<string?> language;

    private static List<Option<string>> languages = new()
{
    { new Option<string> { Value = "DE", Text = "German" } },
    { new Option<string> { Value = "EN", Text = "English", Selected = true }},
};
}
```

Your code was using a mix of both options

**Comment by chigivigi** [comment]
Thank you for clarification, it works after modification.
