### ISSUE TITLE
fix: FluentDatePicker does not update value when current value is null and user selects date from drop down calendar in FluentDatePicker

### ISSUE THREAD

**Issue by NickHirras** [microsoft/fluentui-blazor#2237]
# 🐛 Bug Report

## 💻 Repro or Code Sample

```
@page "/test"

<FluentDataGrid Items="@People" ShowHover="true" TGridItem="Person">
    <PropertyColumn Width="100px" Property="@(p => p.PersonId)" Title="ID" />
    <PropertyColumn Width="300px" Property="@(p => p.Name)" />
    <TemplateColumn Width="150px" Title="Birthdate" Sortable="true" SortBy="@_sortByBirthDate" Align="Align.Center" Filtered="startDate != null || endDate != null" >
      <ColumnOptions>
        <div class="search-box">
          <div>
            <FluentDatePicker @bind-Value="startDate" Label="Start date" DisabledDateFunc="@DisabledStartDate" />
          </div>
          <div>
            <FluentDatePicker @bind-Value="endDate" Label="End date" DisabledDateFunc="@DisabledEndDate" />
          </div>
        </div>
      </ColumnOptions>
      <ChildContent>
        @context!.BirthDate.ToString("yyyy-MM-dd")
      </ChildContent>
    </TemplateColumn>
</FluentDataGrid>

<div>
    <b>Peoples:</b>
    @String.Join("; ", People.Where(p => p.Selected).Select(p => p.Name))
</div>


@code {
    DateTime? startDate =  null;
    DateTime? endDate = null;

    private readonly GridSort<Person> _sortByBirthDate =
      GridSort<Person>.ByAscending(d => d.BirthDate);

    private bool DisabledStartDate(DateTime date)
    {
      return endDate.HasValue && date > endDate.Value;
    }

    private bool DisabledEndDate(DateTime date)
    {
      return startDate.HasValue && date < startDate.Value;
    }

    record Person(int PersonId, string Name, DateOnly BirthDate)
    {
        public bool Selected { get; set; }
    };

    static IQueryable<Person> People = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)) { Selected = true },
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9)),
    }.AsQueryable();

}
```

## 🤔 Expected Behavior

User should be able to select a Date even if the current value is null.

To reproduce, run this example, and click the `filter` icon on the Birtdate field. There is a date picker for startDate and endDate. Trying to change the dates by clicking the calendar does not work.

## 😯 Current Behavior

When user clicks a date from the calendar, the components value is not updated. If the user first types in a new date, that value is applied, and then the date picker works correctly.  Or initializing with a non-null value it will also work.

## 💁 Possible Solution

No solutions.

## 🔦 Context

This is an issue as of Fluent 4.8.0 release.

## 🌍 Your Environment

Chrome Version 126.0.6478.62 (Official Build) (arm64)
Mac OS Sonoma 14.5 arm64

**Comment by NickHirras** [comment]
@marciolordelo

**Comment by dvoituron** [comment]
Could you give us more details or a small example?
I've tried your example, but everything seems OK. What can I do to reproduce your problem?
What's wrong?

![peek_1](https://github.com/microsoft/fluentui-blazor/assets/8350694/885200ce-e64e-42e2-9af2-eb5225ca0c3b)

**Comment by programmerbits** [comment]
I am having this issue as well.  I can reproduce on the docs site

https://www.fluentui-blazor.net/DateTime

- Scroll down to the Default Date Picker section
- Clear the selected date from Days view
- Try to select a new date, it doesn't select

**Comment by NickHirras** [comment]
@dvoituron 


https://github.com/microsoft/fluentui-blazor/assets/3911628/bf4b6769-ea9b-4928-b1f6-5b93d4c87814

**Comment by NickHirras** [comment]
@dvoituron 

https://github.com/microsoft/fluentui-blazor/assets/3911628/e3324f00-7522-47f2-bb7e-7abba70d8140

**Comment by NickHirras** [comment]
> Could you give us more details or a small example? I've tried your example, but everything seems OK. What can I do to reproduce your problem? What's wrong?
> 

Make sure you're running with fluent 4.8.0.  Also, maybe it's language / country specific somehow?

**Comment by vnbaaij** [comment]
Fixed with PR mentioned above. You can use preview package newer than 4.8.1-preview.24174.2 to verify

**Comment by Rudtan** [comment]
4.8.1 FluentDatePicker not work

https://github.com/microsoft/fluentui-blazor/assets/138755518/da90dd2e-e3ee-4916-8861-9677931c5429

**Comment by vnbaaij** [comment]
We had to do a patch release (v4.8.1) for an upcoming icons update. We mention this as the only change in the WhatsNew docs. 

This release does not include this or any other fixes yet. These will be in v4.8.2

**Comment by vnbaaij** [comment]
Updated info on [releases](https://github.com/microsoft/fluentui-blazor/releases/tag/v4.8.1) page as well
