### ISSUE TITLE
fix: FluentSwitch, FluentAutocomplete and serverals other components do not align at the middle when using inside FluentDataGrid

### ISSUE THREAD

**Issue by hevilhuy** [microsoft/fluentui-blazor#2244]
## 💻 Repro or Code Sample

```
        <FluentDataGrid Virtualize="true" Items="Advisors">
            <TemplateColumn Context="ctx" Title="Admin">
                <FluentSwitch @bind-Value="@ctx.Admin" @bind-Value:after="() => PropageAdmin(ctx.Id)" />
            </TemplateColumn>
        </FluentDataGrid>
```
![image](https://github.com/microsoft/fluentui-blazor/assets/17383256/f1c8b787-4b92-48ef-a0d0-fad609cbcb06)

## 🤔 Expected Behavior

`FluentSwitch` should be placed in the middle per vertical perspective of the row. Notice the Email column is correct set

## 😯 Current Behavior

`FluentSwitch` at the bottom of the row

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
The grid is not meant to be used as a row data editor. Some components, for example the select do not work correctly in that setup because of the underlying web components.

We only automatically align text. The rest is up to you. You could use standard css or our Stack or Grid components for that.
