### ISSUE TITLE
fix: items number badge becomes almost invisible. Also +0 is shown in Overflow component

### ISSUE THREAD

**Issue by darcome** [microsoft/fluentui-blazor#2248]
# 🐛 Bug Report

The badge containing the number of "invisible" items becomes almost invisible sometimes and it also shows a +0 which I think is useless...

## 💻 Repro or Code Sample

I have tested it in the demo site:

Badge half visible:
![image](https://github.com/microsoft/fluentui-blazor/assets/18150093/9091c02b-80b4-4faf-840c-f9b0dd59bad8)

Badge almost invisible and therefore "useless":
![image](https://github.com/microsoft/fluentui-blazor/assets/18150093/cc1aa05b-05ec-4dc9-86db-39316fe61c95)

Badge showing +0 which in my opinion is useless too.
![image](https://github.com/microsoft/fluentui-blazor/assets/18150093/3c654b4f-fa20-4ed4-bfb6-801549f0635b)

## 🤔 Expected Behavior

The badge should always be visible and disappear when it shows +0 because it means there are no overflown items.

## 🌍 Your Environment

The screenshots come from the demo site.

**Comment by dvoituron** [comment]
Maybe will be fixed with #2236. @vnbaaij can you validate that?

**Comment by vnbaaij** [comment]
I have indeed added a 'compensation' for the badge itself in that PR. Will test it some more and will also look at if we can prevent the +0 case

**Comment by vnbaaij** [comment]
Fixed with #2236
