### ISSUE TITLE
FluentMultiSplitter - Collapsed doesn't work with fixed size panel

### ISSUE THREAD

**Issue by ianclough** [microsoft/fluentui-blazor#2249]
# 🐛 Bug Report

FluentMultiSplitter, Collapsible/Collapsed doesn't work with a fixed size panel 

## 💻 Repro or Code Sample

@page "/MultiSplitter"
@rendermode InteractiveServer

<h3>MultiSplitter</h3>

<FluentSwitch Label="Collapse 2" @bind-Value="_collapsed2"></FluentSwitch>
<FluentSwitch Label="Collapse 3" @bind-Value="_collapsed3"></FluentSwitch>
<FluentMultiSplitter Orientation="Orientation.Horizontal" Style="height: 50%; width: 100%; border: 2px solid red">
    <FluentMultiSplitterPane>
        <h1>Panel 1</h1>
    </FluentMultiSplitterPane>
    <FluentMultiSplitterPane Collapsed="@_collapsed2" Collapsible="true">
        <h1>Panel2</h1>
    </FluentMultiSplitterPane>
    <FluentMultiSplitterPane Size="300px" Resizable="false" Collapsed="@_collapsed3" Collapsible="true">
        <h1>Panel3</h1>
    </FluentMultiSplitterPane>
</FluentMultiSplitter>

@code {
    private bool _collapsed2;
    private bool _collapsed3;

}

## 🤔 Expected Behavior

I would expect a fixed size panel to be collapsible

## 😯 Current Behavior

A fixed size panel remains at its pre-set size and doesn't collapse.

## 🔦 Context

Really appreciate the MultiSplitter component and can probably work around this with a conditional section rather than trying to collapse.

## 🌍 Your Environment

Windows 10 in a Parallels VM
Microsoft Edge
.NET8, Fluent UI Blazor library 4.8.0

**Comment by dvoituron** [comment]
Your code example must be between triple quotes to be displayed as code (we can't see anything at the moment).

At the moment, this is effectively a restriction, by design, where the **Pane** can only be resized and therefore collapsed when `Resizable="true"`.

**Comment by ianclough** [comment]
Ok, thank you for the fast response, I think I can live with that, code included below for completeness.

"""
@page "/MultiSplitter"
@rendermode InteractiveServer

<h3>MultiSplitter</h3>

<FluentSwitch Label="Collapse 2" @bind-Value="_collapsed2"></FluentSwitch>
<FluentSwitch Label="Collapse 3" @bind-Value="_collapsed3"></FluentSwitch>
<FluentMultiSplitter Orientation="Orientation.Horizontal" Style="height: 50%; width: 100%; border: 2px solid red">
    <FluentMultiSplitterPane>
        <h1>Panel 1</h1>
    </FluentMultiSplitterPane>
    <FluentMultiSplitterPane Collapsed="@_collapsed2" Collapsible="true">
        <h1>Panel2</h1>
    </FluentMultiSplitterPane>
    <FluentMultiSplitterPane Size="300px" Resizable="false" Collapsed="@_collapsed3" Collapsible="true">
        <h1>Panel3</h1>
    </FluentMultiSplitterPane>
</FluentMultiSplitter>

@code {
    private bool _collapsed2;
    private bool _collapsed3;

}
"""
