### ISSUE TITLE
fix: `CSSBuilder` removes valid CSS class names provided by external CSS frameworks

### ISSUE THREAD

**Issue by ApacheTech** [microsoft/fluentui-blazor#2254]
# 🐛 Bug Report

The `CSSBuilder` will remove valid CSS classes from the class list of components. For instance, the following are all valid class names provided by TailwindCSS:

* min-h-[16px]
* p-[2rem]
* bg-[#ff0000]
* bg-red-500/50
* w-11/12
* bg-[#ff0000]/50
* my-abitrary-value-[#ff0000]/100

## 💻 Repro or Code Sample

```csharp
    [Fact]
    public void CssBuilder_AddValidUserClass()
    {
        // Arrange
        var expected = "ml-2 inline-block min-w-[16px]";
        var cssBuilder = new CssBuilder(expected);

        // Act
        var actual = cssBuilder.Build();

        // Assert
        Assert.Equal(expected, actual);
    }
```

i.e.

```xml
<FluentIcon Value="new Icons.Regular.Size16.Settings()" OnClick="Edit" Class="ml-2 inline-block min-w-[16px]" />
```

## 🤔 Expected Behaviour

The class list should read `class="ml-2 inline-block min-w-[16px]"`, with all valid CSS classes intact.

## 😯 Current Behaviour

The class list reads `class="ml-2 inline-block"`, with `min-w-[16px]` removed, even though it is valid.

## 💁 Possible Solution

The regex used [here](https://github.com/microsoft/fluentui-blazor/blob/c6cdfbf4133252b3e0ae4bebce58640fe302c9e1/src/Core/Utilities/CssBuilder.cs#L106) should read:

```regex
^[a-zA-Z_][a-zA-Z0-9_-]*(\[[^\]]+\])?(\/\d{1,3})?$
```

### Explanation

* **^:** Asserts the start of the string.
* **[a-zA-Z_]:** Ensures the first character is a letter (a-z, A-Z) or an underscore (_).
* **[a-zA-Z0-9_-]*:** Ensures subsequent characters are letters, digits, hyphens (-), or underscores (_).
* **(\[[^\]]+\])?:** Optionally matches a part that starts with [, followed by one or more characters that are not ], and ends with ].
* **(\/\d{1,3})?:** Optionally matches a / followed by one to three digits, representing the opacity value (to cover 100 as well).
* **$:** Asserts the end of the string.

### Example Matches

* min-h-[16px]
* p-[2rem]
* bg-[#ff0000]
* bg-red-500/50
* w-11/12
* bg-[#ff0000]/50
* my-abitrary-value-[#ff0000]/100

I have prepared a PR with this fix for approval.

## 🔦 Context

We use FluentUI heavily within many of our projects, and there is a large overlap with FluentUI, and Tailwind. The Regex at current will disallow the use of a large amount of classes that Tailwind offers, including making any class "important", using any negative values for margins, padding, etc., using any opacity modifiers, and using any arbitrary values. The changes made to this regex addresses all of these issues, and more. While it is not an exhaustive fix for everything that any CSS framework will offer, it will fix that vast majority of use-cases.

Currently, FluentUI actively fights against frameworks such as Tailwind, when it should not need to, or want to. While I have focussed on Tailwind here within our use-case, other similar frameworks for CSS utility classes will suffer the same.

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Firefox, Chrome, Opera, and Edge.
* .NET and Fluent UI Blazor library Version [e.g. 8.0.3 and 4.8.0]

**Comment by dvoituron** [comment]
This issue has just been discussed here: #2251

**Comment by dvoituron** [comment]
I'm going to close this one and keep only one (the first).
