### ISSUE TITLE
4.8.1 FluentDatePicker not work

### ISSUE THREAD

**Issue by Rudtan** [microsoft/fluentui-blazor#2257]
4.8.1 FluentDatePicker not work

https://github.com/microsoft/fluentui-blazor/assets/138755518/da90dd2e-e3ee-4916-8861-9677931c5429

_Originally posted by @Rudtan in https://github.com/microsoft/fluentui-blazor/issues/2237#issuecomment-2188032616_

**Comment by vnbaaij** [comment]
Closing this as it is not a new issue. New version containing the fits has not been released yet
