### ISSUE TITLE
fix: Disabled option does not get showed as selected value when @bind-Value is equal disabled one [FluentSelect]

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2262]
# 🐛 Bug Report

Consider this example:
```asp
<FluentSelect @bind-Value="@selectValue4" TOption="string">
    <FluentOption Value="Option One">Option One</FluentOption>
    <FluentOption Value="Option Two" Disabled>Option Two</FluentOption>
    <FluentOption Value="Option Three">Option Three</FluentOption>
    <FluentOption Value="Option Four">Option Four</FluentOption>
</FluentSelect>
<p>Selected: @selectValue4</p>
@code {
    string? selectValue4 = "Option Two";
}
```

On render you will see this now:
![grafik](https://github.com/microsoft/fluentui-blazor/assets/32510006/d387005d-feed-4d47-a21e-8d983e2e959f)

The component shows a different selected value instead of selectedValue4.

## 💻 Repro or Code Sample

I've created a branch which shows this issue:
https://github.com/MarvinKlein1508/fluentui-blazor/tree/disabled-options-not-selected
 SImply run the project and go to `/Select` => `Manual Options`

## 🤔 Expected Behavior
I would the correct value to be shown as selected in the component.

## 😯 Current Behavior

Wrong value will be shown.

## 🔦 Context

I'm using the disable property to prevent certain users to allow to change to a speicfic status. But they should be able to switch from disabled statuses to non disabled ones.

## 🌍 Your Environment
Mozilla Firefox

Components v4.8.0
.NET 8.0.x

**Comment by dvoituron** [comment]
I understand the difference between the `Value` and the screen value.
But if you force a disabled value to be set, which one do you expect to have in the `Value` property ?

We can't go through all the elements to find the first 'non-disabled' item.

**Comment by MarvinKlein1508** [comment]
@dvoituron 

I would expect the component to display the disabled value as selected to me and then allow me to select a non disabled value per hand.

**Comment by dvoituron** [comment]
Mmm. I'm not sure if the background web components allow it.

**Comment by MarvinKlein1508** [comment]
@dvoituron 
basically I want it to behave like vanilla InputSelect.
https://github.com/MarvinKlein1508/SelectVanillaExample

![expected](https://github.com/microsoft/fluentui-blazor/assets/32510006/80c94909-b71e-4b80-875e-3c0383f8c1bb)

**Comment by dvoituron** [comment]
Sorry, but the Web Component doesn't accept this feature :-(
See my light sample: https://jsfiddle.net/dvoituron/uew7dy90/

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="https://unpkg.com/@fluentui/web-components"></script>
  </head>
  <fluent-select value="2">
    <fluent-option value="1">One</fluent-option>
    <fluent-option value="2" disabled>Two</fluent-option>
    <fluent-option value="3">Three</fluent-option>
  </fluent-select>
</html>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/4b13edef-20f6-4b0b-ba16-4f29ac49d649)

**Comment by MarvinKlein1508** [comment]
@dvoituron no problem. Do I need to post about this somewhere else or do you take care of it? 

As a workaround I'm checking within disabled if my propery is not equal to the current one.

**Comment by vnbaaij** [comment]
I'm guessing we are not going to see this fixed in the v2 version of the web components anymore. @MarvinKlein1508 you want to keep this open nevertheless?

**Comment by MarvinKlein1508** [comment]
@vnbaaij I'm going to post tomorrow in the Fluent repo and link this issue here.

Do you know if/when we can expect v3 to be ready for production and will this repo here will be migrated to V3? 

If so you may create fluentv3 label.

**Comment by vnbaaij** [comment]
> @vnbaaij I'm going to post tomorrow in the Fluent repo and link this issue here.

👍

> Do you know if/when we can expect v3 to be ready for production and will this repo here will be migrated to V3?

They are currently in beta. and yes, we will implement that on our side as well. There will however be *a lot* of breaking changes between web components (wc) v2 and v3. So on our side  wc v3 will mean a new **major** version release (v5). There is a chance that wc v3 will not be on par with v2 wrt the set of components included in the final release. So our v5 might have less components in the beginning. Not totally clear yet how it will all fan out.

 
> If so you may create fluentv3 label.
`vNext` label has already been created

**Comment by vnbaaij** [comment]
Closing this as it can not be solved on our side.
