### ISSUE TITLE
TreeView: Is it possible to have clicking anywhere on the row expand the item?

### ISSUE THREAD

**Issue by Rocky-25** [microsoft/fluentui-blazor#2263]
Is it possible to have clicking anywhere on the row expand the item?

I tried using OnSelectedChange and then updating the Item.Expanded property but the documentation says: You cannot update FluentTreeItem properties. Why is this? Is it all possible to achieve what I'm after?

**Comment by vnbaaij** [comment]
No, TreeViewItem can only be expanded with the button shown in front of the item (or keyboard).
 
> You cannot update FluentTreeItem properties. Why is this? 

That is standard Blazor. You can't/shouldn't update properties of a component in code outside of that component. In this case that would be in TreeView code for a TrieViewItem.

>Is it all possible to achieve what I'm after?
I don't think so.
