### ISSUE TITLE
feat: add Color to/in FluentPersona

### ISSUE THREAD

**Issue by michelmoorlag** [microsoft/fluentui-blazor#2280]
# 🙋 Feature Request

The FluentPersona background color seems to be fixed. It would be nice if we could change color dependend on a bound property that takes light/dark mode in account

## 🤔 Expected Behavior

Add a "CalculateColor" parameter to FluentPersona that can be set to a string. Depended on the string value a color is calculated that is used to set the background color that has sufficiant contrast with the text inside and takes in account light/dark mode

## 😯 Current Behavior

There is no way to set or alternate the color (dynamically)

## 💁 Possible Solution

A "CalculateColor" parameter that can be set to a string would be ideal. Depended on the string value a color is calculated that is used to set the background color that has sufficiant contrast with the text inside and takes in account light/dark mode.

If this is complicated setting the the CustomColor like in FluentIcon would already be a great improvement.

## 🔦 Context

We are showing a list of messages and the sender initials are shown with the FluentPersona control. Since all FluentPersonas have the same color it is hard to see which messages have the same sender. It would be nice if colors alternate where the same sender has the same color.

**Comment by dvoituron** [comment]
No, there is no background defined with the FluentPersona component.

For example, if I set the container background color to yellow.
![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/f83da53a-1ee4-4e32-a76f-f7071f3ae322)

On the other hand, you can configure everything yourself by customizing the `fluent-persona` style.

**Comment by michelmoorlag** [comment]
@dvoituron Thank you for your investigation but with customizing style I can only set fixed colors and I want it to be dynamic bases on some parameter. Second I want to set the background of the circle, not of the whole control like this:
![image](https://github.com/microsoft/fluentui-blazor/assets/14913939/6f24d4de-1157-445d-8b68-b075e23f22a4)

**Comment by michelmoorlag** [comment]
For anyone that want to set the FluentPersona background color:
I added a componentname.razor.cc file with:
`/*remove background color from FluentPersona*/
::deep .fluent-persona .initials {
    background-color: initial !important;
}`
Then you can set the color dynamically in the FluentPersona by adding something like
`Style="background-color: @variableDependendColor"`

@dvoituron Thank you for your suggestions, it helped me in the right direction
