### ISSUE TITLE
The EventCallbacks of the FluentNavGroup not working.

### ISSUE THREAD

**Issue by juchunwei** [microsoft/fluentui-blazor#2282]
Hello, not sure how to make it working, but it not working like this.

`<FluentNavGroup Icon="@(new Icons.Regular.Size24.BuildingPeople())" Title="@city.Name" OnClick="OnClick">
</FluentNavGroup>`

Please help! Thanks!

**Comment by vnbaaij** [comment]
Hi,

This is not a bug report we can or want to work with. No reproduction code or steps, no environment information, no cause or proposed solution.

Closing this. Feel free to try again with a complete report.
