### ISSUE TITLE
fix: FluentPersona component source code is in the List/ folder

### ISSUE THREAD

**Issue by thebarrettlo** [microsoft/fluentui-blazor#2285]
# 🐛 Bug Report

## 🤔 Expected Behavior

`FluentPersona` component is easily discoverable (without searching).

## 😯 Current Behavior

`FluentPersona` component is filed in the List/ folder, making the source code unlikely to find unless it is searched for. https://github.com/microsoft/fluentui-blazor/blob/6072e948565902a59ffe56da8c1fad21530cc1d0/src/Core/Components/List/FluentPersona.razor.cs

## 💁 Possible Solution

Put `FluentPersona.razor`, `FluentPersona.razor.cs`, and `FluentPersona.css` in its own folder in Components/

**Comment by dvoituron** [comment]
The files are in this folder because we created it during the development of the Autocomplete component. 

I don't think that's a problem to be there: a first quick search and you find that 😊

We could refactor that during the next "v5 phase".

**Comment by thebarrettlo** [comment]
You're right, it's a very minor annoyance, just wanted to make sure it was known if that file placement was not intended :)

**Comment by dvoituron** [comment]
And if we decide to move these files, we will lost the GIT history (including our work on Archive-v3). 

But I agree with you, and we will do that for the next major Release.

**Comment by vnbaaij** [comment]
Closing this for now.
