### ISSUE TITLE
fix: Tooltip without service not work

### ISSUE THREAD

**Issue by franklupo** [microsoft/fluentui-blazor#2296]
# 🐛 Bug Report

If you move the mouse over the button, the tooltip appears

https://github.com/microsoft/fluentui-blazor/assets/6276309/42d5bf7d-1ada-40e9-851a-59714e1dba7d

## 💻 Repro or Code Sample

```
<FluentStack>
    <FluentButton Id="visible1"
                  Appearance="Appearance.Accent"
                  OnClick="@(e => visible = !visible)">
        Click me to toggle tooltip visibility
    </FluentButton>

    <FluentTooltip Anchor="visible1"
                   Position="TooltipPosition.End"
                   Delay="200"
                   UseTooltipService="false"
                   Visible="@visible">I'm helping!</FluentTooltip>
</FluentStack>

@code
{
    bool visible = false;
}
```

## 🤔 Expected Behavior

The tooltip should only display if the button is pressed

## 😯 Current Behavior

If you move the mouse over the button, the tooltip appears

## 🌍 Your Environment

* OS & Device: Windows
* Browser Google Chrome
* .NET and Fluent UI Blazor library Version 8.0.302 and 4.8.1

**Comment by vnbaaij** [comment]
This is 'by design'. If you do not use the service, the tooltip will always be displayed immediately on hover.

It kind of says that in the docs on the first line but it should be made more clear. I'll amend the docs.

**Comment by franklupo** [comment]
https://github.com/microsoft/fluentui-blazor/assets/6276309/3209f8e7-5a36-4025-886c-b3145de264c4


The visible variable is false. When the mouse passes over the tooltip is displayed. If you click the button twice the variable changes to true and then false when the mouse passes over again the tooltip is not displayed. For me the problem is the first time.

**Comment by dvoituron** [comment]
Your example is the EXACT code used in the Demo page. And it works correctly.
https://www.fluentui-blazor.net/Tooltip#alwaysvisible
![peek_4](https://github.com/microsoft/fluentui-blazor/assets/8350694/ef9e3043-269b-422e-b1f2-105c099d9b0b)

Perhaps you've added another component with the same `visible1` ID? Or another element?

**Comment by franklupo** [comment]
The example start with variable `visible = true`. In my case  `visible = false`

**Comment by dvoituron** [comment]
This is a problem that depends on the WebComponent `fluent-tooltip`. You can write an issue in [their GitHub](https://github.com/microsoft/fluentui/tree/web-components-v2/packages/web-components/src/tooltip)
