### ISSUE TITLE
fix: FluentE Group doesn't work the first menu element.

### ISSUE THREAD

**Issue by srburton** [microsoft/fluentui-blazor#2299]
# 🐛 Bug Report
Hello, it seems that an old problem has happened again with FluentNavGroup, the first element in the list is not working.

## 💻 Repro or Code Sample

```razor

<FluentNavMenu Width="320" CustomToggle="true">
    <FluentNavLink Icon="@(new Icons.Regular.Size24.Home())">Inicio</FluentNavLink>

    <FluentNavGroup Title="Board" Icon="@(new Icons.Regular.Size24.UsbPlug())" >
        <FluentNavLink Icon="@(new Icons.Regular.Size24.Info())">Informação</FluentNavLink>
        <FluentNavLink Icon="@(new Icons.Regular.Size24.CloudSync())">Centro Atualização</FluentNavLink>
    </FluentNavGroup>

    <FluentNavGroup Title="Manager" Icon="@(new Icons.Regular.Size24.Apps())">
        <FluentNavLink Icon="@(new Icons.Regular.Size24.TicketDiagonal())">Eventos</FluentNavLink>
        <FluentNavLink Icon="@(new Icons.Regular.Size24.DrinkMargarita())">Bebidas</FluentNavLink>
        <FluentNavLink Icon="@(new Icons.Regular.Size24.DrinkToGo())">Doses</FluentNavLink>
    </FluentNavGroup>

    <FluentNavGroup Title="PDV" Icon="@(new Icons.Regular.Size24.DesktopToolbox())">
        <FluentNavLink Icon="@(new Icons.Regular.Size24.Desktop())">Terminal</FluentNavLink>
        <FluentNavLink Icon="@(new Icons.Regular.Size24.Settings())">Configuração</FluentNavLink>
    </FluentNavGroup>
</FluentNavMenu>

```
## 🤔 Expected Behavior

The expected behavior is that all FluentNavGroup dropdowns

## 😯 Current Behavior

![Screenshot_8](https://github.com/microsoft/fluentui-blazor/assets/15394508/8ac08569-ee10-4c7b-a3cc-7d681c46a09a)
![Screenshot_9](https://github.com/microsoft/fluentui-blazor/assets/15394508/ec39d530-c08e-458c-8a92-5a8daeaddeaf)
![Screenshot_10](https://github.com/microsoft/fluentui-blazor/assets/15394508/bba79f02-8df5-4cdf-b144-523956ec199a)

## 💁 Possible Solution

I think it's a javascript problem.

## 🌍 Your Environment

- Blazor MUAI 
- .Net8.0

**Comment by vnbaaij** [comment]
This has been reported already and ids fixed with #2293. Will be in next release (soon)
