### ISSUE TITLE
fix: clear selection in FluentCombobox

### ISSUE THREAD

**Issue by joriverm** [microsoft/fluentui-blazor#2302]
# 🐛 Bug Report

when code clears the selection of a combobox, the combobox reverts back to the value before it was cleared.
this is something that was fixed in issue #1485 and PR #1506 but was introduced in the refactor of #2118 for issue #2077

A possible solution was found, but before making a PR i wanted to check if the change was accepted or why the null coalesce was put in a comment.

i will also be doing some testing to check if all the cases from the issues mentioned above still work

## 💻 Repro or Code Sample

I Added the following to the `ComboboxDefault.razor` from the demo site : 
```
<FluentButton OnClick="@(() => Person =null)">Select first person</FluentButton>
<FluentCombobox Items="@Data.People"
                OptionValue="@(i => i?.PersonId.ToString())"
                @bind-SelectedOption=@Person>
    <OptionTemplate>
        <FluentIcon Value="@(new Icons.Regular.Size16.Person())" Slot="end" OnClick="@(() => DemoLogger.WriteLine($"Icon for {@context?.LastName} selected"))" />
        @context?.FirstName (@context?.LastName)
    </OptionTemplate>
</FluentCombobox>
<p>
    Selected: @Person?.FirstName (@Person?.LastName)
</p>

<FluentCombobox Items="_items"
                TOption="string"
                @bind-SelectedOption=@Filter />

<FluentButton IconEnd="@(new Icons.Regular.Size12.Dismiss())" OnClick="@(() =>DeleteFilter())" />

<FluentCombobox Items="_items"
                TOption="string"
                SelectedOptionChanged="x => HandleOriginProductChanged(x)" />
```
and this code : 
```
    public Person? Person { get; set; } = default!;

    private List<string> _items = ["Item 1", "Item 2", "Item 3"];
    private string _filter = string.Empty;
    public string Filter
    {
        get => _filter;
        set
        {
            _filter = value;
            Console.WriteLine($"Selected product: {value}");
        }
    }

    private void HandleOriginProductChanged(string? value)
    {
        Console.WriteLine($"Selected product: {value}");
    }

    private void DeleteFilter()
    {
        Filter = string.Empty;
    }
```
## 🤔 Expected Behavior

Selection to clear in the combobox

## 😯 Current Behavior

selection is cleared, and reverted back

## 💁 Possible Solution
during the refactor, the `SetParameterAsync` was changed to only set `Value` if the value is not null. this used to have a null coalesce to set it to an empty string. why was this changed? 
[by the looks of it, this makes it so that upon clearing the `SelectedOption` it never sets the `Value` correct because `value` is null](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/List/FluentCombobox.razor.cs#L114-L119)

## 🔦 Context
we were adding a clear button to our combobox' that are used in our grid filters. something i reported to the webcomponents too, but until they respond, we wanted to implement something ourselves. 
(https://github.com/microsoft/fluentui/issues/31838)

## 🌍 Your Environment

* OS & Device: Windows 10, PC
* Browser: Chromium & Firefox
* .NET and Fluent UI Blazor library Version: 8.0.2 and 4.8.1

**Comment by vnbaaij** [comment]
So your PR puts back the string.Empty? Maybe it is easier to just create the PR and then we can asses and test if everything still works from our side. If you've found the null coalese is not an issue, then great!

**Comment by vnbaaij** [comment]
@joriverm could you try to get the PR in asap, please. 

We are preparing a new release at the moment and it would be great if we can get this in. Otherwise it will need to wait till next patch release.

**Comment by joriverm** [comment]
> @joriverm could you try to get the PR in asap, please.
> 
> We are preparing a new release at the moment and it would be great if we can get this in. Otherwise it will need to wait till next patch release.

im currently out of the office for the day. i will be making a PR tomorrow, which puts the null coalesce back & removes the check if value is not null (because the null coalesce makes it useless).
I will be in sprint review meeting too, but will keep an eye open for this one so a version can be made!
