### ISSUE TITLE
FluentCombobox onchange function sending OptionText

### ISSUE THREAD

**Issue by EmirLogas** [microsoft/fluentui-blazor#2315]
# 🐛 Bug Report
When I make any change in FluentCombobox, "ChangeEventArgs e" fills with the text that appears, not the value behind the Combobox.

## 💻 Repro or Code Sample

```
<FluentGridItem md="3" xs="12">
    <FluentCombobox Placeholder="Country"
                    Autocomplete="ComboboxAutocomplete.Both"
                    TOption="Country"
                    Items="@countries"
                    OptionText="@(p => p.CountryName)"
                    OptionValue="@(p => p.CountryCode)"
                    @bind-Value="@merchant.CountryCode"
                    @onchange="OnCountryChanged">
        <FluentIcon Value="@(new Icons.Regular.Size16.Certificate())" Slot="start" Color="Color.Neutral" />
    </FluentCombobox>
</FluentGridItem>
```

```
private void OnCountryChanged(ChangeEventArgs e)
{
    var selectedCountryCode = e.Value?.ToString();
    if (!string.IsNullOrEmpty(selectedCountryCode))
    {
        merchant.CountryCode = selectedCountryCode;
        states = StaticDatas.StateList
            .Where(s => s.CountryCode == merchant.CountryCode)
            .OrderBy(s => s.StateName);
    }
    else
    {
        states = Enumerable.Empty<State>();
    }

    StateHasChanged();
}
```

## 🤔 Expected Behavior

The Value of the selected element must be sent.

## 😯 Current Behavior

Text value of the selected element is sent.
![image](https://github.com/microsoft/fluentui-blazor/assets/76751818/d6f55dfd-35f7-4e2d-8e48-ffd3e6dff3c5)
This should be MT instead of Malta, right?
Thank you for your help.

**Comment by vnbaaij** [comment]
The code you supplied is **not** something we can just run/test quickly. Please be considerate of the time and effort we need to put into looking at this and supply a **working minimal reproduction!**!!

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

Help us to help you. Thanks.

**Comment by vnbaaij** [comment]
I suggest you look at https://www.fluentui-blazor.net/Combobox#optiontemplate

With a combobox the option value is not guaranteed to be set. A user can change the contents of the text box and then there is no corresponding value anymore. We then return the value of the text box. 

Closing this as we can't change this behavior.

**Comment by EmirLogas** [comment]
Okay, I got it. You can close.
