### ISSUE TITLE
feat: add theme color changer to hello users to change preset themes

### ISSUE THREAD

**Issue by fasteddys** [microsoft/fluentui-blazor#2319]
# 🙋 Feature Request

In the current web applications, users like to customize the colors either for readability or in some cases because of challenges they prefer high contrast settings. It would be great if you could provide a component under the settings COG so that the user can select and set their themes to change their primary colors and their text colors.

## 🤔 Expected Behavior

If you look at any of the current standard web applications they have a cog and settings that allows the user to select and then a tab opens up or a modal/drawer on the right so that the user can select the colors for their theme, preciwed and save.

Also in the _second help video it shows that authorization has been ported over but that sample is missing on the website._

## 😯 Current Behavior

This is missing.

**Comment by vnbaaij** [comment]
Sorry, this makes no sense to me at all. Closing...
