### ISSUE TITLE
fix: OnResize event callback of MultiSplitter

### ISSUE THREAD

**Issue by emetrix** [microsoft/fluentui-blazor#2321]
# 🐛 Bug Report

It seems the OnResize event callback of MultiSplitter is called each time a mouse click on the "resize bar" is performed - even if the panes / "resize bar" is not moved / resized at all.

## 💻 Repro or Code Sample

It can easily be reproduced on the demo site https://www.fluentui-blazor.net/MultiSplitter by performing a click on the MultiSplitter bar without moving the mouse / bar and check the console log at the right side of the page 

## 🤔 Expected Behavior

The OnResize event should only be raised when the bar is really moved / resized.

## 😯 Current Behavior

The OnResize event is raised even when the bar / panes are not resized.

## 🔦 Context

In my case I have to handle the panes' sizes in pixels not in percentages. This works in general but due to the described behaviour the resize event where I have to recalculate the percentage size to pixels makes the pane resize even if it shouldn't.
I think it's based by the transformation from percentage to pixels which is not needed if the position of the "resize bar" has not been changed.

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Browser: Microsoft Edge
* .NET and Fluent UI Blazor library Version: 8.0.3 and 4.8.0

**Comment by dvoituron** [comment]
I don't know if it's possible to change this information which is computed by a JavaScript method and sent to the C# code, with a new value. Even if it is a percentage, the result may be different. And so, technically, it's a resizing.

![peek_2](https://github.com/microsoft/fluentui-blazor/assets/8350694/3261a903-614b-4857-afa0-a19468468368)

Perhaps you could check, in C#, whether the returned value differs from the one expected for your project?

**Comment by vnbaaij** [comment]
Maybe we can detect how big the change is and if it is less than 1% or less than x pixels, we ignore the action?

**Comment by dvoituron** [comment]
> Maybe we can detect how big the change is and if it is less than 1% or less than x pixels, we ignore the action?

We could add a "Precision" property to specify the number of percentages required to trigger this event. But this percentage may differ from one screen to another (depending on resolution).

**Comment by dvoituron** [comment]
I think I can find a solution to detect the movement of the "mouse" so as not to trigger the event in this case. Let me have a look.

**Comment by dvoituron** [comment]
Will be fixed, via #2333
