### ISSUE TITLE
fix: Vertical overflow tab component example in demo site glitching

### ISSUE THREAD

**Issue by thebarrettlo** [microsoft/fluentui-blazor#2335]
# 🐛 Bug Report

## 💻 Repro or Code Sample

https://www.fluentui-blazor.net/Tabs

https://github.com/microsoft/fluentui-blazor/assets/36118918/8c0145ca-b3b4-4a1c-b5fe-826923c3a863

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Browser: Microsoft Edge

**Comment by vnbaaij** [comment]
Hotfix pushed to demo environment
