### ISSUE TITLE
FluentNumberField with nullable value return validation error

### ISSUE THREAD

**Issue by AlexNek** [microsoft/fluentui-blazor#2337]
# 🐛 Bug Report

I have in EditForm
```
<DataAnnotationsValidator/>
<FluentValidationSummary class="text-danger" role="alert"/>
...
<FluentNumberField Name="Input.Abc" @bind-Value="Input.Abc" Step=0.5 Label="text" />
...
```
```csharp
 private sealed class InputModel
 {
     public double? Abc { get; set; }
 }
```

## 💻 Repro or Code Sample

EidtForm with FluentNumberField and nullable value

## 🤔 Expected Behavior

Nothing to type and after pressing Submit button, I expected
No validation error for nullable types without attributes

User must see empty field and it is valid situation

## 😯 Current Behavior

Nothing to type and after pressing Submit button, I see
The value '' is not valid for 'Abc'.

The same error if I create my own validation attribute with Valid = true

## 🔦 Context
Edit form with optional numeric values
## 🌍 Your Environment

Windows, Google Chrome
.NET8 and Fluent UI Blazor library Version 4.*

**Comment by vnbaaij** [comment]
Hi,

The web component underlying our FluentNumberField is horribly broken. We can't fix that on our side. 

I would advise you to not use that component regardless of if it works or not. See also my comment in #1127, and other issues around it in #1345 and others.

**Comment by vnbaaij** [comment]
Your issue is already mention in #1345 as well, so closing this one as it is a duplicate

**Comment by vnbaaij** [comment]
Will do that. For the next release it will be:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/21c3bb40-81ee-450a-ae44-76e9ee93eaed)
