### ISSUE TITLE
DataGrid/PropertyColumn use DisplayAttribute value for enum but doesn't support Localization

### ISSUE THREAD

**Issue by JarJasAskom** [microsoft/fluentui-blazor#2344]
In file src\Core\Extensions\EnumExtensions.cs there is a function GetDisplayName. Line 

        return displayAttribute?.Name ?? enumValue.ToString();

should be changed to 

        return displayAttribute?.GetName() ?? enumValue.ToString();

**Comment by vnbaaij** [comment]
Good catch! Will change.
