### ISSUE TITLE
FluentToastProvider  ShowCloseButton not implemented

### ISSUE THREAD

**Issue by franklupo** [microsoft/fluentui-blazor#2346]
Hi,
I needed to hide the FluentToast button close and I found this.

https://github.com/microsoft/fluentui-blazor/blob/41f8671c55d3ab38216ab57cd8dd9a8080c85044/src/Core/Components/Toast/FluentToastProvider.razor.cs#L43

But it is not used anywhere, why?

**Comment by vnbaaij** [comment]
It seems it has been there from the beginning but it is indeed not used anywhere. I looked at the (internal) Toast design document again and it also should not be there. 

From that doc:
# Toast overview
Toasts, referred to as “notifications” in the UI, keep customers informed by briefly:
- Confirming an action they took.
- Informing the customer about a timely event.
- Communicating the status of a process someone initiated.

The information in a toast is useful and relevant but never critical. 

Based on that info and other guidance in the docs we implemented this as follows:

A Toast always needs to have the following call-to-action (dependent on the type of toast:
- Confirmation Toast: Link; optional. If you do not supply an action to the `ToastService` call it defaults to dismiss
- Communication Toast: required; Must be dismiss or timestap
- Progress Toast: required; Must be dismiss or link

I'll mark the parameter as obsolete so we can remove it later.
