### ISSUE TITLE
fix: Initial theme breaks after update to v4.9.0

### ISSUE THREAD

**Issue by bpsc-wkubis** [microsoft/fluentui-blazor#2349]
# 🐛 Bug Report

I bumped my app to v.4.9.0 and now my theme's acting weird. I'm using theme.js to set up my default theme (accent color, density, etc.), same as Aspire project. But here's the thing: when my app loads, my custom styles show up for a sec and then they get replaced by the default styles. I found that this behavior was introduced by https://github.com/microsoft/fluentui-blazor/commit/544a9c4fb7ba5363794b9ed6e7c45e6fca0745e6, so when i use any of design tokens it's importing new file with suffix 4.9.0 which i overwriting theme.

## 💻 Repro or Code Sample
https://github.com/bpsc-wkubis/fluentui-v4.9.0-breaks-theme

## 🤔 Expected Behavior
Default theme is applied and not overwritten when using any of DesignTokens

## 😯 Current Behavior
Default theme is overwritten when using any of DesignTokens, in repro i used Density. 

## 🔦 Context
Set default theme for app

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version 8.0.6 and 4.9.0

**Comment by liaan-mynhardt** [comment]
I was just researching this same issue, as soon as you use design tokens it changes the theme back to defaults

**Comment by vnbaaij** [comment]
I'm undoing the add suffix for the next release (4.9.1).

**Comment by vnbaaij** [comment]
Confirmed this is fixed with reverting add of suffix. Will be in 4.9.1
