### ISSUE TITLE
fix: Column options are not aligned correctly in a DataGrid Column

### ISSUE THREAD

**Issue by joriverm** [microsoft/fluentui-blazor#2350]
# 🐛 Bug Report
My Team just reported that when a column in a datagrid has a align set to `Align.End`, the column options is aligned on the right of the grid, not just the column.

## 💻 Repro or Code Sample

I opened the demo site for grids, and in the typical example i changed the `country name` column to the following (aka added `Align=@Align.End`

```
    <PropertyColumn Align=@Align.End Property="@(c => c.Name)" Sortable="true" Filtered="!string.IsNullOrWhiteSpace(nameFilter)" Tooltip="true" Title="Name of the country">
        <ColumnOptions>
            <div class="search-box">
                <FluentSearch Autofocus=true @bind-Value=nameFilter @oninput="HandleCountryFilter" @bind-Value:after="HandleClear" Placeholder="Country name..." Style="width: 100%;" Label="Filter" />
            </div>
        </ColumnOptions>
    </PropertyColumn>
```

## 🤔 Expected Behavior
i'd expect the column to be like this : 
![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/24259b29-4984-45a1-b8bc-caf60d6be807)

## 😯 Current Behavior

the column options are displayed way on the right of the grid
![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/782b1922-58d1-4960-8c8f-4469fc47146f)

## 💁 Possible Solution

i looked around the css, and it seems the column options have position set to absolute, and [when align is set to end, it adds a CSS class](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/DataGrid/FluentDataGrid.razor.cs#L609) which [gives it a right of 0.2rem](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/DataGrid/FluentDataGrid.razor.css#L36-L39).

this makes it render all the way on the right of the grid.
deleting that makes it better, but its still scouched up to the right a bit to much (?)

![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/340944b1-5f58-40c7-be6a-e8223ab0d6fc)

im not sure what the correct fix is here, but i can make a PR with this possible solution if requested :)

## 🔦 Context
We are kinda uneffected as we have currently removed the `right:0.2rem` by overwriting it in app.css

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Chromium, Firefox
* .NET and Fluent UI Blazor library Version: 8.0.2 and 4.9.0

**Comment by vnbaaij** [comment]
Good find. Of course, I only tested it with the Totals column which is already all the way to the right...

I'm changing the `right: 0.2rem;` to `margin-right: 0.6rem;` which then gives:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/821612f1-c41b-46e5-b864-c6767fdcf9e2)
