### ISSUE TITLE
docs: add How to use parameter Field of FluentTextField component

### ISSUE THREAD

**Issue by JarJasAskom** [microsoft/fluentui-blazor#2352]
# 🙋 Documentation Request

Page https://www.fluentui-blazor.net/TextField#fluenttextfield-class_properties contains info that Field parameter exists but there is no info how to use it.

Why I would like to use it.

My model contains property

        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true, ErrorMessageResourceName = "Validation_FieldRequired", ErrorMessageResourceType = typeof(Localization.LocalizationRes))]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\d{18}$", ErrorMessageResourceName = "Validation_FieldMustHave18Digits", ErrorMessageResourceType = typeof(Localization.LocalizationRes))]
        [Display(Name = "DanePpOgolne_KodPp", ResourceType = typeof(Localization.LocalizationRes))]
        public string KodPp { get; set; } = default!;

When I bind FluentTextField to the property validation work correctly. 

When I use FluentTextField  inside my own component validation does not work because I'm providing only value of property KodPp not the property itself.

It seems that giving parameter of type FieldIdentifier  to my component and then using parameter Field in FluentTextField  could solve the problem.

**Comment by vnbaaij** [comment]
This is what is happening in the `FluentInputBase` class (so not just for `FluentTextField` but for all base derivedcomponents) in abbreviated form:

```
  public override Task SetParametersAsync(ParameterView parameters)
  {
      parameters.SetParameterProperties(this);

      if (!_hasInitializedParameters)
      {
          // This is the first run
          // Could put this logic in OnInit, but its nice to avoid forcing people who override OnInit to call base.OnInit()

          if (Field is not null)
          {
              FieldIdentifier = (FieldIdentifier)Field;
          }
          else if (ValueExpression is not null)
          {
              FieldIdentifier = FieldIdentifier.Create(ValueExpression);
          }
          else if (ValueChanged.HasDelegate)
          {
              FieldIdentifier = FieldIdentifier.Create(() => Value);
          }
         :
         :
```   
So if you set `Field`, the `FieldIdentifier` will be set to that. It is in fact the only thing where Field is used for. Not sure what more would need to be documented on that. Standard Blazor documentation applies.
