### ISSUE TITLE
FluentTextField AutoComplete Off doesn't work

### ISSUE THREAD

**Issue by Rocky-25** [microsoft/fluentui-blazor#2355]
# 🐛 Bug Report
When using FluentTextField and setting AutoComplete to off this doesn't work, it isn't applied in the underlying html.

## 💻 Repro or Code Sample
<FluentTextField @bind-Value=Name Label="Name" Id="Name" AutoComplete="off"></FluentTextField>

![image](https://github.com/microsoft/fluentui-blazor/assets/52032850/988cf6d2-f9e2-46ec-abb2-957c2e104375)

## 🤔 Expected Behavior

autocomplete should be set in the html something like:
![image](https://github.com/microsoft/fluentui-blazor/assets/52032850/3dedd091-385e-4b7a-bae9-749a00e959a1)

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser Google Chrome
* .NET and Fluent UI Blazor library Version 4.9.0

**Comment by vnbaaij** [comment]
Yes, it is being applied.  The autocomplete attribute in the shadow dom is being set by a script called from the `FluentTextField` `OnAfterRenderAsync` method. You will not see that represented in the dev tools, 
Same goes for the inputmode

Example when Autocomplete parameter not set:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/1e7c5c7f-1fd3-4977-9e9a-32b7ea8aadb8)

Example when Autocomplete parameter not set: (no suggestion popup shown on focus)
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/642b6c39-605e-426f-a2bc-427acd0685c4)

Have you verified it to not work? If so, please post ready-to-run reproduction code, not just one line that we can't run.

**Comment by Rocky-25** [comment]
It was failing because I had dots in the id so the javascript would fail to find the element. Changed the id to remove the dots and it works fine. Please close.
