### ISSUE TITLE
Vertical slider range direction is reversed

### ISSUE THREAD

**Issue by ssnseawolf** [microsoft/fluentui-blazor#2357]
# 🐛 Bug Report

Filing this as a bug, though it may be intended. The vertical slider range direction is reversed.

## 💻 Repro or Code Sample

1. Examine [demo site](https://www.fluentui-blazor.net/Slider) vertical slider.
2. Observe that the range direction goes from top to bottom.

## 🤔 Expected Behavior

The vertical slider range direction should increase from bottom to top.

Vertical slider direction should observe general guidance. See [linked](https://learn.microsoft.com/en-us/windows/apps/design/controls/slider#range-direction) guidance from Fluent site for Windows:

_For vertical slider, put the largest value at the top of the slider, regardless of reading direction. For example, for a volume slider, always put the maximum volume setting at the top of the slider._ 

## 😯 Current Behavior

The slider range direction increases from top to bottom.

## 💁 Possible Solution

Consider:
* Make the default vertical slider range increase from bottom to top.
OR
* Add `Orientation.VerticalBottomToTop` option for `FluentSlider.Orientation`.

## 🔦 Context

This issue confuses users, as the traditional vertical slider range direction is bottom-to-top. If it is not possible to make the default slider range direction go from bottom to top, perhaps consider adding an additional `Orientation` to allow for bottom-to-top viewing.

## 🌍 Your Environment

* OS & Device: Windows 11 22631.3880. 
* Browser Firefox 129.0
* .NET 8.0.7. 
* FluentUI 4.9.1

**Comment by vnbaaij** [comment]
Unfortunately this behavior comes from the underlying web component and can't be changed by us.
The FAST/Fluent UI WC team is busy with the next version and deprecating the current one so we won't see a fix from them for this. I will check how it is done in the next version.

Closing this as we can't change anything currently.

**Comment by vnbaaij** [comment]
Next version is handeling this correctly:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/98505bcd-07fc-45c9-b529-59ffd7b253a8)
