### ISSUE TITLE
fix: Columns not vertically aligned in FluentUI DataGrids

### ISSUE THREAD

**Issue by BartvDijk** [microsoft/fluentui-blazor#2358]
# 🐛 Bug Report

In the Fluent UI DataGrid i'm trying to allow for the dynamic adding/removing of columns. When doing so, the columns are no longer vertically aligned: individual cells are replaced chaotically. I notice the same behaviour in the FluentUI-blazor.net example, when using MS Edge: [https://www.fluentui-blazor.net/DataGrid#typicalusage](url)
(Under **Typical Usage** -> click on chevron-down in the column header -> hit the refresh button)

## 💻 Repro or Code Sample

From the link:
[https://www.fluentui-blazor.net/DataGrid#typicalusage](url)

![image](https://github.com/microsoft/fluentui-blazor/assets/145265555/769f2bd6-6701-4bf9-8a27-36897a158ee6)

Under **Typical Usage** -> click on chevron-down in the column header -> hit the refresh button

## 🤔 Expected Behavior

Aligned columns, headers and it's datacells with the same horizon positioning and width

## 😯 Current Behavior

cells are no longer placed directly beneath it's headers, cells are also not aligned in respect to each other

## 🔦 Context

I'm building a columnpicker to use in conjunction with the fluent ui datagrid. Adding or removing columns results in the aforementioned bug.

## 🌍 Your Environment

Windows 11 PRO, Microsoft Edge

* OS & Device: [Windows 11] on [PC]
* Browser [Microsoft Edge]
* .NET and Fluent UI Blazor library Version [8.0.6 and 4.9.1]

**Comment by Jan-Henk-Edens** [comment]
+1

**Comment by vnbaaij** [comment]
There are 2 different things happening here:
1) The effect you are seeing om the demo site
2) The effect you are seeing in you own code when adding/removing columns. 

1) Occasionally the initial set `GridTemplateColumns` value gets mixed up when there are multiple resizable grids on one page. I'll try to make that process more resilient.

2) This one I can't investigate as there is no reproduction code provided (yet). What I suspect is happening is that you set `GridTemplateColumns` parameter when the initial grid is created. The grid's JavaScript reads this initial value on initialization and restores it when the reset method is executed. When adding/removing columns, the GridTemplateColumns may or may not be updated but the end result is the initially stored value does not correspond to the current grid setup. If you then reset, the value set will not represent the actual  situation and rendering will go do its own thing.

I'm not really sure how to solve this. Would reset also remove added columns or add removed columns again? If not, what to reset to then?

**Comment by f4n0** [comment]
+1

**Comment by vnbaaij** [comment]
Guys come on. What are you all '+1'-ing to? 

That this happens on the demo site? I already confirmed that in my previous reply.
That this happens in your own code? Then give us reproduction code please (as also requested in my previous reply!) And also answer the questions I asked in my previous reply

The +1 are not really helping at all.

**Comment by BartvDijk** [comment]
Thanks for your quick reponse. I noticed the reset-button on the demo-site, figured i could use whatever handle it had, to fix my own issues. When that didn't work as expected, i assumed it might be the same underlying issue. Sorry, didn't mean to draw a spotlight on it.

Concerning `GridTemplateColumns`, I did try using this parameter, to force a column-width based on the amount of columns. Either that or the `Width`-parameter on the Column. Setting it, or not, did not make a difference regarding the vertical alignment.

What follows is reproduction code, i cleaned it as much as possible.


Grid.razor
```
@typeparam TGridItem

<div class="entity-grid p-2 pb-0">
    <CascadingValue Value="@this" IsFixed="true">
        <CascadingValue Value="@_filterManager" IsFixed="true">
            <CascadingValue Value="@DataManager" IsFixed="true">
                <GridHeaderToolBar Icon="@Icon"
                                   T="TGridItem"
                                   GridTitle="@Title"
                                   Add="_add"
                                   RefreshColumns="RefreshData"
                                   UseColumnPicker="@UseColumnPicker"
                                   EntityGridHeaderManager="@EntityGridHeaderToolBarManager"
                                   HeaderContent="@HeaderContent"
                                   ColumnManager="EntityGridColumnManager" />

                <FluentDataGrid TGridItem="@TGridItem" ItemsProvider="@DataManager.LoadVirtualizeItems"
                                virtualize="@Virtualize" Pagination="@PaginationState"
                                NoTabbing="@NoTabbing"
                                ShowHover="@ShowHover"
                                GenerateHeader="@GenerateHeader"
                                OnRowClick="@(row => Click(row.Item))"
                                OnRowDoubleClick="@(row => DoubleClick(row.Item))"
                                @ref="@_gridReference">
                    <ChildContent>
                        @RenderColumns
                    </ChildContent>
                    <EmptyContent>
                        @GetTranslation("No Data Found")
                    </EmptyContent>
                    <LoadingContent>
                        <div class="h-100">
                            <FluentStack Orientation="Orientation.Vertical"
                                         HorizontalAlignment="HorizontalAlignment.Center">
                                Loading...<br />
                                <FluentProgress Width="240px" />
                            </FluentStack>
                        </div>
                    </LoadingContent>
                </FluentDataGrid>
                @if (PaginationState != null)
                {
                    <Paginator State="@PaginationState" />
                }
            </CascadingValue>
        </CascadingValue>
    </CascadingValue>
</div>

@code
{
    private RenderFragment RenderColumns => __builder =>
    {
        if (EntityGridColumnManager == null)
        {
            return;
        }

        @foreach (var column in EntityGridColumnManager.GetColumns())
        {
            <PropertyColumn Title="@column.DisplayName" Property="@column.Property"
                            Filtered="@_filterManager.HasBeenFilterdOn(column)"
                            IsDefaultSortColumn="@column.IsDefaultSortColumn"
                            InitialSortDirection="@column.InitialSortDirection"
                            Sortable="@column.Sortable">
                <ColumnOptions>
                    <div class="filter">
                        <CascadingValue Value="@column" IsFixed="true">

                            <DefaultFilter ColumnInfo="@column" />

                        </CascadingValue>
                    </div>
                </ColumnOptions>
            </PropertyColumn>


        }
    };
}
```
Grid.razor.cs (snippet)

 ```
   #region Functions

    public async Task RefreshData()
    {
        await DataManager.RefreshData(default);
        await RefreshGrid();
    }

    public Task RefreshGrid()
        => _gridReference == null ? Task.CompletedTask : _gridReference!.RefreshDataAsync();

    public void SetLoadingState(bool loadingState)
        => _gridReference?.SetLoadingState(loadingState);
    
    #endregion


    #region Helper

    private string GetTranslation(string translation, bool isMultiple = false)
    {
        return _translate?.GetTranslation(translation, isMultiple) ?? translation;
    }

    #endregion
}
```

```
public IEnumerable<EntityGridColumn<TGridItem>> GetColumns(bool getAll = false)
{
    if (!_columns.Any())
        foreach (var column in typeof(TGridItem).GetProperties().Where(x =>
                     x.GetCustomAttributes(typeof(ExcludeFromMappingAttribute), true).Length == 0 &&
                     x.GetCustomAttributes(typeof(NotMappedAttribute), true).Length == 0))
        {
            if (!IsSimpleType(column.PropertyType))
                continue;

            var parameterExpression = Expression.Parameter(typeof(TGridItem));

            var propertyExpression = Expression.Property(parameterExpression, column);

            var convertExpression = Expression.Convert(propertyExpression, typeof(object));

            var lambdaExpression =
                Expression.Lambda<Func<TGridItem, object>>(convertExpression, parameterExpression);

            AddColumn(lambdaExpression, column,
                DefaultValueFormatterHelper.DefaultFormatter(column.PropertyType)
            );
        }

    if (!getAll & _customLayout?.Count > 0)
        return GetSpecificLayout(_customLayout);


    if (!getAll && _defaultLayout?.Count > 0)
        return GetSpecificLayout(_defaultLayout);

    return _columns;
}

public IEnumerable<EntityGridColumn<TGridItem>> GetSpecificLayout(List<string> specificLayout)
{
    List<EntityGridColumn<TGridItem>> specificLayoutColumns = [];

    foreach (var column in specificLayout
                 .Select(specificLayoutColumn => _columns.FirstOrDefault(x => x.PropertyName == specificLayoutColumn))
                 .OfType<EntityGridColumn<TGridItem>>().Where(column => !specificLayoutColumns.Contains(column)))
    {
        specificLayoutColumns.Add(column);
    }

    return specificLayoutColumns;

}

public void UseCustomLayout(List<string> layout)
{
    _customLayout = layout;
}

public void UseDefaultLayout(List<string> layout)
{
    _defaultLayout = layout;
}

#endregion

#region Helper

private static bool IsSimpleType(Type? type)
{
    if (type == null)
        return false;

    var typeInfo = type.GetTypeInfo();
    if (typeInfo.IsGenericType && typeInfo.GetGenericTypeDefinition() == typeof(Nullable<>))
    {
        return IsSimpleType(typeInfo.GetGenericArguments()[0]);
    }

    return type.IsPrimitive || type.IsEnum || type == typeof(string) || type == typeof(decimal) ||
           type == typeof(double) ||
           type == typeof(TimeOnly) ||
           type == typeof(TimeSpan) ||
           type == typeof(DateOnly) ||
           type == typeof(DateTime) ||
           type == typeof(DateTimeOffset) || type == typeof(Guid);
}

#endregion
```

I'm probably missing stuff you require, if so, please let me know. I'm still rather new at this, trying my hand on some more advanced stuff. Thanks in advance.

**Comment by vnbaaij** [comment]
Hi @BartvDijk, Bart, 

Can you post a zip of a project that I can run locally? Cutting, pasting and then guessing what's missing isn't really efficient

**Comment by BartvDijk** [comment]
Can't share the project sadly. 'Fixed' the issue by forcing a re-render of the table.
