### ISSUE TITLE
feat: add Overlay to Splash screen shown by ShowSplashScreenAsync

### ISSUE THREAD

**Issue by JarJasAskom** [microsoft/fluentui-blazor#2367]
Function ShowSplashScreenAsync always set 'Modal = false' and splash screen does not have overlay (obscured area around the dialog.)

    public async Task<IDialogReference> ShowSplashScreenAsync(Type component, object receiver, Func<DialogResult, Task> callback, DialogParameters<SplashScreenContent> parameters)
    {
        DialogParameters dialogParameters = new()
        {
            DialogType = DialogType.SplashScreen,
            Alignment = HorizontalAlignment.Center,
            Modal = false,
            PreventDismissOnOverlayClick = parameters.PreventDismissOnOverlayClick,
            ShowDismiss = false,
            ShowTitle = false,
            PrimaryAction = null,
            SecondaryAction = null,
            Width = parameters.Width ?? "600px",
            Height = parameters.Height ?? "370px",
            DialogBodyStyle = "width: 100%; height: 100%; margin: 0px;",
            AriaLabel = $"{parameters.Content.Title} splashscreen",
            OnDialogResult = EventCallback.Factory.Create(receiver, callback),
        };

        return await ShowDialogAsync(component, parameters.Content, dialogParameters);
    }

ShowSplashScreen function does set Modal = true but there is no info how to close its dialog programmatically.

Scenario is as follows:

        IDialogReference mDialog = await mDialogService.ShowSplashScreenAsync(splashScreenContent);

        ValueResult<Unit> result = await mModelUnitOfWork.SaveChangesAsync(mCancellationTokenSource.Token);

        await mDialog.CloseAsync();

**Comment by vnbaaij** [comment]
It works as any other of our dialog components. Closing should work the same way.
I'll look at the modal part

**Comment by vnbaaij** [comment]
I'm changing the `DialogService.ShowSplashScreen...` methods to use the Modal parameter. 

Not sure what you want to achieve with the Close part. A SplashScreen is normally not closable by user interaction. However, by playing with `Modal` and  `PreventDismissOnOverlayClick` you can get the screen to be dismissed on clicking on the background.

**Comment by JarJasAskom** [comment]
> changing the DialogService.ShowSplashScreen... methods to use the Modal parameter.

Thank you.

> Not sure what you want to achieve with the Close part. A SplashScreen is normally not closable by user interaction. However, by playing with Modal and PreventDismissOnOverlayClick you can get the screen to be dismissed on clicking on the background.

What I wanted to achieve was to close dialog that was showed with ShowDialog. There are many examples of using ShowDialogAsync (and then IDialogReference.CloseAsync) but no single one of using ShowDialog. 

Checking this again I've found FluentDialogProvider.DismissAll function. Maybe it is what shoud be used.

**Comment by JarJasAskom** [comment]
I've installed update 4.9.3.  

Function ShowSplashScreenAsync shows splash screen always without overlay. Setting Modal parameter to true or false in DialogParameters<SplashScreenContent> has no effect.


Documention of SplashScreen has two demos in section "Default splash screen". 

Button "Open splash screen" uses ShowSplashScreen and splash screen has overlay. 

Button "Open splash screen (async)" uses ShowSplashScreenAsync and splash screen has no overlay. 

Click handler OpenSplashDefaultAsync of the button "Open splash screen (async)"  demonstrates the scenario I would like to implement: 

- show splash screen with overlay visible, 
- do work, 
- update splash screen, 
- do work, 
- close splash screen programmatically from the code.

**Comment by vnbaaij** [comment]
See remark in #2447
