### ISSUE TITLE
FluentTimePicker Culture

### ISSUE THREAD

**Issue by Nicolas3347** [microsoft/fluentui-blazor#2370]
Would you be able to Add the property Culture to the FluentTimePicker. Not everybody understand or have the concept of AM, PM.
If you choose a culture from France fr-FR it should display from 0 to 23:59.

Thank you very much

**Comment by vnbaaij** [comment]
We use the standard browser support for this. If that one supports culture, we can use it. But I don't think there is.

**Comment by Nicolas3347** [comment]
> We use the standard browser support for this. If that one supports culture, we can use it. But I don't think there is.

It should be the same as the **FluentDatePicker**  or Calendar which has Culture?

**Comment by vnbaaij** [comment]
No, it is not the same. DatePicker and calendar are custom created components. Where as the time picker is a browser supplied control

**Comment by Nicolas3347** [comment]
> No, it is not the same. DatePicker and calendar are custom created components. Where as the time picker is a browser supplied control

Can we create a custom component for this or even one that would have both Date and Time Picker within the same controls
![image](https://github.com/user-attachments/assets/20dbd37c-1774-41de-9c59-be30e1308d4e)

**Comment by vnbaaij** [comment]
No, that is not something on our list of things to do

**Comment by vnbaaij** [comment]
Please see https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#time_strings for what the time input supports. The AM/PM parts comes from the system the site/app is running on. We can't influence that.

Closing this as it is not actionable from our side.

**Comment by iftiharh** [comment]
Hi Nicolas3347.How did you solve this problem?
