### ISSUE TITLE
rfc: add FromId and ToId to FluentSortableList

### ISSUE THREAD

**Issue by RReventlov** [microsoft/fluentui-blazor#2376]
# 💬 RFC

The current implementation of `FluentSortableListEventArgs` does not allow one to determine from which list onto which list the item was dragged and then dropped. By providing two additional properties, `FromId` and `ToId` the developer would be able to determine which lists were involved.

## 🔦 Context

I am building a todo application and sort the items into buckets (think of kanban columns). I want a view with all the buckets and the ability to drag and drop one item from one list to the next. I have considered using the `FluentDragContainer`. I decided against it because I would have to re-implement the nice visuals of `FluentSortableList` on my own and because the underlying SortableJS library provides the means to solve my problem.

## 💻 Examples

I have forked the fluentui-blazor project and implemented changes that accomplishes what I want. You can view it [here](https://github.com/RReventlov/fluentui-blazor). I also changed the code in the demo page for the `FluentSortableList`-Component to test my changes and provide a demonstration.

https://github.com/user-attachments/assets/c893d1e0-6f93-4a12-ae12-8e558949fd46

I can create a pull request but I don't know if it would be okay to do that out of the blue.

**Comment by dvoituron** [comment]
Interesting :-)
Yes, I think this could be an interesting addition for developers.

- I would name the properties `FromListId` and `ToListId` to be clearer. 
- In the Demo example, I wouldn't modify the whole example, which seems simple enough at the moment, but I would only add traces in the right console to display the Indexes and these new IDs.

A unit test will also be needed to validate this new functionality (although the current tests are not yet complete 😊 ).

**Comment by RReventlov** [comment]
^^
I can modify my branch accordingly. I have a question regarding the unit test, what exactly does the test have to test for? As I understand it I need to test that the Id gets added to the generated html.

After I modified it do I create a pull request?

**Comment by dvoituron** [comment]
> I can modify my branch accordingly. I have a question regarding the unit test, what exactly does the test have to test for?
You can create a Unit Test to (1) verify that the IDs are added and (2) calling `OnUpdateJS` (simulating the JS call) the event will be fired.

And yes, you can create a PR (set a short title and a complete description including a screenshot or a [GIF](https://apps.microsoft.com/store/detail/XP8CD3D3Q50MS2) to explain correctly the new features).
