### ISSUE TITLE
FluentDataGrid - column resizing with additional unwanted effects

### ISSUE THREAD

**Issue by gryzorr** [microsoft/fluentui-blazor#2381]
# 🐛 Bug Report

When resizing FluentDataGrid column at the beginning width of current column gets smaller and all previous one shrinks also a little.

## 💻 Repro or Code Sample

See video and attachment.

## 🤔 Expected Behavior

When starting resize operation previous columns and current one should not shrink.

## 😯 Current Behavior

Each time user starts resize column (very little move to right to start enlarge column) all columns to the left shrinks causing that current column gets smaller on start (resize cursor doesn't match column separator). When there is more columns and user repeats operation for more than one column sometimes prevoius one need correction and so on.

## 💁 Possible Solution

beyond my capabilities :-)

## 🔦 Context

Minor problem (at the moment we use components only for internal app) but nice to have a solution.

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Microsoft Edge, Google Chrome
* .NET and Fluent UI Blazor library Version: 4.9.1

https://github.com/user-attachments/assets/873ed6b8-c984-4a72-bf3e-353aff7b78a9

**Comment by gryzorr** [comment]
And ofcourse example code.
[BlazorAppTest.zip](https://github.com/user-attachments/files/16236030/BlazorAppTest.zip)

**Comment by michaelc06** [comment]
Can confirm noticing the same issues. Repeatable on https://www.fluentui-blazor.net/DataGrid -> Typical usage

**Comment by f4n0** [comment]
Hi, @vnbaaij !
I've tried something. by editing the js function to use % values instead of px values, it seems to work better. but I don't think that could be the real fix to the issue

**Comment by f4n0** [comment]
Well, I don't really think that this is a minimum impact issue. 
The column resizing of a table it's an essential feature, and this need to work. The end user uses this functionality practically every day!

For my app, if you resize the table multiple times, the select column will disappear!

**Comment by vnbaaij** [comment]
> Well, I don't really think that this is a minimum impact issue. The column resizing of a table it's an essential feature, and this need to work. The end user uses this functionality practically every day!

You make it sound as if it does not work at all. I'm just saying that is not the case. Resizing _is_ possible but has some visible quirks. Please understand we have a limited amount of time to work on this. There are more grave issues we need to work on.
 
> For my app, if you resize the table multiple times, the select column will disappear!

That is something we definitely need to look at. 
 
> EDIT: Why is fluentui-blazor resizing columns via grid template column? why not the width parameter?

Because the underlying web components automatically populate and use the grid template columns value

Thank you for your PR!! We will test and verify that one soon.

**Comment by thebarrettlo** [comment]
Just want to note that this same behavior is also seen when wrapping a `FluentDataGrid` in a `FluentCard`. I've confirmed by testing in the demo site that #3072 **does** fix this issue too (thanks @f4n0!), so if anyone else is experiencing the same issue, make sure you're using a version of the Fluent UI library that includes #3072 (v4.11.1 I believe).

https://github.com/user-attachments/assets/256c6a69-2b6c-487b-8b2c-02a3e6cacef5
