### ISSUE TITLE
FluentCounterBadge destroy menu offset in FluentNavGroup

### ISSUE THREAD

**Issue by AlexNek** [microsoft/fluentui-blazor#2387]
# 🐛 Bug Report
I use hierarchical menu, but as long as I want to add counter badge, my menu item shifted to the left.
![image](https://github.com/user-attachments/assets/3ad8c415-6560-4986-aea4-4d0e934cce3a)
Line 1 and 2 are identical
![image](https://github.com/user-attachments/assets/1c0fc529-07db-480c-b95b-86517e7ed17c)

## 🤔 Expected Behavior

The child element of FluentCounterBadge must not change its position.

## 😯 Current Behavior

See top

## 🌍 Your Environment

* OS & Device:  Windows
* Browser  Google Chrome/Edge
* .NET 8 and Fluent UI Blazor library Version  4.*

**Comment by vnbaaij** [comment]
This will get fixed in the next version. There was a CSS class that did not respond correctly to the CounterBadge inserting some divs into the structure:

![image](https://github.com/user-attachments/assets/91c5a8d7-e8a7-4c96-a883-8c0d9c250477)

You will however most probably need to tweak the position of the CounterBadge yourself (by using its `HorizontalPosition` and `VerticalPosition` parameters)

**Comment by AlexNek** [comment]
Thanks for the good news.

Will the FluentStack position within the submenu also be corrected?
>This will get fixed in the next version

When could we expect this?
> You will however most probably need to tweak the position of the CounterBadge yourself

I just want to test what happens with too long/truncated text. For position I can read documentation, thanks for the hint.

**Comment by dvoituron** [comment]
Since the fix has been pushed to the `dev` branch, you can use the Preview NuGet Feed.
https://github.com/microsoft/fluentui-blazor/blob/dev/docs/using-latest-daily.md

**Comment by vnbaaij** [comment]
> Thanks for the good news.
> 
> Will the FluentStack position within the submenu also be corrected?
> 
Not sure what you mean with this, With the change it renders as shown in my image

> > This will get fixed in the next version
> 
> When could we expect this?
> 

We never set exact dates for releases. Maybe next week.

**Comment by AlexNek** [comment]
Thanks for the quick reply

> Not sure what you mean with this,

```html
<FluentNavGroup ...>
    <FluentStack Orientation="Orientation.Horizontal" >
        <FluentNavLink>xxx</FluentNavLink>
    </FluentStack>
</FluentNavGroup >
```
Tested with preview, offset is corrected but menu width is shortened for this example. Note: I tried to simulate the badge. Not important to me at all.
