### ISSUE TITLE
fix: popover doesn't close in FluentOverflow

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#2390]
# 🐛 Bug Report

This is a regression in FluentPopover when updating from 4.7.2 to 4.9.1. A FluentPopover that's nested inside a FluentOverflow isn't closing when clicking on the page outside of the popup.

## 💻 Repro or Code Sample

Code here:
https://github.com/dotnet/aspire/blob/1f94dac8188391804b22a8441c979d033b7b43b9/src/Aspire.Dashboard/Components/ResourcesGridColumns/EndpointsColumnDisplay.razor#L17-L60

Notably the popover is bound to a field, `@bind-Open="_popoverVisible"`.

I changed it to a property for debugging and found clicking outside of the popup set it to false in 4.7.2:
![image](https://github.com/user-attachments/assets/8c4cd93f-b9aa-4c17-b087-086696613148)

But in 4.9.2 that changed to true:
![image](https://github.com/user-attachments/assets/bd6cebc9-f229-42f6-8bea-21c2942a79c1)

## 🤔 Expected Behavior

Clicking on the page outside of the popup will close the popup.

## 😯 Current Behavior

The popup flickers but stays visible:
![fluentpopover-open](https://github.com/user-attachments/assets/b178489b-f0b2-4d3f-9b92-54d09faa25c4)

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Chrome
* .NET 8

**Comment by vnbaaij** [comment]
Hmm, weird. The only files I see have changed between v4.7.2 and 4.9.1 are `FluentOverflow.razor.cs` and `FluentOverflow.razor.js` but there is nothing in there that could cause this.

I can fix it easily by changing some code in `FluentPopover.CloseAsync()` (but that file was changed last 103 days ago!). A new PR will be up for this soon
