### ISSUE TITLE
feat: add setting to always display the first item in FluentOverflow

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#2391]
# 🙋 Feature Request

FluentOverflow hides items if there aren't enough room to display them. However, sometimes you might want to display the first item, even if it is cutoff.

For example, given a list of names, seeing the first name, but having it cut off with an ellipsis (someone can add CSS to add ellipsis) so the user can interact with it is preferrable to just showing the overflow button and no content.

## 🤔 Expected Behavior

The first item is displayed is the space available, then the overflow button.

This is what it could look like:

![fluentoverflow-firstitem](https://github.com/user-attachments/assets/77a32797-1729-4606-a1b1-83d3c2fdc6aa)

## 😯 Current Behavior

FluentOverflow only shows the first item if there is room for it. If there isn't then just the overflow button is displayed.

This is what it looks like today:

![fluentoverflow-firstitem-current](https://github.com/user-attachments/assets/63cfe8d1-2397-435b-b5b0-a157bcdc621b)

## 💁 Possible Solution

Add a setting to FluentOverflow that controls whether the first item is always rendered inline.

**Comment by vnbaaij** [comment]
The script used to determine which items overflow actually already accounts for this... 

By supplying a `fixed` attribute to an item, it will be excluded from the calculations (we already use that internally with the AppBar). We just did not expose this in any way in the `FluentOverflowItem`. I'm creating a PR to add this as a parameter.
