### ISSUE TITLE
fix: Class property not passed down to fluent-design-system-provider

### ISSUE THREAD

**Issue by bpsc-wkubis** [microsoft/fluentui-blazor#2392]
# 🐛 Bug Report
FluentDesignSystemProvider has Class property which is not passed down to web component.

![image](https://github.com/user-attachments/assets/7f696d91-1570-4566-b77e-3023b15dc724)

## 🔦 Context

I've been using this component primarily for design token changes, but I find myself needing to apply classes directly to the container. Currently, the only options seem to be using inline styles or using the web component itself (without blazor wrapper).

**Comment by vnbaaij** [comment]
I've added Class in the commit mentioned above. Will be in next release.

Note however that the `FluentDesignSystemProvider` is not the recommended way to do token changes. It also does not expose all tokens that are being used by the web components

**Comment by bpsc-wkubis** [comment]
There's a flickering issue when applying tokens within the `OnAfterRender` event, which doesn't occur with `FluentDesignSystemProvider`. Implementing a loading state in every component that changes tokens to mitigate this issue is inconvenient and not an ideal solution.
