### ISSUE TITLE
Need help with CSS isolation with new rendering modes Blazor

### ISSUE THREAD

**Issue by PascalVorwerk** [microsoft/fluentui-blazor#2395]
# 💬 RFC

Hi, for some reason when i am trying to add some scoped css to my components it does not work. The tags that are eventually introduced in the html are completely different then those that are bundled in my css. 

Bundled css:
![image](https://github.com/user-attachments/assets/23655bc0-6ecc-4a2f-b106-e16d206b9b96)

Mainlayout html component:
![image](https://github.com/user-attachments/assets/6ed927e1-b4a5-4e40-bd79-9646596affbd)

This is causing that even a deep selector wont work, because the tags are different and thus it won't affect the components..

Has anyone else tried the suggested css styling? 

I have also found why the components are different tags:

![image](https://github.com/user-attachments/assets/e8a17da9-c351-4666-8c36-cb9f5aa442c8)

My project structure is as so:

Web.API (Containing API logic)
Web.Client (Containing the Razor components for both client and server side rendering)
Web.Server (Containing the app.razor and bootstrapping everything server side)
Web.Wasm (Containing the blazor WASM client that bootstraps everything for client side)

I don't know if it's because of my specific project structure that this is screwing things up, but help would be greatly appreciated!

**Comment by vnbaaij** [comment]
This is not really a library issue. Think it has indeed to do with your project setup.

I'll convert this to a discussion item so people can help you there m

**Comment by PascalVorwerk** [comment]
Ah right completely my bad, i forgot there was such a thing as the discussion tab. Did u already post it there or should i recreate?
