### ISSUE TITLE
fix: FluentCombobox ReadOnly not work

### ISSUE THREAD

**Issue by franklupo** [microsoft/fluentui-blazor#2402]
# 🐛 Bug Report

The propery `ReadOnly` for `FluentCombobox` not work.

## 💻 Repro or Code Sample

```
<FluentCombobox ReadOnly="true"  TOption="string">

</FluentCombobox>
```

## 🤔 Expected Behavior

ComboBox is editable.

## 😯 Current Behavior

ComboBox is read only.

## 💁 Possible Solution

The ReadOnly property is not assigned to the control. This could cause problems for other `list` components.

## 🌍 Your Environment

Windows 11 PRO, Microsoft Edge

OS & Device: [Windows 11] on [PC]
Browser Chrome
.NET and Fluent UI Blazor library Version [8.0.6 and 4.9.1]

**Comment by vnbaaij** [comment]
`ReadOnly` is not supported by the underlying web components and can therefore not be used with `FluentComboBox`, `FluentSelect` and FluentListbox`. 

These 3 component _do_ support the `Disabled` parameter.

We'll add a note to the documentation.

**Comment by franklupo** [comment]
Overriding ReadOnly and adding an exception, could that be an idea?

**Comment by vnbaaij** [comment]
Think that is a bit too much. Will put it in the code comments as well as in the docs. Developers should be able to find/see it then
