### ISSUE TITLE
feat: Can we provide support for multiple languages

### ISSUE THREAD

**Issue by TimChen44** [microsoft/fluentui-blazor#2404]
# 🙋 Feature Request

Can we add support for multiple languages
1. Examples of components in the document are provided in multiple languages
2. The buttons in components such as message boxes provide support for multiple languages

**Comment by dvoituron** [comment]
All components are customizable and can be used in any language.
What's your question?

**Comment by TimChen44** [comment]
Two questions.
Firstly, the Doc document is currently only available in English
The second one is that when using the Message Box component, other languages require input parameters every time to change the button text, which is quite troublesome, for example
DialogService.ShowConfirmationAsync("Do you have two eyes?", "是", "否", "Eyes on you");

**Comment by dvoituron** [comment]
Yes, English is the default language for all our developments (and default values).
And so, for other languages, you need to specify the content of the labels.

You could create your own extension methods to help you if you wish.

**Comment by franklupo** [comment]
you can use IStringLocalizer and store data in resources, database, json

**Comment by vnbaaij** [comment]
With regards to the demo and docs site, we really do not have capacity to translate it into multiple languages.

Closing this as it is not actionable.
