### ISSUE TITLE
SelectedItemChanged doesn't trigger on first sub item

### ISSUE THREAD

**Issue by stefandhondt** [microsoft/fluentui-blazor#2409]
Given your exact example code for the Treeview with unlimited items located at https://www.fluentui-blazor.net/TreeView#withunlimiteditems, the first subitem of an item never gets selected. All other items will update SelectedItem, but never the first.

![FirstSubItemIssue](https://github.com/user-attachments/assets/8a4693be-ac66-4f1b-acf6-c9608d9a0f31)

**Comment by dvoituron** [comment]
Will be fixed in the next release: #2414
