### ISSUE TITLE
fix: OnRowClick is always trigger in FluentDataGrid

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#2410]
# 🐛 Bug Report

If there is a control on a row, such as a button, OnRowClick is also triggered when clicking on the button. I would expect the button (or link) to have precedence and OnRowClick not to be triggered.

## 💻 Repro or Code Sample

1. Add FluentDataGrid with template column that contains button.
2. Add OnRowClick event.
3. Click on button.

## 🤔 Expected Behavior

Just the button is triggered when clicked. Clicking on the rest of the row triggers OnRowClick.

## 😯 Current Behavior

The button and OnRowClick is triggered.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by JamesNK** [comment]
The JavaScript equivalent would be calling `event.stopPropagation();` in the button click to stop the row also seeing the click, but I don't know how to do that with Blazor/FluentUI.

**Comment by JamesNK** [comment]
Suprisingly, this works:

```html
<div @onclick:stopPropagation="true">
    <FluentButton />
</div>
```

**Comment by vnbaaij** [comment]
Would you agree that the click should never propagate beyond the button?

**Comment by JamesNK** [comment]
I don't know. It seems like something you'd want to control. JavaScript lets you do that in events with `stopPropagation`. I don't know if Blazor has a similar API.

**Comment by dvoituron** [comment]
You can also use this code, passing directly through the Web Component, but in this case you're bypassing Blazor's functionality.
```xml
<fluent-button @onclick="..." @onclick:stopPropagation="true">Click here</fluent-button>
```

**Comment by vnbaaij** [comment]
@JamesNK for now please use the workaround you've found. For a later version we will look at adding the `@onclick:stopPropagation` to fluent-button (and perhaps other components).

Putting it on our todo list and closing it here
