### ISSUE TITLE
Fix For: Missing LibraryConfiguring Injection in DesignToken.razor.cs

### ISSUE THREAD

**Issue by TimonFeldmann** [microsoft/fluentui-blazor#2425]
# 🐛 Bug Report

This issue occurs exclusively in version 4.9.2, downgrading to 4.9.1 resolves the issue.

When injecting any design token and calling `.SetValue()` with any element reference, the `DesignToken` class fails to inject the registered `LibraryConfiguration` causing an `Object reference not set to an instance of an object`  exception to be thrown inside `UrlFormatterExtensions.cs`.

### Component:

```csharp
@using Microsoft.FluentUI.AspNetCore.Components.DesignTokens

<div class="container">
	<FluentTextField @ref="Test" @bind-Value=Title></FluentTextField>
</div>

@code {
	[Parameter, EditorRequired]
	public string Title { get; set; } = null!;

	FluentTextField Test;

	[Inject]
	private Density _density { get; set; } = default!;

	protected override async Task OnAfterRenderAsync(bool firstRender)
	{
		if (firstRender)
		{
			await _density.SetValueFor(Test.Element, 10);

			StateHasChanged();
		}
	}
}
```

### Startup:

```csharp
    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });

            builder.Services.AddMauiBlazorWebView();
	    builder.Services.AddHttpClient();
            builder.Services.AddFluentUIComponents();

#if DEBUG
            builder.Services.AddBlazorWebViewDeveloperTools();
            builder.Logging.AddDebug();
#endif

            return builder.Build();
        }
    }
```

## 🤔 Expected Behavior

Calling `.SetValue()` on any `DesignToken` should not throw a null reference exception.

## 😯 Current Behavior

`LibraryConfiguration` is injected as `null` into `DesignToken.razor.cs` causing a null reference exception when attempting to set *any* `DesignToken` value.

## 🌍 Your Environment

* OS & Device: Windows
* .NET MAUI desktop application
* .NET and Fluent UI Blazor library Version: .NET 8 / Fluent UI 4.9.2

**Comment by TimonFeldmann** [comment]
I went ahead and checked out this repository to see if I could find the issue and I was able to locate the issue and confirm the fix locally. I was not able to push a branch to this repository due to permission issues so I will simply post my perhaps naive fix here.

It appears there was an existing DI constructor in `DesignToken` which set the `IJSRuntime`, but not the `LibraryConfiguration` which was introduced in 4.9.2.

I modified the constructor for `DesignToken` as well as the `DesignTokenGenerator` to add the DI for `LibraryConfiguration` for all design tokens:

```diff
diff --git a/src/Core/DesignTokens/DesignToken.razor.cs b/src/Core/DesignTokens/DesignToken.razor.cs
index b06b05e2d..ec5142d8a 100644
--- a/src/Core/DesignTokens/DesignToken.razor.cs
+++ b/src/Core/DesignTokens/DesignToken.razor.cs
@@ -51,9 +51,10 @@ public partial class DesignToken<T> : ComponentBase, IDesignToken<T>, IAsyncDisp
     /// <summary>
     /// Constructs an instance of a DesignToken.
     /// </summary>
-    public DesignToken(IJSRuntime jsRuntime)
+    public DesignToken(IJSRuntime jsRuntime, LibraryConfiguration libraryConfiguration)
     {
         JSRuntime = jsRuntime;
+        LibraryConfiguration = libraryConfiguration;
     }
 
     /// <inheritdoc/>
diff --git a/src/Extensions/DesignToken.Generator/DesignTokenGenerator.cs b/src/Extensions/DesignToken.Generator/DesignTokenGenerator.cs
index 48f8a01d1..baf0345d6 100644
--- a/src/Extensions/DesignToken.Generator/DesignTokenGenerator.cs
+++ b/src/Extensions/DesignToken.Generator/DesignTokenGenerator.cs
@@ -66,7 +66,8 @@ public class DesignTokenGenerator : IIncrementalGenerator
             sb.AppendLine($"\t/// Constructs an instance of the {name} design token");
             sb.AppendLine("\t/// </summary>");
             sb.AppendLine("\t/// <param name=\"jsRuntime\">IJSRuntime reference</param>");
-            sb.AppendLine($"\tpublic {name}(IJSRuntime jsRuntime) : base(jsRuntime)");
+            sb.AppendLine("\t/// <param name=\"libraryConfiguration\">LibraryConfiguration reference</param>");
+            sb.AppendLine($"\tpublic {name}(IJSRuntime jsRuntime, LibraryConfiguration libraryConfiguration) : base(jsRuntime, libraryConfiguration)");
             sb.AppendLine("\t{");
             sb.AppendLine($"\t\tName = Constants.{name};");
             sb.AppendLine("\t}");

```

This works as expected locally.

**Comment by marqdouj** [comment]
fwiw, I just tried creating a  [WPF/Blazor Hybrid](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-10.0)

I figured I would try and replace the bootstrap with FluentUI-Blazor.
When I did, the app would not run and I got the 'LibraryConfiguration' error.

So I added the fix to the MainWindow constructor and it worked:

`
            InitializeComponent();

            var serviceCollection = new ServiceCollection();
            serviceCollection.AddWpfBlazorWebView();
            serviceCollection.AddSingleton(new LibraryConfiguration()
            {
                CollocatedJavaScriptQueryString = null,
            });
            Resources.Add("services", serviceCollection.BuildServiceProvider());
`
