### ISSUE TITLE
Toolbar example preview error

### ISSUE THREAD

**Issue by agriffard** [microsoft/fluentui-blazor#2428]
In https://www.fluentui-blazor.net/Toolbar, the first example preview shows an error : 
`AggregateException_ctor_DefaultMessage (Arg_NullReferenceException)`

![image](https://github.com/user-attachments/assets/1d209549-e67a-4e20-b773-936c1e3bbce7)

**Comment by agriffard** [comment]
In https://github.com/microsoft/fluentui-blazor/blob/fb861bcf63991033282eeeb9d98c7e744cd0baa1/examples/Demo/Shared/Pages/Toolbar/Examples/ToolbarDefault.razor#L1

```
@inject FillColor FillColor
@inject BaseLayerLuminance BaseLayerLuminance
```

Those classes don't seem to exist.

**Comment by vnbaaij** [comment]
This is caused by #2425. We will fix that soon.
