### ISSUE TITLE
Tooltip sample is not displayed over menu

### ISSUE THREAD

**Issue by agriffard** [microsoft/fluentui-blazor#2431]
In https://www.fluentui-blazor.net/Tooltip

The tooltip displayed by button 'Tooltip withou service' does not appear.
It seems to be under the menu:

![image](https://github.com/user-attachments/assets/58e413c9-772b-48b2-adec-a461573ba118)

**Comment by vnbaaij** [comment]
This is on purpose to show the difference between **not** using the service and using the service
