### ISSUE TITLE
Possible bug in the 4.9.2 javascript

### ISSUE THREAD

**Issue by coderdnewbie** [microsoft/fluentui-blazor#2433]
I have started to get the following error in 4.9.2 (see screenshot). Is this a bug or have I done something wrong.

![info](https://github.com/user-attachments/assets/41d068f7-157b-4d6a-b03d-aa0ed187e449)

Is this an issue?

Thanks.

**Comment by coderdnewbie** [comment]
It was ok in 4.9.0 (an earlier version), but I can see the above error in 4.9.1 as well. This is what it looked like in 4.9.0

![info](https://github.com/user-attachments/assets/b80d63f1-26b3-49c0-a39a-5698db931b12)

**Comment by vnbaaij** [comment]
This is probably because of #2425. Will be fixed soon
