### ISSUE TITLE
fix: If FluentNavMenu is shown shown programmatically the CollapsedChildNavigation doesn't work

### ISSUE THREAD

**Issue by DefinitelyADev** [microsoft/fluentui-blazor#2441]
# 🐛 Bug Report

If FluentNavMenu is placed inside an if and the property that if evaluates, is changed OnAfterRenderAsync, after some async work, the CollapsedChildNavigation stops working.

## 💻 Repro or Code Sample

I have provided an example project illustrating the problem.

## 🤔 Expected Behavior

The collapsed child navigation should work.

## 😯 Current Behavior

![nav-issue](https://github.com/user-attachments/assets/8b00f042-fdee-404a-ba99-bd242d172f10)

## 💁 Possible Solution

I'm willing to contribute a fix, but I don't know where the issue is.

## 🔦 Context

On OnAfterRenderAsync I am evaluating whether to show the collapse button of the nav menu (the Collapsible property). And I call some js providing me with the window inner width. This causes the collapse button to show after the rest of the menu is shown. It's much more preferable to show the complete menu later, than just the collapse button.

What happens without the check:
![collapse-experience](https://github.com/user-attachments/assets/5abf3ceb-9f7c-4935-a067-15b263f20734)

```cs
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        var width = await JsRuntime.InvokeAsync<int>("getViewportWidth");
        await SetCollapsibleBasedOnWidth(width);
        await JsRuntime.InvokeVoidAsync("addWindowResizedEventListener", _objRef);
        _hasFinishedRendering = true;
        StateHasChanged();
    }
}

[JSInvokable("SetCollapsibleBasedOnWidth")]
public Task SetCollapsibleBasedOnWidth(int width)
{
    _isCollapsible = width > 768;
    StateHasChanged();
    return Task.CompletedTask;
}
```

```js
function addWindowResizedEventListener(dotNetObjectRef) {
    window.addEventListener('resize', (event) => {
        dotNetObjectRef.invokeMethodAsync('SetCollapsibleBasedOnWidth', event.currentTarget.innerWidth)
    });
}

function getViewportWidth() {
    return window.innerWidth;
}
```

## 🌍 Your Environment

* OS & Device: Windows 10 on Dell laptop
* Browser: Microsoft Edge
* .NET and Fluent UI Blazor library Version: 8.0.206 and 4.9.1

**Comment by vnbaaij** [comment]
> I have provided an example project illustrating the problem.

I'm not seeing that code/project. We can't (won't) investigate based on the few code blocks you posted. Also, we need details on how you are running the site. Server/WebAssembly/Auto and with which interactivity

From what you are describing, it seems like you want the component to do something else then what it was built for. Not sure if we can accommodate to that.

**Comment by DefinitelyADev** [comment]
Oops forgot to attach the file 😳 

[nav-issue.zip](https://github.com/user-attachments/files/16347654/nav-issue.zip)


![image](https://github.com/user-attachments/assets/567188ef-e1a7-4c45-87e1-5c198929fa7f)

**Comment by DefinitelyADev** [comment]
> From what you are describing, it seems like you want the component to do something else then what it was built for. Not sure if we can accommodate to that.

I am using code from the examples mostly. The issue is, that I want to hide the collapse button on small screens.

**Comment by DefinitelyADev** [comment]
Hm ok this works, but I would also need to make sure to also expand it just in case the user has not expanded the sidebar.

**Comment by DefinitelyADev** [comment]
@vnbaaij would it be possible to expand it without js callback?

**Comment by vnbaaij** [comment]
You can use `@bind-Expanded="@Expanded"`. You can also make it use a menu in collapsed state. See https://www.fluentui-blazor.net/NavMenu#collapsible-navigation-example

**Comment by DefinitelyADev** [comment]
Yes, but I would have to something like this and still use js:

```razor
@implements IDisposable
@rendermode InteractiveServer
@inject IJSRuntime JsRuntime

<div class="navmenu">
    <input type="checkbox" title="Menu expand/collapse toggle" id="navmenu-toggle" class="navmenu-icon"/>
    <label for="navmenu-toggle" class="navmenu-icon">
        <FluentIcon Value="@(new Icons.Regular.Size20.Navigation())" Color="Color.Fill"/>
    </label>
    <nav class="sitenav" aria-labelledby="main-menu">
        <FluentNavMenu Id="main-menu" Collapsible="true" bind-Expanded="_expanded" Width="250" Title="Navigation menu" CollapsedChildNavigation="true" CustomToggle="true">
            <FluentNavLink Href="/" Match="NavLinkMatch.All" Icon="@(new Icons.Regular.Size20.Home())" IconColor="Color.Accent">Home</FluentNavLink>
            <FluentNavGroup Title="example" Icon="@(new Icons.Regular.Size20.Apps())" Expanded="true">
                <FluentNavLink Href="counter" Icon="@(new Icons.Regular.Size20.NumberSymbolSquare())" IconColor="Color.Accent">Counter</FluentNavLink>
                <FluentNavLink Href="weather" Icon="@(new Icons.Regular.Size20.WeatherPartlyCloudyDay())" IconColor="Color.Accent">Weather</FluentNavLink>
            </FluentNavGroup>
        </FluentNavMenu>
    </nav>
</div>

@code {
    private bool _expanded = false;
    private DotNetObjectReference<NavMenu> _objRef;

    protected override void OnInitialized() => _objRef = DotNetObjectReference.Create(this);

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await JsRuntime.InvokeVoidAsync("addWindowResizedEventListener", _objRef);
            StateHasChanged();
        }
    }

    [JSInvokable("SetExpandedBasedOnWidth")]
    public Task SetExpandedBasedOnWidth(int width)
    {
        if (width > 768)
        {
            _expanded = true;
            StateHasChanged();
        }

        return Task.CompletedTask;
    }

    public void Dispose() => _objRef?.Dispose();
}
```

```js
function addWindowResizedEventListener(dotNetObjectRef) {
    window.addEventListener('resize', (event) => {
        dotNetObjectRef.invokeMethodAsync('SetExpandedBasedOnWidth', event.currentTarget.innerWidth)
    });
}
```

**Comment by DefinitelyADev** [comment]
Admittedly this works much better though.

**Comment by vnbaaij** [comment]
So your issue is solved?

**Comment by DefinitelyADev** [comment]
Sure, if you have no other proposal. Thank you very much for your help!

**Comment by vnbaaij** [comment]
No, nothing I can think of. We dont have a way to make this a pure Blazor solution as we don't have info about screen size etc.

**Comment by DefinitelyADev** [comment]
I'm writing an update on this for anyone having a similar issue. I just found a way more elegant solution that seems to be working like a charm and has no js dependency. This will hold the state correctly no matter which button you click and persists on any screen size.

@vnbaaij maybe the demo/docs example can be updated with this. If you agree, would you like me to submit a pull request?

```razor
<div class="navmenu">
    <input type="checkbox" title="Menu expand/collapse toggle" id="navmenu-toggle" class="navmenu-icon" checked="@_expanded" @oninput="ExpandedChanged" />
    <label for="navmenu-toggle" class="navmenu-icon"><FluentIcon Value="@(new Icons.Regular.Size20.Navigation())" Color="Color.Fill" /></label>
    <nav class="sitenav" aria-labelledby="main-menu">
        <FluentNavMenu Id="main-menu" Collapsible="true" Width="250" Title="Navigation menu" @bind-Expanded="_expanded" CustomToggle="true">
            <FluentNavLink Href="/" Match="NavLinkMatch.All" Icon="@(new Icons.Regular.Size20.Home())" IconColor="Color.Accent">Home</FluentNavLink>
            <FluentNavLink Href="counter" Icon="@(new Icons.Regular.Size20.NumberSymbolSquare())" IconColor="Color.Accent">Counter</FluentNavLink>
            <FluentNavLink Href="weather" Icon="@(new Icons.Regular.Size20.WeatherPartlyCloudyDay())" IconColor="Color.Accent">Weather</FluentNavLink>
        </FluentNavMenu>
    </nav>
</div>

@code {
    private bool _expanded = false;

    private Task ExpandedChanged(ChangeEventArgs changeEventArgs)
    {
        if (changeEventArgs.Value is bool expanded)
        {
            _expanded = expanded;
        }

        return Task.CompletedTask;
    }

    private Task ExpandedChanged(bool expanded)
    {
        _expanded = expanded;
        return Task.CompletedTask;
    }
}
```

**Comment by DefinitelyADev** [comment]
I don't know why I went down that complicated rabbit hole previously, with all the callbacks.
