### ISSUE TITLE
Possible bug in 4.9.3 javascript

### ISSUE THREAD

**Issue by coderdnewbie** [microsoft/fluentui-blazor#2445]
I am still seeing the javascript issue, which unfortunately, was not fixed in https://github.com/microsoft/fluentui-blazor/issues/2433

I have investigated the issue. It was because I added the following line in App.razor

`<script src="_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js" type="text/javascript"></script>`

Please can you check the validity of the js file: _Microsoft.FluentUI.AspNetCore.Components.lib.module.js_ (which last worked fine in 4.9.0).

Unfortunately, from 4.9.1 to 4.9.3, the file now gives the following error (SyntaxError: Unexpected token 'export'), in the console log:

![info](https://github.com/user-attachments/assets/6c523e34-190a-490f-a84b-56ff2672e3f0)

**Comment by vnbaaij** [comment]
You normally don't need to add that script manually. We automatically load it,

Are you sure the script you are getting is the latest/newest one? Have you tried a hard refresh/empty cache?

**Comment by coderdnewbie** [comment]
A few months ago it was recommended I add this file so that the blazor app does not flicker when it is loading. That is why I had it manually added. I have now removed it and everything is working fine, without any initial flicker. So that is even better. Thanks, I will close this issue.
