### ISSUE TITLE
fix: add Overlay to Splash screen shown by ShowSplashScreenAsync

### ISSUE THREAD

**Issue by JarJasAskom** [microsoft/fluentui-blazor#2447]
Update 4.9.3.

Function ShowSplashScreenAsync shows splash screen always without overlay. Setting Modal parameter to true or false in DialogParameters has no effect.

Documention of SplashScreen has two demos in section "Default splash screen".

Button "Open splash screen" uses ShowSplashScreen and splash screen has overlay.

Button "Open splash screen (async)" uses ShowSplashScreenAsync and splash screen has no overlay.

Click handler OpenSplashDefaultAsync of the button "Open splash screen (async)" demonstrates the scenario I would like to implement:

- show splash screen with overlay visible,
- do work,
- update splash screen,
- do work,
- close splash screen programmatically from the code.

**Comment by vnbaaij** [comment]
I forgot to change one variation of the `ShowSplashScreenAsync` methods in PR #2398. The PR mentioned above fixes that and will be in the next release.
