### ISSUE TITLE
fix: Class not being set in FluentBadge

### ISSUE THREAD

**Issue by martin2karlsson** [microsoft/fluentui-blazor#2464]
# 🐛 Bug Report

## 💻 Repro or Code Sample
I created a new project with 

`dotnet new blazor`

 * Added Fluent package
 * Added reference in Program.cs 
 * Added a  using statement in the _Imports.razor
* Modified the App.Razor:

```
@page "/"

<PageTitle>Home</PageTitle>

<FluentBadge Class="--set-primary-color">

    This is a test
</FluentBadge>

<h1>Hello, world!</h1>

Welcome to your new app.
```

## 🤔 Expected Behavior
I expected the class to be set on FluentBadge but it was not. This was working in 4.7.2

![image](https://github.com/user-attachments/assets/abf31e66-0d35-4410-8d2b-9c9061c40375)

## 😯 Current Behavior
![image](https://github.com/user-attachments/assets/7481cf78-baf8-4725-98ce-22bfa9272f28)

## 💁 Possible Solution
I could rollback to the earlier version, or write a js script to set the class name. 

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version 8.0.7 and 4.9.3 (working in 8.0.7 and 4.7.2)

**Comment by vnbaaij** [comment]
I don't think you can start a class name with '--' as that is reserved for css variables and gets filtered out  See also https://github.com/microsoft/fluentui-blazor/pull/2255
