### ISSUE TITLE
Additional hover effects while loading content rows on data grids with Fluent-Skeleton

### ISSUE THREAD

**Issue by NataschaZorgWijnhoven** [microsoft/fluentui-blazor#2477]
# 🐛 Bug Report
Hello, We have noticed that while using the FluentSkeleton component for data grids, we have additional hover effects while loading the content rows. The rows are already clickable, can be selected and are highlighted as a whole. 

## 💻 Repro or Code Sample
Create a data grid which for instance is being used to retrieve data sets and make use of the FluentSkeleton here for loading content. 
Add a delay to see this behavior better while loading. 

## 🤔 Expected Behavior
To us this appears to be a bug, since the mentioned hover effects are only useful in case you have data to work with.
So we believe that these effects should be removed. 

## 😯 Current Behavior
Whilst using the FluentSkeleton component for data grids, the rows are already clickable, can be selected and are highlighted as a whole whilst loading.

## 💁 Possible Solution
Remove the mentioned hover effects. 

## 🌍 Your Environment
* OS: Windows 11, Visual Studio 17.10.4
* Browser: Edge Version 127.0.2651.74
* .NET: 8.0.303

**Comment by vnbaaij** [comment]
Hi Natascha,

Please supply us with ready to run example reproduction code. We don't have capacity to craft or compose a reproduction for every issue that gets raised in the repo. We are only a small team and need you to help us to help you.

**Comment by NataschaZorgWijnhoven** [comment]
When we use the `FluentDataGrid` with the following properties: `Loading="true"` `ShowHover="true"`, the rendered `<LoadingContent/>` has a hover effect, which is unexpected, since there is no usable data yet. 

The following code can be added to a razor-page to demonstrate this situation:

@page "/counter"

<FluentDataGrid Loading="true" ShowHover="true" Items="@(_gridData)">
    <ChildContent>
        <PropertyColumn Property="x => x" Title="Example" />
    </ChildContent>
    <LoadingContent>
        <h1>Loading...</h1>
    </LoadingContent>
</FluentDataGrid>

@code {
    private static readonly IQueryable<string> _gridData = new string[] { "Item 1" }.AsQueryable();
}

**Comment by NataschaZorgWijnhoven** [comment]
Thanks for the quick resolution.
