### ISSUE TITLE
fix: Databinding severed when Updated from JS Interop in FluentSlider

### ISSUE THREAD

**Issue by beowulf29a** [microsoft/fluentui-blazor#2478]
# 🐛 Bug Report

I'm trying to keep a value in sync between some JS code and my Blazor page.  Initially there are no issues; i.e. I can update the FluentSlider and I see the JS value getting updated.  Similarly, if I update the JS value I can see the FluentSlider value update.

However, after the first time utilizing the FluentSlider to update the JS any subsequent update from JS is not reflected in Blazor (I don't think it is a debouncer issue, but I have exhausted my time attempting work-arounds).

## 💻 Repro or Code Sample

```

@page "/sliderTest"
@inject IJSRuntime JS

<canvas id="myCanvas" height="300" width="400" style="border: 1px solid black" />
<p>Blazor: @ZoomValue</p>
<p>JS: <span id="mySpan"></span></p>

<div style="height: 10vh">
    <FluentSlider Min="0.5" Max="2.0" Step="0.1" @bind-Value:get=ZoomValue @bind-Value:set="UpdateJsZoom" Orientation="Orientation.Vertical" />
</div>

<script>
    var canvas = document.getElementById("myCanvas");
    var span = document.getElementById("mySpan");
    var currentZoom = 1.0;
    var currentStep = 0.1;
    var maxZoom = 2.0;
    var minZoom = 0.5;

    canvas && canvas.addEventListener('wheel', (evt) => {
        if (0 > evt.deltaY) {
            currentZoom += currentStep;
            currentZoom = Math.min(currentZoom, maxZoom);
        } else {
            currentZoom -= currentStep;
            currentZoom = Math.max(currentZoom, minZoom);
        }
        span.innerHTML = currentZoom;
        window.myDotNetHelper.invokeMethod("JsResize", currentZoom);
    });

    window.setDotNetHelper = function (dotNetHelper) {
        window.myDotNetHelper = dotNetHelper;
    };

    window.setDotNetZoom = function (zoom) {
        currentZoom = zoom;
        span.innerHTML = zoom;
    };
</script>

@code {
    double ZoomValue = 1.0;
    private DotNetObjectReference<SliderTest>? dotNetHelper;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            dotNetHelper = DotNetObjectReference.Create(this);
            await JS.InvokeVoidAsync("setDotNetHelper",
                dotNetHelper);
        }
    }

    async Task UpdateJsZoom(double val)
    {
        await JS.InvokeVoidAsync("setDotNetZoom",
                val);
        ZoomValue = val;
        StateHasChanged();
    }


    [JSInvokable]
    public void JsResize(double value)
    {
        ZoomValue = value;
        StateHasChanged();
    }
}
```

1. Use mouse wheel on canvas (black box) will update the JS-bound value and the Blazor-bound value (including FluentSlider)
2. Use the FluentSlider to update the JS-bound value and Blazor-bound

## 🤔 Expected Behavior

Using the mouse wheel again from step 1 now does not update the FluentSlider value (although it is updating the Blazor-bound value, which can be verified by the <span> update.)

## 😯 Current Behavior
The FluentSlider no longer updates after using itself to change the value from JS interop.

## 💁 Possible Solution
FluentInput is likely not detecting the Blazor-bound value updates

## 🔦 Context
I am trying to keep a zoom value in sync between blazor and javascript

## 🌍 Your Environment

.NET 8.0.7
FluentUI 4.9.3
Windows 11
Edge  127.0.2651.74

**Comment by vnbaaij** [comment]
I don't think this is a good way to do what you want. You are mixing responsibilities on who is to update the resulting zoom value. The slider itself is using script/js code itself internally as well so there is a good chance this interferes with your code.

**Comment by vnbaaij** [comment]
Your code is only working once because a script error is being thrown. If i change the line 
```
        window.myDotNetHelper.invokeMethod("JsResize", currentZoom);
```

to

```
        window.myDotNetHelper.invokeMethodAsync("JsResize", currentZoom);
```

it all works as expected.
