### ISSUE TITLE
feat: Add an option to align the filter to the right of the title in the Datagrid.

### ISSUE THREAD

**Issue by Quantumf0x** [microsoft/fluentui-blazor#2480]
# 🙋 Feature Request

To enhance the user interface (UI) of the data grid table, the filtering feature, which allows users to refine the data displayed, needs to be relocated. Instead of being positioned on the left side, the filter will be moved to the right side of the title at the top of the table. This adjustment aligns the filtering control closer to the title, streamlining the UI and possibly making it more intuitive for users to access and understand the filter's association with the table's content.

## 🤔 Expected Behavior

The filtering feature should be positioned to the right of the title at the top of the data grid table. This makes the filter more visible and intuitively linked with the title, enhancing the overall user experience. The filter's location should remain consistent, regardless of table size or screen resolution.

Additionally, there should be a configuration option to control the filter's alignment, such as a parameter like AlignFilter="right". The default behavior would place the filter on the left side, maintaining backward compatibility with existing implementations.

## 😯 Current Behavior

At the moment, the filter is located on the left side of the title at the top of the data grid table. This positioning can be less intuitive, especially for users who are accustomed to seeing filters aligned with the title on the right side in other applications.

## 💁 Possible Solution

Introduce a parameter, such as AlignFilter="right", to control the alignment of the filtering feature. When set, this parameter would move the filter to the right side of the title. By default, the filter should continue to be placed on the left side, preserving current behavior and ensuring a smooth transition for users.

This solution provides flexibility for different use cases, allowing developers to choose the filter alignment that best suits their application's design and user expectations.

## 🔦 Context

I'm trying to get the filter to the right because that placement suits my application's design better. In my application, the filter being on the right side aligns with other UI elements and user expectations.

Users have reported confusion and issues with the filter being on the left side, as they are accustomed to it being on the right in similar applications. This adjustment would help maintain consistency across the application's UI and improve user satisfaction.

I've considered custom CSS or JavaScript solutions to manually reposition the filter, but these approaches are less maintainable and harder to implement consistently across different environments. A built-in parameter would be a more robust and flexible solution.

## 💻 Examples

![image](https://github.com/user-attachments/assets/502a176d-5ea6-41e4-ad24-f8796c1a3bb8)

**Comment by vnbaaij** [comment]
With PR #2238 we've introduced another option being added to the "filter" menu. Effectively this means it is no longer a filter menu, but a more general column options menu. 
At the moment you only get this with a resizable grid but in a future version we will rool this out for all grids.
The filter indication will then be shown besides the sort up/sort down icon behind the title. You can already see this in action in the Typical Usage example at https://fluentui-blazor.net/Datagrid.

We will research to make positioning the menu indicator (the chevron down icon) configurable. But that is not a promise it will happen. It is another parameter on the grid and I'm not sure yet if it will offer any benefit.

**Comment by vnbaaij** [comment]
Closing this one as it will be addressed with a future DataGrid change.
