### ISSUE TITLE
fix: Failed to fetch dynamically imported module: in Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js

### ISSUE THREAD

**Issue by aldo-leka** [microsoft/fluentui-blazor#2482]
# 🐛 Bug Report

I get this error when running my fluent-ui blazor-server project a few times. It didn't happen for a few weeks since I started the project and now it's happening quite often although I simply changed some .razor files and I get stuck as fluent-ui's assets are not loading. I started this project by using the Fluent Blazor Web App template with individual user accounts.

## 💻 Repro or Code Sample

Program.cs (with my own services omitted)
```c#
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.FluentUI.AspNetCore.Components;
using TestIdentityScaffoldingFluentUi.Components;
using TestIdentityScaffoldingFluentUi.Components.Account;
using TestIdentityScaffoldingFluentUi.Data;
using TestIdentityScaffoldingFluentUi.Services;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();
builder.Services.AddFluentUIComponents();
builder.Services.AddDataGridEntityFrameworkAdapter();

builder.Services.AddCascadingAuthenticationState();
builder.Services.AddScoped<IdentityUserAccessor>();
builder.Services.AddScoped<IdentityRedirectManager>();
builder.Services.AddScoped<AuthenticationStateProvider, IdentityRevalidatingAuthenticationStateProvider>();

builder.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
        options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    })
    .AddIdentityCookies();

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
builder.Services.AddDbContext<ApplicationDbContext>(options => options.UseNpgsql(connectionString));

builder.Services.AddDatabaseDeveloperPageExceptionFilter();

builder.Services.AddIdentityCore<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddSignInManager()
    .AddDefaultTokenProviders();

builder.Services.Configure<IdentityOptions>(options =>
{
    options.User.RequireUniqueEmail = true;
});

builder.Services.AddSingleton<IEmailSender<ApplicationUser>, SendGridEmailSender>();
builder.Services.Configure<SendGridEmailSenderOptions>(options =>
{
    options.ApiKey = builder.Configuration["SendGrid:ApiKey"];
    options.SenderEmail = builder.Configuration["SendGrid:SenderEmail"];
    options.SenderName = builder.Configuration["SendGrid:SenderName"];
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseMigrationsEndPoint();
}
else
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseStatusCodePagesWithRedirects("/404");
app.UseAntiforgery();

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

// Add additional endpoints required by the Identity /Account Razor components.
app.MapAdditionalIdentityEndpoints();

app.Run();
``` 

App.razor
```c#
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="TestIdentityScaffoldingFluentUi.styles.css" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <HeadOutlet @rendermode="RenderModeForPage" />
</head>

<body>
    <Routes @rendermode="RenderModeForPage" />
    <script src="_framework/blazor.web.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.slim.js" integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script>
</body>

</html>

@code {
    [CascadingParameter]
    private HttpContext HttpContext { get; set; } = default!;

    private IComponentRenderMode RenderModeForPage => HttpContext.Request.Path.StartsWithSegments("/Account")
        ? null
        : InteractiveServer;
}

``` 

## 🤔 Expected Behavior

The fluent-ui assets should load normally.

## 😯 Current Behavior

I get these errors in my browser console:
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

`Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://localhost:7246/_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js`

## 💁 Possible Solution
I deleted the .vs and bin folder, cleaned and rebuilt the solution. I ran the project in a different laptop by pulling it from Github and it worked there. I did the same at my pc and it works temporarily. After a few runs I get this error again.

When I browse `https://localhost:7246/_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js`, I get my own _404.razor page.

## 🔦 Context

I am building an app and I am stuck at the moment because of this issue.

## 🌍 Your Environment

OS & Device: Windows
Browser: Microsoft Edge, Google Chrome, Mozilla FireFox
.NET library Version: 8.0
Fluent UI Blazor library Version: I see `"4.*-* "` in my .csproj but 4.9.3 at Manage NuGet Packages...

**Comment by aldo-leka** [comment]
I had routing like this:

`@page "/{ticker}/{name}/{accessionNumber}"`
When I changed it to this, I got it working again:

`@page "/companies/{ticker}/{name}/{accessionNumber}"`

It seems the previous routing created issues with assets loaded from wwwroot. I'd like to know how to keep the previous routing though, but for now this will do.

**Comment by vnbaaij** [comment]
We don't do anything with the standard Blazor routing. If you get errors with a certain error, I'm guessing that would happen with standard Blazor as well.

Closing this as you have found a workaround.
