### ISSUE TITLE
FluentMenuButton (or FluentMenu with a separate button) are clipped by the bounds of the container

### ISSUE THREAD

**Issue by rsukremap** [microsoft/fluentui-blazor#2488]
# 🐛 Bug Report

FluentMenuButton (or FluentMenu with a separate button) are clipped by the bounds of the containing card.

## 💻 Repro or Code Sample

    <FluentCard Height="100px">
        <FluentMenuButton Text="Select brand color">
            <FluentMenuItem Id="0078D4">Windows</FluentMenuItem>
            <FluentMenuItem Id="D83B01" Disabled="true">Office</FluentMenuItem>
            <FluentMenuItem Id="464EB8">Teams</FluentMenuItem>
            <FluentMenuItem Id="107C10" Disabled="true">Xbox</FluentMenuItem>
            <FluentMenuItem Id="8661C5">Visual Studio</FluentMenuItem>
            <FluentMenuItem Id="F2C811" Disabled="true">Power BI</FluentMenuItem>
            <FluentMenuItem Id="0066FF">Power Automate</FluentMenuItem>
            <FluentMenuItem Id="742774" Disabled="true">Power Apps</FluentMenuItem>
            <FluentMenuItem Id="0B556A">Power Virtual Agents</FluentMenuItem>
        </FluentMenuButton>
    </FluentCard>

## 🤔 Expected Behavior

Menu should appear above the page content

## 😯 Current Behavior

Menu is clipped by the card bounds.

![image](https://github.com/user-attachments/assets/f46a66f2-2237-4138-ae42-bd832bd3c84f)

## 💁 Possible Solution

Unknown.

## 🔦 Context

I'm guessing this problem might happen in other scenarios too if the menu is not rendered above the page content. Maybe there is a simple mitigation I am overlooking - I did a good search of FluentMenu / FluentMenuButton issues.

## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version [e.g. 8.0.7 and 4.9.3]

**Comment by vnbaaij** [comment]
Did you look at https://www.fluentui-blazor.net/Card#AreaRestricted example?

**Comment by rsukremap** [comment]
Arrgghh - completely missed that on the card page - thank you and apologies for the oversight.
