### ISSUE TITLE
feat: add ability to have a preferred positioning option in FluentTooltip

### ISSUE THREAD

**Issue by adamint** [microsoft/fluentui-blazor#2491]
# 🙋 Feature Request
There is the ability to set position, and the ability to have a position chosen for you, for FluentTooltip, but not the ability to have a preferred positioning (if space permits), otherwise defaulting to the automatic placement.

## 🤔 Expected Behavior
If there is enough screen space to place the tooltip in your preferred spot (ie, bottom), then the tooltip would be placed there. If it would be cut off, then the tooltip would be automatically placed. 

## 🔦 Context
https://github.com/dotnet/aspire/pull/5151

**Comment by dvoituron** [comment]
You have the `TooltipPosition` to specify the desired position (left, top, bottom, ...)

But if you don't set this property, the _best position_ will be used. Is it not the case?

**Comment by dvoituron** [comment]
We don't have other possibilities with the web components used to display a tooltip.

**Comment by adamint** [comment]
> You have the `TooltipPosition` to specify the desired position (left, top, bottom, ...)

This property isn’t enough, since the tooltip may be placed in an inaccessible position if set.

> But if you don't set this property, the _best position_ will be used. Is it not the case?

The “best position” is subjective and sometimes chosen wrongly. Oftentimes there are multiple valid positions a tooltip could be set at, there is no way to choose a preferred one.

**Comment by dvoituron** [comment]
I agree with you, but with WebComponents v2 we don't have any other options for handling this situation. We're working on the next version of FluentUI-Blazor, which will support WebComponents v3. I hope this feature will be present.

To get around the problem, isn't it possible to impose the Tooltip position, just for this component?

Example: https://jsfiddle.net/dvoituron/skzbm6p5/113/

**Comment by vnbaaij** [comment]
As Denis mentioned, we can't change this with the current web components version. Closing this one.
