### ISSUE TITLE
fix: CurrentSelected in FluentTreeView

### ISSUE THREAD

**Issue by beowulf29a** [microsoft/fluentui-blazor#2493]
# 🐛 Bug Report

Documentation indicates that CurrentSelected can set the selected tree item.  But I am unable to visually clear the selected in codebehind.

## 💻 Repro or Code Sample

```
@page "/clearSelected"

<FluentTreeView @bind-CurrentSelected=currentSelected OnExpandedChange="HandleOnExpandedChanged">
    <FluentTreeItem Text="Root item 1">
        <FluentTreeItem Text="Flowers">
            <FluentTreeItem Disabled="true" Text="Daisy" />
            <FluentTreeItem Text="Sunflower" />
            <FluentTreeItem Text="Rose" />
        </FluentTreeItem>
        <FluentTreeItem Text="Nested item 2" />
        <FluentTreeItem Text="Nested item 3" />
    </FluentTreeItem>
    <FluentTreeItem Text="Root item 2">
        <FluentDivider></FluentDivider>
        <FluentTreeItem Text="Flowers">
            <FluentTreeItem Disabled="true" Text="Daisy" />
            <FluentTreeItem Text="Sunflower" />
            <FluentTreeItem Text="Rose" />
        </FluentTreeItem>
        <FluentTreeItem Text="Nested item 2" />
        <FluentTreeItem Text="Nested item 3" />
    </FluentTreeItem>
    <FluentTreeItem Text="Root item 3 - Leaf Erikson" />
</FluentTreeView>

<p>Current selected tree item is @currentSelected?.Text</p>
<p>Most recently expanded/collapsed tree item is @currentAffected?.Text</p>

@code {
    FluentTreeItem? currentSelected;
    FluentTreeItem? currentAffected;

    private void HandleOnExpandedChanged(FluentTreeItem item)
    {
        currentAffected = item;

        //Notice when expanded again the selected item
        // still appears as "selected" even though it
        // is reset to null.
        if (!item.Expanded)
        {
            currentSelected = null;
        }
    }
}
```
1. Expand tree to leaf
2. Select leaf
3. Collapse parent
4. Expand same item in step 3

## 🤔 Expected Behavior

Upon expanding the parent of a previously selected TreeViewItem child I would expect it to not show as visually selected.

## 😯 Current Behavior

![image](https://github.com/user-attachments/assets/0e873035-d916-45b2-bb2f-a1a5fa044b62)
Child still shows as visually selected within tree view.

## 🔦 Context

PO complains that it is confusing to users :D

## 🌍 Your Environment

Windows 11
Edge 127.0.2651.74 
.NET 8
FluentUI 4.9.3

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by dvoituron** [comment]
I don't think it's possible to deselect using a tree constructed via `FluentTreeItem`. But you should be able to deselect an item using the tree construction via the `Items` property (where `SelectedItem` can be setted to `null`).

See example "With Items" https://www.fluentui-blazor.net/TreeView

**Comment by beowulf29a** [comment]
@dvoituron yes, I suspected as much. I would request then that the documentation be updated (there are other places where usage of .Items is required. My only hope was that because of the 'With Data Binding' example shows a similar usage of the @bind-Selected set on the FluentTreeItem, but again, I had hoped that the FluentTreeView 'CurrentSelected' may do the trick.

**Comment by vnbaaij** [comment]
We will add a note to the docs
