### ISSUE TITLE
feat: add auto-fit to DataGrid

### ISSUE THREAD

**Issue by ksbecker** [microsoft/fluentui-blazor#2495]
# 🙋 Feature Request

Add some sort of auto-fit feature to the DataGrid component to make the columns render better

## 🤔 Expected Behavior

By setting a flag on the DataGrid component, the columns of the DataGrid should make an attempt to balance the columns better.

## 😯 Current Behavior

With no explicit formatting, the columns evenly distribute the width of each column.

## 💁 Possible Solution

Use JS and some CSS techniques to calculate column widths and apply widths dynamically to each column. 

## 🔦 Context

With dynamic content it's difficult to predict exact widths for each column of a DataGrid. This feature would automatically determine better widths for each column based on initial load.

## 💻 Examples

![image](https://github.com/user-attachments/assets/e2f3adee-a6ee-42d4-b6b7-3ef4824321df)

**Comment by MarvinKlein1508** [comment]
I would also love to see the ability to not cut-off the text in the columns using this apporach here.

**Comment by ksbecker** [comment]
> I would also love to see the ability to not cut-off the text in the columns using this apporach here.

Good news, I've already submitted a PR for this new feature. It's not perfect, but it's a simple way to format the columns for a bit better presentation out of the box.

**Comment by vnbaaij** [comment]
Closing this as PR has been merged
