### ISSUE TITLE
fix: PreventDismissOnOverlayClick = true not working in DialogService.ShowMessageBoxAsync

### ISSUE THREAD

**Issue by roamschemer** [microsoft/fluentui-blazor#2499]
🐛 Bug Report

💻 Repro or Code Sample

When setting PreventDismissOnOverlayClick = true in DialogService.ShowMessageBoxAsync, clicking outside the modal does not cancel it as expected. Below is the code used:

```csharp
private async Task OnOpenDeleteConfirmationDialog(Company company) {
    var dialog = await DialogService.ShowMessageBoxAsync(new DialogParameters<MessageBoxContent>() {
            Content = new() {
                Title = "Delete Confirmation",
                MarkupMessage = new MarkupString("Are you sure you want to delete?"),
                Icon = new Icons.Regular.Size24.Games(),
                IconColor = Color.Success,
            },
            PreventDismissOnOverlayClick = true
        });
    var result = await dialog.Result;
    if (result.Cancelled)
        return;
    await DeleteCompanyAsync(company);
}
```

🤔 Expected Behavior

The modal should close when clicking outside it if PreventDismissOnOverlayClick is set to true.

😯 Current Behavior

Currently, clicking outside the modal does not close it even with PreventDismissOnOverlayClick set to true.

💁 Possible Solution

Please provide guidance or a fix if available.

🔦 Context

This issue affects the functionality of our confirmation dialogs, leading to dialogs not closing as expected.

🌍 Your Environment

OS & Device: [e.g. Windows] on [PC]
Browser: [e.g. Google Chrome]
.NET and Fluent UI Blazor library Version: [e.g. 8.0.6 and 4.9.3]
Please let me know if you need any further information or clarification. Thank you for your assistance!

**Comment by vnbaaij** [comment]
You have the meaning of the PreventDismissOnOverlayClick wrong... If you set it to true, when clicking on the overlay (ie outside of the dialog) it is  **prevented to close**

Besides that, it is by design that a MessageBox acts like it does. It isn't super too be dismissed by clicking outside of it.
