### ISSUE TITLE
rfc: input field in DataGrid

### ISSUE THREAD

**Issue by yermakovsergey** [microsoft/fluentui-blazor#2528]
# 💬 RFC

Hello,
I don't know is it a bug or it's working as planned:
You can't use home and end buttons in input fields placed in datagrid, 
when you press home or end this leads to focus on table cell and focusOut from input field, that's quite annoying.
As I understand problem exists because of row selection is happening when clicking at input.

## 💻 Examples

like at fluentUI homepage, Datagrid page, part "Template columns 2".
focus in FluentTextField, press home or end btn
https://www.fluentui-blazor.net/DataGrid#templatecolumns2

**Comment by dvoituron** [comment]
This is indeed how the DataGrid works: these “Home” and “End” keys are used to navigate through the cells.

On the other hand, FluentUI does not recommend using input fields directly in a DataGrid, but recommends opening a separate window;
