### ISSUE TITLE
fix: Selected tab in FluentTabs is visually inconsistent

### ISSUE THREAD

**Issue by garrenf** [microsoft/fluentui-blazor#2536]
# 🐛 Bug Report
There's a synchronization issue regarding the small blue line underneath the selected tab in FluentTabs. The problem seems to originate from adding new tabs. The title text of the selected tab does get switched to bold, while blue underline stays in place.

## 💻 Repro or Code Sample
This visual inconsistency can be seen straight from the [demo website](https://www.fluentui-blazor.net/Tabs#dynamic).

In the 'Dynamic' example, delete all tabs except 'December'
![image](https://github.com/user-attachments/assets/51acb778-9dde-417a-ba42-81c466a8c155)

Click 'Add and select'. This should add a new tab named 'New 21' and select it, but notice how the blue underline stays in place, while the title text of the selected tab is styled to bold.
![image](https://github.com/user-attachments/assets/661e83c5-347a-42c4-93af-ae5227a1fed7)

Clicking 'December' now switches the underline to the unselected 'New 21' tab, but 'December' is now bold because it is selected.
![image](https://github.com/user-attachments/assets/9f532dd2-27b5-448b-9430-eaadf8cb3b55)

Clicking 'New 21' now causes the selected tab to be consistent.
![image](https://github.com/user-attachments/assets/0fd09a9d-8355-47a9-94d1-c6e7581f3c3f)

**Comment by vnbaaij** [comment]
That behavior is coming from the underlying web component and we can't fix on our side unfortunately.
