### ISSUE TITLE
feat: add HiddenWhen property to FluentDataGrid columns for on small screens

### ISSUE THREAD

**Issue by d7zzz** [microsoft/fluentui-blazor#2537]
# 🙋 Feature Request

Attribute in PropertyColumn/TemplateColumn that allows to hide some column on smaller screens.
Compare to StepTitleHiddenWhen in FluentWizard

## 💁 Possible Solution

A property like "HiddenWhen" that can be filled with something like GridItemHidden (XsAndDown...)

## 🔦 Context

I tried it with CSS but i have not found a working solution.

Alternative: Copy and paste the grid and hide one complete grid with CSS.

**Comment by dvoituron** [comment]
You can use the `FluentGrid` component to detect whether you are on mobile and to update the `GridTemplateColumns` attribute (in addition to `display: none`).

Example of "Get started" grid in our Demo site.

```razor
@code
{
    bool Mobile = false;
    void OnBreakpointEnter(GridItemSize size) => Mobile = size < GridItemSize.Sm;
    string GetGridTemplateColumns => Mobile ? "0px 1fr 0px" : "1fr 1fr 1fr";
}

<style>
    /* 0px 1fr 0px */
    fluent-data-grid[mobile] fluent-data-grid-cell:nth-child(1),
    fluent-data-grid[mobile] fluent-data-grid-cell:nth-child(3) {
        display: none;
    }
</style>

<FluentGrid OnBreakpointEnter="@OnBreakpointEnter" />

<FluentDataGrid mobile="@Mobile" Items="@people" GridTemplateColumns="@GetGridTemplateColumns">
    <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" />
    <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
    <PropertyColumn Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
</FluentDataGrid>
```

![peek_2](https://github.com/user-attachments/assets/911dca3a-c32c-452f-a0c4-5904dbc3f0ea)

> You will probably have some issue when using the Resize feature

**Comment by d7zzz** [comment]
Interesting approach! Thank you!

**Comment by vnbaaij** [comment]
Closing this as an alternative approach has been provided.
