### ISSUE TITLE
fix: anchored HorizontalPosition in FluentMenu does not always work inside a splitter panel

### ISSUE THREAD

**Issue by adamint** [microsoft/fluentui-blazor#2538]
# 🐛 Bug Report

The gif in [this comment](https://github.com/dotnet/aspire/pull/5266#issuecomment-2289838512) displays the issue - in the second column header in a data grid inside a fluent splitter panel, if you have a menu that is anchored on the column header, its horizontal positioning will be messed up.

<img width="797" alt="image" src="https://github.com/user-attachments/assets/456efd38-2b08-4f36-a9d7-02aac65aa91c">

## 💻 Repro or Code Sample
```blazor
<FluentSplitter Orientation="Orientation.Vertical" BarSize="6" Panel1MinSize="15%" Panel2MinSize="50px" Style="height: 100%">
    <Panel1>
        <div class="demopanel">
            <p>Panel1</p>
        </div>
    </Panel1>
    <Panel2>
        <div style="width: 700px; height: 400px; overflow-y: scroll; overflow-x: scroll;">
            <FluentDataGrid
                ResizableColumns="true"
                Items=@_items
                Virtualize="true"
                ItemSize="54">
                <ChildContent>
                    <PropertyColumn TGridItem="SampleGridData" TProp="string" Property="@(c => c.Item1)" Sortable="true" Title="Test"/>

                    <PropertyColumn TGridItem="SampleGridData" TProp="string" Property="@(c => c.Item1)" Sortable="true" Title="Test">
                        <HeaderCellItemTemplate>
                            <FluentButton Style="width: 100%" Id="@_columnId" Appearance="Appearance.Stealth" class="col-sort-button" @onclick="@(() => _isMenuOpen = !_isMenuOpen)">
                                Column header
                            </FluentButton>

                            <FluentMenu Anchor="@_columnId" @bind-Open="@_isMenuOpen">
                                <FluentMenuItem>Option1</FluentMenuItem>
                                <FluentMenuItem>Option2</FluentMenuItem>
                            </FluentMenu>
                        </HeaderCellItemTemplate>
                    </PropertyColumn>
                </ChildContent>
                <EmptyContent>
                    <FluentIcon Value="@(new Icons.Filled.Size24.Crown())" Color="@Color.Accent"/>&nbsp; Nothing to see here. Carry on!
                </EmptyContent>
            </FluentDataGrid>
        </div>
    </Panel2>
</FluentSplitter>

@code {
    private bool _isMenuOpen;
    private readonly string _columnId = $"column-header{Guid.NewGuid():N}";

    public record SampleGridData(string Item1, string Item2, string Item3, string Item4);

    IQueryable<SampleGridData>? _items = Enumerable.Empty<SampleGridData>().AsQueryable();

    private IQueryable<SampleGridData> GenerateSampleGridData(int size)
    {
        SampleGridData[] data = new SampleGridData[size];

        for (int i = 0; i < size; i++)
        {
            data[i] = new SampleGridData($"value {i}-1", $"value {i}-2", $"value {i}-3", $"value {i}-4");
        }
        return data.AsQueryable();
    }
    
    protected override void OnInitialized()
    {
        _items = GenerateSampleGridData(5000);
    }
}
```

## 🤔 Expected Behavior

Both column header menus should be anchored at the beginning of the component.

## 😯 Current Behavior

<img width="702" alt="image" src="https://github.com/user-attachments/assets/2acdd458-9949-4c59-a169-0886c880eafc">
<img width="780" alt="image" src="https://github.com/user-attachments/assets/10f8a491-bd3b-402c-9135-427e248358d4">

## 🔦 Context

https://github.com/dotnet/aspire/pull/5266#issuecomment-2289838512

**Comment by vnbaaij** [comment]
As strange as it sounds, this can be solved by adding `HorizontalPosition="HorizontalPosition.End"` to the `FluentMenu` component tag. There seems to be a logical error in the web components script in the part that calculates the transform values.

I've verified this to work on the Aspire side:
![image](https://github.com/user-attachments/assets/01d7932b-a625-4479-b5a0-0149e83b20bb)

**Comment by vnbaaij** [comment]
We could also pass through the `HorizontalViewportLock` to the anchored region and set `HorizontalScaling="AxisScalingMode.Anchor"` on the anchored region. That way the menu will always be set to the same with as the button in the header (as that is the anchor). It would look like this:

![image](https://github.com/user-attachments/assets/47c96f84-ef4a-42b4-a299-08c4556991e4)

Thoughts?

**Comment by adamint** [comment]
> We could also pass through the `HorizontalViewportLock` to the anchored region (and set it to `false`) and set `HorizontalScaling="AxisScalingMode.Anchor"` on the anchored region. That way the menu will always be set to the same with as the button in the header (as that is the anchor). It would look like this:
> 
> ![image](https://private-user-images.githubusercontent.com/1761079/360974123-47c96f84-ef4a-42b4-a299-08c4556991e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NDAzNDAsIm5iZiI6MTcyNDQ0MDA0MCwicGF0aCI6Ii8xNzYxMDc5LzM2MDk3NDEyMy00N2M5NmY4NC1lZjRhLTQyYjQtYTI5OS0wOGM0NTU2OTkxZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTkwNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Q3ZjhhOTA2NDY3MTQyOTI3MGFkNDYxOTM5YmI4YzI3ZWYzNzBlYmYyZGJlOTA0MTBkNzVkNTM0MThlNDY3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TTDaxTRi4_ABc945eVAjj197lgtdHwpTczDTuxdAhPU)
> 
> Thoughts?

I’m of the opinion that more/all anchored region properties should be accessible through Menu/Select, so I do like this idea.

**Comment by vnbaaij** [comment]
Created PR #2579 for the extra parameter pass through
