### ISSUE TITLE
Change FluentButton background

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [microsoft/fluentui-blazor#2544]
Hello,

It seems FluentButton background color in light theme could be stronger to differentiate from the website's background color. Right now, we can barely see some of them are buttons:

![image](https://github.com/user-attachments/assets/7de415eb-f70b-4a6a-985f-03f56e628618)

What it is the recommend approach to change these buttons background? Is it by overriding/creating a theme?

Thanks.

**Comment by vnbaaij** [comment]
This is not really an issue we need to change from our side. There are a couple of things you can do
- you can use the buttons' BackgroundColor parameter
- you can chance the background color of the site with standard CSS or by using one of the defined css variables (see https://fluentui-blazor.net/DesignTokens)
