### ISSUE TITLE
feat: add @ref to form inputs

### ISSUE THREAD

**Issue by JD2005L** [microsoft/fluentui-blazor#2547]
# 🙋 Feature Request

Need @ref parameter to work on fluentinputs such as fluentselect so that I can set focus via an ElementReference.

## 🤔 Expected Behavior

Allow @ref as a parameter so that it can be referenced in the code block.

## 😯 Current Behavior

@ref currently isn't supported by the fluent inputs.

## 💁 Possible Solution

Anything that allows me to reference the input in code.

## 🔦 Context

I am trying to programmatically set focus to a fluentselect after pageload.

## 💻 Examples

@if(isEditingWorkSite)
{
    <FluentSelect TOption="CustomerSite"
                  Label="Work Site"
                  Items="job.JobCustomer.CustomerSites"
                  OptionValue="@(c => c.id)"
                  OptionText="@(c => c.Name)"
@ref="inputSelectWorkSite"
                  @onfocusout="CancelEditing"
                  @bind-Value="selectedSiteId"
                  @onchange="@(async (args) => await OnWorkSiteChanged(args.Value?.ToString()))"
    Placeholder="Choose a Work Site" />
}
else
{
    <h6><span class="editable" @onclick="EnableEditWorkSite">@job.JobWorkSite?.JobCustomerSite.Name</span></h6>
}

private bool isEditingWorkSite =  false;
private ElementReference inputSelectWorkSite;

private void EnableEditWorkSite()
{
    isEditingWorkSite = true;
    inputSelectWorkSite.FocusAsync();
    StateHasChanged();
}

private async Task CancelEditing()
{
    await Task.Delay(50);
    isEditingWorkSite = false;
    StateHasChanged();
}

**Comment by vnbaaij** [comment]
@ref is not an ElementReference in this case. It should be declared as type `FluentSelect`.
If you then want to get the element, use the `.Element` parameter/property

**Comment by JD2005L** [comment]
I don't follow?  Without the @ref how do I reference the fluentselect in order to manipulate it after the page has already loaded?

Here is a simpler example of what I am trying to do, this works fine:

<h1 @ref=MyElementReference>Hello, world!</h1>

@code {
  private ElementReference MyElementReference;
}

What would be the equivalent example in your recommended approach?

**Comment by vnbaaij** [comment]
Something like this (I'm not near a computer so doing this from top of my head) :
```
@if(isEditingWorkSite)
{
    <FluentSelect TOption="CustomerSite"
                  Label="Work Site"
                  Items="job.JobCustomer.CustomerSites"
                  OptionValue="@(c => c.id)"
                  OptionText="@(c => c.Name)"
@ref="inputSelectWorkSite"
                  @onfocusout="CancelEditing"
                  @bind-Value="selectedSiteId"
                  @onchange="@(async (args) => await OnWorkSiteChanged(args.Value?.ToString()))"
    Placeholder="Choose a Work Site" />
}
else
{
    <h6><span class="editable" @onclick="EnableEditWorkSite">@job.JobWorkSite?.JobCustomerSite.Name</span></h6>
}

private bool isEditingWorkSite =  false;
private FluentSelect inputSelectWorkSite;

private void EnableEditWorkSite()
{
    isEditingWorkSite = true;
    inputSelectWorkSite. Element.FocusAsync();
    StateHasChanged();
}

private async Task CancelEditing()
{
    await Task.Delay(50);
    isEditingWorkSite = false;
    StateHasChanged();
}
```

**Comment by JD2005L** [comment]
But that's the point of my post here, @ref="inputSelectWorkSite" is throwing errors as not being supported by the fluentselect.

**Comment by JD2005L** [comment]
So here's what I've done, and I'm getting error "Object reference not set to an instance of an object." on the line that calls "inputSelectWorkSite.FocusAsync();"

```
@if(isEditingWorkSite)
{
    <FluentSelect TOption="CustomerSite"
                  Label="Work Site"
                  Items="job.JobCustomer.CustomerSites"
                  OptionValue="@(c => c.id)"
                  OptionText="@(c => c.Name)"
@ref="inputSelectWorkSite"
                  @onfocusout="CancelEditing"
                  @bind-Value="selectedSiteId"
                  @onchange="@(async (args) => await OnWorkSiteChanged(args.Value?.ToString()))"
    Placeholder="Choose a Work Site" />
}
else
{
    <h6><span class="editable" @onclick="EnableEditWorkSite">@job.JobWorkSite?.JobCustomerSite.Name</span></h6>
}

private bool isEditingWorkSite =  false;
private FluentSelect<CustomerSite> inputSelectWorkSite;

private void EnableEditWorkSite()
{
    isEditingWorkSite = true;
    inputSelectWorkSite.FocusAsync();
    StateHasChanged();
}

private async Task CancelEditing()
{
    await Task.Delay(50);
    isEditingWorkSite = false;
    StateHasChanged();
}
```

**Comment by JD2005L** [comment]
Ok I figured it out, needed to add a slight delay so the fluentselect could render.  It now works, thanks for your help!

```
private void EnableEditWorkSite()
{
    isEditingWorkSite = true;
    StateHasChanged();

    _ = Task.Run(async () =>
    {
        await Task.Delay(50);

        if (inputSelectWorkSite != null)
        {
            inputSelectWorkSite.FocusAsync();
        }
        else
        {
            ToastService.ShowInfo("inputSelectWorkSite is not yet initialized.");
        }
    });
}
```
