### ISSUE TITLE
feat: Support read-only collections as items in `<FluentDataGrid>` with `ItemsProvider`

### ISSUE THREAD

**Issue by aayjaychan** [microsoft/fluentui-blazor#2548]
# 🙋 Feature Request

I'd like to use a read-only collection as items for `<FluentDataGrid>` when using `ItemsProvider`.

## 🤔 Expected Behavior

```csharp
public class Response
{
    public IReadOnlyList<ItemType> Items { get; }
    public int TotalItemCount { get; }
    // ...
}

// Assigned to `FluentDataGrid.ItemProvider`.
private async ValueTask<GridItemsProviderResult<ItemType>> ProvideItemsAsync(
    GridItemsProviderRequest<ItemType> request)
{
    Response response = // ...

    // This currently doesn't compile.
    return GridItemsProviderResult.From(
        items: response.Items,
        totalItemCount: response.TotalItemCount);
}
```

## 😯 Current Behavior

Currently, `GridItemsProviderResult<TGridItem>.Items` has type of `ICollection<T>`.  Read-only collections like `IEnumerable<T>`, `IReadOnlyCollection<T>`, `IReadOnlyList<T>`, `IImmutableList<T>` can't be used directly with `FluentDataGrid.ItemProvider`.

The above code will cause a compile time error:
```
Error CS0411 : The type arguments for method 'GridItemsProviderResult.From<TGridItem>(Icollection<TGridItem>, int)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

## 💁 Possible Solution

It doesn't seem like `GridItemsProviderResult<TGridItem>.Items` is mutated in FluentUI itself, so it should be possible to change it to `IEnumerable<T>`.  This will make `GridItemsProviderResult` more symmetric with `ItemsProviderResult` in `Microsoft.AspNetCore.Components.Web.Virtualization`.

Though this is a source-incompatible breaking change, so it may not be possible without a major version bump.

A more backward compatible solution is a new non-overloading method that accepts an `IEnumerable<T>` and tries to reuse the existing collection without duplicating it.

## 🔦 Context

Sometimes we want to display results returned by third party libraries whose type is outside of our control.  It would be nice if the response returned by such libraries can be supplied directly to `<FluentDataGrid>`.

Currently , we need to duplicate the data in-memory to get a compatible collection using `.ToList()`.

```csharp
    return GridItemsProviderResult.From(
        items: response.Items.ToList(),
        totalItemCount: response.TotalItemCount);
```

**Comment by vnbaaij** [comment]
As you say, this would be a major breaking change. We are not considering to do this at the moment. Also, we kept our implementation equal to how it is done in the Blazor QuickGrid. This is also not something we want to change.

Closing this as it is not actionable.
