### ISSUE TITLE
FluentDatePicker triggers onfocusout event before bind-value update

### ISSUE THREAD

**Issue by Sweetli1415926** [microsoft/fluentui-blazor#2552]
# 🐛 Bug Report

I've noticed that in the FluentDatePicker component, the onfocusout event is being triggered before the bind-value behavior updates the bound value. This is inconsistent with the typical behavior observed in other other components, where bind-value is expected to update the data model before the onfocusout event is fired. This discrepancy can cause issues when relying on the onfocusout event to process the latest bound value.

Is this the intended behavior for FluentDatePicker, or is it a bug that needs to be addressed?

I'm hoping for a functionality similar to CellEndEdit to handle this scenario. If such a feature doesn't currently exist, using onfocusout with additional flags to manage this seems to be the best workaround. Is this the most recommended approach?

## 💻 Repro or Code Sample

<FluentDatePicker @bind-Value=CurrentCarInfo.PickUpDateTime ReadOnly="@readOnly" Style="width:150px" @onfocusout="@(()=> CellEndEdit("PickUpDateTime"))" />
    <FluentTimePicker @bind-Value=CurrentCarInfo.PickUpDateTime ReadOnly="@readOnly" @onfocusout="@(()=> CellEndEdit("PickUpDateTime"))" />

 private async Task CellEndEdit(string columnName)
 {
     var newValue = CurrentCarInfo.GetType()?.GetProperty(columnName)?.GetValue(CurrentCarInfo);
//when the control is FluentDatePicker or FluentTimePicker the newValue still equal the old one
//...
 }

* .NET and Fluent UI Blazor library Version [e.g. 8.0.303 and 4.9.3]

**Comment by vnbaaij** [comment]
> Is this the intended behavior for FluentDatePicker, or is it a bug that needs to be addressed?

We have not looked at providing any functionality specific to `onfocusout`. Till this report, we have not had any remarks about it either. As our resources are limited, this is not something we have planned to work on.
 
> I'm hoping for a functionality similar to CellEndEdit to handle this scenario. If such a feature doesn't currently exist, using onfocusout with additional flags to manage this seems to be the best workaround. Is this the most recommended approach?

Yes, that seems like a valid approach.
