### ISSUE TITLE
fix: Cannot set `ValueChanged` without binding in `FluentNumberField`

### ISSUE THREAD

**Issue by denispaluca** [microsoft/fluentui-blazor#2554]
# 🐛 Bug Report

When using a `FluentNumberField` I want to set the `ValueChanged` callback manually. When trying to do this I get the compiler error:

> CS1503	Argument 2: cannot convert from 'method group' to 'Microsoft.AspNetCore.Components.EventCallback'	

## 💻 Repro or Code Sample

```c#
@page "/"

@using BlazorApp2.Pages
@using Microsoft.FluentUI.AspNetCore.Components

<FluentNumberField
    Value="@l"
    ValueChanged="@ChangeValue"
    Label="Number Field" />

@code {
    private long l;

    private void ChangeValue(long value)
    {
        l = value;
    }
}
```

## 🤔 Expected Behavior

I should be able to set the `ValueChanged` callback.

## 😯 Current Behavior

The compiler forbids me from setting the `ValueChanged` callback of the `FluentNumberField` component.

## 🔦 Context

I am trying to use `FluentNumberField` and manually control the changes to the property. These changes may contain things that I do not want to include in the setter of the property and they can also be `async`.

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser all
* .NET and Fluent UI Blazor library Version 8.0.7 and 4.7.2

**Comment by MarvinKlein1508** [comment]
Try add `TValue="long"` I would also recommend not using the `FluentNumberField` component at all because the underlying webcomponents has some nasty bugs. You can read more about it in #1345 

I would recommend using a vanilla `InputNumber` and apply FluentUI style to it.
https://github.com/microsoft/fluentui-blazor/issues/1345#issuecomment-2145145944

**Comment by vnbaaij** [comment]
Solution provided by @MarvinKlein1508 is correct. So is his advice about not using `FluentNumberField` btw,

Closing this as it was an issue in calling code
