### ISSUE TITLE
fix: ButtonClick toggel FluentAccordionItem in HeadingTemplate

### ISSUE THREAD

**Issue by UweLesta** [microsoft/fluentui-blazor#2573]
# 🐛 Bug Report

If I use a FluentButton inside a HeadingTemplate of a FluentAccordionItem a click on the Button also toggle (collaps or open) the AccordionItem. I'll try different approaches with ```@onclick:stopPropagation="true"```and ```onclick="event.stopPropagation()"```, but without success.

## 💻 Repro or Code Sample

```
@inherits FluentComponentBase
@page "/testpagemarkup"
@using FisBoxTools.BlazorUi.Components.Controls

<PageTitle>test page markup</PageTitle>
<h1>Test Page FluentAccordionItem HeadingTemplate with FluentButton</h1>

<FluentAccordionItem style="border-color:black">
	<HeadingTemplate>
		<div >
			<FluentButton IconStart="@(new Icons.Regular.Size16.ArrowClockwise())" Loading="@loading" OnClick="@LoadingAsync" Appearance="Appearance.Lightweight">
				Reload
			</FluentButton>
		</div>
		header
	</HeadingTemplate>
	<ChildContent>
		some text
		<hr />
		more text
	</ChildContent>
</FluentAccordionItem>

@code {
	bool loading = false;
	async Task<bool> LoadingAsync()
	{
		loading = true;
		await Task.Delay(2000);
		loading = false;
		return true;
	}
}
```

## 🤔 Expected Behavior

A click on the button should not toggel the FluentAccordionItem.

## 🌍 Your Environment

Winows, Blazor render mode interactive server, net 8

**Comment by vnbaaij** [comment]
The web component renders an accordion item as a button element. When embedding a `FluentButton` inside of it, you will get a button in a button and that is not valid HTML according to W3C. So want you want is not possible to do.
