### ISSUE TITLE
FR: Improve FluentTimePicker 🕒

### ISSUE THREAD

**Issue by dromerolovo** [microsoft/fluentui-blazor#2576]
I've noticed that the `FluentTimePicker` component use a native web component `<input type=time` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time. That would be the reason why the design theme has no effect on the overlay elements of the time picker.

![Screenshot 2024-08-23 162719](https://github.com/user-attachments/assets/be86e2c5-d409-4410-be27-7faba7951138)

What are the plans for `FluentTimePicker`? Could we develop a fluent component that don't rely on `<input type=time`, something similar to Fluent UI React `TimePicker` https://react.fluentui.dev/?path=/docs/compat-components-timepicker--docs?

![Screenshot 2024-08-23 170204](https://github.com/user-attachments/assets/81b92168-413a-417b-b420-64dc79b0630d)

**Comment by vnbaaij** [comment]
We have no plans to change the standard implementation we have currently. Looking at the MDN link and playing with the dev tools  bit, I see it is possible to get it to respond to a dark mode setting:
![image](https://github.com/user-attachments/assets/65d54303-2b6d-4b58-9c31-297ee7c03604)

I'll research if/how we can get it to behave like that on our side too. Closing this one as it s note really an issue (but more a discussion item)
