### ISSUE TITLE
fix: FluentSelect doesn't render properly when changing both Value and Items

### ISSUE THREAD

**Issue by jokerboy** [microsoft/fluentui-blazor#2578]
# 🐛 Bug Report

Have a FluentSelect component and a button click causes it to change both the Value and Items of the select. When this is done more than once, the FluentSelect no longer displays the selected item without clicking on the dropdown to show the list of items.

## 💻 Repro or Code Sample

Create a new project using the 'Fluent Blazor Web App' template. Replace the contents of the 'Counter.razor' file, in the Client project, with this.  Run the project, navigate to the 'Counter' page and click on 'Click me' several times.

```
@page "/counter"
@rendermode InteractiveAuto

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<div role="status" style="padding-bottom: 1em;">
    Current count: <FluentBadge Appearance="Appearance.Neutral">@currentCount</FluentBadge>
</div>

<FluentButton Appearance="Appearance.Accent" @onclick="IncrementCount">Click me</FluentButton>
<FluentSelect Items="@FruitList" Value="@Fruit" />
<FluentTextArea Value="@Fruit"/>

@code {
    private int currentCount = 0;

    private string Fruit = "Orange";
    private List<string> FruitList = new List<string>() { "Apple", "Grape", "Orange", "Kiwi" };

    private void IncrementCount()
    {
        currentCount++;
        if (Fruit.Equals("Orange"))
        {
            FruitList = new List<string>() { "Watermelon", "Blueberry", "Lemon", "Peach" };
            Fruit = "Blueberry";
        }
        else
        {
            FruitList = new List<string>() { "Apple", "Grape", "Orange", "Kiwi" };
            Fruit = "Orange";
        }


    }
}
```

## 🤔 Expected Behavior

The value of the FluentSelect and the list of items should change each click, alternating between 'Orange' being selected and displayed on the FluentSelect control and 'Blueberry'.

## 😯 Current Behavior

The first time the 'Click me' button is clicked, the FluentSelect properly shows 'Blueberry' as the selected item. However, subsequent clicks show the FluentSelect with no text visible on the component but when clicking on the drop down arrow, I can see the proper items and that the correct item is selected.

![image](https://github.com/user-attachments/assets/aa6cf2a4-1b8f-4576-9b74-3526ca431fd2)
![image](https://github.com/user-attachments/assets/859c9586-98e7-458c-983b-3421ac0c1bd3)

I will note that the FluentCombobox component (simply change FluentSelect to FluentCombobox) works properly.

## 🔦 Context

I have a requirement to dynamically change the list of options in a drop down box depending on the value of other components.

## 🌍 Your Environment

* OS & Device: Windows 11 
* Browser Edge and Firefox are all I've tested.
* .NET 8.0.8 and Fluent UI Blazor library Version 4.9.3

**Comment by vnbaaij** [comment]
It is a timing issue. The underlying web component needs to have a tiny amount of time to 'catch up' with the items being changed. If you change the `IncrementCount` to

```
private async Task IncrementCountAsync()
{
    currentCount++;
    if (Fruit.Equals("Orange"))
    {
        FruitList = new List<string>() { "Watermelon", "Blueberry", "Lemon", "Peach" };
        await Task.Delay(1);
        Fruit = "Blueberry";
    }
    else
    {
        FruitList = new List<string>() { "Apple", "Grape", "Orange", "Kiwi" };
        await Task.Delay(1);
        Fruit = "Orange";
    }
}
```

It will work then: 
![image](https://github.com/user-attachments/assets/334a3ccf-a900-43e3-912e-5e34b97dee9e)

**Comment by jokerboy** [comment]
This "work around" does indeed solve it for my simple example.

However, for my application which relies on getting the select list and selected item via an Http api, it still doesn't work.

My guess is that the timing intricacies are more complex than a simple Task.Delay can fix.

**Comment by vnbaaij** [comment]
I'm not sure that the timing is very different. 

Once your API call is done and the data is returned (which I assume is not like thousands of options) your situation should not be really different than in this simple example. You set the items, give the component some room to catch up and then set the selected item.
