### ISSUE TITLE
fix: FluentRadio cannot be focused from javascript in  MAUI/Blazor application

### ISSUE THREAD

**Issue by gstoro** [microsoft/fluentui-blazor#2588]
# 🐛 Bug Report

We have a requirement where the first FluentRadio has to be focused in a FluentRadioGroup when user has not made any selection , this has to be at runtime and we are using javascript code to perform that action and we are seeing focus() is not happening , however .click() on FluentRadio is working.

## 💻 Repro or Code Sample

I have attached sample ready-to-run reproduction code for investigating the issue.

## 🤔 Expected Behavior

focus() call in Javascript should focus the radio button

## 😯 Current Behavior

focus() is not focusing the element . You can see in below screenshot that the Radio button is not having the black highlight :

![image](https://github.com/user-attachments/assets/fd44f2c4-a79c-4891-a709-e2cd140dc8d9)

Also when you run the application and just try to submit the Form with Enter Key on Keyboard it highlights Radiobutton as below: , but the selection afterwards is not saved into object; 
![image](https://github.com/user-attachments/assets/a168e7db-47d4-40cd-97c0-b2af7c15990d)

## 🔦 Context

We have a requirement to focus the first invalid element in screen , It happened to be Radio button Group  which needs to be focused with first Radiobutton highlighted and this is not happening

## 🌍 Your Environment

* OS & Device: Windows 
* Browser [N/A , this is MAUI APP]
* .NET 8.0 
* Fluent UI Blazor library Version [4.9.3]
[FluentRadioButtonFocusIssue.zip](https://github.com/user-attachments/files/16769396/FluentRadioButtonFocusIssue.zip)

This was similar to bug: https://github.com/microsoft/fluentui-blazor/issues/2212
I have attached ready-to-run reprodcution code.

**Comment by vnbaaij** [comment]
I have no idea why you would want to use Javascript for this as I think it can be done with only Blazor code.

Change the `FluentRadioGroup` line to:

```
<FluentRadioGroup Name="Suffix" @bind-Value="PersonData.Suffix" Orientation="Orientation.Vertical">
```

and add to `OnInitialized`
```
 if (PersonData.Suffix == null)
 {
     PersonData.Suffix = SuffixList[0];
 }
```

**Comment by gstoro** [comment]
- We went the route of Javascript as we need to  focus the element which is in error dynamically. So if a form has like 50 controls we need to find first element which is  invalid and focus that element . this logic works for all elements except for radio button if this is the first element which is invalid.
- Also I see you mentioned to add code in OnInitialized method to default radio option to first but we do not want that , we want user to select the option.

**Comment by vnbaaij** [comment]
Ok, clear. So just focus and not actually setting a value.

Have you tried setting focus to the radio group instead of seeing it to the first item in the group?

**Comment by gstoro** [comment]
Yes . I have tried and is not working.
