### ISSUE TITLE
fix: Cannot Reset Stream to Position=0 in FluentInputFileEventArgs 

### ISSUE THREAD

**Issue by Kratos-T** [microsoft/fluentui-blazor#2592]
# 🐛 Bug Report

In order to pass the uploaded file to my internal Api for saving the file I need to reset the stream to Position=0, otherwise when trying to download it, I get a file with Size = 0 Mb
I seems that FluentInputFileEventArgs object  on the OnCompletedAsync Event in the FluentInputFile componenent does not reset the file position to 0
So any attemt to do inputFile.Stream.Position=0;
or inputFile.Stream.Seek(0, SeekOrigin.Begin);
triggers System.NotSupportedException: , I've tried to do a copy to a memoryStream but cannot make the copy of the file either, it's behaving like the file is locked
## 💻 Repro or Code Sample

 ```
   <FluentInputFile @ref="@myFileByStream"
                     Class=@(CssClass + (progressOngoing ? " has-progress" : string.Empty))
                     Disabled=_disabledField
                     AnchorId="@Id"
                     Id="@(DragDropZoneVisible ? Id : "PLACEHOLDER")"
                     Mode=InputFileMode.Stream
                     DragDropZoneVisible=@DragDropZoneVisible
                     Multiple
                     MaximumFileCount=MaxFiles
                     MaximumFileSize="@(10*1024*1024)"
                     Accept=@accept
                     OnCompleted=OnCompletedAsync
                     OnFileUploaded=OnFileUploadedAsync
                     ProgressPercentChanged=ProgressPercentChanged>
        <ChildContent>
            @ChildContent
        </ChildContent>

        <ProgressTemplate>
            @if (progressPercent > 0)
            {
                <FluentProgress Min="0" Max="100" Value="@progressPercent" Color="@progressColor" />
            }
            @if (!string.IsNullOrEmpty(progressTitle))
            {
                <FluentLabel Alignment="HorizontalAlignment.Center" Style=@($"color: {progressColor};")>
                    @progressTitle
                </FluentLabel>
            }
        </ProgressTemplate>
    </FluentInputFile>
```

```
// in the upload component
private async Task OnCompletedAsync(IEnumerable<FluentInputFileEventArgs> files)
{
    _ = await ActionExecution.ExecuteAsync(async () =>
    {
        UpdateProgressTitle();

        if (Files.IsNullOrEmpty())
            return;

        // upload files return model add ids
        var uploadResult = await documentService.UploadDocumentAsync(Files.ToArray());
        InputFileModel[]? result = default;
        if (InputFiles.IsNullOrEmpty())
            result = uploadResult;
        else
        {
            var mergedResult = new List<InputFileModel>();
            mergedResult.AddRange(InputFiles!);
            mergedResult.AddRange(uploadResult);
            result = mergedResult.ToArray();
        }

        await EndUploadAsync();

        // reset
        Files = new List<InputFileModel>();
        InputFiles = result;
        await InputFilesChanged.InvokeAsync(result);
        await OnChange.InvokeAsync(new ChangeEventArgs { Value = InputFiles });
    }, toaster);

    await EndUploadAsync();
}

private async Task OnFileUploadedAsync(FluentInputFileEventArgs file)
{
    bool endUpload = false;
    if (IsValidContentType(file))
    {
        UpdateProgressTitle();

        var allFiles = Files.ToList();
        if (!InputFiles.IsNullOrEmpty())
            allFiles.AddRange(InputFiles!);

        // check that max file uploaded has not been exceeded
        if (allFiles.Count < MaxFiles)
        {
            var sha256Hash = (await sha256.ComputeHashAsync(file.Stream!)).ToBase64String();

            if (!allFiles.Any(f => f.Sha256 == sha256Hash))
            {
                var uploadedFile = new InputFileModel
                    {
                        Name = file.Name,
                        ContentType = file.ContentType,
                        Size = file.Size,
                        Stream = file.Stream,
                        Sha256 = sha256Hash
                    };

                Files.Add(uploadedFile);
            }
            else
            {
                toaster.AddInfo(string.Format(i18n["file-upload.validation.file-already-uploaded"], file.Name));
                endUpload = true;
            }
        }
        else
        {
            toaster.AddInfo(string.Format(i18n["file-upload.validation.max-file-exceeded"], MaxFiles));
            endUpload = true;
        }
    }
    else
    {
        toaster.AddInfo(string.Format(i18n["file-upload.validation.file-type-forbidden"], file.Name));
        endUpload = true;

    }

    if (endUpload)
        await EndUploadAsync();

}

// my service
public async Task<InputFile[]> UploadDocumentAsync(InputFile[] inputFiles)
{
    var result = new List<InputFile>();
    foreach (InputFile inputFile in inputFiles)
    {
        if (inputFile.Stream != null )
        {

            StreamReader sr = new StreamReader(inputFile.Stream);
            await sr.ReadToEndAsync();
            inputFile.Stream.Seek(0, SeekOrigin.Begin); // my code crashes here
            await sr.ReadToEndAsync(); 
            //var resu = await CopyStreamToMemory(inputFile.Stream);
            var uploadResult = await documentApi.FilePOSTAsync(new FileParameter(sr.BaseStream, inputFile.Name, inputFile.ContentType));
            if (uploadResult != null)
            {
                inputFile.Id = uploadResult;
                inputFile.Stream = null;
                result.Add(inputFile);
            }
        }
    }
    return [.. result];
}
```

## 🤔 Expected Behavior

I would like to be able to copy my stream and have a lenght > 0

## 😯 Current Behavior

When doing a copy to a memoryStream I have a lenght = 0 so basically a empty file

## 🌍 Your Environment

* OS & Device: Windows
* Browser Google Chrome
* .NET 8 and Fluent UI Blazor library Version 4.9.3

**Comment by vnbaaij** [comment]
Have you seen the examples on the demo site (https://www.fluentui-blazor.net/InputFile)?
This is not my expertise area, but it seems you are trying to do too much with copying both after a file is done uploading and after everything is uploaded.

Also, I see in
```
if (Files.IsNullOrEmpty())
            return;
```

and also other places `Files` being used but I don't see this declared anywhere. Is the code you supplied ready-to-run? If not, we can not/will not take this issue in.

**Comment by Kratos-T** [comment]
Yes I did saw the demo, I can provide the full code

```
namespace Application;
public class InputFile
{
    public string Id { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;

    public long Size { get; set; } = 0;

    public string ContentType { get; set; } = string.Empty;

    [JsonIgnore]
    public Stream? Stream { get; set; }

    /// <summary>
    /// SHA256 of the file, stored as Base64
    /// for comparing uploaded file and avoid duplicates
    /// </summary>
    public string? Sha256 { get; set; }
}
```


@using Application
@using System.Security.Cryptography

@inject IDocumentService documentService
@inject IJSRuntime JSRuntime
@inject ToasterService toaster;

<div class="h-100">
    <FluentInputFile @ref="@myFileByStream"
                     Class=@(CssClass + (progressOngoing ? " has-progress" : string.Empty))
                     Disabled=_disabledField
                     AnchorId="@Id"
                     Id="@(DragDropZoneVisible ? Id : "PLACEHOLDER")"
                     Mode=InputFileMode.Buffer
                     DragDropZoneVisible=@DragDropZoneVisible
                     Multiple
                     MaximumFileCount=MaxFiles
                     MaximumFileSize="@(10*1024*1024)"
                     Accept=@accept
                     OnCompleted=OnCompletedAsync
                     OnProgressChange=OnFileUploadedAsync
                     ProgressPercentChanged=ProgressPercentChanged>
        <ChildContent>
            @ChildContent
        </ChildContent>

        <ProgressTemplate>
            @if (progressPercent > 0)
            {
                <FluentProgress Min="0" Max="100" Value="@progressPercent" Color="@progressColor" />
            }
            @if (!string.IsNullOrEmpty(progressTitle))
            {
                <FluentLabel Alignment="HorizontalAlignment.Center" Style=@($"color: {progressColor};")>
                    @progressTitle
                </FluentLabel>
            }
        </ProgressTemplate>
    </FluentInputFile>
</div>
@code {

    FluentInputFile? myFileByStream = default!;
    private const string accept = "application/pdf,image/jpeg,image/png,image/jpg";
    private static string[] acceptedMimeTypes => accept.Split(",");
    List<InputFileModel> Files = new();

    bool fileIsUploading = false;

    int? progressPercent;
    string? progressTitle;
    bool progressDisplayed = true;
    bool progressOngoing => progressDisplayed && (progressPercent > 0 || !string.IsNullOrEmpty(progressTitle));
    string progressColor => progressTitle == FluentInputFile.ResourceLoadingCompleted ? "green" : "blue";


    [Parameter]
    public RenderFragment? ChildContent { get; set; }

    [Parameter, EditorRequired]
    public string Id { get; set; } = string.Empty;

    [Parameter]
    public bool Disabled { get; set; }

    [Parameter]
    public string? CssClass { get; set; }

    [Parameter]
    public int MaxFiles { get; set; } = 10;

    [Parameter]
    public bool ShortLoadingMessages { get; set; } = false;

    [Parameter]
    public InputFileModel[]? InputFiles { get; set; }

    [Parameter]
    public bool DragDropZoneVisible { get; set; } = true;

    [Parameter]
    public EventCallback<InputFileModel[]?> InputFilesChanged { get; set; }

    [Parameter]
    public EventCallback<ChangeEventArgs> OnChange { get; set; }

    private bool _disabledField => Disabled || fileIsUploading;

    private SHA256 sha256 = SHA256.Create();

    protected override void OnInitialized()
    {
        //File upload
        FluentInputFile.ResourceLoadingBefore = GetLoadingMessage("loading-before");
        FluentInputFile.ResourceLoadingCompleted = GetLoadingMessage("loading-completed");
        FluentInputFile.ResourceLoadingCanceled = GetLoadingMessage("loading-canceled");
        FluentInputFile.ResourceLoadingInProgress = GetLoadingMessage("loading-inprogress");

        base.OnInitialized();
    }

    public async Task DeleteUploadedFileAsync(InputFileModel? inputFileModel)
    {
        if (inputFileModel is null)
        {
            toaster.AddError(@i18n["file-upload.validation.not-found-delete"]);
            return;
        }

        var result = await ActionExecution.ExecuteAsync(async () =>
        {
            await documentService.DeleteUploadedDocumentAsync(inputFileModel);
            InputFiles = InputFiles?.Where(f => f.Id != inputFileModel!.Id).ToArray();
            await InputFilesChanged.InvokeAsync(InputFiles);
            await OnChange.InvokeAsync(new ChangeEventArgs { Value = InputFiles });
        },
        toaster,
        // these are temp file we force the delete anyways in case of Api Error
        async () =>
        {
            InputFiles = InputFiles?.Where(f => f.Id != inputFileModel!.Id).ToArray();
            await InputFilesChanged.InvokeAsync(InputFiles);
            await OnChange.InvokeAsync(new ChangeEventArgs { Value = InputFiles });
        });

        if (result)
            toaster.AddSuccess(string.Format(i18n["file-upload.validation.success-delete"], inputFileModel!.Name));

        await Task.Delay(1);
        StateHasChanged();
    }

    public async Task DownloadUploadedFileAsync(InputFileModel? inputFile)
    {
        if (inputFile is null)
        {
            toaster.AddError(@i18n["file-upload.validation.not-found"]);
            return;
        }

        await ActionExecution.ExecuteAsync(async () =>
        {
            var result = await documentService.DownloadUploadedDocumentAsync(inputFile);
            using var streamReference = new DotNetStreamReference(stream: result.Stream);

            await JSRuntime.InvokeVoidAsync("downloadFileFromStream", $"{inputFile.Name}", streamReference);

        }, toaster);
    }


    private async Task OnCompletedAsync(IEnumerable<FluentInputFileEventArgs> files)
    {
        _ = await ActionExecution.ExecuteAsync(async () =>
        {
            UpdateProgressTitle();

            if (Files.IsNullOrEmpty())
                return;

            // upload files return model add ids
            // Files.ForEach(f =>
            // {
            //     f.Stream = files.FirstOrDefault(x => x.Name == f.Name && x.ContentType == f.ContentType)?.Stream;
            // });
            var uploadResult = await documentService.UploadDocumentAsync(Files.ToArray());
            InputFileModel[]? result = default;
            if (InputFiles.IsNullOrEmpty())
                result = uploadResult;
            else
            {
                var mergedResult = new List<InputFileModel>();
                mergedResult.AddRange(InputFiles!);
                mergedResult.AddRange(uploadResult);
                result = mergedResult.ToArray();
            }

            await EndUploadAsync();

            // reset
            Files = new List<InputFileModel>();
            InputFiles = result;
            await InputFilesChanged.InvokeAsync(result);
            await OnChange.InvokeAsync(new ChangeEventArgs { Value = InputFiles });
        }, toaster);

        await EndUploadAsync();
    }

    public async Task<MemoryStream> ToMemoryStreamAsync(FluentInputFileBuffer buffer)
    {
        using var stream = new MemoryStream(buffer.Data);
        return stream;
    }

    private async Task OnFileUploadedAsync(FluentInputFileEventArgs file)
    {
        bool endUpload = false;
        if (IsValidContentType(file))
        {
            UpdateProgressTitle();

            var allFiles = Files.ToList();
            if (!InputFiles.IsNullOrEmpty())
                allFiles.AddRange(InputFiles!);

            // check that max file uploaded has not been exceeded
            if (allFiles.Count < MaxFiles)
            {
                var stream = await ToMemoryStreamAsync(file.Buffer);
                var sha256Hash = (await sha256.ComputeHashAsync(stream)).ToBase64String();

                if (!allFiles.Any(f => f.Sha256 == sha256Hash))
                {
                    var uploadedFile = new InputFileModel
                        {
                            Name = file.Name,
                            ContentType = file.ContentType,
                            Size = file.Size,
                            Stream = stream,
                            Sha256 = sha256Hash
                        };

                    Files.Add(uploadedFile);
                }
                else
                {
                    toaster.AddInfo(string.Format(i18n["file-upload.validation.file-already-uploaded"], file.Name));
                    endUpload = true;
                }
            }
            else
            {
                toaster.AddInfo(string.Format(i18n["file-upload.validation.max-file-exceeded"], MaxFiles));
                endUpload = true;
            }
        }
        else
        {
            toaster.AddInfo(string.Format(i18n["file-upload.validation.file-type-forbidden"], file.Name));
            endUpload = true;

        }

        if (endUpload)
            await EndUploadAsync();

    }

    private bool IsValidContentType(FluentInputFileEventArgs file)
        => acceptedMimeTypes.Contains(file.ContentType);


    private void ProgressPercentChanged(int percent)
    {
        if (percent > 0)
        {
            progressDisplayed = true;
            fileIsUploading = true;
        }

        progressPercent = percent;
        UpdateProgressTitle();
    }

    private async Task EndUploadAsync()
    {
        fileIsUploading = false;
        UpdateProgressTitle();

        // wait 3 sec and remove progress
        await Task.Delay(3000);
        progressDisplayed = false;
    }

    private string GetLoadingMessage(string key)
        => i18n[$"file-upload.{key}" + (ShortLoadingMessages ? "-short" : string.Empty)];

    private void UpdateProgressTitle()
        => progressTitle = myFileByStream?.ProgressTitle;
}

**Comment by vnbaaij** [comment]
Sorry, but this is still not code we can run (`Bisa.App.Shared.Enums.Color`, `IDocumentService`, @i18n[])

**Comment by Kratos-T** [comment]
Can you now i tried to remove all my internal dependecies

**Comment by dvoituron** [comment]
Hello, I'm on vacation at the moment... I can take a look in a few days.

**Comment by Kratos-T** [comment]
Hello, I managed to resolve my issue by copy byte per byte my Stream wich is not seekable (only the property canRead= true) to a MemoryStream wich by definition is seekable (canSeek = true)

`
private async Task OnFileUploadedAsync(FluentInputFileEventArgs file)
{
    bool endUpload = false;
    if (IsValidContentType(file))
    {
        UpdateProgressTitle();

        var allFiles = Files.ToList();
        if (!InputFiles.IsNullOrEmpty())
            allFiles.AddRange(InputFiles!);

        // check that max file uploaded has not been exceeded
        if (allFiles.Count < MaxFiles)
        {
            var outputStream = new MemoryStream();
            await CopyStreamAsync(file.Stream!, outputStream); // I Addded this

            var sha256Hash = (await sha256.ComputeHashAsync(outputStream)).ToBase64String();
            if (!allFiles.Any(f => f.Sha256 == sha256Hash))
            {
                var uploadedFile = new InputFileModel
                {
                    Name = file.Name,
                    ContentType = file.ContentType,
                    Size = file.Size,
                    Stream = outputStream,
                    Sha256 = sha256Hash
                };

                Files.Add(uploadedFile);
            }
            else
            {
                toaster.AddInfo(string.Format(i18n["file-upload.validation.file-already-uploaded"], file.Name));
                endUpload = true;
            }
        }
        else
        {
            toaster.AddInfo(string.Format(i18n["file-upload.validation.max-file-exceeded"], MaxFiles));
            endUpload = true;
        }
    }
    else
    {
        toaster.AddInfo(string.Format(i18n["file-upload.validation.file-type-forbidden"], file.Name));
        endUpload = true;
    }

    if (endUpload)
        await EndUploadAsync();

}

private static async Task CopyStreamAsync(Stream input, Stream output)
{
    byte[] buffer = new byte[32768];
    int read;
    while ((read = await input.ReadAsync(buffer.AsMemory(0, buffer.Length))) > 0)
        await output.WriteAsync(buffer.AsMemory(0, read));

    await input.DisposeAsync();
}

// this is my Service
public async Task<InputFile[]> UploadDocumentAsync(InputFile[] inputFiles)
{
    var result = new List<InputFile>();
    foreach (InputFile inputFile in inputFiles)
    {
        if (inputFile.Stream != null)
        {

            if (inputFile.Stream.CanSeek)
                inputFile.Stream.Position = 0; // this is necessary to correctly pass the stream to my api, I had this property before set to the size of the file wich lead to a 0 Mb file transfer

            var uploadResult = await documentApi.FilePOSTAsync(new FileParameter(inputFile.Stream, inputFile.Name, inputFile.ContentType));
            if (uploadResult != null)
            {
                inputFile.Id = uploadResult;
                inputFile.Stream = null;
                result.Add(inputFile);
            }
        }
    }
    return [.. result];
}

`
