### ISSUE TITLE
fix: Vertical tabs overflow without showing the users that more tabs are visible

### ISSUE THREAD

**Issue by trondjun** [microsoft/fluentui-blazor#2602]
# 🐛 Bug Report

An application with vertical tabs inside horizontal tabs has an overflow issue. This might appen if the vertical tabs are placed outside the horizontal tabs too, I have not tested that.

The problem is visible when the window size is made smaller, and the text for the given tab "overflows".

## 💻 Repro or Code Sample

When the page has enough width, all 4 tabs are visible
![image](https://github.com/user-attachments/assets/2ba55308-24ba-4d5b-a2f1-cabe0e554f8c)

Window is smaller, two tabs are gone:
![image](https://github.com/user-attachments/assets/f2f304f3-dec6-405e-b182-2f346061c770)

Code for these tabs:
```
<div style="min-height:600px">
<FluentTabs Orientation="Orientation.Vertical" >
        <FluentTab LabelClass="spaceRight10" Id="students-tab-1">
        <Header>
            Elever
        </Header>
        <Content>
            <EnterStudentsTab SaveReportEvent="@SaveReportEvent" ReportChangedEvent="@ReportChangedEvent" School="@School" LevelsAtSchool="@LevelsAtSchool"></EnterStudentsTab>
        </Content>
    </FluentTab>
        <FluentTab LabelClass="spaceRight10" Id="students-tab-2">
        <Header>
            Alenevedtak
        </Header>
        <Content>
            <StudentResolutionsTab SaveReportEvent="@SaveReportEvent" ReportChangedEvent="@ReportChangedEvent" School="@School" LevelsAtSchool="@LevelsAtSchool"></StudentResolutionsTab>
          </Content>
    </FluentTab>
        <FluentTab LabelClass="spaceRight10" Id="students-tab-3">
        <Header>
            Gruppevedtak
        </Header>
        <Content>
            <ResolutionGroupTab SaveReportEvent="@SaveReportEvent" ReportChangedEvent="@ReportChangedEvent" ReportingSchool="@School"></ResolutionGroupTab>
        </Content>
    </FluentTab>
        <FluentTab LabelClass="spaceRight10" Id="students-tab-4">
        <Header>
            Eksterne elever
        </Header>
        <Content>
            <FromOtherMuncipalitiesTab SaveReportEvent="@SaveReportEvent" ReportChangedEvent="@ReportChangedEvent" ReportingSchool="@School"></FromOtherMuncipalitiesTab>         
        </Content>
    </FluentTab>    
 </FluentTabs>

</div>
```

## 🤔 Expected Behavior

I believe there should be a notification showing the user that two tabs are missing. Equal the horizontal tab when the window becomes to narrow:
![image](https://github.com/user-attachments/assets/185d090a-8716-476d-918b-9ca8afcb1461)

## 😯 Current Behavior
The vertical tabs just disappears without any notification or info to the user.

## 💁 Possible Solution
Im not sure what would be the best solution, but for vertical tabs like this, maybe just let the content overflow the table?
Or show the "more tabs button" (the little square with a number and +)

If non of these are possible, it's kind of hard to make sure users wouldn't miss content. 

## 🌍 Your Environment

.Net 8
Fluent Blazor 4.9.3

**Comment by vnbaaij** [comment]
Hi,

When trying a similar setup (vertical tabs inside of horizontal tabs) in one of the demo site examples, I get this:

![image](https://github.com/user-attachments/assets/9b2ed7f2-4854-4e8c-a80f-950ac272e2ef)

We can't run the code you posted and from the screenshot I see, I'd say there is plenty of room to display the missing two tabs. I assume there is something in you CSS that is causing this. Don't think there is a lot we can do here.
