### ISSUE TITLE
fix: Dynamic FluentTab creation does not always completely select the new tab

### ISSUE THREAD

**Issue by Nuthin2do** [microsoft/fluentui-blazor#2608]
# 🐛 Bug Report

Playing around with the dynamic tab creation -> https://www.fluentui-blazor.net/Tabs#dynamic i noticed that after creation the tab is not "completely" selected. The font is bold, but the navigation indicator isn't located at the new tab. Like this ->
<img width="789" alt="image" src="https://github.com/user-attachments/assets/e7869bfd-407b-40f9-b83a-57c12b0d3d39">

## 🤔 Expected Behavior

I would expect that both the font and the navigation indicator (or however it is called) are at the newly created tab.

## 😯 Current Behavior

See the bug report. Font is bold and the navigation indicator goes to the newly created tab only if it starts from January, from any other tab it stops at the previously created tab.

## 🌍 Your Environment

* OS & Device: Windows
* Browser Google Chrome

**Comment by vnbaaij** [comment]
This is am error in the underlying web component that we can't fix. Has been reported a number of times already. See for example #2536 and #2043.
