### ISSUE TITLE
fix: Missing "slot" property in the generated HTML of nested components when asynchronously loading data for the component

### ISSUE THREAD

**Issue by bokidonev** [microsoft/fluentui-blazor#2619]
# 🐛 Bug Report
If you have a blazor component that needs to load data from somewhere, and you do that in the `OnInitializedAsync` lifecycle method, and this blazor component is **used** in another component - it cannot be seen in the page.

Some extra information and findings:
Inspecting the generated HTML, I can see that all the elements are there with the correct content, it's just that they are missing the "slot" property. As I was working with "FluentTabs", they were missing slot="tab" and slot="tabpanel" properties.

If I add them manually in the inspector - the elements will appear immediately.
If I refresh the page after the initial load - the elements will be shown on the screen.

## 💻 Repro or Code Sample

Simple repo which reproduces the issue: https://github.com/bdn-mca/BlazorFluentUIAsyncBug

You can also reproduce it yourself:
Create a brand new Blazor application, with Authentication none, configured for https, Interactive render mode Auto, Interactivity location Per page/component, and include the sample pages.

Create a new Blazor component called `WeatherFrame.razor` in the "Layout" folder with the following content.
Have the `await Task.Delay(1500);` as well to simulate loading data.

```
@using Microsoft.FluentUI.AspNetCore.Components

<FluentTabs>
    <FluentTab Label="Weather">
        @foreach (var forecast in forecasts)
        {
            <tr>
                <td>@forecast.Date.ToShortDateString()</td>
                <td>@forecast.TemperatureC</td>
                <td>@forecast.TemperatureF</td>
                <td>@forecast.Summary</td>
            </tr>
        }
    </FluentTab>

    <FluentTab Label="Weather 2">
        @foreach (var forecast in forecasts)
        {
            <tr>
                <td>@forecast.Date.ToShortDateString()</td>
                <td>@forecast.TemperatureC</td>
                <td>@forecast.TemperatureF</td>
                <td>@forecast.Summary</td>
            </tr>
        }
    </FluentTab>

    <FluentTab Label="Weather 3">
        @foreach (var forecast in forecasts)
        {
            <tr>
                <td>@forecast.Date.ToShortDateString()</td>
                <td>@forecast.TemperatureC</td>
                <td>@forecast.TemperatureF</td>
                <td>@forecast.Summary</td>
            </tr>
        }
    </FluentTab>
</FluentTabs>

@code {
    private WeatherForecast[] forecasts = [];

    protected override async Task OnInitializedAsync()
    {
        // Simulate asynchronous loading to demonstrate streaming rendering
        await Task.Delay(1500);

        var startDate = DateOnly.FromDateTime(DateTime.Now);
        var summaries = new[] { "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching" };
        forecasts = Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = startDate.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = summaries[Random.Shared.Next(summaries.Length)]
            }).ToArray();
    }

    private class WeatherForecast
    {
        public DateOnly Date { get; set; }
        public int TemperatureC { get; set; }
        public string? Summary { get; set; }
        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
    }
}
```

Use this new component in the `Weather.razor` component:
```
@page "/weather"
@using BlazorFluentUILoadTest.Components.Layout
@using Microsoft.FluentUI.AspNetCore.Components
@attribute [StreamRendering]

<PageTitle>Weather</PageTitle>

<WeatherFrame />

@code {
}
```

Start the app.
Open the Weather menu.

## 🤔 Expected Behavior
Tabs are visible initially, as well as after refreshing the page.

## 😯 Current Behavior
You see the tabs for 1.5 seconds (the amount of delay), and then they disappear. Same thing happens if you load data from database for example.
Refresh the page, or manually add the `slot` properties mentioned above, and they will appear.

## 💁 Possible Solution
For now, switching to synchronous loading of data works for me.
That is, instead of `OnInitializedAsync`, override the `OnInitialized` method and load data synchronously.

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser Microsoft Edge, Google Chrome
* .NET 8;
* Microsoft.FluentUI.AspNetCore.Components 4.9.3;
* Microsoft.AspNetCore.Components.WebAssembly.Server 8.0.8;

**Comment by vnbaaij** [comment]
Hmm, interesting... I think the title is perhaps a bit to broad and that this issue manifests when using tabs specifically. 

So looking more closely at that, it does behave strangely and the slot indicators are indeed not there after loading the data.

What I tried to solve this is to add those slot indicators to the component by default. That does not have any ill side effects as the web components script detects them and does not re-add them again. If does not however have the desired effect. Now after getting the data is done, it looks like this:

![image](https://github.com/user-attachments/assets/564bd003-b1de-4032-912a-c979265b08c3)

After clicking around on the tabs a bit, that issue resolves itself and display looks like it should. No idea yet why that is happening. More investigation is needed...

**Comment by vnbaaij** [comment]
I investigated some more and it looks like an issue with the underlying web components. We won't see any important change/fixes for v2 anymore so we can't change this behavior unfortunately.

Closing this as it is not actionable from our side
