### ISSUE TITLE
fix: TopCorner parameter in FluentProfileMenu doesnt apply style

### ISSUE THREAD

**Issue by badrimichael** [microsoft/fluentui-blazor#2621]
# 🐛 Bug Report

Regression of this issue? https://github.com/microsoft/fluentui-blazor/issues/1997

Setting "TopCorner" to "true" on "FluentProfileMenu" does not apply the style that forces the positioning of the popup [here](https://github.com/microsoft/fluentui-blazor/blob/main/src/Core/Components/ProfileMenu/FluentProfileMenu.razor.css#L17)

## 💻 Repro or Code Sample
Occurs when using `Microsoft.FluentUI.AspNetCore.Components` & Icons version `4.9.3`, simply downgrading the packages to `4.7.1` fixes the issue. Can't attach a screenshot due to network policy here :/

The below component is the topmost element of my app.

```html
<FluentLayout>
    <FluentHeader Style="height: 48px; background: var(--neutral-layer-4); color: var(--neutral-foreground-rest);">
        <FluentSpacer />
        <FluentProfileMenu Image="@(new Icons.Regular.Size48.Person().ToDataUri())"
                           TopCorner="true">
            <HeaderTemplate>
                    <FluentButton Appearance="@Appearance.Accent">Sign In</FluentButton>
            </HeaderTemplate>
            <ChildContent>
            </ChildContent>
            <FooterTemplate>
            </FooterTemplate>
        </FluentProfileMenu>
    </FluentHeader>
</FluentLayout>
```

**Comment by vnbaaij** [comment]
Yes, it is indeed a regression. Later commits rearranged the divs, so ::deep used to solve this does not work anymore. We will pick this up.

**Comment by dvoituron** [comment]
The PR #2632 will fix that, in the next Release.
