### ISSUE TITLE
When the Fluent UI Grid is very long, it cannot fully render the background color and grid lines for the hidden sections

### ISSUE THREAD

**Issue by javiercn** [microsoft/fluentui-blazor#2625]
---
**Issue moved from dotnet/aspnetcore#57721**
- Please respond to @YJFSS.

---

_From @YJFSS on Friday, September 6, 2024 3:25:17 AM_

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

错误如下：
![G1](https://github.com/user-attachments/assets/9fd74305-b96f-41af-94f8-7e638acd4cf8)
![G1](https://github.com/user-attachments/assets/063a6ec9-02e9-436a-b2e9-252858479e64)

### .NET Version

NETCORE 8.0

**Comment by vnbaaij** [comment]
Hi @YJFSS,

We use a template for submitting issues and we ask you to include ready-to-run reproduction code (project/repo). Please see our standard reply below:

---

Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

**Help us to help you. Thanks.**
