### ISSUE TITLE
fix: Combobox hides behind the other elements in EditForm

### ISSUE THREAD

**Issue by MatejMa2ur** [microsoft/fluentui-blazor#2629]
# 🐛 Bug Report

Combobox **works fine** until I search for items than it looks like it's z-index get's behind the other elements in the EditForm.
<img width="253" alt="image" src="https://github.com/user-attachments/assets/be290694-ddcb-41c1-bac7-399ae1f163c6">

Sorry I can't show you more emails, but it will go behind the other fields.

## 💻 Repro or Code Sample

Code:
```csharp

<CustomCreateForm T="CreateTestAssignmentDto"
                  PostUrl="/Admin/TestAssignment"
                  EditUrl=@($"/Template/{Id}?Tab=Assign")
                  Validator=@Validator
                  Object="CreateTestAssignmentDto">
    <div class="mb-3">
        Užívateľ:
        <FluentCombobox Items="Users"
                        TOption="UserDto"
                        OptionValue="t => t.Id.ToString()"
                        OptionText="t => t.Email"
                        Autocomplete="ComboboxAutocomplete.Both"
                        Height="400px"
                        SelectedOptionChanged="dto => CreateTestAssignmentDto.UserId = dto.Id"
                        Style="width: 100%"/>
    </div>
    <div class="mb-3">
        Test:
        <FluentSelect TOption="TemplateDto"
                      Items="Templates"
                      SelectedOptionChanged="dto => CreateTestAssignmentDto.TestId = Id"
                      SelectedOption="Templates.FirstOrDefault(t => t.Id == Id)"
                      OptionValue="t => t.Id.ToString()"
                      OptionText="t => t.Name"
                      Class="w-100">
            <FluentOption>Select one of the options</FluentOption>
        </FluentSelect>
    </div>

```

Custom form:
```csharp

<div Class=@($"p-3 bg-white shadow-sm rounded-3 {Class}")>

    <EditForm Model="@Object" class="form" OnValidSubmit="SubmitForm">
        <FluentValidationValidator Validator=@Validator />
        <ValidationSummary />
        @ChildContent
        <div>
            <button class="btn btn-primary shadow-sm" type="submit">
                <i class="bi bi-floppy me-1"></i>
                Vytvoriť
            </button>
        </div>
    </EditForm>

</div>


```

## 🌍 Your Environment

* OS & Device: MacOS
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version 4.10.0

**Comment by vnbaaij** [comment]
You have not supplied any details (Server/Wasm rendermode, used in combination with (Bootstrap?), no ready to run repro code, etc. See our standard reply below. If you're not going to help us to help you, this issue will be closed.

Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

**Help us to help you**. Thanks.

**Comment by MatejMa2ur** [comment]
Thank you for your help it is WASM.
