### ISSUE TITLE
4.10 breaking change

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2646]
Hi yesterday we've updated to v4.10 and there have been breaking changes. We needed to add `<FluentMenuProvider />` to our MainLayout to get `FluentMenu`s working again. Perhaps you can add this information to the release page as help for others.

This happens because the component is using `UseService=true` by default from now on.

**Comment by dvoituron** [comment]
You're right. We'll update the “What's New” page like this: #2649

**Comment by RobDene** [comment]
Ahhh, that wasn't on the menubutton demo page :) 

Perhaps you can add a line for amateurs like me !

Thanks !
