### ISSUE TITLE
fix: FluentDatePicker popup calendar has lost ability to change between Views [Day, Month, Year] by clicking on text Month, Year placed on the top-left corner.

### ISSUE THREAD

**Issue by undersoft-org** [microsoft/fluentui-blazor#2651]
#### FluentCalendar still have this feature but FluentDatePicker after click on top-left corner of popup calendar (pointer are changing to role=button) with month and year  simply closes the calendar and not switch to other views like FluentCalendar. I'm not sure when it starts but pretty sure it was after this pull request [https://github.com/microsoft/fluentui-blazor/pull/1903#issue-2254699649](#1903) .

![2024-09-12 19 27 51 www fluentui-blazor net 0b09fb7f3629](https://github.com/user-attachments/assets/1e46af87-6dcc-4553-94ac-63780ca20028)

**Comment by dvoituron** [comment]
This issue is already fixed in the `dev` branch and will be included in the next Release.

Examples: Left (v4.10.0) vs Right (v4.10.1)
![peek_3](https://github.com/user-attachments/assets/e5c576e5-860f-4b8b-aef9-960a5f82cb74)
