### ISSUE TITLE
Allow Custom Time in Time Picker

### ISSUE THREAD

**Issue by satyajit-behera** [microsoft/fluentui-blazor#2654]
Hi,

Time Picker displays all the time for hours and minutes. Hours displayed from 00 to 23 and minutes from 00 t0 59.

If its possible to customize the display values, it can help in a lot of ways where we can display some specific period to the users in some special cases where the user need to pick only given time 

Example I want users to select only a time with a gap of 15 mins. At present I don't see any options to do that.

Thanks.

**Comment by vnbaaij** [comment]
You should be able to control it with the standard step attribute (we are using standard <input type=time>), but I could not get it to work on a standard input neither in Edge nor Firefox.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#step

**Comment by satyajit-behera** [comment]
Thanks
