### ISSUE TITLE
feat: add Background Color to FluentTextField

### ISSUE THREAD

**Issue by ryanhuang2715** [microsoft/fluentui-blazor#2658]
# 🙋 Feature Request

Currently, when FluentTextField is set to Style="Background:lightgreen", FluentTextField cannot have the expected effect.
![4](https://github.com/user-attachments/assets/5c29b9a3-f501-4541-a10a-0e7ab3c584be)

## 🤔 Expected Behavior

![2](https://github.com/user-attachments/assets/5a721bb8-3795-4d1e-9028-84a8571aa732)

## 😯 Current Behavior

![3](https://github.com/user-attachments/assets/0fd27140-c893-4fad-b646-5804605114e6)
To make the color more obvious, use red instead

## 💁 Possible Solution
![1](https://github.com/user-attachments/assets/01f61a00-7ddd-42af-86c5-464450db6c1e)

According to the suggestion of 
[https://github.com/microsoft/fluentui-blazor/discussions/2240,]() 
it was processed, but it had no effect.

![5](https://github.com/user-attachments/assets/4bb1cc93-5621-440b-bd88-957057c49644)

**Comment by LuohuaRain** [comment]
please use: 
```css
fluent-text-field::part(root) > input { background: red }
```

**Comment by ryanhuang2715** [comment]
This works, thanks for the guidance
