### ISSUE TITLE
fix: [TreeView] @bind-SelectedItem does not work when clicking on an icon.

### ISSUE THREAD

**Issue by k111s222** [microsoft/fluentui-blazor#2659]
# 🐛 Bug Report

## 💻 Repro or Code Sample
https://www.fluentui-blazor.net/TreeView
'With Items'

As can be seen in the "With Items" example on the fluentui-blazor.net page, when clicking on an icon or a number enclosed in square brackets, the selected item (@bind-SelectedItem="@SelectedItem") is not work.

## 🤔 Expected Behavior
 I expected the bind-SelectedItem to change when clicking the icon or text (generated from the ItemTemplate) of a list item.

## 💁 Possible Solution
The solution I implemented to resolve this issue was to create an empty div that overlays the list item and apply the onclick event to that div.
```<div @onclick="async(e) => await HandleSelect(myTreeViewItem)" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(256,0,0,0.1); z-index: 10;"></div>```

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Mozilla FireFox, webview2 (rust tauri)
* .NET and Fluent UI Blazor library Version: example in https://www.fluentui-blazor.net/TreeView and Microsoft.FluentUI.AspNetCore.Components-4.10.0

**Comment by vnbaaij** [comment]
Closing this as it is not actionable from our side. The v2 web components will not see updates anymore...
