### ISSUE TITLE
fix: Anchors stopped working under 4.10.0

### ISSUE THREAD

**Issue by pmi24** [microsoft/fluentui-blazor#2661]
# 🐛 Bug Report

Anchors are not working under v4.10.0. 

## 💻 Repro or Code Sample

Install NuGet Version 4.10.0 and run the `Default` example for the FluentMenu component:
https://www.fluentui-blazor.net/Menu#default

## 🤔 Expected Behavior

After clicking the button a dropdown should appear next to the button.

## 😯 Current Behavior

No dropdown appears next to the button nor anywhere in the DOM.

## 🌍 Your Environment

* Windows 11
* Microsoft Edge 128.0.2739.63 (64-Bit)
* .NET 8.0 and FluentUI Blazor v. 4.10.0

**Comment by dvoituron** [comment]
Can you give us some more details? When I click on the "Open menu" button, the drop-down menu appears.
![peek_1](https://github.com/user-attachments/assets/46538c53-7167-49b9-b749-c734dcaad997)

**Comment by dvoituron** [comment]
Do you have the new ˋFluentMenuProvider` included in your MainLayout page?

See https://github.com/microsoft/fluentui-blazor/pull/2649
