### ISSUE TITLE
fix: Unexpected column options icon in FluentDataGrid

### ISSUE THREAD

**Issue by Leon99** [microsoft/fluentui-blazor#2669]
# 🐛 Bug Report

Adding `ResizeType="DataGridResizeType.Discrete" ` causes the column option button with an unexpected icon to appear in all the column headers.

## 💻 Repro or Code Sample

```
            <FluentDataGrid Items="Results" ResizableColumns="true" ResizeType="DataGridResizeType.Discrete" ShowHover="true">
                <PropertyColumn Property="@(p => p.Mapping)">
                    <ColumnOptions>
                        <div class="search-box">
                            <FluentSearch type="search" Autofocus=true @bind-Value="_mappingFilter"
                                          @oninput="@(args => _mappingFilter = args.Value?.ToString() ?? string.Empty)"/>
                        </div>
                    </ColumnOptions>
                </PropertyColumn>
                <PropertyColumn Property="@(p => p.ValueA)" Title="A"/>
            </FluentDataGrid>
```
## 🤔 Expected Behavior

![image](https://github.com/user-attachments/assets/4581c664-77e7-496c-b848-db0e7e62aa29)
on the columns with  `ColumnOptions`, nothing on the ones without.

## 😯 Current Behavior

![image](https://github.com/user-attachments/assets/7848d007-e2e1-47bb-8db9-d7140640ca1e)
Pressing it on the ones without `ColumnOptions` opens an empty popup.

## 🌍 Your Environment

* OS & Device: Windows 11, PC
* Browser Microsoft Edge
* .NET 8.0 
* Fluent UI Blazor library Version 4.10

**Comment by Leon99** [comment]
Thanks for the explanation @vnbaaij!
Just a suggestion - consider renaming `ResizeType` to make it clear that it enables "keyboard resizing" and changes the UI. As it is now, it's unclear that it doesn't affect "classic" resizing (dragging column borders).

**Comment by vnbaaij** [comment]
I've extended the source comment to make clear this only pertains to keyboard resize
