### ISSUE TITLE
fix: Autofit in DataGrid

### ISSUE THREAD

**Issue by RobDene** [microsoft/fluentui-blazor#2670]
# 🐛 Bug Report

When using autofit with virtualise, the initial Datagrid loading works correctly until you apply any additional filter once the grid has been displayed.
After applying a filter it reserves the correct rows in the grid but just displays one blank column. 

## 🤔 Expected Behaviour
To display correctly even after applying a filter 

## 😯 Current Behavior
After applying a filter it reserves the correct rows in the grid but just displays one blank column. 

Latest fluent ui

**Comment by vnbaaij** [comment]
`AutoFit` and `Virtualize` do not work together. The premise of `AutoFit` is that it goes through all rows to determine the widths needed. With `Virtualize` it can't do that.
