### ISSUE TITLE
fix: Column filtering indicator missing in FluentDataGrid

### ISSUE THREAD

**Issue by Leon99** [microsoft/fluentui-blazor#2683]
# 🐛 Bug Report

I'm pretty sure I saw the column filter button having an indicator when a filter applied, but it doesn't appear anymore.

## 💻 Repro or Code Sample

https://www.fluentui-blazor.net/DataGrid#customcomparer

## 🤔 Expected Behavior

Column filter button has an overlay when a filter is applied

## 😯 Current Behavior
![image](https://github.com/user-attachments/assets/f411e68d-3149-4d82-9ec7-6b038359b3a8)

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser Mozilla FireFox
* .NET and Fluent UI Blazor library Version: 
> Version: 4.10.0+10a73c3c  -  [Powered by .NET 9.0.0-preview.7.24405.7](https://dotnet.microsoft.com/en-us/learn/aspnet/what-is-aspnet-core)

**Comment by vnbaaij** [comment]
Hi,

The icon can still show a filtered state of a column:
![image](https://github.com/user-attachments/assets/86cbfdbf-5a13-491d-b24e-b8fc6502819f)

But for it to show up, you need to set the `Filtered` (bool) parameter on the column. For this Custom Comparer example it should be as follows:

```
<PropertyColumn Property="@(c => c.Name)" InitialSortDirection=SortDirection.Descending Sortable="true" IsDefaultSortColumn=true Comparer="@StringLengthComparer.Instance" Filtered="!string.IsNullOrWhiteSpace(nameFilter)">
```

It used to be working for the `Typical Usage` sample but that one is now using the new action menu. I'll change it now for the Custom Comparer sample.
