### ISSUE TITLE
fix: Using component inside same component causes "RangeError: Maximum call stack size exceeded."

### ISSUE THREAD

**Issue by oerbeke** [microsoft/fluentui-blazor#2692]
# 🐛 Bug Report

I have encountered this issue in 2 places (havent tested others):
1. When opening panel using dialogService and then opening another panel inside the previous panel.
2. When having a fluentcard inside another fluentcard

## 💻 Repro or Code Sample
Example using dialogs:

Calender.razor:

    public async Task OpenDay(int selectedDayOfMonth) {
        DateTime date = new DateTime(selectedMonth.Value.Year, selectedMonth.Value.Month, selectedDayOfMonth);
        var dialogData = new Tuple<DateTime, List<CalenderEventDTO>>(date, eventsOnDay);
        var dialog = await DialogService.ShowDialogAsync<Admin.Components.Pages.Calender.Dialogs.CalenderDialog>(dialogData, new DialogParameters() {
                Width = "calc(100% - 20vw)",
                DialogType = DialogType.Panel,
                DialogBodyStyle = "overflow:scroll",
                Title = LS.T("Calender.EventTitle"),
                Alignment = HorizontalAlignment.Center,
                PreventDismissOnOverlayClick = false,
                PreventScroll = false,
            });

        var result = await dialog.Result;
    }

CalenderDialog.razor:

    private async Task OpenEvent(CalenderEventDTO editEvent = null) {
        var dialogData = new Tuple<DateTime, CalenderEventDTO>(selectedDay, null);
        string dialogTitle = LS.T("Calender.CreateEventDialogTitle");

        if (editEvent is not null) {
            dialogData = new Tuple<DateTime, CalenderEventDTO>(selectedDay, editEvent);
            dialogTitle = LS.T("Calender.EditEventDialogTitle");
        }

        var dialog = await DialogService.ShowDialogAsync<CalenderEventDialog>(dialogData, new DialogParameters() {
                Width = "calc(100% - 20vw)",
                DialogType = DialogType.Panel,
                Modal = true,
                Alignment = HorizontalAlignment.Right,
                DialogBodyStyle = "overflow:scroll",
                Title = dialogTitle,
                PreventDismissOnOverlayClick = false,
                PreventScroll = false,
            });

        var result = await dialog.Result;
        if (!result.Cancelled) {
            if (editEvent is null) {
                var newEvent = (CalenderEventDTO)result.Data;
                events.Add(newEvent);
            } else {
                var updatedEvent = (CalenderEventDTO)result.Data;
                var index = events.FindIndex(e => e.ID == updatedEvent.ID);
                if (index >= 0) {
                    events[index] = updatedEvent;
                    StateHasChanged();
                }
            }
            StateHasChanged();
        }
    }

CalenderEventDialog.razor:

        <FluentTextField Label="@LS.T("Calender.EditEventTitle")" @bind-Value="editEvent.Title" Maxlength="50" InputMode="InputMode.Text" Autofocus="true" Immediate="true"></FluentTextField>
       

When i click on the fluenttextfield in CalenderEventDialog.razor i get the following browser console error and the cursor doesnt stay inside the textfield (loses focus right after):

![image](https://github.com/user-attachments/assets/a6efed3b-67c0-4b66-b6e7-00b01efdc7bb)

## 🤔 Expected Behavior

Nested dialogs and cards shouldnt cause this rendering error.

## 🌍 Your Environment

Blazor web app using server interactivity in .NET 8.
Tested in Edge and Chrome.
Using fluent UI 4.10.0

**Comment by vnbaaij** [comment]
Hi,

Closing this as it is a duplicate for the code provided. See https://github.com/microsoft/fluentui-blazor/issues/948#issuecomment-1804000795

Wrt to the cards, try to use the `MinimalStyle` parameter. If that still causes the same error, please open an new issue for that case.

**Comment by oerbeke** [comment]
Sorry for not having noticed issue #948 and thanks for the reply :)
