### ISSUE TITLE
docs: fix FluentDialogProvider registration

### ISSUE THREAD

**Issue by Leon99** [microsoft/fluentui-blazor#2698]
# 🙋 Documentation Request

https://www.fluentui-blazor.net/Dialog says

> Dialogs are rendered by the <FluentDialogProvider /> component. This component needs to be added to the main layout of your application/site. 

As per https://github.com/microsoft/fluentui-blazor/issues/1195, it's incorrect as FluentDialogProvider needs to be added to the component, not the layout.

**Comment by dvoituron** [comment]
What do you mean by this? The `FluentDialogProvider` must be added at the end of the `MainLayout` page... as explained here :
https://www.fluentui-blazor.net/CodeSetup

![{98F49D22-6C91-402C-B66E-A75FB4E45CDA}](https://github.com/user-attachments/assets/94e45a54-4e4e-4e94-b299-d7c197b143fa)

**Comment by vnbaaij** [comment]
And this has already been added quite some time ago:
![image](https://github.com/user-attachments/assets/48a7b1ef-5199-4408-a178-bb4af333d285)

**Comment by vnbaaij** [comment]
Oops, wrong button...

**Comment by vnbaaij** [comment]
No response so apparently not _that_important. Closing this.

**Comment by Leon99** [comment]
I spent quite some time figuring out why FluentDialogProvider doesn't work despite added in the main layout before I stumbled upon https://github.com/microsoft/fluentui-blazor/issues/1195#issuecomment-1868106676 and tried to add it to the component instead, which fixed it. Either it's a bug in the code or in the documentation.
