### ISSUE TITLE
fix: Clearing value in FluentCombobox when items change.

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#2708]
# 🐛 Bug Report

I have a combobox that I want to clear its selected value and changes its items. If I do those at the same time, then the value isn't cleared.

## 💻 Repro or Code Sample

There is a FluentSelect and a FluentCombobox. The combox is dependent on the select. That means when the FluentSelect value changes, the combox box value is cleared - `_formModel.Value = "";` - and bound items are changed - `ValueChanged();`.

However, if both of those things happen at the same time then the value in the UI isn't cleared. I worked around this by adding a Task.Delay between clearing the value and then changing the items.

```cs
private async Task ParameterChangedAsync()
{
    UpdateParameterFieldValues();

    _formModel.Value = "";
    StateHasChanged();

    // Clearing the selected value and the combo box items together wasn't correctly clearing the selected value.
    // This is hacky, but adding a delay between the two operations puts the combo box in the right state.
    await Task.Delay(100);
    ValueChanged();
}
```

PR with changes: https://github.com/dotnet/aspire/pull/5762

## 🤔 Expected Behavior

Value should be cleared when both of things happen at the same time.

## 😯 Current Behavior

Value isn't cleared.

## 💁 Possible Solution

Adding a hacky `Task.Delay` between the two actions fixes the problem.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Adding the `Task.Delay` is currently the only way to make this work. The Blazor components need time to 'catch up' with the changes that are being done in the web components with JS. There is nothing we can do about that with the current version of the web components.

A delay of just 5 (and sometimes even less) milliseconds is already enough in most cases.

Closing this as it is unfortunately not actionable from our side at the moment
