### ISSUE TITLE
[WebToolsE2E][Aspire] Some contents in aspire dashboard are not localized in non-ENU OS.

### ISSUE THREAD

**Issue by vmykagapuz** [microsoft/fluentui-blazor#2710]
REGRESSION
1. Not a regression in aspire 8.1.0 because this are new changes in aspire 8.2.0

INSTALL STEPS
1. Clean machine: Win11 x64 22h2 CHS
2. Install VS 17.12 Preview 3
3. Install Aspire 9.0 Preview 4

REPRO STEPS
1. Create Aspire Starter App
2. Build solution and F5

ACTUAL
In Resources module these are the contents that are not localized

- The "Sort" & "Resize" option in [Type, Name, State, Start time]

![image](https://github.com/user-attachments/assets/ce2f2806-b9d3-44b9-92df-72ac36c7918b)

- The "Column width (in pixels) in [Source, Endpoints, Logs, Details]

![image](https://github.com/user-attachments/assets/487d3e3d-3afb-420e-bc12-b3844c34649c)

EXPECTED
The new changes for the contents of aspire dashboard should be localized.

**Comment by oneolddev** [comment]
FYI - new comment added requesting this issue be closed.

https://github.com/dotnet/aspire/issues/5382#issuecomment-2371502601
