### ISSUE TITLE
feat: add FluentDataGridRow iteration and selection by Index/Data/Id to FluentDataGrid

### ISSUE THREAD

**Issue by vpetit-reimagine** [microsoft/fluentui-blazor#2715]
# 🙋 Feature Request
Currently, it is not possible to iterate the rows of the FluentDataGrid in order to select them programmatically based on some events. 
As an example, if we use the FluentKeyCode component with a FluentDataGrid, it is not possible to select a list of rows between 2 rows with a combination of `OnRowClick` and a specific KeyCode (alike Excel shift click between rows).

## 🤔 Expected Behavior
We expect to be able to iterate and select rows based on other conditions, maybe by row index, row id, or row data.
It is expected that this kind of feature would also work with `Virtualize` as this is a way to do a selection of a lot of rows across a really big list of items.

## 😯 Current Behavior
We can't iterate over the rows of the FluentDataGrid or select them programmatically with other events/conditions

## 💁 Possible Solution
Make the list of `FluentDataRow` public? Or allow a way to programatically select a row by Id/Data/Index and be able to retrieve the Item associated with it.

Ideal solution:
- Selecting a row via click and selecting another one with Shift click would allow a selection of all the rows in between, and would allow the possibility to work/update on the items of each row

## 🔦 Context
We are trying to accomplish some Excel like selection feature for our users to be able to update multiple row items at once (we currently use the drag & drop feature on a column with FluentDragContainer, but it has some issues when scrolling on a virtualized list of items as the selection is not really kept properly when scrolling outside of the visible rows).

## 💻 Examples
Currently no examples that I can show, but if the explanation isn't clear I can try to provide some.

**Comment by vnbaaij** [comment]
> We can't iterate over the rows of the FluentDataGrid or select them programmatically with other events/conditions

That is not entirely true. You can use `@bind-SelectedItems` on the `SelectColumn` to set selected items based on the data source properties. See https://www.fluentui-blazor.net/DataGrid#multiselect for example code on that.

We will put the 'Excel like selection feature' on our ToDo list. Ast we have not had any requests for this in the past, it is not going to be a high priority item though.

**Comment by vpetit-reimagine** [comment]
That is true that we can iterate over the selected items, but it means that the user needs to select all rows manually. 

I was looking at ways to also provide some reference of the Row to the FluentDropZone items that are inside it (as a ParentReference), but it is not even possible to do so as the Rows are not really available when describing the FluentDataGrid and the different columns. Even if we try to pass a reference with @ref, it will be done on the column and it is not possible to do so with a row.

Currently, I am not able to continue further with what I want to achieve as some features/components are not able to work together in a way that would allow me to reference the row from the content of its cells.


To summarize a bit more what I want to perform, with some pseudo-code:
```
<FluentKeyCode OnKeyDown="HandleKeyDown">
    <FluentDragContainer TItem="MyItem" OnCellClick="HandleCellClick">
         <FluentDataGrid @ref="_myGrid" TGridItem="MyItem" Items="@(_myItems.AsQueryable())">
                 <TemplateColumn>
                          <FluentDropZone TItem="MyItem" Draggable="true" Droppable="true" Item="context">
                                @* inner content *@
                           </FluentDropZone>
                   </TemplateColumn>
           </FluentDataGrid>
      </FluentDragContainer>
</FluentKeyCode>


@code {
    private bool isCtrlPressed;

    private async Task HandleKeyDown(FluentKeyCodeEventArgs obj)
    {
        _isCtrlPressed = obj.CtrlKey;
    }

    private void HandleCellClick(FluentDataGridCell<MyItem> obj)
    {
         if (_isCtrlPressed)
         {
                // iterate over all rows between previously clicked one (saved in a variable) and the currently clicked one to update the items
         }
    }
}
```

**Comment by dvoituron** [comment]
I don't think you need new methods to do this. 
In this example, you can capture the `Shift` or `Ctrl` key in memory (to know if this key is pressed).
And in the `OnSelectRow` method, you can customise the way to select the current item (if `Shift` is not pressed) or to select a range of items (if `Shift` is pressed).

Tips:
- I added `Style="user-select: none;"` to disable de default text selection using the Shift key.
- `@key="@GridKey"` forces the grid to be refreshed when a selected item is updated.

```razor
<FluentKeyCode OnKeyDown="@(e => SelectRange = e.Value == "Control" || e.Value == "Shift")" OnKeyUp="@(e => SelectRange = false)"
               IgnoreModifier="false"
               PreventDefault="true"
               Only="@(new [] { KeyCode.Ctrl, KeyCode.Shift })">

    <FluentDataGrid Items="@People" ShowHover="true" TGridItem="Person" Style="user-select: none;">
        <SelectColumn TGridItem="Person"
                      @key="@GridKey"
                      SelectMode="@DataGridSelectMode.Multiple"
                      SelectFromEntireRow="true"
                      SelectAllDisabled="true"
                      Property="@(e => e.Selected)"
                      OnSelect="@OnSelectRow"
                      SelectAll="@(People.All(p => p.Selected))"
                      SelectAllChanged="@(all => People.ToList().ForEach(p => p.Selected = (all == true)))" />
        <PropertyColumn Width="100px" Property="@(p => p.PersonId)" Title="ID" />
        <PropertyColumn Width="300px" Property="@(p => p.Name)" />
        <PropertyColumn Width="150px" Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
    </FluentDataGrid>

    <div>
        <b>Peoples:</b>
        @String.Join("; ", People.Where(p => p.Selected).Select(p => p.Name))
    </div>

</FluentKeyCode>

@code {
    bool SelectRange = false;
    int GridKey = 0;

    void OnSelectRow((Person Item, bool Selected) e)
    {
        if (SelectRange)
        {
            var startIndex = People.ToList().FindIndex(p => p.Selected);
            var endIndex = People.ToList().FindIndex(p => p.PersonId == e.Item.PersonId);
            var range = People.Skip(Math.Min(startIndex, endIndex)).Take(Math.Abs(startIndex - endIndex) + 1);
            range.ToList().ForEach(p => p.Selected = true);
        }
        else
        {
            People.ToList().ForEach(i => i.Selected = false);
            e.Item.Selected = true;
        }

        GridKey++;  // Force the refresh of this DataGrid
    }

    record Person(int PersonId, string Name, DateOnly BirthDate)
    {
        public bool Selected { get; set; }
    };

    static IQueryable<Person> People = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)) { Selected = true },
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9)),
    }.AsQueryable();

    private void ResetSelectItems()
    {
        People.ToList().ForEach(i => i.Selected = false);
        People.First().Selected = true;
    }
}
```
![peek_2](https://github.com/user-attachments/assets/8e0c9e52-36de-4144-9508-d19687867296)

**Comment by vpetit-reimagine** [comment]
That could work, but we actually do not really select the rows (we do not use the `SelectFromEntireRow`, but that is probably something we have to change as we do have actions on specific cells). What we are looking for is to copy the value of an item of a row to the other items (that is why we used the drag and drop, as the logic to copy a value from one item to the other items is implemented there).

The idea was to be able to replicate the `copy` of those values by selecting a range of rows directly

**Comment by dvoituron** [comment]
All `OnCellClick`, `OnRowClick` and other events send your selected element `FluentDataGridCell<TGridItem>.Item`.
Using this item, you should be able to find the index, identifier or other property.

**Comment by vpetit-reimagine** [comment]
It is not really possible to find the index from the Item (as it doesn't come with it anywhere), the only way to retrieve the row index is by `OnRowClick` where (thankfully?) there is `aria-rowindex` in the `AdditionalAttributes`, which gives the row Index (but for some reason, `RowIndex` is null tho)

**Comment by vpetit-reimagine** [comment]
Alright, I was able to get around the limitations of the different components used with reflection, with some few small issues still left. I will first expand a bit more the context of all the requirements, all the things that we put in place, and all the things that do not work well together for this situation:

- We have data loaded from a cache into the `FluentDataGrid`. This `FluentDataGrid` has up to 26 visible columns.
- The number of items (rows) is over 3600
- Our customers want to be able to do the following actions on the data:
   - Copy and paste a value from a column from one line to any other line in the list 
   - Drag and drop some values from a line to adjacent lines
   - Sorting columns

To implement the previous requirements, we used `FluentDataGrid` to list the items. Because it internally uses custom html components, this fails to load anything if we do not virtualize the grid (3600*26 components to be processed). I saw that there is an ongoing work being done to move to the possibility to use plain old html tables, which I think will give better results in similar situations.
(We will see later on that the Virtualization is giving other issues).

To allow the copy/paste, we used `FluentKeyCode` and handle `CTRL+C` and `CTRL+V`. This works fine, if we know how to actually copy an item from the DataGrid (we use TemplateColumn with a FluentDropZone using the context as the Item).

To allow the Drag & Drop, it is basically using the `FluentDragContainer` and handle the drop with the `FluentDropZone`. That works almost fine if you do not use Virtualize, because then as the data is refreshed, if you apply a class/style to the rows to highlight them, the styling disappears once you scroll out of the current list of items. This is an issue for our users as it confuses them. This is one of the first limitations of `Virtualize` and `FluentDataGrid`.

To actually allow our users to copy some value from a line really high in the list, to a line that is few "virtualized" screens later, we needed to implement a copy on other events (we chose `CTRL + Click`, which is a `OnCellClick` and `OnKeyDown`). This is where things started to fall apart because not everything works as they should out of the box for this situation. 

First of all, as mentioned previously, it is not possible to actually iterate over rows that are not in a `Selected` state. We do not actually want to select the rows, as we would have to unselect them. We also have some columns that should not trigger the selection (so we can't really use `SelectFromEntireRow`). The fact that we also use `Virtualize` will fail as the rows are unloaded, and replaced by newly added virtualized rows.

Therefore, how do we iterate over rows? A good option would be to try to simply get the selected row index and iterate over the Items of the `FluentDataGrid`. Does it work? No, because `Items` is an `IQueryable` and because `GridSort` applies the sorting on the displayed rows, the `Items` are always in the same order. 

How to deal with that? Well, to be able to actually retrieve and iterate over the sorted list of Items (in the order of the `GridSort`), we have to use the `_internalGridContext` and retrieve the `Items` property as the list there will be properly sorted (which is, interestingly strange as the `FluentDataGrid` list of Items is still unsorted). To do that, because `_internalGridContext` is of an internal type, and also a private member, we have to rely on reflection (which, in the long term is not a viable solution as there are no guarantees that those private members will never change).


This below is the implementaton of how we dealt with all that, with the `OnCellClick` function only:

```cs
    private async Task HandleCellClick(FluentDataGridCell<DomainFullDto> obj)
    {
        // We only handle specific cells that are not headers, as those won't have any Item
        if (obj.CellType != DataGridCellType.Default || !obj.Class.Contains("copyable"))
        {
            return;
        }
      
        // This is a way to retrieve the property that will be copied, which is also something to deal with
        DomainEditedField key = DomainEditedField.None;
        obj.Class.Split(" ")
            .FirstOrDefault(e => Enum.TryParse<DomainEditedField>(e, out key));

        // Saving the item in a "clipboard" and to also save the property that will be copied. We save it only if ctrl is not pressed
        if (key != DomainEditedField.None && !_isCtrlPressed)
        {
            _internalTemporaryClipboard = new(key, obj.Item);
        }
    
       // Dealing with the fact we can't iterate/access the sorted Items directly in the list, but through an internal member
        var field = _myGrid
            .GetType()
            .GetField("_internalGridContext", BindingFlags.NonPublic | BindingFlags.Instance)
            .GetValue(_myGrid);

        var igc = field.GetType();
        var items = igc.GetProperty("Items").GetValue(field) as DomainFullDto[];

        var enumeratedItems = items?.AsEnumerable().Select((item, index) => (item, index));
        
        // On first press, we retrieve the index of the selected Item based on the currently selected Cell Item
        if (!_isCtrlPressed)
        {
            _firstSelectedRowForCtrlCopy = enumeratedItems
                .Where(x => x.item is not null)
                .First(x => x.item.Id == obj.Item.Id).index;
        }
        else // We are currently pressing ctrl, so we now have to apply the copy
        {
            var current = enumeratedItems
                .Where(x => x.item is not null)
                .First(x => x.item.Id == obj.Item.Id).index;

            // Dealing with the order to which we copy from/to (upwards or downwards)
            var start = current < _firstSelectedRowForCtrlCopy ? current : _firstSelectedRowForCtrlCopy;
            var end = current > _firstSelectedRowForCtrlCopy ? current : _firstSelectedRowForCtrlCopy;

            // Iterating over the items, making sure that we remove the row that was selected first
            foreach (var row in enumeratedItems.Where(x => x.item.Id != _internalTemporaryClipboard.Item2.Id && start <= x.index && x.index <= end))
            {
                // Doing the copy
                await CopyValueForKeyFromSourceToDestination(_internalTemporaryClipboard.Item2, row.item, _internalTemporaryClipboard.Item1);
            }
            _isCtrlPressed = false;
        }
    }
```


This is not optimal, and would be easier if it was possible to access the sorted list directly from the grid (we have a reference to the grid, but the items are not sorted). The fact `Virtualize` replaces the rows on scroll is also an issue (but understandable why it acts that way). The fact that the `FluentDataGrid` doesn't load properly when many rows/columns are displayed is also an issue in cases where you might need to do something like in the current example.

**Comment by vnbaaij** [comment]
It is impressive to see what you have done with reflection and your own code and turend that into something that your customers want. But I do not see a lot of value in incorporating this into our standard grid. 
Drag-drop, copying rows are nice things but as you mention do not always play nice with Virtualization. And we _do_ need virtuallization. Not because (like you hinted at) we are using custom components (those are performant enough in the vast majority of case), but because it is also possible to use far lager number of rows than the 3600 you are using, like the 26k we use in our remote data example (https://www.fluentui-blazor.net/DataGrid#remotedata). Doing that without Virtualization would be nuts and will nor perform in any way.

So yes, currently it is not possible to iterate the rows of the FluentDataGrid in order to select them programmatically based on some events. And I don't see us adding that ourselves anytime soon. a) because we lack resources to build this (I think this would be a substantial task) and b) we have not received any other asks for this so I don't see this as/think this is a high in demand request.

**Comment by bcdev-com** [comment]
> I don't think you need new methods to do this. In this example, you can capture the `Shift` or `Ctrl` key in memory (to know if this key is pressed). And in the `OnSelectRow` method, you can customise the way to select the current item (if `Shift` is not pressed) or to select a range of items (if `Shift` is pressed).
> 
> Tips:
> 
>     * I added `Style="user-select: none;"` to disable de default text selection using the Shift key.
> 
>     * `@key="@GridKey"` forces the grid to be refreshed when a selected item is updated.

I found this thread while looking to solve a vaguely similar issue.  The use of @key with a synthetically changing value when I change the row selections in the data model due to other user actions was the 'key' insight to making it to work for me.

What I did discover though, is that putting that @key on the SelectColumn let me control when the individual row-select checkboxes get refreshed to match my model, but it left the SelectAll checkbox in the header as indeterminate even after all the rows were unselected.  Moving the @key to the containing grid fixed the problem, though presumably at an unnecessary re-render.

I'm posting this here for the next person struggling with that SelectAll checkbox not updating.
