### ISSUE TITLE
feat: add Multiple support to/in FluentCombobox

### ISSUE THREAD

**Issue by danielpastoor** [microsoft/fluentui-blazor#2719]
# 🙋 Feature Request

Now we have the FluentCombobox and the FluentSelect but I need in a project a select or combobox that has the autocompletion and the multiple select. Is this possible to add the Multiple support to the FluentCombobox?

**Comment by vnbaaij** [comment]
Not with the standard FluentCombobox. You can have multiple selection with the `FluentAutoComplete` component: https://www.fluentui-blazor.net/Autocomplete
