### ISSUE TITLE
fix: Accordion single expand forces one accordion to always be open

### ISSUE THREAD

**Issue by RobDene** [microsoft/fluentui-blazor#2729]
# 🐛 Bug Report

With Accordion set into single expand, the first accordion item is forced to expand even if you manually set all accordion tabs to expand false. 

## 🤔 Expected Behaviour

Should behave the same as multi expand where you can open and close any single item - when you select a new accordion then it closes any other. You should be able to have a state with no items open.

## 😯 Current Behaviour

One accordion item is forced open all the time - it won't allow you to close all items

## 🔦 Context

The behaviour is erratic - both multi and single should honour no items open - the difference is that single should only allow one open at any time and closes the previously opened one whereas multi doesn't.

## 🌍 Your Environment

latest Blazor/FluentUI 4.10.1

**Comment by dvoituron** [comment]
This is how the component works (by design): in `Single` mode you must **always** have an element open. 

You can extend this mode by configuring the component as a `Multiple` and manually managing the elements you want to open or close.
