### ISSUE TITLE
fix: Fluenttabs overflow badge button doesnt work 

### ISSUE THREAD

**Issue by oerbeke** [microsoft/fluentui-blazor#2731]
# 🐛 Bug Report

When using FluentTabs, clicking on the badge showing +1 doesnt do anything. I have used the same setup as on the documentation page and tried many different parameter combinations with no luck. 

https://github.com/user-attachments/assets/4b074231-c111-4bf6-a0c5-ca7620141610

## 💻 Repro or Code Sample

<FluentTabs @bind-ActiveTabId="@activeid" OnTabChange="HandleOnTabChange" Width="100%" Size="TabSize.Large">

    <FluentTab Label="@LS.T("Product.TabProductCategories")" Id="tab-1" Icon="@(new Icons.Regular.Size24.SkipForwardTab())">
        <CascadingValue Value="this" IsFixed="true">
            <Admin.Components.Pages.ProductSettings.Tabs.ProductCategoriesTab></Admin.Components.Pages.ProductSettings.Tabs.ProductCategoriesTab>
        </CascadingValue>
    </FluentTab>
   
    <FluentTab Label="@LS.T("Product.TabCategoriesOutlets")" Id="tab-2" Icon="@(new Icons.Regular.Size24.SkipForwardTab())">
        <CascadingValue Value="this" IsFixed="true">
            <Admin.Components.Pages.ProductSettings.Tabs.OutletProductCategoriesTab></Admin.Components.Pages.ProductSettings.Tabs.OutletProductCategoriesTab>
        </CascadingValue>
    </FluentTab>
    

    <FluentTab Label="@LS.T("Product.TabProductConfigs")" Id="tab-3" Icon="@(new Icons.Regular.Size24.SkipForwardTab())">
        <CascadingValue Value="this" IsFixed="true">
            <Admin.Components.Pages.ProductSettings.Tabs.ProductConfigurationTab></Admin.Components.Pages.ProductSettings.Tabs.ProductConfigurationTab>
        </CascadingValue>
    </FluentTab>

    <FluentTab Label="@LS.T("Product.TabProductSections")" Id="tab-4" Icon="@(new Icons.Regular.Size24.SkipForwardTab())">
        <CascadingValue Value="this" IsFixed="true">
            <Admin.Components.Pages.ProductSettings.Tabs.ProductSectionTab></Admin.Components.Pages.ProductSettings.Tabs.ProductSectionTab>
        </CascadingValue>
    </FluentTab>

    <FluentTab Label="@LS.T("Product.TabTimeTable")" Id="tab-5" Icon="@(new Icons.Regular.Size24.SkipForwardTab())">
        <CascadingValue Value="this" IsFixed="true">
            <Admin.Components.Pages.ProductSettings.Tabs.TimeTableProductsTab></Admin.Components.Pages.ProductSettings.Tabs.TimeTableProductsTab>
        </CascadingValue>
    </FluentTab>

</FluentTabs>

## 🌍 Your Environment

Latest .NET 8 and Fluent UI version using Blazor fluent UI web app template with reboot styling.

**Comment by dvoituron** [comment]
You need to add the new **Menu Provider** in your **Layout** page: `<FluentMenuProvider />`.

See the section "Add Component Providers" on this page: https://www.fluentui-blazor.net/CodeSetup

**Comment by oerbeke** [comment]
Ok fair enough, that was the one provider I hadnt added. How come there isnt a list or a description of which components need which provider? Or is it seen as unecessary because you should just add all providers always?

Kind regards

**Comment by dvoituron** [comment]
Because we don't have enough time to document and think about all this 😀. We're trying to improve, and v5 of the library will be even better.

**Comment by vnbaaij** [comment]
It is described in the page Denis mentioned. It also says there that you can remove the ones that are not used.

We will add a section on the Tabs page that it uses the menu (and menu provider) when showing the overflow.
