### ISSUE TITLE
fix: Loading == true ignored when Items == null in DataGrid

### ISSUE THREAD

**Issue by cdock1029** [microsoft/fluentui-blazor#2734]
# 🐛 Bug Report

`items == null` overrides `loading == true`, such that `No data to show!` is displayed instead of `Loading..`
prior to the IEnumerable having data.

## 💻 Repro or Code Sample

```razor
@rendermode @(new InteractiveAutoRenderMode(prerender: true))

				
		<FluentDataGrid Items="MyData?.AsQueryable()" Loading="@(MyData is null)">
			...
		</FluentDataGrid>
	

@code {

	[Parameter] public IEnumerable<MyEntity>? MyData { get; set; }
}
```

## 🤔 Expected Behavior

Collections are either null, empty, or full. I would expect the most common state where loading should display is when the data is null, during data loading. If it comes back empty that is when "No data" takes effect. Or in any case, Loading == true should display loading regardless of anything else.

## 😯 Current Behavior

When `Items` is empty, `Loading == true` takes effect and displays properly.

```razor
<FluentDataGrid Items="(RecentTreasuries ?? []).AsQueryable()" Loading="@(MyData is null)">
    ...
</FluentDataGrid>
```

## 💁 Possible Solution

Give precedence to `Loading == true`

## 🔦 Context

Just unexpected, and I guess I could throw that empty list in there but seems better the other way, just using the null parameter as is.

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser Microsoft Edge
* .NET 9 Preview, Fluent UI Blazor 4.10.1

**Comment by Thoronion** [comment]
I can confirm this as well. Our web app stopped displaying loading when upgrading to 4.10.1. Downgrading to 4.10.0 will result in the expected behavior.

**Comment by vnbaaij** [comment]
> I can confirm this as well. Our web app stopped displaying loading when upgrading to 4.10.1. Downgrading to 4.10.0 will result in the expected behavior.

I've been looking at the changes and I can't see/find where that change would have been made. Can you get as a reproducible example of this?

**Comment by Thoronion** [comment]
> > I can confirm this as well. Our web app stopped displaying loading when upgrading to 4.10.1. Downgrading to 4.10.0 will result in the expected behavior.
> 
> I've been looking at the changes and I can't see/find where that change would have been made. Can you get as a reproducible example of this?

Sure!

I made two commits for each version. In 4.10.1 you won't see any "loading" at all while in 4.10.0 "loading" is displayed until you  press the button.

https://github.com/Thoronion/FluentUISandbox

**Comment by vnbaaij** [comment]
Ok, Tested your repo (thanks) against what I have in a PR I'm working on to fix this and can confirm your example is showing the 4.10.0 behavior with those changes!

**Comment by Thoronion** [comment]
> Ok, Tested your repo (thanks) against what I have in a PR I'm working on (#2739) to fix this and can confirm your example is showing the 4.10.0 behavior with those changes!

That is great :)
