### ISSUE TITLE
fix: Scrollbars appear when opening a FluentMenu

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#2736]
# 🐛 Bug Report

There was a regression when moving from 4.9.3 to 4.10.1. Horizontal scrollbars appear when opening a FluentMenu.

Before:
![menu-scrollbars-before](https://github.com/user-attachments/assets/67e23c3d-6f9d-426f-9f60-60940346aee2)

After:
![menu-scrollbars-after](https://github.com/user-attachments/assets/69807401-a226-4af7-8ed4-b4e3d024d0d6)

## 💻 Repro or Code Sample

This was the change that introduces the regression: https://github.com/dotnet/aspire/pull/5670

Control on the page with the issue: https://github.com/dotnet/aspire/blob/f7f20e4c12dafa5b4b50c2b42f31cc2b1327fa37/src/Aspire.Dashboard/Components/Controls/AspireMenuButton.razor

## 🤔 Expected Behavior

No scroll bars.

## 😯 Current Behavior

Scroll bars appear.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by dvoituron** [comment]
Probably caused by the position of the `<FluentMenuProvider />` which should be in an HTML section containing a `overflow-y`. Is it possible in your code?

You can disable the usage of this Provider by adding the `UseMenuService="false"` attribute. In this case, the menu is drawn at the location of your HTML code.

**Comment by JamesNK** [comment]
Is being an a section with `overflow: auto` ok?

I tested more and found the scrollbars only appear when the browser is zoomed in, e.g. 110% size.

**Comment by vnbaaij** [comment]
So this can be closed?

**Comment by JamesNK** [comment]
Scroll bars shouldn’t be appearing.

**Comment by dvoituron** [comment]
Have you tried adding `UseMenuService=‘ false’` to revert to the previous usage?

**Comment by JamesNK** [comment]
Yes: https://github.com/dotnet/aspire/pull/6039. But it is a temporary fix because the menu [can be hidden by splitter areas](https://github.com/microsoft/fluentui-blazor/issues/2490) again.

We need fluent menu provider but not have it add scroll bars.

**Comment by dvoituron** [comment]
> Yes: [dotnet/aspire#6039](https://github.com/dotnet/aspire/pull/6039). But it is a temporary fix because the menu [can be hidden by splitter areas](https://github.com/microsoft/fluentui-blazor/issues/2490) again.
> 
> We need fluent menu provider but not have it add scroll bars.

OK. Let me take a look

**Comment by dvoituron** [comment]
The problem is that the `body` allows `overflow`, and with the new `FluentMenuProvider`, a side effect may be the display of this scroll bar.

You can solve that adding this code in the `app.css` file

```css
body, .body {
    overflow: hidden;
}
```

I haven't seen a problem disabling scrollbars in `body`, as it seems that a layout div adds scrollbars if necessary.

**Comment by dvoituron** [comment]
I've found another way to avoid displaying this body scrollbar: using `display: fixed`. 
I will create a PR to include these styles by default in the FluentUI Blazor library, but in the meantime, you can use it.

```html
<div style="position: fixed; bottom: 0;">
    <FluentMenuProvider />
</div>
```

**Comment by JamesNK** [comment]
Thanks, that works.
