### ISSUE TITLE
feat: expose PopoverVisible property on FluentProfileMenu

### ISSUE THREAD

**Issue by brused27** [microsoft/fluentui-blazor#2737]
# 🙋 Feature Request
I would like to be able to set the property PopoverVisible = true/false manually on the FluentProfileMenu component.

## 🤔 Expected Behavior
PopoverVisible is moved from a private property to a public property and has the [Parameter] attribute added.

## 😯 Current Behavior
I need to use reflection or custom JavaScript to help close this menu overlay as PopoverVisible is a private property on this component.

## 💁 Possible Solution
PopoverVisible is moved from a private property to a public property and has the [Parameter] attribute added.

## 🔦 Context
I am using a custom header/footer template and I am currently unable to easily close this menu should the app decide to trigger an action/navigation based upon a click that occurs inside this menu. There is currently no exposed visibility parameter on this component today.

We would not need to set this property via reflection and/or use JavaScript to help close the menu manually if this was updated.

## 💻 Examples
See Context above, I think this should be clear but let me know if not.

**Comment by dvoituron** [comment]
This could be interesting. I renamed this internal variable and exposed it externally using the name `Open`.

#2741

**Comment by brused27** [comment]
Wow, thank you the quick response!  This looks great and I'm looking forward to having it in the next release.
