### ISSUE TITLE
The content of a FluentTab runs out of the FluentDialog

### ISSUE THREAD

**Issue by JohnVottero** [microsoft/fluentui-blazor#2738]
# 🐛 Bug Report

When a FluentDialog contains FluentTabs and the contents of a FluentTab exceed the size of the dialog, the content runs out the bottom of the dialog. A scroll bar is added but, the size of the fluent-tab-panel is much larger than the size of the dialog so, even the scroll bar runs out the bottom of the dialog. 

## 💻 Repro or Code Sample

This repository reproduces the issue and has a screenshot of the problem:

https://github.com/JohnVottero/ScrollBarInTabPage

## 🤔 Expected Behavior

The contents of the FluentTab should be contained within the FluentDialog.

## 😯 Current Behavior

The contents of the FluentTab run out the end of the FluentDialog.

## 💁 Possible Solution

I do not know of a solution or workaround. Looking at the generated HTML, the <fluent-tab-panel> starts with:
```
<fluent-tab-panel style="height: calc(100% - 40px); overflow-y: auto;...
```
The height and overflow look correct so I think the issue is with the container of the fluent-tab-panel but, I'm getting out of my area of expertise.
 
## 🌍 Your Environment

Windows 11, Edge browser, .NET 8 and FluentUI-Blazor 4.10.1

**Comment by vnbaaij** [comment]
Thanks for the repo. That made it a lot easier to solve this.

Because you specify the dialog `Height` (in `Home.razor`) as 80**vh**, you eed to specify the `Height` in the `FluentTabs` in `TabWithScrollDialog` in vh as well. If you change it to something like 62vh, things will render as expected again.

**Comment by JohnVottero** [comment]
Thanks for the quick response! Changing height to 62vh does resolve my issue but, I would encourage you to call that a workaround and keep this issue open. Why does width work as a percentage of parent by height doesn't?

I'm going to use the same reproducer for a second issue so maybe there is an underlying problem that is causing both issues.
