### ISSUE TITLE
fix: [FluentMenu] as context menu not being fully visible

### ISSUE THREAD

**Issue by Schneider-N** [microsoft/fluentui-blazor#2749]
# 🐛 Bug Report

I have an Website where i am using an FluentMenu as context menu.
Which i set it like this:
`<FluentMenu Anchor="htmlEditorDiv" Trigger="MouseButton.Right" Anchored="false"  UseMenuService="true">`
When i now rightclick the anchor div to open the menu, while my mouseposition is near the bottom of the screen, the menu
opens but parts of it are not visible, And there is no way to get them to be visible other then to scroll the page and right click a higher part which is not always possible. 
Normal ContextMenue:
![image](https://github.com/user-attachments/assets/691095c3-a0cf-4b0a-ab16-91b484c993d4)

"Cut" ContextMenue:
![image](https://github.com/user-attachments/assets/bb72e89b-8655-4448-8493-64e357aa7a4c)

This behavior can also be seen on the demo site: https://www.fluentui-blazor.net/Menu
![image](https://github.com/user-attachments/assets/197d2e73-cff7-4f98-9876-e863277cf574)
![image](https://github.com/user-attachments/assets/f850ae10-d56f-4daf-9dde-24cfd63a1ba4)

## 💻 Repro or Code Sample
To get a small code sample:
Create new Application:
dotnet new fluentblazor --name MyApplication

Change content of Home.razor to the following and run the app:
```
@page "/"
@rendermode InteractiveServer
<div style="position: relative; height:100%">
<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new Fluent Blazor app.

<div id="myId4" style="position: absolute; bottom: 0">
    Right-click on this text <br/>
    to open a Context Menu.
</div>
</div>

<FluentMenu Anchor="myId4" Trigger="MouseButton.Right" Anchored="false" UseMenuService="true" @onmenuchange=OnMenuChange>
    <FluentMenuItem Label="Item 1" />

    <FluentMenuItem Label="Item 2">
        <MenuItems>
            <FluentMenuItem Label="Item 2.1">
                <MenuItems>
                    <FluentMenuItem Label="Item 2.1.1"  />
                    <FluentMenuItem Label="Item 2.1.2"  />
                </MenuItems>
            </FluentMenuItem>
            <FluentMenuItem Label="Item 2.2"  />
        </MenuItems>
    </FluentMenuItem>

    <FluentMenuItem Label="Item 3" />
</FluentMenu>

<p>@status</p>

@code {

    private string status = "";

    private void OnMenuChange(MenuChangeEventArgs args)
    {
        if (args is not null && args.Value is not null)
            status = $"Item \"{args.Value}\" clicked";
    }
}
```

## 🤔 Expected Behavior

When right clicking the context menu should be fully seen.

## 😯 Current Behavior

Some parts of the context menu are not visible and therefor cannot be selected

## 💁 Possible Solution

For trying to fix the error i tried to set the vertical threshold and placements etc.
But  when "Anchored ="false"" is set, it does ignore those settings and opens the menu
to the bottom right of the point where the right click was positioned.

So maybe to fix this problem add a threshold check if there is enough space for the full menu,
otherwise let it select another area to open it.

## 🌍 Your Environment

* OS: Windows 10
* Browser: Microsoft Edge, Google Chrome
* .net8
* Fluent UI 4.10.1

**Comment by dvoituron** [comment]
You can use the `VerticalThreshold` property to set how short the space allocated to the default position has to be before the tallest area is selected for layout. To set this property, you need to use `Anchored=‘true’` (or remove this attribute because true is the default value).

**Comment by Schneider-N** [comment]
Yes i know that i could use the vertical threshold WHEN i am setting `Anchored=True` but thats not what i want to do here.
Because i dont want the context menu to be opened relativ to the div it belongs to but to the mouse position.

For a bit more context here:
I am tryining to build a WYSIWYG- Editor on that page, that has an own custom actionbar and only for the writing pane an context menu. This writing pane takes up a relativ big amount of that page. So when i am writing in the lower part of that, and i want to use the context menu there. I really dont want to open the context menu relativ to that whole pane but where my mouse cursor is atm. 

Thats what i thought the `Anchored=False` - Option of the FluentMenu is build for. So your answer does not really fix what i was trying to do. Or am i missing something here?

**Comment by dvoituron** [comment]
This is a limitation of Web Components v2 that we are currently using. When we display a menu at the position of the mouse, we don't have the option of making the menu position dynamic. This should be corrected with the next version of Web Components v3.
