### ISSUE TITLE
fix: Setting Loading in FluentButton bound to FluentInputFile breaks it

### ISSUE THREAD

**Issue by Leon99** [microsoft/fluentui-blazor#2754]
# 🐛 Bug Report

After setting Loading in FluentButton bound to FluentInputFile, it won't open the file browse dialog anymore.

## 💻 Repro or Code Sample

```
                    <FluentButton
                        Id="form-browse-button"
                        Loading="_formUploading">
                        Upload...
                    </FluentButton>
                <FluentInputFile
                    Accept="application/pdf"
                    AnchorId="form-browse-button"
                    DragDropZoneVisible="false"
                    Id="form-file-uploader"
                    Mode="InputFileMode.SaveToTemporaryFolder"
                    OnCompleted="OnFormUploadCompleted"
                    OnProgressChange="OnFormUploading"/>
@code {
    bool _formUploading;
    void OnFormUploading()
    {
        _formUploading = true;
    }
    async Task OnFormUploadCompleted(IEnumerable<FluentInputFileEventArgs> files)
    {
        _formUploading = false;
    }
}
```

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser: Microsoft Edge, Mozilla FireFox
* .NET and Fluent UI Blazor library Version: 8.0.400/4.10.1

**Comment by vnbaaij** [comment]
I can't find what is causing this. As an alternative I would use the `Disabled` property instead. Tested that and can confirm it works.

Will leave this open for a bit but it is not going to be treated as a high priority issue.

**Comment by Leon99** [comment]
Thanks @vnbaaij, `Disabled` plus a separate ProgressRing is what I ended up doing as a workaround. Would be good to, at least, make a note of this limitation in the documentation, to make sure others don't spend as much time as I did trying to localize the issue upon testing a number of changes. I'd say it's not an unexpected use case, since file uploading always requires a progress indicator and using `Loading` on a button seems to be the easiest way to do it.

**Comment by vnbaaij** [comment]
> Thanks @vnbaaij, `Disabled` plus a separate ProgressRing is what I ended up doing as a workaround. Would be good to, at least, make a note of this limitation in the documentation, to make sure others don't spend as much time as I did trying to localize the issue upon testing a number of changes. 

Yes, I'll make a note of that. This is supper 'low hanging fruit' where you can help the community yourself (an us) by creating a simple PR for it.

> I'd say it's not an unexpected use case, since file uploading always requires a progress indicator and using `Loading` on a button seems to be the easiest way to do it.

It is not an unexpected use case indeed, but you are the first person that has reported this in the ~2.5 years we've had this component.

I'm adding the 'community:good-first-issue' and 'community:contribution' labels with the hope that someone is willing to dive into this deeper.

**Comment by dvoituron** [comment]
I don't think you can do that: each time the page will be rendered, this JS code will be executed and a click event will be added.

```js
button.addEventListener("click", function (e) {
    fileInput.click();
});
```

**Comment by MarvinKlein1508** [comment]
@dvoituron yea but you can prevent this by removing the handler first.
```js
export function attachClickHandler(buttonId, fileInputId) {
    var button = document.getElementById(buttonId);
    var fileInput = document.getElementById(fileInputId);

    if (button && fileInput) {
        button.removeEventListener("click");
        button.addEventListener("click", function (e) {
            fileInput.click();
        });
    }
}
```

**Comment by dvoituron** [comment]
The `removeEventListener` method requires both the type of the event (e.g., "click") and a reference to the exact function that was added as an event listener. Without providing the function reference, the browser doesn’t know which event listener to remove.

**Comment by MarvinKlein1508** [comment]
@dvoituron my bad. How about:
```js
export function attachClickHandler(buttonId, fileInputId) {
    var button = document.getElementById(buttonId);
    var fileInput = document.getElementById(fileInputId);

    if (button && fileInput) {
        const handler = function (e) {
            fileInput.click();
        };

        button.removeEventListener("click", handler);
        button.addEventListener("click", handler);
    }
}
```

**Comment by MarvinKlein1508** [comment]
Or we can simplyfy it even more:
```js
export function attachClickHandler(buttonId, fileInputId) {
    var button = document.getElementById(buttonId);
    var fileInput = document.getElementById(fileInputId);

    if (button && fileInput && !button.onclick) {
        button.onclick = function (e) {
            fileInput.click();
        };
    }
}
```

**Comment by dvoituron** [comment]
To verify :-)

I'm not sure: 
- The `handler` function is defined each time `attachClickHandler` is called.
  This creates a new function reference every time the method is invoked.
- However, since handler is a new function instance, it won't match any previously attached event listeners, even if their functionality is identical.

Using `!button.onclick` is better, but if the dev added a manual click on this button (for another stuff), that will not work. Sorry :-)

I understand, but not easy... may be, adding a "flag" to detect this "addEventListener".

**Comment by MarvinKlein1508** [comment]
@dvoituron damn I hate JS. But you were right. I think the only way is by setting a data attribute then.

```js
export function attachClickHandler(buttonId, fileInputId) {
    var button = document.getElementById(buttonId);
    var fileInput = document.getElementById(fileInputId);

    if (button && fileInput && !button.hasAttribute("data-click-handler-attached")) {

        button.addEventListener("click", function (e) {
            fileInput.click();
        });

        button.setAttribute("data-click-handler-attached", "true");
    }
}
```

**Comment by dvoituron** [comment]
Argg... not using `setAttribute`, because you will have this info in the HTML code. You can dynamically create a property 
`button.fluentuiBlazorFileInputHandlerAttached = true` ;-)

But that is the idea.

**Comment by MarvinKlein1508** [comment]
Damn I didn't even know that's possible! But it works fine for me. Guess you'll never stop learning.

```js
export function attachClickHandler(buttonId, fileInputId) {
    var button = document.getElementById(buttonId);
    var fileInput = document.getElementById(fileInputId);

    if (button && fileInput && !button.fluentuiBlazorFileInputHandlerAttached) {

        button.addEventListener("click", function (e) {
            fileInput.click();
        });

        button.fluentuiBlazorFileInputHandlerAttached = true
    }
}
```

**Comment by vnbaaij** [comment]
Like the dynamic attribute! Although, how bad would it be to have the data attribute in the HTML. That is what they are there for, right?

**Comment by dvoituron** [comment]
> Although, how bad would it be to have the data attribute in the HTML. That is what they are there for, right?

If this information is useful for the user interface or needs to be known by the developer. But not for “internal” use.

**Comment by MarvinKlein1508** [comment]
@vnbaaij if I have ever learnt one thing in Blazor than it is you should almost prevent manipulating the DOM using JS. Makes many stuff much harder to maintain in the longrun. In this case I thought it wouldn't be an issue since the attribute will be removed everytime the loading spinner occurs which is excatly what this problem is about. 

But if we can prevent using it, why not.

If you both agree with this approach then I will create a PR for this and add a new example for this. Not sure about tests though. I'Ve never created any for blazor components.

**Comment by dvoituron** [comment]
But I'd rather find a way to “detect” this behavior from C#.
Otherwise, calling this method won't always do the job. That is not "logical".
Is it possible to keep a similar "flag" in C#?

```csharp
await Module.InvokeVoidAsync("attachClickHandler", AnchorId, Id);
```

**Comment by MarvinKlein1508** [comment]
@dvoituron I think this will be pretty difficult because the the issue is a combination of 2 different components. How is the `FluentInputFile` component supposed to know that the FluentButton has altered it's rendering.

The only logical way I can think of is checking the property before calling the method. But I find it much harder to understand than simply repeatly calling the method to register the handler. IMO it isn't a bad design either because methods are designed to return when nothing has to be done.
