### ISSUE TITLE
fix: [Unable to select Month and year in FluentDatePicker] in [ FluentDatePicker]

### ISSUE THREAD

**Issue by pradm777** [microsoft/fluentui-blazor#2756]
# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by dvoituron** [comment]
Duplicated #2746
