### ISSUE TITLE
feat: add ability to set tooltip for column header to FluentDataGrid

### ISSUE THREAD

**Issue by Leon99** [microsoft/fluentui-blazor#2757]
# 🙋 Feature Request

I'd like to set a tooltip for a column header that is different from Title, but it seems impossible at the moment.

## 💁 Possible Solution

I tried to override `HeaderCellItemTemplate`, but generated code misses a necessary attribute:
![image](https://github.com/user-attachments/assets/74ab0ee3-40a7-4be9-8195-0dde5290b928)
That autogenerated attribute that applies the necessary styling is missing when setting `HeaderCellItemTemplate` as 
```
<div class="col-title">
   <div class="col-title-text" title="@tooltip">@Title</div>
</div>
```

**Comment by vnbaaij** [comment]
In determining what tooltip to show in the header, the following code is now used:

```
string? tooltip = Tooltip ? Title : null;
```
(in `ColumnBase.razor`, right above where your `<div...` code comes from.

What if we change that to:
```
string? tooltip = Tooltip ? (TooltipText ?? Title) : null;
```

That way you could use the `TooltipText` parameter to change the tooltip text even with the standard header template.

ps: In your HeaderCellItemTemplate, I think you should be able to get that attribute added by using `::deep` in your own styles

**Comment by vnbaaij** [comment]
Turns out we can't do it in the way I suggested. When rendering the headers, we do not have an actual item available yet that can act as the context for getting the `TooltipText` function executed,

**Comment by vnbaaij** [comment]
Creating a new PR for this. We have now solved this by adding a new `HeaderTooltip` parameter to the column:

```
<TemplateColumn Tooltip="true" HeaderTooltip="Flag of each team" TooltipText="@(c => "Flag of " + c.Name)" Title="Rank"...
```

![image](https://github.com/user-attachments/assets/9a249a45-b345-4ed5-b0a4-8261a5aff4d7)
