### ISSUE TITLE
fix: Right-To-Left in Tree View

### ISSUE THREAD

**Issue by aminmashayekhi** [microsoft/fluentui-blazor#2766]
Tree View component not shown correctly in Righ-To-Left direction:
![image](https://github.com/user-attachments/assets/3de52d64-9650-4fb4-be66-1aa49821e584)

**Comment by vnbaaij** [comment]
Will be fixed in next release:

![image](https://github.com/user-attachments/assets/17a846f7-3e2c-48c5-bedf-8dd3044a92d7)
