### ISSUE TITLE
fix: Blazor Fluent UI Components do not work in Blazor Hybrid and Blazor Hybrid with Web (shared UI)

### ISSUE THREAD

**Issue by adanbrownpaca** [microsoft/fluentui-blazor#2779]
# 🐛 Bug Report

I have followed the instructions noted on the documentation to use Fluent UI Blazor for my MAUI Hybrid Blazor project (and with Web), but the UI will not load on any of the target platforms (Windowns, Android, etc.).

## 💻 Repro or Code Sample

Create a new project using Visual Studio template:
![image](https://github.com/user-attachments/assets/ecbbd87c-42d7-4888-9380-d6601810fb77)

or

![image](https://github.com/user-attachments/assets/646c7b2c-f118-45e0-a4e7-7fa65cf8e71f)

Add the necessary nuget packages:
dotnet add package Microsoft.FluentUI.AspNetCore.Components
dotnet add package Microsoft.FluentUI.AspNetCore.Components.Icons
dotnet add package Microsoft.FluentUI.AspNetCore.Components.Emoji

Modify the MauiProgram.cs
builder.Services.AddFluentUIComponents();

Update MainLayout.razor
<FluentLayout>
    <FluentHeader>
Test App
    </FluentHeader>
    <FluentStack Class="main" Orientation="Orientation.Horizontal" Width="100%">
        <NavMenu />
        <FluentBodyContent Class="body-content">
            <div class="content">
                @Body
            </div>
        </FluentBodyContent>
    </FluentStack>
    <FluentFooter>
        <a href="https://www.fluentui-blazor.net" target="_blank">Documentation and demos</a>
        <FluentSpacer />
        <a href="https://learn.microsoft.com/en-us/aspnet/core/blazor" target="_blank">About Blazor</a>
    </FluentFooter>
</FluentLayout>

Update NavMenu.razor
@rendermode InteractiveServer

<div class="navmenu">
    <input type="checkbox" title="Menu expand/collapse toggle" id="navmenu-toggle" class="navmenu-icon" />
    <label for="navmenu-toggle" class="navmenu-icon"><FluentIcon Value="@(new Icons.Regular.Size20.Navigation())" Color="Color.Fill" /></label>
    <nav class="sitenav" aria-labelledby="main-menu">
        <FluentNavMenu Id="main-menu" Collapsible="true" Width="250" Title="Navigation menu" @bind-Expanded="expanded" CustomToggle="true">
            <FluentNavLink Href="/" Match="NavLinkMatch.All" Icon="@(new Icons.Regular.Size20.Home())" IconColor="Color.Accent">Home</FluentNavLink>
            <FluentNavLink Href="counter" Icon="@(new Icons.Regular.Size20.NumberSymbolSquare())" IconColor="Color.Accent">Counter</FluentNavLink>
            <FluentNavLink Href="weather" Icon="@(new Icons.Regular.Size20.WeatherPartlyCloudyDay())" IconColor="Color.Accent">Weather</FluentNavLink>
        </FluentNavMenu>
    </nav>
</div>

@code {
    private bool expanded = true;
}

Update index.html
<script app-name="[TestApp]" src="./_content/Microsoft.FluentUI.AspNetCore.Components/js/initializersLoader.webview.js"></script>

## 🤔 Expected Behavior

The application should load on Windows, Android, etc.

## 😯 Current Behavior

The application does not load:
![image](https://github.com/user-attachments/assets/d91c9277-9812-4330-b471-196b34e00d45)

## 💁 Possible Solution

Is the new update (with .Net 9 target broke it?)

**Comment by vnbaaij** [comment]
With .NET 9, you need to remove the temporary workaround as mentioned at https://www.fluentui-blazor.net/BlazorHybrid

**Comment by vnbaaij** [comment]
> In the fluent ui blazor template when go to weather component I am getting the following error when StreamRendering is enabled. 
> If I dont enable sreamrendering it is working fine


See https://github.com/microsoft/fluentui-blazor/issues/3068#issuecomment-2559246806. Will be fixed in next release of the templates
