### ISSUE TITLE
fix: The OnClick event in FluentMenuItem does not function when it is an item within a FluentMenuButton.

### ISSUE THREAD

**Issue by aminmashayekhi** [microsoft/fluentui-blazor#2780]
# 🐛 Bug Report

When FluentMenuItem is nested within FluentMenuButton, its OnClick event is not triggered.

## 💻 Repro or Code Sample

```
<FluentMenuButton ButtonAppearance="Appearance.Stealth" Text="File" >
    <FluentMenuItem Id="itmAccCodeList" OnClick="@((e) => itmAccCodeList_Click(e))" >AccCode List</FluentMenuItem>
</FluentMenuButton>

@code {
    private void itmAccCodeList_Click(MouseEventArgs e)
    {
        // Do somthing like:
        Console.WriteLine("Worked!");
    }
}
```
## 🤔 Expected Behavior

The itmAccCodeList_Click event is triggered when a FluentMenuItem is clicked.

## 😯 Current Behavior

No action occurred when it is a child of FluentMenuButton.

**Comment by dvoituron** [comment]
That will be fixed in the next Release: #2784 

In the meantime, you can use the `FluentMenuButton.OnMenuChanged` event to detect when a menu item is clicked.
