### ISSUE TITLE
fix: FluentCheckbox not be able to render correctly with @bind- attributes when unsafe-eval is not part of the Content Security Policy

### ISSUE THREAD

**Issue by aDisplayName** [microsoft/fluentui-blazor#2783]
# 🐛 Bug Report

When "unsafe-eval" is not specified in Content Security Policy directive, the rendering of FluentCheckbox will fail in client-side interactive rendering

## 💻 Repro or Code Sample

Here is the part of the `App.razor`
```razor
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <meta http-equiv="Content-Security-Policy" 
          content="script-src 'self' 'wasm-unsafe-eval';">
    <link href="_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css" rel="stylesheet" />
    <HeadOutlet />
</head>

<body>
<Routes/>
<script src="_framework/blazor.web.js"></script>
</body>

</html>
```

And here is one of the razor page using interactivewebassembly rendering

```razor
@page "/"
@using Microsoft.FluentUI.AspNetCore.Components
@rendermode @(new InteractiveWebAssemblyRenderMode(prerender: false))

<FluentCheckbox @bind-CheckState="@_isChecked">Will fail</FluentCheckbox>
<FluentCheckbox @bind-Value="@_isChecked">Will fail</FluentCheckbox>
<FluentCheckbox CheckedState="@_isChecked">Will not fail</FluentCheckbox>
<FluentCheckbox Value="@_isChecked">Will not fail</FluentCheckbox>

@code {
  bool _isChecked=false;
}
```

## 🤔 Expected Behavior

Fluent Checkbox should be able rendered without problem.

## 😯 Current Behavior

Following error message shown in the console log.
![image](https://github.com/user-attachments/assets/4492bca7-213d-4f51-aa14-c829a64823f6)

## 💁 Possible Solution

The workaround is to change from "wasm-unsafe-eval" to "unsafe-eval", but this violates our IT's CSP requirements.
```
    <meta http-equiv="Content-Security-Policy" 
          content="script-src 'self' 'unsafe-eval';">
```

## 🌍 Your Environment

* Windows 11
* Microsoft Edge Version 129.0.2792.79 (Official build) (64-bit)
* .NET 8.0
* Microsoft.FluentUI.AspNetCore.Components 4.10.0

**Comment by vnbaaij** [comment]
Have tried this with a regular `InputCheckbox` component as well. Is so, does it generate the same error? If not, please do so and report back. Thanks in advance.
I have a strong feeling this is a more general Blazor issue and not a specific library issue.

**Comment by aDisplayName** [comment]
@vnbaaij, I've published an example code https://github.com/aDisplayName/bugsamplecode/tree/main/20241008/FluentRender, which is based .NET 8 Blazor Web App template.

There are three Webassembly page:
* /counter: Using both `<FluentCheckbox/>` and `<InputCheckbox/>`
* /counter2: Using only `<FluentCheckbox/>`
* /counter3: Using only `<InputCheckbox/>`

It seems using `<InputCheckbox/>` alone will not trigger the error.

**Comment by vnbaaij** [comment]
Ok, good to have reproduction code. But am I supposed to download the whole repo with all you bug submissions :)

I can create an ew project based on the template myself and copy over the pages in question from your side but want to know which options you choose when creating the site. Going with the code I'd say 'Authentication = None' and 'Interactive render mode = None'. Correct?

**Comment by vnbaaij** [comment]
I'm seeing an error in the InputCheckbox variant ( counter 2 page) as well:
![Image](https://github.com/user-attachments/assets/09451786-a0b6-4f31-9ae9-b5d3c215570c)

So more strongly think it is a general Blazor issue now...

With just the `FluentCheckbox` I actually get a different error:
![Image](https://github.com/user-attachments/assets/24b1eaa1-a48d-4673-a3af-b0b5f044dcbf)

And with using both options, I get both errors:
![Image](https://github.com/user-attachments/assets/95c32233-8092-472a-82e9-eb7b49eb7f2e)


I suggest you create an issue in the aspnetcore repo.

**Comment by aDisplayName** [comment]
@vnbaaij  Thank you for looking into. I've submitted a bug in aspnet core.

**Comment by vnbaaij** [comment]
Ok, thanks. Will keep it open here to await response from the Blazor team
