### ISSUE TITLE
[WebToolsE2E][Aspire] Click Help on the Aspire Dashboard page, and the "Close" button prompt will automatically appear.

### ISSUE THREAD

**Issue by v-reinawang** [microsoft/fluentui-blazor#2787]
**REGRESSION INFO**: Worked in Aspire 8.2.1

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.402
3. Install Aspire 9.0 RC1 [9.0.0-preview.4.24480.1]

**REPRO STEPS**

1. Open CMD, run following command to create an Aspire Starter App project

```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
```

2. Dotnet run the project in CMD, and open URL in the browser.
   `dotnet run`

**ACTUAL**
Click Help, the prompt ‘Close’ will be automatically displayed.
![Image](https://github.com/user-attachments/assets/1c5fc2b8-6cf4-4360-a652-4d66ca92485e)

Also reproduce the Add filter page in Structured and Traces
![Image](https://github.com/user-attachments/assets/99d66412-6105-498a-8d20-e920f23a97ac)

**EXPECTED**
When the mouse hovers over the close button, the prompt "Close" will appear.

**Comment by adamint** [comment]
This occurs in the examples

**Comment by vnbaaij** [comment]
Fixed with PR mentioned. Will be in next release
