### ISSUE TITLE
fix: Problems in FluentMenu weren't correctly fixed

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#2788]
# 🐛 Bug Report

I tried out 4.10.2 and the fixes in it don't work. This PR is wrong: https://github.com/microsoft/fluentui-blazor/pull/2744

It added `display:fixed`. It should be `position:fixed`.

Also, a PR added a z-index to fix content not being hidden: https://github.com/microsoft/fluentui-blazor/pull/2772. However, it is incomplete.

It added the z-index to `FluentMenuProvider` but it didn't add it to `FluentTooltipProvider` which was supposed to get `position: fixed` in https://github.com/microsoft/fluentui-blazor/pull/2744

## 🤔 Expected Behavior

I suggest creating a page to test the various scenarios. Changes appear to be made without testing.

The page would have a way to test menus and tooltips don't add scroll bars. Menus and tooltips appear above other content, etc.

## 😯 Current Behavior

Current output:

![Image](https://github.com/user-attachments/assets/06468188-3dbc-4eb0-a0b6-6446b917a559)

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Hmm. I think I mixed some stuff up there. Sorry about that. I'll see if we can get a fix to fix that out asap.

**Comment by ksbecker** [comment]
I'm curious, would this impact the `FluentMenuButton` control? After upgrading to v4.10.1 it stopped working on my site and v4.10.2 didn't fix it either. I created a new project, copied the example site code to the home page and it's not working. I also downloaded the VS 2022 preview and latest 9.0rc to see if that fixes it, but no such luck.

https://github.com/ksbecker/FluentUIMenuButtonBug

**Comment by JamesNK** [comment]
You probably need to add `FluentMenuProvider`. IMO it shouldn't silently fail if a provider is missing. It should either display menu without using the provider, or throw an error and say that the provider is missing.

**Comment by ksbecker** [comment]
I think I tried that, but I’ll try it again when I get into the office tomorrow. I was able to roll back to v4.9.3 for now. If that is the case, maybe I’ll update the documentation with a PR.

I just noticed your name, @JamesNK. Thanks for your many years of contribution to .NET development.

**Comment by vnbaaij** [comment]
> I'm curious, would this impact the `FluentMenuButton` control? After upgrading to v4.10.1 it stopped working on my site and v4.10.2 didn't fix it either. I created a new project, copied the example site code to the home page and it's not working. I also downloaded the VS 2022 preview and latest 9.0rc to see if that fixes it, but no such luck.
> 
> https://github.com/ksbecker/FluentUIMenuButtonBug
> 
> If I roll back to v4.9.3 it works.

It is probably related indeed. Will try to take a look at your repro steps later today.

**Comment by vnbaaij** [comment]
> I think I tried that, but I’ll try it again when I get into the office tomorrow. I was able to roll back to v4.9.3 for now. If that is the case, maybe I’ll update the documentation with a PR.
> 
> I just noticed your name, [@JamesNK](https://github.com/JamesNK). Thanks for your many years of contribution to .NET development.

https://github.com/microsoft/fluentui-blazor/pull/2792

**Comment by dvoituron** [comment]
> You probably need to add `FluentMenuProvider`. IMO it shouldn't silently fail if a provider is missing. It should either display menu without using the provider, or throw an error and say that the provider is missing.

You're right... I've added a test to check the presence of this provider: #2793

**Comment by ksbecker** [comment]
Confirmed in my project, adding `FluentMenuProvider` works for me with v4.10.2.
