### ISSUE TITLE
DataGrid RowFocus DoubleClick

### ISSUE THREAD

**Issue by RobDene** [microsoft/fluentui-blazor#2789]
# 🙋 Feature Request

I know this was raised previously under https://github.com/microsoft/fluentui-blazor/issues/1953 and you've closed integrating into Multiselect .
However that doesn't seem to allow a double-click as it doesn't pass the row details - we use rowfocus for that which only support single clicks  - am I missing something ?

**Comment by RobDene** [comment]
We do have a workaround , its a bit around the houses so wondered if there is a more elegant way or if it can be added
<FluentDataGrid OnRowFocus="@HandleRowFocus" @onclick="@(() => OnSingleClick())" ondblclick="@(() => OnDoubleClick())" >

@code{
    string ClickMessage = "";
    FluentDataGridRow<VVM> vRow; //remember highlighted row

    private void OnSingleClick()
    {
        // If it's a double-click, do nothing
        if (isDoubleClick)
        {
            return;
        }

        // Handle single click action
        ClickMessage = "Single click detected! - ID: " + vRow.Item.ID;

        // Start a timer to reset the double click flag
        clickTimer = new System.Timers.Timer(1000); // Adjust time as needed
        clickTimer.Elapsed += (s, e) =>
        {
            isDoubleClick = false;
            clickTimer.Stop();
            clickTimer.Dispose();
        };
        clickTimer.Start();
    }

     private void OnDoubleClick()
    {
        isDoubleClick = true;

        // Handle double click action
        ClickMessage = "Double click detected! - ID: " + vRow.Item.ID;
    }

    private void HandleRowFocus(FluentDataGridRow<VVM> row)
    {
        vRow = row;
        int id = row.Item.ID;
    }
}

**Comment by dvoituron** [comment]
I may have misunderstood something, but why not use `OnRowDoubleClick`, which gives you information about the double-clicked line?

**Comment by RobDene** [comment]
> I may have misunderstood something, but why not use `OnRowDoubleClick`, which gives you information about the double-clicked line?

?? we are using OnDoubleClick from fluent datagrid - can't see OnRowDoubleClick as an attribute ?

**Comment by dvoituron** [comment]
I don't seem to understand your request.
If you want to be able to double-click on a line and get details of that element, you have the `OnRowDoubleClick` attribute. 

See the live Example on our Demo website (Remote Data example)
```xml
                                                   vvvvvvvvvvvvvvvv
<FluentDataGrid ItemsProvider="foodRecallProvider" OnRowDoubleClick="@(()=>DemoLogger.WriteLine("Row double clicked!"))" Virtualize="true">
  <PropertyColumn Title="ID" Property="@(c => c!.Event_Id)" />
  ...
</FluentDataGrid>
```
https://www.fluentui-blazor.net/DataGrid#remotedata

**Comment by RobDene** [comment]
Ah - found the issue - that particular dev was using a slightly older version of visual studio which wasn't displaying that as an attribute option !

**Comment by RobDene** [comment]
That's helpful as it passes the row details  but if you code for both a single click and a double click, the single click event always gets triggered twice followed by the double click event - perhaps there needs to be a delay on the single click event that ignores the event if it becomes a double click. We are building in the delay ourselves.

**Comment by vnbaaij** [comment]
Addressed with PR mentioned above. Will be in next release.
