### ISSUE TITLE
fix: DatePicker popup is hidden in MultiSplitterPane

### ISSUE THREAD

**Issue by hygehyge** [microsoft/fluentui-blazor#2791]
# 🐛 Bug Report

Calendar popup of DatePicker that located in MultiSplitterPane is hidden by multi-splitter-bar.
![Image](https://github.com/user-attachments/assets/856565f5-981d-4b9f-a6a8-e5b5609e2500)

## 💻 Repro or Code Sample

```razor
@page "/"
@rendermode InteractiveServer

<PageTitle>Home</PageTitle>

<h1>DatePicker popup is hidden</h1>

<FluentMultiSplitter Orientation="Orientation.Vertical">
    <FluentMultiSplitterPane>
        <FluentDatePicker/>
    </FluentMultiSplitterPane>
    <FluentMultiSplitterPane>
        <p>ABC</p>
    </FluentMultiSplitterPane>
</FluentMultiSplitter>
```

## 🤔 Expected Behavior

Calendar should be visible over other components.

## 😯 Current Behavior

Calendar is hidden by multi-splitter-bar.

## 🌍 Your Environment

* OS & Device: Windows 11 23H2 22631.4317
* Browser: Microsoft Edge 129.0.2792.79
* .NET: 8.0.400
* Fluent UI Blazor: 4.10.2

**Comment by dvoituron** [comment]
This behaviour is due to the presence of this style `overflow` in the `FluentMultiSplitter` component. 
You can disable it (see example below) if you manage the minimum panel size correctly. 
We will try to find a solution that is compatible with both functions.

```css
.fluent-multi-splitter > .fluent-multi-splitter-pane {
   overflow: unset !important;
}
```

**Comment by vnbaaij** [comment]
Workaround provided. Closing this.
