### ISSUE TITLE
fix: FluentSlider's FluentSliderLabels doesn't recover from Disabled=true

### ISSUE THREAD

**Issue by RobGess** [microsoft/fluentui-blazor#2794]
# 🐛 Bug Report

If a FluentSlider's `Disabled=true` by default, the FluentSliderLabels doesn't recover properly when setting `Disabled=false` during runtime. If `Disabled=false` by default and manually toggled during runtime, everything works fine.

**Current behavior:** Slider `Disabled=true` by default and was set to `false` during runtime (FluentSliderLabels are still washed out).
![Image](https://github.com/user-attachments/assets/0057f402-2593-4376-acae-44bb0a953b05)

**Expected behavior:** Slider `Disabled=false` by default and toggled during runtime (FluentSliderLabels are displayed properly).*
![Image](https://github.com/user-attachments/assets/f697cb0a-29d0-4c8a-9a49-bc9739d4d916)

## 💻 Repro or Code Sample

See [FluentBlazorTest](https://github.com/RobGess/FluentBlazorTest) or:

1. Create new fluent blazor project: `dotnet new fluentblazor --name FluentBlazorTest`
2. Add `@rendermode InteractiveServer` to Home.razor pager
3. Add FluentSlider, FluentButton and FluentLabel to toggle Disabled property and display current state:
```
<FluentStack Orientation="Orientation.Vertical" VerticalGap="30" Style="margin-top:2rem;">
    <FluentSlider Min="0" Max="100" Step="1" Disabled=@_disabled Style="width:50%">
        <FluentSliderLabel Position="0">0</FluentSliderLabel>
        <FluentSliderLabel Position="10">10</FluentSliderLabel>
        <FluentSliderLabel Position="20">20</FluentSliderLabel>
        <FluentSliderLabel Position="30">30</FluentSliderLabel>
        <FluentSliderLabel Position="40">40</FluentSliderLabel>
        <FluentSliderLabel Position="50">50</FluentSliderLabel>
        <FluentSliderLabel Position="60">60</FluentSliderLabel>
        <FluentSliderLabel Position="70">70</FluentSliderLabel>
        <FluentSliderLabel Position="80">80</FluentSliderLabel>
        <FluentSliderLabel Position="90">90</FluentSliderLabel>
        <FluentSliderLabel Position="100">100 %</FluentSliderLabel>
    </FluentSlider>

    <FluentButton OnClick="ToggleDisabled">Toggle slider</FluentButton>
    <FluentLabel>Slider disabled is @_disabled</FluentLabel>
</FluentStack>
```

## 🤔 Expected Behavior

FluentSliderLabel's color should be set properly.

## 😯 Current Behavior

FluentSliderLabel's color is not set properly.

## 🌍 Your Environment

* OS: Windows 11 Enterprise
* Google Chrome Version 129.0.6668.101 (64-Bit), MS Edge Version 129.0.2792.89 (64-Bit)
* Microsoft.FluentUI.AspNetCore.Components 4.10.2

**Comment by vnbaaij** [comment]
Will be fixed in next release. See PR #2796
