### ISSUE TITLE
fix: 'Paceholder" mispelling(should be "Placeholder") used in Template in src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/Index.razor (and also in one other template file)

### ISSUE THREAD

**Issue by jhogan05** [microsoft/fluentui-blazor#2799]
# 🐛 Bug Report

	

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Fixed with PR mentioned. I did a 'Find all' through the solution and it gave me one result only.

**Comment by jhogan05** [comment]
OFFICIAL

When searching via my GitHub App on iOS it was matching also in:

tests/TemplateValidation/IndividualAcccounts/A-SSR/Components/Account/Pages/Manage/Index.razor




[cid:644adae3-c663-422d-96be-942f54916cf5]



Dr Jonathon Hogan-Doran
Senior Specialist in Geriatric & Adult Oncology

Royal Adelaide Hospital, Mount Barker & Broken Hill Hospital
Provider Nr: 228457BT / 228457CJ

Level 6 (Blue Space) – Room 6E-367
Ext x22024 – Speed Dial 81861

 Mon

Tue

Wed

Thu

Fri



BHH: AM

RAH: PM



SA EMR





Med Onc

(RAH)



Med Onc: AM

SA EMR: PM





Med Onc

(RAH)



         All Referrals – Broken Hill – 02-8580-4936 (Fax),  Mount Barker – 08-8219-9982 (Fax)



________________________________

**Comment by vnbaaij** [comment]
Ah, that is actually a result of using the template to build a site. If the source is fixed, this is going to be fixed as well,
