### ISSUE TITLE
feat: add support for Byte in FluentNumberField

### ISSUE THREAD

**Issue by markoweb2** [microsoft/fluentui-blazor#2802]
# 🙋 Feature Request

Please add support for the Byte type in FluentNumberField.

## 🤔 Expected Behavior

Should accecpt Byte as underlying value.

## 😯 Current Behavior

Currently throws an error `The type 'System.Byte' is not a supported numeric type.`

## 🔦 Context

You are already supporting Short, Int, Long, etc. 
Adding Byte to the list should be trivial.
Since my program uses Bytes extensively, all the way to the database level, it would be a massive pain to have to create new cloned classes for everything (eg. with Byte replaced for Short) just to data bind to FluentNumberField.

PS! Haven't checked, but are unsigned types supported? `ushort, uint, ulong`?
Better add support for those as well if they aren't currently supported.

## 💻 Examples

```
<FluentNumberField Label="Max employees:" @bind-Value=this.Entity.MaxEmployees Min="1" Max="10" />

@code
{
    private SomeClass Entity { get; set; }

    public class SomeClass
    {
         public byte MaxEmployees { get; set; }
    }
}
```

**Comment by vnbaaij** [comment]
We will consider this for the next version. Currently the NumberField is too broken and I would advise you not to use it.
