### ISSUE TITLE
feat: add translation possibility to MessageBox Show methods

### ISSUE THREAD

**Issue by markoweb2** [microsoft/fluentui-blazor#2805]
# 🙋 Feature Request

```
ShowSuccess / ShowSuccessAsync
ShowWarning / ShowWarningAsync
ShowInfo / ShowInfoAsync
ShowError / ShowErrorAsync
```

These methods only take input for the message and the title, but the OK button can't be translated.
Would be nice to be able to do that without having to write up more boiler-plate code to do this via `MessageBox` custom content.

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/0c1d6dc5-c7f1-43d4-9f87-3f8e61dfc004)

## 💁 Possible Solution

Same logic as with this method, add an extra parameter:
![Image](https://github.com/user-attachments/assets/fb4c9f85-3d3e-4122-b65f-0533c0bb3f86)

PS! An error message with an OK button should not exist, an error is never OK. Use the word "Close" instead.
`ShowError / ShowErrorAsync`
![Image](https://github.com/user-attachments/assets/6c72516f-5357-47cb-a525-571fb9f967b8)

Even Microsoft UI guidelines mention this (granted these were refined a long while back, but I haven't seen any newer guidelines for error messages):

https://learn.microsoft.com/en-us/windows/win32/uxguide/mess-error

![Image](https://github.com/user-attachments/assets/cbece549-3094-437d-9345-8ec95d017fda)

**Comment by vnbaaij** [comment]
Will be fixed in PR mentioned above and in next release.
