### ISSUE TITLE
fix: Wrong colors in FluentIcon

### ISSUE THREAD

**Issue by markoweb2** [microsoft/fluentui-blazor#2814]
# 🐛 Bug Report

Whichever `Icons.Color` item comes first, will define the color scheme for all the other colored icons.

## 💻 Repro or Code Sample

```
<PageTitle>Home</PageTitle>

<FluentIcon Value="@(new Icons.Color.Size32.Person())" />
<FluentIcon Value="@(new Icons.Color.Size32.Home())" />
<FluentIcon Value="@(new Icons.Color.Size32.Edit())" />
```

Produces:
![Image](https://github.com/user-attachments/assets/44d306ea-d0b2-4ce0-ab39-270fb3d09f14)

While this code:
```
<PageTitle>Home</PageTitle>

<FluentIcon Value="@(new Icons.Color.Size32.Home())" />
<FluentIcon Value="@(new Icons.Color.Size32.Person())" />
<FluentIcon Value="@(new Icons.Color.Size32.Edit())" />
```

Produces:
![Image](https://github.com/user-attachments/assets/c202f7d9-083a-43d9-8fb2-6f33c5185d14)

## 🤔 Expected Behavior

I would expect each icon to be in their originally intended color.

## 😯 Current Behavior

Every subsequent icon will pick up the color scheme from the very first icon used. (perhaps a nice feature to keep, but make it an opt-in via a Property or something)

## 🔦 Context

Use multiple colored icons on a page.

## 🌍 Your Environment

* OS = Windows
* Browser = Microsoft Edge, Google Chrome
* .NET and Fluent UI Blazor library Version = 8.0.10 and 4.10.2
* Visual Studio 2022 (17.11.5)

**Comment by vnbaaij** [comment]
Ha, that is a nice one. Will look into it.

**Comment by vnbaaij** [comment]
We've traced it down to an optimization step in the icons repo. Fix has been submitted and PR has been approved already. We will deliver an updated package with the next release.
Brace for even more colors... 😁

**Comment by vnbaaij** [comment]
With latest icons (with id fix applied):
![Image](https://github.com/user-attachments/assets/f47b266b-a56c-464c-a52f-2f4708239aeb)
