### ISSUE TITLE
StreamRendering causes formatting issues with FluentDataGrid when page contains FluentOverlay

### ISSUE THREAD

**Issue by marqdouj** [microsoft/fluentui-blazor#2815]
# 🐛 Bug Report

Using the templated Weather page, I removed the FluentProgressRing and added a FluentOverlay instead.
When StreamRendering is used the columns are mis-aligned:

## 💻 Repro or Code Sample

```
@attribute [StreamRendering] //causes issue

<FluentOverlay @bind-Visible=@loading Opacity="0.4">...
```

## 🤔 Expected Behavior

I would expect the column rendering to be the same.

## 😯 Current Behavior

When StreamRendering is used the columns are mis-aligned
![Image](https://github.com/user-attachments/assets/4a189a05-a427-4e76-bd20-5a7c831cce5c)

When StreamRendering is not used the columns appear normal:
![Image](https://github.com/user-attachments/assets/23f7df5b-c129-4e22-8415-e4873568685b)

## 💁 Possible Solution

Unknown

## 🔦 Context

At this point, doesn't affect me - I am just experimenting.

## 🌍 Your Environment

* OS & Device: Windows 11 Home
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version 8.0.2 and 4.10.2

**Comment by vnbaaij** [comment]
We need ready-to-run reproduction code if you by us to look at this. There are too many things like @rendermode in play. We do not have resources to go hunting this down.
