### ISSUE TITLE
Add target parameter to FluentAppBarItem Class

### ISSUE THREAD

**Issue by tcukanoot** [microsoft/fluentui-blazor#2816]
# 🙋 Feature Request

We are using the FluentAppBar component as a type of left-hand navigation. We like the look and feel, but open to alternatives.
The user has requested that some of the apps/links need to open in a new browser tab. Using the "onclick" parameter seems to make the browsers treat them differently (like a pop-up). Would it be possible to just add an optional target parameter? target="_blank"

## 🤔 Expected Behavior

Clicking on an app link, with the target set, it will open in a new browser tab. 
Browser does not treat it as a pop-up.

## 😯 Current Behavior

You can set the Href on the app items, but not specify the target. 
Adding onclick makes them become a pop-up, and there is no right-click functionality.
![Image](https://github.com/user-attachments/assets/78871f82-e73b-4c0c-a964-bce43b1cb87c)

## 💁 Possible Solution

Add an optional "target" parameter
https://www.fluentui-blazor.net/AppBar#fluentappbaritem-class_properties

## 🔦 Context

Accordion or panel component.
Building links individually

## 💻 Examples

The documentation examples are great, but just with the ability to open in a new tab, instead of only in the same window.
https://www.fluentui-blazor.net/AppBar

**Comment by vnbaaij** [comment]
Hi,

The AppBar is specifically meant for in-app navigation (like the one in Teams). 
I therefore don't think this would be a good addition.
