### ISSUE TITLE
fix: scrollbar flicker when FluentProfileMenu opened at right edge

### ISSUE THREAD

**Issue by markoweb2** [microsoft/fluentui-blazor#2818]
# 🐛 Bug Report

Scrollbars flash for a split second, when opening `FluentProfileMenu`, when it is located at the right side of the screen.

## 💻 Repro or Code Sample

Default Visual Studio Blazor Web App template, add this code to homepage:

```
<PageTitle>Home</PageTitle>

<div style="display: flex; flex-direction: row; justify-content: flex-end; width: 100%;">
    <div>
        <FluentProfileMenu FullName="aaa bbbb" />
    </div>
</div>
```

## 🤔 Expected Behavior

Scrollbars should not flash when opening the profile menu.

## 😯 Current Behavior

I managed to capture the flash on the second click, but really it happens on every click (probably depends on the Gif frame capture rate):

![Image](https://github.com/user-attachments/assets/4b0d42d1-ed0d-49c7-a494-ac2575603a0d)

This code on the other hand does not produce flashing:
```
<div style="display: flex; flex-direction: row; justify-content: flex-end; width: 100%;">
    <FluentProfileMenu FullName="aaa bbbb" />
</div>
```

But this does again:
```
<div style="display: flex; flex-direction: row; justify-content: space-between; width: 100%;">
    <label>aaaa</label>
    <FluentProfileMenu FullName="aaa bbbb" />
</div>
```

This last option is what I am really trying to get working, need two elements to be in same container (so when you resize the browser, wrapping occurs as needed). One element needs to be to the left of the screen and I want the `FluentProfileMenu` to be on the right.

## 💁 Possible Solution

I think what happens is that the popup is first rendered down and to the right of the "button", basically offscreen (causing scrollbars to appear).
Then a few milliseconds later, it realizes that it is offscreen and draws it down and to the left (causing scrollbars to disappear).
When I was writing code over RDP connection to my machine, I could see the scrollbars a bit better and it seemed as if the scroll amount equaled the popup width.
Flashing does not occur, if `FluentProfileMenu` is at the center or at the left side of the screen. The latter option does not render the popup to the right of the button (another bug?), but still to the left and offscreen. Scrollbars likely don't flash, because you can't scroll in the negative direction.

## 🔦 Context

This seems to be a very similar case to this issue:
https://github.com/microsoft/fluentui-blazor/issues/2736

Which I think was never properly solved.
Applying the `body { overflow: hidden; }` in app.css stops the scrollbar flashing, but it also stops scrolling alltogether.
I have tried adding `<div style="overflow: scroll; height: 100%">` into the home page, to create like an inner scrollable container, but it still doesn't work with the body overflow..

`FluentProfileMenu` does not contain a property for `UseMenuService`, so can't use that, as suggested in the previous issue link.
And I am not so well versed in html layout to figure out other means to achieve the positioning that I want. I am sure there is some combination of elements and properties that could also work, but so far the `flex` mechanism has been my goto and worked wonders...

## 🌍 Your Environment

* OS = Windows
* Browser = Google Chrome
* .NET and Fluent UI Blazor library Version = 8.0.10 and 4.10.2
* Visual Studio 2022 (17.11.5)

**Comment by vnbaaij** [comment]
It is exactly the same as #2736 which we tried to fix in #2744 . But we made an error and have now fixed it in #2788 which will be in 4.10.3.

You can apply the changes done in that #2788 manually temporarily in the providers (see https://github.com/microsoft/fluentui-blazor/issues/2736#issuecomment-2385350981) until it is released
