### ISSUE TITLE
feat: add "keepOpen" property to/in autocomplete dropdown so it does not closes automatically after each selection

### ISSUE THREAD

**Issue by lasbrojen** [microsoft/fluentui-blazor#2819]
🙋 Feature Request
Add "keepOpen" property to autocomplete dropdown so it does not closes automatically after each selection

https://www.fluentui-blazor.net/Autocomplete

🤔 Expected Behavior
When interacting with the autocomplete dropdown, I expect the selection list to remain open until I explicitly click outside of it. This would allow me to quickly browse and select multiple options without the need for reopening the dropdown each time.

Maybe Multiple="true" should result in this behavior?

😯 Current Behavior
Currently, the autocomplete dropdown closes automatically after each selection. This behavior requires me to reopen the dropdown every time I want to choose another option, which disrupts the flow and increases interaction time.

![Image](https://github.com/user-attachments/assets/db92816d-788e-456a-b963-e9436e216303)

💁 Possible Solution
A possible solution would be to introduce a property (e.g., keepOpen) that can be set to keep the selection list open until the user clicks outside the dropdown area. 

❤️

**Comment by dvoituron** [comment]
That could be a good improvement.

I don't know what is the best: 
1. to add a new property `KeepOpen` or `AutoClose`
2. to use an existing property like `MaximumSelectedOptions` or `Multiple` to use this new behavior

**Comment by lasbrojen** [comment]
> See the PR [#2829](https://github.com/microsoft/fluentui-blazor/pull/2829)

Thank you very much - have a nice weekend 🌞
