### ISSUE TITLE
fix: PropertyColumn display bug in FluentDataGrid

### ISSUE THREAD

**Issue by markoweb2** [microsoft/fluentui-blazor#2835]
# 🐛 Bug Report

I can best describe this as some kind of z-index bug. When browser window is very small and scrolling, `PropertyColumn` title with it's horizontal border line, is displayed even when it should not be.

## 💻 Repro or Code Sample

Default Visual Studio Blazor Web App template, add this code to home page:

```
<FluentDataGrid Items="this.source">
    <PropertyColumn Title="Name" Property="@(prop => prop.Name)" />
</FluentDataGrid>

@code
{
    private IQueryable<Test> source = (new List<Test>() { new Test() { Name = "aa" }, new Test() { Name = "bb" }, new Test() { Name = "cc" }, new Test() { Name = "bb" }, new Test() { Name = "bb" } }).AsQueryable();

    private class Test
    {
        public string Name { get; set; } = String.Empty;
    }
}
```

## 🤔 Expected Behavior

When scrolling out of view, the top bar should cover the scrolled contents. For example rows and their data is covered correctly.

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/aa4c3c6e-7021-4998-aec8-9e0530554208)

## 🔦 Context

Some of the other elements that I have tried, such as `FluentTreeView`, behave correctly.

## 🌍 Your Environment

* OS = Windows
* Browser = Google Chrome
* .NET and Fluent UI Blazor library Version = 8.0.10 and 4.10.2
* Visual Studio 2022 (17.11.5)

**Comment by vnbaaij** [comment]
> When scrolling out of view, the top bar should cover the scrolled contents. For example rows and their data is covered correctly.

It only covers the scrolled content if the header is of type Sticky (`GenerateHeader` parameter). It should however remove the background and line as well.
Not sure if we can fix it with the DataGrid Web Components but should be fixable with the v4.11 'table' version of the grid.

**Comment by markoweb2** [comment]
The top row is sticky by default from the Blazor Web App template.

Found the issue - `FluentDataGrid` sets the header row with `z-index: 3`, not sure what the purpose is, as data rows don't have a `z-index` defined (maybe if you scroll the DataGrid, instead of the page, you want the header to stay visible, thus the z-index?). But the top row in the template has a `z-index: 1`, thus causing the issue.

For me the workaround was simple - `MainLayout.razor.css` file, in the `@media (min-width: 641px)` section, change the z-index, for example:

```
    .top-row {
        position: sticky;
        top: 0;
        z-index: 5; /* custom set to 5 (was 1), because FluentDataGrid header has z-index: 3 and otherwise header will show through when scrolling */
    }
```

(might need to CTRL + F5 to clear the cached stylesheet in the browser)

**Comment by vnbaaij** [comment]
Ok. Clear what caused this ten. Closing this.
