### ISSUE TITLE
fix:  [ResizableColumns=true In RTL Direction] in FluentDataGrid

### ISSUE THREAD

**Issue by NabaviFard-Mahdi** [microsoft/fluentui-blazor#2836]
# 🐛 Bug Report

When Change Direction = RTL And in Data Grid ResizableColumns=true 
When Move Mouse Left Or Right To move and change the size of the column, they work in the opposite way

## 💻 Repro or Code Sample

Company.razor
```
@page "/Company"
@using AppManager.Common.Resources
@using AppManager.Application.Modules.Company.Dtos
@using AppManager.WebAppV1.Common

@attribute [StreamRendering]

<PageTitle> @AppStringResource.CompanyPageTitle </PageTitle>

<FluentCard MinimalStyle="true" Width="100%" Height="100%">
    <FluentDataGrid TGridItem="CompanyDto" AutoFit="true" 
                    ItemKey="dto => { return dto.Id; }" 
                    ShowHover="true"
                    Data="@_companies"
                    Items="@_companies?.AsQueryable()"
                    Loading="@(_companies == null)"
                    ResizableColumns=true
                    ResizeType="DataGridResizeType.Exact"
                    Pagination="@UiHelper.PaginationState">
        
        <SelectColumn TGridItem="CompanyDto"
                      SelectMode="DataGridSelectMode.Single"
                      SelectFromEntireRow="true"
                      Property="dto => dto.Selected"
                      OnSelect="@(e => e.Item.Selected = e.Selected)"
                      Filtered="true"/>
                      
        <TemplateColumn Tooltip="true" Title="@AppStringResource.LogoTitle" Align="Align.Center" Sortable="false" Filtered="false" Width="50rem">
            <img class="flag" src="@context.Logo" alt="Logo @context.Name" />
        </TemplateColumn>

        <PropertyColumn
            Property="@(p => p.Name)" Sortable="true" Filtered="true"
            IsDefaultSortColumn="true" Align="Align.End" InitialSortDirection="SortDirection.Ascending"/>

        <PropertyColumn Property="@(p => p.EnName)" Sortable="true" Filtered="true"
                        Align="Align.End" InitialSortDirection="SortDirection.Ascending"/>

        <PropertyColumn Property="@(p => p.CodeName)" Sortable="true" Filtered="true"
                        Align="Align.End" InitialSortDirection="SortDirection.Ascending"/>

        <PropertyColumn Property="@(p => p.PhoneNumber)" Sortable="true" Filtered="true"
                        Align="Align.End" InitialSortDirection="SortDirection.Ascending"/>

        <PropertyColumn Property="@(p => p.Fax)" Sortable="true" Filtered="true"
                        Align="Align.End" InitialSortDirection="SortDirection.Ascending"/>

        <PropertyColumn Property="@(p => p.Email)" Sortable="true" Filtered="true"
                        Align="Align.End" InitialSortDirection="SortDirection.Ascending"/>

        <PropertyColumn Property="@(p => p.Address)" Sortable="true" Filtered="true"
                        Align="Align.End" InitialSortDirection="SortDirection.Ascending"/>

        <PropertyColumn Property="@(p => p.Description)" Sortable="true" Filtered="true"
                        Align="Align.End" InitialSortDirection="SortDirection.Ascending"/>

        <TemplateColumn Title="Actions" Align="@Align.End">
            <FluentButton Title="@AppStringResource.Edit" IconEnd="@(new Icons.Regular.Size16.Edit().WithColor(Color.Warning))" />
            <FluentButton  Title="@AppStringResource.Delete" IconEnd="@(new Icons.Regular.Size16.Delete().WithColor(Color.Error))" OnClick="async () => { await OnDeleteAsync(context.Id); }"/>
            
        </TemplateColumn>
    </FluentDataGrid>
</FluentCard>

@  Code {
public List<CompanyDto>? _selectedItems { get; set; }
public IReadOnlyList<CompanyDto>? _companies { get; set; }

[Inject] private ICompanyService _companyService { get; set; }
protected override async Task OnInitializedAsync()
{
    var result = await _companyService.GetAllAsync(CancellationToken.None);
    if (result.IsSuccess)
    {
        _companies = result.Data!;
        await InvokeAsync(StateHasChanged);
    }
    await base.OnInitializedAsync();
}

private async Task OnDeleteAsync(Guid id)
{
    //var res = await _companyService.DeleteAsync(id, CancellationToken.None);
}
}

```

## 🤔 Expected Behavior

The direction of mouse movement and the direction of changing the size of the columns should be in the same direction

## 😯 Current Behavior

Currently, they are not in the same direction and in the opposite direction

## 🔦 Context

Get Data From Database And display With Data Grid in RTL Direction

## 🌍 Your Environment

 FluentUi :   4.10.2
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 DotNet       8.0.10 X64
 Browser :    Chrome Version 130.0.6723.59 (Official Build) (64-bit)
 Editor :     Visual Studio 2022 v17.10.5 X64

**Comment by NabaviFard-Mahdi** [comment]
hi , thanks for new Release.
i checked and This bug has not been fixed yet and it exists in version 4.10.3

**Comment by vnbaaij** [comment]
You are probably walking int a script being cached too aggressively. Try forcing a hard refresh.

This is what I am seeing on the live demo site:
![Image](https://github.com/user-attachments/assets/56a80aab-8be2-447c-8507-3c8f6af203ac)

**Comment by NabaviFard-Mahdi** [comment]
yes demo site script being cached too aggressively. i refreshed With Ctrl+F5
but in my project it not fix. i think package Microsoft.FluentUI.AspNetCore.Components.Icons depeendecies on v4.10.2 and when installing [Microsoft.FluentUI.AspNetCore.Components v4.10.3]  and then installing [Microsoft.FluentUI.AspNetCore.Components.Icons v4.10.3] it downgrade package Microsoft.FluentUI.AspNetCore.Components to v4.10.2 

![Image](https://github.com/user-attachments/assets/f22bc855-2e69-407c-a3dd-1b68e12c68e4)

**Comment by vnbaaij** [comment]
But you can update to core package 4.10.3 again after that, right?

**Comment by NabaviFard-Mahdi** [comment]
I first install Microsoft.FluentUI.AspNetCore.Components v4.10.3
Then install Microsoft.FluentUI.AspNetCore.Components.Icons v4.10.3,  but Microsoft.FluentUI.AspNetCore.Components.Icons 4.10.3 need Microsoft.FluentUI.AspNetCore.Components v4.10.2.


Microsoft.FluentUI.AspNetCore.Components.Icons depend on 
Microsoft.FluentUI.AspNetCore.Components v4.10.2 not v4.10.3

**Comment by vnbaaij** [comment]
It is definitely not relevant to this issue.

In the Icons package I see:
![Image](https://github.com/user-attachments/assets/090ef20e-d3b2-4040-8e48-25387ca4a93a)

So 4.10.2 or later. No idea why it should downgrade the core page

**Comment by NabaviFard-Mahdi** [comment]
I checked again and this time I first installed the Icons package version 4.10.3 and then the Core package version 4.10.3.
Again, there was the problem of changing the size of the columns
Steps:
1) Clear Obj Folder
2) Clear Bin Folder
3) Install Core Package v4.10.3
4) Install Icons Package v4.10.3
5) Check Version Of Packages Core And Icons (Both 4.10.3 )
6) Rebuild Solution
7) Run
8) Check Js Scripts Of (FluentDivider.razor.js , FluentDataGrid.razor.js )

![Image](https://github.com/user-attachments/assets/efaf56b8-ee20-4b78-bef1-ed35af687a57)
![Image](https://github.com/user-attachments/assets/023423c0-69df-4195-a9d0-245ef95aed2b)

Test Video : [https://files.fm/u/rzarkf3jxj](https://files.fm/u/rzarkf3jxj)

**Comment by vnbaaij** [comment]
> I checked again and this time I first installed the Icons package version 4.10.3 and then the Core package version 4.10.3.

Again, this has nothing to do with the issue. Please don't mix issues 

> Again, there was the problem of changing the size of the columns
> Steps:
> 1) Clear Obj Folder
> 2) Clear Bin Folder
> 3) Install Core Package v4.10.3
> 4) Install Icons Package v4.10.3
> 5) Check Version Of Packages Core And Icons (Both 4.10.3 )
> 6) Rebuild Solution
> 7) Run
> 8) Check Js Scripts Of (FluentDivider.razor.js , FluentDataGrid.razor.js )

A local script file being cached has nothing to do with obj/bin folder. You can referee to the demo site to see that it is working as it should. If you are seeing different result, check your code please.
