### ISSUE TITLE
fix: Show Resizing Menu When ResizableColumns = false in FluentDataGrid

### ISSUE THREAD

**Issue by NabaviFard-Mahdi** [microsoft/fluentui-blazor#2837]
# 🐛 Bug Report

In fluentDataGrid When ResizableColumns = true and ResizeType="DataGridResizeType.Discrete" or ResizeType="DataGridResizeType.Exact" the resize is enable and resizing tool show in column header
but when **ResizableColumns = false** and ResizeType="DataGridResizeType.Discrete" or ResizeType="DataGridResizeType.Exact" resize is enable and again resizing tool show in column header but resize not working

## 🤔 Expected Behavior

when ResizableColumns = false or not set , resizing tool should not show

## 😯 Current Behavior

when ResizableColumns = false or not set and ResizeType="DataGridResizeType.Discrete" or ResizeType="DataGridResizeType.Exact" , resizing tool is showing

## 🌍 Your Environment

 FluentUi :   4.10.2
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 DotNet       8.0.10 X64
 Browser :    Chrome Version 130.0.6723.59 (Official Build) (64-bit)
 Editor :     Visual Studio 2022 v17.10.5 X64

**Comment by vnbaaij** [comment]
Not really a bug. It could/should be handled better but think it should be obvious to the **developer** must not set a `ResizeType` if `ResizableColumns` is set to false. This is not something that affects the end user.

I'll add a check for the parameters being set.
