### ISSUE TITLE
fix: [Not showing data and messing up the style when click on column header] in [FluentDataGrid]

### ISSUE THREAD

**Issue by NabaviFard-Mahdi** [microsoft/fluentui-blazor#2838]
# 🐛 Bug Report

when virtualize and autofit and sortable column is true and then click on each column the data is gone and messing up the style .
Both RTL and LTR directions

## 💻 Repro or Code Sample
`
<FluentDataGrid TGridItem="CompanyDto" 
                **AutoFit="true"**
                ItemKey="dto => { return dto.Id; }"
                ShowHover="true"
                Loading="@(_numResults == null)"
                **Virtualize="true"**
                GenerateHeader="GenerateHeaderOption.Sticky"
                ItemsProvider="CompanyGridItemProvider"
                HeaderCellAsButtonWithMenu="true"
                ItemSize="46"
                Style="Height: 95%; overflow:auto;">
`

## 🤔 Expected Behavior

Do nothing or default behavior

## 😯 Current Behavior

Not showing data and messing up the style

## 💁 Possible Solution

Remove or set false Autofit Or Virtualize

## 🔦 Context

Working With FluentDataGrid in Virtualize With Many Data And Autofit and Sortable is True

## 🌍 Your Environment

FluentUi : 4.10.2
OS Name: Windows
OS Version: 10.0.19045
OS Platform: Windows
RID: win-x64
DotNet 8.0.10 X64
Browser : Chrome Version 130.0.6723.59 (Official Build) (64-bit)
Editor : Visual Studio 2022 v17.10.5 X64

**Comment by vnbaaij** [comment]
There is **NO** ready-to-run reproduction code provided. We do not have time nor resources to go on a scavenging hunt to try to reproduce this. A small blurb of your custom code is not of any use to us. 

**Please help us to help you on your next issue report.** 

However, I would say to not use Virtualize and AutoFit together. Reason is that AutoFit scans through all the rows (that can be rendered) and misses information on the virtualize (not rendered) row. It will throw the resizing algorithm off. We ill work on giving a warning/error on the developer side when using this combination.

**Comment by NabaviFard-Mahdi** [comment]
Thanks for the advice.
I created a sample code for you to check further
[File](https://www.mediafire.com/file/cnuqco83ogvnsu3/BlazorApp91.rar/file)
