### ISSUE TITLE
fix: [what is the issue?] in [where is the issue?]

### ISSUE THREAD

**Issue by gsnyder87** [microsoft/fluentui-blazor#2846]
# 🐛 Bug Report

The fluentNumberField immediate delay does not work when using the up and down arrows. 

## 💻 Repro or Code Sample

<FluentNumberField MaxLength=25  Immediate=true ImmediateDelay=1000 TValue=decimal?  ValueChanged=@OnValueChanged />

## 🤔 Expected Behavior

the up and  down arrows should work the same was an inputting text into the field does. 

## 😯 Current Behavior

when using the up and down arrows, the OnValueChanged method is hit immediately.

## 💁 Possible Solution

I have a page level workaround, but it would be nice if this was within the component itself. 

@page "/counter"

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<FluentNumberField MaxLength=25  Immediate=true ImmediateDelay=1000 TValue=decimal?  ValueChanged=@OnValueChanged />

@code {
    private System.Timers.Timer _timer;
    private decimal? _latestValue;

    public Counter()
    {
        _timer = new System.Timers.Timer(1000); // 1 second delay
        _timer.Elapsed += OnTimerElapsed;
        _timer.AutoReset = false;
    }

    private void OnValueChanged(decimal? value)
    {
        _latestValue = value;
        _timer.Stop();
        _timer.Start();
    }

    private void OnTimerElapsed(object sender, System.Timers.ElapsedEventArgs e)
    {
        InvokeAsync(() => OnValueChanedAction(_latestValue));
    }

    private void OnValueChanedAction(decimal? value)
    {
        Console.WriteLine(value);
    }
}

## 🔦 Context

when users hit the arrows too fast, it triggers the ValueChanged resulting in changes too fast to the page which gets us into a code loop. 

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
The 'code loop' has been addressed in #2807. We have no further plans to add the `IntemediateDelay` to the component
