### ISSUE TITLE
feat: add FluentTextField Show Content Or Model DisplayName Atttribute

### ISSUE THREAD

**Issue by NabaviFard-Mahdi** [microsoft/fluentui-blazor#2847]
# 🙋 Feature Request

Add a feature to be able to get the label value of the field from Attribute Display (Name="name")
This can be added inside a Label or a separate Attribute

## 🤔 Expected Behavior

Get FluentTextField Label From Attribute Display(Name="name") in Model Property

## 😯 Current Behavior

No such method or behavior exists.

## 💁 Possible Solution
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

public static class ModelExtensions
{
    // Generic method to get display name based on the model and its property
    public static string GetDisplayName<TModel, TProperty>(this TModel model, Expression<Func<TModel, TProperty>> expression)
    {
        // Get the property info from the lambda expression
        var member = expression.Body as MemberExpression;

        if (member == null)
        {
            // Handle cases where the member expression may be nested in a Convert expression (e.g., boxing)
            var unary = expression.Body as UnaryExpression;
            member = unary?.Operand as MemberExpression;
        }

        if (member == null)
            throw new ArgumentException("Expression is not a valid member expression", nameof(expression));

        // Get the property information for the specified property
        var property = member.Member as PropertyInfo;

        if (property == null) return member.Member.Name; // If property is not found, return the name

        // Get the DisplayAttribute from the property, if available
        var displayAttribute = property.GetCustomAttributes(typeof(DisplayAttribute), true)
                                       .FirstOrDefault() as DisplayAttribute;

        // Return the display name if found, otherwise return the property name
        return displayAttribute?.Name ?? property.Name;
    }
}

## 💻 Examples
Create FluentEditForm -> <FluentTextField>

    < FluentEditForm @ref="@_form" EditContext="@_editContext" Enhance="true" FormName="CreateCompany">
        < FluentValidationValidator @ref="_fluentValidationValidator" />
        < FluentValidationSummary Model="@context"/>
        < ValidationSummary Model="@context"/>
        < DataAnnotationsValidator/>
        < FluentTextField @bind-Value="@Content.Name" 
                         DisplayName="@Content.Name"
                         Label="@Content.GetDisplayName(d=>d.Name)"
                         Maxlength="100" 
                         Required="true" 
                         Autofocus="true" 
                         AutoComplete="true" 
                         Immediate="true" 
                         ImmediateDelay="100" 
                         InputMode="InputMode.Text"
                         TextFieldType="TextFieldType.Text"/>

    < /FluentEditForm >
< /FluentDialogBody>

**Comment by vnbaaij** [comment]
I don't think we want to have such capability built in. We leave that to the developer to tweak and tune it like they want. Doing it with an extension, like in your example, is a perfect example of that
