### ISSUE TITLE
fix: Allow forcing dark or light mode on all users regardless of system theme

### ISSUE THREAD

**Issue by HunterAhlquist** [microsoft/fluentui-blazor#2850]
# 🙋 Feature Request

If `Mode` on `FluentDesignTheme` is explicitly set to a value, force that value regardless of user system theme.

## 🤔 Expected Behavior

When `<FluentDesignTheme StorageName="theme" Mode="DesignThemeModes.Dark" />` is added to `App.cs` the theme selected by FluentUI will always be dark regardless of what the user's system UI theme is.

## 😯 Current Behavior

Explicit setting of `Mode` on `FluentDesignTheme` will be ignored and use the user's system theme.

## 💁 Possible Solution

Do what is stated in expected behavior assuming this is a bug and not intended.

## 🔦 Context

I have a website that is stylistically intended to work only in dark mode, when the user uses a light UI theme, it just defaults to the system theme regardless of my explicit set in `FluentDesignTheme`. 
I've tried clearing cache, cookies, and the `obj` + `bin` folders in my local environment.
This appears to be a bug.
Some info about my environment:
I tested on iOS and MacOS in Safari, extensions disabled, and the project uses the WASM stand-alone app variant of the FluentUI-Blazor template.

## 💻 Examples
Repro project:
https://github.com/HunterAhlquist/ForceThemeModeBug

Code from my own project:
My `App.cs` where `FluentDesignTheme` is added:
```razor
<FluentDesignTheme CustomColor="#ffff00" StorageName="theme" Mode="DesignThemeModes.Dark" />
<Router AppAssembly="@typeof(App).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)"/>
        <FocusOnNavigate RouteData="@routeData" Selector="h1"/>
    </Found>
    <NotFound>
        <PageTitle>Not found</PageTitle>
        <LayoutView Layout="@typeof(MainLayout)">
            <p role="alert">Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
```
My `index.html`:
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AI.Website</title>
    <base href="/" />
    <link href="_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css" rel="stylesheet" />
    <link rel="stylesheet" href="css/app.css" />
    <link href="AI.Website.styles.css" rel="stylesheet" />
</head>

<body>
    <div id="app">
        <svg class="loading-progress">
            <circle r="40%" cx="50%" cy="50%" />
            <circle r="40%" cx="50%" cy="50%" />
        </svg>
    </div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js" type="module" async></script>
    <!-- Set the default theme -->
    <script src="_content/Microsoft.FluentUI.AspNetCore.Components/js/loading-theme.js" type="text/javascript"></script>
    <loading-theme storage-name="theme"></loading-theme>
</body>
</html>

```
`Mode="DesignThemeModes.Dark"` gets ignored by FluentUI and just uses the user's system theme.

**Comment by HunterAhlquist** [comment]
Sorry it appears I used the wrong issue template, this is a bug report.

**Comment by vnbaaij** [comment]
Hi,

We will take a look at that. In the meantime, do not put the below line in your `index.html` the library will automatically load it for you and i have observed some weird things happen when it is loaded twice
```
<script src="_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js" type="module" async></script>
```
in

**Comment by HunterAhlquist** [comment]
> Hi,
> 
> We will take a look at that. In the meantime, do not put the below line in your `index.html` the library will automatically load it for you and i have observed some weird things happen when it is loaded twice
> 
> ```
> <script src="_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js" type="module" async></script>
> ```
> 
> in

Thanks for the tip and prompt response, it didn't solve the problem here, but did fix some other quirks I was experiencing. Hopefully the fix will be easy.

**Comment by HunterAhlquist** [comment]
Here's a code project to show the issue, changing system theme changes the site theme when it should stay in dark mode due to the explicit setting of `Mode` on `FluentDesignTheme` in `App.cs`

Some info about my environment:
I tested on iOS and MacOS, extensions disabled, and the project uses the WASM stand-alone app variant of the FluentUI-Blazor template.

https://github.com/HunterAhlquist/ForceThemeModeBug

**Comment by vnbaaij** [comment]
Hi,

I can't reproduce your issue. Using you reproduction code (which does not contain any code wrt FluentDesignTheme) and adding the line
```
<FluentDesignTheme CustomColor="#ffff00" StorageName="theme" Mode="DesignThemeModes.Dark" />
``` 
to `App.razor` just works. First time I see a script error because the local storage does not exist yet but the site shows with dark theme nevertheless

**Comment by HunterAhlquist** [comment]
> Hi,
> 
> I can't reproduce your issue. Using you reproduction code (which does not contain any code wrt FluentDesignTheme) and adding the line
> 
> ```
> <FluentDesignTheme CustomColor="#ffff00" StorageName="theme" Mode="DesignThemeModes.Dark" />
> ```
> 
> to `App.razor` just works. First time I see a script error because the local storage does not exist yet but the site shows with dark theme nevertheless

Could it be specific to Safari on MacOS, or did you only try on windows/Chrome?

**Comment by vnbaaij** [comment]
I only have a Windows machine

**Comment by HunterAhlquist** [comment]
> I only have a Windows machine

I mean can we really call this closed then? Safari is the second most [popular browser today](https://gs.statcounter.com/browser-market-share). Perhaps someone else can use my test project on their mac.

**Comment by vnbaaij** [comment]
I'm pretty sure we would have received more reports if this was not working on Safari.

Your test project does not contain any theme specific code. Please make sure it is a an actual reproduction of the issue.
