### ISSUE TITLE
fix: Element reference properties are null in FluentDatePicker

### ISSUE THREAD

**Issue by markoweb2** [microsoft/fluentui-blazor#2861]
# 🐛 Bug Report

`Element` reference properties are null.

## 💻 Repro or Code Sample

Place a break point in the click handler and click on the button.

```
<PageTitle>Home</PageTitle>

<FluentDatePicker @ref="this.datePicker" Label="DP" Name="dp" />

<FluentButton OnClick="this.OnClick">Test</FluentButton>

@code
{
    private FluentDatePicker? datePicker;

    private void OnClick(MouseEventArgs args)
    {
        System.Diagnostics.Trace.WriteLine(this.datePicker?.Element.Id.ToString());
    }
}
```

## 🤔 Expected Behavior

`Element` reference properties should not be null, they should contain valid Id and Context. Just like `FluentTextField` does for example.

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/d54d7e22-1e66-4b6f-95a5-03f60d8a6511)

## 🔦 Context

I need the Element reference properties to be correct, inorder to pass it to a JavaScript function, which could then scroll the element into view.
At the moment I get a JavaScript exception.

## 🌍 Your Environment

* OS = Windows
* Browser = Google Chrome
* .NET and Fluent UI Blazor library Version = 8.0.10 and 4.10.2
* Visual Studio 2022 (17.11.5)

**Comment by dvoituron** [comment]
We can upate this property in the release, but you have access to all `FluentTextField `properties from your `this.datePicker` object.
Example:
```csharp
var id = this.datePicker?.Id;
```

**Comment by markoweb2** [comment]
Even if do add the `Id` manually to all `FluentDatePicker`-s, it still doesn't work.

My JavaScript function is:

```
    function ScrollIntoView(element) {
        if (!element) return;
        else element.scrollIntoView({ behavior: "smooth", block: "center", inline: "center" });
    }
```

Adding to my original example code:

```
@inject IJSRuntime js

    private async Task OnClick(MouseEventArgs args)
    {
        await js.InvokeVoidAsync("ScrollIntoView", this.datePicker.Id);
        await js.InvokeVoidAsync("ScrollIntoView", new ElementReference(this.datePicker.Id));
    }
```

I can understand the first call not working, `Id` is just a string, that is not an element in the html tree.
But the second call does nothing also, perhaps it requires the `Context` property to be set as well. But I haven't digged around yet, from where I could get that.

Were I to add say a `FluentTextField` to the page, then this call would scroll:
`await js.InvokeVoidAsync("ScrollIntoView", this.someTextField.Element);`

**Comment by dvoituron** [comment]
If you call your JavaScript using `await js.InvokeVoidAsync("ScrollIntoView", this.datePicker.Id);` 
then the JS function must manager this ID (string) with a function like...

```js
function ScrollIntoView(id) {
    const element = document.getElementById(id);
    element.scrollIntoView({ behavior: "smooth", block: "center", inline: "center" });
    }
```

**Comment by markoweb2** [comment]
Thanks, that works :)

**Comment by vnbaaij** [comment]
Closing this as there is a solution.

**Comment by markoweb2** [comment]
Closing is otherwise fine, but please still fix the original issue, as stated: 

> We can upate this property in the next release

Because someone else might still have a need for the `Element` property to be valid.
The _solution_ provided is only a workaround.
