### ISSUE TITLE
fix: cannot resize columns in FluentDataGrid if it's nested inside AuthorizeView

### ISSUE THREAD

**Issue by markoweb2** [microsoft/fluentui-blazor#2868]
# 🐛 Bug Report

A very peculiar bug, that only manifests if certain conditions are met:
1) `FluentDataGrid` must be nested inside `<AuthorizeView> `
2) DataGrid must not show any items at first render (you can still resize columns at this point)
3) Click a button to show items, refresh the DataGrid, now you can no longer resize columns

## 💻 Repro or Code Sample

New Visual Studio Blazor Web App project. 
Add this code to the home page:
```
<PageTitle>Home</PageTitle>

<AuthorizeView>
    <NotAuthorized>
        <FluentDataGrid @ref="this.dataGrid" ResizableColumns="true" Items="this.GridSource">
            <ChildContent>
                <PropertyColumn Title="Id" Property="@(prop => prop.Id)" Width="6rem" />
                <PropertyColumn Title="Name" Property="@(prop => prop.Name)" Width="6rem" />
            </ChildContent>
        </FluentDataGrid>

        <FluentButton OnClick="this.OnClick">Show</FluentButton>
    </NotAuthorized>
</AuthorizeView>

@code
{
    private static bool showHiddenItems = false;
    static List<Test> source = new List<Test>() { new Test() { Id = 1, Name = "aa", Hidden = true }, new Test() { Id = 2, Name = "bb", Hidden = true } };

    private FluentDataGrid<Test>? dataGrid;

    public IQueryable<Test> GridSource { get; set; } = source.AsQueryable().Where(src => showHiddenItems ? true : src.Hidden == false);

    private async Task OnClick(MouseEventArgs args)
    {
        showHiddenItems = true;
        await this.dataGrid!.RefreshDataAsync();
    }

    public class Test
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public bool Hidden { get; set; }
    }
}
```

Add this inside Program.cs
`builder.Services.AddCascadingAuthenticationState();`

## 🤔 Expected Behavior

Columns should always be resizable.

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/3d212633-c80c-47af-b142-b73e44c85168)

## 🔦 Context

On initial load, a DataGrid might have all it's items hidden.
If you click a button to show all hidden items, then after that, columns are no longer resizable.
This bug only happens if `FluentDataGrid` is inside an `<AuthorizeView>` component.

Actually, did some more testing, and it seems you can comment out `showHiddenItems = true;` from the click method. Just a call to `RefreshDataAsync()` will make the columns not resizable. Doesn't matter if the items are initially shown or not.

In my own code base, if the DataGrid has at least one item initially visible, and you then click on the show all items button, then you can resize columns afterwards. But perhaps this is because in my code base, the `FluentDataGrid` is inside the `<Authorized>` section. (difficult to provide a quick repo code sample for that scenario)

Based on this, I can conclude that the bug lies within `RefreshDataAsync()`. I guess it tries to apply some logic, eg if you are not authorized then you can't touch the DataGrid, but it fails to do so correctly.

## 🌍 Your Environment

* OS = Windows
* Browser = Google Chrome
* .NET and Fluent UI Blazor library Version = 8.0.10 and 4.10.2
* Visual Studio 2022 (17.11.5)

**Comment by NabaviFard-Mahdi** [comment]
I'm testing your code and in own side I don't see any problem with resizing the column before and after clicking the button and refreshing the data.

**Comment by markoweb2** [comment]
Well it's definently happening on my end.
Here is the mini code sample repo project.
[BlazorApp1.zip](https://github.com/user-attachments/files/17547954/BlazorApp1.zip)

You are using FluentDataGrid inside the AuthorizeView component?
Because if I take the grid out if it, then it also works for me.

Only other thing I could think of, are you running .net 9 preview? (I am running .NET 8)
