### ISSUE TITLE
feat: add custom translation for Search/Clear icons to/in FluentAutocomplete

### ISSUE THREAD

**Issue by lasbrojen** [microsoft/fluentui-blazor#2873]
Hi and thank you for this nugget!

 # 🙋 Feature Request

Add custom translation for Search/Clear icons to/in FluentAutocomplete:

![Image](https://github.com/user-attachments/assets/1d2932c6-1a4b-4d1b-95a1-2c05253d73e7)

## 🤔 Expected Behavior

Maybe expected behaviors would be setting culture or custom properties?

## 😯 Current Behavior

Is currently hardcoded

**Comment by dvoituron** [comment]
You are right. We will update this.

**Comment by dvoituron** [comment]
See #2891

**Comment by lasbrojen** [comment]
Hi @dvoituron 

Could you clarify how to use this 🫣?

I tried adding the following to `Program.cs`:
`FluentAutocomplete<SelectedIdCommandModel<DepartmentEntity>>.AccessibilityIconSearch = "Ryd alle";`

However, I also tried this approach, which, of course, doesn't work because the properties are static:
```
private FluentAutocomplete<SelectedIdCommandModel<TEntity>> _autoComplete;
protected override void OnInitialized()
{
    _autoComplete.AccessibilityIconSearch = "Ryd alle";
   ........
```

BR
Lasse

**Comment by dvoituron** [comment]
Did you try this?

```
FluentAutocomplete<SelectedIdCommandModel<TEntity>>. AccessibilityIconSearch = "Ryd alle"
```

**Comment by lasbrojen** [comment]
Yes, it works – and I used `AccessibilityIconSearch `but tested `AccessibilityIconDismiss`!

Apologies for wasting your time on this!

🫣
