### ISSUE TITLE
RFC: Add autofit all columns feature to DataGrid control

### ISSUE THREAD

**Issue by woaidianqian** [microsoft/fluentui-blazor#2876]
Request for DataGrid Auto-Fit Columns Functionality with Image Support

🔦 Context
I would like to know if the DataGrid control can achieve an autofit all columns feature to automatically resize columns to fit the content across all columns. The absence of this feature affects the display, making it necessary to manually resize each column to avoid clipping of text or images. Additionally, I plan to add image support to better illustrate this functionality and enhance the visual representation of data within the grid.

Alternatives Considered
I’ve reviewed alternatives such as manually adjusting column widths or setting a fixed width, but these options are not adaptive to content changes and reduce flexibility in the UI design.

💻 Examples
Below are examples of how the autofit all columns feature could function:

Text Auto-fit: Automatically adjust each column width based on text length, preventing text from clipping or being truncated.
Image Support: Include the ability to auto-fit columns to accommodate images, where the column width adjusts to fit the entire image.

I will provide screenshots or images showing the current behavior versus the expected behavior with autofit all columns enabled for reference.
![Image](https://github.com/user-attachments/assets/9aff1e15-3990-484d-879f-0b82f27bce0d)
![Image](https://github.com/user-attachments/assets/66d35d38-392e-43e4-98b8-d7e5639f0875)
https://demos.telerik.com/blazor-ui/grid/column-resizing

**Comment by vnbaaij** [comment]
We already support this for text columns: https://fluentui-blazor.net/DataGrid#autofit

We don't have plans to do this for columns containing images.

**Comment by woaidianqian** [comment]
"Apologies for not thoroughly checking the examples on the webpage earlier—I missed that text columns already support auto-fit. Thank you for the clarification!"

**Comment by woaidianqian** [comment]
> We already support this for text columns: https://fluentui-blazor.net/DataGrid#autofit
> 
> We don't have plans to do this for columns containing images.

"Apologies for not thoroughly checking the examples on the webpage earlier—I missed that text columns already support auto-fit. Thank you for the clarification!"
