### ISSUE TITLE
fix: Pre-selected values cannot be deleted from FluentAutocomplete

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2880]
# 🐛 Bug Report

When you have a predefined value assigned to a bound property of a `FluentAutocomplete` it cannot be deleted unless you have selected another value.

This used to work in 4.10.2 but it does not in 4.10.3

## 💻 Repro or Code Sample
I've created a small sample repository which can be found here:
https://github.com/MarvinKlein1508/FluentUI-Autocomplete-issue

## 🤔 Expected Behavior
You should be able to delete the predefined value, just like it in 4.10.2.

## 😯 Current Behavior
The value can only be deleted whenever you select another value first.

**Comment by MarvinKlein1508** [comment]
When I remove the added if block here everything works for me just like before.
https://github.com/microsoft/fluentui-blazor/blob/78ff71e3d8514c6a8b59be86db1da4b907b10b3c/src/Core/Components/List/ListComponentBase.razor.cs#L539

**Comment by MarvinKlein1508** [comment]
Or alternativly:
```cs
if (_selectedOptions.Count != 0 || SelectedOptions?.Any() == true)
```

**Comment by dvoituron** [comment]
See #2891
