### ISSUE TITLE
fix: [Local storage for theme not being set] in [FluentDesignTheme]

### ISSUE THREAD

**Issue by Nikkoro** [microsoft/fluentui-blazor#2885]
# 🐛 Bug Report

Theme is not saved in localstorage when using `StorageName`

## 💻 Repro or Code Sample

Add to App.razor or main layout:
`<FluentDesignTheme Mode="DesignThemeModes.Default" OfficeColor="OfficeColor.Teams" StorageName="theme" />`

## 🤔 Expected Behavior

Theme should be saved in localstorage without need to switch it manually for the first time

## 😯 Current Behavior

When you set a theme like this:
`<FluentDesignTheme Mode="DesignThemeModes.Default" OfficeColor="OfficeColor.Teams" StorageName="theme" />`
it's not being added to localstorage untill you switch the theme.

Right now, the only way to save the theme to localstorage is to bind values and switch the theme for example using some button, only then the theme is added to localstorage.

`<FluentDesignTheme @bind-Mode="@Mode" @bind-OfficeColor="@ThemeColor" StorageName="theme" `

https://github.com/user-attachments/assets/4de13519-002d-4109-a6a5-eba8bc2151e4

## 💁 Possible Solution

Not sure

## 🔦 Context

I want to save the theme in localstorage with values mode: null and primaryColor: Teams, so it will switch according to user settings. Right now sometimes the theme is being set wrong and having the values in localstorage could help.

## 🌍 Your Environment

Windows 11, Edge, FluentUI v4.10.3, .NET 8.0.4

**Comment by dvoituron** [comment]
This is how the component works: nothing is saved in the LocalStorage until it is needed and the default values are used.

We can't change this behaviour.

However, you can use the `OnLoaded` event to get the theme settings when your application starts.

**Comment by Nikkoro** [comment]
> This is how the component works: nothing is saved in the LocalStorage until it is needed and the default values are used.
> 
> We can't change this behaviour.
> 
> However, you can use the `OnLoaded` event to get the theme settings when your application starts.

Alright I understand. Thank you 😊
