### ISSUE TITLE
fix: Fluent Numeric TextFiled issue inside DialogBox

### ISSUE THREAD

**Issue by pradm777** [microsoft/fluentui-blazor#2886]
# 🐛 Bug Report

I have a FluentDataGrid that contains Add and Edit options. When a row is clicked, the Edit mode is triggered. Once a value is edited, the data is saved, but when I click on another row, the numeric TextField still shows the old value. This numeric field has a ValueChanged event, which is also firing.

Version 4.10.2 is working for me, but the latest version 4.10.3 has this issue.
## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by dvoituron** [comment]
Without a reproducible code example to detect the problem, we cannot help you. 

Looking at your description, I can't see which component of our library could be at fault.

**Comment by vnbaaij** [comment]
Supply reproduction code, please. If not, the offset will be closed after 3 days
