### ISSUE TITLE
fix: Right-To-Left in Listbox

### ISSUE THREAD

**Issue by aminmashayekhi** [microsoft/fluentui-blazor#2893]
Listbox items not shown correctly in Righ-To-Left direction:
(same as issue https://github.com/microsoft/fluentui-blazor/issues/2766)
![Image](https://github.com/user-attachments/assets/467f36f7-0d37-477c-86af-838159e807cc)

**Comment by NabaviFard-Mahdi** [comment]
this bug is also exists in Autocomplete ,Combobox ,Select ,Option and context menu

**Comment by dvoituron** [comment]
This problem is present in the `fluent-option` WebComponent we're using.
We can't solve it ourselves, but you can create an Issue in the repo https://github.com/microsoft/fluentui/

**Comment by NabaviFard-Mahdi** [comment]
create an Issue in the repo [ https://github.com/microsoft/fluentui/]( https://github.com/microsoft/fluentui/)
[https://github.com/microsoft/fluentui/issues/33210](https://github.com/microsoft/fluentui/issues/33210)

**Comment by vnbaaij** [comment]
Closing this here. If it gets fixed on the wc side, that will flow to us when we update to a new script version.
