### ISSUE TITLE
FluentTimePicker icon color not changing when in dark mode.

### ISSUE THREAD

**Issue by grantcolley** [microsoft/fluentui-blazor#2896]
# 🐛 Bug Report

**FluentTimePicker** icon color not changing when in dark mode.

## 💻 Repro or Code Sample

Here I have a **FluentDatePicker** and **FluentTimePicker** side by side.

```html
        <FluentLabel>To</FluentLabel>
        <div style=" display: flex; flex-direction:row;">
            <FluentDatePicker @bind-Value=@(_logArgs.To) Style="margin-right: 2px; width: 120px" />
            <FluentTimePicker @bind-Value=@(_logArgs.To) />
        </div>

```

## 🤔 Expected Behavior

When i switch to dark mode I expect the color of the **FluentTimePicker**'s icon to change in line with the other components.

## 😯 Current Behavior

When i switch to dark mode the color of the **FluentTimePicker**'s icon doesn't change in line with the other components.

![Image](https://github.com/user-attachments/assets/a7460f0d-fbbc-4095-8be4-622079df8ac0)

## 🌍 Your Environment

* Browsers : Microsoft Edge (latest), Google Chrome (latest)
* .NET 8.0
* Fluent UI Blazor library Version 4.10.2

**Comment by dvoituron** [comment]
We already explained that: #1258

You could find a "solution" here: https://github.com/microsoft/fluentui-blazor/discussions/1193#discussioncomment-7930415
