### ISSUE TITLE
fix: Horizontal Scroll In RTL mode

### ISSUE THREAD

**Issue by NabaviFard-Mahdi** [microsoft/fluentui-blazor#2899]
# 🐛 Bug Report

Horizontal scrolling in rtl mode doesn't show properly and doesn't work properly

## 💻 Repro or Code Sample

demo site : [https://www.fluentui-blazor.net/HorizontalScroll](https://www.fluentui-blazor.net/HorizontalScroll)

## 🤔 Expected Behavior

Correct display of slides (cards) (not fully displayed)
Correct function of show previous key (when I go to the last card and press the key to go back to the previous card, all cards go back to afab)
Hide the navigation keys at the end of each direction
Ability: By holding the left mouse click and moving the mouse left and right, move the cards forward and backward

## 🌍 Your Environment

* OS & Device: Windows, PC
* Browser Google Chrome Version 130.0.6723.92 (Official Build) (64-bit)
* .NET and Fluent UI Blazor library Version 8.0.4 and 4.10.3 ,4.11.0

**Comment by vnbaaij** [comment]
> Correct display of slides (cards) (not fully displayed)

That is by design

> Correct function of show previous key (when I go to the last card and press the key to go back to the previous card, all cards go back to afab)

Issue in the current web component code

> Hide the navigation keys at the end of each direction

Issue in the current web component code

> Ability: By holding the left mouse click and moving the mouse left and right, move the cards forward and backward

This is not a functionality that the component offers
