### ISSUE TITLE
Autocomplete Aria-Hidden and Focusable bug

### ISSUE THREAD

**Issue by jpiquot** [microsoft/fluentui-blazor#2901]
# 🐛 Bug Report

The issue originally reported in bug #2644 was resolved with the release of version 4.10.1 in pull request #2648. However, the bug has reappeared in version 4.10.3. When I roll back to version 4.10.1, everything functions correctly.

**Comment by dvoituron** [comment]
Will be fixed in the next Release

See #2903

**Comment by jpiquot** [comment]
Thanks for the fix.
