### ISSUE TITLE
fix: FluentTreeView selection bug #3

### ISSUE THREAD

**Issue by markoweb2** [microsoft/fluentui-blazor#2911]
# 🐛 Bug Report

Just tested the new 4.10.3 build, the supposed fixes for `FluentTreeView` have made it even worse than before :(

## 💻 Repro or Code Sample

```
<FluentTreeView Items="@list" @bind-SelectedItem="this.selectedItem">
    <ItemTemplate>
        @context.Text
    </ItemTemplate>
</FluentTreeView>

@code
{
    private ITreeViewItem? selectedItem;
    private List<TreeViewItem> list = new List<TreeViewItem>() { new TreeViewItem() { Expanded = true, Text = "test 1", Items = new List<TreeViewItem>() { new TreeViewItem() { Text = "sub test 2" } } }, 
        new TreeViewItem() { Text = "test 2" } };
}
```

## 🤔 Expected Behavior

The control should work and items should be selectable.

## 😯 Current Behavior

Nothing is selectable in the `FluentTreeView`:

![Image](https://github.com/user-attachments/assets/9346b403-7ac0-4826-ad2d-c4bb2b0ba923)

## 🔦 Context

This is a regression from 4.10.2, the above code at least worked and everything was selectable.

The original issues were #2797 and #2798 .
If you remove the `<ItemTemplate>`, then "test 2" and "sub test 2" become selectable, but not "test 1".

Also, if you just use minimalist code:
```
<FluentTreeView Items="@list"></FluentTreeView>

@code
{
    private List<TreeViewItem> list = new List<TreeViewItem>() { new TreeViewItem() { Text = "test 1" }, new TreeViewItem() { Text = "test 2" } };
}
```

Then you now end up with an endless flicker loop (also worse than before):
![Image](https://github.com/user-attachments/assets/94884cc4-5c06-4cad-86a6-2272d05cb987)

## 🌍 Your Environment

OS = Windows
Browser = Microsoft Edge, Google Chrome
.NET and Fluent UI Blazor library Version = 8.0.10 and 4.10.3
Visual Studio 2022 (17.11.5)

**Comment by vnbaaij** [comment]
Is this on Wasm or Server?

**Comment by markoweb2** [comment]
This is on server with `InteractiveServerRenderMode(false)`

Did a clean solution, rebuild solution, CTRL+F5 in browser, doesn't seem to be a cache issue.

**Comment by vnbaaij** [comment]
Ok, will try to take a look later today. Currently on airport wifi without PC.
