### ISSUE TITLE
Autocomplete - unable to clear items

### ISSUE THREAD

**Issue by Lindsay-Mathieson** [microsoft/fluentui-blazor#2914]
Unable to clear items once selected, reproducible both in my app and the demo. Rolling back to 4.10.2 fixes the issue for me.

https://www.fluentui-blazor.net/Autocomplete#default

Tested with Latest Windows 11  + Edge

https://github.com/user-attachments/assets/c85a8cca-01d8-4dbe-9cd8-d60e4fea5ba9

**Comment by vnbaaij** [comment]
Duplicate. See #2903

**Comment by Lindsay-Mathieson** [comment]
> Duplicate. See [#2903](https://github.com/microsoft/fluentui-blazor/issues/2903)

Thanks, sorry I did search for it, but not closed items.

**Comment by vnbaaij** [comment]
No worries!
