### ISSUE TITLE
In the dialog box, the required attribute for FluentTextField is not taking effect.

### ISSUE THREAD

**Issue by zuijiaoghb** [microsoft/fluentui-blazor#2918]
# 🐛 Bug Report

In the dialog box, the required attribute for FluentTextField is not taking effect.

## 💻 Repro or Code Sample
<FluentDialogBody>
    <p>当前票据的票据号: @Content.TicketNumber，子票据号:@Content.SubTicketNumber，承兑金额：@Content.AcceptAmount，余额：@Content.Balance。</p>
    <FluentTextField Name="newSubTicketNumber" @bind-Value="@newSubTicketNumber" Required="true">拆分子票号：</FluentTextField>
    <FluentTextField @bind-Value="@Endorser" Required="true">背书人：</FluentTextField>
    <FluentNumberField @bind-Value="@SplitAcceptAmount" Required="true">转出金额:</FluentNumberField>
</FluentDialogBody>

## 🤔 Expected Behavior
Page prompt required。

## 🌍 Your Environment
* OS & Device: Linux centos8  on  PC
* Browser Microsoft Edge
* .NET 8.0.301 and Fluent UI Blazor library Version 4.10.3

**Comment by zuijiaoghb** [comment]
![Image](https://github.com/user-attachments/assets/87c1c3ff-c241-4a38-ad30-5c3fe77edb3c)

**Comment by vnbaaij** [comment]
Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

Help us to help you. Thanks.
