### ISSUE TITLE
Template for .NET MAUI Blazor Hybrid and Web App in .NET 9

### ISSUE THREAD

**Issue by satyajit-behera** [microsoft/fluentui-blazor#2927]
Hi,

Any plans for creating a template for .NET MAUI Blazor Hybrid and Web App in .NET 9 including the fluent UI.
This would be very useful for new development.

Thanks

**Comment by vnbaaij** [comment]
Plans yes. Now we just need to find time...

**Comment by vnbaaij** [comment]
See #2960

**Comment by vnbaaij** [comment]
Closing this. Will be available with v4.11.0 release
