### ISSUE TITLE
FluentUI blazor web app,Content-Security-Policy problem

### ISSUE THREAD

**Issue by iftiharh** [microsoft/fluentui-blazor#2934]
There is a problem in FluentUI blazor web app. When I add Content-Security-Policy as in this link https://learn.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy?view=aspnetcore-8.0, all control views are broken.

I add the following lines to App.razor.
<meta http-equiv="Content-Security-Policy" content="base-uri 'self'; default-src 'self'; img-src data: https:; object-src 'none'; script-src 'self'; style-src 'self'; upgrade-insecure-requests;">

Thank you

**Comment by vnbaaij** [comment]
Duplicate. See #2783
