### ISSUE TITLE
FluentHorizontalScroll: Add AutoScroll, AutoWrap, and OnChange

### ISSUE THREAD

**Issue by marqdouj** [microsoft/fluentui-blazor#2942]
# 🙋 Feature Request

I would like to see the FluentHorizontalScroll to have three new features:

1. AutoScroll. Have the control automatically scroll the content at a specified interval, instead of having to manually click on the flipper buttons.
2. AutoWrap. Have the control automatically scroll back to the first content when reaching the last content.
3. OnChange: Have the control support an OnChange event (or maybe just data bind the current index to a variable) so I can track which content (index) is currently active; which would allow me to setup a kind of radio button display so that the user can click on a button and I can move specifically to that index. Perhaps this button display could be linked to the control kind of like how paginator does with the data grid.

## 😯 Current Behavior

I do not see any of these features currently supported.

**Comment by vnbaaij** [comment]
Hi, these features are not supported currently in the underlying web components. With the work we are doing on the next version of this library, we do not have capacity to work on extending this web component.
