### ISSUE TITLE
fix: FluentAutoComplete empty SelectedOptions param doesn't update selected options, breaks demo search

### ISSUE THREAD

**Issue by dmitrifaleev** [microsoft/fluentui-blazor#2943]
# 🐛 Bug Report

It looks like passing empty SelectedOptions to FluentAutoComplete doesn't update _selectedOptions in ListComponentBase.
MaximumSelectedOptions is bypassed.

## 💻 Repro or Code Sample

Demo site
 - Search for a page and navigate to it.
 - Search for another page and navigate to it

Relevant code https://github.com/microsoft/fluentui-blazor/blob/84170b547a775c102cd838bca333576b8982b8eb/src/Core/Components/List/ListComponentBase.razor.cs#L347

## 🤔 Expected Behavior

Second page opens

## 😯 Current Behavior

Uncaught exception
First and second page show as selected, 

## 💁 Possible Solution

Check for empty SelectedOptions and non-empty _selectedOptions in OnParametersSet of ListComponentBase.

```
if (Multiple)
{
    if (SelectedOptions?.Any() == false && _selectedOptions.Count > 0)
    {
        _selectedOptions = [];
    }
...
```

## 🔦 Context

Demo site search is not working
It looks like passing empty SelectedOptions to FluentAutoComplete does not update ListComponentBase _selectedOptions.

## 🌍 Your Environment

Reproducible in Demo site Version: 4.10.4+a5eaca4e

**Comment by dvoituron** [comment]
Will be fixed in the next Release: #2945
