### ISSUE TITLE
fix:Autcomplete

### ISSUE THREAD

**Issue by pradm777** [microsoft/fluentui-blazor#2949]
# 🐛 Bug Report

## 💻 Repro or Code Sample

Autocomplete search is not working like Google search autocomplete. I am unable to use the keydown and keyup functionality, and pressing the Enter button does not select an item

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by dvoituron** [comment]
Without code to reproduce your problem, we cannot discuss it with you or find a solution.
The FluentAutocomplete works as expected. You can try it out on the demo site: https://www.fluentui-blazor.net/Autocomplete

**Comment by vnbaaij** [comment]
Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

Help us to help you. Thanks.

**Comment by vnbaaij** [comment]
Actually, I'm just going to close this as the issue template was not used either. Please try again if you are ready and willing to play by the rules.
