### ISSUE TITLE
fix: Console Errors for not set FluentDesignTheme in local storage

### ISSUE THREAD

**Issue by przsmolana** [microsoft/fluentui-blazor#2952]
# 🐛 Bug Report

After upgrading package from 4.10.1 version to 4.10.3 version, we started observing console errors. Please see the screenshot:
![Image](https://github.com/user-attachments/assets/a9bb4ddd-fbaf-4b86-b66d-7e6609dca08c)

## 💻 Repro or Code Sample

That is the only usage in our app at the moment:
`<FluentDesignTheme StorageName="fluent-theme" CustomColor="@_theme.Surface.Background.Accent" Mode="DesignThemeModes.Light" />`

## 🔦 Context

In general, it doesn't affect how the application works. Nevertheless console errors are annoying.
Found this issue: https://github.com/microsoft/fluentui-blazor/issues/2885 that as I understand says theme is not set in local storage. Question is if we should see errors?
Please, let us know if there is something we should do on our side to not see this console error

## 🌍 Your Environment
We have observed in MacOS and Windows devices and browser wise the same situation, the same happening on Safari or Chrome.

**Comment by coderdnewbie** [comment]
If you go to 

https://github.com/coderdnewbie/DemoFluentUI

I have put in fixes to get rid of this issue, as well as update the Dotnet Conf 2024 demo to dotnet 9.0.

Hope this helps you.

**Comment by dvoituron** [comment]
Thanks @coderdnewbie and @przsmolana for your feedback.

In fact, in certain ‘simple’ circumstances, this error can occur.
It's a non-blocking error, but it's annoying for the console logs.

I've fixed this for the next Release, by adding a simple test in the JS code :-)

See #2956

**Comment by przsmolana** [comment]
@dvoituron many thanks :)
