### ISSUE TITLE
feat: add [rich text editor] to/in [form inputs]

### ISSUE THREAD

**Issue by saeednoruzi** [microsoft/fluentui-blazor#2962]
# 🙋 Feature Request

it can be use for  reciving  advanced  scenario such cod for  fifrent language  ading  external url and embeding  pictures and formating text for blogs and son

## 🤔 Expected Behavior

somthing like CKEditor

**Comment by vnbaaij** [comment]
Hi,

This has been discussed before. We will not be adding such a component to the library anytime soon.
