### ISSUE TITLE
fix: Unhandled error after new MAUI Hybrid Blazor App Solution created and Manual install of Fluent

### ISSUE THREAD

**Issue by B-Cantu** [microsoft/fluentui-blazor#2969]
# 🐛 Bug Report

I created a new MAUI Hybrid Application solution using Visual Studio and DotNet 9 

- FluentUI was installed using: 
```  
dotnet add package Microsoft.FluentUI.AspNetCore.Components 
``` 

and the Icons and emoji's using

```
 dotnet add package Microsoft.FluentUI.AspNetCore.Components.Icons
 dotnet add package Microsoft.FluentUI.AspNetCore.Components.Emoji
``` 

 
- Built and ran sample application was this worked fine and the Home.razor page was displayed

- The setup document was read, "Blazor Hybrid" and I saw the note: 

Note: The workaround below only applies to .NET 8 (and below). As of .NET 9 this workaround is no longer needed. If you have this workaround in place for .NET 9 your Blazor Hybrid project will not load.

- added to the _Imports.razor file @using Microsoft.FluentUI.AspNetCore.Components
- added to Home.Razor file the following:

```html
<FluentCard>
    <h2>Hello World!</h2>
    <FluentButton Appearance="@Appearance.Accent">Click Me</FluentButton>
</FluentCard>
``` 

- Built successfully, No errors 
- Application displayed as follows:

![Image](https://github.com/user-attachments/assets/ad9995b6-90cd-4afc-852e-fae3d2aaa17f)

Attached is the Visual Studio solution that is the new MAUI blazor hybrid project with the maually added FluentUI nuget packages minus the bin and obj folders so I could attach here...

 [DevOpsCloud.zip](https://github.com/user-attachments/files/17891501/DevOpsCloud.zip)

**Comment by vnbaaij** [comment]
We can't assess the issue without any source code. Please add a zip or link to a repo.

**Comment by B-Cantu** [comment]
Sorry I should have attached. The zip is here of the Visual Studio solutions minus the bin and obj folders

[DevOpsCloud.zip](https://github.com/user-attachments/files/17891400/DevOpsCloud.zip)
