### ISSUE TITLE
fix: MenuIndex error in FluentMenu

### ISSUE THREAD

**Issue by wisamidris77** [microsoft/fluentui-blazor#2974]
![Image](https://github.com/user-attachments/assets/944472d7-d6be-458c-9cd9-3d22fa4453b9)

This excpetion is begin to be thrown when i upgraded net9.0 and latest fluent
Also other excpetions caught in my js and I fixed them with if statements to pervent the exception
But here this exception always get thrown in every place I use FluentMenu

**Comment by vnbaaij** [comment]
You have no provided reproduction code. You have not followed the issue template. You can see in the demo site that the errors are not happening there. 

Why do you expect us to help you if you do not want to help us?

Have you added a `FluentMenuProvider`? See https://www.fluentui-blazor.net/Menu

I'm closing this one. Feel free to open a new issues if you are willing to play by the rules.

**Comment by wisamidris77** [comment]
I mean this issue only appeared in net9.0 the latest fluent and blazor version

**Comment by wisamidris77** [comment]
I mean in release it would work but the problem is in debugging it's just annoying when it always throws there every time I click in text field inside the FluentMenu

It still a bug but does not affect anything a Error/Exception does not affect anything
