### ISSUE TITLE
FluentDialog with EditForm / EditContext reverts to original dialog data when clicking outside of dialog component

### ISSUE THREAD

**Issue by gkenaston** [microsoft/fluentui-blazor#2975]
## 💻 Repro or Code Sample

https://github.com/gkenaston/FluentUI-Dialog

1. Open the Dialog and wait 3 secs (Name field will update)
2. Click outside of the Dialog and observe the Name field change

**Comment by vnbaaij** [comment]
You will need to get the `Data` from the `Result`. See https://www.fluentui-blazor.net/Dialog#editabledialog for an example

**Comment by gkenaston** [comment]
I had a feeling I might be using the component outside of its intended design. Thank you for taking the time to review the issue.
