### ISSUE TITLE
NET 9: Visual Studio Hybrid Blazor Projekt Problem mit {PROJECT_NAME}.styles.css.

### ISSUE THREAD

**Issue by true-perfect-code** [microsoft/fluentui-blazor#2977]
# 🐛 Bug Report

When I create a hybrid blazor project via Visual Studio Template in NET 9 (MAUI Blazor + RCL + Blazor Web) and then install FluentUI Blazor in RCL, CSS is loaded. For example, when I go to {PROJECT_NAME}.styles.css on the client via inspection, I see the following:

```
@import '_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.dwk6czdzfo.bundle.scp.css';
@import '_content/pTodo.Shared/TestApp.Shared.c4ofc0y3p7.bundle.scp.css';
```

After a few days I suddenly lose the FluentUI Blazor CSS and components are displayed without FluentUI CSS (which looks terrible). If I switch to MAUI Blazor, I don't have the problem there. I also see there (MAUI Blazor) in inspection window (F12) the imports:

```
@import '_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.dwk6czdzfo.bundle.scp.css';
@import '_content/pTodo.Shared/TestApp.Shared.c4ofc0y3p7.bundle.scp.css';
```

But when I look at the {PROJECT_NAME}.styles.css in Blazor Web on the client again, I see now the complete content of my App.razor!? The imports are not included there!

Does anyone know this problem and what can I do about it?

Thanks
pc

## 💻 Repro or Code Sample

No

## 🤔 Expected Behavior

Clarify the {PROJECT_NAME}.styles.css using in Hybrid Template

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/cc2bec58-60dc-43ad-81b7-e4841d835350)

## 💁 Possible Solution

No solution

## 🔦 Context

I have tried:
- clear cash in the browser
- Rebuild a project
- Bin and Obj deleted, project rebuild
- Add in RCL the "@import" to app.css

None of this has helped.

## 🌍 Your Environment

* Windows 11
* Google Chrome
* .NET 9 and Fluent UI Blazor library Version 4.10.4

**Comment by vnbaaij** [comment]
The {PROJECT_NAME} needs to be replaced with your actual project name...

If that is what you have done and you still have the issue, then we need reproduction code. Please reopen then and supply ready to run code or a repository we can use to analyse

**Comment by true-perfect-code** [comment]
Hi @vnbaaij 

I have created a GitHub project and added it to the post above.
So that should be clear at first look what is happening, I have added a picture from MAUI Blazor where the FluentUI Blazor CSS works and on the “old” picture you can see how in Blazor Web the FluentUI Blazor CSS no longer affects.

I have also added a GIF that shows how this will look in the GitHub project.

I hope this is enough to find the problem.

Thanks
pc

**Comment by vnbaaij** [comment]
I think the problem is that you still have the Bootstap CSS in your web application: 
https://github.com/true-perfect-code/FluentUIBlazor_in_Hybrid/blob/9d1c2c1b55ec4e25b40bac55cada942594b0dfae/pTodo.Web/Components/App.razor#L8

**Comment by true-perfect-code** [comment]
Hi @vnbaaij 

Unfortunately, it's not because of that (it would have been nice). In any case, it shouldn't work in MAUI Blazor either, because I also have Bootstrap in there.

- I have commented out the line in Blazor Web App.razor.
![Image](https://github.com/user-attachments/assets/fb378b37-0ee6-479a-a097-05a60467fc07)

- Solution cleaned up
- Solution recreated
- Browser cash deleted

Unfortunately, the problem persists.

Could it have something to do with CSS isolation?

pc

**Comment by vnbaaij** [comment]
Ok, I took a look in VS when running both projects (you can run them at the same time). The Bootstrap stuff might cause interference nevertheless, so I'd remove that anyway.

Issue(s) found:
- In .NET 9 use `app.MapStaticAssets{};` (instead of `app.UseStaticFiles`) in `Program.cs`
- In `App.razor` surround your style href's with `@Assets`:
```href="@Assets["_content/pTodo.Shared/app.css"]"```

Not strictly necessary but advised: 
- In `Shared\app.css` add to the top of the file:
`@import '/_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css';`
- Use a more Fluent based css instead of Bootstap standard:
```
body {
    --body-font: "Segoe UI Variable", "Segoe UI", sans-serif;
    font-family: var(--body-font);
    font-size: var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    margin: 0;
}

.navmenu-icon {
    display: none;
}

.main {
    min-height: calc(100dvh - 86px);
    color: var(--neutral-foreground-rest);
    align-items: stretch !important;
}

.body-content {
    align-self: stretch;
    height: calc(100dvh - 86px) !important;
    display: flex;
}

.content {
    padding: 0.5rem 1.5rem;
    align-self: stretch !important;
    width: 100%;
}

.manage {
    width: 100dvw;
}

footer {
    background: var(--neutral-layer-4);
    color: var(--neutral-foreground-rest);
    align-items: center;
    padding: 10px 10px;
}

    footer a {
        color: var(--neutral-foreground-rest);
        text-decoration: none;
    }

        footer a:focus {
            outline: 1px dashed;
            outline-offset: 3px;
        }

        footer a:hover {
            text-decoration: underline;
        }

.alert {
    border: 1px dashed var(--accent-fill-rest);
    padding: 5px;
}


#blazor-error-ui {
    background: lightyellow;
    bottom: 0;
    box-shadow: 0 -1px 2px rgba(0, 0, 0, 0.2);
    display: none;
    left: 0;
    padding: 0.6rem 1.25rem 0.7rem 1.25rem;
    position: fixed;
    width: 100%;
    z-index: 1000;
    margin: 20px 0;
}

    #blazor-error-ui .dismiss {
        cursor: pointer;
        position: absolute;
        right: 0.75rem;
        top: 0.5rem;
    }

.blazor-error-boundary {
    background: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTYiIGhlaWdodD0iNDkiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIG92ZXJmbG93PSJoaWRkZW4iPjxkZWZzPjxjbGlwUGF0aCBpZD0iY2xpcDAiPjxyZWN0IHg9IjIzNSIgeT0iNTEiIHdpZHRoPSI1NiIgaGVpZ2h0PSI0OSIvPjwvY2xpcFBhdGg+PC9kZWZzPjxnIGNsaXAtcGF0aD0idXJsKCNjbGlwMCkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0yMzUgLTUxKSI+PHBhdGggZD0iTTI2My41MDYgNTFDMjY0LjcxNyA1MSAyNjUuODEzIDUxLjQ4MzcgMjY2LjYwNiA1Mi4yNjU4TDI2Ny4wNTIgNTIuNzk4NyAyNjcuNTM5IDUzLjYyODMgMjkwLjE4NSA5Mi4xODMxIDI5MC41NDUgOTIuNzk1IDI5MC42NTYgOTIuOTk2QzI5MC44NzcgOTMuNTEzIDI5MSA5NC4wODE1IDI5MSA5NC42NzgyIDI5MSA5Ny4wNjUxIDI4OS4wMzggOTkgMjg2LjYxNyA5OUwyNDAuMzgzIDk5QzIzNy45NjMgOTkgMjM2IDk3LjA2NTEgMjM2IDk0LjY3ODIgMjM2IDk0LjM3OTkgMjM2LjAzMSA5NC4wODg2IDIzNi4wODkgOTMuODA3MkwyMzYuMzM4IDkzLjAxNjIgMjM2Ljg1OCA5Mi4xMzE0IDI1OS40NzMgNTMuNjI5NCAyNTkuOTYxIDUyLjc5ODUgMjYwLjQwNyA1Mi4yNjU4QzI2MS4yIDUxLjQ4MzcgMjYyLjI5NiA1MSAyNjMuNTA2IDUxWk0yNjMuNTg2IDY2LjAxODNDMjYwLjczNyA2Ni4wMTgzIDI1OS4zMTMgNjcuMTI0NSAyNTkuMzEzIDY5LjMzNyAyNTkuMzEzIDY5LjYxMDIgMjU5LjMzMiA2OS44NjA4IDI1OS4zNzEgNzAuMDg4N0wyNjEuNzk1IDg0LjAxNjEgMjY1LjM4IDg0LjAxNjEgMjY3LjgyMSA2OS43NDc1QzI2Ny44NiA2OS43MzA5IDI2Ny44NzkgNjkuNTg3NyAyNjcuODc5IDY5LjMxNzkgMjY3Ljg3OSA2Ny4xMTgyIDI2Ni40NDggNjYuMDE4MyAyNjMuNTg2IDY2LjAxODNaTTI2My41NzYgODYuMDU0N0MyNjEuMDQ5IDg2LjA1NDcgMjU5Ljc4NiA4Ny4zMDA1IDI1OS43ODYgODkuNzkyMSAyNTkuNzg2IDkyLjI4MzcgMjYxLjA0OSA5My41Mjk1IDI2My41NzYgOTMuNTI5NSAyNjYuMTE2IDkzLjUyOTUgMjY3LjM4NyA5Mi4yODM3IDI2Ny4zODcgODkuNzkyMSAyNjcuMzg3IDg3LjMwMDUgMjY2LjExNiA4Ni4wNTQ3IDI2My41NzYgODYuMDU0N1oiIGZpbGw9IiNGRkU1MDAiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjwvZz48L3N2Zz4=) no-repeat 1rem/1.8rem, #b32121;
    padding: 1rem 1rem 1rem 3.7rem;
    color: white;
}

    .blazor-error-boundary::before {
        content: "An error has occurred. "
    }
```

**Comment by vnbaaij** [comment]
With doing changes mentioned above, things work as expected. Think you can close the issue on the aspnetcore repo.

For our next release (v4.11.0) we will provide a Fluent version of the new Blazor Hybrid + Web App in our Templates package.

**Comment by true-perfect-code** [comment]
Hi @vnbaaij 

Thanks it works. Working App.razor for me is:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    @* <link rel="stylesheet" href="_content/pTodo.Shared/bootstrap/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="_content/pTodo.Shared/app.css" />
    <link rel="stylesheet" href="pTodo.Web.styles.css" />
    @* <link rel="stylesheet" href="@Assets["_content/pTodo.Shared/app.css"]" /> *@
    <link rel="stylesheet" href="_content/Microsoft.FluentUI.AspNetCore.Components.Icons/css/fluent-icons.css" /> *@
    <link rel="icon" type="image/png" href="_content/pTodo.Shared/favicon.png" />

    <HeadOutlet @rendermode="InteractiveServer" />
</head>

<body>
    <Routes @rendermode="InteractiveServer" />
    <script src="_framework/blazor.web.js"></script>
</body>

</html>
```

Odcource with your changes in **Program.cs** and **app.css**. Thanks again for your help.

Regards
pc
