### ISSUE TITLE
fix: When focusable error in FluentMenu

### ISSUE THREAD

**Issue by wisamidris77** [microsoft/fluentui-blazor#2986]
# 🐛 Bug Report

This issue happens when input inside FluentMenu
So when you click or focus in the element or input inside FluentMenu and then focusout
It goes and throw exception

https://github.com/user-attachments/assets/1ab9c653-b60d-4660-bd88-3f8fb2eb5c26

## 💻 Repro or Code Sample

[BlazorApp5.zip](https://github.com/user-attachments/files/17948800/BlazorApp5.zip)
------
Or these code snippets

```razor
<FluentButton OnClick="() => visible = !visible" Id="sample-menu-button">
	Sample Button
</FluentButton>
<FluentMenu @bind-Open="visible" Anchor="sample-menu-button">
	<FluentTextField Label="Input 2"/>
</FluentMenu>
@code {
	public bool visible;
}
```

And in layout

```razor
@* Fluent Layout... *@
<FluentMenuProvider />
```
## 🤔 Expected Behavior

I should be able to focus and focusout from the input with no errors thrown

## 😯 Current Behavior

When I focus in input or focusable element and when focusout throwing this ![Image](https://github.com/user-attachments/assets/12edf12c-e0f8-4975-a6af-87216992417f)

## 💁 Possible Solution

To making a filter there for if it a FluentMenuItem only for making tabIndex -1

## 🔦 Context

Affected me by not making my app works

## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version 9.0.0 and 4.9.3

**Comment by wisamidris77** [comment]
If there any detail missed there just tell me

**Comment by vnbaaij** [comment]
This is something we can work with, thanks. We will investigate soon.
