### ISSUE TITLE
fix: FluentSelect with multiple does not collapse

### ISSUE THREAD

**Issue by svrooij** [microsoft/fluentui-blazor#2996]
# 🐛 Bug Report

The [FluentSelect](https://fluentui-blazor.net/Select#multipleitems) with multiple items does not collapse, which is very annoying.

## 💻 Repro or Code Sample

Demo website 👉 [FluentSelect](https://fluentui-blazor.net/Select#multipleitems)

## 🤔 Expected Behavior

I expect that there would be an arrow button to open/close the selectbox, because it cannot respond to click events if you can multi select items.

Closed it should look like `Value 1, Value3`, or `Value 1, Value 2 (+4)` in case of more then 3 items selected.

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/24374872-95b7-489f-9eb6-a8f90338ee64)

It also has an `Open` property, that does nothing (for multi select)

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Unfortunately, that is not supported by the underlying web component...

![Image](https://github.com/user-attachments/assets/92b35686-20c7-4d14-a250-f21d5ddf574e)

See also #2044 (Which reminds me that I still haven't updated the docs. Will do that now!)
