### ISSUE TITLE
fix: Generated initial project Template for Fluent Blazor App (or Blazor Web App) fails to build as App.Client is incomplete when Auto and per Page/component selected

### ISSUE THREAD

**Issue by jhogan05** [microsoft/fluentui-blazor#2999]
# 🐛 Bug Report

Generated New Project in VS2022 using .Net 8, No authentication,  Auto (Server or Webassesmbly) and (per Page/component) and no sample pages and no top level statements does not build. 

On reviewing the outputted source code the FluentBlazorApp.Client project does not contain any Razor files or folders (e.g Layout or Pages). This results in an error on Build because there is no generated code using the Layout namespace which appears in _Imports.razor

Error (active)	CS0234	The type or namespace name 'Layout' does not exist in the namespace 'BlazorApp6.Client' (are you missing an assembly reference?)	

Switching to (Global) results in a buildable empty app, but running .Client fails

## 💻 Repro or Code Sample

![Image](https://github.com/user-attachments/assets/991574a2-1fe2-4222-afa6-6a414c267898)

## 🤔 Expected Behavior

The initial template should Build regardless of the options selected.

The online reference to the non-fluent version (which is also affected in same way) say:

_In the .Client project:

The Pages folder contains routable client-side Razor components. The route for each page is specified using the [@page](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-9.0#page) directive.

The wwwroot folder is the [Web Root](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-9.0#web-root) folder for the .Client project that holds the app's public static assets.

The Program.cs file is the project's entry point that sets up the WebAssembly [host](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-9.0#host-definition) and contains the project's startup logic, including service registrations, configuration, logging, and request processing pipeline._

## 😯 Current Behavior

Fails to build. .Client appears to generate incompletely. Does not run.

## 💁 Possible Solution

Empty template should run (App and App.Client) after first instantiation.
Should be generated appropriately to give sample of what is trying to achieive with this combination.

## 🔦 Context

New users exploring the different intiial templated outcome and behaviour

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Edge
* .NET Version: 8.0.403
Fluent template version: Microsoft.FluentUI.AspNetCore.Templates::4.10.4

**Comment by jhogan05** [comment]
.NET Version:  8.0.403
Fluent template version: Microsoft.FluentUI.AspNetCore.Templates::4.10.4

**Comment by vnbaaij** [comment]
Will be fixed with next Template (v4.11.0) package
