### ISSUE TITLE
FluentDatePicker horizontal position

### ISSUE THREAD

**Issue by geowong2022** [microsoft/fluentui-blazor#3000]
![Image](https://github.com/user-attachments/assets/b3921f7b-fab0-4aca-b8d6-5482fc369e22)

Hi all,

I had an issue where the calendar on the right cut into half when it hit on the right side of the screen. May I know if there is anyway I can set the position to the left?

Thank you so much for your help.

**Comment by dvoituron** [comment]
Will be fixed in the next Release: #3001
