### ISSUE TITLE
Lightweight datagrid to work around MAUI JS bug (#1036).

### ISSUE THREAD

**Issue by true-perfect-code** [microsoft/fluentui-blazor#3008]
It would be very helpful to have a lightweight datagrid that does not use JS resources. This would avoid the problem https://github.com/microsoft/fluentui-blazor/issues/1036 .

Current workarounds to this problem #1036 don't help much (e.g. prevent F5 on MAUI Blazor or don't show Fluentdatagrid before navigating). The only really useful solution here is to switch to a pure HTML/CSS table and that would be a shame.

But if we have a small version of datagrid, you would no longer have to do this.

As far as we understand, the bug fix in MAUI was already planned for version NET 9, but has now been moved to version NET 10. It will probably be years before this problem is finally fixed by MAUI Team! All the more reason to get active on the FluentUI Blazor site, isn't it?

Justin

**Comment by vnbaaij** [comment]
Without any JS, a grid would not offer a lot of useful functionality. Thinks like sorting and resizing won't be available. A pure, styled, HTML table seems a good solution in that case. You should be able to get that by working with the CSS files we provide

We are not planning on adding a second/specific data grid for this. Besides simply lacking resources to do so, I don't think it would be a very useful component to have. The issue really needs to be solved on the MAUI side.

**Comment by true-perfect-code** [comment]
@vnbaaij  Thanks for the quick reply.

**It's not about deleting JS completely,** but to identify the current Datagrid JS functionalities that result in this issue with JS resource release.

Virtualization could be one such feature, but however I am not at all familiar with what has been programmed into JS in Fluentdatagrid and what could be reason this JS error be triggered via JS resource release in MAUI.

Another possibility would be to adapt existing Fluentdatagrid so that the functionality (of JS resource allocation) is “switched off” when setting specific parameters (e.g. virtualisation = false). So we could also work around this problem, if one or the other Fluentdatagrid functionality is “switched off” that we do not need, but which would trigger the problem of JS resource release (e.g. if the MAUI page is suddenly left via F5).

**It would be a real shame if this problem existed just because the current JS Datagrid script is reserving some JS resources that no one (or someone very rarely) actually uses and that finally causes us this MAUI problem!**

I don't expect much from the MAUI team. On the other hand, you can't expect the user not to be able to bring his MAUI app back to its original state by pressing F5 (on Windows/Mac). Not to mention that there will certainly still be situations where the app will reload itself on a mobile device and this problem will then occur automatically also if the user has not requested a refresh.

Thanks
justin

**Comment by vnbaaij** [comment]
The issue in MAUI with the datagrid goes deeper than only refresh actions. Think it will be very hard to pinpoint and isolate what is triggering the error.

As said, it really needs to be solved on the MAUI side as it is a general error with the WebView icw Blazor.
