### ISSUE TITLE
fix: [what is the issue?] in [where is the issue?]

### ISSUE THREAD

**Issue by cidelab** [microsoft/fluentui-blazor#3018]
# 🐛 Bug Report

I got the error "An unhandled error has occurred. Reload". Unfortunately I haven't been able to resolved following the recommended methods from other posts. My objective is to implement sliders and components from FluentUI to control graphics displayed with ScottPlot. If I remove the FluentUI code from the razor page it's render correct.

I'm using the versionFluentUI 4.10.4 and ScottPlot 5.0.47.

## 💻 Repro or Code Sample
`@using ScottPlot;
@using ScottPlot.Blazor;
@using Microsoft.FluentUI.AspNetCore.Components;

<div style="margin-bottom: 60px;">
    <FluentButton style="width: 90px; margin: 10px;" @onclick="() => orientation = (orientation == Microsoft.FluentUI.AspNetCore.Components.Orientation.Vertical) ? Microsoft.FluentUI.AspNetCore.Components.Orientation.Horizontal : Microsoft.FluentUI.AspNetCore.Components.Orientation.Vertical">Toggle orientation</FluentButton>
    <FluentSlider Label="Select a temperature" Orientation="@orientation" Min="0" Max="100" Step="10" @bind-Value=value>
        <FluentSliderLabel Position="0">0&#8451;</FluentSliderLabel>
        <FluentSliderLabel Position="10">10&#8451;</FluentSliderLabel>
        <FluentSliderLabel Position="90">90&#8451;</FluentSliderLabel>
        <FluentSliderLabel Position="100">100&#8451;</FluentSliderLabel>
    </FluentSlider>
</div>
<p>Selected value: @value</p>

<BlazorPlot @ref=Sigmoid Style="width: 600px; height: 300px;" />

@code {

    Microsoft.FluentUI.AspNetCore.Components.Orientation orientation = Microsoft.FluentUI.AspNetCore.Components.Orientation.Horizontal;
    int value = 70;

    BlazorPlot Sigmoid { get; set; } = new();

    protected override void OnAfterRender(bool firstRender)
    {
        double[] fltData = new double[100];
        float[] arrFltData = new float[100];

        for (int i = 0; i < 100; i++)
        {
            fltData[i] = i;
            arrFltData[i] = (float)Function.Sigmoid(fltData[i], 1, 100, 1, 100, 0.001);
        }
        Sigmoid.Plot.Add.Signal(Tools.Convert2Doubles(fltData.ToList()));
        ScottPlot.Plottables.Signal sign2 = Sigmoid.Plot.Add.Signal(Tools.Convert2Doubles(arrFltData.ToList()));
        sign2.LineColor = Colors.Red;
        Sigmoid.Plot.Title("complex Sigmoid function");
    }

}
`
## 🤔 Expected Behavior

Render the slider and the graphic.

## 😯 Current Behavior

error

## 💁 Possible Solution

no idea, I also I haven't being able to debug the page.

## 🔦 Context

My objective is to implement sliders and components from FluentUI to control graphics displayed with ScottPlot. 
If I remove the FluentUI code from the razor page it's render correct with no error.

I'm using the versionFluentUI 4.10.4 and ScottPlot 5.0.47.

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Microsoft Edge
* .NET 8.0 and Fluent UI Blazor library Version 4.10.4
* I have created a BlazorwebAssemblyStandalone app and I have added FluentUI.AspNetCore.Components 4.10.4 from nugget
* Visual studio community

**Comment by vnbaaij** [comment]
Closed due to inactivity
