### ISSUE TITLE
Using dotnet templates results in build error

### ISSUE THREAD

**Issue by mbhoek** [microsoft/fluentui-blazor#3020]
# 🐛 Bug Report

I followed the 'using our dotnet templates' instructions in README.md. 

If I try to build the project, it results in multiple "The type or namespace name 'Icons' could not be found" errors.

## 💻 Repro or Code Sample

```
$ dotnet new install Microsoft.FluentUI.AspNetCore.Templates

The following template packages will be installed:
   Microsoft.FluentUI.AspNetCore.Templates

Success: Microsoft.FluentUI.AspNetCore.Templates::4.10.4 installed the following templates:
Template Name                             Short Name        Language  Tags
----------------------------------------  ----------------  --------  ---------------------------------
Fluent Blazor Web App                     fluentblazor      [C#]      Web/Fluent/Blazor/WebAssembly
Fluent Blazor WebAssembly Standalone App  fluentblazorwasm  [C#]      Web/Fluent/Blazor/WebAssembly/PWA
```

```
$ dotnet new fluentblazorwasm

The template "Fluent Blazor WebAssembly Standalone App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/8.0-third-party-notices for details.

Processing post-creation actions...
Restoring C:\Projects\FluentBlazor\FluentBlazor.csproj:
Restore succeeded.
```

```
$ dotnet build

Restore complete (0,3s)
  FluentBlazor failed with 4 error(s) (3,2s)
    C:\Projects\FluentBlazor\Layout\NavMenu.razor(3,79): error CS0246: The type or namespace name 'Icons' could not be found (are you missing a using directive or an assembly reference?)
    C:\Projects\FluentBlazor\Layout\NavMenu.razor(6,75): error CS0246: The type or namespace name 'Icons' could not be found (are you missing a using directive or an assembly reference?)
    C:\Projects\FluentBlazor\Layout\NavMenu.razor(7,56): error CS0246: The type or namespace name 'Icons' could not be found (are you missing a using directive or an assembly reference?)
    C:\Projects\FluentBlazor\Layout\NavMenu.razor(8,56): error CS0246: The type or namespace name 'Icons' could not be found (are you missing a using directive or an assembly reference?)

Build failed with 4 error(s) in 4,1s
```

## 🤔 Expected Behavior

I expected the project to build succesfully after using the template.

## 😯 Current Behavior

The build fails with multiple "error CS0246: The type or namespace name 'Icons' could not be found (are you missing a using directive or an assembly reference?)" errors. 

## 💁 Possible Solution

I suspect the generated project is missing a reference to the `Microsoft.FluentUI.AspNetCore.Components.Icons` NuGet package.

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* .NET 8 and Fluent UI Blazor 4.10.4

**Comment by vnbaaij** [comment]
Hi,

We just made some changes to the Core and Icons package for v4.11.0 (beta packages have been released just now). The templates for v4.10.4 point to download the latest version so you might actually be using 4.11.0-beta.1 for the components and Icons now. 

Tom make it work you need to add
```
@using Icons = Microsoft.FluentUI.AspNetCore.Components.Icons 
```

to your `_Imports.razor`


Please see the documentation on our **[preview](https://preview.fluentui-blazore.net)** site for more information.

After installing our new template package, things will be set up to work out of the box again.

**Comment by nhwilly** [comment]
This one got me, too.  Thanks for the quick fix!

**Comment by mbhoek** [comment]
@vnbaaij I'm new to Fluent UI Blazor, so apologies if I sound too forward but..

If you're introducing breaking changes in minor version upgrades (i.e. 4.10 to 4.11) doesn't make it sense to lock the 4.10 templates to the 4.10 components (and not the latest or `Version="4.*-*"` as it is now)? And to have separate 4.11.0-beta templates if you want to use the 4.11.0-beta components?

**Comment by vnbaaij** [comment]
Yes, we should have done that. But we made the error with publishing the template package with the `Version=4.*-*` before and are correcting that now (with the unfortunate effect you were getting). 
From now on the template package will always use for Version  the version of the package they are released with.

**Comment by mbhoek** [comment]
Thanks for the explanation! 👍

**Comment by VietNT2011** [comment]
![Image](https://github.com/user-attachments/assets/ea1b3ead-0b34-40e7-9bea-907844d57bea)
please help me! Why is the datagrid located vertically?

**Comment by dvoituron** [comment]
> ![Image](https://github.com/user-attachments/assets/ea1b3ead-0b34-40e7-9bea-907844d57bea) please help me! Why is the datagrid located vertically?

Without code, this is complicated :-)
Do you have an example of this page? Including Styles or CSS?

**Comment by vnbaaij** [comment]
Please don't attach an issue to a closed issue. Create a new issue an append reproduction code!

**Comment by iftiharh** [comment]
I have the same grid problem after upgrade to 4.11.0-beta. Which issue can I follow for the solution to the problem?

**Comment by vnbaaij** [comment]
> I have the same grid problem after upgrade to 4.11.0-beta. Which issue can I follow for the solution to the problem?

Just look at the issue overview... #3021
