### ISSUE TITLE
fix: Using Icons in Template

### ISSUE THREAD

**Issue by cliedeman** [microsoft/fluentui-blazor#3022]
# 🐛 Bug Report

A fresh template project does does not work due to a missing import

```
@using Icons = Microsoft.FluentUI.AspNetCore.Components.Icons`
```

as recomended in https://github.com/microsoft/fluentui-blazor/tree/dev/src/Assets/FluentUI.Icons#usage

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by cliedeman** [comment]
Tracked this down to the `Version="4.*-*"` which is defaulting to the Beta release

**Comment by vnbaaij** [comment]
If you want to use the beta components package, that using is needed indeed.

The beta templates package has the needed line in place

**Comment by cliedeman** [comment]
Thanks @vnbaaij . I wasnt trying to use the beta package 

https://github.com/microsoft/fluentui-blazor/blob/v4.10.4/src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/BlazorWeb-CSharp.csproj#L32

but it was getting pulled in

**Comment by vnbaaij** [comment]
Yes, it is a wrong configuration in our current template
