### ISSUE TITLE
Autocomplete Required Validation Not Working as Expected

### ISSUE THREAD

**Issue by VBTXDeveloper** [microsoft/fluentui-blazor#3025]
# 🐛 Bug Report

Using the Autocomplete control, we are dynamically setting required to "true" when a different control is populated.
This properly sets the requirement; you cannot submit the form when the control is empty.
However, the issue is that field remains required and will not validate, even after you select a value.

## 💻 Repro or Code Sample

![Image](https://github.com/user-attachments/assets/2bd703a5-b042-4b9a-b933-c5ac3cd8f454)

## 🤔 Expected Behavior

When we select a value in the autocomplete control, it should no longer say that the field is required, and allow the form to submit.

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/3c3c855c-3a5d-44b6-95b8-266a1338d2d5)

## 💁 Possible Solution

I suspect there is an additional property we need to set when a selection is made?

## 🌍 Your Environment

* .NET 9
* Fluent UI Blazor library Version 4.10.4

**Comment by dvoituron** [comment]
1. You will find here an example of Autocomplete with Required property defined: https://fluentui-blazor.net/Forms
2. As indicated on [this page](https://fluentui-blazor.net/Autocomplete) : 
    > The FluentAutocomplete component is not yet fully compatible with the EditForm and FluentEditForm elements. Some functionalities, such as error messages, the requirement message or the validation messages are missing.
3. Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository. We do not have capacity to craft or compose a reproduction for every issue that gets raised. If no code or repository is provided, this issue will be closed in 3 days.
  Help us to help you. Thanks.

**Comment by VBTXDeveloper** [comment]
Thank you. I have attached a example of a required autocomplete control, that will still show the requirement message, even after a selection has been made.  Please let me know if I can provide additional context.  Thank you,[BlazorTestApp.zip](https://github.com/user-attachments/files/18065963/BlazorTestApp.zip)

**Comment by vnbaaij** [comment]
Closing this as Denis mentioned in his second point that this is not a supported scenario
