### ISSUE TITLE
feat: add backdrop to/in DialogService.ShowConfirmationAsync()-method

### ISSUE THREAD

**Issue by DM-98** [microsoft/fluentui-blazor#3027]
# 🙋 Feature Request
I'd like DialogService.ShowConfirmationAsync-method to be able to show a backdrop (faded background) just like a modal, so the user will not be confused why nothing is happening, since the confirmation modal is not that visibly obvious when opened.

**Comment by vnbaaij** [comment]
`ShowConfirmationAsync` is just a utility method. We want to keep this method as simple as possible. It is calling `ShowDialogAsync` internally. If you want to get the backdrop, you can just use `ShowDialogAsync` directly.
