### ISSUE TITLE
fix: FluentAutocomplete tooltips for option template show too many

### ISSUE THREAD

**Issue by bLinMil** [microsoft/fluentui-blazor#3039]
# 🐛 Bug Report

Using tooltip for option template doesnt hide when scrolling options for fluent autocomplete.
It will show for each item the right tool tip, but when I scroll fast, it starts showing multiple tooltips.

## 💻 Repro or Code Sample

```
<FluentAutocomplete TOption="Person"
                    AutoComplete="off"
                    Items="people"
                    Placeholder="Select Datapoints"
                    MaximumSelectedOptions="25"
                    MaximumOptionsSearch="@people.Count()"
                    Multiple="true"
                    KeepOpen="true"
                    Width="200px"
                    Height="250px"
                    Virtualize="true"
                    OptionTemplate="@AdditionalDatapointOption" />
@code {
    List<Person> people = new();

    protected override void OnInitialized()
    {
        for (int i = 0; i < 30; i++)
        {
            var x = new Person(i, "testtesttest" + i, new DateOnly(1985, 3, 16));
            people.Add(x);
        }
        StateHasChanged();
    }

    record Person(int PersonId, string Name, DateOnly BirthDate)
    {
        public bool FocusedRow { get; set; }
    }

    RenderFragment<Person> AdditionalDatapointOption = (Person opt) =>
    @<div><FluentLabel Id="@opt.Name">@opt.Name</FluentLabel><FluentTooltip HideTooltipOnCursorLeave="true" Delay="5" Position="TooltipPosition.Right" Anchor="@opt.Name">@opt.Name</FluentTooltip></div>;

}
```

## 🤔 Expected Behavior

When I scroll it should just show or even hide the last items tooltip then when I hover over a new element, it should show just one, new tooltip.

## 😯 Current Behavior

It spams a lot of tooltips and sporadically places them around the screen

## 💁 Possible Solution

I don't know a solution but it does work for a FluentSelect with multiple elements and virtualized scrolling

## 🌍 Your Environment

Windows on PC
Edge
Fluent UI Components 4.10.4
.NET 8.0.404

**Comment by vnbaaij** [comment]
Use 3 ` for starting and ending a code block

**Comment by bLinMil** [comment]
Please find attached a screen recording as well.
https://github.com/user-attachments/assets/8a3e62ff-2bda-403b-b162-8505b43be529

**Comment by vnbaaij** [comment]
First, using a tooltip for an option that is shown in a listbox kind of control is _not_ a recommended approach. I've not **ever** seen that being used before.

Second, the `StateHasChanged` in `OnInitialized` is unnecessary.

Third, with this code it is not possible to actually have a selection be shown in the AutoComplete.


You can fix this by adding `UseTooltipService="false"` to the Tooltip tag.
