### ISSUE TITLE
Immediate doesn't work in TextField

### ISSUE THREAD

**Issue by NicoDevelops** [microsoft/fluentui-blazor#3041]
# 🐛 Bug Report

FluentTextField has Immediate and ImmediateDelay options to react to the value changing immediately. They don't work right now.

Seems to be identical to [Issue 2672](https://github.com/microsoft/fluentui-blazor/issues/2672).

I suppose this is also the case for the FluentNumberField.

## 💻 Repro or Code Sample

The problem appears to be that FluentTextField doesn't bind `oncontolinput`, as seen in Issue 2672's resolving Pullrequest #2685:

See FluentCombobox.razor changes [here](https://github.com/microsoft/fluentui-blazor/pull/2685/commits/f4ff1b8f6cca9e2ef1320669092f9a3ad2a49bf6#diff-b3f57806c2983bf7cbe1b2cfe49b81a1c6b74cb78a24f47e7d524ee07d3248a3).

## 🤔 Expected Behavior

ValueChanged raised while typing in a text field when immediate is true.

## 😯 Current Behavior

ValueChanged is only raised when focus leaves the combo box.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by dvoituron** [comment]
I cannot reproduce your issue.

I'm used this code:
```razor
<FluentTextField @bind-Value="value1" Immediate="true"></FluentTextField>
<p>You entered: @value1</p>

@code {
    string? value1;
}
```
And the result is correct:
![Image](https://github.com/user-attachments/assets/bdc6bb38-b4af-49ba-91d4-5e9ae1ac11fe)

**Comment by MarvinKlein1508** [comment]
@NicoDevelops it works for me as well. Which rendering mode are you using? When you are using the SSR render mode then their won't be any interactivitiy.
