### ISSUE TITLE
feat: Change project templates to exclude preview releases

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#3048]
# 🙋 Feature Request

Creating a new Fluent Web app shouldn't target preview packages by default. For the current one it results in non compilable code because of the new Icon changes.

## 🤔 Expected Behavior

The templates should target the latest stable release.

## 😯 Current Behavior

Right now the latest beta version is the default for new projects.

**Comment by dvoituron** [comment]
Duplicated #3022

**Comment by vnbaaij** [comment]
> Right now the latest beta version is the default for new projects.

Yes, we had to break it somewhere to correct that and we have done so now. 

Moving forward, a site created with the new templates will reference the packages with the same version as the template. You can still upgrade to a newer version of the packages if those are available
