### ISSUE TITLE
feat: Datagrid: Add column accessibility

### ISSUE THREAD

**Issue by bLinMil** [microsoft/fluentui-blazor#3049]
# 🙋 Feature Request

I would to access the data grid to obtain the current column that is being used to sort the data grid.
In addition, could their be a way to have a method RemoveSortByColumn(string title)?
^(Similar to this feature request and pr: https://github.com/microsoft/fluentui-blazor/issues/2148, https://github.com/microsoft/fluentui-blazor/pull/2156/files)

## 🤔 Expected Behavior

- Access the column that currently has sorting applied to it and have access to its title
- Remove sorting by column given a title

## 😯 Current Behavior

No way to access or modify the datagrid in this manner

## 💁 Possible Solution

There is a ``` private ColumnBase<TGridItem>? _sortByColumn;``` could this be exposed with a getter?

## 🔦 Context

I have a grid where I am dynamically removing columns (not rendering them) and when that column has sorting applied but then removed, I want the sorting to be removed so when I call ApplySorting in my request in my items provider, nothing will change.

**Comment by bLinMil** [comment]
Edit: found a work around. I can find the sorted column from the request in the items provider. Then I can catch and store it there and use it to check if I remove a column that is the sorted column. If so, then I call _gridRef.RemoveColumnSortAsync() to clear my sort.

**Comment by vnbaaij** [comment]
Closing this one then

**Comment by nodefusioncom** [comment]
@vnbaaij 

This feature is very important for our use case. We need to know which column is currently sorted and in which direction, so we can send the correct OData $orderby parameter to our backend API. This is essential for implementing proper server-side paging and sorting in our Blazor WebAssembly application. Without this capability, we cannot synchronize the grid’s sort state with our backend, which is a critical requirement for our project.
