### ISSUE TITLE
FluentMessageBar unreadable in dark theme

### ISSUE THREAD

**Issue by alexagmanic** [microsoft/fluentui-blazor#3050]
# 🐛 Bug Report

FluentMessageBar is displayed with a white font on a white background when using a dark theme.

## 💻 Repro or Code Sample

- Create a new project using the template:

dotnet new fluentblazor --name ReproDarkThemeMessage

- Open the project in visual studio

- In App.razor, add the line:

```xml
<FluentDesignTheme Mode="DesignThemeModes.Dark" />
```

before the head element:

![Image](https://github.com/user-attachments/assets/b6eaa8e3-2815-48d3-abe3-7cc4e40ff410)

- In Home.razor, add the line:

```xml
<FluentMessageBar Title="Test" />
```

after the Hello World header:

![Image](https://github.com/user-attachments/assets/6bdfc4f8-461e-4c3c-90bd-a23efef5274a)

- Build and run the project.

## 🤔 Expected Behavior

We would expect either the background or the text of the message bar to be of a different color such that the message is readable.

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/60a8336c-55c7-4313-bdaa-989aab7f9163)

## 🌍 Your Environment

* OS & Device: Windows PC
* Browser: Microsoft Edge
* .NET 8 and Fluent UI Blazor Version 4.10.3 (and 4.10.4 and 4.11.0-beta.1)

**Comment by vnbaaij** [comment]
Closed as duplicate. Please see #2200
