### ISSUE TITLE
feat: add customizing to KeyCodeService

### ISSUE THREAD

**Issue by minimalisticMe** [microsoft/fluentui-blazor#3052]
# 🙋 Feature Request
I would like to override specific default browser behavior in `KeyCodeService` when using `OnKeyDownAsync`. I know I can prevent **all** default browser behavior at once with
```
<FluentKeyCodeProvider PreventDefault="true" />
```
With this I can prevent page jumping when pressing `[SPACE]`, debugging with `[F12]` or navigating forth/back with `[ALT]` + `[<-]` / `[->]`. However I would prefer to have some of these default behaviors while preventing to have others. 

For example I have custom use for the `[SPACE]` key, so I do not want to have default prowser behavior.
On the other hand I would like to stilll be able to navigate with `[ALT]` + `[<-]` / `[->]` or debug with `[F12]`.

It feels wrong to prevent all default behavior just to reimplement some behavior that I want to keep.

## 🤔 Expected Behavior

Configure specific keys that I want to use custom logic instead of default browser behavior.

## 😯 Current Behavior

Either all default behavior is prevented or none, no distinction can be made.

## 💁 Possible Solution

I think this could be managed with a optional parameter, that configures which keys will override default behavior. Per default none of the keys implement `event.preventDefault();` and only explicitely configured keys implement `event.preventDefault();`.

**Comment by dvoituron** [comment]
You can use 
- `Only` to specify the list of KeyCode to accept, and only this list, when evaluating the key code.
- `PreventDefaultOnly` to specify the list of **KeyCode** to tells the user agent that if the event does not get explicitly handled.

With these properties, you should solve your questions.

**Comment by f4n0** [comment]
Hi, I've found out this issue! 
I would like to use the PreventDefaultOnly in the KeyCodeProvider, but as now it is not possible (in the provider you can only set the PreventDefaults, not the others)! 
Is it possible to add also this one? Shall I open a new issue?

**Comment by dvoituron** [comment]
The `KeyCodeProvider` is a global (document) key manager. If you want to customize it using `PreventDefaultOnly`, you need to use the `FluentKeyCode` component. 

I don't think a good idea to define only some keys in the global manager.

**Comment by minimalisticMe** [comment]
Initally I thougt setting this global is the best way.
Upon thinking about it a bit more, I came to the conclusion, doing this local is also more than fine.
