### ISSUE TITLE
docs: fix icon documentation in tree view

### ISSUE THREAD

**Issue by Zyberg** [microsoft/fluentui-blazor#3058]
# 🙋 Documentation Request

Treeview [documentation](https://www.fluentui-blazor.net/TreeView) for icon expanded and collapsed is mixed up (is inverse):

![Image](https://github.com/user-attachments/assets/f7350baa-f9dc-4578-9493-4d4d546d8748)

## 💁 Possible Solution
https://github.com/microsoft/fluentui-blazor/blob/61ef3de5e4fa21376fd10d7b7d7d05834dd0a21f/src/Core/Components/TreeView/FluentTreeItem.razor.cs#L80-L94 

Either: for collapsed, correct the ref tag to point to collapsed; for expanded correct the ref tag to point to expanded.
![Image](https://github.com/user-attachments/assets/e3498421-05e4-43f0-83d5-d2926705d4e7)

Or, if this is really intended, then a quick explanation on why that is the case would be useful.

**Comment by MarvinKlein1508** [comment]
Looks right to me. It clearly says when `IconExpanded` is **not set** then `IconCollapsed` will be used and vice versa.

**Comment by Zyberg** [comment]
But why would you want a default from a state `X` to be displayed in `!X` case? It seems counter intuitive to me that expanded uses collapsed icon, if expanded has no icon of its own.

**Comment by vnbaaij** [comment]
This is just a fallback for situations were people want to specify only 1 icon (and where the icon does not necessarily have to show an expanded/collapsed state!!)
