### ISSUE TITLE
fix: row height in FluentGrid in manual mode

### ISSUE THREAD

**Issue by JarJasAskom** [microsoft/fluentui-blazor#3070]
# 🐛 Bug Report

One of the rows in the fluent grid in manual mode is much too tall.

![Image](https://github.com/user-attachments/assets/cd884533-8a7c-47f4-b62e-3b7030944964)

## 💻 Repro or Code Sample

https://github.com/JarJasAskom/TestApplicationRepro

## 🤔 Expected Behavior

All rows have the same height.

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser Google Chrome
* .NET 9 and Fluent UI Blazor library Version 4.11

**Comment by vnbaaij** [comment]
This is caused by a CSS issue in your code...

![Image](https://github.com/user-attachments/assets/519f1459-bb5c-4e24-bcf1-2006ef27cdf9)

**Comment by JarJasAskom** [comment]
Come on! It is not my code. It is your code. This code is generated by Microsoft.FluentUI.AspNetCore.Templates. Even by the latest version:

<code>
@import '/_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css';

body {
    --body-font: "Segoe UI Variable", "Segoe UI", sans-serif;
    font-family: var(--body-font);
    font-size: var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    margin: 0;
}

.navmenu-icon {
    display: none;
}

.main {
    min-height: calc(100dvh - 86px);
    color: var(--neutral-foreground-rest);
    align-items: stretch !important;
}

.body-content {
    align-self: stretch;
    height: calc(100dvh - 86px) !important;
    display: flex;
}
<b>
.content {
    padding: 0.5rem 1.5rem;
    align-self: stretch !important;
    width: 100%;
}
</b>

</code>

**Comment by JarJasAskom** [comment]
Honestly, I was planning to test the beta version, but suddenly the release just dropped...

I've checked my project, and it does not use the CSS rule align-self at all.

Regarding "no extra layout being applied," it turns out that wrapping the FluentDataGrid with a div causes all rows to have the correct height:


```
<div>
    <FluentDataGrid GenerateHeader=GenerateHeaderOption.None 
                               GridTemplateColumns="1fr 2fr" TGridItem="string" MultiLine="true">
        @foreach (var row in mNamePlateRows)
        {
            <FluentDataGridRow>
                <FluentDataGridCell GridColumn=1>@row.Label</FluentDataGridCell>
                <FluentDataGridCell GridColumn=2>@row.Text</FluentDataGridCell>
            </FluentDataGridRow>
        }
    </FluentDataGrid>
</div>

```
