### ISSUE TITLE
fix: ItemSize in FluentDataGrid

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#3071]
# 🐛 Bug Report

For some reason the `ItemSize` property is used in v4.11.0 of the component which results in all rows being 32px height in `FluentDataGrid` Which results into some cut-off content for me:

![Image](https://github.com/user-attachments/assets/fbe763d7-b7c5-4545-963e-31217e90e60b)

The cause for this issue is this line:
https://github.com/microsoft/fluentui-blazor/blob/6501cec3bc8e40480943cab7998d5025509e1373/src/Core/Components/DataGrid/FluentDataGrid.razor#L118

According to the docs this property should only have an effect when virtualization is being used:
![Image](https://github.com/user-attachments/assets/311db498-8781-4be1-af6d-ebf5bc98bf26)

Which is definately not the case for me:
```razor
<FluentDataGrid Items="@Data.AsQueryable()" GenerateHeader="GenerateHeaderOption.Sticky"  TGridItem="Stammdatensatz" Style="min-width: max-content;">
    <TemplateColumn Width="150px" Title="Aktion">
        <FluentButton @onclick="async () => await OnItemSelected.InvokeAsync(context)">Auswählen</FluentButton>
    </TemplateColumn>
    <PropertyColumn Width="200px" Property="@(p => p.Art)" />
    <PropertyColumn Property="@(p => p.Kurzbezeichnung)" />
    <PropertyColumn Width="125px" Property="@(p => p.GetEindeutigeNummer())" Title="Identifier" />
    <PropertyColumn Property="@(p => p.Name1)" Title="Name" />
    <PropertyColumn Property="@(p => p.Strasse)" Title="Straße" />
    <PropertyColumn Property="@(p => p.Ort)" />
    <PropertyColumn Property="@(p => p.Postleitzahl)" Title="PLZ" />
</FluentDataGrid>
```

## 🤔 Expected Behavior

I expect the columns to use auto-height by default

## 😯 Current Behavior

`ItemSize` will always be applied.

## 🔦 Context
Why do you even need the `ItemSize` in the first place? I've never specified it for `Virtualize` in my project at all and it always had used default auto height here as well. I know you can specify it but why should I?

## 🌍 Your Environment

.NET 9 & Fluent UI 4.11.0

All major browsers

**Comment by vnbaaij** [comment]
> Why do you even need the `ItemSize` in the first place? I've never specified it for `Virtualize` in my project at all and it always had used default auto height here as well. I know you can specify it but why should I?

Because `Virtualize` will fall apart if you have rows of different heights.

For the new DataGrid we now have the `RowSize` parameter (which we should probably document better!!) which uses the `DataGridRowSize` enumeration for its type and defaults to `Small` (= 32px).

There are examples of using this at https://www.fluentui-blazor.net/DataGrid#templatecolumns and https://www.fluentui-blazor.net/DataGrid#templatecolumns2

The line 118 you are referring to is only used when a placeholder row is being rendered (ie when you are using Virtualize and going through a large grid quickly)

**Comment by MarvinKlein1508** [comment]
Thanks for the clarification. Indeed setting it to Medium works fine for me. As my last effort at work this year I will update it in my projects and then I relax for the rest of the year. 

You can keep this issue open if you want to improve the documentation. Otherwise feel free to close it! :)

**Comment by vnbaaij** [comment]
Docs added

**Comment by imuller** [comment]
Ok, but what if we want it larger?

**Comment by vnbaaij** [comment]
We do not have any plans to offer other sizes than what we have in the DataGridRowSize enum (ie 24, 32,44 and 58px)
