### ISSUE TITLE
[System.ArgumentNullException: <FluentMenuProvider /> needs to be added to the main layout of your application/site.] in [FluentMenu.razor.cs:line 188]

### ISSUE THREAD

**Issue by abednejad** [microsoft/fluentui-blazor#3081]
# 🐛 Bug Report

Hello  everyone

When I am using FluentDatagrid and enable HeaderCellAsButtonWithMenu="true" I am getting the following error

Error: System.ArgumentNullException: <FluentMenuProvider /> needs to be added to the main layout of your application/site. (Parameter 'UseMenuService')
   at Microsoft.FluentUI.AspNetCore.Components.FluentMenu.OnInitialized() in /_/src/Core/Components/Menu/FluentMenu.razor.cs:line 188
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

this error do not happen when use Fluent v4.10.2, but as soon as you update the Library to upper Versions like 4.11.0 it occurs. 
in first load of page everything run ok but in first try to reload page with(F5) the error appears.

## 💻 Repro or Code Sample

      <FluentDataGrid @ref="grid" Items="ccp"
                      ShowHover="true"
                      ResizableColumns=true
                      ResizeType="DataGridResizeType.Discrete"
                      ItemSize="54"
                      GridTemplateColumns="1fr 1fr 1fr 1fr "
                      Style="height: 400px;"
                       HeaderCellAsButtonWithMenu="true">
          <ChildContent>

              <Microsoft.FluentUI.AspNetCore.Components.PropertyColumn Property="@(c=> c.Date.ToShortDateString())" Sortable="true" />
              <Microsoft.FluentUI.AspNetCore.Components.PropertyColumn Property="@(c=> c.TemperatureC)" Sortable="true" />
              <Microsoft.FluentUI.AspNetCore.Components.PropertyColumn Property="@(c=> c.TemperatureF)" Sortable="true" />
              <Microsoft.FluentUI.AspNetCore.Components.PropertyColumn Property="@(c=> c.Summary)" Sortable="true" />

          </ChildContent>
      </FluentDataGrid>

 

@code {

    protected override async Task OnInitializedAsync()
    {

        var startDate = DateOnly.FromDateTime(DateTime.Now);
        var summaries = new[] { "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching" };

        try
        {

            var ss = Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = startDate,
                TemperatureC = 50,
                Summary = summaries[1]
            });

            ccp = ss.AsQueryable();
        }
        catch (Exception ex)
        {

            ex = ex;
        }

      

    }

    private class WeatherForecast
    {
        public DateOnly Date { get; set; }
        public int TemperatureC { get; set; }
        public string Summary { get; set; }
        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
    }

    //------------FluentUi DataGrid

    FluentDataGrid<WeatherForecast>? grid;

    Microsoft.FluentUI.AspNetCore.Components.PaginationState FluentPagination = new Microsoft.FluentUI.AspNetCore.Components.PaginationState { ItemsPerPage = 10 };

    private IQueryable<WeatherForecast?> ccp { get; set; } = null;

}

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.11.0]

**Comment by abednejad** [comment]
It must Be mentioned that 
I Added 
<FluentMenuProvider @rendermode="InteractiveServer" />

to my main Layout

**Comment by vnbaaij** [comment]
It is logical that you did not get that error before. MenuProvider has only been added recently.
What is the rendermode of your application itself? And what is the rendermode of the page you are using the grid on?

**Comment by abednejad** [comment]
Hi
I find out that it need to add
<FluentMenuProvider @rendermode="InteractiveServer" />

before the @body section in main layout
and in next run it works correctly.

according to the fluent Installation page it's recommended to add at the end of main section and after  @Body

**Comment by abednejad** [comment]
> It is logical that you did not get that error before. MenuProvider has only been added recently. What is the rendermode of your application itself? And what is the rendermode of the page you are using the grid on?

my rendermode set per page  and it is InteractiveServer

**Comment by vnbaaij** [comment]
Ok, closing this one then as you have a fix.
