### ISSUE TITLE
fix: ForceLoad="true" flag in FluentNavLink does not seem to force-load

### ISSUE THREAD

**Issue by frindler** [microsoft/fluentui-blazor#3083]
# 🐛 Bug Report

The ForceLoad="true" flag in FluentNavLink does not seem to force-load

## 💻 Repro or Code Sample

* Set up the FluentUI WebApp template
* Add `ForceLoad="true"` to all the `FluentNavLink`s, e.g. `<FluentNavLink Href="counter" ForceLoad="true">` 
* Run
* Click on the nav links...

## 🤔 Expected Behavior

The page should force-reload

## 😯 Current Behavior

The navigation events become fetches (i.e. _not_ force-loads). See:

![Image](https://github.com/user-attachments/assets/9a03d556-2cfc-49e0-8af6-612858aeaf20)

## 💁 Possible Solution

Force-reload via `Navigation.NavigateTo(Navigation.Uri, forceLoad: true);`, e.g:
add `<FluentButton OnClick="OnReloadClicked">Reload</FluentButton>` and
```
private void OnReloadClicked()
    {
        Navigation.NavigateTo(Navigation.Uri, forceLoad: true);
    }
```
(or for the individual items).

This indeed force-reloads, as can be observed in Chrome.

## 🔦 Context

I can see the `NavigationManager.NavigateTo(Href, ForceLoad);` in `FluentNavBase.cs`:129. I guess this is what should do the force load, but doesn't seem to be executed.

## 🌍 Your Environment

* OS & Device: macOS
* Browser: Chrome
* .NET and Fluent UI Blazor library Version: .NET 9 and FluentUI 4.11.0

**Comment by vnbaaij** [comment]
> I can see the `NavigationManager.NavigateTo(Href, ForceLoad);` in `FluentNavBase.cs`:129. I guess this is what should do the force load, but doesn't seem to be executed.

When there is no `OnClick` callback and an `Href` is set, the navigation will be done through the standard Blazor `NavLink` component. That component does not expose a parameter to do a forced reload. 
The code you mentioned in `FluentNavBase` will be executed if there is an `OnClick` callback, an `Href` specified and `ForceReload=true` has been set.

If you change the `NavMenu` code to below, you will see that clicking on the Home link will do a forced reload.:
```
<div class="navmenu">
    <input type="checkbox" title="Menu expand/collapse toggle" id="navmenu-toggle" class="navmenu-icon" />
    <label for="navmenu-toggle" class="navmenu-icon"><FluentIcon Value="@(new Icons.Regular.Size20.Navigation())" Color="Color.Fill" /></label>
    <nav class="sitenav" aria-labelledby="main-menu">
        <FluentNavMenu Id="main-menu" Collapsible="true" Width="250" Title="Navigation menu" @bind-Expanded="expanded" CustomToggle="true">
            <FluentNavLink OnClick="HandleMe" ForceLoad="true" Href="/" Match="NavLinkMatch.All" Icon="@(new Icons.Regular.Size20.Home())" IconColor="Color.Accent">Home</FluentNavLink>
            <FluentNavLink ForceLoad="true" Href="counter" Icon="@(new Icons.Regular.Size20.NumberSymbolSquare())" IconColor="Color.Accent">Counter</FluentNavLink>
            <FluentNavLink ForceLoad="true" Href="weather" Icon="@(new Icons.Regular.Size20.WeatherPartlyCloudyDay())" IconColor="Color.Accent">Weather</FluentNavLink>
        </FluentNavMenu>
    </nav>
</div>

@code {
    private bool expanded = true;

    private void HandleMe()
    {

    }
}
```

**Comment by frindler** [comment]
Thanks for this non-intuitive workaround. It’s not what it says in the docs, though. There, it says “If true, force browser to redirect outside component router-space.” I realise this may be a bit low priority, but I would not consider an empty OnClick handler that changes the behavior of an unrelated parameter to be a “fix”. Maybe it’s something that could be improved in the future?

**Comment by vnbaaij** [comment]
Yeah, it is not the best description. We need to revisit the code for a next version.

I did not mention "fix" anywhere in my reply, did I? I tried to explain that the parameters and event callback are not unrelated.
