### ISSUE TITLE
feat: ensure compatibility with Chromium 75

### ISSUE THREAD

**Issue by LuohuaRain** [microsoft/fluentui-blazor#3085]
# 🙋 Feature Request

## 🤔 Expected Behavior

Works fine with Chromium 75

## 😯 Current Behavior

![Image](https://github.com/user-attachments/assets/5ef539e9-73f5-441d-b132-71ca730df703)

## 💁 Possible Solution
To ensure compatibility with Chrome 75, I propose adjusting the build target from ES2022 to ES2019
https://github.com/microsoft/fluentui-blazor/blob/a677327448c679b9ba3411692185fa78969133bc/src/Core.Assets/esbuild.config.mjs#L1-L14

## 🔦 Context

I'm currently using FluentUI Blazor for older browsers, specifically Chromium 75. But now because it builds with ES2022, so doesn't work correctly.

**Comment by vnbaaij** [comment]
We only support the last couple of versions of current browsers.
Besides, v75 is like really (really) old, isn't it? We are now at 133

**Comment by LuohuaRain** [comment]
1. I noticed that the [fluent-ui webcomponent](https://github.com/microsoft/fluentui) repository appears to build its TypeScript target at ES2019 (or even lower). This suggests that maintaining a build that supports ES2019 can be feasible. 

https://github.com/microsoft/fluentui/blob/55c85d75a6b62659b137bf0a09fdcd7b7335dbe7/packages/web-components/tsconfig.json

2. Some platforms rely on embedding a WebView (for example, mini-program), and I have no way to upgrade underlying web-view component.

3. I also serve customers whose browsers are domain-controlled and cannot be updated to a more modern version of Chromium, so compatibility with ES2019 is crucial in those scenarios.

4. My request is not for you to "go back" to ES2019 in your source code. Rather, I’m asking whether a backward-compatible build (targeting ES2019) could be provided in addition to the current ES2022 build—similar to how .NET targets different standards while still allowing for modern features.

**Comment by vnbaaij** [comment]
1) I was talking about our own scripts, not the we components script

2) Wich platforms are you thinking about? We support Blazor Hybrid WebView

3) you were mentioning chromium 75. That is from 2019. A serious company should have upgraded a long time ago already.

4) we really do not have capacity to do these kind of backward compatible releases. It all needs to be tested, validated, built and distributed. With the SFI mantra we are in now, we can't just go create more build pipelines etc. Sorry, but we (have to) stick to to what we have.

If you really need/want such a version, I think you should clone and build your pen distribution.

**Comment by LuohuaRain** [comment]
Thank you for your explanation, @vnbaaij.

I I have gone through a lot of materials and also noticed that Blazor itself compiles its scripts using `ES2022` ([tsconfig](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Shared.JS/tsconfig.json)), so I understand why we shouldn't support old platforms.

Thanks again for your time and efforts!
