### ISSUE TITLE
Accordion ExpandedChanged Event Callback

### ISSUE THREAD

**Issue by grumpykiwi** [microsoft/fluentui-blazor#3086]
Hi

Is there a way to use the ExpandedChanged event to pass the ID or the accordion item context itself to the event handler so that I can detect which accordion to operate on, instead of having to use a different event handler for each accordion on the page?

Something like this:

```
protected async Task OnExpandedChanged(bool expanded, FluentAccordionItem item)
{
   if (expanded)
   {
      // go and get remote data for the fluent data grid inside the accordion item if it is empty
   }
}
```

Thanks

Mark

**Comment by vnbaaij** [comment]
Can't you use the `OnAccordionItemChange` event handler? See also https://fluentui-blazor.net/Accordion#accordiondefaultexam

**Comment by vnbaaij** [comment]
> What I have found is when I use the OnAccordionItemChange event, when I examine the item.Expanded property, it always seems to be false, even though I just clicked the down arrow on a non expanded accordion item

Yup, that is a bug! I see in the code which invokes `OnAccordionItemChange` that the `Expanded` state (part of the `AccordionChangeEventArgs`) is not being set on the item. I'm changing that for the next release:

![Image](https://github.com/user-attachments/assets/5ff7cd4c-d6bc-4365-99d8-e00545b2851d)
