### ISSUE TITLE
fix: unable to move the cursor with arrow keys in a FluentTextField

### ISSUE THREAD

**Issue by StefanJansson** [microsoft/fluentui-blazor#3087]
# 🐛 Bug Report

Difficulties navigating inside text field with left and right arrow keys

## 💻 Repro or Code Sample

https://www.fluentui-blazor.net/TextField, go to "Filled Appearance" section to have multiple textfields.

## 🤔 Expected Behavior

Enter text in first field, try to move the cursor with left/right arrow keys

## 😯 Current Behavior

When theres only one textfield, you can navigate with double tap the arrow keys
When there are multiple textfields, you can navigate left with double tap on the left arrow key, right arrow key always change focus to next control

## 🔦 Context

Text edit in forms often needs using the mouse or replacing whole text

## 🌍 Your Environment

Tested and verified on mac and windows, edge, chrome and safari

**Comment by vnbaaij** [comment]
Will be fixed in next release. Turned out to be an error in the DataGrid script. If you do not use a DataGrid on a page with text fields, you will not run into this error

**Comment by StefanJansson** [comment]
I asume that the Parameters section on the page is using DataGrid and therefore, the error occures on the TextField page?

**Comment by vnbaaij** [comment]
Yes, correct!

**Comment by StefanJansson** [comment]
Great work, love this package!
