### ISSUE TITLE
fix: FluentMenu not closing when FluentMenuItem is in a wrapper component

### ISSUE THREAD

**Issue by danny-may** [microsoft/fluentui-blazor#3088]
# 🐛 Bug Report

When the FluentMenuItems are declared in a different component to the FluentMenu they are within, clicking on them does not cause the fluent menu to close automatically. I believe this is because the [Task CloseAsync()](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Menu/FluentMenu.razor.cs#L239-L245) method does not call `StateHasChanged()`, unlike the [Task OpenAsync(int x, int y)](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Menu/FluentMenu.razor.cs#L254-L265) method.

Im not sure if this is intentional, but it would be useful if this worked as it allows the same menu items to be reused in different menus without duplicating the markup

## 💻 Repro or Code Sample

MyComponent.razor
```razor
<div id="ctx">
    Right-click on this text <br />
    to open a Context Menu.
</div>

<FluentMenu Anchor="ctx" Trigger="MouseButton.Right" Anchored="false">
    <MyReusableMenuAction />
</FluentMenu>
```

MyReusableMenuAction.razor
```razor
@using System.Diagnostics
<FluentMenuItem Label="Foo" OnClick="@((e) => Debug.WriteLine("Foo"))" />
```

## 🤔 Expected Behavior

The menu should close when a child menuitem is clicked regardless of how that item is added to the menu

## 😯 Current Behavior

The FluentMenu stays open until it rerenders and realises that `Open` is now `false`

## 💁 Possible Solution

Add a `StateHasChanged()` call [here](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Menu/FluentMenu.razor.cs#L244)

## 🔦 Context

I wanted to reuse some common FluentMenuItems in multiple places, so I created a component wrapping them. This means that the rerender which is triggered by clicking the action is limited to my wrapper component, and so the menu never gets rerendered

## 🌍 Your Environment

* OS & Device: Win11 on PC
* Browser Firefox & MAUI Blazor
* .NET and Fluent UI Blazor library Version 8.0.404 and 4.11.0

**Comment by dvoituron** [comment]
This is the development currently planned, as in general, items should be included in the **FluentMenu**.
You can inform your **FluentMenu** adding this attribute `OpenChanged="@(e => StateHasChanged())"`

```xml
<FluentMenu Anchor="ctx" Trigger="MouseButton.Right" OpenChanged="@(e => StateHasChanged())" Anchored="false">
    <MyReusableMenuAction />
</FluentMenu>
```

**Comment by danny-may** [comment]
Thats what I have done for now as a workaround, I just felt it was a bit of a strange development experience and inconsistent beaviour between opening and closing a menu

**Comment by dvoituron** [comment]
Your proposal will ask Blazor to redesign the menu anyway, since its content changes when `Open` becomes `False`. 

By design, we consider Items to be part of the **FluentMenu**. If you place them in another component, it's normal to inform the **FluentMenu** that its content must change when an **Item** is closed. This workaround does just that for you.

**Comment by danny-may** [comment]
I take your point about having the FluentMenuItems not being directly within the FluentMenu as an unsupported scenario. Is there a better way that I can reuse FluentMenuItems across multiple different context menus? In my use case, I have a list of items, and a pane to show the details of the selected item. I want a similar set of menu items to be available when right clicking one of the items in the menu and also when clicking a `...` button on the details pane.

![Image](https://github.com/user-attachments/assets/6a9755e8-d73c-4470-837c-ab840a0dd791)
![Image](https://github.com/user-attachments/assets/e5beee4e-0191-4914-8b63-705cf351bd95)


I am already using the workaround you proposed (or rather a similar concept), but it would be nice if there was a better way to approach this scenario in the first place if using a wrapper component is not the right approach.
