### ISSUE TITLE
FluentDataGrid: Combination of ResizableColumns="true" AutoFit="true" does not work

### ISSUE THREAD

**Issue by ProAra** [microsoft/fluentui-blazor#3089]
# 🐛 Bug Report
When creating a FluentDataGrid in Blazor, the combination of ResizableColumns="true" AutoFit="true" does not do the Auto fit of the columns. This in combination with @rendermode InteractiveServer and pagination, could perhaps be the issue here.

## 💻 Repro or Code Sample
See [Demo Page](http://obscure.proara.se/DemoAutoFit)
Source code [DemoAutoFit.txt](https://github.com/user-attachments/files/18229911/DemoAutoFit.txt)

Code is a variant from [Demo Fluent DataGrid](https://www.fluentui-blazor.net/DataGrid#autofit)

## 🤔 Expected Behavior
Expected behaviour should be that the data grid should auto size the columns width, so longest text would be as most visible as possible.

## 😯 Current Behavior

The columns are not adjusted in width, the columns with short text is wider than necessary. 
Also, at the same time, you should be able to adjust the width with the mouse, which u can, but initially the width are NOT adjusted to longest text.

## 💁 Possible Solution

Remove the ResizableColumns="true" attribute, and the width of columns are adjusted as expected.

## 🔦 Context

Creating a normal Blazor web page, showing all Visitors

## 🌍 Your Environment

* OS & Device:  Windows, Desktop
* Browser Chrome, Version 131.0.6778.205 (Official Build) (64-bit)
* Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.13.0 Preview 2.1
* .Net 9.0 Core
* Fluent UI Blazor library Version 4.11.0

**Comment by vnbaaij** [comment]
Will be fixed in next release with PR mentioned above
