### ISSUE TITLE
The type or namespace name 'Icons' could not be found after updating Icons to 4.11.0

### ISSUE THREAD

**Issue by JakobMadsen717** [microsoft/fluentui-blazor#3093]
I update NuGet package Microsoft.FluentUI.AspNetCore.Components.Icons from 4.10.4 to 4.11.0. After doing that, I now have to use fully qualified names for Icons in code, so for example:
        `<FluentIcon Value="@(new Microsoft.FluentUI.AspNetCore.Components.Icons.Regular.Size20.TextFont())" Color="Color.Accent" />`
instead of 
        `<FluentIcon Value="@(new Icons.Regular.Size20.TextFont())" Color="Color.Accent" />`

I perform _no other changes_ than updating the _Icon_ package and building project.
    `<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.11.0" />`
    `<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.11.0" />`

The error I get is: **The type or namespace name 'Icons' could not be found (are you missing a using directive or an assembly reference?)**

I have a line for Microsoft.FluentUI.AspNetCore.Components in my _Imports.razor, and that used to be enough to make it happy without me using fully qualified names.

I feel embarrassed in advance, it should be easy to fix, but hoping someone can just throw me a hint so I can close this.

**Comment by vnbaaij** [comment]
It is right here: https://www.fluentui-blazor.net/WhatsNew#icons-and-emoji...

**Comment by JakobMadsen717** [comment]
Great & thanks much. I will close this as fast as I can
