### ISSUE TITLE
fix:  Can't Access UserManager service Inside DialogService

### ISSUE THREAD

**Issue by abednejad** [microsoft/fluentui-blazor#3095]
# 🐛 Bug Report

hi
I created a Blazor Component Without using Fluent Component and inside that, injected UserManger and call some methods , after that I Create new razor page for use inside Fluent DialogService with same code before, but when I call UserManager Methods, it's failed and get error

## 💻 Repro or Code Sample
    public async Task<ApplicationUser?> getUser()
    {
        var u = await authenticationStateTask;

        var user = await UserManager.GetUserAsync(u.User);

        username = await UserManager.GetUserNameAsync(user);

        return user;
    }

Errors:

Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll
Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Cannot access a disposed object.
Object name: 'Microsoft.AspNetCore.Identity.UserManager`1[[BlazorApp1.Data.ApplicationUser, BlazorApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'.

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.AspNetCore.Identity.UserManager`1[[BlazorApp1.Data.ApplicationUser, BlazorApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'.
   at Microsoft.AspNetCore.Identity.UserManager`1.GetUserNameAsync(TUser user)
   at BlazorApp1.Components.Pages.TeamPages.EditTeamFluentDialog.getUser() in E:\Programs\OWN\Projects\HesabrasMali\WebApp\HesabrasMaliBlazorApp\BlazorApp1\Components\Pages\TeamPages\EditTeamFluentDialog.razor.cs:line 83
   at BlazorApp1.Components.Pages.TeamPages.EditTeamFluentDialog.OnInitializedAsync() in E:\Programs\OWN\Projects\HesabrasMali\WebApp\HesabrasMaliBlazorApp\BlazorApp1\Components\Pages\TeamPages\EditTeamFluentDialog.razor.cs:line 128
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'CqXppufBsoT96q4DJ2-movO06Pyh4ChtP4KrgobC9zE'.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.11.0]

**Comment by vnbaaij** [comment]
This is a general Blazor error you are running into. Please read the error message and go from there. You are probably not injecting the needed service into your component. 

Closing this as it does not seem to be a Fluent UI library related error.

**Comment by abednejad** [comment]
Hi

As I mentioned above, injected required services, and app run normally, just when I tried to load  the razor inside dialogsevice  it's getting error

**Comment by vnbaaij** [comment]
Are you injecting it into the component that you are using in the dialog service?

I closed this as you have not followed our issue template and have not supplied the details (library version, os, browser, etc.). See our standard reply below. 

I suggest you try again with a new issue. this time with one we can act upon and without the "it doesn't work, help!" attitude.

----------

Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.

We do **not** have capacity to craft or compose a reproduction for every issue that gets raised. 

If no code or repository is provided, this issue will be closed in **3** days

Help us to help you. Thanks.

**Comment by abednejad** [comment]
> Are you injecting it into the component that you are using in the dialog service?
> 
> I closed this as you have not followed our issue template and have not supplied the details (library version, os, browser, etc.). See our standard reply below.
> 
> I suggest you try again with a new issue. this time with one we can act upon and without the "it doesn't work, help!" attitude.
> 
> Please supply us with ready-to-run reproduction code in the form of something we can copy/paste, a (zipped) project structure or a GitHub repository.
> 
> We do **not** have capacity to craft or compose a reproduction for every issue that gets raised.
> 
> If no code or repository is provided, this issue will be closed in **3** days
> 
> Help us to help you. Thanks.

Yes , I injecting it into the component that you are using in the dialog service

**Comment by abednejad** [comment]
Hi 
I find a way to resolve the bug , but I don't understand why this happen

I just add a line 
         var us = _UserManager.Users.ToList();
befor calling  GetUserAsync method
and then it run correctly.



public async Task<ApplicationUser?> getUser()
{


    var u = await authenticationStateTask;
    var us = _UserManager.Users.ToList();


    var user = await _UserManager.GetUserAsync(u.User);

    username = await _UserManager.GetUserNameAsync(user);

    return user;
}
