### ISSUE TITLE
fix: OnRowFocus in DataGrid

### ISSUE THREAD

**Issue by artur-michalak** [microsoft/fluentui-blazor#3096]
# 🐛 Bug Report

When you press row, the click handler isn't executed.

## 💻 Repro or Code Sample

The issue can be observed on the [FluentUI documentation page](https://www.fluentui-blazor.net/DataGrid#customcomparer)

## 🔦 Context

I would like to redirect the user to the details page using NavigateTo.

## 😯 Current Behavior

Nothing is happening

## 🌍 Your Environment

* OS & Device: Windows 10 on PC
* Browser Google Chrome 131
* .NET and Fluent UI Blazor library Version 4.11.0

**Comment by vnbaaij** [comment]
Hi,

Have you tried with `OnRowClick`?

I see the `OnRowFocus` is not being invoked from the code anymore. This has to do with the change from web components to table rendering in 4.11. I'll see if we still need/want this as we have the row click now

**Comment by artur-michalak** [comment]
OnRowClick works well. How about adding this in breaking changes of 4.11?

**Comment by vnbaaij** [comment]
Yes, that is an oversight from our side...sorry about that.

As we now have the option to 'walk' through rows and cells with the arrow keys, we are probably going to bring back the events for the next release.

**Comment by artur-michalak** [comment]
No problem, thanks for the quick reply.
