### ISSUE TITLE
FluentNumberField Display and Edit format

### ISSUE THREAD

**Issue by christiantricarico** [microsoft/fluentui-blazor#3099]
Hello,
I'd like to format the value displayed in the FluentNumberField using the Italian culture using the comma (,) as decimal separator.
It seems that the component always uses the dot (.) as decimal separator.
What's the best way to achieve that?

![Image](https://github.com/user-attachments/assets/56850a58-8a22-4a0d-881a-acdd84a18db1)

**Comment by vnbaaij** [comment]
That is not possible with the current underlying web component.

This has been asked and answered before. Closing this. Duplicate

**Comment by christiantricarico** [comment]
Hi, I want to share my workaround for handling this issue.

Created a custom FluentDecimalField component that works as a wrapper for the existing FluentTextField with a decimal binding property _DecimalValue_ that will be exposed to the parent.

FluentDecimalField has a private _StringValue_ property that depends on _DecimalValue_ and stores converted strings to display in the original component based on the current culture or specific needs (logic coded in UIUtils.ConvertTextToDecimal(value)) .

![Image](https://github.com/user-attachments/assets/07e802f4-18ad-41f6-864c-7ea652403515)

And in the parent you can bind the component to a decimal property:

![Image](https://github.com/user-attachments/assets/29dfdce3-f9f7-4b23-af83-cf63ce29e400)

This is the result I got for Italian culture where a comma is used as a decimal separator:

![Image](https://github.com/user-attachments/assets/41b266c3-d551-40bc-9ca8-e6fdc3739e82)
