### ISSUE TITLE
fix: Render in Tooltip

### ISSUE THREAD

**Issue by wisamidris77** [microsoft/fluentui-blazor#3100]
A problem appeared using fluent tooltip it does not renders tooltip content every render just once it created

# 🐛 Bug Report

So for example when going to Counter.razor and changes the tooltip content to be the currentCount so a problem would appear

## 💻 Repro or Code Sample

Counter.razor
```razor
@page "/counter"
@rendermode InteractiveServer

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<div role="status" style="padding-bottom: 1em;">
	Current count: <FluentBadge Appearance="Appearance.Neutral">@currentCount</FluentBadge>
</div>


<FluentButton Id="mytooltipCounterButton" Appearance="Appearance.Accent" @onclick="IncrementCount">Click me</FluentButton>
<FluentTooltip Anchor="mytooltipCounterButton" Position="TooltipPosition.Bottom" Delay=200>
	Current count:@currentCount
</FluentTooltip>

@code {
	private int currentCount = 0;

	private void IncrementCount()
	{
		currentCount++;
	}
}
```

MainLayout.razor
```razor
@* Some code *@
<FluentTooltipProvider @rendermode="InteractiveServer" />
```

## 🤔 Expected Behavior

It should update the update the counter value inside the tooltip

## 😯 Current Behavior

The counter stays in 0 instead of 4

![Image](https://github.com/user-attachments/assets/8dc24c7a-f0e6-4977-a862-502d8ce054a4)

## 💁 Possible Solution

I really don't know

## 🔦 Context

I'm using tooltip as value for some places in my app and these values change overtime

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by wisamidris77** [comment]
If you want project as zip

[BlazorApp10.zip](https://github.com/user-attachments/files/18247158/BlazorApp10.zip)

**Comment by dvoituron** [comment]
Probably caused by the rendering not refreshed for this tooltip, because the HTML code is generated in the `TooltipProvider`, outside of the Counter component. 

Can you try to add a `key` attribute to force Blazor to re-render this component each time the counter is updated?

```xml
<FluentTooltip @key="@Counter" Anchor=...
```

**Comment by wisamidris77** [comment]
Okay but the problem
This is a simple example but mine is a html elements changing with many values

And @key would recreate and dispose the tooltip over again and again
I thought of making Guid for the key but this would be very impacting for my app performance because it have over 40 tooltip per page

**Comment by wisamidris77** [comment]
If this is the only solution
It's okay but I hope it get fixed
