### ISSUE TITLE
fix: The selection is one off in the Calendar component on the demo site

### ISSUE THREAD

**Issue by PeterSoder** [microsoft/fluentui-blazor#318]
When selecting a date in the Calendar component on the demo site it says the day after is selected.
ie. click Feb 14 and it writes out that I selected Feb 15.

If it's in anyway related I'm in a region that have yy-mm-dd format (Sweden).

**Comment by vnbaaij** [comment]
This is fixed in the latest version of the web-components script. To make sure you are using this version change the `<script>` reference in `index.html` or `_Host.cshtml` to read:
```
 <script type="module" src="https://cdn.jsdelivr.net/npm/@fluentui/web-components@2.5.13/dist/web-components.min.js"></script>
```
