### ISSUE TITLE
fix: custom events registeration in MAUI blazorwebview

### ISSUE THREAD

**Issue by zh4ui** [microsoft/fluentui-blazor#327]
# 🐛 Bug Report

I'd like to report that the Javascript initializer `src\Microsoft.Fast.Components.FluentUI\wwwroot\Microsoft.Fast.Components.FluentUI.lib.module.js` does not work on MAUI blazorwebview due to problems reported in this [issue](https://github.com/dotnet/maui/issues/7965#issuecomment-1164635637).

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
The linked issue is closed and as I understand it, it works on a number of platforms. Are you seeing specific errors when using this library in a MAUI app?

**Comment by vnbaaij** [comment]
Ok, so we are blocked until these are solved. Nothing we can do here, I mean. I added the 'Blocked' label

**Comment by lkd3063601** [comment]
I have the same problem

**Comment by vnbaaij** [comment]
Closing this as we now have a workaround fr this. See https://github.com/microsoft/fluentui-blazor#tempory-workaround-for-maui-issues for the details.
