### ISSUE TITLE
docs: fix Incomplete documentation

### ISSUE THREAD

**Issue by pekspro** [microsoft/fluentui-blazor#367]
Just some quick feedback after spending some time to get started with this. I’m a beginner 😊

I have looked on three integrations guides:

https://www.fast.design/docs/integrations/blazor
https://github.com/microsoft/fluentui-blazor
https://brave-cliff-0c0c93310.azurestaticapps.net/

The first one doesn’t say anything about `<link href="{PROJECT_NAME}.styles.css" rel="stylesheet" />` nor Reboot. That’s confusing. The last two are the same, I think.

Also, it is a bit unclear what to do with `<link href="{PROJECT_NAME}.styles.css" rel="stylesheet" />`. Should I add this file to my project? Should PROJECT_NAME be replaced? Can some other name be used?

Eventually, I found that there were project templates I could use:
https://brave-cliff-0c0c93310.azurestaticapps.net/Templates 
This should be mentioned in the quick start guides, I think.

I created a new project from the template and then started to I tested some components with code for the documentation at https://brave-cliff-0c0c93310.azurestaticapps.net/. Some of these didn’t work out of the box.
 
## Card
I tried the sample code of the card component here https://brave-cliff-0c0c93310.azurestaticapps.net/Card, but some of these cards had a reference to an undefined context variable: `<FluentCard BackReference="@context">`. I removed these cards and tried to other ones. It looked like this:

![image](https://user-images.githubusercontent.com/3163293/230842524-89f29059-8cd6-4d0d-97df-a3c81c436ba6.png)
 
Doesn’t look right. I got similar issues with the Skeleton component: https://brave-cliff-0c0c93310.azurestaticapps.net/Skeleton

## Emoji
When trying the emoji component: https://brave-cliff-0c0c93310.azurestaticapps.net/Emoji my application failed to load in the browser. I found this error message in the browser tools:

    fail: Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
          System.Exception: Emoji assest are not available
             at Microsoft.Fast.Components.FluentUI.FluentEmoji.OnParametersSet() in /_/src/Microsoft.Fast.Components.FluentUI/Components/Emoji/FluentEmoji.cs:line 86
             at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
             at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

## Icon
Next, I tried the first sample if the Icon sample: https://brave-cliff-0c0c93310.azurestaticapps.net/Icon. This page also failed to load properly; I got this in the browser tools:

    blazor.webassembly.js:1         
           fail: Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
          System.ArgumentException: The requested icon (ArrowCircleLeft, Size20, Regular) is not available in the collection
             at Microsoft.Fast.Components.FluentUI.FluentIcon.OnParametersSet() in /_/src/Microsoft.Fast.Components.FluentUI/Components/Icon/FluentIcon.cs:line 92
             at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
             at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

## PercentBadge
This page fails to load:

https://brave-cliff-0c0c93310.azurestaticapps.net/Lab/PresenceBadge

**Comment by vnbaaij** [comment]
Hi @pekspro,

Welcome to the club!

>The first one doesn’t say anything about <link href="{PROJECT_NAME}.styles.css" rel="stylesheet" /> nor Reboot. That’s >confusing. The last two are the same, I think.

A PR to align the docs on the different sites has been submitted a couple of days ago. In general, GitHub and demo will be most up-to-date.

>Also, it is a bit unclear what to do with <link href="{PROJECT_NAME}.styles.css" rel="stylesheet" />. Should I add this file to my >project? Should PROJECT_NAME be replaced? Can some other name be used?

Yes, {PRODUCT_NAME} should be replaced. Say you have solution 'ABC' with project ABC.Client, then put ABC.Client in as a replacement. Notation like this to indicate you need to replace something is fairly common.

>Eventually, I found that there were project templates I could use:...This should be mentioned in the quick start guides, I think.
Yes, you are right. Will fix that.

Card
I think you got an unreferenced error because you're missing a using statement for `Microsoft.Fast.Components.FluentUI.DesingTokens` but hard to be sue without seeing any code.

Emoji/Icon
You are missing the required configuration in your project file and configuration settings in your `Program.cs`. See the 'V2.1' section of this page: https://brave-cliff-0c0c93310.azurestaticapps.net/WhatsNew 
It's not clear enough you need to do this so we will work on that too.

PresenceBadge
Good find. We can't publish all icons to the demo environment. Will change this to use an available one.

Thanks for your comments. Good to have a fresh pair of eyes going over the docs. For us it tends to get so familiar that we assume certain things to be clear and understandable. And you know what they say about assumptions...

**Comment by pekspro** [comment]
Thanks for a very quick response @vnbaaij :-) I was able to get the icons working after following your instructions. But cards are still an issue. I created a new Fluent UI Blazor WebApplication, and replaced the code in `Index.razor` with this:

``` razor
@using Microsoft.Fast.Components.FluentUI
@using Microsoft.Fast.Components.FluentUI.DesignTokens

@page "/"

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

<div>
    <BaseLayerLuminance Value="(float?)0.15">
        <FluentCard BackReference="@context">
            <div class="contents">
                <p>Dark</p>
                <FluentButton Appearance="Appearance.Accent">Accent</FluentButton>
            </div>
        </FluentCard>
    </BaseLayerLuminance>

    <FluentCard card-fill-color="#449544">
        <div class="contents">
            <p>Custom card-fill-color</p>
            <FluentButton Appearance="Appearance.Accent">Accent</FluentButton>
            <FluentButton Appearance="Appearance.Stealth">Stealth</FluentButton>
            <FluentButton Appearance="Appearance.Outline">Outline</FluentButton>
            <FluentButton Appearance="Appearance.Lightweight">Lightweight</FluentButton>
            <p>
                Note the stealth buttons have a slight fill, which is because the card-fill-color is explicit, but the stealth
                recipe gets its value from the neutral palette which has been created based on the card-fill-color, but does not
                contain that exact color.
            </p>
        </div>
    </FluentCard>
</div>
```

Now it compiles, but when I run it I get this error message in the browser:

```
Failed to resolve module specifier '' TypeError: Failed to resolve module specifier '' at https://localhost:7247/_framework/blazor.webassembly.js:1:716 at https://localhost:7247/_framework/blazor.webassembly.js:1:3332 at new Promise (<anonymous>) at Object.beginInvokeJSFromDotNet (https://localhost:7247/_framework/blazor.webassembly.js:1:3306) at Object.St [as invokeJSFromDotNet] (https://localhost:7247/_framework/blazor.webassembly.js:1:59960) at _mono_wasm_invoke_js_blazor (https://localhost:7247/_framework/dotnet.6.0.15.ncdybormud.js:1:195300) at https://localhost:7247/_framework/dotnet.wasm:wasm-function[219]:0x1a4c1 at https://localhost:7247/_framework/dotnet.wasm:wasm-function[167]:0xce8f at https://localhost:7247/_framework/dotnet.wasm:wasm-function[166]:0xbd73 at https://localhost:7247/_framework/dotnet.wasm:wasm-function[2815]:0xabef3
```

If I remove the `BaseLayerLuminance` it will load, but margins etc doesn't look right.

I will try to keep my eyes fresh :-)

**Comment by vnbaaij** [comment]
Do you have the web components script referenced somewhere? (index.html in webassembly / _host.cshtml in server app):
`<script type="module" src="https://cdn.jsdelivr.net/npm/@fluentui/web-components/dist/web-components.min.js"></script>`

**Comment by pekspro** [comment]
Thanks again, @vnbaaij. Adding the `@inject` made the code finally run:

``` razor
@using Microsoft.Fast.Components.FluentUI
@using Microsoft.Fast.Components.FluentUI.DesignTokens
@inject BaseLayerLuminance BaseLayerLuminance

@page "/"

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

<div>
    <BaseLayerLuminance Value="(float?)0.15">
        <FluentCard BackReference="@context">
            <div class="contents">
                <p>Dark</p>
                <FluentButton Appearance="Appearance.Accent">Accent</FluentButton>
            </div>
        </FluentCard>
    </BaseLayerLuminance>

    <FluentDesignSystemProvider FillColor="#D6D6D6">
        <FluentCard neutral-palette-source="#CABA8C">
            <div class="contents">
                <p>Tinted neutral-palette-source, dark container</p>
                <FluentButton Appearance="Appearance.Accent">Accent</FluentButton>
                <FluentButton Appearance="Appearance.Stealth">Stealth</FluentButton>
                <FluentButton Appearance="Appearance.Outline">Outline</FluentButton>
                <FluentButton Appearance="Appearance.Lightweight">Lightweight</FluentButton>
            </div>
        </FluentCard>
    </FluentDesignSystemProvider>
</div>
``` 

It looks like this:

![image](https://user-images.githubusercontent.com/3163293/230899597-3177eb03-3022-44f6-9800-60499c95e84e.png)

Which is quite different compared to the documentation:

![image](https://user-images.githubusercontent.com/3163293/230900026-817a0c31-6cb3-4894-bda8-b1c66bdf2031.png)

![image](https://user-images.githubusercontent.com/3163293/230900064-83b15a8a-3698-43cd-b923-80a3ad04e176.png)

I've looked a bit at design tokens, but I am a bit confused. If there are no default margins for cards for instance, how do you configure this once for the entire project?

**Comment by vnbaaij** [comment]
For the card we just added some styling to the default site css:
```
::deep fluent-card {
    --card-height: 400px;
    --card-width: 500px;
    padding: 20px;
    margin: 12px;
}
::deep > .contents {
    display: flex;
    flex-direction: column;
}
```
See the css tab for option 2 on the demosite homepage

**Comment by pekspro** [comment]
Thanks, @vnbaaij, now it looks better :-)

**Comment by vnbaaij** [comment]
Closing this. Changes and additions have been made to the readme.
