### ISSUE TITLE
fix: Performance issue in FluentIcon

### ISSUE THREAD

**Issue by ThatGuyMike7** [microsoft/fluentui-blazor#370]
# 🐛 Bug Report

Multiple FluentIcons in a FluentDataGrid lead to very slow repaint (250ms and higher).

The repro contains two pages that are identical, except one page has a FluentButton with a FluentIcon in each data grid row (performance issue) and the other page has a FluentButton with text in each data grid row (ok).

The delete buttons in the repro toggle the visibility of a loading indicator so the performance issue is visible directly.

## 💻 Repro or Code Sample

[Click me](https://github.com/ThatGuyMike7/fluentui-blazor-icon-performance-issue)

## 🤔 Expected Behavior

When clicking the delete button, a repaint is triggered which should not take more than a few ms.

## 😯 Current Behavior

When clicking the delete button, a repaint is triggered that can take more than 250ms.

## 🔦 Context

I added a delete button to each data grid row (with a delete icon).

## 🌍 Your Environment

Windows 11
Visual Studio 2022
Microsoft Edge
.NET 7.0
ASP.NET Core Components WASM 7.0.3 (see project file)
FluentUI Blazor 2.1.1 (see project file)

**Comment by vnbaaij** [comment]
Further investigation has revealed that the delay lies (very) deep in the wasm bowels (apparently in function 221):
![image](https://user-images.githubusercontent.com/1761079/233081259-8a0ee44d-e071-4015-a2bf-e5db670552a8.png)
![image](https://user-images.githubusercontent.com/1761079/233081299-511bdd5f-30a7-4d4b-873a-860e7309da46.png)

If anyone has knowledge that can help here that would be much appreciated. Until then this will stay like it is, I guess.
