### ISSUE TITLE
fix: PresenceBadge and MonacoEditor has errors on https://aka.ms/fluentui-blazor

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#371]
# 🐛 Bug Report

`PresenceBadge` and `MonacoEditor` has errors on https://aka.ms/fluentui-blazor

https://brave-cliff-0c0c93310.azurestaticapps.net/Lab/PresenceBadge

> An error has occurred. The requested icon (Person, Size32, Regular) is not available in the collection

![image](https://user-images.githubusercontent.com/4015237/232159647-bb118c47-1160-4a3e-98a1-04e4334a41c7.png)

Trigger `MonacoEditor` editor error by first visiting `Table of Contents` and then click on `MonacoEditor`.

https://brave-cliff-0c0c93310.azurestaticapps.net/Lab/TableOfContents

https://brave-cliff-0c0c93310.azurestaticapps.net/Lab/MonacoEditor

An unhandled error has occurred. 

![image](https://user-images.githubusercontent.com/4015237/232159898-4bc80fe3-7df0-4db1-8b45-d1525105c339.png)

**Comment by vnbaaij** [comment]
The error is actually caused by the ToC component, but anyways fixes are pushed now.
