### ISSUE TITLE
fix: Assets are not loaded when the library is used via an intermediate Razor component library

### ISSUE THREAD

**Issue by patrickjahr** [microsoft/fluentui-blazor#372]
# 🐛 Bug Report

If I use the UI library in a Razor component library, the necessary data such as CacheStorageAccessor.js is not loaded. This leads to the fact that the application, which uses the library, cannot be executed correctly. As an example I have created a small application that demonstrates my problem.

## 💻 Repro or Code Sample

Sample Code: [GitHub](https://github.com/patrickjahr/blazor-fast-ui-issue-sample)

## 🤔 Expected Behavior

I would expect that the components in the library can be used in the same way as if they can be used directly in a Blazor app. (Icons, Emojis, etc.)

## 😯 Current Behavior

![failed_loading](https://user-images.githubusercontent.com/16818441/232756136-6a88ff0d-f63f-44ad-9249-b230d48d65bc.png)

## 💁 Possible Solution

Please let us know if you'd be willing to contribute the fix; we'd be happy to work with you

## 🌍 Your Environment

* OS & Device: Windows
* Browser e.g. Microsoft Edge, Google Chrome
* .NET and FAST Version
* * .NET: 7.0.5
* * FAST: 2.1.4

**Comment by vnbaaij** [comment]
Hi, 

Sorry, but that is not something I foresee to be fixed. The components and library depend on settings (like the ones you have in your `FastUi.Sample.Components.csproj` file) to be present the referencing application and project. 

The package is not and will not be transitive.

**Comment by patrickjahr** [comment]
> Hi, 
> 
> 
> 
> Sorry, but that is not something I foresee to be fixed. The components and library depend on settings (like the ones you have in your `FastUi.Sample.Components.csproj` file) to be present the referencing application and project. 
> 
> 
> 
> The package is not and will not be transitive.  

Ok! Thanks for the quick feedback. Do you have a tip how I could use it via an own component library?

**Comment by vnbaaij** [comment]
Why not just install it in both project (ie your library and consuming project)?

**Comment by patrickjahr** [comment]
The idea was to provide a library with components that take over the styling and behavior of fast ui but have additional logic. So that it can be used in several projects at the same time without installing more than one package.

**Comment by vnbaaij** [comment]
I see. Understood but I don't think there are a lot of component libraries that would make this scenario possible.
