### ISSUE TITLE
fix: compile error in FluentTreeItem when trying to specify 'stopPropagation'

### ISSUE THREAD

**Issue by StevenRasmussen** [microsoft/fluentui-blazor#375]
Hello, when I try to specify `onclick:stopPropagation` and I have already defined an `onclick` handler, I receive the following compile error:

> The component parameter 'onclick' is used two or more times for this component. Parameters must be unique (case-insensitive). The component parameter 'onclick' is generated by the 'onclick:stopPropagation' directive attribute.

The code I'm using is:
```razor
<FluentTreeItem @onclick="OnNavigationItemClick" @onclick:stopPropagation="true">
</FluentTreeItem>

@code{
    private Task OnNavigationItemClick(MouseEventArgs args) { ... }
}
```

I'm new to using this behavior and so I'm not sure if I'm doing something wrong, but I tested this just using a `div` and didn't receive this error.

I'm using v2.2.0-preview.2 of the package.

**Comment by vnbaaij** [comment]
The `@onclick:stopPropagation` only woks on HTML DOM elements. See also https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-7.0#stop-event-propagation
