### ISSUE TITLE
fix: FluentTooltip not being displayed for disabled FluentButtons when using Chrome browser

### ISSUE THREAD

**Issue by emilkvarnhammar** [microsoft/fluentui-blazor#376]
# 🐛 Bug Report

FluentTooltip text is not shown in Chrome when a FluentButton is Disabled. It is shown in Firefox.

## 💻 Repro or Code Sample

```
<div style="height:100px; display: flex; gap: 10px; margin: 2em; flex-direction: row; align-items: center; justify-content: center;">
    <FluentButton id="DisabledButton" Disabled=true Appearance=Appearance.Accent>Disabled Button</FluentButton>
    <FluentTooltip Anchor="DisabledButton" Position=TooltipPosition.Top>Tooltip for disabled button!</FluentTooltip>

    <FluentButton id="EnabledButton" Appearance=Appearance.Accent>Enabled Button</FluentButton>
    <FluentTooltip Anchor="EnabledButton" Position=TooltipPosition.Top>Tooltip for enabled button!</FluentTooltip>
</div>

```

## 🤔 Expected Behavior

Tooltip should be shown regardless if a control is Disabled or not, and the behavior should be consistent in all supported browsers. For usability purposes, It's useful to point out (through the tooltip) why the FluentButton is disabled.

## 😯 Current Behavior

Using Chrome: Tooltip is displayed when hovering over the EnabledButton in the code sample, but it's not displayed when hovering over the DisabledButton
Using Firefox: Tooltip is displayed for both buttons in the code sample

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Firefox 112.0.2 (64-bit), Chrome Version 112.0.5615.138 (Official Build) (64-bit)
* .NET 7.0, Microsoft.Fast.Components.FluentUI 2.2.0

**Comment by vnbaaij** [comment]
This behavior comes directly from the Fluent UI Web Components. I do not have a real preference on it working as you describe but I'll raise the issue in the FAST repo to see what they think. If they change the behavior, it will flow to here as well.

**Comment by vnbaaij** [comment]
Closing this as it seems this is a browser specific anomaly. There is nothing done in the web-components that would trigger this behavior.
