### ISSUE TITLE
DropDown component missing? 

### ISSUE THREAD

**Issue by tomkuijsten** [microsoft/fluentui-blazor#379]
Am I missing something or is the DropDown controle not ported yet?

**Comment by vnbaaij** [comment]
We're not porting anything. We have wrappers for the Fluent UI Web Components. In vNext we will offer new components as well.

I think for the current version you are looking for the [FluentSelect](https://www.fluentui-blazor.net/Select) component

**Comment by tomkuijsten** [comment]
Ah thanks! I did look at the select of course, but what I was missing is a multi select DropDown, can't me mimiced by the select I guess? The multi select in the examples will show the full list instead of a DropDown, or am I missing a setting?

**Comment by vnbaaij** [comment]
No, you are correct there. Multiselect is only possible with a listbox

**Comment by tomkuijsten** [comment]
I wanted to add a "select columns" DropDown in a tool ar above a datagrid. Any controle which can mimic this behaviour, or should a write a rapper aroudn the official DropDown component?

**Comment by vnbaaij** [comment]
At the moment we don't have any component for that, no. What do you mean with 'official'? The React component?

**Comment by vnbaaij** [comment]
Closing this as no further action needs to be taken
