### ISSUE TITLE
fix: "Number Field" page in Demo site

### ISSUE THREAD

**Issue by StevenRasmussen** [microsoft/fluentui-blazor#383]
# 🐛 Bug Report

The "Number Field" page is not working on the demo site.

## 💻 Repro or Code Sample

See here: [https://brave-cliff-0c0c93310.azurestaticapps.net/NumberField](https://brave-cliff-0c0c93310.azurestaticapps.net/NumberField)

![image](https://user-images.githubusercontent.com/11198735/235689970-47f6cb21-2141-4012-ac90-356236f2b145.png)

## 🤔 Expected Behavior

Demo should work

## 😯 Current Behavior

Demo page is not working

**Comment by vnbaaij** [comment]
Working on it!

p.s brave-cliff... will not be updated anymore soon. Use https://www.fluentui-blazor.net from now on.
