### ISSUE TITLE
fix: Icon isn't showing with WindowsAuthentication in FluentIcon

### ISSUE THREAD

**Issue by LittleHnata** [microsoft/fluentui-blazor#384]
# 🐛 Bug Report

Fluent Icon is not showing with WindowsAuthentication enabled

## 💻 Repro or Code Sample

Enable on IISExpress WindowsAuthentication and it should be enough to reproduce it.

## 🤔 Expected Behavior

It should work 🙂

## 😯 Current Behavior

HttpClient is giving error 401 Unauthorized if using Blazor Server
See screenshots below
![image](https://user-images.githubusercontent.com/10107575/235861902-3c545763-0fcd-4f8e-8bd7-eccce9c1e376.png)
![image](https://user-images.githubusercontent.com/10107575/235862143-4d7dbe64-0f89-4031-b54f-15f8e1dffd93.png)
![image](https://user-images.githubusercontent.com/10107575/235861267-bd36db05-4a36-4d24-8c3a-19a0e2a8c630.png)

## 💁 Possible Solution

if is WindowsAuthentication enabled  -> HttpClient to use DefaultCredentials if its possible

## 🔦 Context

NavMenu in not showing any icons

## 🌍 Your Environment

* OS & Device:  Windows 11 on PC
* Browser Google Chrome
* .NET 7.0.5  and FAST Version 2.2.1

**Comment by LittleHnata** [comment]
I tried to upgrade it to version 3.0.0.preview3, but behavior is the same.

**Comment by vnbaaij** [comment]
Yes, that was too be expected. We haven't done anything with it yet.

Happy to take a PR, if you know how to solve it...

**Comment by V-AATARE** [comment]
I also facing similar issue that Icons are not loading, but getting different error in stacktrace :
<img width="668" alt="image" src="https://user-images.githubusercontent.com/120010112/236795918-d6bc2542-5277-4c50-a7f2-23909c4c8a9c.png">
Is there any solution for this? Now no Icons are visible..

**Comment by vnbaaij** [comment]
@V-AATARE What are your settings in the project file wrt the icons?
