### ISSUE TITLE
Microsoft.Fast.Components.FluentUI 3.0.0-preview.3 FluentDataGrid shows no rows

### ISSUE THREAD

**Issue by ernestasjuska** [microsoft/fluentui-blazor#385]
Hello,

I am trying out new components in _Microsoft.Fast.Components.FluentUI 3.0.0-preview.3_ and noticed that _FluentDataGrid_ does not show any rows.

Before updating (_Microsoft.Fast.Components.FluentUI 2.1.4_):
![image](https://user-images.githubusercontent.com/53167314/236623852-a11b59cc-a0fe-4909-99ed-6ab794d6d465.png)

After updating (_Microsoft.Fast.Components.FluentUI 3.0.0-preview.3_):
![image](https://user-images.githubusercontent.com/53167314/236623877-1f86f78a-819f-4ee3-8a52-478805f3917f.png)

Thanks.

---

Code for repro:
_Index.razor_:
```razor
<FluentDataGrid Id="general" RowsData=myItems GridTemplateColumns="1fr" TGridItem=MyItem>
    <PropertyColumn Property=@(c => c!.Description) />
</FluentDataGrid>

@code {
    public record MyItem(string Description);
    private IQueryable<MyItem> myItems = new MyItem[]
    {
        new("First"),
        new("Second"),
    }.AsQueryable();
}
```

**Comment by vnbaaij** [comment]
Parameter names have changed for v3.see http://baaijte.net/blog/microsoft-fluentui-blazor-3.0/

**Comment by osmanm786** [comment]
It's not rowsdata in the preview. Review it here https://brave-cliff-0c0c93310-365.centralus.azurestaticapps.net/DataGrid

**Comment by ernestasjuska** [comment]
I see. I didn't notice that RowData is now red instead of blue.

Thanks.
