### ISSUE TITLE
fix: Clearing number in NumberField and NumberFieldOnInput does not reset the bind value

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#394]
# 🐛 Bug Report

Write 1234 for NumberField, select the entire number and then press backspace. The bind value will still be present even if the number is removed. 

https://www.fluentui-blazor.net/NumberField

## 🤔 Expected Behavior

I expect the number to be 0 or null based on data type. 

## 🌍 Your Environment

OS & Device:: Windows 11 Pro on PC
Browser: Chrome Version 113.0.5672.64 (Official Build) (64-bit)
.NET 7 and Microsoft.Fast.Components.FluentUI V2.3.0.

**Comment by vnbaaij** [comment]
Fixed in #395

**Comment by Ogglas** [comment]
@vnbaaij This should be opened again. It only works for `FluentNumberField` with `oninput` now. 

This wont currently work for example:

`<FluentNumberField @bind-Value="exampleInt">Integer</FluentNumberField>`

Looking at https://www.fluentui-blazor.net/NumberField - I can run the examples but when I click on Razor I see the old values. Using empty cache and hard reload does not load correct values either. In order to do that I have to use Clear site data in Chrome Developer tools. Is there anyway to avoid this?

**Comment by vnbaaij** [comment]
Generating the txt file sometimes lags a bit behind. If you do a rebuild solution a new one should get generated. The 'Clear cache' page just empties what is in the browsers Cache storage.
Before:
<img width="387" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/88d2929f-f12a-4210-9491-3b11c987ced8">

After:
<img width="245" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/bc08151c-ed32-4761-b0b4-dfb9292ff4f8">

If the right txt dile is present on the server, it should be downloaded and displayed on the page after a refresh

**Comment by Ogglas** [comment]
In this case it seemed to be browser cache. When looking at a normal tab i saw the old values but when I tried incognito I got the new values. When I then used empty cache and hard reload in my normal tab I still saw the old values. It was not until I used Clear site data in Chrome Developer tools that I got the new values in a non incognito tab.

**Comment by vnbaaij** [comment]
Hmm, maybe we need to add a no-cache header then to the txt files so they don't get cached by the browser. I'll make a note of that

**Comment by Ogglas** [comment]
Sounds good!

**Comment by vnbaaij** [comment]
Hi Oscar,

Are you still planning on submitting a PR for this? (pretty please...)

**Comment by Ogglas** [comment]
Thanks for the clarification but I still think this can cause some unexpected values for users. Created a PR to clarify the difference in examples: https://github.com/microsoft/fluentui-blazor/pull/433
