### ISSUE TITLE
fix: Unable to GET FluentIcon in Blazor Server

### ISSUE THREAD

**Issue by pk9r327** [microsoft/fluentui-blazor#399]
# 🐛 Bug Report

The code below are supplying the factory with a single instance of HttpClientHandler to use in all clients. Once the default HandlerLifetime has elapsed (2 minutes) it will be marked for disposal, with the actual disposal occurring after all existing HttpClients referencing it are disposed.

```C#
// Microsoft.Fast.Components.FluentUI/Extensions/ServiceCollectionExtensions.cs

HttpClientHandler? handler = GetHandler();
if (string.IsNullOrEmpty(configuration.StaticAssetServiceConfiguration.BaseAddress))
{
    services.AddHttpClient<IStaticAssetService, HttpBasedStaticAssetService>()
        .ConfigurePrimaryHttpMessageHandler(() =>
        {
            return handler;
        });
}
else
{
    services.AddHttpClient<IStaticAssetService, HttpBasedStaticAssetService>(c =>
    {
        c.BaseAddress = new Uri(configuration.StaticAssetServiceConfiguration.BaseAddress);
    }).ConfigurePrimaryHttpMessageHandler(() =>
        {
            return handler;
        });
    }
}
```

All clients created after the handler is marked continue to be supplied the soon-to-be disposed handler, leaving them in an invalid state once the disposal is actioned.

https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#httpclient-lifetimes

## 🤔 Expected Behavior

The factory should be configured to create a new handler for each client

## 😯 Current Behavior

After disposed handler, new access to the website (without cache) throw an 'System.ObjectDisposedException' with Object name: 'System.Net.Http.SocketsHttpHandler'.
![image](https://github.com/microsoft/fluentui-blazor/assets/72692627/f81e7238-9bd0-4e54-9e7e-0085b596cfec)

## 💁 Possible Solution

AddHttpClient code for Blazor server should be modified like this
```C#
if (string.IsNullOrEmpty(configuration.StaticAssetServiceConfiguration.BaseAddress))
{
    services.AddHttpClient<IStaticAssetService, HttpBasedStaticAssetService>()
        .ConfigurePrimaryHttpMessageHandler(GetHandler);
}
else
{
    services.AddHttpClient<IStaticAssetService, HttpBasedStaticAssetService>(c =>
    {
        c.BaseAddress = new Uri(configuration.StaticAssetServiceConfiguration.BaseAddress);
    }).ConfigurePrimaryHttpMessageHandler(GetHandler);
}
```

### Remarks
> The configureHandler delegate should return a new instance of the message handler each time it is invoked.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.configureprimaryhttpmessagehandler?view=dotnet-plat-ext-6.0

## 🔦 Context

After throwing System.ObjectDisposedException, SignalR will be disconnected and the client cannot continue to interact with the server

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Microsoft Edge
* .NET 7.0.5 and FAST Version 2.3.0

**Comment by vnbaaij** [comment]
Good catch. Was about to ask you to create an issue for this on Discord :).

Will change the behavior like you mentioned.
