### ISSUE TITLE
fix: fluentui combobox in blazor still showing value, not text

### ISSUE THREAD

**Issue by scanhamman** [microsoft/fluentui-blazor#402]
Hi
This seems to be the same as issue #328 , which is reported as fixed but as far as I can see is not.
(May also be related to issue #24937?)
As the demo page still shows, (at https://www.fluentui-blazor.net/Combobox) selecting an option when using a list ot Option<T> items still displays the value, at least initially. Users would expect to see the text. Second and successive selections of the same option display the text, as expected. Change the option and the value re-appears.
N.B. The URL in #328 that refers to an updated demo now gives a 404.
It would be good to have the option of using Option<T>
Or is there a workaround / configuration that I am missing?
Cheers

**Comment by vnbaaij** [comment]
Can you take a look at https://calm-sea-053fa6a03-403.westeurope.3.azurestaticapps.net/ and verify if it is now working as expected? Thanks.

**Comment by scanhamman** [comment]
Hi
Thanks for coming back to me so quickly.
Yes - the version on the link you sent works exactly as would be expected.
I also saw that there is an updated Nuget package (2.3.1). I installed that (on both server and client, in an API hosted Blazor app) but that still shows the same problem as before. An item marked as selected ('2' in the example code) displays correctly on initial load (i.e., as 'Two') but selecting any option shows the value. Repeated selection of the same option shows the text, but not the first selection of an option, which always shows the value.
Is a further Nuget upgrade planned? Or is a more up to date download available somewhere??
Cheers
Steve

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by vnbaaij** [comment]
The thing you have verified to work correctly will be in version 2.3.2 then. I'll try to do a release later today or tomorrow.

There is no newer version available at the moment than 2.3.1. There are 3.0 preview versions available, but this fix is not available in there yet either.

**Comment by scanhamman** [comment]
Hi
Ok, I will keep a lookout for the update. Thanks for the quick feedback – much appreciated.
Cheers
Steve

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
