### ISSUE TITLE
fix: Incomplete GetIconConfiguration() is generated if PublishFluentEmojiAssets is set to false

### ISSUE THREAD

**Issue by andreisaperski** [microsoft/fluentui-blazor#405]
# 🐛 Bug Report

ConfigurationGenerator (src/Microsoft.Fast.Components.FluentUI.Configuration/ConfigurationGenerator.cs) adds code to populate Sizes and Variants only when PublishFluentEmojiAssets is set to true:

ln 161:             if (options.PublishEmojiAssets) 

it needs to be changed to:

             if (options.PublishIconAssets)

## 💻 Repro or Code Sample
Set property group as follow:

	<PropertyGroup>
		<PublishFluentIconAssets>true</PublishFluentIconAssets>
		<FluentIconSizes>10,16,20,24,48</FluentIconSizes>
		<FluentIconVariants>Filled,Regular</FluentIconVariants>
		<PublishFluentEmojiAssets>false</PublishFluentEmojiAssets>
	</PropertyGroup>

## 🤔 Expected Behavior

Generated GetIconConfiguration() looks like:

	public static IconConfiguration GetIconConfiguration()
	{
		IconConfiguration config = new(true);
		config.Sizes = new[] {
			IconSize.Size10,
			IconSize.Size16,
			IconSize.Size20,
			IconSize.Size24,
			IconSize.Size48
		};
		config.Variants = new[] {
			IconVariant.Filled,
			IconVariant.Regular
		};
		return config;
	}

## 😯 Current Behavior

Generated GetIconConfiguration() looks like:

	public static IconConfiguration GetIconConfiguration()
	{
		IconConfiguration config = new(true);
		return config;
	}

## 💁 Possible Solution

Change line 161 in src/Microsoft.Fast.Components.FluentUI.Configuration/ConfigurationGenerator.cs from
             if (options.PublishEmojiAssets) 

to:

             if (options.PublishIconAssets)

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Oops! Will be fixed in 2.3.3 (released later today).
