### ISSUE TITLE
fix: [new-components] 'id' attribute isn't rendered for some components.

### ISSUE THREAD

**Issue by andreisaperski** [microsoft/fluentui-blazor#408]
# 🐛 Bug Report

FluentComponentBase got Id parameter and needs to be rendered explicitly now. In version 2.x.x Id was captured by AdditionalAttributes and rendered with @attributes="AdditionalAttributes".
Many components don't render Id: FluentAccordion, FluentAccordionItem, FluentAnchor, etc. These affects cases when JS interop relies on 'id' e.g. Tabs - Dynamic example - overflow badge doen't show menu on click 'cause FluentBadge doens't render id and anchored menu cannot subscribe to badge's clieck event using id.

Btw, Tabs demo page isn't working at the moment because of missing icons - size 12:

The requested icon (Dismiss, Size12, Regular) is not available in the collection.

## 🤔 Expected Behavior

id attribute rendered for components that inherit FluentComponentBase

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
> FluentComponentBase got Id parameter and needs to be rendered explicitly now. In version 2.x.x Id was captured by AdditionalAttributes and rendered with @attributes="AdditionalAttributes". Many components don't render Id: FluentAccordion, FluentAccordionItem, FluentAnchor, etc. These affects cases when JS interop relies on 'id' e.g. Tabs - Dynamic example - overflow badge doen't show menu on click 'cause FluentBadge doens't render id and anchored menu cannot subscribe to badge's clieck event using id.

Id needs to be rendered explicitly indeed. That is a deliberate choice we made so we don't put Id's into the HTML everywhere (even when they are not being used). We made it a nullable property in `FluentComponentBase` so it won't get rendered if it is null. Where needed, we changed the constructor for components so a value will be set for the Id. For example:
```csharp
public FluentAccordionItem()
{
      Id = Identifier.NewId();
}
```
And you HTML looks like this: 
<img width="358" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/b04be438-0117-4f0a-8f72-e2e2801fedf3">

Apparently, we forgot to do this for the example/components you mentioned. I added the Id to the `FluentBadge` and that seems to do the trick:
<img width="357" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/efe9b823-6bf0-4be6-8009-d15534c46bab">


> Btw, Tabs demo page isn't working at the moment because of missing icons - size 12:
> 
> The requested icon (Dismiss, Size12, Regular) is not available in the collection.

See, I told you we would need extra required icon settings in project file sooner or later 😁. I added one for size 12 (with this icon) to the project file.

**Comment by andreisaperski** [comment]
Hi Vencent,
Thank you for a quick response)
It just feels that Id parameter sets an expectation that if it's set, it will rendered in HTML element. If it's rendered only for a subset of components, this creates confusion and may limit options for composite controls creation

**Comment by vnbaaij** [comment]
Maybe we can add it to every web component rendering? By default, it is null and won't be outputed. We will add it in constructor for components where needed. If you need/want to create a value for it yourself, that could be done in `OnParameterSet` or `OnInitialized`. Would that work? @dvoituron any thoughts?

**Comment by andreisaperski** [comment]
If Id is assigned in constructor, it can also be overridden in .razor. Tabs-Dynamic example and DemoSection.razor set id for FluentTab-s, replacing value assigned FluentTab's constructor.
The issue is more how to have it rendered consistently across all components, rather than how to assign it. Seems like the only option is to add id="@Id" to the components where it's missing)

**Comment by vnbaaij** [comment]
Hi @andreisaperski are you clear on how we intended it to work? Can this be closed?

**Comment by andreisaperski** [comment]
yeah, it can be closed
