### ISSUE TITLE
fix: FluentTreeView Clicking becomes unstable when generated from a data collection

### ISSUE THREAD

**Issue by scabrera** [microsoft/fluentui-blazor#410]
# 🐛 Bug Report

Every time a click is made, the component is regenerated and there comes a time when it becomes unstable.
This happens when we try to generate the TreeViewItem from a collection, that is, it is created at runtime.

## 💻 Repro or Code Sample

https://github.com/scabrera/FastFluentTreeViewBug.git

## 🤔 Expected Behavior

The expected is that we can load the Treeview from a data collection

**Comment by scabrera** [comment]
s

**Comment by vnbaaij** [comment]
Your sample works perfectly fine **IF** you make sure all `KeyCategories` have a unique ID. 

In your current code for example, both 'Xamarin' and 'MGC' have an Id of '3'. This causes the code to start selecting both items in turn when one of them is selected.
