### ISSUE TITLE
fix: Rows parameter in Text area does not work

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#417]
# 🐛 Bug Report

I can not set FluentTextArea Rows property and therefore can't control vertical height. 

Looking at the code the following constructed stylesheet seems to be the culprit: Without this code it works as expected:

```
.control {
    height: calc(((var(--base-height-multiplier) + var(--density)) * var(--design-unit) * 2) * 1px);
```

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/65818c70-32ff-4283-b584-f5561c4b3d17)

## 💻 Repro or Code Sample

```
<FluentTextArea @bind-Value=value1 Rows=10 style="width: 100%;"></FluentTextArea>

@code {
    string? value1;
}
```

**Comment by vnbaaij** [comment]
Hi Oscar,
This is a known bug (#72) and has been reported to the FAST team. Will raise it there again but needs to be fixed by them

**Comment by Ogglas** [comment]
Hello Vincent,
Thank you, I missed that old issue! Any known workaround? Since it affects the html textarea it is hard to get around.

**Comment by c0g1t8** [comment]
@Ogglas 

I encountered the same issue. My workaround was _revert_ the _height_ setting in css.

```css
::deep > fluent-text-area::part(control) {
    height: revert;
}
```
I hope this works for you.
