### ISSUE TITLE
fix: I can not use arrow keys in FluentTextArea inside a FluentDataGrid

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#418]
# 🐛 Bug Report

I can not use arrow keys in FluentTextArea inside a FluentDataGrid. It works perfectly outside a FluentDataGrid

## 💻 Repro or Code Sample

```
<FluentDataGrid RowsData="@people">
    <TemplateColumn Title="TextArea">
        <FluentTextArea @bind-Value=value1></FluentTextArea>
    </TemplateColumn>
</FluentDataGrid>

@code {
    string value1;

    record Person(int PersonId, string Name, DateOnly BirthDate);

    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
    }.AsQueryable();
}
```

**Comment by vnbaaij** [comment]
Hi, this one has already been raised to the FAST team: https://github.com/microsoft/fast/issues/6500

**Comment by Ogglas** [comment]
I hope it will be fixed soon then! Did you get a change to look at the sort of related https://github.com/microsoft/fluentui-blazor/issues/217?

**Comment by vnbaaij** [comment]
Will be fixed with next release. Please verify it works here: https://calm-sea-053fa6a03-421.westeurope.3.azurestaticapps.net/DataGrid#template-columns-2

**Comment by Ogglas** [comment]
@vnbaaij Nice! However it only seems to be partially fixed. Using a virtualized data grid it still does not work. Example:

```
<FluentDataGrid RowsData="@people" Virtualize="true" RowsDataSize="100">
    <TemplateColumn Title="TextArea">
        <FluentTextArea @bind-Value=value1></FluentTextArea>
    </TemplateColumn>
</FluentDataGrid>

@code {
    string value1;

    record Person(int PersonId, string Name, DateOnly BirthDate);

    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
    }.AsQueryable();
}
```

**Comment by vnbaaij** [comment]
Yes, confirmed it does not work with a virtualized grid. No idea how to fix that though...

**Comment by Ogglas** [comment]
Thanks anyway! Created a new issue to track the bug: https://github.com/microsoft/fluentui-blazor/issues/435

Can FAST solve it on their side?

**Comment by vnbaaij** [comment]
A fix had just been submitted for this: https://github.com/microsoft/fast/pull/6754. We have to get it in the right branch and pushed to the Fluent script and then test it, so might still take some time.
