### ISSUE TITLE
Demo site not working on iPhone

### ISSUE THREAD

**Issue by c0g1t8** [microsoft/fluentui-blazor#422]
# 🐛 Bug Report

The demo site was working on my iPhone and iPad. It currently hangs on a partially completed loading screen.

 Version: 2.3.5+eec7b584c2d7e01944aca69bae95d666fd016349 - Powered by .NET 8.0.0-preview.4.23259.5

## 💻 Repro or Code Sample

Using Safari or Chrome go to [www.fluentui-blazor.net.](https://www.fluentui-blazor.net/)

## 🤔 Expected Behavior

Demo site should work.

## 😯 Current Behavior

Site is stuck on loading screen

## 💁 Possible Solution

Did notice that the demo site is now on _Version: 2.3.5+eec7b584c2d7e01944aca69bae95d666fd016349  -  Powered by .NET 8.0.0-preview.4.23259.5_

Possible solution revert back to last stable .NET 7 version.

## 🔦 Context

Working on a new site using this package where my target application is a PWA running primarily on phones and tablets. Discovered issue as part of my CI/CD process.

## 🌍 Your Environment

* iPhoneX iOS16.5
* iPad (6th gen) iPadOS 16.5 
* Windows 11Pro (used for development and works here)

**Comment by vnbaaij** [comment]
Sorry, but I don't have any Apple device to test on. Do you have any errors displayed/see anything in Developer Toools?

Pretty sure though it is not a .NET 8 issue.

**Comment by c0g1t8** [comment]
I'll see what I can find. The site worked a couple of weeks ago on my iPhone and iPad.

**Comment by c0g1t8** [comment]
@vnbaaij 

I just retested Version: 2.3.5+45e364942a017a1345ea7174a8730faf0980c8c5  -  Powered by .NET 8.0.0-preview.4.23259.5

iPhoneX - still hangs in both Safari and Chrome
iPad - still hangs in both Safari and Chrome
Mac - hangs in Safari
Mac - works in Chrome

There appears to be some sort of timing issue. Sometimes a partial render starts before hanging. You can scroll but no links are active.

For example, I show 100% loaded with only 50% of the loading ring filled. They are out of sync. I would expect the numeric value to match the graphic.

**Comment by vnbaaij** [comment]
It might be related to #424. I'm going to implement a fix for that in a bit. Will let you know here and on Discord so you can test again.

**Comment by c0g1t8** [comment]
@vnbaaij 

Thanks. I can confirm that the following resolved my issue - 
_Version: 2.3.5+9d21e4c1952932dd8e65b0b0f73d0fcb3bddb28c  -  Powered by .NET 8.0.0-preview.4.23259.5_
