### ISSUE TITLE
fix: [Demo apps] Infinite rendering loop in TableOfContents

### ISSUE THREAD

**Issue by andreisaperski** [microsoft/fluentui-blazor#424]
# 🐛 Bug Report

OnAfterRenderAsync (in [TableOfContents.razor.cs](https://github.com/microsoft/fluentui-blazor/blob/45e364942a017a1345ea7174a8730faf0980c8c5/examples/FluentUI.Demo.Shared/Components/TableOfContents.razor.cs)) calls QueryDom() which in its turn loads anchors and calls StateHasChanged() - rendering starts again.

## 💻 Repro or Code Sample

FluentUI.Demo.Client/FluentUI.Demo.Server in examples.
Browser's tab with https://www.fluentui-blazor.net/ consumes ~20% of CPU on my PC even if there's no any interaction (clicks/scroll)

## 🤔 Expected Behavior

Re-rendering doesn't happen all the time

## 😯 Current Behavior

TableOfContents keeps re-rendering without any reason.

## 💁 Possible Solution

Looks like QueryDom() should call StateHasChanged() only if anchors have changed e.g.:

```csharp
    private async Task QueryDom()
    {
        var foundAnchors = await _jsModule.InvokeAsync<Anchor[]?>("queryDomForTocEntries");

        if (AnchorsEqual(_anchors, foundAnchors))
        {
            return;
        }

        _anchors = foundAnchors;
        StateHasChanged();
    }

    private bool AnchorsEqual(Anchor[]? firstSet, Anchor[]? secondSet)
    {
        return (firstSet ?? Array.Empty<Anchor>())
            .SequenceEqual(secondSet ?? Array.Empty<Anchor>());
    }
```
Anchor record needs Equal implemented because of child anchors:

```csharp
        public virtual bool Equals(Anchor? other)
        {
            if (other is null) return false;

            if (Level != other.Level ||
                Text != other.Text ||
                Href != other.Href ||
                (Anchors?.Length ?? 0) != (other.Anchors?.Length ?? 0))
            {
                return false;
            }

            if (Anchors is not null &&
                Anchors.Length > 0)
            {
                for (var i = 0; i < Anchors.Length; i++)
                {
                    if (!Anchors[i].Equals(other.Anchors![i]))
                    {
                        return false;
                    }
                }
            }

            return true;
        }
```

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
@andreisaperski locally your solution works on Server but not on Client. Have you tested on Client? Is it working for you there?

**Comment by vnbaaij** [comment]
Yes, I see that it works in a sense that it is nor running continuously. But it is also not showing the actual table of contents after reading the markdown file. And that is what we want it to do.

**Comment by andreisaperski** [comment]
Could you please point me to a page where it doesn't work. i checked markdown-based pages What's new?/Project setup/Code setup/Design tokens  and ToC there matched with pages' structure.  Also check that these pages raise OnRefreshTableOfContents, DemoMainLayout handles it and calls TableOfContents.Refresh() which in its turn calls QueryDom() 

![image](https://github.com/microsoft/fluentui-blazor/assets/30940385/2ea970ca-5aac-471c-b9de-87303381ba5a)

**Comment by vnbaaij** [comment]
For me it goes wrong on every page that loads Markdown to display contents, ie DesignTokens and CodeSetup
