### ISSUE TITLE
fix: I can not use arrow keys in FluentTextArea inside a virtualized FluentDataGrid

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#435]
# 🐛 Bug Report

 I can not use arrow keys in FluentTextArea inside a virtualized FluentDataGrid. Original issue: https://github.com/microsoft/fluentui-blazor/issues/418. Probably related: https://github.com/microsoft/fast/issues/6500

## 💻 Repro or Code Sample

```
<FluentDataGrid RowsData="@people" Virtualize="true" RowsDataSize="100">
    <TemplateColumn Title="TextArea">
        <FluentTextArea @bind-Value=value1></FluentTextArea>
    </TemplateColumn>
</FluentDataGrid>

@code {
    string value1;

    record Person(int PersonId, string Name, DateOnly BirthDate);

    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
    }.AsQueryable();
}
```

**Comment by vnbaaij** [comment]
A fix had just been submitted for this: https://github.com/microsoft/fast/pull/6754. We have to get it in the right branch and pushed to the Fluent script and then test it, so might still take some time.

**Comment by vnbaaij** [comment]
Closing this as it will not be solved in FAST (due to changed policy)
