### ISSUE TITLE
fix: https://www.fluentui-blazor.net/ is down

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#443]
# 🐛 Bug Report

https://www.fluentui-blazor.net/ is down. 

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/2bdd77f2-cff0-461a-862f-ebdbffcad5c7)

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/6157c72e-4b90-4e07-a5d8-f5c7904a17e5)

**Comment by vnbaaij** [comment]
Yes 😔 Subscription issue. Working on it.

**Comment by LuohuaRain** [comment]
it's okay now

**Comment by vnbaaij** [comment]
It works for now, but operations are underway to move everything to a new subscription. Hiccups are to be expected...

**Comment by vnbaaij** [comment]
Ok, everything is moved over. Service should be as normal
