### ISSUE TITLE
fix: The first animation effect of the active tab indicator is not correct in FluentTab

### ISSUE THREAD

**Issue by LuohuaRain** [microsoft/fluentui-blazor#444]
The first animation effect may have an overflow effect and the position may not be displayed correctly.
# 🐛 Bug Report

## 💻 Repro or Code Sample
```razor
<h4>Horizontal</h4>
<FluentTabs>
    <div slot="start">
        <FluentButton>1</FluentButton>
        <FluentButton>2</FluentButton>
        <FluentButton>3</FluentButton>
    </div>
    <div slot="end">
        <FluentButton>1</FluentButton>
        <FluentButton>2</FluentButton>
        <FluentButton>3</FluentButton>
    </div>
    <FluentTab>Tab one</FluentTab>
    <FluentTab>Tab two</FluentTab>
    <FluentTab>Tab three</FluentTab>
    <FluentTabPanel>
        Tab one content. This is for testing.
    </FluentTabPanel>
    <FluentTabPanel>
        Tab two content. This is for testing.
    </FluentTabPanel>
    <FluentTabPanel>
        Tab three content. This is for testing.
    </FluentTabPanel>
</FluentTabs>

<h4>Vertical</h4>
<FluentTabs Orientation="Orientation.Vertical">
    <div slot="start">
        <FluentButton>1</FluentButton>
        <FluentButton>2</FluentButton>
        <FluentButton>3</FluentButton>
    </div>
    <div slot="end">
        <FluentButton>1</FluentButton>
        <FluentButton>2</FluentButton>
        <FluentButton>3</FluentButton>
    </div>
    <FluentTab>Tab one</FluentTab>
    <FluentTab>Tab two</FluentTab>
    <FluentTab>Tab three</FluentTab>
    <FluentTabPanel>
        Tab one content. This is for testing.
    </FluentTabPanel>
    <FluentTabPanel>
        Tab two content. This is for testing.
    </FluentTabPanel>
    <FluentTabPanel>
        Tab three content. This is for testing.
    </FluentTabPanel>
</FluentTabs>

```

## 😯 Current Behavior

https://github.com/microsoft/fluentui-blazor/assets/37979368/539b0d3c-e3f1-4f8a-99bb-6f7636022aa8

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Microsoft Edge 114.0.1823.37
* .NET and FAST Version : latest demo site

**Comment by vnbaaij** [comment]
This is an issue in the underlying web component. You can see it happen here: https://fluent-components.azurewebsites.net/?path=/docs/components-tabs--tabs and then clear out the activeId and then click on a tab.
As the team is changing this in web-components V3 and it is only a minor graphical glitch, I'm guessing it will not get fixed anytime soon. Therefore closing it here.

**Comment by LuohuaRain** [comment]
Thanks @vnbaaij  I get it. 

I just offer `activeId` for `FluentTabs` and an id for `FluentTab` then fixed! 🚀

**Comment by vnbaaij** [comment]
Ok, so we should just make sure to always add activeId in the component. I'll add that to the list
