### ISSUE TITLE
fix: Icons not showed in dockercontainer + reverse proxy in FluentIcon

### ISSUE THREAD

**Issue by damianog** [microsoft/fluentui-blazor#446]
# 🐛 Bug Report

I do not know why but FluentIcon does not show nothing. For example the FluentPaginator show only empty buttons.

In local environment and local desktop docker container all run fine.

## 💻 Repro or Code Sample

I deployed the application in my develop environment; that means docker engine + traefik reverse proxy + regular ssl certificate. The application use Authentication and Authorization services.

The content slot is empty and the svg is missing.
![image](https://github.com/microsoft/fluentui-blazor/assets/2786682/d3a024ad-b33f-40f9-9775-df72c8798c18)

Instead in local environment both are present

![image](https://github.com/microsoft/fluentui-blazor/assets/2786682/aa4c33a4-7ef7-424d-9a5f-403875b4f97a)

but Docker container logs show that icons are retrieved without error

![image](https://github.com/microsoft/fluentui-blazor/assets/2786682/04cad653-a53b-4ee8-a1be-d5f52e815a3b)

and by the url I could get the icon.

![image](https://github.com/microsoft/fluentui-blazor/assets/2786682/52ebc629-783f-40cb-b64c-fdf6851249fb)

## 🤔 Expected Behavior

Icons should be showed

![image](https://github.com/microsoft/fluentui-blazor/assets/2786682/e157213e-425e-415d-afc3-1bfdbf7ceef8)

## 😯 Current Behavior

Icons are blank

![image](https://github.com/microsoft/fluentui-blazor/assets/2786682/c9d924e8-efab-456e-bb6f-14f2139d9d9c)

## 💁 Possible Solution
I have no idea. 

## 🌍 Your Environment

Docker engine provied by VMware PhotonOS 5
Traefik 2.10.1 as Reverse proxy
Regular SSL wildcard certificate

**Comment by vnbaaij** [comment]
Maybe you need change the `<base>` tag in you `index.html` (Blazor WASM) or `_layout. cshtml` (Blazor Server)

**Comment by damianog** [comment]
Hi @vnbaaij,

the base tag is OK

![image](https://github.com/microsoft/fluentui-blazor/assets/2786682/ae3a81e7-94f7-4476-baca-472e0f6f4dc2)

Opened the console of the running container and look into wwwroot; all icons are published

![image](https://github.com/microsoft/fluentui-blazor/assets/2786682/8ce005a7-ea8d-41ab-9ca0-2d281e983dc5)

Could it be the roundtrip from the app that make the https request to the proxied alias back to http?

For some reasons the webcomponent itself is missing to add the svg part, but I am still investigating
