### ISSUE TITLE
fix: JS and CSS cache issues in V2.3.0 and above

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#459]
# 🐛 Bug Report

Since JS and CSS files were included in the library we have had cache issues in production with new versions. Primarily CSS but it could also be JS related.

https://www.fluentui-blazor.net/WhatsNew#v2.3.0

For every other library imported we use `asp-append-version="true"` which prevents cache errors. Since JS and CSS are included we can not do that for `Microsoft.Fast.Components.FluentUI`.  Tested that  `asp-append-version="true"` works with both `Blazor Server` and `Blazor WebAssembly`. In the case of `Blazor WebAssembly` I got it to work in a ASP.NET Core Hosted project.

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/6229bf60-6eac-466f-b6ec-f1493a28bf83)

![image](https://github.com/microsoft/fluentui-blazor/assets/4015237/faa065b8-d76e-4155-8143-bd97784f1121)

Affected files:

Microsoft.Fast.Components.FluentUI.lib.module.js
Microsoft.Fast.Components.FluentUI.bundle.scp.css
web-components.min.js

## 💁 Possible Solution

Use `asp-append-version="true"` or similar to appen hash. 

If this is not possible then add the possibility for a user to include CSS and JS files themselves without them being automatically loaded. This is not the preferred solution though.

**Comment by Ogglas** [comment]
I hope https://github.com/dotnet/aspnetcore/issues/31922 will be included in .NET 8 then. :) Perhaps we only noticed the CSS cache bugs after 2.3.0 then but they have been there all the time.

**Comment by vnbaaij** [comment]
I'm closing this as it is not actionable from our side.

**Comment by Ogglas** [comment]
@vnbaaij Can we keep it open to track the bug? I would rather see it open and blocked to show that the bug is present but can not be fixed now. It will also show as an open bug to the aspnetcore team if it remains open.

**Comment by vnbaaij** [comment]
Although this will probably not solve all the problems with caching, we've added a version indicator to the included web components javascript file link in version 2.4.2
