### ISSUE TITLE
feat: add Virtualize to Listbox

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#460]
# 🙋 Feature Request

Virtualization works really well for Data grid with large data sets. Given that Listbox can sometimes contain large data sets I think it would be really good here as well. This could also mean that Search with debounce would only be needed for API calls. 

https://www.fluentui-blazor.net/Search#interactive-with-debounce

Could be an alternative for this fix:

https://github.com/microsoft/fluentui-blazor/issues/389

**Comment by vnbaaij** [comment]
Unfortunately, we cannot interject into the rendering of the listbox as that is done by the web component.

**Comment by Ogglas** [comment]
Created a new issue https://github.com/microsoft/fast/issues/6814 and we will see how it goes
