### ISSUE TITLE
fix: ConfigurationGenerator is not generated in FluentUI

### ISSUE THREAD

**Issue by nimrof** [microsoft/fluentui-blazor#462]
This might very well be a user error, but i have failed to find out what i am doing wrong

# 🐛 Bug Report

ConfigurationGenerator is not generated
Program.cs(13,35): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context

## 💻 Repro or Code Sample

Using this docker image and template to make sure nothing else in setup is making problems.
```
FROM ubuntu:22.04
RUN apt-get update && \
    apt-get -y dist-upgrade && \
    DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install dotnet-sdk-6.0 dotnet-runtime-6.0 ca-certificates

WORKDIR /build
RUN dotnet new --install Microsoft.Fast.Templates.FluentUI::2.0.6
RUN dotnet new fluentuiblazorserver
```

- Change Program.cs to use ConfigurationGenerator

```
builder.Services.AddHttpClient();

//builder.Services.AddFluentUIComponents();
//When using icons and/or emoji replace the line above with the code below
LibraryConfiguration config = new(ConfigurationGenerator.GetIconConfiguration(), ConfigurationGenerator.GetEmojiConfiguration());
builder.Services.AddFluentUIComponents(config);

builder.Services.AddSingleton<WeatherForecastService>();
```

- Change build.csproj to only use .net 6.0 (did not get the -f to work ) and changed the propertygroup to

```
<PropertyGroup>
	<PublishFluentIconAssets>true</PublishFluentIconAssets>
	<FluentIconSizes>10,12,16,20,24,28,32,48</FluentIconSizes>
	<FluentIconVariants>Filled,Regular</FluentIconVariants>
	<PublishFluentEmojiAssets>true</PublishFluentEmojiAssets>
	<FluentEmojiGroups>Activities,Animals_Nature,Flags,Food_Drink,Objects,People_Body,Smileys_Emotion,Symbols,Travel_Places</FluentEmojiGroups>
	<FluentEmojiStyles>Color,Flat,HighContrast</FluentEmojiStyles>
</PropertyGroup>
```

Then
dotnet build

```

root@2e3b8cfeb6bb:/build# dotnet build
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : warning CS8032: An instance of analyzer Microsoft.Fast.Components.FluentUI.Generators.ConfigurationGenerator cannot be created from /root/.nuget/packages/microsoft.fast.components.fluentui/2.3.6/analyzers/dotnet/cs/Microsoft.Fast.Components.FluentUI.Configuration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/build/build.csproj]
/build/Program.cs(13,35): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]
/build/Program.cs(13,82): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]

Build FAILED.

CSC : warning CS8032: An instance of analyzer Microsoft.Fast.Components.FluentUI.Generators.ConfigurationGenerator cannot be created from /root/.nuget/packages/microsoft.fast.components.fluentui/2.3.6/analyzers/dotnet/cs/Microsoft.Fast.Components.FluentUI.Configuration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/build/build.csproj]
/build/Program.cs(13,35): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]
/build/Program.cs(13,82): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]
    1 Warning(s)
    2 Error(s)
```

## 🤔 Expected Behavior

Build without warning/error

## 😯 Current Behavior

```
CSC : warning CS8032: An instance of analyzer Microsoft.Fast.Components.FluentUI.Generators.ConfigurationGenerator cannot be created from /root/.nuget/packages/microsoft.fast.components.fluentui/2.3.6/analyzers/dotnet/cs/Microsoft.Fast.Components.FluentUI.Configuration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/build/build.csproj]
/build/Program.cs(13,35): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]
/build/Program.cs(13,82): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]
```

## 💁 Possible Solution

`CSC : warning CS8032: An instance of analyzer Microsoft.Fast.Components.FluentUI.Generators.ConfigurationGenerator cannot be created from /root/.nuget/packages/microsoft.fast.components.fluentui/2.3.6/analyzers/dotnet/cs/Microsoft.Fast.Components.FluentUI.Configuration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/build/build.csproj]`

Guessing i am missing something, but my attempts to fix it has failed

## 🔦 Context

Unable to use FluentNavMenu as it needs the icons (different setup, but same problem)

## 🌍 Your Environment

Ubuntu 22.04 (see 'Repro or Code Sample') for dockerfile

**Comment by vnbaaij** [comment]
Maybe try with adding this package to your project: 'Microsoft.CodeAnalysis, Version=4.5.0.0'

**Comment by nimrof** [comment]
> Maybe try with adding this package to your project: 'Microsoft.CodeAnalysis, Version=4.5.0.0'

Thanks for the tip, but it still failed

```
root@2e3b8cfeb6bb:/build# dotnet add package Microsoft.CodeAnalysis --version 4.5.0
  Determining projects to restore...
  Writing /tmp/tmpVUzkWw.tmp
info : Adding PackageReference for package 'Microsoft.CodeAnalysis' into project '/build/build.csproj'.
info : Restoring packages for /build/build.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.fast.components.fluentui/index.json
info : Package 'Microsoft.CodeAnalysis' is compatible with all the specified frameworks in project '/build/build.csproj'.
info : PackageReference for package 'Microsoft.CodeAnalysis' version '4.5.0' added to file '/build/build.csproj'.
info : Committing restore...
info : Assets file has not changed. Skipping assets file writing. Path: /build/obj/project.assets.json
log  : Restored /build/build.csproj (in 258 ms).

root@2e3b8cfeb6bb:/build# dotnet build
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : warning CS8032: An instance of analyzer Microsoft.Fast.Components.FluentUI.Generators.ConfigurationGenerator cannot be created from /root/.nuget/packages/microsoft.fast.components.fluentui/2.3.6/analyzers/dotnet/cs/Microsoft.Fast.Components.FluentUI.Configuration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/build/build.csproj]
/build/Program.cs(14,35): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]
/build/Program.cs(14,82): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]

Build FAILED.

CSC : warning CS8032: An instance of analyzer Microsoft.Fast.Components.FluentUI.Generators.ConfigurationGenerator cannot be created from /root/.nuget/packages/microsoft.fast.components.fluentui/2.3.6/analyzers/dotnet/cs/Microsoft.Fast.Components.FluentUI.Configuration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/build/build.csproj]
/build/Program.cs(14,35): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]
/build/Program.cs(14,82): error CS0103: The name 'ConfigurationGenerator' does not exist in the current context [/build/build.csproj]
    1 Warning(s)
    2 Error(s)
```

https://www.nuget.org/packages/Microsoft.CodeAnalysis/4.5.0#dependencies-body-tab

**Comment by vnbaaij** [comment]
What exactly is in your build/build.csproj?

**Comment by nimrof** [comment]
> What exactly is in your build/build.csproj?

```
<Project Sdk="Microsoft.NET.Sdk.Web">

        <PropertyGroup>
                <TargetFrameworks>net6.0</TargetFrameworks>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
                <IsPackable>true</IsPackable>
        </PropertyGroup>

        <PropertyGroup>
                <PublishFluentIconAssets>true</PublishFluentIconAssets>
                <FluentIconSizes>10,12,16,20,24,28,32,48</FluentIconSizes>
                <FluentIconVariants>Filled,Regular</FluentIconVariants>
                <PublishFluentEmojiAssets>true</PublishFluentEmojiAssets>
                <FluentEmojiGroups>Activities,Animals_Nature,Flags,Food_Drink,Objects,People_Body,Smileys_Emotion,Symbols,Travel_Places</FluentEmojiGroups>
                <FluentEmojiStyles>Color,Flat,HighContrast</FluentEmojiStyles>
        </PropertyGroup>

        <ItemGroup>
                <PackageReference Include="Microsoft.CodeAnalysis" Version="4.5.0" />
                <PackageReference Include="Microsoft.Fast.Components.FluentUI" Version="2.3.*" />
        </ItemGroup>

</Project>
```

**Comment by vnbaaij** [comment]
Try removing the 'IsPackable'

**Comment by nimrof** [comment]
> Try removing the 'IsPackable'. Otherwise I don't see anything strange.

Same problem.



Switched to .net 7.0 and then it gives a different warning, but same errors
`CSC : warning CS9057: The analyzer assembly '/root/.nuget/packages/microsoft.fast.components.fluentui/2.3.6/analyzers/dotnet/cs/Microsoft.Fast.Components.FluentUI.Configuration.dll' references version '4.5.0.0' of the compiler, which is newer than the currently running version '4.4.0.0'. [/build/build.csproj::TargetFramework=net6.0]`


You know of a unittest / dockerfile or something building with icons on linux that i can take a look at?
It works out of the box on my not-that-clean windows, so might be something there or?

**Comment by vnbaaij** [comment]
@mattgoedde that is a deliberate error in the demo to show runtime verification :![Screenshot_20230620-151301.png](https://github.com/microsoft/fluentui-blazor/assets/1761079/c287ae4c-e1dc-42f5-817a-624da3a2904d)

**Comment by mattgoedde** [comment]
> @mattgoedde that is a deliberate error in the demo to show runtime verification

haha! I made this change to [the repo](https://github.com/mattgoedde/fluent-ui-test) and it works properly now!

**Comment by andreisaperski** [comment]
Microsoft.Fast.Components.FluentUI.Configuration references Microsoft.CodeAnalysis v4.5.0.0 (Microsoft.CodeAnalysis.CSharp v4.5.0.0 -> Microsoft.CodeAnalysis.Common v4.5.0.0), but the compiler shipped with .NET SDK 6.0 doesn't have this version. The latest SDK (6.0.410) has Microsoft.CodeAnalysis v4.3.0.0.
As a workaround, Microsoft.Net.Compilers.Toolset v4.5.0 reference can be added - it will force build of the project with a compiler shipped in the package.

```xml
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.5.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

It looks like the version of Microsoft.CodeAnalysis.CSharp in Microsoft.Fast.Components.FluentUI.Configuration could be downgraded to 4.2.0, it will resolve the issue at least for the majority 6.0.x SDKs. 
More robust option would be to implement different versions of the generator for different versions of Roslyn as [Microsoft.Extensions.Logging.Abstractions](https://github.com/dotnet/runtime/tree/main/src/libraries/Microsoft.Extensions.Logging.Abstractions/gen) does.

**Comment by nimrof** [comment]
> As a workaround, Microsoft.Net.Compilers.Toolset v4.5.0 reference can be added - it will force build of the project with a compiler shipped in the package.
> 
> ```
>     <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.5.0">
>       <PrivateAssets>all</PrivateAssets>
>       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
>     </PackageReference>
> ```

Thanks a loot! @andreisaperski for the explanation and a workaround, that fixed the problem.

@mattgoedde thanks for the repo it helped to reproduce the problem, if anyone is interested this action will reproduce the problem 

```
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04  
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      run: |
        apt-get update && apt-get -y install dotnet-sdk-6.0 dotnet-runtime-6.0  ca-certificates
    - name: Restore dependencies
      run: |
        cd Test.FluentUi.Server
        dotnet restore
    - name: Build
      run: |
        cd Test.FluentUi.Server
        dotnet build --no-restore
```

@vnbaaij i am done with this issue, but do you want to have it open to make some changes in the documentation or something?

**Comment by vnbaaij** [comment]
No, I'll close it as it's kind of an edge case and we have it documented in this issue now
