### ISSUE TITLE
fix: Fluent Icons makes app unable to build in Maui Blazor Android

### ISSUE THREAD

**Issue by guillaume-brouillon** [microsoft/fluentui-blazor#509]
# 🐛 Bug Report

When making the changes to csproj requested [here](https://www.fluentui-blazor.net/ProjectSetup) the MAUI .NET does not deploy on Android anymore with the error message "cannot open file" 
![image](https://github.com/microsoft/fluentui-blazor/assets/59391027/f878a248-04f7-44f5-88d0-7f9a4470a158)
Everything is working fine when deploying the app to windows. 

## 💻 Repro or Code Sample

Create a MAUI .NET App.
Initialize Fluent UI as explained [here](https://github.com/microsoft/fluentui-blazor#getting-started)
add the following to the csproj : 

`
		<PublishFluentIconAssets>true</PublishFluentIconAssets>
		<FluentIconSizes>10,12,16,20,24,28,32,48</FluentIconSizes>
		<FluentIconVariants>Filled,Regular</FluentIconVariants>
		<PublishFluentEmojiAssets>true</PublishFluentEmojiAssets>
		<FluentEmojiGroups>Activities,Animals_Nature,Flags,Food_Drink,Objects,People_Body,Smileys_Emotion,Symbols,Travel_Places</FluentEmojiGroups>
		<FluentEmojiStyles>Color,Flat,HighContrast</FluentEmojiStyles>`

Deploy to android and see app not launching.
## 🤔 Expected Behavior

The app should launch as it does in windows.

## 😯 Current Behavior

Build error : 
![image](https://github.com/microsoft/fluentui-blazor/assets/59391027/f878a248-04f7-44f5-88d0-7f9a4470a158)

**Comment by vnbaaij** [comment]
I'm guessing this is caused by the emoji and NOT by the icons. Can you verify that the file causing the issue is called 'piñata' or something like that?

**Comment by guillaume-brouillon** [comment]
Indeed removing the emokis fixed the issue !
