### ISSUE TITLE
feat: Add ability to pass Icon instances to FluentIcon

### ISSUE THREAD

**Issue by mrpmorris** [microsoft/fluentui-blazor#513]
<FluentIcon Value="@(new Icons.Regular.Size24.ArrowCircleRight())" OnClick="@HandleSearch"/>

Is there a way we can avoid the user having to use `new` here?

BTW, the `@typeparam Icon` should be `TIcon`, and we can check it has a parameterless constructor at compile time...

`@typeparam TIcon where TIcon : new()`

**Comment by dvoituron** [comment]
I suppose you mean the `new-components` branch with the new Icons library.

There are several ways of using FluentIcon with the Icon class:

1. Using the icon type. The `FluentIcon` will instantiate this type to generate the icon.
   `<FluentIcon Icon="Icons.Regular.Size24.Save" />`

2. Using an icon instance.
   `<FluentIcon Value="@(new Icons.Regular.Size24.Save())" />`
   
3. Using the `Icon.FromImageUrl` method to include this image in place of the icon.
   `<FluentIcon Value="@(Icon.FromImageUrl("/Blazor.png"))" />`

4. Using the `ToMarkup` method. This generates the SVG code without using the `FluentIcon` features.
   
BTW, naming the type `Icon` is more intuitive for the developer in the first example.
