### ISSUE TITLE
docs: add guidance for positioning elements (ie bootstrap grid system)

### ISSUE THREAD

**Issue by tomkuijsten** [microsoft/fluentui-blazor#516]
# 🙋 Documentation Request

How should one layout a page who is used to bootstrap? I couldn't find a real alternative here. I tried using nested Stack components, in combination with the Spacer, but it's not as convenient as the bootstrap grid system. Am I missing a component or obvious replacement for it?

**Comment by dvoituron** [comment]
Hi,

In the next version (v3), you will have the **FluentGrid** component. 

https://calm-sea-053fa6a03-365.westeurope.3.azurestaticapps.net/Grid
