### ISSUE TITLE
fix: JS exception when navigating to a specific page

### ISSUE THREAD

**Issue by mrpmorris** [microsoft/fluentui-blazor#525]
1. Run the demo
2. Navigate to one of the pages
3. Click "Refresh" in the browser

Problem: Error is displayed on screen.

![image](https://github.com/microsoft/fluentui-blazor/assets/3111981/3b098657-ca4c-47ea-b142-4645f4e5ae5e)

**Comment by vnbaaij** [comment]
Fixed in mentioned commit
