### ISSUE TITLE
feat: Expose the Method PaginationState#SetTotalItemCountAsync to use it outside of a DataGrid

### ISSUE THREAD

**Issue by bytefish** [microsoft/fluentui-blazor#533]
# 🙋 Feature Request

I am trying to use the Paginator Component outside of the DataGrid, but the method PaginationState#SetTotalItemCountAsync is internal, so I couldn't set it from the outside. It would be great if it could be made public, so I can reuse the Paginator for Components other than a Data Grid.

* https://github.com/microsoft/fluentui-blazor/blob/6a32fc27a21a0401b472d3a5789f69072a42e708/src/Microsoft.Fast.Components.FluentUI/Components/Pagination/PaginationState.cs#L58C5-L58C61

## 🤔 Expected Behavior

It's possible to set the Total Item Count, to reuse the Paginator outside the Data Grid.

## 😯 Current Behavior

Unable to set the TotalItemsCount in the PaginatorState.

**Comment by vnbaaij** [comment]
This will most probably be in the next minor version release (tomorrow or early next week).

If you have a (couple of) great samples where this is used, please consider posting those here. We can then put them in the demo site for everyone to learn from. Thanks.

**Comment by vnbaaij** [comment]
This is in 2.4.1 release. Available on NuGet now...

**Comment by bytefish** [comment]
Great! I need to polish the code a little, and add a link in here.

**Comment by bytefish** [comment]
@vnbaaij Hm, I don't want to open a new issue, because my question might not be an issue. In my code I copy and pasted the `FluentPaginator` and subscribed to the `EventCallbackSubscribable` exactely like the code in the DataGrid. Now I see, that an `EventCallbackSubscribable` is an internal class, and external components are probably not meant to register to them. Is there any workaround I could get notified of the `CurrentPageItemsChanged` event?

**Comment by bytefish** [comment]
@vnbaaij I have finally released the source code. 

I have used the FluentUI Paginator to paginate search results, which are part of a project on writing a Code Search:

* https://github.com/bytefish/ElasticsearchCodeSearch/tree/main/ElasticsearchCodeSearch/ElasticsearchCodeSearch.Client
