### ISSUE TITLE
feat: Expose Monaco Editor object for more flexibility

### ISSUE THREAD

**Issue by osmanium** [microsoft/fluentui-blazor#543]
# 🙋 Feature Request/Question

CodeEditor more flexibility request

## 🤔 Expected Behavior

I'd like to have more options in CodeEditor, for example I want to disable mini code map, but monaco editor object is private

`private DotNetObjectReference<FluentCodeEditor>? _dotNetHelper = null;`

## 💁 Possible Solution

Replicating all the options/properties is probably not a good idea, but a dictionary for properties, and a wrapper method to invoke methods on the editor would be nice or directly exposing monaco editor reference.

## 🔦 Context

- I'd like to customize and invoke methods on the monaco editor, such as interfering suggestions (ctrl+space) and insert new suggestions, 
- Remove mini map (1 line code editor with customized intellisense)

**Comment by vnbaaij** [comment]
Sounds do-able. We will take a look. Also, we do love to get pull requests... 😉

**Comment by vnbaaij** [comment]
Update: we currently have no plans to extend the code editor. There is not a lot of Fluent specific design in this component. If you are in need  of a more feature complete implementation, we suggest you take a look at [BlazorMonaco](https://github.com/serdarciplak/BlazorMonaco)
