### ISSUE TITLE
docs: add WPF/WinForms Blazor Hybrid Documentation to FluentUI Integrations Page

### ISSUE THREAD

**Issue by EddyHaigh** [microsoft/fluentui-blazor#547]
# 🙋 Documentation Request

There is only documentation regarding [getting the library working with Blazor Hybrid MAUI](https://learn.microsoft.com/en-us/fluent-ui/web-components/integrations/blazor). Having WPF/WinForms documentation would be useful as, right now, it is hard to tell what to do. 

## 💁 Possible Solution

Not too sure how to get it working but needs to be added the instructions alongside MAUI.

**Comment by vnbaaij** [comment]
In v3 the static assets config is no longer needed for Blazor Hybrid. There is however one (temporary) workaround needed which is described here:  https://preview.fluentui-blazor.net/#tempory-workaround-for-mauiwpfwindows-forms-issues
