### ISSUE TITLE
Client website down

### ISSUE THREAD

**Issue by AlthalusDGr8** [microsoft/fluentui-blazor#552]
When trying to browse to https://www.fluentui-blazor.net/ it is currently showing an error to reload the page.

Following error is being reported in console:
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load type of field 'Microsoft.AspNetCore.Components.Routing.TemplateParser:_invalidParameterNameCharacters' (0) due to: Could not resolve type with token 01000094 from typeref (expected class 'System.Buffers.IndexOfAnyValues`1' in assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Buffers.IndexOfAnyValues`1 member:(null)
System.TypeLoadException: Could not load type of field 'Microsoft.AspNetCore.Components.Routing.TemplateParser:_invalidParameterNameCharacters' (0) due to: Could not resolve type with token 01000094 from typeref (expected class 'System.Buffers.IndexOfAnyValues`1' in assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Buffers.IndexOfAnyValues`1 member:(null)
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(Dictionary`2 )
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(List`1 )
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(RouteKey )
   at Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable()
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters

**Comment by vnbaaij** [comment]
Yes, we are aware

**Comment by dvoituron** [comment]
The https://www.fluentui-blazor.net website is now available.
