### ISSUE TITLE
fix: white text on white background in grid demo 3.0.0-RC.1

### ISSUE THREAD

**Issue by nimrof** [microsoft/fluentui-blazor#564]
# 🐛 Bug Report

When the demo site is viewed with dark theme is impossible to read the text inside the grid boxes

## 💻 Repro or Code Sample

View the examples in the grid demo page with dark theme 
https://calm-sea-053fa6a03-365.westeurope.3.azurestaticapps.net/Grid

## 🤔 Expected Behavior

viewable text

![image](https://github.com/microsoft/fluentui-blazor/assets/9848846/e648ed04-e884-4ea8-b77d-f36516c1ec11)

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/9848846/8c7925b7-29f3-4993-9013-1d0693280c7f)

## 💁 Possible Solution

Change background or font color

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Fixed. See https://preview.blazor-fluentui.net/Grid (yes, that is a new url for the preview demo)
