### ISSUE TITLE
fix:`oncustomclick` is too generic a name

### ISSUE THREAD

**Issue by mrpmorris** [microsoft/fluentui-blazor#566]
It is used only by radio group, and does the following
1. Ensure the item is not readonly
2. Ensure the item is not disabled
3. Trigger the event with the string value of the group item

I would suggest `onradiogroupchange` (even though it is actioned with a click).

**Comment by vnbaaij** [comment]
'Custom' refers to the fact that it is an event emitted by the web components which they call custom. It could potentially be emitted by other web components (and consumed by our components) as well. That is why I stuck with the custom label.
You are right that in the current code base it is only used by radio group so we can change it. I would then rather suggest `onradiogroupclick` as it acts on the emitted click event

**Comment by mrpmorris** [comment]
Agreed
