### ISSUE TITLE
fix: No NuGet for v2.4.2 - Still v2.4.1 as latest release

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#589]
# 🐛 Bug Report

There is no NuGet for v2.4.2. Normally when a new release comes out a new NuGet version is available as well. 

https://www.nuget.org/packages/Microsoft.Fast.Components.FluentUI/

https://github.com/microsoft/fluentui-blazor/releases/tag/v2.4.2

This can probably fix this as well: https://github.com/microsoft/fluentui-blazor/issues/72#issuecomment-1646963981

**Comment by vnbaaij** [comment]
We are having an issue with the library not picking up the latest version of the script. Need to investigate what is happening. No 2.4.2 package because of that. Might take a while because of summer vacation.

**Comment by Ogglas** [comment]
I wish you a great vacation @vnbaaij!

**Comment by vnbaaij** [comment]
2.4.2 is on NuGet now
