### ISSUE TITLE
fix: NavMenu assumes fixed-size icons

### ISSUE THREAD

**Issue by mrpmorris** [microsoft/fluentui-blazor#591]
The sizes in NavMenu are fixed. This applies to icon sizes and the collapsed size.

These should be configurable at NavMenuLevel.

**Comment by mrpmorris** [comment]
I'm happy to submit a PR for this if it is acceptable?

**Comment by mrpmorris** [comment]
Sorry, no.  Pulled onto other things, I'm afraid :(

**Comment by vnbaaij** [comment]
The `FluentNavMenuLink` and `FluentNavMenuGroup` components now expose an `Icon` parameter. With that it is possible to specify an icon size (in the `Icon` reference `Icons.Regular.Size##.Home()`)
