### ISSUE TITLE
fix: Missing icons in the parametrized page

### ISSUE THREAD

**Issue by Marfusios** [microsoft/fluentui-blazor#592]
# 🐛 Bug Report

I have encountered a very strange bug. When the page receives URL parameter, some icons on the page are gone. 
Any idea what can be causing this?

## 💻 Repro or Code Sample

- [Working url](https://nostrdebug.com/publisher) 
- [Buggy url](https://nostrdebug.com/publisher?base64=eyJpZCI6IjcyYTYxYmQ4Y2E3NjMzOGYzMDY3YTM4YjhlOTQyZjRiZjlmMjVmMzYwNDEzMDMzMDY1ZTNlNThmYmE5YzQ3MDYiLCJwdWJrZXkiOiI4MjM0MWY4ODJiNmVhYmNkMmJhN2YxZWY5MGFhZDk2MWNmMDc0YWYxNWI5ZWY0NGEwOWY5ZDJhOGZiZmJlNmEyIiwiY3JlYXRlZEF0IjoxNjkwMjY4Nzk2LCJraW5kIjoxLCJ0YWdzIjpbWyJlIiwiZGU5ZTJmYmE2OTE2YzRiYjY5YTA1NmZiOTUzOGFiYTU0OTg0MjUyNmJkZTYxYzIwMTY4NDIyYmQ5NDg1MjU1MyIsIiJdLFsiZSIsImYzZjIxZGIwNThhOWZiZWJhYzE1M2ZlNTdjMTlhNzg3ZDAxZmRkOTBiYjkyYzA2ODA0M2YzODM3YzkyZDNjODMiXSxbInAiLCI5MzAzYWIyNjBhNmM3NjUzZmM4ZWEzYjA0MWQ1MzNjMmM2NzhjMWUzYzQ3NzJhMDVlOWY1M2I4YmU5OTg2OWM3Il0sWyJwIiwiNmM2ZTNlMDVlMWM5ZDJhYWUwZWQyNDMxNTQ0YWVhNDExNzcxZGQ5ZDgxMDE3NTM5YWYwZmQ4MThiMjM4OWYyOCJdXSwiY29udGVudCI6IkkgZGlkbuKAmXQgbWFrZSB0aGUgZGVhbC4gUmVzZWFyY2ggYSBiaXQuIiwic2lnIjoiNzMxNzI2NTEyZTI2YTJkMDA2MDRmMjdlNzkyNmNiMDFjYzU0MWU3MDI1OTczZmMyNWNhNDBjM2FhMDdiMjRlM2E0MWVjNzczZTMzMzNhNjBjMjJhODVlMzMwNTg3OGRlMGNlMTliYTgyOGMwMDVmMmNjMTY5NWZhYjBmOTZkMmIiLCJhZGRpdGlvbmFsRGF0YSI6e319)

Source code [here](https://github.com/Marfusios/nostr-client/blob/master/apps/nostr-debug/NostrDebug.Web/Pages/Publisher.razor)

Icons            |  No Icons
:-------------------------:|:-------------------------:
<img width="619" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/3494837/bacef556-4ed4-4bb9-980e-c8ec500119d5">  |  <img width="619" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/3494837/16b225f4-df83-48fb-ad4e-ed1e469743d7">

## 🌍 Your Environment

* OS & Device: MacOS and Windows
* Browser: Google Chrome
* Lib version: 2.4.1

**Comment by dvoituron** [comment]
I don't know why your second example doesn't contain the SVG icon.
But it's not related to the presence or absence of URL parameters: the icon is displayed when you delete the last character of your second URL: `https://nostrdebug.com/publisher?base64=...YSI6e31` (I delete the last character `9`).

In another way, in the next version (v3),  we've updated the use of icons by using a [NuGet package](https://www.nuget.org/packages/Microsoft.Fast.Components.FluentUI.Icons) with all available FluentUI icons.
See this [sample page](https://calm-sea-053fa6a03-365.westeurope.3.azurestaticapps.net/Icon).
