### ISSUE TITLE
feat: add Cancel Icon

### ISSUE THREAD

**Issue by ehsangfl** [microsoft/fluentui-blazor#595]
please add a cancel icon, if it is possible.
there is react version of this icon
[Microsoft](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons)

the SVG path data of the icon on size 32px is 
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048" class="svg_dd790ee3" focusable="false"><path d="M1115 1024l690 691-90 90-691-690-691 690-90-90 690-691-690-691 90-90 691 690 691-690 90 90-690 691z"></path></svg>`

thanks a lot

**Comment by vnbaaij** [comment]
In the SVG icons this is available as the 'Dismiss' icon
`<FluentIcon Name="@FluentIcons.Dismiss" Size="@IconSize.Size24" Variant="@IconVariant.Regular" Color="@Color.Accent"/>`
