### ISSUE TITLE
NavMenu does not switch to items with icons if they have already been switched

### ISSUE THREAD

**Issue by gitvadim** [microsoft/fluentui-blazor#601]
# 🐛 Bug Report

NavMenu does not switch to items with icons if they have already been switched to when the icon is clicked.

## 💻 Repro or Code Sample

1. Implement the NavMenu as described [here](https://www.fluentui-blazor.net/Lab/NavMenu): 
2. Make sure you have at least one Menu Item with a FluentIcon
3. Click the menu item with the icon (click the icon),
4. Click any other item
5. Click the menu item with the icon again (click the icon)

## 🤔 Expected Behavior

The menu should correctly set the clicked item as active regardless of it having an icon.

## 😯 Current Behavior

Right now, if a menu item is activated by clicking its icon, activating any other menu item (with or without icon) blocks the original menu item from ever becoming active again. 

## 🔦 Context

I'm trying to build a NavMenu for my app and right now this blocks me entirely.

## 🌍 Your Environment

OS: Windows 11 Pro 22H2 (22621.1992)
NET: 7.0
Fluent UI: 2.3.6

The issue can also be observed on the [demo site](https://www.fluentui-blazor.net/Lab/NavMenu), that has this FluentUI version: 2.4.2+286cf97d00e8c22a325e44c0b500ee2738a9cd40  -  NET 7.0.9

**Comment by vnbaaij** [comment]
The NavMenu has been significantly changed for v3. Please try your scenario with the RC of this version. A final version will be released before the end of the month.
Qe will not be making any big changes to the lab/v3 components anymore...

**Comment by gitvadim** [comment]
I can't reproduce this on the v3 demo site, however, locally, I'm still getting the same issue with NET7 and Microsoft.Fast.Components.FluentUI 3.0.0-RC.1. In my local I'm using Blazor Server if that matters.

**Comment by vnbaaij** [comment]
I can't reproduce this on the Server version of the demo site. Please supply a repo where we can investigate this

**Comment by gitvadim** [comment]
Hey, I've figured out what was the problem. The project I had the issue with had been created using version 2 Fluent UI templates and had a reference to version 2 of the web-components.min.js file. When I removed it, cleaned the project and rebuilt it, everything started to work the way it should. My bad.
