### ISSUE TITLE
docs: The 'LibraryConfiguration' class has no described properties

### ISSUE THREAD

**Issue by sajadkardel** [microsoft/fluentui-blazor#607]
![Untitled](https://github.com/microsoft/fluentui-blazor/assets/62190682/a9f58cfd-54d6-4a93-b696-50675129319b)

FluentUI Version: `3.0.0-RC.1`.

I want to add Icons/emojis to my project and when I follow the document, some of the properties that I want to add in the AddFluentUIComponents method are missing.

**Comment by dvoituron** [comment]
Hi,
Using the new Lib (v3). You don't have startup configure. You have to add the new Icons NuGet and that's all. 

https://preview.fluentui-blazor.net/Icon
