### ISSUE TITLE
fix: The `Flipper` in `HorizontalScroll` component  is in the wrong direction.

### ISSUE THREAD

**Issue by sajadkardel** [microsoft/fluentui-blazor#608]
![Untitled](https://github.com/microsoft/fluentui-blazor/assets/62190682/45be9c7a-a722-44bf-bca5-6f9af7e566e4)

I've set up the `<FluentDesignSystemProvider>` with `Direction="LocalizationDirection.rtl"` and the flippers in the `HorizontalScroll` component do not match the direction.

**Comment by vnbaaij** [comment]
This seems to be an issue in the underlying web components script. I raised an issue there: https://github.com/microsoft/fast/issues/6810. 
Once the web components script is fixed, it will be fixed here as well,

**Comment by vnbaaij** [comment]
Closing this as it will not be solved in FAST
