### ISSUE TITLE
Fluent controls Css is not getting applied from css file

### ISSUE THREAD

**Issue by RekhaMamil** [microsoft/fluentui-blazor#610]
# 🐛 Bug Report
Fluent control: CSS  is not getting applied from css file

We have separate project for custom controls where  we are using fluent controls. We are adding razor specific css file along with the controls. Css classes from css file are not getting applied. When we move the same classes in to .razor file as an internal css they are getting applied.

## 💻 Repro or Code Sample
Below is the code for .razor file

![image](https://github.com/microsoft/fluentui-blazor/assets/141959602/64c97327-2472-469e-a97a-db542db18c24)

And We have added below css in .razor.css file
![image](https://github.com/microsoft/fluentui-blazor/assets/141959602/ddcf42ee-3340-4941-8a40-7fdf8cb7d182)

## 🤔 Expected Behavior
Dialog height and width should get applied

## 😯 Current Behavior
Dialog height and width is not get applied

## 🌍 Your Environment

* Windows 11
* Browser Microsoft Edge, Google Chrome
* .NET 7.0 and FAST Version 2.4.1

**Comment by vnbaaij** [comment]
We need a repo to be able to examine this. Can you supply one?

**Comment by vnbaaij** [comment]
Closing this as no response received
