### ISSUE TITLE
Toasts

### ISSUE THREAD

**Issue by vincemcc79** [microsoft/fluentui-blazor#611]
# 🐛 Bug Report

Toasts using the samples from the document don't seem to work

## 💻 Repro or Code Sample
In program.cs
builder.Services.AddFluentUIComponents();

In an Index page
@page "/"
@using Microsoft.Fast.Components.FluentUI;
@inject IToastService ToastService

<p>Click on this button to open a Toast. The toast is created by just specifying an intent and a message.</p>

<FluentButton @onclick="@ShowToast" Appearance="Appearance.Accent">Open</FluentButton>

@code
{
    int counter = 1;
    void ShowToast()
    {
        Random rnd = new();

        var intent = Enum.GetValues<ToastIntent>()[rnd.Next(10)];
        var message = $"Simple Toast #{counter++}";
        ToastService.ShowToast(intent, message);
    }
}

## 🤔 Expected Behavior

Toast should appear

## 😯 Current Behavior

Unfortunately, the toast never appears

## 💁 Possible Solution

Perhaps I am missing something in the set up?
Is there more steps involved to get toast working aside from injecting the service?
I see that builder.Services in the program file can also AddFluentToasts but that doesn't make a difference  if I add it.

## 🔦 Context
Thank you 
## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge, 
* .NET and FAST Version dotnet 7 and v3.01RC

**Comment by joecuevasjr** [comment]
@vincemcc79 There's undocumented setup for using toasts, please refer to this post: https://github.com/microsoft/fluentui-blazor/issues/606#issuecomment-1673347086

Also, if you're using Blazor Server don't forget your add `builder.Services.AddHttpClient()` before `AddFluentUIComponents()` and set the ` option.HostingModel` as documented here for v3.0.0-RC.1 https://calm-sea-053fa6a03-365.westeurope.3.azurestaticapps.net/CodeSetup

**Comment by vincemcc79** [comment]
Hi @joecuevasjr

That sorted it out - Thank you very much, I missed the post #606 somehow.
Excellent! Have a great weekend!
