### ISSUE TITLE
Blazor Fluent Template Update

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/fluentui-blazor#616]
Are there any plans to update the Fluent Blazor Template to Include more features and better align with Fluent Design Language.

In the sense of aligning with Fluent Design Language, We could add a better Side Nav Bar that Responsive for Different Screen Sizes.

Additionally Add a New Section in Nav Bar Called Settings which hosts Theme Switcher, RTL Switcher, Etc..

This is my initial take on this, feel free to hope in and to share your thoughts.

By the way, I'm ready to create a pull request on this and work on it in the near future.

**Update**: We could also align this with Blazor Fluent v3 as well

**Comment by vnbaaij** [comment]
Hi, 

The template that we have now, will soon be updated to use the then latest released version (v3) of the library. We do **not** plan to add any new functionality to it. It will remain just a copy of the regular Blazor template with the Fluent UI library and components already set up (and Bootstrap, etc. removed).

What we **can** do is add a new/extra template to the template package that has (some of) the functionality that you describe. However, due to all the thing we still need to do, this would need to come from PRs contributed by others. If you would like to work on that, great!

**Comment by AathifMahir** [comment]
> Hi, 
> 
> The template that we have now, will soon be updated to use the then latest released version (v3) of the library. We do **not** plan to add any new functionality to it. It will remain just a copy of the regular Blazor template with the Fluent UI library and components already set up (and Bootstrap, etc. removed).
> 
> What we **can** do is add a new/extra template to the template package that has (some of) the functionality that you describe. However, due to all the thing we still need to do, this would need to come from PRs contributed by others. If you would like to work on that, great! 

I would love to work on it.

**Comment by AathifMahir** [comment]
@vnbaaij Can you keep this open and assign me into it

**Comment by AathifMahir** [comment]
Do we have a name or package Id for the new template?

**Suggestions**:          

- Microsoft.Fast.Templates.FluentUI.Standard
- Microsoft.Fast.Templates.FluentUI.Basic
- Microsoft.Fast.Templates.FluentUI.Starter

**Comment by AathifMahir** [comment]
> Do we have a name or package Id for the new template?
> 
> **Suggestions**:          
> 
> - Microsoft.Fast.Templates.FluentUI.Standard
> - Microsoft.Fast.Templates.FluentUI.Basic
> - Microsoft.Fast.Templates.FluentUI.Starter

Anything on this? @vnbaaij

**Comment by vnbaaij** [comment]
Maybe `Microsoft.Fast.Templates.FluentUI.Extended`? 
I would not go with master branch as that is now still v2 code. New components branch is the v3 code.
Are you not planning on this template being part of the existing template package? If so, why not? Maybe I have not been clear before, but I meant we will not change the existing Server and WebAssembly templates. We can definitely add a new one.

**Comment by AathifMahir** [comment]
> Maybe `Microsoft.Fast.Templates.FluentUI.Extended`? 
> I would not go with master branch as that is now still v2 code. New components branch is the v3 code.
> Are you not planning on this template being part of the existing template package? If so, why not? Maybe I have not been clear before, but I meant we will not change the existing Server and WebAssembly templates. We can definitely add a new one. 

I was planning to make the template available for v2 as well but that defeats the purpose right since v3 is around the corner, I'll develop based on the new components branch. Thanks for the package id, I'll go with that.

**Comment by AathifMahir** [comment]
Are we going to Include this in Default Template Nuget or Want to Make New Nuget package? @vnbaaij 

This is how initially structured the project:
https://github.com/AathifMahir/fluentui-blazor/tree/Extended-Templates/src/Templates

**Comment by vnbaaij** [comment]
In default template NuGet. I'll take a look at project early next week

**Comment by vnbaaij** [comment]
@AathifMahir I just updated our templates to use the latest v3.x package and made the necessary code changes. It can oll be found in the `dev` branch. Pushing a V3 version of the template package to NuGet as well.

**Comment by AathifMahir** [comment]
> @AathifMahir I just updated our templates to use the latest v3.x package and made the necessary code changes. It can oll be found in the `dev` branch. Pushing a V3 version of the template package to NuGet as well.

Great, in that case I'll start working on the Extended version of the template in the next few weeks

**Comment by vnbaaij** [comment]
Hi @AathifMahir, are you still (planning to) work(ing) on this?

**Comment by AathifMahir** [comment]
> Hi @AathifMahir, are you still (planning to) work(ing) on this? 

Yes, of course. I was busy with the project that I mentioned before and the project will be going to production within the next 3 days to a week. I'm looking to Work on this afterwards

**Comment by vnbaaij** [comment]
For v4 I've copied and updated the newest standard Blazor templates (both Blazor Web App and Standalone Blazor WebAssembly). These will be available soon. Impression:
![template+auth](https://github.com/microsoft/fluentui-blazor/assets/1761079/33f6ad08-78d6-485e-a2ec-8747a9db7aa2)

(Early version. They look better now)
