### ISSUE TITLE
fix: Could not load file or assembly Microsoft.Fast.Components.FluentUI issue in Blazor Server App with FluentUI version 3.0.0-RC.1

### ISSUE THREAD

**Issue by v-rajesha** [microsoft/fluentui-blazor#618]
Hi Team,

We are using Fluent UI version 2.4.1 in Blazor application and upgraded Fluent UI to version 3.0.0-RC.1. 

Followed required process as mentioned  in [https://www.nuget.org/packages/Microsoft.Fast.Components.FluentUI/3.0.0-RC.1](url) but getting  issue : **Could not load file or assembly Microsoft.Fast.Components.FluentUI Version=3.1.23185.1**  

Please find below screenshot of issue.
<img width="902" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/128696687/de61cd58-4205-40d6-b830-f063a45ce9aa">

Help on this will be highly appreciated.

Thanks,
Rajesh

# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
See #573. 

Will be fixed in a later version
