### ISSUE TITLE
fix: Accessibility: Ensures buttons have discernible text in FluentSearch

### ISSUE THREAD

**Issue by anujasuvarnkar124** [microsoft/fluentui-blazor#621]
# 🐛 Bug Report
We are facing below accessibility issue for FluentSearch control's search button. We are checking accessibility issues by using **FastPass** option of **Application Insights for Web** extension. 
This issue is available on https://www.fluentui-blazor.net/Search as well.

Please find below screenshot for more details:
<img width="239" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/142414647/27c6e76f-049c-4061-95c2-04259ca7909c">

<img width="391" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/142414647/67ac6ba1-4f79-442e-afa2-b70c66e1e2fd">

## 💻 Repro or Code Sample

We have integrated fluent search control as below:
<img width="434" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/142414647/f09996d6-44a9-470d-8955-93f5de086b15">

## 🤔 Expected Behavior

Fluent Search should not throw any accessibility issue.

Thank you in advance...!!

**Comment by vnbaaij** [comment]
Needs to be solved in the underlying web component, I've raised an issue for it: https://github.com/microsoft/fast/issues/6813

**Comment by vnbaaij** [comment]
Created a workaround to set the `aria-hidden` attribute without changing the web components script.
