### ISSUE TITLE
fix: v3 Unhandled exception rendering in NavMenuContent of FluentMainLayout

### ISSUE THREAD

**Issue by flogruber** [microsoft/fluentui-blazor#624]
# 🐛 Bug Report

If the `NavManuContent` of the `FluentMainLayout` is used in a release version, then the navigation icon is not displayed correctly, as the error message listed in the point below is delivered.

## 💻 Repro or Code Sample

```
<FluentMainLayout>
    <Header>
        WebApp-Name
        <FluentSpacer />
        <AccessControl />
    </Header>

    <Body>
        @Body
    </Body>

    <NavMenuContent>
        <FluentNavMenuLink Icon="@(new Icons.Regular.Size24.Home())" Text="Home" Href="/" />
        <FluentNavMenuLink Icon="@(new Icons.Regular.Size24.Cloud())" Text="Counter" Href="/counter" />
    </NavMenuContent>
</FluentMainLayout>
```

## 🤔 Expected Behavior

<img width="253" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/49080575/9062e3ab-1b38-4913-b78c-8b7e32eeab7f">

## 😯 Current Behavior

<img width="317" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/49080575/e5a2618c-e0d2-484c-93a6-798c9aef3783">

**Error Message in app release version**
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type Microsoft.Fast.Components.FluentUI.CoreIcons+Regular+Size24+Navigation must have a parameterless constructor.
System.ArgumentException: The type Microsoft.Fast.Components.FluentUI.CoreIcons+Regular+Size24+Navigation must have a parameterless constructor.
   at Microsoft.Fast.Components.FluentUI.FluentIcon`1[[Microsoft.Fast.Components.FluentUI.CoreIcons.Regular.Size24.Navigation, Microsoft.Fast.Components.FluentUI, Version=3.0.23198.21, Culture=neutral, PublicKeyToken=null]].OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

## 🔦 Context

Blazor WASM, .NET7.0

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Edge
* .NET: 7.0
* Microsoft.Fast.Components.FluentUI: 3.0.0-RC.1

**Comment by vnbaaij** [comment]
Can't reproduce on local WASM demo site. Please supply a repo that we can test against/investigate on

**Comment by flogruber** [comment]
Hello,  
thank you very much!  

I have just made available a demo repo with FluentUI v3, which is published directly via Github Actions.  
The publised version shows that the error occurs.  

Repo: https://github.com/flogruber/BlazorWASM-FluentUI-Demo  
Page: https://fluentui-demo.bitscode.dev/  

**error message**  
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type Microsoft.Fast.Components.FluentUI.CoreIcons+Regular+Size24+Navigation must have a parameterless constructor.
System.ArgumentException: The type Microsoft.Fast.Components.FluentUI.CoreIcons+Regular+Size24+Navigation must have a parameterless constructor.
   at Microsoft.Fast.Components.FluentUI.FluentIcon`1[[Microsoft.Fast.Components.FluentUI.CoreIcons.Regular.Size24.Navigation, Microsoft.Fast.Components.FluentUI, Version=3.0.23198.21, Culture=neutral, PublicKeyToken=null]].OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

**Comment by vnbaaij** [comment]
Is it working for you when running the code locally? It is for me. After cloning your repo and running from VS I get:
<img width="276" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/1ded1f36-670d-4fd9-9f28-e2d92c15b174">

Also, i see in your repo you are using Icons RC1 package. There is an issue with that package. Change it to use 3.0.0-preview.5 NuGet. See https://github.com/microsoft/fluentui-blazor/issues/573 for more information.

It must be something with running the site on GitHub pages (which is something I have no experience with and can't really help with)

**Comment by flogruber** [comment]
Thank you for the information.  
I tried changing the Icons package and this did not solve the problem.  

After some back and forth, I was able to identify a possible issue that only occurs when the Blazor WASM is published and then made available on a web server.   
This error does not occur in the Debug and Release Debugging in VS, only when the files are publised.  

I have included now two buttons in my demo. The Icon is displayed for one and not for the second one.  
<img width="499" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/49080575/8d1c463a-5c9c-4dcb-aafd-06bc044ef8d5">

```
<FluentButton><FluentIcon Value="@(new Icons.Regular.Size24.Fingerprint())" />Button - Icon as Value-Parameter</FluentButton>
<FluentButton><FluentIcon Icon="Icons.Regular.Size24.Airplane" />Button - Icon as Icon-Parameter</FluentButton>
```  
It looks like if the parameter `Icon` is used and no object has been generated from this icon before, it cannot be loaded correctly.  

**error message**  
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type Microsoft.Fast.Components.FluentUI.Icons+Regular+Size24+Airplane must have a parameterless constructor.
System.ArgumentException: The type Microsoft.Fast.Components.FluentUI.Icons+Regular+Size24+Airplane must have a parameterless constructor.
   at Microsoft.Fast.Components.FluentUI.FluentIcon`1[[Microsoft.Fast.Components.FluentUI.Icons.Regular.Size24.Airplane, Microsoft.Fast.Components.FluentUI.Icons, Version=3.0.23198.3, Culture=neutral, PublicKeyToken=null]].OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

And the same implementation applies to the `FluentNavMenu`-Component in the `MainLayout`-Component.  
https://github.com/microsoft/fluentui-blazor/blob/new-components/src/Core/Components/NavMenu/FluentNavMenu.razor#L29C50-L29C50  

Could it be related to that?

**Comment by vnbaaij** [comment]
I triggered on the 'only when published' part. It might be an issue with trimming and/or the new .NET 8 Native AOT settings. @dvoituron can you perhaps take a look once you're back?

**Comment by dvoituron** [comment]
Indeed, this seems to be an error linked to the Trimming process. A Reflector should be used to look at the DLL Icons generated in the Publish folder. This icon has probably been removed by the publication process. 

I'll have a look at it next week, when I'm back from vacation 😀

**Comment by dvoituron** [comment]
I've downloaded your sample code. Indeed, the `Airplane` icon is used using the `Icon` property. This property creates an instance dynamically during application execution. The Trimming process does not see this instance creation. It then deletes the code from the icon library.

Example displayed using the **Reflector**:
```csharp
public class Airplane : Icon
{
}

public class Cloud : Icon
{
    public Cloud() : base("Cloud", IconVariant.Regular, IconSize.Size24, "<path d=\"M12 5.5a4.5 4.5 0 0 0-4.5 4.29.75.75 0 0 1-.74.71H6.5a3 3 0 1 0 0 6h11a3 3 0 1 0 0-6h-.26a.75.75 0 0 1-.74-.71A4.5 4.5 0 0 0 12 5.5ZM6.08 9.02a6 6 0 0 1 11.84 0A4.5 4.5 0 0 1 17.5 18h-11a4.5 4.5 0 0 1-.42-8.98Z\"/>") { }
}
```

**Possible workarounds:**
1. To use the `Value` property.
2. To publish the project using the configuration `<PublishTrimmed>false</PublishTrimmed>` in the csproj (but not application for WASM projects)
3. To instantiate this icon in another location `var x = new Icons.Regular.Size24.Airplane()`
4. To use a **Root Descriptors** file, to exclude some types from the Trimming process, like describe in this [doc page](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#root-descriptors).

But I'm going to contact the [Trimming Tools](https://github.com/dotnet/runtime/tree/main/src/tools/illink) team to find out if (and how) it's possible to keep the code of a referenced class.

**Comment by flogruber** [comment]
Thank you very much for your answer!  

That means we have to wait and see if there will be any changes in the Trimming Tools in the near future so that `MainLayout` can be used with the `FluentNavMenu`.   
Or will there be a change in the `MainLayouts` `FluentNavMenu` so that the `NavigationIcon` is implemened differently?

https://github.com/microsoft/fluentui-blazor/blob/main/src/Core/Components/NavMenu/FluentNavMenu.razor#L29C50-L29C50

Thanks!

**Comment by vnbaaij** [comment]
Yes, changing that line to use `Value` in the next update
