### ISSUE TITLE
fix: ComboBox Select Menu in ComboBox

### ISSUE THREAD

**Issue by IdrisQashan** [microsoft/fluentui-blazor#627]
I Have Maked z-index: 999
Also Did'nt Work

So Can You Fix This Issue And Stop Scrolling And Be Top Of All

![Screenshot 2023-08-18 204744](https://github.com/microsoft/fluentui-blazor/assets/62256969/04474d92-ba37-4fc7-87f5-77cf8e77a946)

**Comment by vnbaaij** [comment]
There is no 'top of all' in CSS. The listbox can not break out of its parent div. You can make this work in your own app/site by making sure the parent container has sufficient height.
