### ISSUE TITLE
feat: add center to/in anchored region horizontal and vertical position

### ISSUE THREAD

**Issue by Karlssn** [microsoft/fluentui-blazor#642]
# 🙋 Feature Request
We are running in to a problem where it the enum value seems to be missing for centering the fluent anchored region.

## 🤔 Expected Behavior
For our usecase, we would want to have the HorizontalPosition to include HorizontalPosition.Center as well as VerticalPosition to include VerticalPosition.Center

## 😯 Current Behavior
Today this value does not exist. 

## 💁 Possible Solution
It seems to me that it should be a simple enum to be updated [from](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/anchored-region/anchored-region.options.ts#L45) in the horiztonal position [file](https://github.com/microsoft/fluentui-blazor/blob/main/src/Microsoft.Fast.Components.FluentUI/Enums/HorizontalPosition.cs)
and the vertical position [file](https://github.com/microsoft/fluentui-blazor/blob/main/src/Microsoft.Fast.Components.FluentUI/Enums/VerticalPosition.cs) 

## 🔦 Context
We have solved this issue today by invoking a javascript method doing the following: 
`element.setAttribute("horizontal-default-position", "center");`

**Comment by vnbaaij** [comment]
This will be available in v3 release (not in RC1 yet). 

See ['Open callout 2'](https://preview.fluentui-blazor.net/Popover#emptyparts) in the Popover examples and ['Toggle position and size'](https://preview.fluentui-blazor.net/AnchoredRegion#togglepositionandsize) in the AnchoredRegion examples for usage.
