### ISSUE TITLE
FluentIcon sometimes fails to render

### ISSUE THREAD

**Issue by konvolution** [microsoft/fluentui-blazor#645]
# 🐛 Bug Report

We had the following scenario:

* A virtualized FluentDataGrid with a column containing a FluentIcon in every row.
* Icons were missing in some rows.

I think the problem is with the following code. If the icon content has changed, `StateHasChanged()` is called to force a re-render. However, since `_shouldRender` is not set to true, rendering is skipped.

```csharp
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (!_iconChanged)
        {
            return;
        }

        _iconChanged = false;
        var iconContent = await GetIconContentAsync();

        if (_previousIconContent != iconContent)
        {
            _svg = iconContent;
            _previousIconContent = iconContent;
            _size = Convert.ToInt32(Size);
            // I think `_shouldRender = true;` is needed here
            StateHasChanged();
        }
    }
```

We worked around the problem by deriving from `FluentIcon` and overriding `ShouldRender()` to always return true.

**Comment by vnbaaij** [comment]
I'm adding the `_shouldRender=true` for v2.4.3 (should be out later today)
