### ISSUE TITLE
fix: [Is there any way to change styling of selected Fluent Tab and change position of extra tabs] in [Blazor Server App?]

### ISSUE THREAD

**Issue by v-rajesha** [microsoft/fluentui-blazor#652]
Hi Team,

We are using **Fluent UI version 3.0 RC1** in Blazor Server App. We are not able to apply custom CSS classes to selected **Fluent Tab** and unable to change direction of **fluent-anchored-region** popup(extra tabs) to bottom position. Currently extra tabs popup opens in top position of fluent badge and extra tabs are not displaying properly as mentioned in below screenshot. Please let us know how to add custom CSS classes to fluent tabs and change the direction of fluent-anchored-region popup (extra tabs) to bottom position using CSS.
<br>
<img width="560" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/128696687/69940ca3-5249-439d-a858-3f3862bcc0b7">
<br><br><br>

Please find below sample code snippet used from Fluent UI version 3.0 RC1.

<img width="686" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/128696687/5841fe6c-4dce-40aa-a8f5-be5de2ae80c5">

Help on this will be highly appreciated.

Thanks,
Rajesh

# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
For styling the tab, the `LabelClass` and `LabelStyle` parameters arre added in v3. 

The popup for the extra tabs uses a `FluentMenu` with a `VerticalDefaultPosition="@VerticalPosition.Bottom"` for displaying the list . (this in turn renders a `fluent-anchored-region`). If the menu is displayed ate the top, that means there is not sufficient room to display it at the bottom. This is automatically determines  by the web component and we can't influence that
