### ISSUE TITLE
Huge Emoji DLL download

### ISSUE THREAD

**Issue by warappa** [microsoft/fluentui-blazor#653]
# 🐛 Bug Report

I tried to open the v3 announcement post on fluentui-blazor.net on my phone, but it seemed stuck at 99%.
At my PC I opened it with developer tools open and saw why it takes so long:
**`Microsoft.Fast.Components.FluentUI.Emojis.dll` has 28.2MB!**

## 💻 Repro or Code Sample

On a desktop, open a browser with its Network developer tools open and open https://www.fluentui-blazor.net/#whatsnew.

## 🤔 Expected Behavior

The page (and maybe the library itself) should not require to download 10ths of MB, especially not for emojis. Especially for a showcase page, it's no good look.

## 😯 Current Behavior
With a good 100MBit/s connection:

Emojis:
<img width="717" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/886232/1754ecfc-9467-49c0-b44e-a977cbe38667">

Total transfer:
<img width="396" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/886232/677ad424-4e16-4b18-a261-fc6e0361c8cd">

## 🌍 Your Environment

* OS & Device: Windows 11 22H2 (Build 22621.2215)
* Browser: Microsoft Edge 116.0.1938.62

**Comment by vnbaaij** [comment]
Yes, that is correct. The DLL houses around 7500 different emoji which we all want to have browsable in the demo environment.

If you would use the emoji package in your own program, the publication process will trim the DLL to contain only the emoji that are actually being used in your application with the result that that would normally be a tiny piece to download. For the demo that is not the case.
