### ISSUE TITLE
fix: [FluentTreeItem not collapsing and expanding properly] in [Blazor Server App]

### ISSUE THREAD

**Issue by v-rajesha** [microsoft/fluentui-blazor#659]
Hi Team,

We are using Fluent UI 3.0 RC1 in Blazor server application.
I need to expand all nested treeviewitems on component initial load and expand/collpase all nested treeview items on button click.
Expand all TreeViewItems on first load is working fine with property InitiallyExpanded=true.
We have tried Expanded / @bind-Expanded properties to collapse all treeview items when user clicks on button but we are unable to expand single treeviewitem first time after collapsing all treeview items using Expanded=false property.Treeviewitem is expanding and collapsing automatically. Please find below sample screenshot of treeview structure.
<br>
<img width="361" alt="Screenshot 2023-08-30 192214" src="https://github.com/microsoft/fluentui-blazor/assets/128696687/fac12064-ded2-4e66-9539-99227cdaa1f9">
<br>
Help on this will be highly appreciated!

Thanks,
Rajesh

# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Sorry, but I don't understand what your ask is.

What version of the library are you using? And did you take a look at https://www.fluentui-blazor.net/TreeView#withdatabinding

**Comment by v-rajesha** [comment]
HI @vnbaaij ,

we are using Fluent UI 3.0 version and followed same steps mentioned in [https://www.fluentui-blazor.net/TreeView#withdatabinding](url). 

Please find below sample screenshot of FluentTreeVIew used in the application and performed below steps in sequence for identifying the issue.

- Expand/Collapse each TreeViewItem.
- Collapsed all TreeView Items on button click using @bind-Expanded property. 
- Trying to expand one TreeView item but it is expanding and collapsing automatically.

We observed TreeView Item not expanding on first click and it is expanding on second click. Can you help us on this issue.

<img width="361" alt="Screenshot 2023-08-30 192214" src="https://github.com/microsoft/fluentui-blazor/assets/128696687/cce49fbb-46e3-4a16-ac60-d1b15dfe70d4">


Thanks,
Rajesh

**Comment by vnbaaij** [comment]
Sorry, but I still don't understand. You provided the same screenshot and no extra information...

- Expand/Collapse each TreeViewItem.
Manual action by just clicking on the items?

- Collapsed all TreeView Items on button click using @bind-Expanded property.
By iterating the tree view items (with children)  and then set the property? 

- Trying to expand one TreeView item but it is expanding and collapsing automatically.
How are you trying to expand then? How is it expanding and collapsing automatically?

**Comment by v-rajesha** [comment]
Thanks @vnbaaij for reaching out. we have found solution for above issue.
To resolve the issue, I am iterating through each item and set the @bind-Expanded property.

Thank you so much for support.
