### ISSUE TITLE
feat: Change the icon location in the MessageBox to the Title instead of in the body

### ISSUE THREAD

**Issue by StevenRasmussen** [microsoft/fluentui-blazor#660]
# 🙋 Feature Request

It seems like the most common design pattern for icons in dialogs is to place the icon next to the title and not in the body. 

## 🤔 Expected Behavior

Icon should be part of the Title

## 😯 Current Behavior

Icon is part of the body:

![image](https://github.com/microsoft/fluentui-blazor/assets/11198735/039356b5-bcf8-40ec-8e30-9d7811d3af69)

**Comment by vnbaaij** [comment]
Hi Steven, 

The Fluent 2 specs dictate to only use text in a Dialog title.

**Comment by StevenRasmussen** [comment]
@vnbaaij - I had reviewed the spec and re-reviewed it now to try and find where it says something to the effect of "Thou shalt not put any icons in the Title" and was not able to find any.  If you're referring to the text in the "Layout" section that says:

> A header, which can contain a title and a dismiss icon

then I would say that your interpretation is pretty reaching to say that it should "only use text".  If I missed it, please correct me and point me to the part in the spec where you are deriving your stance from.

For context, a suggestion was made and implemented in the React repo for the same thing back in 2019 here: [https://github.com/microsoft/fluentui/issues/8238](https://github.com/microsoft/fluentui/issues/8238)

At the very least, I feel you should expose a property to be able to turn off the icon.  I would rather there be no icon than have it appear next to the body text.  The layout looks horrendous when used with longer text:

![image](https://github.com/microsoft/fluentui-blazor/assets/11198735/77841fab-dac7-4906-afd4-f8d8a0e8afa6)

Ideally I would suggest an `IconLocation` property with the following values:
1) None
2) Title
3) Body - Top
4) Body - Centered
5) Body - Bottom

I don't know if option 5 would ever be used but I put it in there more for completeness.  Anyway, I hope you seriously consider allowing for some deviation of the current implementation, otherwise I feel many of us will be recreating our own dialogs which reduces the usefulness of this feature.

**Comment by StevenRasmussen** [comment]
I'll just leave this here for comparison:

![image](https://github.com/microsoft/fluentui-blazor/assets/11198735/c10ffa66-daba-4774-ae96-c033c3734667)

**Comment by vnbaaij** [comment]
> @vnbaaij - I had reviewed the spec and re-reviewed it now to try and find where it says something to the effect of "Thou shalt not put any icons in the Title" and was not able to find any. If you're referring to the text in the "Layout" section that says:
> 
> > A header, which can contain a title and a dismiss icon
> 
> then I would say that your interpretation is pretty reaching to say that it should "only use text". If I missed it, please correct me and point me to the part in the spec where you are deriving your stance from.

Yes, I'm referring to that and also the (internal) Figma design documents. They are pretty  clear in their language normally and would call out using an icon if 'allowed'. We are in a certain amount free of course to define our own 'rules'

 
> For context, a suggestion was made and implemented in the React repo for the same thing back in 2019 here: [microsoft/fluentui#8238](https://github.com/microsoft/fluentui/issues/8238)
> 

True, but that was for the (much older) Fluent predecessor (office-ui-fabric-react@v6.159.0)

> At the very least, I feel you should expose a property to be able to turn off the icon. I would rather there be no icon than have it appear next to the body text. The layout looks horrendous when used with longer text:

I'm changing the `MessageBox` code to not render an Icon if one is not supplied in the parameters:
```
     _dialog = await DialogService.ShowMessageBoxAsync(new DialogParameters<MessageBoxContent>()
            {
                Content = new()
                {
                    Title = "My title",
                    MarkupMessage = new MarkupString("My <strong>customized</strong> message"),
                    //Icon = new Icons.Regular.Size24.Games(),
                    //IconColor = Color.Success,
                },
                PrimaryAction = "Plus",
                SecondaryAction = "Minus",
                Width = "300px",
            });
            DialogResult result = await _dialog.Result;
```
Renders as 
<img width="222" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/f88404fa-0c48-4e1f-868c-a37b10f2503b">

> Ideally I would suggest an `IconLocation` property with the following values:
> 
> 1. None
> 2. Title
> 3. Body - Top
> 4. Body - Centered
> 5. Body - Bottom
> 
 Not going to add all of these. Too much rendering complexities to handle. I will look at an option to enable adding an `Icon` to the title
