### ISSUE TITLE
fix: FluentSwitch/FluentCheckbox => @bind-Value does not call property setter

### ISSUE THREAD

**Issue by hml-coder** [microsoft/fluentui-blazor#661]
# 🐛 Bug Report

`FluentSwitch/FluentCheckbox` => `@bind-Value` does not call property setter

## 💻 Repro or Code Sample

I must be doing something wrong or have no understanding of how 2-way binding works in Blazor Server (or both).  Tried using the documented Value and ValueChanged as well.

```
FluentStack>
    <FluentSwitch @bind-Value="Show" >Toggle Switch</FluentSwitch>
@*<FluentCheckbox @bind-Value="Show">Toggle Checkbox</FluentCheckbox>*@
    <FluentLabel Typo="Typography.Body">@Show</FluentLabel>
</FluentStack>

@code {
    // full property for debugging.
    private bool show = false;
    private bool Show 
    {
        get 
        { 
            return show; 
        }
        set 
        {
            if (show != value)
            {
                show = value;
            }
        }
    } 
}
```

## 🤔 Expected Behavior

Property setter should be called

## 😯 Current Behavior

Property setter not called

## 🌍 Your Environment

* Windows 11 with updates
* VS 2022 17.16.0
* .Net 7
```
<PackageVersion Include="Microsoft.Fast.Components.FluentUI" Version="3.0.0-RC.1" />
<PackageVersion Include="Microsoft.Fast.Components.FluentUI.Icons" Version="3.0.0-preview.5" />
```

**Comment by vnbaaij** [comment]
Hi,

`@onclick` is a standard Blazor event handling mechanism so we have not described/documented that further.

What is not working for you. If I use your code, I get this in the demo site (when setting  `show` to true):

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/414488f2-5c1d-4d2e-b7f0-27ee6502ff5e)

Flicking the switch changes the label text to 'False'

**Comment by vnbaaij** [comment]
Hi,

Sorry, previous answer was a mis-interpretation from my side... 

I've pasted your code and ran it in the demo site in VS. Set a breakpoint on the `show = value;` line and that gets triggered when running in debug mode. Tried both Server and Client versions of the demo.

**Comment by vnbaaij** [comment]
Just thought of something...Did you implement the workaround mentioned here: https://github.com/microsoft/fluentui-blazor#tempory-workaround-for-mauiwpfwindows-forms-issues

**Comment by vnbaaij** [comment]
I downloaded your project, updated to v3 Final package and added the following to `index.html` in `WinFormsBlazorFluent`:
```
    <script app-name="WinFormsBlazorFluent" src="./_content/Microsoft.Fast.Components.FluentUI/js/initializersLoader.webview.js"></script>
    <script src="_framework/blazor.webview.js"></script>
```
_There is no need to include `initializersLoader.windows.js` file as it is included in the library_

Getting this when running the app andclicking the switch:
<img width="425" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/009c62a8-dd4e-4fd7-a21e-3ff699f04679">
i.e. breakpoint in setter is hit...
