### ISSUE TITLE
docs: fix dialogue service code examples not showing C# method bodies

### ISSUE THREAD

**Issue by ApacheTech** [microsoft/fluentui-blazor#662]
# 🙋 Documentation Request

Within pages that show how to use the various dialogue service features, such as [the MessageBox](https://www.fluentui-blazor.net/MessageBox), the Razor code only shows the `onclick` call, but not the C# for the call handler.

For example:

```csharp
@inject IDialogService DialogService

<FluentStack>
    <FluentButton @onclick="@ShowSuccessAsync" Appearance="Appearance.Accent">Success</FluentButton>
    <FluentButton @onclick="@ShowWarningAsync" Appearance="Appearance.Accent">Warning</FluentButton>
    <FluentButton @onclick="@ShowErrorAsync" Appearance="Appearance.Accent">Error</FluentButton>
    <FluentButton @onclick="@ShowInformationAsync" Appearance="Appearance.Accent">Information</FluentButton>
    <FluentButton @onclick="@ShowConfirmationAsync" Appearance="Appearance.Accent">Confirmation</FluentButton>
    <FluentButton @onclick="@ShowMessageBoxLongAsync" Appearance="Appearance.Accent">Long message</FluentButton>
    <FluentButton @onclick="@ShowMessageBoxAsync" Appearance="Appearance.Accent">Custom message</FluentButton>
</FluentStack>
```

There is nowhere that shows the method bodies for `ShowSuccessAsync`, `ShowWarningAsync`, etc.

## 💁 Possible Solution

In the past, an "Additional C#" link has been available, to show the code-behind, or a "C#" tab, that does the same. This would be handy, to show a full working example, end-to-end.

**Comment by vnbaaij** [comment]
It seems the additional C# files are not being shown because of some changes we made in the demo component. Will fix that!
