### ISSUE TITLE
v3.0.0 IIS debugging/deployments 'Failed to load resource'

### ISSUE THREAD

**Issue by joecuevasjr** [microsoft/fluentui-blazor#668]
# 🐛 Bug Report

In Microsoft.Fast.Components.FluentUI 3.0.0 and Microsoft.Fast.Components.FluentUI.Icons 3.0.0:  
Debugging on or deploying to IIS is not loading components correctly. Kestral and IIS Expresss debugging works just fine.

## 💻 Repro or Code Sample

My current Program.cs has the required code setup:
````csharp
builder.Services.AddHttpClient();
builder.Services.AddFluentUIComponents(options =>
{
    options.HostingModel = BlazorHostingModel.Server;
});
````

## 🤔 Expected Behavior

In Microsoft.Fast.Components.FluentUI 3.0.0-RC.1 and Microsoft.Fast.Components.FluentUI.Icons 3.0.0-preview.5, deploying to IIS worked correctly. It should work with GA releases too.

## 😯 Current Behavior

I get this error in chrome: 
![image](https://github.com/microsoft/fluentui-blazor/assets/82356181/7c7dc0b6-6667-45a9-9694-d928745c9379)

## 💁 Possible Solution

Adding this to my Layout.cshtml seems to resolve the issue:
 <script type="module" src="https://cdn.jsdelivr.net/npm/@@fluentui/web-components@2.5.16/dist/web-components.min.js"></script>

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Chrome
* .NET: NET 7, Blazor Server

**Comment by dvoituron** [comment]
Could you give us more details about this loading problem? For example, could you take a screenshot like this one?

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/915f6bb6-3284-4f7c-bca5-663dd4d232c8)

**Comment by joecuevasjr** [comment]
@dvoituron 

Here's the failing call on v3.0.0
![image](https://github.com/microsoft/fluentui-blazor/assets/82356181/0b3c311b-e6d7-48eb-9a3e-567c63b82cbe)

And here's the successful call on v3.0.0-RC.1
![image](https://github.com/microsoft/fluentui-blazor/assets/82356181/318f97c8-3bed-4979-8fdf-58f35d8bde3c)

**Comment by vnbaaij** [comment]
Looking at the redacted parts, it seems you ar missing a  `<base href="/{sitename}" />` tag in your page (`index.html` or `_host.cshtml`)

**Comment by joecuevasjr** [comment]
I have it set. In v2.4.2 and v3.0.0-RC.1 it picks up the appropriate IIS path with the following in my _Layout.chstml:  `<base href="~/" />`

**Comment by vnbaaij** [comment]
I've found the error. There is a difference in how the script is being included. It will be reverted to the previous method with the next update (3.0.1). Should be out soon

**Comment by joecuevasjr** [comment]
Thanks @vnbaaij!
