### ISSUE TITLE
docs: add DataGrid PropertyColumn Align Left/Right => Start/End in Upgrade Guide

### ISSUE THREAD

**Issue by Lindsay-Mathieson** [microsoft/fluentui-blazor#670]
# 🙋 Documentation Request

When upgrading from FluentUI 2 to 3, the DataGrid PropertyColumn Align enum now uses "Start/End" in place of "Left/Right"

## 💁 Possible Solution

Mention this in the Upgrade Guide:
https://www.fluentui-blazor.net/UpgradeGuide

Side Note: The new components look awesome! Looking forward to making use of them, was especially missing label and a Grid Layout.

**Comment by vnbaaij** [comment]
Docs have been updatet.

Markdown files are being cached in the browser. If you do not see the updates, go into developer tools and delete the cache for the component:
<img width="213" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/9a6f38a0-790d-4bf0-a423-87eaf5e78fa8">

**Comment by Lindsay-Mathieson** [comment]
Thanks
