### ISSUE TITLE
docs: Add Installation of Icons/Emojis Package to Upgrade Guide

### ISSUE THREAD

**Issue by Lindsay-Mathieson** [microsoft/fluentui-blazor#671]
# 🙋 Documentation Request

When upgrading from 2.x => 3.x and using FluentIcon or FluentEmoji, the relevant nuget package needs to be installed before the project will build

## 💁 Possible Solution

Mention installing the "Microsoft.Fast.Components.FluentUI.Icons" and "Microsoft.Fast.Components.FluentUI.Emojis" nuget packages in:
* https://www.fluentui-blazor.net/UpgradeGuide

**Comment by vnbaaij** [comment]
Docs have been updatet.

Markdown files are being cached in the browser. If you do not see the updates, go into developer tools and delete the cache for the component:
<img width="213" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/9a6f38a0-790d-4bf0-a423-87eaf5e78fa8">

**Comment by Lindsay-Mathieson** [comment]
Thanks
