### ISSUE TITLE
fix: nav menu groups can be selected without action/href

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#675]
# 🐛 Bug Report

The indicator of a selected nav menu item jumps to non-selectable elements like `FluentNavMenuGroup`s without href/custom action and back to the actual selected element, when the groups are clicked.

## 🤔 Expected Behavior

`FluentNavMenuGroup`s without rhef/custom action should not be selectable. The indicator for selected elements should remain on the selected element, when a nav group element is clicked.

## 💁 Possible Solution

Maybe add a parameter to nav items to prevent them from being selectable.

**Comment by vnbaaij** [comment]
The `FluentNavMenuGroup` is basically a 'dressed-up' <fluent-tree-item>. Clicking and selecting such an item and raising a custom ('selectchanged') event for that is done on the web component side and is out of our control. Changing this would require a change in the way the <fluent-tree-item>works. You can raise an issue in the fluentui web components repo but I think it will take a while to see such a change being implemented (if at all).

 Only thing we can do on 'our' side (which we do already) is to detect the invalid action and revert it.
