### ISSUE TITLE
fix: FluentOverflow not working correctly

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#677]
# 🐛 Bug Report

The `FluentOverflow` or more specifically the tooltip/OverflowTemplate is not working as intended. When hovered, the items are not displayed in the tooltip.

## 💻 Repro or Code Sample

This behavior can be observed in the [official documentation](https://www.fluentui-blazor.net/Overflow):

![image](https://github.com/microsoft/fluentui-blazor/assets/143792830/271c3782-0bd0-4a11-9c9a-4a60fdd67c12)

## 🤔 Expected Behavior

The tooltip should be displayed correctly.

**Comment by dvoituron** [comment]
Fixed in the PR #678 and will be included in the next release.
