### ISSUE TITLE
fix: require is not defined in FluentCodeEditor

### ISSUE THREAD

**Issue by datvm** [microsoft/fluentui-blazor#690]
# 🐛 Bug Report

I wonder if the `FluentCodeEditor` needs any special setup because when adding it, I immediately receive this error:

```
fail: Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
      Microsoft.JSInterop.JSException: require is not defined
      ReferenceError: require is not defined
          at Module.monacoInitialize (https://localhost:44397/_content/Microsoft.Fast.Components.FluentUI/Components/CodeEditor/FluentCodeEditor.razor.js:4:5)
          at https://localhost:44397/_framework/blazor.webassembly.js:1:3337
          at new Promise (<anonymous>)
```

The library that causes the error is this:

![image](https://github.com/microsoft/fluentui-blazor/assets/6388546/1976e6af-c1fa-4a5c-8c85-7a3a05c85eae)

Do I need to add `loader.min.js` somehow?

## 💻 Repro or Code Sample

Simply use `FluentCodeEditor`:

```html
<FluentCodeEditor Language="csharp"></FluentCodeEditor>
```

* OS & Device: Windows 11 Pro
* Browser Microsoft Edge
* .NET and FAST Version 3.0.0

**Comment by vnbaaij** [comment]
Hi,
Please see https://github.com/microsoft/fluentui-blazor/blob/dev/examples/Demo/Client/wwwroot/index.html#L52-L55 for how it is set up in the demo site.
I need to check what is automatically being done by the component already and if we need to add anything to that or if we need to document extra steps needed.

**Comment by vnbaaij** [comment]
Ok, looked at this a bit deeper. You need to include 1 script in your `index.html`/`_Layout.cshtml`. Add:
```
<script src="_content/Microsoft.Fast.Components.FluentUI/lib/monaco-editor/min/vs/loader.min.js"></script>
```
**before** the line where the Blazor script is being added and the FluentCodeEditor should work as expected.

I'll add this to the component's documentation page.

**Comment by datvm** [comment]
Yep, can confirm it works after adding that reference.

**Comment by datvm** [comment]
@vnbaaij  Hi, now that I integrate it into my project, I realize it would stop working without the other 2 lines as soon as I add binding:

```html
<FluentCodeEditor @bind-Value="markdown" @bind-Value:after="@(() => ConvertCode(true))"
                  Language="markdown">
</FluentCodeEditor>
```

> Cannot read properties of undefined (reading 'setValue')

It happens if I remove any of these line:

```html
<script>require.config({ paths: { 'vs': '_content/Microsoft.Fast.Components.FluentUI/lib/monaco-editor/min/vs' } });</script>
<script src="_content/Microsoft.Fast.Components.FluentUI/lib/monaco-editor/min/vs/editor/editor.main.js"></script>
```

The reason is this code is being run:

![image](https://github.com/microsoft/fluentui-blazor/assets/6388546/ef611922-bea2-4125-aba2-962b4b9c79f6)

`container.editor` is null because the code above runs before this one:

![image](https://github.com/microsoft/fluentui-blazor/assets/6388546/a5d7449f-562a-491a-b0e4-a450c4f0b02a)
