### ISSUE TITLE
feat: add callback functions to Dialogue Service `Show...[Async]` methods.

### ISSUE THREAD

**Issue by ApacheTech** [microsoft/fluentui-blazor#693]
# 🙋 Feature Request

I've hit an issue, whereby I would like to display an error, within a dialogue box, and then when the user presses "Ok", I would like to perform an action; in my case, navigating away from the page. Currently, the page navigates away as soon as the dialogue box appears; without waiting for the user to click "Ok".

## 🤔 Expected Behavior

```csharp
private async Task ShowErrorAndNavigateAwayAsync()
{
    await Dialogue.ShowErrorAsync("An error has occured.", "My Application");
    
    // This should not be triggered, until the user clicks "Ok" on the error message.
    NavigationManager.NavigateTo("/other-page");
}
```

## 😯 Current Behavior

You can get a "similar" result to expected, by using a message box... but there's no way to hide the secondary button.

```csharp
private async Task ShowErrorAndNavigateAwayAsync()
{
    var mbox = await Dialogue.ShowMessageBoxAsync(new DialogParameters<MessageBoxContent>()
    {
        Content = new()
        {
            Intent = MessageBoxIntent.Error,
            Title = "My Application",
            Message = new MarkupString("An error has occured."),
            Icon = new Icons.Regular.Size24.ErrorCircle(),
            IconColor = Color.Error,
        },
        TrapFocus = true,
        Modal = true,
    });
    await mbox.Result;
    NavigationManager.NavigateTo("/other-page");
}
```

## 💁 Possible Solution

Ideally, all dialogue boxes should include a callback option. Within each of the box types, there are general use cases whereby you would want to wait for user feedback, before continuing with the code flow. This is especially the case when delaying page navigation.

In this example, `ShowErrorAsync` is treated the same as `ShowMessageBoxAsync` within it's usage.

```csharp
private async Task ShowErrorAndNavigateAwayAsync()
{
    var dialogue = await Dialogue.ShowErrorAsync("An error has occured.", "My Application");
    await dialogue.Result;
    NavigationManager.NavigateTo("/other-page");
}
```

Another simple fix would be to add `ShowPrimaryActionButton`, and `ShowSecondaryActionButton` parameters to the `DialogParameters<>` options, so we can have a `ShowMessageBoxAsync` with only one button.

## 🔦 Context

**What are you trying to accomplish?**

I want to show the user an error message, and then navigate away from the page.

**How has not having this feature affected you?**

The page navigation happens immediately, ignoring the fact that a modal dialogue box is on the screen, giving the user important information.

**What alternatives have you considered?**

I am currently using the MessageBox workaround that I have detailed above, however, from a UX standpoint, this is not ideal. There are redundant buttons on the screen that I have no control over.

**Comment by vnbaaij** [comment]
For the use case you describe, the `MessageBox`  should be the way to go, not a general `Dialog`

Your workaround can be made to do exactly what you want quite easily...In the `DialogParameters` you just need to set the `SecondaryAction` to `null`. If the text is null, the button will not be displayed

Adding the callback to the other `MessageBox` calls is probably not a bas idea. We'll see if we can do that for a next release.

**Comment by vnbaaij** [comment]
Close as completed
