### ISSUE TITLE
feat: provide reference to TGridItem in OnRowFocus/OnCellFocus

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#695]
# 🙋 Feature Request

The `OnRowFocus` event of the `FluentGrid` provides only a reference to the row's HTML element ID and a row index. However, to implement custom selecting behavior, a reference to a row's TGridItem is required. The `TGridItem` should be stored in and be accesible through a `FluentDataGridRow`.

## 🤔 Expected Behavior

As `OnRowFocus` provides a `FluentDataGridRow` through its event callback, the row should hold a public reference to a `TGridItem`.

**Comment by vnbaaij** [comment]
PR #700 is merged in. Will be in next version (no ETA...)

Thanks for your contribution!!
