### ISSUE TITLE
fix: FluentButton does not get enabled when its parent fieldset is not disabled any more

### ISSUE THREAD

**Issue by datvm** [microsoft/fluentui-blazor#698]
# 🐛 Bug Report

When a `FluentButton` is inside a `fieldset`, all of them get disabled when that `fieldset` is disabled which is correct. However when the `fieldset` is no longer disabled, the `FluentButton`s are still disabled.

![image](https://github.com/microsoft/fluentui-blazor/assets/6388546/26528077-7bc3-432d-8f94-bbc16aec494d)

## 💻 Repro or Code Sample

```html
@page "/test"

<fieldset disabled="@(working)">
    <p>
        <FluentButton OnClick="WorkAsync">
            Work
        </FluentButton>

        <FluentButton>
            Button for Testing
        </FluentButton>

        <button>Button for Testing</button>
    </p>
</fieldset>

<p>
    <button disabled="@(working)">Testing Button</button>
</p>


@code {
    bool working;

    async Task WorkAsync()
    {
        working = true;
        StateHasChanged();

        await Task.Delay(1000);
        working = false;
    }
}
```

## 🤔 Expected Behavior

The `FluentButton`s should be enabled once the fieldset is not disabled anymore.

## 😯 Current Behavior

The `FluentButton`s are still disabled. The standard `button`s are for confirming that the code works as intended and they get enabled.

## 💁 Possible Solution

Unknown, I tried adding extra `StateHasChanged` called too but it doesn't work.

## 🌍 Your Environment

* OS & Device: Windows 11 Pro
* Browser Microsoft Edge
* .NET and FAST Version 3.0.0

**Comment by dvoituron** [comment]
## Problem
It seems to be a bug in the `fluent-button` web component used:
1. By adding `disabled` to the **fieldset**, **fluent-buttons** are automatically set to Disabled.
2. But when removing `disabled` from the **fieldset**, the reverse operation of re-enabling the **fluent-buttons** doesn't work.

## Solution
A solution is to use the `Disabled="@working"` attribute on all **FluentButtons**.

```xml
<fieldset disabled="@working">
    <p>
        <FluentButton OnClick="WorkAsync" Disabled="@working">
            Work
        </FluentButton>

        <FluentButton Disabled="@working">
            Button for Testing
        </FluentButton>

        <button>Button for Testing</button>
    </p>
</fieldset>
```

**Comment by vnbaaij** [comment]
I recreated the bug on the FAST repo to see if we can get a fix from there: https://github.com/microsoft/fast/issues/6831

**Comment by vnbaaij** [comment]
Closing this. Work around provided, formal solution will come from web-components script

**Comment by vnbaaij** [comment]
There is not much to update on. The fix you linked is for the next version of the web components. If it's not possible (as far as I know) to backport that to v2.

**Comment by Mike-E-angelo** [comment]
Thank you for that update @vnbaaij and the further context.  I am particularly interested in what you meant by this:

> Work around provided, formal solution will come from web-components script

Are you saying that since this can no longer be backported this is no longer possible?

**Comment by vnbaaij** [comment]
Most probably not in our current version of the library. But will be fixed on the Blazor side when we move to the web components v3 with the next major version.

**Comment by Mike-E-angelo** [comment]
OK great thank you very much for that update @vnbaaij it is greatly appreciated, along with all your efforts here. 🙏
