### ISSUE TITLE
fix: Missing usings in WebAssembly Project template

### ISSUE THREAD

**Issue by agriffard** [microsoft/fluentui-blazor#703]
As in #701, The usings removed in the PR https://github.com/microsoft/fluentui-blazor/pull/688/files#diff-427e533447cbc204767f3d4883d0120b89b60188d71b09c5fdcb53eea997ed25 are required in Program.cs of the WebAssembly Project template:

```
using FluentUIBlazorWebAssemblyApp;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Fast.Components.FluentUI;
```

I let you fix it if you don't mind.

**Comment by vnbaaij** [comment]
Fixed in v3.0.1 of the Template package.

**Comment by agriffard** [comment]
I only see https://www.nuget.org/packages/Microsoft.Fast.Templates.FluentUI/3.0.0 on Nuget and it does not seem to be fixed on the current Program.cs of the Wasm project template.

https://github.com/microsoft/fluentui-blazor/blob/386d500996f148d62e098606317d8497dfb98e9b/src/Templates/Projects/FluentUIBlazorWebAssemblyApp/Program.cs#L1

**Comment by vnbaaij** [comment]
Hold on :) pipeline is still running, then it needs to be uploaded to NuGet and then NuGet needs to index it

And changes are done on `dev` branch: 
https://github.com/microsoft/fluentui-blazor/blob/dev/src/Templates/Projects/FluentUIBlazorWebAssemblyApp/Program.cs
