### ISSUE TITLE
fix: Nav Menu Group expanding/collapsing continuously in FluentNavMenu

### ISSUE THREAD

**Issue by gkizior** [microsoft/fluentui-blazor#705]
# 🐛 Bug Report

#### BACKGROUND
I am using FluentNavMenu as a 'sidebar' nav menu in my Blazor Server application. Each `FluentNavMenuLink` is wrapped within a `FluentNavMenuGroup`. 

#### HOW ISSUE WAS FOUND
Each `FluentNavMenuLink` routes to a page within the app using the `Href` param. Some of these pages load somewhat slower than others (1-3 seconds). This is where I noticed the issue. For pages that loaded slower, sometimes I found myself clicking in the NavMenu again (specifically clicking a `FluentNavMenuGroup` to collapse a nav grouping) before the page finished loading. This sometimes caused the NavMenuGroup to continuously expand/collapse, and flash the "selected" indicator on both the NavMenuGroup and NavMenuLink. I found that to easily reproduce the issue all I had to do was click any NavMenuLink and then rapidly click its parent NavMenuGroup many times.

## 💻 Repro or Code Sample

I created a fresh Blazor Server app and only included the following on the `Index.razor`. 

```razor
<FluentNavMenu Collapsible=true Width=300>
    <FluentNavMenuGroup InitiallyExpanded=true>
        <h6>Menu Group</h6>
        <FluentNavMenuLink Icon="new Icons.Regular.Size20.Money()" Href="/" Text="Menu Item 1" />
        <FluentNavMenuLink Icon="new Icons.Regular.Size20.Key()" Href="/" Text="Menu Item 2" />
    </FluentNavMenuGroup>
</FluentNavMenu>
```

#### Steps to reproduce
1. Click on "Menu Item1"
2. Rapidly click on "MenuGroup" (the text or the area - not the expand/collapse arrow)

## 🤔 Expected Behavior

`FluentNavMenuGroup` should not continuously expand/collapse. Clicking the MenuGroup quickly should not cause the component to misbehave. 

## 😯 Current Behavior

This video shows what I mean by 'expanding/collapsing continuously'. I recorded after following the reproduction steps and am hands off mouse/keyboard during the whole recording.

https://github.com/microsoft/fluentui-blazor/assets/8591342/7673945c-1128-4150-94f4-48df1fe05960

## 💁 Possible Solution

Unknown. I was able to reproduce in a fresh blazor server app and within the `Index.razor`. No other changes other than my code sample.

## 🔦 Context

See "HOW ISSUE WAS FOUND"

## 🌍 Your Environment

* Issue found on my machine, but also has same behavior in our deployed environment Azure Container App
* OS & Device: Windows 11
* Browser Microsoft Edge
* .NET 7 and Microsoft.Fast.Components.FluentUI Version 3.0.1

**Comment by vnbaaij** [comment]
This issue also occurs with the `FluentNumberField` UP/Down arrows icw Blazor Server. It is caused by the 'lag' in clearing up the SignalR queue from all the events that get send when clicking rapidly. You probably see it getting to a normal/steady state if you just let it run for a while. 
It is definitely not a behavior we want but I do not have a solution for it at the moment. I'll see if I can get someone from the Blazor team to take a llok butthey are pretty busy with getting .NET 8 done so might take a bit of time

**Comment by vnbaaij** [comment]
In v3.2 we are introducing new `FluentNavMenu`, `FluentNavGroup` and `FluentNavLink` components based on the standard Blazor `NavLink` and which does not utilize the TreeView component. 

Take a look at https://preview.fluentui-blazor.net to see it in action as the NavMenu there is already using the new component!.
Appearance is 99.9% the same and migrating to the new menu is pretty easy (we supply an [upgrade guide](https://preview.fluentui-blazor.net/UpgradeGuide)).

**Comment by gkizior** [comment]
@vnbaaij When is v3.2 releasing? I dont see it

**Comment by vnbaaij** [comment]
Building, documenting and uploading as we speak. Just a bit more patience please.

**Comment by gkizior** [comment]
I made this change. Functionally it fixed my issue!

One question though... it seemed to clear out the font/text styling that the previous component had. How can I get the same font/text style that is on the demo site?

New
![image](https://github.com/microsoft/fluentui-blazor/assets/8591342/5cc338f1-b23c-4621-bdb1-ab0eaffcf0e2)

Old
![image](https://github.com/microsoft/fluentui-blazor/assets/8591342/3ecd8ff3-0510-4bbb-8a77-e5d8aae6247b)

**Comment by vnbaaij** [comment]
For the new groups, the default `Title` parameter will render the same as the NavLinks. You can change that by using the `TitleTemplate` parameter in place of the `Title` (or use both as in the sample for 'Item 3'.

If you use `TitleTemplate`, the `FluentNavLinks` and `FluentNavGroups` beneath that item need to be in a `ChildContent` tag
