### ISSUE TITLE
fix: [Browser developer tools not opening with FluentCodeEditor] in [Blazor Server App]

### ISSUE THREAD

**Issue by v-rajesha** [microsoft/fluentui-blazor#707]
Hi Team,

We used FLuentUI 3.0.1 in Blazor Server Application.

We are using FluentCodeEditor as mentioned in demo site  [https://www.fluentui-blazor.net/CodeEditor](url) and observed below issue when we open browser developer tools.

- **Page is navigating to below blank page. Can you help us on this?**

<img width="932" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/128696687/97671b93-eea8-4be3-9254-1bf4b5813929">

- **do we have option to remove preview in FLuentCodeEditor control?**

<img width="497" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/128696687/6d230284-a810-47b9-8a02-0dd06cb65183">

Help on this will be highly appreciated!

Thanks,
Rajesh

# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Not seeing this when running the demo site in Server side Blazor (you can easily run this yourself bij just cloning the repo and run the server denk from VS)

We don't offer functionality to change any aspects of the editor. Those night be added at a later date. If you need a more extended version of the Monaco editor, I can recommend the excellent https://github.com/serdarciplak/Blazor Monaco package

**Comment by V-AATARE** [comment]
https://github.com/serdarciplak/Blazor this link is not opening.
Hide preview pane is not possible, but is there any way to hide the line numbers?
Thanks

**Comment by vnbaaij** [comment]
Sorry, correct link is https://github.com/serdarciplak/BlazorMonaco

No, hiding line numbers is also not an option atm
