### ISSUE TITLE
fix: FluentButton in slot attribute when loading is true

### ISSUE THREAD

**Issue by alderic** [microsoft/fluentui-blazor#708]
# 🐛 Bug Report

slot attribute when FluentButton in Loading=true not wrok, coz button wrapped by span

## 💻 Repro or Code Sample

```
 <FluentToolbar  style="width:100%">
    <FluentButton slot="end"  IconEnd="@(new Icons.Regular.Size20.Alert())" Loading="true"></FluentButton>
</FluentToolbar>
```

## 🤔 Expected Behavior
Button in end slot

## 😯 Current Behavior
button in default position

## 💁 Possible Solution
one more span wrap
```
    <FluentToolbar style="width:100%">
        <span slot="end">
            <FluentButton  IconEnd="@(new Icons.Regular.Size20.Alert())" Loading="true"></FluentButton>
        </span>
    </FluentToolbar>
```

## 🌍 Your Environment

* OS & Device: Linux
* Browser Microsoft Edge, Google Chrome, Mozilla FireFox
* .NET 7 and FAST 3.0.1

**Comment by vnbaaij** [comment]
This won't work because the slot attribute, when added in the Fluent button, will be rendered in the Fluent button itself. Like you say, there needs to be something surrounding the button (like your span) to make it work.

As this is a rather specific way to use a button, we will not add that 'wrapping" to the button component itself. When needed you can do this manually.

**Comment by alderic** [comment]
You probably don't know how your fluentbutton works, when you set the Loading attribute to true, a span-wrapper is already added. 
![notmyspan](https://github.com/microsoft/fluentui-blazor/assets/19504621/0b314b97-8e55-4024-9158-009a3e169cca)

I.e. when using the loading attribute, the slot attribute in this component is useless, and I will have to, as always, sculpt an additional crutch

**Comment by vnbaaij** [comment]
This tone of commenting and communication is not appropriate nor appreciated. Consider this as a warning. Next time I will block you.

Now back to the issue. I believe you can still have a span with a slot enclosing the loader span. We need that span to blur the button underneath and that is the only situation when we add a span. Other option might perhaps be to use a tiny piece of JS interop to add the slot attribute to the loader span?
