### ISSUE TITLE
fix: [FluentSelect Change Event returns only first item in selected options when multi= true]

### ISSUE THREAD

**Issue by madcoda9000** [microsoft/fluentui-blazor#713]
# 🐛 Bug Report

When using a FluentSelect with property Multiple=true the onchange event callback returns the first item in @bind-selectedoptions list.

## 💻 Repro or Code Sample

Razorfile.razor

```
<FluentSelect TOption="IdentityRole" Position="SelectPosition.Below"
                                        Open="false"
                                        Items="@AllRoles"
                                        Id="roles-listbox"
                                        Multiple="true"
                                        OptionValue="@(p => p.Name!.ToString())"
                                        OptionText="@(p => p.Name)"
                                        @bind-Value="@SelectedValue"
                                        @bind-SelectedOptions="@SelectedOptions" 
                                        @onchange="(args)=>SelOptionsChange(args)" "/>

@code {
    private IEnumerable<IdentityRole>? SelectedOptions;
    private IEnumerable<IdentityRole>? AllRoles {get; set;}
    private string? SelectedValue;

    protected override async Task OnInitializedAsync() {
        var res = await _roles.GetRoles(new PagedPostModel{ page=1, pageSize=1000, searchValue="", });
        if(res.Success) {AllRoles = res.Data!.PagedList;}
   }

    private async Task SelOptionsChange(ChangeEventArgs e) {
        Console.WriteLine(e.Value);
    }
}
```

## 🤔 Expected Behavior

I would expect that the event callback returns the clicked value of the selectedoptions list.

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/25504739/9402567e-948e-4ad8-a493-0812febb8449)

## 🔦 Context

it is neccessary to detect which item is clicked by the user to avoid selecting items by the user, that should not be selected together. For ex. I want to avoid that the user can select the admin and the user role at the same time.

## 🌍 Your Environment

* OS & Device: [Windows] on [PC]
* Browser [Google Chrome]
* .NET [7.0] and FAST Version [3.0]

**Comment by vnbaaij** [comment]
Did you look at https://www.fluentui-blazor.net/Select#multiple items? I'm showing all the selected options there.

**Comment by madcoda9000** [comment]
The problem is not that it is not nshowing all selected options.

This is working as expected:

`<span>SelectedOptions:&nbsp;@(String.Join(", ", SelectedOptions!.Select(i => i.Name)))</span>`

The problem is, that if i define a onchange method and assign that to the FluentSelect onchange event, the callback value returns always the first item in the selected options list of the FluentSeleect and not the clicked item of the FluentSelect.

Example:
```
<FluentSelect TOption="IdentityRole" Position="SelectPosition.Below"
                                        Open="false"
                                        Items="@AllRoles"
                                        Id="roles-listbox"
                                        Multiple="true"
                                        OptionValue="@(p => p.Name!.ToString())"
                                        OptionText="@(p => p.Name)"
                                        @bind-Value="@SelectedValue"
                                        @bind-SelectedOptions="@SelectedOptions" 
                                        @onchange="(args)=>SelOptionsChange(args)"
                                        style="box-shadow:none !important;"/>

private async Task SelOptionsChange(ChangeEventArgs e) {
        Console.WriteLine(e.Value);
    } 
```

If, as in this case, @AllRoles contains a list of IdentityRole (Admin, User, IT-Adm) and @SelectedOptions contains the IdentityRole Admin, then everytime i click on a item in the list e.value returns the IdentityRole Admin (which is the first item in selcted options).

I would expect that e.Value returns the clied item.

**Comment by vnbaaij** [comment]
Ah, sorry misunderstood your question. Unfortunately the underlying web component does not return the clicked item when multiple selection is enabled. I believe there is an issue raised for it in the Fast repo already. If not, maybe you can raise one there?

**Comment by madcoda9000** [comment]
hmmm, ok. thx. Just a questions. Is there any timeline when the FluentListbox MultiSeclect feature will beready?

**Comment by vnbaaij** [comment]
No, no time line for that. I think it was also dependent on web component functionality that is not there yet. Will take a look though on how fast along it is already. I know of one other implementation that is working so maybe we can copy some code from there

**Comment by madcoda9000** [comment]
oh, ok. Then it seems like i have to do it the old shool way with checkboxes and javascript validation. Anyway, it would be cool if fluentui blazor would have one working multi listbox component.

One last question. Is there any posibility to remove the dropshadow by css from the FluentSelect in Multi mode?

**Comment by dvoituron** [comment]
That's not an answer to your issue. But in some days, I'll publish a new component: an Autocomplete Components with a multi-select option. 

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/8b1fb8b5-8a44-47f3-9ac1-8b5927ecfb54)
