### ISSUE TITLE
feat: add Header,Footer,Content to Dialog

### ISSUE THREAD

**Issue by ehsangfl** [microsoft/fluentui-blazor#715]
At first, thanks everyone to everyone for releasing version 3 and great improvements. 
but I think there is more complexity for dialog component. 
I suggest to add three property to dialog, so this is becomes more simpler to use
something like this

[Parameter]
public RenderFragment Header{get;set;}

[Parameter]
public RenderFragment Content{get;set;}

[Parameter]
public RenderFragment Footer{get;set;}

so we could add everything to header, content and footer of dialog
BR

**Comment by vnbaaij** [comment]
You can already completely customize what is shown in Dialog content. See https://www.fluentui-blazor.net/#dialog-content

Header and Footer are underway. See PR #717
