### ISSUE TITLE
fix: [DataGrid filtering not working] in [Blazor Server App]

### ISSUE THREAD

**Issue by v-rajesha** [microsoft/fluentui-blazor#719]
Hi Team, 

We used Fluent UI 3.0.1 version in Blazor server application.

DataGrid filtering working fine in local environment but not working on server after code deployment.
Observed below error in browser developer tools and logs.

<img width="944" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/128696687/41516740-33c2-461c-82b9-4ac9acd76a8d">

- **error log**
Microsoft.JSInterop.JSException:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at System.Threading.Tasks.ValueTask`1.get_Result (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at Microsoft.JSInterop.JSRuntime+<InvokeAsync>d__16`1.MoveNext (Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at Microsoft.Fast.Components.FluentUI.FluentSearch+<OnAfterRenderAsync>d__42.MoveNext (Microsoft.Fast.Components.FluentUI, Version=3.0.23247.4, Culture=neutral, PublicKeyToken=null: /_/src/Core/Components/Search/FluentSearch.razor.cs:83)    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at Microsoft.AspNetCore.Components.RenderTree.Renderer+<GetErrorHandledTask>d__71.MoveNext (Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

Help on this will be highly appreciated!

Thanks,
Rajesh

# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
The image of the error shows it goes wrong in `FluentSearch`, not Grid?

It is impossible to help here without more context or source code to look at. Error log is not helpful here

**Comment by vnbaaij** [comment]
Again, this does not give me information enough to determine what the problem is. 

What are you seeing when you look at the 'Sources' tab? Are other scripts from the library being found/loaded? 
This is what I see when looking at the demo site 
<img width="204" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/bae6672c-e76d-44ca-9cf4-dc2ca2062c9b">

Have you tried loading the script by just entering the URL in a browser? What is you base tag set to? What server is the site running on?

**Comment by v-rajesha** [comment]
Hi @vnbaaij,

Thanks for your help, we have identified the root cause of the issue. we made change on server to unblock the file. Its working now.

Thanks,
Rajesh

**Comment by vnbaaij** [comment]
> one quick question, do we have option to make FluentCodeEditor as non-editable?

No, there is no setting for that.
