### ISSUE TITLE
feat: add selection to/in datatable

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/fluentui-blazor#722]
# 🙋 Feature Request

DataTable should include row selection support

## 🤔 Expected Behavior

It should have a SelectedRowItem and SelectedRowIndex properties, and a SelectionChanged Event.

Selecting a row should set those properties, and fire the event. Similarly if the selection is removed, then fire the event and set the properties to null. 

## 😯 Current Behavior

Remove the amount of code needed by the application.

**Comment by LuohuaRain** [comment]
https://github.com/microsoft/fluentui-blazor/issues/173
