### ISSUE TITLE
feat: add NoItemsContent to/in DataGrid

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/fluentui-blazor#723]
# 🙋 Feature Request

Include a content property that will be shown in the datagrid when no items are available in the data source.

## 🤔 Expected Behavior

When the items are empty or null, then this placeholder should be shown in the body area of the datagrid. Its should replace the content of the table (TBD for keeping the headers). The paging etc should be retained.

## 😯 Current Behavior

Today you have to conditionally show/hide the grid, and replace with your own content, that doesn't have the same size etc. The discontinuity is high between when there is content and when there isn't. This feature would make that less significant.

**Comment by vnbaaij** [comment]
Something like this:

<img width="687" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/2d177009-664e-4b0c-86d0-2b08d826b5cd">

Implementing this as follows:
- Add parameter `EmptyContent` (of type `RenderFragment`)  (name chosen to stay in line with new parameter added on standard `Virtualize` component)
- Add a class to the isolated `FluentDataGrid.razor.css`:
```
::deep .empty-content {
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: 600;
}
```
- The `FluentDataGrid` component will render this when Items/ItemsProvider is empty/has a count of 0:
```
 <div class="empty-content">
         @if (EmptyContent is null)
          {
                 @("No data to show!");
          }
          else
          {
                  @EmptyContent
           }
</div>
``` 
This allows you to specify your own text and/or layout for when there is no content or uses a sensible default when none is provided.
- Only caveat is that if you specify your own content for the `EmptyContent` parameter, the `PropertyColumn`/`TemplateColumn` definitions need to be wrapped in a `ChildContent` element, i.e.:
```
<FluentDataGrid Style="height: 400px;" Items=@items Virtualize="true" ItemSize="32" GridTemplateColumns="1fr 1fr 1fr 1fr">
        <ChildContent>
            <PropertyColumn Property="@(c => c.Item1)" Sortable="true" />
            <PropertyColumn Property="@(c => c.Item2)" />
            <PropertyColumn Property="@(c => c.Item3)" Align="Align.Center" />
            <PropertyColumn Property="@(c => c.Item4)" Align="Align.End" />
        </ChildContent>
        <EmptyContent>Nothing to see here!</EmptyContent>
    </FluentDataGrid>
```
