### ISSUE TITLE
fix: Combobox: Height Attribute not working as expected or my misunderstanding???

### ISSUE THREAD

**Issue by patelyahya** [microsoft/fluentui-blazor#736]
# 🐛 Bug Report
As provided in the documentation attribute Height in Combobox Component sets the height of the component or of the of the popup panel.
`
<FluentCombobox Height="5" Id="combobox-with-both-autocomplete" Autocomplete="ComboboxAutocomplete.Both" @bind-Value="@comboboxValue" TOption="string">
    <FluentOption>William Hartnell</FluentOption>
    <FluentOption>Patrick Troughton</FluentOption>
    <FluentOption>Jon Pertwee</FluentOption>
    <FluentOption>Tom Baker</FluentOption>
    <FluentOption>Peter Davidson</FluentOption>
    <FluentOption>Colin Baker</FluentOption>
    <FluentOption>Sylvester McCoy</FluentOption>
    <FluentOption>Paul McGann</FluentOption>
    <FluentOption>Christopher Eccleston</FluentOption>
    <FluentOption>David Tenant</FluentOption>
    <FluentOption>Matt Smith</FluentOption>
    <FluentOption>Peter Capaldi</FluentOption>
    <FluentOption>Jodie Whittaker</FluentOption>
</FluentCombobox>
`

## 😯 Current Behavior
No changes are seen on the screen and the popup panel's height is not shortened.
![image](https://github.com/microsoft/fluentui-blazor/assets/48586810/acd18d21-302e-4eee-9bd4-d330d0c79d86)

Blazor WASM .NET 7
Fluent UI 3.0.1

**Comment by dvoituron** [comment]
The `Height` property is associated to the [CSS height property](https://developer.mozilla.org/en-US/docs/Web/CSS/height). You must therefore define a unit after your value.

Example:
```xml
<FluentCombobox Id="combobox"
                Items="@Data.Hits"
                @bind-Value="@hit"
                Height="200px" />
```

This example come from the [FluentUI-Blazor.net Documentation](https://www.fluentui-blazor.net/Combobox)

**Comment by patelyahya** [comment]
Thanks a lot, seems working now.
