### ISSUE TITLE
fix: Embed the wwwroot directory and it's contents in order to create a single file executable

### ISSUE THREAD

**Issue by vncpetrov** [microsoft/fluentui-blazor#742]
# 🐛 Bug Report

Generating single-file executable not working when using _FluentUI_ library in _WPF Blazor_ application, which is an installation inconvenience. Also, this may be considered as a **security vulnerability** if someone changes the JS files inside the _wwwroot_ folder?

## 💻 Repro or Code Sample

1. [Create WPF Blazor application](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-7.0)
2. Import latest version of FluentUI library
3. Publish the project as single-file using the following command: `dotnet publish -r win-x64 --self-contained true -p:PublishSingleFile=true`

## 😯 Current Behavior
There's a _wwwroot_ folder next to the executable containing FluentUI assets:

![image](https://github.com/microsoft/fluentui-blazor/assets/20843160/63d31a13-91f1-4463-ba87-12227a4910ae)

![image](https://github.com/microsoft/fluentui-blazor/assets/20843160/239e1057-a302-4ba2-865a-9ca2a3a8880e)

## 🤔 Expected Behavior

Possibility to publish a WPF Blazor application (or any other BlazorWebView based application) as a single-file when using FluentUI library.

## 💁 Possible Solution

BlazorWebView itself has the ability to load and operate with embedded static files. However, in order for this to work when using FluentUI library, the _wwwroot_ files should be present before publishing/embedding them. The publishing step would first have to generate the wwwroot files before they could be embedded.

**Comment by vnbaaij** [comment]
Hi,

This is not an issue with the Fluent UI library, but more a general Wpf/Blazor problem, I believe.

I stopped after your step 1 of the repo steps, used your publish command and then copied the executable to a different location. If I then try to run the exe file, it does not start. It does start when run in the publish folder with all the other files present. At this point a `wwwroot` folder is already created in the output location (ie that comes with Blazor and not specifically from this library).

I suggest you raise an issue in the [aspnetcore repo](https://github.com/dotnet/aspnetcore) for this. Closing this for now as there is no action we can take at the moment.
