### ISSUE TITLE
Nav Manu not changing selection when navigating away to different area

### ISSUE THREAD

**Issue by timheuer** [microsoft/fluentui-blazor#743]
# 🐛 Bug Report

When you have a nav menu that has different Hrefs, they aren't updating when navigation is happening and changing URI.

For example in my main page if I have a link in the body that takes to /page2 and I have a nav menu item that is "Page 2" with Href="/page2" I would expect that when I click the body link and the view and address bar changes to include /page2 that the Nav Menu updates to select to the right nav item.

using v3 blazor with Blazor .NET 8

**Comment by vnbaaij** [comment]
Hi Tim,

I'm not seeing this in the demo site. For instance if I navigate to https://www.fluentui-blazor.net/DialogService, that page gets selected in the `NavMenu`. On that page there are links to other pages in the site like '/Dialog' and '/Panel'. Clicking those, I navigate there and both address bar change and item gets selected in the `NavMenu`

Is there any source we can look at to pinpoint the problem?

**Comment by vnbaaij** [comment]
Fixed in v3.1
