### ISSUE TITLE
fix: Button displayed above sticky header in FluentDataGrid

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#744]
# 🐛 Bug Report

A data grid with a sticky header doesn't work well with buttons in the grid. Buttons display above the sticky header instead of being hidden by it.

## 💻 Repro or Code Sample

```html
<div style="max-height: 600px; width: 100%; overflow-y: scroll;" class="StructuredLogsOverflow" tabindex="-1">
    <FluentDataGrid Class="StructuredLogsDataGrid" Virtualize="true" GenerateHeader="GenerateHeaderOption.Sticky" ItemSize="48" ResizableColumns="true" Items="@(_logEntries)" GridTemplateColumns="1fr 1fr 4fr 1fr 2fr 1fr">
        <PropertyColumn Title="Severity" Sortable="true" Property="@(context => context.Severity)" />
        <PropertyColumn Title="Timestamp" Sortable="true" Property="@(context => context.TimeStamp.ToLocalTime().ToLongTimeString())" />
        <PropertyColumn Title="Format" Property="@(context => context.Message)" />
        <PropertyColumn Title="Span" Property="@(context => context.SpanId)" />
        <PropertyColumn Title="Trace Id" Property="@(context => context.TraceId)" />
        <TemplateColumn>
            <FluentButton Appearance="Appearance.Hypertext"
                          OnClick="async() => await OnShowProperties(context)">View</FluentButton>
        </TemplateColumn>
    </FluentDataGrid>
</div>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/303201/afc4fc9a-28ea-4250-8b31-b3fe11d5e43b)

Note, I tried changing the button appearance to "Hypertext", but it was still a button. Is that another bug?

## 🤔 Expected Behavior

The "View" button is hidden when it scrolls out of view.

## 😯 Current Behavior

The "View" button is above the header when scrolling.

## 🌍 Your Environment

Windows
Chrome
.NET 8 RC2 daily build

**Comment by vnbaaij** [comment]
This is fixed in the next release (due this week)
