### ISSUE TITLE
fix: Value is not different from name in Combobox

### ISSUE THREAD

**Issue by MatejMa2ur** [microsoft/fluentui-blazor#749]
# 🐛 Bug Report

The Value in the inspect when looking on the Combo box contains the OptionName instead of OptionValue

## 💻 Repro or Code Sample

```C#

<FluentCombobox TOption="TopicDto"
                            Items="Topics"
                            OptionValue="t => t.Id.ToString()"
                            OptionText="t => t.Name" 
                            OptionSelected="t => t.Id.ToString() == SelectedTopicIdString"
                            Class="w-100"/>
                            
// Model:

public class TopicDto
{
    public Guid Id { get; set; }

    public string Name { get; set; } = null!;
}            
                
```

## 🤔 Expected Behavior

I am not able to retrieve the Id from the value of selected option 

## 😯 Current Behavior

It seems that currently it is using the name of selected option in value field
![image](https://github.com/microsoft/fluentui-blazor/assets/41269745/675b753d-ef90-40dc-bcdb-5865e2bcf1e0)

## 💁 Possible Solution

Maybe it is intended and a different way how to retrieve the value from the combobox

## 🔦 Context

I want to be able to do:

```C#
private string _TopicId;
    public string SelectedTopicIdString { get => _TopicId; set { _TopicId = value; UpdateQuestionSelectDto.TopicId = Guid.Parse(value); } }
```

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
A Combobox is designed to enable you to enter a value **which is not in the list** of predefined names. It is impossible to get the OptionVue for such an item because there isn't one

**Comment by MatejMa2ur** [comment]
Can you please than point me to which other component should I use?

**Comment by MatejMa2ur** [comment]
But than why I am able to set the OptionValue, when I am not able to retrieve it or use it in ComboBox

**Comment by vnbaaij** [comment]
In the soon to be released v3. 1 version you can use the autocomplete component. See https://preview.fluentui-blazor.net/Autocomplete

**Comment by vnbaaij** [comment]
> But than why I am able to set the OptionValue, when I am not able to retrieve it or use it in ComboBox

Because it shares a lot of functionality with the FluentLlistbox and FluentSelect

**Comment by MatejMa2ur** [comment]
Thank you very much for your help and answers, I will check out the new Autocomplete when it will come out.

**Comment by MatejMa2ur** [comment]
> > But than why I am able to set the OptionValue, when I am not able to retrieve it or use it in ComboBox
> 
> Because it shares a lot of functionality with the FluentLlistbox and FluentSelect and you need to supply a OptionValue for the items that are in the list

I would still change the documentation or the functionality of the component mainly because even from the documentation I still think that it can be totally different value from the one being displayed.
![image](https://github.com/microsoft/fluentui-blazor/assets/41269745/14dbf002-ffd5-4ef6-b194-8aa2e3b4bf1f)
