### ISSUE TITLE
fix: Footer with Style / Class Params do not get applied.

### ISSUE THREAD

**Issue by hammie1010** [microsoft/fluentui-blazor#754]
# 🐛 Footer with Style / Class Params

FluentFooter Component Style/Class Params don't get applied, 

## 💻 Repro or Code Sample
In the demo site change the Footer to the following:
```
<FluentFooter style="background-color: red">
    Footer text
</FluentFooter>
```

## 🤔 Expected Behavior

Background should be red.

## 😯 Current Behavior

Style not applied.

**Comment by hammie1010** [comment]
Yes:
![image](https://github.com/microsoft/fluentui-blazor/assets/12533052/3867d5f1-be40-4a97-be85-987e323c9bed)

Shows:

![image](https://github.com/microsoft/fluentui-blazor/assets/12533052/e4a4b096-208a-4836-b4ce-c09c1a86d8a6)

**Comment by hammie1010** [comment]
Did you use the dev or main branch to test that?  Dev works, Main doesn't.  It looks like it was fixed in Dev:

![image](https://github.com/microsoft/fluentui-blazor/assets/12533052/136c4ccb-eb5c-46a7-bda0-a2da16708b32)

**Comment by vnbaaij** [comment]
`dev`. You are right. This is a change we made only yesterday (I think). Will be in v3.1 which is due later this week (maybe already tomorrow)
