### ISSUE TITLE
feat: add Stroke property in Progress Ring control

### ISSUE THREAD

**Issue by zharchimage** [microsoft/fluentui-blazor#760]
# 🙋 Feature Request

I'm trying to customize the FluentProgressRing's Stroke property but I'm finding it really difficult to do it, I can only change successfully the background as it is inherited. The Stroke in the other hand is set in a Shadow root where it is difficult to access and change with CSS selectors

## 🤔 Expected Behavior

To expose the Stroke property from the Progress Ring so it is easy to modify externally. The component could look like this:

## 😯 Current Behavior

Those properties are not exposed in the control, and can't modify them easily. Opened a Question on [StackOverflow ](https://stackoverflow.com/questions/77146191/css-selector-over-circle-element-inside-svg-inside-shadow-dom-not-working)on this for more information 

## 💁 Possible Solution
Expose the properties in the base component

`<FluentProgressRing Stroke="pink"/>`  or `<FluentProgressRing Style="stroke:pink"></FluentProgressRing>`

**Comment by vnbaaij** [comment]
Hi,

Was your intent to include an image? We are not going to implement this in the Blazor component. We follow what is available in the Web Component.

You can most probably still achieve what you want. Targeting the shadow dom is not so hard. Use the ::part() selecto.r

**Comment by zharchimage** [comment]
Thanks for the answer. Got it working at the end with: 

`fluent-progress-ring::part(indeterminate-indicator-1) {
    stroke: blue !important;       
}`
