### ISSUE TITLE
feat: add select all to AutoComplete

### ISSUE THREAD

**Issue by PlayerModu** [microsoft/fluentui-blazor#768]
# 🙋 Feature Request

The new AutoComplete component allows filtering and multi-select. I would like to request the addition of a "Select All" to the component so I can select all currently filtered, without needing to click multiple times on each of the filtered items.

## 🤔 Expected Behavior

If I filter the original autocomplete items list, say by one or more letters or something, then clicking select all would select all the filtered items in the list 

## 😯 Current Behavior

Currently this achieved through filtering, selecting one item, then repeat (I have raised a discussion point around keeping the list open after searching)

## 💁 Possible Solution

There is always a "Select All" option above the list items inside the dropdown, or somewhere in/around the component/dropdown.

## 🔦 Context

I want to filter a list of codes by their first letter and then select all the filtered ones for further UI and data processing actions.

## 💻 Examples

(Select All at the bottom)
https://codebeam-mudextensions.pages.dev/mudselectextended

**Comment by dvoituron** [comment]
Thank you for your suggestion.
But this is unfortunately not planned for the moment.

You can also easily add a link or button in the `HeaderContent` section to do that and to select all the items displayed in the list.
At this moment, I think it's best to add this feature to a custom development.

**Comment by vnbaaij** [comment]
Also, what would happen if you have like 100's of items in the list...

**Comment by PlayerModu** [comment]
> Thank you for your suggestion. But this is unfortunately not planned for the moment.
> 
> You can also easily add a link or button in the `HeaderContent` section to do that and to select all the items displayed in the list. At this moment, I think it's best to add this feature to a custom development.

Okay no problem, thank you for replying anyway!. I'll take a look at doing this via the HeaderContent as you suggested.
