### ISSUE TITLE
fix: Dropdown appears below grid title in FluentSelect

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#771]
# 🐛 Bug Report

Select dropdown appears below the sticky grid title.

## 💻 Repro or Code Sample

![image](https://github.com/microsoft/fluentui-blazor/assets/303201/9ca9f5e3-a72a-49ee-8955-e7f5fd0b2dc3)

## 🤔 Expected Behavior

Appears above the sticky grid title.

## 😯 Current Behavior

Appears below the sticky grid title.

## 🌍 Your Environment

* Windows
* Chrome
* .NET 8 and Fluent Blazor 3.1

**Comment by vnbaaij** [comment]
I'm not seeing this when combining a `FluentSelect` with a `FluentDataGrid` sample:

![select_with_grid](https://github.com/microsoft/fluentui-blazor/assets/1761079/63886fc6-d121-463d-8760-56c2bbd6078c)

You can see the sample at https://preview.fluentui-blazor.net/Lab/Overview.

Can you share some source (privately) perhaps?

**Comment by JamesNK** [comment]
Your test example has overridden the z-index of the select listbox to a huge value:

![image](https://github.com/microsoft/fluentui-blazor/assets/303201/c102cab9-ddf5-461b-ba94-159957f81eda)

My listbox has a z-index of 1.

**Comment by vnbaaij** [comment]
Ah, true but we do that for every `FluentSelect` **but only if** it has a value for the `Height` parameter

From `FluentSelect.razor`:
```
if (!String.IsNullOrEmpty(Height))
{
    <style>
        @($"#{Id}::part(listbox) {{ max-height: {Height}; z-index: {ZIndex.SelectPopup} }}")
        @($"#{Id}::part(selected-value) {{ white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}")
        @($"fluent-anchored-region[anchor='{Id}'] div[role='listbox'] {{ height: {Height}; }}")
    </style>
}
```

**Comment by JamesNK** [comment]
Adding a height fixed it. The dropdown should probably have a max height anyway.

**Comment by vnbaaij** [comment]
Closing this. Made a note on the min-height/default behavior

**Comment by dvoituron** [comment]
I pushed this PR #774 to fix this issue.
