### ISSUE TITLE
docs: Large Property comments are not displayed entirely

### ISSUE THREAD

**Issue by agriffard** [microsoft/fluentui-blazor#772]
I wanted to understand how was working the `GridTemplateColumns` of a DataGrid but when the related comment is too large, the sentence is not displayed entirely : https://www.fluentui-blazor.net/DataGrid#templatecolumns

![image](https://github.com/microsoft/fluentui-blazor/assets/703248/5bbf6d59-4f41-4a33-a849-efc1ec6c188f)

**Comment by dvoituron** [comment]
You should have an horizontal scrollbar below the grid. Is it not the case?

**Comment by vnbaaij** [comment]
I've made and error in the demo site css, I think. fixing this now
