### ISSUE TITLE
[FluentDatePicker] No Date Formatting Option found

### ISSUE THREAD

**Issue by patelyahya** [microsoft/fluentui-blazor#775]
Hi, This is Yahya Patel. Just dived int Blazor a week ago and got in love with Fluent UI 💙💙💙. I am finding a way to change date format which currently is MM/dd/yyyy but I need to change it dd/MM/yyyy. Could anyone help? Thanks

**Comment by vnbaaij** [comment]
Hi Yahya,

Welcome to Blazor and the Fluent UI library.

The component follows the settings of the client (Culture) it is running on. Is your local setting MM/dd/yy?
If you want to change it for the browser, you need to change the locale/Culture for the page/site. See https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-70 for more information

**Comment by patelyahya** [comment]
Just checked it, it's possible but I want just one date picker to be in different format. How could I do that?

**Comment by dvoituron** [comment]
You can force the _culture_ of this component using the `Culture` property.
Example for setting the format and language _English-UnitedState_ :
```xml
<FluentDatePicker @bind-Value="@SelectedValue" Culture="@(System.Globalization.CultureInfo.GetCultureInfo("en-us"))" />
```

**Comment by jova1111** [comment]
@dvoituron Forcing the culture with `Culture` property doesn't seem to help with the date format, it only affects calendar (starting day of the week).
For example, if culture is set to `sr`, date should be in _dd/MM/yyyy_ format:

```
<FluentDatePicker @bind-Value="@Content.Date" 
    Culture="@(System.Globalization.CultureInfo.GetCultureInfo("sr"))" />
```

However, the date is still in the `MM/dd/yyyy` format because `en-US` culture is set in the browser:

<img width="202" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/33571287/d4ce1a08-ea35-45e4-be00-8a04ba8bd430">


It should be possible to force the date format in the date picker independent of the browser culture.

**Comment by jova1111** [comment]
> @dvoituron Forcing the culture with `Culture` property doesn't seem to help with the date format, it only affects calendar (starting day of the week). For example, if culture is set to `sr`, date should be in _dd/MM/yyyy_ format:
> 
> ```
> <FluentDatePicker @bind-Value="@Content.Date" 
>     Culture="@(System.Globalization.CultureInfo.GetCultureInfo("sr"))" />
> ```
> 
> However, the date is still in the `MM/dd/yyyy` format because `en-US` culture is set in the browser:
> 
> <img alt="image" width="202" src="https://private-user-images.githubusercontent.com/33571287/300752129-d4ce1a08-ea35-45e4-be00-8a04ba8bd430.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDc5NDMsIm5iZiI6MTcwNjYwNzY0MywicGF0aCI6Ii8zMzU3MTI4Ny8zMDA3NTIxMjktZDRjZTFhMDgtZWEzNS00NWU0LWJlMDAtOGEwNGJhOGJkNDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA5NDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZmM2ZTlhNjZlNWU4OTlhYzgxMjI0Y2M2YjA0NTk0NjFkN2M1MjZkMGRjZTVhYTI4MmJjYzRkOWQ3ZDE0NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BoLUyGSofosfIJkZ2yXZrISDW7MjmCmV2gh9s3bf0Bo">
> It should be possible to force the date format in the date picker independent of the browser culture.

I tried Germany (`de`) culture and it is showing the correct _dd.MM.yyyy_ format, so it looks like it is not working for Serbian (`sr`) culture. Weird, but this will do the job.

**Comment by dvoituron** [comment]
@jova1111 I've tried this sample and the result seems fine.
``` xml
<FluentDatePicker AriaLabel="To" @bind-Value="@SelectedValue" Culture="@System.Globalization.CultureInfo.GetCultureInfo("sr")" />
```

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/a89e37d0-5557-4daf-9259-c702efa11fa7)
