### ISSUE TITLE
TextField Sizing Options

### ISSUE THREAD

**Issue by patelyahya** [microsoft/fluentui-blazor#777]
Hi,
How could I size textfield component to small, medium or large?

 I got this example from fluent UI react but couldn't see any documentation for fluentui-blazor.
![image](https://github.com/microsoft/fluentui-blazor/assets/48586810/048d99c3-d35e-4496-90ed-71056d50f51e)

**Comment by dvoituron** [comment]
FluentUI React and FluentUI Blazor are not same products and don't have same features.

To display a label, using FluentUI Blazor, you should use the FluentLabel 

https://fluentui-blazor.net/Label

**Comment by patelyahya** [comment]
Label is something different. I want the text field in small size just like shown above.

**Comment by vnbaaij** [comment]
Like @dvoituron said, we don't have the same functionality as in React. Getting this smaller version is not an option on our side yet.

**Comment by dvoituron** [comment]
The **FluentTextField** doesn't contain a Label property (not yet). So you have to use a **FluentLabel** and a **FluentTextField** just below. You should have the same visual result.

**Comment by patelyahya** [comment]
> The **FluentTextField** doesn't contain a Label property (not yet). So you have to use a **FluentLabel** and a **FluentTextField** just below. You should have the same visual result.
> 
> But it's not possible to increase the FluentTextField size/height. Except using CSS.

Please guide how could I do this using CSS? Cause the components are taking some space. All I need is to set all Input components like AutoComplete, Textfield e.t.c

**Comment by patelyahya** [comment]
> Like @dvoituron said, we don't have the same functionality as in React. Getting this smaller version is not an option on our side yet.

Can I expect to have this feature in future?

**Comment by dvoituron** [comment]
You have these two CSS variables that could be applied in your case.
```html
<style>
    body {
        --type-ramp-base-font-size: 24px;
        --density: 3;
    }
</style>
```

Or better, you could set these variable values using the [Design Tokens](https://www.fluentui-blazor.net/DesignTokens) component (see section **Sizing**).

And we haven't planned to add a `Size` attribute to all our components.
