### ISSUE TITLE
Question: Data grid row as a clickable link

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#779]
I want rows in a data grid to act like a clickable link. I see an `OnRowFocus` event but no equivalent for clicking on a row.

I'm guessing I can give rows a class and use CSS over to simulate the appearance of a link (e.g. highlight the row, change the cursor) and use a JavaScript event for the click event and interop back into Blazor.

Before I start, I was wondering if there is a simpler known pattern for this.

**Comment by vnbaaij** [comment]
The underlying fluent-data-grid only raises the row-focused event. This is what we pick up on the Blazor side and where you can add an `EventCallback` to in `OnRowFocus`
Guess that means there is no simpler pattern for what you want to do.
