### ISSUE TITLE
fix: 'OK' button rendered outside of panel for Site settings

### ISSUE THREAD

**Issue by c0g1t8** [microsoft/fluentui-blazor#780]
# 🐛 Bug Report

**Ok** button is rendered outside of the dialog boundary when showing the Site Settings for _https://www.fluentui-blazor.net/_
![SiteSettings](https://github.com/microsoft/fluentui-blazor/assets/23250332/912d4f0f-5aa5-400d-9b3f-df12f8d69963)

## 💻 Repro or Code Sample

N/A

## 🤔 Expected Behavior

Button should be rendered within the panel.

## 😯 Current Behavior

Button is rendered outside of panel.

## 💁 Possible Solution

Correct css for **fluent-dialog-footer** class

## 🌍 Your Environment

Version: 3.1.0+3cfd4cf29b9230515c8cd9ee8dc2e788dde50d2b  -  [Powered by .NET 8.0.0-rc.1.23419.4]

**Comment by vnbaaij** [comment]
There are some dialog/padding issues that we will address in a 3.1.1 hotfix. Coming soon...

**Comment by joriverm** [comment]
@vnbaaij : i was going through the issue tracker to find if there was anything on an issue i was having with dialog height not being correct and the buttons being drawn over my dialog-body.
would this be related or is this a new issue i will need to investigate ?

![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/e4e09c7f-dd10-48e0-a763-3daf1b1b2d18)

**Comment by vnbaaij** [comment]
No, is same issue. Working on that as well.

**Comment by joriverm** [comment]
alright, good to know! :)
