### ISSUE TITLE
fix: [AutoComplete] cannot view text that get overloads

### ISSUE THREAD

**Issue by patelyahya** [microsoft/fluentui-blazor#785]
Hi,
I cannot view the rest of the text once I have fixed the width of AutoComplete even by clicking the arrow it doesn't work.

Attached recording for reference
https://github.com/microsoft/fluentui-blazor/assets/48586810/35baa6c0-8e2c-4fd1-83f3-31bea4fd3348

**Comment by dvoituron** [comment]
This is because your item is too large for the editable area.
The arrow is used to move to another item when you have selected several items in the list.

I don't think it's possible to combine the two features.
Perhaps by adding [...] at the end of the element, in the editing area, as is the case with the list. I'll check it out.

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/445bcee4-dee8-4591-8817-6862f5337dde)

**Comment by patelyahya** [comment]
There is no documentation provided to only have single Item, all examples are of multiple items in fluent UI. How would I Use single Item Selection with AutoComplete?

This didn't help out
![image](https://github.com/microsoft/fluentui-blazor/assets/48586810/0f48c00d-3878-4fd4-a066-07bf70b345cb)

**Comment by dvoituron** [comment]
I don't understand your question.

1. Set the `FluentAutocomplete.MaximumSelectedOptions` property to 1 to force the user to select a maximum of 1 item.
2. Use the `FluentSelect` component to select a single element (without search function).

**Comment by vnbaaij** [comment]
Closing this as no action required

**Comment by vnbaaij** [comment]
@patelyahya If you have questions about usage, please use the [Discussions](https://github.com/microsoft/fluentui-blazor/discussions) area

**Comment by patelyahya** [comment]
Yes, I have set the property `FluentAutoComplete.MaximumSelectedOptions` to 1. The only problem is that I cannot view long text if the text overflows in the component. Both In the Input Component as well as the options popup that is used for selection.

**Comment by dvoituron** [comment]
This is something I can add for a future update. In the meantime, everything is configurable in this component and you can add these [...] using `text-overflow: ellipsis`  like in this updated sample.

```xml
@inject DataSource Data

<FluentAutocomplete Id="my-autocomplete"
                    @ref="CountryList"  
                    TOption="Country"
                    Width="250px"
                    Placeholder="Select countries"
                    OnOptionsSearch="@OnSearchAsync"
                    MaximumSelectedOptions="1"
                    @bind-SelectedOptions="@SelectedItems">
    <SelectedOptionTemplate>
        <FluentBadge Appearance="@Appearance.Neutral"
                     OnDismissClick="@(async () => await CountryList.RemoveSelectedItemAsync(context))">
            <div title="@context.Name" style="max-width: 100px; text-overflow: ellipsis; overflow-x: hidden;">
                @context.Name
            </div>
        </FluentBadge>
    </SelectedOptionTemplate>
    <OptionTemplate>
        @context.Name
    </OptionTemplate>
    <MaximumSelectedOptionsMessage>
        The maximum number of selected items has been reached.
    </MaximumSelectedOptionsMessage>
</FluentAutocomplete>

@code
{
    FluentAutocomplete<Country> CountryList;
    IEnumerable<Country> SelectedItems = Array.Empty<Country>();

    private async Task OnSearchAsync(OptionsSearchEventArgs<Country> e)
    {
        var allCountries = await Data.GetCountriesAsync();
        e.Items = allCountries.Where(i => i.Name.StartsWith(e.Text, StringComparison.OrdinalIgnoreCase))
                              .OrderBy(i => i.Name);
    }
}
```

![ExampleAutoCompleteLong](https://github.com/microsoft/fluentui-blazor/assets/8350694/f0df649b-93c3-4905-b61c-cc37ac069dc6)

**Comment by patelyahya** [comment]
> This is something I can add for a future update. In the meantime, everything is configurable in this component and you can add these [...] using `text-overflow: ellipsis` like in this updated sample.
> 
> ```
> @inject DataSource Data
> 
> <FluentAutocomplete Id="my-autocomplete"
>                     @ref="CountryList"  
>                     TOption="Country"
>                     Width="250px"
>                     Placeholder="Select countries"
>                     OnOptionsSearch="@OnSearchAsync"
>                     MaximumSelectedOptions="1"
>                     @bind-SelectedOptions="@SelectedItems">
>     <SelectedOptionTemplate>
>         <FluentBadge Appearance="@Appearance.Neutral"
>                      OnDismissClick="@(async () => await CountryList.RemoveSelectedItemAsync(context))">
>             <div title="@context.Name" style="max-width: 100px; text-overflow: ellipsis; overflow-x: hidden;">
>                 @context.Name
>             </div>
>         </FluentBadge>
>     </SelectedOptionTemplate>
>     <OptionTemplate>
>         @context.Name
>     </OptionTemplate>
>     <MaximumSelectedOptionsMessage>
>         The maximum number of selected items has been reached.
>     </MaximumSelectedOptionsMessage>
> </FluentAutocomplete>
> 
> @code
> {
>     FluentAutocomplete<Country> CountryList;
>     IEnumerable<Country> SelectedItems = Array.Empty<Country>();
> 
>     private async Task OnSearchAsync(OptionsSearchEventArgs<Country> e)
>     {
>         var allCountries = await Data.GetCountriesAsync();
>         e.Items = allCountries.Where(i => i.Name.StartsWith(e.Text, StringComparison.OrdinalIgnoreCase))
>                               .OrderBy(i => i.Name);
>     }
> }
> ```
> 
> ![ExampleAutoCompleteLong](https://user-images.githubusercontent.com/8350694/270575600-f0df649b-93c3-4905-b61c-cc37ac069dc6.gif) [ ![ExampleAutoCompleteLong](https://user-images.githubusercontent.com/8350694/270575600-f0df649b-93c3-4905-b61c-cc37ac069dc6.gif) ](https://user-images.githubusercontent.com/8350694/270575600-f0df649b-93c3-4905-b61c-cc37ac069dc6.gif) [ ](https://user-images.githubusercontent.com/8350694/270575600-f0df649b-93c3-4905-b61c-cc37ac069dc6.gif)

Thanks Bro! That's the thing I was searching for ! Love You.
