### ISSUE TITLE
feat: add ability to set attributes on data grid rows and cells

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#788]
# 🙋 Feature Request

I want to set a style attribute on data grid rows based on its item. I know there is the ability to set a class, but a style would simplify implementation.

## 🤔 Expected Behavior

There is a way to set arbitrary attributes on rows/cells.

## 😯 Current Behavior

There is no way to set arbitrary attributes on rows/cells.

https://github.com/microsoft/fluentui-blazor/blob/7ea1305d669b98a9cc6ffde933dadc4083f9996d/src/Core/Components/DataGrid/FluentDataGrid.razor#L77-L91

## 💁 Possible Solution

Is `AdditionalAttributes` used for extra attributes?

Perhaps a callback property on the data grid that lets you add attribute name/values such as `Action<IItem, IDictionary<string, object>> RowAdditionalAttributes { get; set; }`.

I haven't got a use case for doing this for a cell, but it seems like something similar would be useful for other people.

## 🔦 Context

I want to set row appearance based on its data. There are potentially a lot of values, so using a class would be ugly and require defining many classes instead of a simple inline style.

**Comment by vnbaaij** [comment]
Fixed with PR #791
