### ISSUE TITLE
fix: Appearance.Hypertext doesn't display a link in FluentButton

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#790]
# 🐛 Bug Report

Hypertext appearance doesn't display a link. It still looks like a button.

## 💻 Repro or Code Sample

See "Clear all messages" at https://www.fluentui-blazor.net/MessageBar

![image](https://github.com/microsoft/fluentui-blazor/assets/303201/3d8966c7-8a1b-413f-9a99-70f404711052)

```html
<FluentButton OnClick="@DisplayMessage" Appearance="Appearance.Accent">Display</FluentButton>
<FluentButton Appearance="Appearance.Hypertext" OnClick="@((e) => MessageService.Clear())">Clear all messages</FluentButton>
```

## 🤔 Expected Behavior

`Appearance.Hypertext` looks like a link.

## 😯 Current Behavior

Looks like a button.

## 🌍 Your Environment

Windows
Chrome
Fluent Blazor 3.1

**Comment by JamesNK** [comment]
This issue doesn't impact me. I just noticed it while playing around with a web page design.

**Comment by dvoituron** [comment]
Yes, I think it's a mistake to have the `Appearance.Hypertext` proposition in the appearance enumeration.
This value is not (no longer) recognized by the `fluent-button` WebComponent.
I suggest removing it and using `FluentAnchor` instead (with Hypertext style enabled by default).

**Comment by vnbaaij** [comment]
Added a remark about this on the Button demo page. We will remove this specific value in an upcoming major release (as it is a breaking change)

**Comment by StevenTCramer** [comment]
@dvoituron  But an Anchor requires an Href where a button doesn't... which is probably why @JamesNK was trying to use a button.  And me too.

**Comment by vnbaaij** [comment]
Ok, clear. 
As mentioned, the `fluent-button` web component we wrap does not support that appearance so using that is not an option.
You can however just do this:

```
<p>With custom action</p>
<FluentAnchor Href="" Appearance="Appearance.Hypertext" OnClick="HandleClick">Link with no Href</FluentAnchor>

@code{
    private void HandleClick() => DemoLogger.WriteLine("Anchor clicked");
}
```
Href is nullable but has `EditorRequired` attribute so will complain if left out. Empty (or '#') will skip redirect.

**Comment by geodeasic** [comment]
Appearance.Hypertext has not been removed from FluentButton, one year later. I just stumbled upon this today while playing around with it :)

**Comment by hganpule** [comment]
> Ok, clear. As mentioned, the `fluent-button` web component we wrap does not support that appearance so using that is not an option. You can however just do this:
> 
> ```
> <p>With custom action</p>
> <FluentAnchor Href="" Appearance="Appearance.Hypertext" OnClick="HandleClick">Link with no Href</FluentAnchor>
> 
> @code{
>     private void HandleClick() => DemoLogger.WriteLine("Anchor clicked");
> }
> ```
> 
> Href is nullable but has `EditorRequired` attribute so will complain if left out. Empty will skip redirect. Supplying a '#' will also make it look like an href.

Even after setting Href="#" or Href="" the FluentAnchor appears as Hyperlink but then gets redirected to home page but also executes the OnClick function
 
If Href is omitted then the FluentAnchor does not appear as Hyperlink nor does the OnClick function work

Surprisingly FluentButton does not support Appearance.HyperText

I want to use it in following manner in a Grid

<TemplateColumn Title="Item Name">
    <FluentAnchor Href="" Appearance="Appearance.Hypertext" OnClick="() => ShowItem(context)">
        @(context.ItemName)
    </FluentAnchor>
</TemplateColumn>
