### ISSUE TITLE
fix: {project}.styles.css missing in Blazor-enhanced asp.net MVC App

### ISSUE THREAD

**Issue by killnine** [microsoft/fluentui-blazor#798]
# 🐛 Bug Report

When I was setting up my project, I could not get the auto-generated `{PROJECT_NAME}.styles.css` to load. It kept saying 404.

However, it ended up being a bit of a miscommunication on my part with the way the documentation was describing the process:

> In order for this library to work as expected, you will need to add the composed scoped CSS file for the components. This can be done by adding the following line to the <head> section of your index.html or _Layout.cshtml file in the project you installed the package:
> `<link href="{PROJECT_NAME}.styles.css" rel="stylesheet" />`

See, the peculiarity 

## 💻 Repro or Code Sample

1. Setup new FluentUI project with name `Web`
2. Modify the project's assembly name and root namespace to be something like `Contoso.Web`
3. Complete the setup but leave the `_Layout.cshtml` or `index.cshtml` with `Web.styles.css`
4. Upon startup, there should be a 404 for the stylesheet

## 🤔 Expected Behavior

I would expect the documentation to denote that it's actually the assembly name or root namespace that determines the auto-generated name of this file. Not the .csproj name, per se.

## 😯 Current Behavior

The current description of the documentation made me thing it was the .csproj name (and what shows up in my IDE as the 'name' of the project) that determined the filename generated. But since my organization typically has a longer assembly/namespace structure (e.g. {AppName}.{Layer}.{ProjectName}) the file wasn't foun.d

## 💁 Possible Solution

I can't see where the generation of this file is actually occurring, so I don't know what it should be changed to but I'd probably tweak the `{PROJECT_NAME}` comment in the installation instructions.

## 🔦 Context

I am setting up an MVC project that has specific pages with Blazor components. I was having a real issue seeing components styled without this stylesheet loading. And I was concerned something about my routing was causing the issue. Instead, it was just my misunderstanding of the installation documentation.

## 🌍 Your Environment

* OS & Device: Windows 10, Latest Patch
* Browser: Edge, latest
* .NET and FAST Version [e.g. 1.8.0]:  .NET 8.0rc1, FAST 3.1.1

**Comment by vnbaaij** [comment]
I added a remark about renaming root namespace/assembly to the specific doc section

**Comment by killnine** [comment]
Perfect! I think that note is very appropriate.
