### ISSUE TITLE
fix: A second operation was started in DataGrid with EF Core

### ISSUE THREAD

**Issue by davidkudera** [microsoft/fluentui-blazor#801]
# 🐛 Bug Report

DataGrid with Paginator in version 3.1.0 and 3.1.1 fails with the following error:

```
A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext.
```

Sometimes it loads the first time after starting the app but fails on the next request.

## 💻 Repro or Code Sample

```csharp
builder.Services.AddFluentUIComponents(options =>
{
    options.HostingModel = BlazorHostingModel.Server;
});

builder.Services.AddDataGridEntityFrameworkAdapter();
```

```razor
<FluentDataGrid Items="@_files" Pagination="_pagination" TGridItem="@File">
    <PropertyColumn Title="Name" Property="@((File f) => f.Name)" Sortable="true" IsDefaultSortColumn="true" InitialSortDirection="SortDirection.Ascending" />
</FluentDataGrid>

<FluentPaginator State="@_pagination" />

@code {

    private readonly PaginationState _pagination = new() { ItemsPerPage = 20 };

    private ApplicationContext? _context;

    private DbSet<File>? _files;

    public void Dispose()
    {
        _context?.Dispose();
    }

    protected override async Task OnInitializedAsync()
    {
        _context = await ContextFactory.CreateDbContextAsync();
        _files = _context.Files;
    }

}
```

## 🤔 Expected Behavior

Not to fail.

## 😯 Current Behavior

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT count(*)::int
      FROM public.file AS f
info: 28.09.2023 11:19:01.627 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT count(*)::int
      FROM public.file AS f
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'ApplicationContext'.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
fail: 28.09.2023 11:19:01.630 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query)
      An exception occurred while iterating over the results of a query for context type 'ApplicationContext'.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
         at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
         at lambda_method1928(Closure, QueryContext)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
         at Microsoft.Fast.Components.FluentUI.FluentDataGrid`1.<BuildRenderTree>b__113_1(RenderTreeBuilder __builder3) in /_/src/Core/Components/DataGrid/FluentDataGrid.razor:line 32
         at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
         at Microsoft.Fast.Components.FluentUI.DataGrid.Infrastructure.Defer.BuildRenderTree(RenderTreeBuilder builder) in /_/src/Core/Components/DataGrid/Infrastructure/Defer.cs:line 26
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '1LCf-dBwf8NBgLlwQAp6gSqC2UtUGsOCS6o62lEQi3c'.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
         at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
         at lambda_method1928(Closure, QueryContext)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
         at Microsoft.Fast.Components.FluentUI.FluentDataGrid`1.<BuildRenderTree>b__113_1(RenderTreeBuilder __builder3) in /_/src/Core/Components/DataGrid/FluentDataGrid.razor:line 32
         at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
         at Microsoft.Fast.Components.FluentUI.DataGrid.Infrastructure.Defer.BuildRenderTree(RenderTreeBuilder builder) in /_/src/Core/Components/DataGrid/Infrastructure/Defer.cs:line 26
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT count(*)::int
      FROM public.file AS f
info: 28.09.2023 11:19:01.639 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT count(*)::int
      FROM public.file AS f
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[@__p_1='20', @__p_0='0'], CommandType='Text', CommandTimeout='30']
      SELECT f.id, f.container_name, f.created_at, f.mime, f.name, f.resolution_v2, f.size
      FROM public.file AS f
      ORDER BY f.name
      LIMIT @__p_1 OFFSET @__p_0
info: 28.09.2023 11:19:01.647 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2ms) [Parameters=[@__p_1='20', @__p_0='0'], CommandType='Text', CommandTimeout='30']
      SELECT f.id, f.container_name, f.created_at, f.mime, f.name, f.resolution_v2, f.size
      FROM public.file AS f
      ORDER BY f.name
      LIMIT @__p_1 OFFSET @__p_0
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT count(*)::int
      FROM public.file AS f
info: 28.09.2023 11:19:01.674 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT count(*)::int
      FROM public.file AS f
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT count(*)::int
      FROM public.file AS f
info: 28.09.2023 11:19:01.706 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT count(*)::int
      FROM public.file AS f
```

## 💁 Possible Solution

Downgrade to version 3.0.1

## 🔦 Context

Print a simple DataGrid with data from `DbSet`.

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Brave, Chromium 117
* .NET: 7.0.201
* Blazor mode: server
* Microsoft.Fast.Components.FluentUI: 3.1.1
* Microsoft.Fast.Components.FluentUI.DataGrid.EntityFrameworkAdapter: 3.0.0
* EF Core with PostgreSQL: 7.0.10
* Npgsql: 7.0.4

**Comment by joecuevasjr** [comment]
I'm using v3.1.0 with no issue utilizing pagination. However, I do not set my context in OnInitializedAsync(). 
Since it's recommended to have a context per operation - [Blazor with EF Core - Database Access](https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-7.0#database-access), consider the following approach:

```csharp
// Update _context field and remove relevant code from OnInitializedAsync()
private ApplicationContext? _context => ContextFactory.CreateDbContext();
```

**Comment by davidkudera** [comment]
@joecuevasjr thanks for your comment, but I'm creating a context per operation (asynchronously): `_context = await ContextFactory.CreateDbContextAsync();`. I store it in a field so I can dispose it later.

**Comment by vnbaaij** [comment]
I have very little experience with EF Core. The code for the adapter is almost a one one one copy of what is used with QuickGrid. Would be interesting to see if QuickGrid showed the same behavior

**Comment by joecuevasjr** [comment]
@davidkudera when the OnInitializedAsync method is called it's only once per component lifetime. It won't rerun for every operation in the component. The call to CreateDbContextAsync() is currently set up as a one time setup when it should be per operation, such as when the data is fetched for the datgrid.

**Comment by malcolmvs** [comment]
We're having the same issue. Downgrading from v3.1.1 to v3.0.1 appears to resolve this.
We setup our DB context as follows:

```csharp
services.AddDbContext<OurDbContext>(options => options.UseSqlServer(connectionString));
```

And then make use of wrapper classes to expose the entities to the page:
```csharp
IQueryable<Customer> customers = Enumerable.Empty<Customer>().AsQueryable();

    protected override async Task OnInitializedAsync()
    {
        customers = CustomerService.List();
    }
```
Where List() returns the DB set.

- .NET: 6.0
- Blazor mode: server
- Microsoft.Fast.Components.FluentUI: 3.1.1
- Microsoft.Fast.Components.FluentUI.DataGrid.EntityFrameworkAdapter: 3.0.0
- EF Core with SQL Server: 7.0.10

**Comment by joecuevasjr** [comment]
The QuickGrid documentation on using [EF-Core IQueryable](https://aspnet.github.io/quickgridsamples/datasources) shows the following code example as the simplest and most performant option for EF Core:
````csharp
@inject ApplicationDbContext MyDbContext

<QuickGrid Items="@MyDbContext.People">
    ...
</QuickGrid>
````

**Comment by malcolmvs** [comment]
> The QuickGrid documentation on using [EF-Core IQueryable](https://aspnet.github.io/quickgridsamples/datasources) shows the following code example as the simplest and most performant option for EF Core:
> 
> ```cs
> @inject ApplicationDbContext MyDbContext
> 
> <QuickGrid Items="@MyDbContext.People">
>     ...
> </QuickGrid>
> ```

Thanks @joecuevasjr - do you know when MyDbContext will be disposed of in that implementation?

**Comment by malcolmvs** [comment]
@joecuevasjr correct me if I'm wrong, but calling Items.Count without making use of the asyncQueryExecutor is going to be causing this issue:

https://github.com/microsoft/fluentui-blazor/blob/2a7634c197574026c1196c97c61397ac623aca95/src/Core/Components/DataGrid/FluentDataGrid.razor.cs#L411

v3.0.1 does not have the empty check which v3.1.1 does, in which Item.Count is being called - might explain why v3.0.1 works for the most part?

https://github.com/microsoft/fluentui-blazor/blob/v3.0.1/src/Core/Components/DataGrid/FluentDataGrid.razor

https://github.com/microsoft/fluentui-blazor/blob/2a7634c197574026c1196c97c61397ac623aca95/src/Core/Components/DataGrid/FluentDataGrid.razor#L32

**Comment by vnbaaij** [comment]
@malcolmvs I don't understand. How can I use the `asyncQueryExecutor` in line 411 if it is `null`?

v3.0.1 indeed does not have the empty check because that version did not have the `EmptyContent` parameter yet. It was added in 3.1. 
De we just need to use `totalItemCount` in the empty check (by turning it in to a privale variable in the class)?

**Comment by malcolmvs** [comment]
Apologies @vnbaaij I see my comment is unclear. What I was trying to say is that by looking at the code I can see that asyncQueryExecutor needs to be used any time a count of the items is needed (IF the asyncQueryExecutor has been set). Thus the following code will cause an issue as it doesn't take the asyncQueryExecutor into consideration:

https://github.com/microsoft/fluentui-blazor/blob/2a7634c197574026c1196c97c61397ac623aca95/src/Core/Components/DataGrid/FluentDataGrid.razor#L32

I do believe you could use `totalItemCount` after exposing it but feel I don't understand the code well enough to be able to comment on a solution.

**Comment by vnbaaij** [comment]
I think I can fix this by removing the `Items?.Count() == 0` part from the line mentioned and just use the `_ariaBodyRowCount` part.
To make sure the _ariaBodyRowCount is set, I set it immediately after https://github.com/microsoft/fluentui-blazor/blob/2a7634c197574026c1196c97c61397ac623aca95/src/Core/Components/DataGrid/FluentDataGrid.razor.cs#L411
with ` _ariaBodyRowCount = totalItemCount;`. 

Sounds good?

**Comment by vukasinpetrovic** [comment]
@vnbaaij I have the same problem but in my case it is happening if I double click on sorting the column, meaning it executes two operations fast. I'm using basic implementation for testing, without paging or anything additional. Do you have an idea how can I prevent this?

```razor
@inject ApplicationDbContext DbContext

<FluentDataGrid Items="@DbContext.Users">
    <PropertyColumn Property="@(u => u.Email)" Sortable="true" Align="Align.Start" />    
    <PropertyColumn Property="@(u => u.UserName)" Sortable="true" Align="Align.Start" />    
</FluentDataGrid>
```

**Comment by davidalexandru11** [comment]
I have similar problem with my QuickGrid component...

When use pagination="true" the request is twice, otherwise the request is single.

My problem is that if I click on a button that for example opens a modal, itemprovider its fired, but if i click to sort one column and then try to press the button again, itemsprovide is not fired.

So everytime I must to sort something , search something or change page inside the quickgrid componet to avoid that itemsproviders to fire

I tried different methods to avoid this but without success.

**Comment by yrova** [comment]
@vnbaaij @davidkudera  
Is it possible to request to reopen this issue? Still happening as of the most recent version and wanted more visibility since I saw someone opened a PR to address it.

I wanted to expand on the issue and explain why it seems intermittent for a lot of people

- EF core DB context only allows one thread to access the DBcontext at time. Throws with the aforementioned error.
- For each paginated button press, it fires a different thread that ExecuteAsync in the entity framework adapter. The issue is this can cause multiple threads to access the Dbcontext at the same time, thus error.
- This issue appears intermittent since it's entirely dependent on how fast the data is retrieved and the thread can resolve its operation. If the operation is fast enough, you _probably_ won't see this issue
  - Another reason for the intermittent nature, there is a "warm-up" period for efcore queries.
For example, in a grid with a lot of data, the first time you paginate quickly it is likely to throw that error. But subsequent tries will work fine (most of the time).
