### ISSUE TITLE
fix: The `OnAction` event is incorrectly fired on the first render of `FluentNavMenu`

### ISSUE THREAD

**Issue by sajadkardel** [microsoft/fluentui-blazor#803]
![Untitled](https://github.com/microsoft/fluentui-blazor/assets/62190682/7c7d2fb8-d0aa-4b4e-9b63-125e36e046ae)

**Comment by vnbaaij** [comment]
Please supply repo steps. We can't wrok from an image...

**Comment by sajadkardel** [comment]
> Please supply proper repo steps. We can't work from an image...

Sure. Sorry for the lack of information. I’m currently working on [this](https://github.com/HiCode4Dev/HiCode.Blog) repo and I want to create a responsive `NavMenu`. For example, when the screen size is mobile, the menu should be closed after selecting one of the items…
I noticed that after selecting each item (or changing the address), the first menu item is selected automatically. This changes the address and re-fires the `OnAction` event.
You can try it out on `NavMenu.razor` in `...\HiCode.Blog\Client\HC.Web\Shared\NavMenu.razor`.
(For now, I have stopped using the `OnAction` event and have implemented a responsive NavMenu using the `OnLocationChanged` event.)

**Comment by vnbaaij** [comment]
We are replacing the NavMenu with a new NavLink based version in version 3.2. See PR #819
