### ISSUE TITLE
feat: add the ability to optionally hide the 'progress' section of the FluentInputFile

### ISSUE THREAD

**Issue by StevenRasmussen** [microsoft/fluentui-blazor#809]
# 🙋 Feature Request

It would be nice to be able to optionally hide the progress section of the FluentInputFile. 

## 😯 Current Behavior

Currently the progress section is always visible.

## 💁 Possible Solution

I would propose adding a property called: `ProgressVisibility` that has the possible values:

- Visible
- WhileUploading
- Never 

As you might guess, the `Visible` option would keep the current behavior.
The 'WhileUploading' would make it visible while files are being uploaded and then hidden once all files are complete.
The `Never` option would never show the progress section.

## 🔦 Context

I am creating a way to upload images to my application and the image, once uploaded, occupies the space of the `FluentInputFile`.  It looks a little weird to have the progress section still visible after the image is uploaded. Here is an image:

![image](https://github.com/microsoft/fluentui-blazor/assets/11198735/e349e508-ba32-4603-b7b9-c35a11740ad9)

**Comment by dvoituron** [comment]
You could define a variable **IsUploaded** in your code, set this variable to **True** behind the event **OnCompleted**. And hide the FluentInputFile, FluentLabel and FluentProgress when this variable is True:

´´´
@if(!IsUploaded)
{
  <FluentInputFile ... />
  <FluentProgress ... />
  <FluentLabel ... />

}
´´´

**Comment by StevenRasmussen** [comment]
@dvoituron - Thanks for the suggestion.  Unfortunately, this won't achieve my desired behavior in this instance as I would still like to use the `<FluentInputFile>` even after a file has been uploaded.  They should still be able to drag/drop a file over the current image to replace it.  And to be clear, the `<FluentProgress>` that I'm talking about is the one that is embedded in the `<FluentInputFile>` and not a custom one that I have added to my component. Thanks

**Comment by dvoituron** [comment]
@StevenRasmussen I can see the problem.
I think it would be even better to make the `ProgressPercent` and `ProgressTitle` properties bindable. Including an `UpdateProgression(percent, title)` method.

This would make it possible to handle other cases, such as displaying the progress and holding it for 5 seconds after 100%, then returning to 0% and allowing a new Upload.
Or reset the percentage to 0% to solve your problem.
Or always set the percentage to 0% to never display the progress bar.

I can modify this this week for the next release.

**Comment by StevenRasmussen** [comment]
@dvoituron - Sounds great! Thanks!

**Comment by dvoituron** [comment]
> Hello, is there any news about this feature ? Online documentation do not explain how to hide the ProgressSection, which by the way do to not have a nice looking style when you add a FluentInputFile to your project, contrary to the one shown in the documentation. Thanks.

Yes. It's still in our development phases and will be published as soon as possible.

What do you mean by "not have a nice looking style (...), contrary to the one shown in the documentation"?
Do you have a screenshot to explain that?

**Comment by DrMozze** [comment]
Yes of course. Maybe I'm doing something wrong but I'm talking about the gray rectangle shown inside the component with the label "Completed" stack to the left side : 
![image](https://github.com/microsoft/fluentui-blazor/assets/72139152/e8575395-47f4-48ff-af0a-bda41ce51198)

I was expecting this kind of style : 
![image](https://github.com/microsoft/fluentui-blazor/assets/72139152/a7dea820-ba57-478f-8498-574e2c4f4dcf)

**Comment by dvoituron** [comment]
What code did you use?
This part of the panel is styled using `.fluent-inputfile-container .progress`.
You can change this style.

**Comment by DrMozze** [comment]
I used this code : 

` <FluentInputFile Id="file_upload_existing_plans"
                  Mode="InputFileMode.Stream"
                  Multiple="true"
                  ShowPreview="true"
                  MaximumFileSize="50000000"
                  Accept=".jpg,.png,.bmp,.pdf,.doc,.docx,.xls,.xlsx"
                  OnCompleted="@((IEnumerable<FluentInputFileEventArgs> files) => OnUploadCompleted(FilesType.ExistingPlans,files))"
                  OnFileError="@OnUploadError"
                  Class="custom-border-dashed">`

The class css "custom-border-dashed" is as follow :

`.custom-border-dashed {
    border: 1px dashed var(--accent-fill-rest);
    padding: 5px;
}`

I'm not overriding ".fluent-inputfile-container .progress" so I'm expecting to have same comportement as in documentation : progressbar visible and text Completed centered.

Looking on the screenshot of @StevenRasmussen above, he seems to have the same issue : text aligned on left side, progressbar not visible and huge gray rectangle.

yet I can see that the styles you've defined seem to apply :

![image](https://github.com/microsoft/fluentui-blazor/assets/72139152/50fbf9e1-9e85-42a0-8ea7-9577530b02ac)

Don't know if I'm missing something obvious, I'm not used to work with web technologies.

**Comment by dvoituron** [comment]
In your screenshot, the `.progress' class comes from `_progress.scss'. That's not a file included in our lib :-)
You probably added Boostrap that contains this CSS class.

During the current **FluentInputFile** changes, I will update this class name to another to avoid this kind of conflict.

**Comment by dvoituron** [comment]
Will be fixed using these changes #1037

**Comment by DrMozze** [comment]
Thanks for your quick reply Denis. I'll check if I have a Bootstrap reference still lying around somewhere in my project.
