### ISSUE TITLE
fix: Divider isn't placed in the end slot in FluentDivider

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#811]
# 🐛 Bug Report

A FluentDivider with `slot="end"` isn't placed in the end slot.

## 💻 Repro or Code Sample

```html
        <FluentToolbar Orientation="Orientation.Horizontal">
            <FluentSelect TOption="ApplicationViewModel"
                          Items="@_applications"
                          OptionValue="@(c => c.Id)"
                          OptionText="@(c => c.Name)"
                          @bind-SelectedOption="_selectedApplication"
                          @bind-SelectedOption:after="HandleSelectedApplicationChangedAsync" />
            <FluentSearch @bind-Value="_filter"
                          @oninput="HandleFilter"
                          AfterBindValue="HandleClear"
                          Placeholder="Filter..."
                          slot="end" />
            <FluentDivider slot="end" Orientation="Orientation.Vertical" />
            <FluentButton slot="end" Appearance="Appearance.Stealth" aria-label="Add Filter" OnClick="() => OpenFilterAsync(null)"><FluentIcon Value="@(new Icons.Regular.Size16.Filter())" /></FluentButton>
        </FluentToolbar>
```

## 🤔 Expected Behavior

FluentDivider is on the right of the toolbar.

## 😯 Current Behavior

FluentDivider is on the left of the toolbar.

## 💁 Possible Solution

Raw HTML with the slot attribute:

```html
<fluent-divider orientation="vertical" role="separator" aria-orientation="vertical" slot="end"></fluent-divider>
```

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Chrome
* 3.1.1

**Comment by vnbaaij** [comment]
`FluentDivider` did not pass on the `AdditionalAttributes` to the web component yet, so `slot` attribute would not get set there. Fixed in 3.2.

p.s. for it to fully work in the toolbar scenario, you also need to supply a `Style="height: aapx;"` to the divider. The component can't figure out the heigth itself in this situation.
