### ISSUE TITLE
fix: FluentSelect in 3.1.1 makes style text visible

### ISSUE THREAD

**Issue by nimrof** [microsoft/fluentui-blazor#813]
# 🐛 Bug Report

Not sure how to explain it, but after 3.1.1 i get extra text before the select component
No problem in 3.1.0

## 💻 Repro or Code Sample

It might be related to how the first examples looks like, but it looks different for me https://www.fluentui-blazor.net/Select
![image](https://github.com/microsoft/fluentui-blazor/assets/9848846/12ef895c-275d-4d68-a902-36a1724b9a94)

Testcode:

EmptyLayout.razor
```
@inherits LayoutComponentBase

<div class="main">    
    <div class="content px-4">
        @Body
    </div>
</div>
```

Testpage.razor
```
@inherits LayoutComponentBase
@using Microsoft.Fast.Components.FluentUI
@layout EmptyLayout

@page "/test2"

<FluentSelect
    Items=@eOptions 
    OptionText="@(i => i.Value?.ToString())"
    OptionSelected="@(i => i.Selected)" 
    @bind-Value=@selectedOption />

@code {
    String? selectedOption;

    Type? enumType;
    List<Option<Enum>> eOptions = new();
}
```

## 🤔 Expected Behavior

Only the select component is shown

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/9848846/5bcb37c7-9b33-4300-8137-d1bf92f4f0ca)

## 🔦 Context

Not a big problem for me, i can use 3.1.0

## 🌍 Your Environment

Linux ubuntu 22.04 (server)
Browser Edge & Firefox
.Net 6

**Comment by vnbaaij** [comment]
See #805. Fixed in next version

**Comment by nimrof** [comment]
> See #805. Fixed in next version

Oh, did not see that 😑

**Comment by vnbaaij** [comment]
No worries!
