### ISSUE TITLE
Maui failed to use fluentui

### ISSUE THREAD

**Issue by HuaFangYun** [microsoft/fluentui-blazor#821]
![image](https://github.com/microsoft/fluentui-blazor/assets/30250585/81508667-1ca6-4087-847e-fa944e24a99e)
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NU1605	错误形式的警告: 检测到包降级: Microsoft.Extensions.Logging.Abstractions 从 7.0.1 降级到 7.0.0。直接从项目引用包以选择不同版本。 
 HuaFang.FluentUI.Maui -> Microsoft.Fast.Components.FluentUI 3.1.1 -> Microsoft.AspNetCore.Components.Web 7.0.11 -> Microsoft.AspNetCore.Components 7.0.11 -> Microsoft.AspNetCore.Authorization 7.0.11 -> Microsoft.Extensions.Logging.Abstractions (>= 7.0.1) 
 HuaFang.FluentUI.Maui -> Microsoft.Extensions.Logging.Abstractions (>= 7.0.0)	HuaFang.FluentUI.Maui	E:\HuaFang\HuaFang.FluentUI.Maui\HuaFang.FluentUI.Maui\HuaFang.FluentUI.Maui.csproj	1

**Comment by dvoituron** [comment]
Hi,

With only a screenshot to explain, it's very difficult to understand where this error comes from.
[NU1605](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605): A dependency package specified a version constraint on a higher version of a package than restore ultimately resolved.

Could you give us a list of all the other NuGet packages referenced?

**Comment by HuaFangYun** [comment]
Operation procedure:
1. Create a Maui Blazor project.（VS17.7.4）
2. Error report when installing FluentUi blazor
3

**Comment by HuaFangYun** [comment]
2.4.3  Can be installed .3.0 Cannot be installed 。This should be a problem with the version of maui. Thank you very much

**Comment by vnbaaij** [comment]
This is indeed a MAUI version problem. See https://github.com/dotnet/maui/issues/16244. Closing this here
