### ISSUE TITLE
FluentCombobox within FluentCard

### ISSUE THREAD

**Issue by Rocky-25** [microsoft/fluentui-blazor#825]
# 🐛 Bug Report

When putting a FluentCombobox within a FluentCard, if the item list is more than the space in the card you can't see the options.

## 💻 Repro or Code Sample

`
<FluentCard Style="min-height:150px;padding:20px;width:25%;">
    <FluentCombobox Items=Options
                    OptionText="@(i => i.Description)"
                    OptionValue=@(i => i.Id.ToString())
                    @bind-Value="MarriageStatus"
                    Autocomplete="ComboboxAutocomplete.Both"
                    Placeholder="Select status">
        Marriage Status
    </FluentCombobox>
</FluentCard>
`

@code {

    private string MarriageStatus;

    public IEnumerable<MarriageOption> Options { get; set; } = new List<MarriageOption>
            {
                new MarriageOption("Married"),
                new MarriageOption("Single"),
                new MarriageOption("Partner"),
                new MarriageOption("Common law"),
                new MarriageOption("Civil partnership"),
                new MarriageOption("Separated"),
                new MarriageOption("Divorced"),
                new MarriageOption("Widowed")
            };
}

## 🤔 Expected Behavior

Should be able to see the list in front of the card.

## 😯 Current Behavior

Can not see the full list.
![image](https://github.com/microsoft/fluentui-blazor/assets/52032850/509ee14f-0028-433e-83b4-eb0c806d1f10)

**Comment by dvoituron** [comment]
Hi,
That's by design from the underlying `fluent-card` Web Component.
You have to remove the `content-visibility` and `contain` styles like this.

```razor
<FluentCard Style="content-visibility: inherit; contain: inherit;">
   ...
</FluentCard>
```

@vnbaaij I suggest disabling these two styles by default in our **FluentCard** component.
Or ask the FAST team to remove these two styles.
What's your opinion?

**Comment by Rocky-25** [comment]
That's great, thank you.
Did I miss this somewhere in the documentation about components in general or should the card page explain this?
https://www.fluentui-blazor.net/Card

**Comment by dvoituron** [comment]
No. I did not found that before your question 😊 Reason why I propose to fix our FluentCard to avoid to do that manually, using styles.
