### ISSUE TITLE
DialogService.ShowDialogAsync<TDialog>(DialogParameters<TData> parameters) throw an ObjectDisposedException exception

### ISSUE THREAD

**Issue by yongkeecho** [microsoft/fluentui-blazor#826]
# 🐛 Bug Report

`DialogService.ShowDialogAsync<TDialog, TData>(DialogParameters<TData> parameters)` works fine but is shown "obsolete" while
`DialogService.ShowDialogAsync<TDialog>(DialogParameters<TData> parameters)` throw an ObjectDisposedException exception.

## 🤔 Expected Behavior

I guess `ShowDialogAsync<TDialog>(DialogParameters<TData> parameters)`  replaces `ShowDialogAsync<TDialog, TData>(DialogParameters<TData> parameters)` but it doesn't work as expected.

**Comment by dvoituron** [comment]
Hi,

We've made obsolete `Task<IDialogReference> ShowDialogAsync<TDialog, TData>(DialogParameters<TData> parameters)`
because we intend to use `Task<IDialogReference> ShowDialogAsync<TDialog>(object data, DialogParameters parameters)`.
This last method do exactly the same job.

I've tried to reproduce your exception, but without success. Can you give me more details?

**MyPage.razor**
```razor
@inject IDialogService DialogService
<FluentButton @onclick="@OpenDialogAsync">
    Open Hello World
</FluentButton>

@code {
    private async Task OpenDialogAsync()
    {
        var dialog = await DialogService.ShowDialogAsync<HelloDialog>(new DialogParameters()
            {
                Title = "Hello Dialog",
            });
        var result = await dialog.Result;
    }
}
```

**HelloDialog.razor**
```razor
@implements IDialogContentComponent
<h1>Hello World</h1>
``` 
![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/86536079-0465-462a-9e82-5f7355aaa44b)

**Comment by yongkeecho** [comment]
Thank you for testing out @dvoituron .
My example is below:

MyPage.razor - Working
`
<FluentButton @onclick="@OpenDialogAsync">
    Open Hello World
</FluentButton>

@code
{
  private async Task OpenDialogAsync()
  {
      var dialog = await DialogService.ShowDialogAsync<HelloDialog, HelloWorldDialogResult>(new DialogParameters<HelloWorldDialogResult>
          {
              Title = "Hello Dialog",
              Content = new()
          });
      var result = await dialog.Result;
  }
}
`
MyPage.razor - Not Working
`
<FluentButton @onclick="@OpenDialogAsync">
    Open Hello World
</FluentButton>

@code
{
  private async Task OpenDialogAsync()
  {
      var dialog = await DialogService.ShowDialogAsync<HelloDialog>(new DialogParameters<HelloWorldDialogResult>
          {
              Title = "Hello Dialog",
              Content = new()
          });
      var result = await dialog.Result;
  }
}
`
HellowDialog.razor
`
@implements IDialogContentComponent
<h1>@Content.Greeting World</h1>

@code {
    [Parameter]
    public HelloWorldDialogResult Content { get; set; } = default!;

    [CascadingParameter]
    public FluentDialog? Dialog { get; set; }
}
`
HelloWorldDialogResult.cs
`
public class HelloWorldDialogResult
{
    public string? Greeting { get; set; } = "Hi";
}
`

![image](https://github.com/microsoft/fluentui-blazor/assets/1816019/7abe1db6-5212-480c-a051-595b2879ed7a)

![image](https://github.com/microsoft/fluentui-blazor/assets/1816019/86082ca6-5f54-430c-a109-0a51dbc7c3b6)

**Comment by dvoituron** [comment]
Have you added the `FluentDialogProvider` in your code, as [requested by the doc](https://www.fluentui-blazor.net/Dialog)?
I also get an exception only when this **Provider** is not defined.

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/6173a057-9aa1-45f2-a5ca-29a36be62cdc)

**Comment by yongkeecho** [comment]
Yes I added FluentDialogProvider and it works fine.
My report is your new generic signature does not work; only old one works as below.

![image](https://github.com/microsoft/fluentui-blazor/assets/1816019/feda524c-0d09-4711-b6c5-06a2f7030c4c)
