### ISSUE TITLE
fix: Updating SelectedOptions doesn't update FluentSelect on page

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#836]
# 🐛 Bug Report

I want to update `FluentSelect.SelectedOptions` but changing the collection has no impact on displayed items.

## 💻 Repro or Code Sample

```razor
<FluentSelect Items="Values"
              TOption="string"
              Multiple="true"
              SelectedOptions="SelectedValues"
              SelectedOptionsChanged="@(async args => await ValuesChangedAsync(args))" />

@code {
    public IEnumerable<string> SelectedValues = new List<string>();
    public List<string> Values = new List<string>
    {
        "All",
        "One",
        "Two"
    };

    public async Task ValuesChangedAsync(IEnumerable<string> values)
    {
        if (values.Contains("All"))
        {
            Values = new List<string> { "All", "One", "Two", "Three" };
            SelectedValues = Values.ToList();
            await InvokeAsync(() => StateHasChanged());
        }
    }
}
```

## 🤔 Expected Behavior

Choosing the `All` option should select all items.

## 😯 Current Behavior

Selected items displayed don't change.

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Chrome
* .NET and FAST Version: .NET 8 and 3.1.1

**Comment by vnbaaij** [comment]
Fixing this for 3.2, Was doing to much in base class `OnInitialized()` and not enough in `OnParameterSet()`

![fix-select](https://github.com/microsoft/fluentui-blazor/assets/1761079/f1a195a9-2b44-4bca-9e19-c1d909b470d0)

(I assume you are aware the code provided in the sample works only once as nothing gets deselected etc)

**Comment by JamesNK** [comment]
I can see the example now works, but as you mentioned, nothing gets deselected (I don't understand why nothing gets deselected when clicked on) then it isn't very useful. Can you reopen this?

My reproduction was trimmed down. The _goal_ here is to have a multiple-option FluentSelect and be able to programmatically select and deselect items in reaction to the user clicking on other items.

For example:
* If `All` isn't selected, then selecting it selects all other items.
* If `All` is selected, then deselecting it deselects all other items.
* If `All` isn't selected and all other items are selected then it becomes selected.
* If `All` is selected and another item is deselected then it becomes deselected.

Is `SelectedOptions` + `SelectedOptionsChanged` the way to achieve this? Or is it `@bind-SelectedOptions` + `@bind-SelectedOptions:after`?
