### ISSUE TITLE
Horizontal Scroll - add properties  for create Carousel

### ISSUE THREAD

**Issue by Andrey-2021** [microsoft/fluentui-blazor#840]
Please,
for "Horizontal Scroll"
add properties so that the navigation buttons appear only when the mouse hovers over the image.
Or add new component Carusel
Example 
https://www.blazor.zone/carousel

Thanks.

**Comment by vnbaaij** [comment]
Hi,

Because of the Fluent design, we can (and will) not change the behavior of the buttons. At this time we do not see any value in adding a new specific component for this.

**Comment by vnbaaij** [comment]
Hi,

Because of the Fluent design, we can (and will) not change the behavior of the buttons. At this time we do not see any value in adding a new specific component for this.
