### ISSUE TITLE
docs: fix ef adapter setup on the demo site and github readme

### ISSUE THREAD

**Issue by backcode-dev** [microsoft/fluentui-blazor#852]
# 🙋 Documentation Request

In the demo page https://www.fluentui-blazor.net/ at the section "Use the DataGrid component with EF Core" / "Usage" 
And github here: https://github.com/microsoft/fluentui-blazor#usage

there is a code snippet to include in program/startup. it currently says to add :
`builder.Services.AddFluentUIDataGridEntityFrameworkAdapter();`

However, following the current instructions on this page, it seems this extension method does not exist.

( demo page version was: Version: 3.2.0+4ee85830b3f758cc3dc0ce1830affaad9f89511d  )

## 💁 Possible Solution

looking in the package/intellisense - I think this should read:
`builder.Services.AddDataGridEntityFrameworkAdapter();`  
if this is not the case, perhaps the version of the EFCore extension package doesn't match the other docs? I haven't tried the data grid quite yet so I don't know if it works - sorry! I'm just reporting these as I follow along.

**Comment by vnbaaij** [comment]
Don't be sorry. Glad you found this. Helps others to get started more smoothly!
