### ISSUE TITLE
docs: fix copy emoji code from emoji search page

### ISSUE THREAD

**Issue by backcode-dev** [microsoft/fluentui-blazor#857]
# 🙋 Documentation Request

On the page: https://www.fluentui-blazor.net/Emoji if you search for a specific entry, the feature to copy an emoji component declaration (clicking the clipboard icon) returns invalid code.

The value given is: 
`<FluentEmoji Value="@(new Emojis.TravelPlaces.Color.Default.Rocket())" Width="32px" />`

( docs site version Version: 3.2.0+4ee85830b3f758cc3dc0ce1830affaad9f89511d  )

## 💁 Possible Solution

This should read: 
`<FluentEmoji Emoji=Emojis.TravelPlaces.Color.Default.Rocket Width="32px" />`

Edit: The icon page ( https://www.fluentui-blazor.net/Icon ) behaves in the same way.

**Comment by dvoituron** [comment]
Hi

The Emoji and Icon components use the same logic. And as we explained in the Icon doc page...

" During the DotNet Publication process, the unused icons are automatically removed from the final library. You can configure this behavior by setting the ´PublishTrimmed´ property in your project file.

So, we recommend always using the ´Value´ property to specify the icon to be rendered (and not the Icon property). This ensures that the icon is not deleted from the final library. "

For same reasons, it's always better to use ´Value' attribute for **Emoji**.

**Comment by backcode-dev** [comment]
Ah, I see. I started from the emoji page and did not see the icon discussion regarding the Value parameter. And for some reason my test page gave me an error when I used hot reload after pasting in the generated component - but now it does not and I cannot reproduce that. False alarm... Perhaps just copy that publication / trimming warning over on the emoji page.  
Thanks! I'm liking the components/setup very much so far (i'm totally new if you can't tell - heh)

**Comment by dvoituron** [comment]
No worries. But yes that should be interesting to include this same remark on this page.
