### ISSUE TITLE
fix: click the nav button does not work outside the <a> html tag in Fluent Nav Menu Component

### ISSUE THREAD

**Issue by Narvalex** [microsoft/fluentui-blazor#859]
# 🐛 Bug Report

The same as the title. If I remebered correctly this work well in the past with the TreeView implementation.

## 💻 Repro or Code Sample

Just create a nav with links to different pages in an app and click outside the anchor tag, like the zone in red bellow. 
![image](https://github.com/microsoft/fluentui-blazor/assets/11648387/2aca33c8-aff7-4d6f-9657-8ff3c21656b7)

## 🤔 Expected Behavior

It should work when clicking the button since the whole button is highlighted when `on hover`.

## 😯 Current Behavior
It only triggers a redirect when clicking in the anchor tag (the blue zone in the screenshot). It does not do anything when clicking the button outside the anchor tag (the red zone).

The same happen with the Fluent UI demo page. Just go to some component page and try to return to home using the nav, but clicking just beside the Home text, like shown in the picture bellow. Nothing will happen until you hit the text.
![image](https://github.com/microsoft/fluentui-blazor/assets/11648387/c7400661-376c-4fd2-af23-6989dae02de4)

## 💁 Possible Solution

Handle on click event? 

## 🔦 Context

Just doing normal nav menu stuff

## 🌍 Your Environment

Windows 11, Edge browser. .NET 7 SDK. Fast Version 3.2.0

**Comment by vnbaaij** [comment]
Hi,

This will be fixed in the next service release. I forgot to make a change in the NavGroup css.
To work around it for now, adding the following to your css should help:

::deep .fluent-nav-link { 
     width: 100%; 
 }

**Comment by Narvalex** [comment]
Thanks for the fix, @vnbaaij. Even so, risking being pedantic, I'm sorry being the one who has to say that there are still areas of the navigation button that, even when illuminated when hovering with the mouse, do nothing when clicking. It happens that the anchor tag does not cover the entire button, as happens for example in the case of Bootstrap button links.
![image](https://github.com/microsoft/fluentui-blazor/assets/11648387/0f1becda-599e-4bfb-aa3a-12c83381062e)
![image](https://github.com/microsoft/fluentui-blazor/assets/11648387/35ed0517-4cc7-439d-85b6-6cad1b4b033f)

**Comment by vnbaaij** [comment]
Yup, this is not good yet. A new issue has been opened for this #884. Let's track this there.

**Comment by vnbaaij** [comment]
Hi Alexis, any chance you can take a quick look at https://preview.fluentui-blazor.net/ and confirm this is solved now?

**Comment by Narvalex** [comment]
Hey @vnbaaij , thanks for the quick fix! It definitely works now as expected. Hopefully it will be available soon.

**Comment by vnbaaij** [comment]
It already is: https://www.nuget.org/packages/Microsoft.Fast.Components.FluentUI/3.2.2 
(I was confident that this fix was the one to rule them all :))
