### ISSUE TITLE
fix: Dropdown area in AutoComplete responds to key presses after being closed with the mouse

### ISSUE THREAD

**Issue by iainross** [microsoft/fluentui-blazor#860]
# 🐛 Bug Report

Open the drop down list for an autocomplete, the first item is automatically highlighted and if you hit Enter it will be selected.
If you instead use the mouse to select a different option it is selected and the drop down list closes.
Hit Enter while focus is on the control and the first element n the drop down is added to the selection as if it was still open.

## 💻 Repro or Code Sample

Issue can be reproduced in the example site: https://www.fluentui-blazor.net/Autocomplete

## 🤔 Expected Behavior

Once the drop down has closed pressing the Enter key should do nothing on the control.

## 😯 Current Behavior

The closed drop down responds to the Enter key as if it were still open.

## 💁 Possible Solution

I would guess that `FluentAutoComplete.SelectableItem` needs setting to `default` when the drop down is closed.

## 🔦 Context

Trying to implement the control on an internal company site to replace a hand rolled (and horrible) multi-select drop down control.

## 🌍 Your Environment

* OS & Device: Windows 10 (19045.3570)
* Browser Microsoft Edge Version 118.0.2088.46 (Official build) (64-bit)
* .NET and FAST Version locally seen using .Net 7.0.402 and Fast 3.2.0, also whatever version is behind the demo site

**Comment by dvoituron** [comment]
Thanks for you feedback. I will check and fix that quickly.

**Comment by dvoituron** [comment]
it's fixed in PR #866... and will be published with the next Release.
