### ISSUE TITLE
fix: Accessibility issue in FluentDivider

### ISSUE THREAD

**Issue by tlmii** [microsoft/fluentui-blazor#872]
# 🐛 Bug Report

The code:

`<FluentDivider Role="DividierRole.Presentation" Orientation="Orientation.Vertical" />`

will generate this:

`<fluent-divider role="presentation" orientation="vertical" aria-orientation="vertical"></fluent-divider>`

which gets flagged by Accessibility Insights because elements with a role of "presentation" (which is just an alias for "none") are not allowed to have an aria-orientation attribute. 

This has been fixed in https://github.com/microsoft/fast/pull/6771 a few months ago. It's not clear to me exactly where that stands in terms of eventually making it into the fluentui web components package used by the FluentUI-Blazor library.

## 💻 Repro or Code Sample

You can see the issue by running Accessibility Insights for Web on the divider example page: https://www.fluentui-blazor.net/Divider

![image](https://github.com/microsoft/fluentui-blazor/assets/9613109/b2f6c3e1-f4f3-4b8c-a205-4d6863629333)

## 🤔 Expected Behavior

No accessibility issue for FluentDivider

## 😯 Current Behavior

The above accessibility issue

## 💁 Possible Solution

Somehow we need to take the fix that already made it into FAST. 

## 🌍 Your Environment

.NET 8, FluentUI Blazor 3.2, Windows 11, Edge, Accessibility Insights for Windows

**Comment by vnbaaij** [comment]
Unfortunately, we can't override what comes out of the web component. To fix this, the FAST fix needs to be backported to the archives/v1 branch and then we need an new release of the web components script

**Comment by dvoituron** [comment]
I create a small fix, until we have a solution from the FAST team: PR #877
