### ISSUE TITLE
Issues with Fluent ComboBox: Redundant Styling Tags and Low Z-Index

### ISSUE THREAD

**Issue by ChrMaass** [microsoft/fluentui-blazor#880]
### Description:
When utilizing the Fluent ComboBox from Fluent UI for Blazor, I've noticed a couple of issues that seem to affect the component's usability and clarity of source code:

1. **Redundant Styling Tags**: For every ComboBox, a `<div>` tag with a plethora of inline styles is generated. This seems redundant and clutters the source code significantly. Below is an example of the tag:
```html
<div class="listbox" part="listbox" role="listbox" id="listbox-0" style="... (all the styles) ..." hidden=""><slot></slot></div>
```

2. **Low Z-Index**: The ComboBox's listbox doesn't seem to have a sufficiently high Z-Index. As a result, elements like Datagrids often overlay the expanded listbox, which impacts the user experience.

### Reproduction Steps:
Implement the Fluent ComboBox in a Blazor project.
Observe the generated source code and notice the redundant styling tags for every ComboBox instance.
Try using the ComboBox in conjunction with other elements like Datagrids and observe the Z-Index issue.

###Expected Behavior:
The ComboBox should generate cleaner source code without redundant or unnecessary inline styles.
The ComboBox's listbox should have a higher Z-Index to ensure it is displayed on top of other UI elements when expanded.

### Additional Information:
Fluent UI Blazor version: 3.2.0

**Comment by vnbaaij** [comment]
Hi,

The styling tags are being generated by the web component that we wrap. We can't change anything there for now. Once it is changed in the web component, those changes will flow to our library as well.

With regards to the z-index, we are setting the z-index of the 'popup' to a value of 9995 in the code on rendering the component. But this is only done if the `Height` parameter is set. Can you try with a value set for the height parameter and report back if that solves your use case. If not, please supply us a concrete example of where it goes wrong.

Closing this for now as there is no immediate action from our side. Will re-open if you report the Height setting is not giving you the correct result.

**Comment by vnbaaij** [comment]
See my comment at https://github.com/microsoft/fluentui-blazor/issues/2029#issuecomment-2105729913. Can you try with that?

**Comment by joriverm** [comment]
> See my comment at [#2029 (comment)](https://github.com/microsoft/fluentui-blazor/issues/2029#issuecomment-2105729913). Can you try with that?

i added these to the style of the combobox & the listbox div in it's shadowroot : 
```
content-visibility: visible;
contain: style;
```
and it didn't fix it sadly
![image](https://github.com/microsoft/fluentui-blazor/assets/87806863/99e78480-29e5-4b4d-9874-7d49c0bf4784)

seeing the code of the combobox ( https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/List/FluentCombobox.razor ) , im starting to think its part of the webcomponents that needs adjusting?

**Comment by vnbaaij** [comment]
Could be. I vaguely remember this has been called out before and that we couldn't fix it then either. Not able to look at it more closely for a couple of days

**Comment by joriverm** [comment]
"Good" News @vnbaaij !
i made a codepen using just the webcomponents, and i think its an issue there after all. could you look at https://codepen.io/joriverm/pen/LYoVNwm and see if you see an issue? if not, i will make an issue on the fluentui webcomponents repository

**Comment by vnbaaij** [comment]
Codepen looks good. Just use the latest wc script version (2.6.1)

**Comment by sybren2** [comment]
> i added these to the style of the combobox & the listbox div in it's shadowroot :
> 
> ```
> content-visibility: visible;
> contain: style;
> ```
> 
> and it didn't fix it sadly

For others reading this, a workaround is mentioned on https://github.com/microsoft/fluentui/issues/31359

The following worked for me:

```
<TemplateColumn Title="MyColumn" Style="overflow:visible">
```
The style will be added to each \<td\> that is generated from the TemplateColumn.
