### ISSUE TITLE
fix: Navigation Issues in FluentHorizontalScroll 

### ISSUE THREAD

**Issue by AlthalusDGr8** [microsoft/fluentui-blazor#889]
# 🐛 Bug Report

On Edge and Chrome , FluentHorizontalScroll not moving elements in the correct direction and stops working altogether after the first event. This happens also when I enable external navigation. Same code on Firefox works properly.

Videos of the issue can be seen here (includes behaviour on edge and firefox): 
Edge
https://github.com/microsoft/fluentui-blazor/assets/13330897/7c61ec26-0284-487b-a8ba-cb2ba4b0d08b

FireFox
https://github.com/microsoft/fluentui-blazor/assets/13330897/9609d56c-de4c-4162-a7fb-f52f3e3da264

## 💻 Repro or Code Sample
```
 <div style="display:grid; align-items:center;">
     <FluentLabel Typo="Typography.H4">Change To</FluentLabel>
     <FluentHorizontalScroll Speed="500" View="HorizontalScrollView.Mobile" Easing="ScrollEasing.EaseInOut" Style="max-width:475px; padding-left:12px; padding-right:12px;" @ref="_horizontalScroll">
         @if ((OtherParts != null) && (OtherParts.Any()))
         {
             @foreach (var part in OtherParts)
             {
                 <RobotPartComponent RobotPartModel="part" />
                 <br />
                 @* <button @onclick="@(() => ReplaceRobotPart(part.UniqueCode, part.TypeCode))">Append @ComponentTypeDisplayName</button> *@
             }
         }
     </FluentHorizontalScroll>
     <FluentFlipper Direction="FlipperDirection.Previous" @onclick="() => _horizontalScroll.ScrollToPrevious()" />
     <FluentFlipper Direction="FlipperDirection.Next" @onclick="() => _horizontalScroll.ScrollToNext()" />
 </div>
``` 

## 🤔 Expected Behavior

Works the same across browsers :)

## 🔦 Context

I am trying to create a scrollable list of items 

## 🌍 Your Environment

* OS & Device: WIndows 11 22H2, PC
* Browser: Edge  118.0.2088.61, Firefox 118.0.2 (64-bit)
* .NET and FAST Version : Net 7, Microsoft.Fast.Components.FluentUI  Version="3.2.0"

**Comment by AlthalusDGr8** [comment]
Note that this behaviour is also present using mobile navigation

**Comment by ggomarighetti** [comment]
Have you tried using a FluentButton to replace the FluentFlipper?

Reviewing the webcomponent wrapper of the flipper, I noticed that unlike the FluentButton, it doesn't have the onclick action referenced.

The association that you are doing in your code, is provided by default by Blazor in all the components that are developed, but it does not guarantee that the call will be effective.

While in the FluentButton component it does have an EventCallback where it is notified when the button is clicked.

**Comment by vnbaaij** [comment]
As suggested by @ggomarighetti (thanks!) you indeed need to use buttons for this. See https://www.fluentui-blazor.net/HorizontalScroll#externalnavigation

**Comment by AlthalusDGr8** [comment]
Hi sorry was a bit away and could not respond.  So i tried with buttons as suggested (see code below) but the same thing is happening
`  <div style="display:grid; align-items:center;">
      <FluentLabel Typo="Typography.H4">Change To</FluentLabel>
      <FluentHorizontalScroll Speed="500" View="HorizontalScrollView.Mobile" Easing="ScrollEasing.EaseInOut" Style="max-width:475px; padding-left:12px; padding-right:12px;" @ref="_horizontalScroll">
          @if ((OtherParts != null) && (OtherParts.Any()))
          {
              @foreach (var part in OtherParts)
              {
                  <RobotPartComponent RobotPartModel="part" />
                  <br />
                  @* <button @onclick="@(() => ReplaceRobotPart(part.UniqueCode, part.TypeCode))">Append @ComponentTypeDisplayName</button> *@
              }
          }
      </FluentHorizontalScroll>
      <FluentButton Appearance="Appearance.Accent"  @onclick="() => _horizontalScroll.ScrollToPrevious()" Style="align-content:center">
          Prev
      </FluentButton>
      <FluentButton Appearance="Appearance.Accent" @onclick="() => _horizontalScroll.ScrollToNext()" Style="align-content:center">
          Next
      </FluentButton>        
  </div>`


https://github.com/microsoft/fluentui-blazor/assets/13330897/6f11ed56-f6f3-4640-a1e5-e71b8bc1bc92

**Comment by vnbaaij** [comment]
Your problem might be caused by the fact thet you are using a `for` loop inside the horizontal scroll. I suggest to look at (for example):
- https://blazor-university.com/components/render-trees/optimising-using-key/
- https://shauncurtis.github.io/Building-Blazor-Applications/For-ForEach-in-Blazor.html
- https://learn.microsoft.com/en-us/aspnet/core/blazor/components/element-component-model-relationships?view=aspnetcore-7.0
-
