### ISSUE TITLE
docs: add v3.2.2 to GitHub Releases

### ISSUE THREAD

**Issue by amis92** [microsoft/fluentui-blazor#893]
# 🙋 Documentation Request

Release v3.2.2 is not published on GitHub as a Release nor as a Tag.

## 💁 Possible Solution

Create the release (if it's automated, check if automation isn't broken).

**Comment by vnbaaij** [comment]
Done! https://github.com/microsoft/fluentui-blazor/releases/tag/v3.2.2

(ps it is not automated :))
