### ISSUE TITLE
fix: Stock component (Card) styling not matching the demos/samples

### ISSUE THREAD

**Issue by erikplestenjak** [microsoft/fluentui-blazor#894]
# 🐛 Bug Report
Using blazor server, this is how a FluentUI card looks like with everything else being stock:
![image](https://github.com/microsoft/fluentui-blazor/assets/3017768/8a0d3268-fc35-4b1f-8a9a-4744035d7fba)

This is how it looks like on the [demo site](https://www.fluentui-blazor.net/Card):
![image](https://github.com/microsoft/fluentui-blazor/assets/3017768/a652a9a0-7bbc-44ca-b320-55c1050d74d2)

Custom css on the demo site:
![image](https://github.com/microsoft/fluentui-blazor/assets/3017768/aa653092-20a9-4726-9b9e-c7fa640bc629)

In [the documentation](https://learn.microsoft.com/en-us/fluent-ui/web-components/components/card?pivots=blazor) under blazor sample, there is some additional css:

![image](https://github.com/microsoft/fluentui-blazor/assets/3017768/e69e9142-daed-4452-9031-a85f00d53c78)
namely 
`    .card-padding {
        padding: 20px;
    }`

## 💻 Repro or Code Sample

So with bone stock unmodified framework loaded, this code reproduces the issue:
`
<FluentCard>
    <h2>Hello World!</h2>
    <FluentButton Appearance="@Appearance.Accent">Click Me</FluentButton>
</FluentCard>
`

## 🤔 Expected Behavior

On of the most basic components of the framework (**Card**), to render as in the demo/sample without additional tweaking of the css.

## 😯 Current Behavior

It's not possible to use the library as blazor components, since you never know what css style is missing. Even the Blazor FluentUI ready templates, are not using blazor FluentUI components, but rather librarys css and HTML directly, which is then additionally patched using "site.css" of the template.

## 💁 Possible Solution

Apart from giving the card some preset padding (20px seems to be the norm in demos), that can be overriden using tokens/variables if needed. 

An actual solution would be, to simply remove **site.css** from all the demo pages. That way, it would be clear that, what we see is what we get. If it's not possible to create a simple demo site without extensive overriding of the stock styling to make it look semi-decent, then the framework is not ready for use.

**Comment by vnbaaij** [comment]
I am currently working on restyling/renewing the templates for the next version of the library. When the current templates were created we didn't have the layout components at our disposal yet.

This is what a template created app will (roughly) look like. The design not totally finished yet: 
<img width="389" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/d89417d7-75eb-4f42-8234-580a468e5e37">

We are also working on getting the styling for the fluent-card fixed by using some sensible defaults out of the box.
> It's not possible to use the library as blazor components, since you never know what css style is missing. Even the Blazor FluentUI ready templates, are not using blazor FluentUI components, but rather librarys css and HTML directly, which is then additionally patched using "site.css" of the template.

> An actual solution would be, to simply remove site.css from all the demo pages. That way, it would be clear that, what we see is what we get. If it's not possible to create a simple demo site without extensive overriding of the stock styling to make it look semi-decent, then the framework is not ready for use.

We are not going to do that. There is definitely room for improvement and we are working on that. Criticism is ok of course, but overall I find the tone of your comments a bit too negative. Maybe use those keystrokes for sending some PRs with fixes our way?

**Comment by erikplestenjak** [comment]
Thank you for the quick reply. Good to hear you are on track with the improvements. I do apologize for the tone. I wanted to use the framework on a new project with relatively tight deadline. Considering this is Microsofts own framework used on Microsofts .NET blazor technology and the version being 3.2, I was not prepared for dealing with such basic issues right out of the box. It seemed a bit more mature just looking at the demo.

Great news on the templates. Regarding the demo I can agree to dissagree.

As for the PRs, I'm currently not in a position to invest time for the fixes. Hopefully that changes in the future and I can make some contribution.

**Comment by vnbaaij** [comment]
This is what the card will be in the next (v3.2.3) version: https://preview.fluentui-blazor.net/Card

Closing this issue as the original problem is solved now.
