### ISSUE TITLE
feat: add `Class` attribute to dialogs created using `DialogService`

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#896]
# 🙋 Feature Request

Since I'm using Tailwind for styling, I want to add some classes to a panel created using the `DialogService` to make its width responsive. However, this is currently not possible.

## 💁 Possible Solution

`DialogParameter`s should have an additional attribute `Class` that gets applied to the control part of a dialog.

**Comment by dvoituron** [comment]
Why not to create a [Customized Dialog](https://www.fluentui-blazor.net/Dialog#customizeddialog) where you have all possibilities to add your styles and classes?

**Comment by vnbaaij** [comment]
Workaround provided. Closing this

**Comment by Linkens** [comment]
I can't find a way to remove the Dialog Padding, even with a customized dialog

**Comment by dvoituron** [comment]
You can use a style like this:
```html
<style>
    fluent-dialog::part(control) {
        padding: 0px !important;
    }
</style>
```
