### ISSUE TITLE
feat: Allow background to be interacted with when dialog is visible

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#897]
# 🙋 Feature Request

When a dialog is visible, the positioning-region part of the dialog prevents interaction with elements in the background of the page. Especially for panels this is annoying, as we want to keep a panel open while still working with other elements.

## 🤔 Expected Behavior

Background elements should be interactable if desired.

## 😯 Current Behavior

Background elements can't be interacted with when a dialog is visible.

## 💁 Possible Solution

Add a new attribute `BackgroundLocked` (or similar) to dialogs that allows backgrounds to be interacted with. If the background is not locked, add a 'pointer-events: none' to the positioning-region and 'pointer-events: all' to the control part of the dialog.

**Comment by dvoituron** [comment]
I don't think it's good practice to open a dialog box and allow the user to interact with the elements below it. This could have undesirable effects, for example, if the user opens a Combobox or similar components.

To enable the user to manipulate data in two different panels, it is preferable to define two distinct DIV zones, one of which is displayed according to certain criteria. For example, using a [FluentGrid](https://www.fluentui-blazor.net/Grid)  or a [FluentSplitter](https://www.fluentui-blazor.net/Splitter)
