### ISSUE TITLE
fix: Column resizing in Data-Grids breaks if column is made too small

### ISSUE THREAD

**Issue by acrow59** [microsoft/fluentui-blazor#911]
# 🐛 Bug Report

When ResizableColumns is enabled, if the column width is not wider than the column label text or if the column is resized to be smaller than the column label text, the divider between columns disappears and the column can no longer be resized.

## 💻 Repro or Code Sample

This can be seen in the Typical Usage example of the documentation by shrinking the columns for Rank, Name of Country, Gold, or Silver.
![image](https://github.com/microsoft/fluentui-blazor/assets/5883501/ec8b6bc0-9ed3-42e0-8499-016102dac52d)

## 🤔 Expected Behavior

The handle for resizing columns should always be visible.

**Comment by vnbaaij** [comment]
Hi,

I made some changes in the styling and resizing logic. 
- The button text (when a column is sortable) now shows ellipses when the button is resized to be smaller than the text content.
- The minimal width of a button is now taking the presence of an option button into account. In case there is an option button, minimum width is now 75px. For other columns it stays at 50px
- I've made the draghandle a tiny bit wider so selecting and dragging it should we a bit easier.

This is what the result looks like (screengrab does not show the drag handle 😞):
![DataGrid-Resizing](https://github.com/microsoft/fluentui-blazor/assets/1761079/a032969b-16ef-4936-9791-dfe547c1d794)

**Comment by DalamarX** [comment]
Using 4.7.1 I am seeing the original behavior where if the splitter is dragged back over the column text, the splitter disappears and I can no longer resize.  The thing happens on the Custom comparer example at [https://www.fluentui-blazor.net/DataGrid](url)

**Comment by vnbaaij** [comment]
Although that is a unpleasant effect, you can now use 'Shift+r' to reset the column widths, use '-' to decrease column sie and use '+' to increase size. With that we have a workaround for this (for now)
