### ISSUE TITLE
Enhancement: Improve Side Menu Aesthetics by Changing Background Color to White

### ISSUE THREAD

**Issue by mahald** [microsoft/fluentui-blazor#914]
Just a small note, but it hurts my eyes every time I see the side menu and the grey background. It would look 10 times better if it was simply white. In the site.css, changing the nav from:

```
nav {
    z-index: 1;
    padding: 2.5rem 1.5rem;
    background-color: var(--neutral-layer-3);
    transition: all 300ms ease-in-out;
    grid-column: 1 / 2;
}
```

to:

```
nav {
    z-index: 1;
    padding: 2.5rem 1.5rem;
    box-shadow: 0px 2px 1px -1px rgba(0,0,0,0.2),0px 1px 1px 0px rgba(0,0,0,0.14),0px 1px 3px 0px rgba(0,0,0,0.12);
    transition: all 300ms ease-in-out;
    grid-column: 1 / 2;
}
```

would make it look so much better.

I have never seen a grey background with white boxes in the menu anywhere else.

now:
![image](https://github.com/microsoft/fluentui-blazor/assets/6714894/6b08fe8c-efc9-4f27-8622-da14650b8198)

with suggested changes:
![image](https://github.com/microsoft/fluentui-blazor/assets/6714894/08de3efd-dbe1-4f98-beb9-995c86d7f184)

compare Azure:
![image](https://github.com/microsoft/fluentui-blazor/assets/6714894/e0320b4a-9d9a-4cb9-95db-95a0b148fe5b)

compare outlook:
![image](https://github.com/microsoft/fluentui-blazor/assets/6714894/a7012d01-bcc4-4856-bbe4-5ba831645403)

**Comment by vnbaaij** [comment]
We are thinking about it. Although it will not be white but just a tad off, just as the background for the content is now
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/db0320cc-027c-4768-a5f9-e675917e391d)

**Comment by vnbaaij** [comment]
Implemented on preview site. Live will follow asap
