### ISSUE TITLE
Setting height on Dialog gets overriden.

### ISSUE THREAD

**Issue by Rocky-25** [microsoft/fluentui-blazor#915]
# 🐛 Bug Report

When setting the height on a dialog and having the alignment set to Center the height property is overridden with height:auto.

## 💻 Repro or Code Sample

```
          IDialogReference dialog = await DialogService.ShowDialogAsync(typeof(SearchDialog<T>), request, new DialogParameters()
          {
              Title = ModalTitle ?? "Search",
              Alignment = HorizontalAlignment.Center,
              Width = "90vw",
              Height = "90vh"
          });
```

## 🤔 Expected Behavior

Should be set to the height requested.

## 😯 Current Behavior

Is set to auto.

![image](https://github.com/microsoft/fluentui-blazor/assets/52032850/60eba19e-fe1f-43f8-964d-d86d1c7b9fe6)

**Comment by vnbaaij** [comment]
Hi,

I'm have a bit of trouble getting this reproduced. Can you post a working minimal reproduction sample? Also, what version are you seeing this with?

**Comment by Rocky-25** [comment]
This is using 3.2.2. I'll try to generate a minimal repo.
