### ISSUE TITLE
feat: Ability to specify Class on DialogParameters

### ISSUE THREAD

**Issue by softinvent-cto** [microsoft/fluentui-blazor#916]
# 🙋 Feature Request

I want to create a fly-in panel using the DialogService. Furthermore I need to control the top position (and size) of the panel.
The best way I recon that can be done is by adding a supplementary class to the `<fluent-dialog />` component and control it from css.

## 🤔 Expected Behavior

That I can write something like:
`
await DialogService.ShowPanelAsync<MyPanel>(data, new DialogParameters<MyEditModel>
{
	Class = "my-custom-dialog-class",
	...
});
`
and the fluent-dialog is rendered as

`<fluent-dialog class="fluent-dialog-main my-custom-dialog-class" ...></fluent-dialog>`

## 😯 Current Behavior

Currently there is now way, as I see it, to specify a custom class on a fluent-dialog.

## 💁 Possible Solution

Add `public string? Class { get; set; }` to DialogParameters and have the DialogService render it.

**Comment by dvoituron** [comment]
Hi,

We could add an attribute `DialogBodyClass` like we already have ´DialogBodyStyle´, but you could create a Customized Dialog like described here: https://www.fluentui-blazor.net/Dialog#customizeddialog

Is this a solution for you?

**Comment by vnbaaij** [comment]
No need to add extra code then. Requested functionality can be achieved with current means. Closing this
