### ISSUE TITLE
fix: FluentNavGroups don't expand in 4.0.0-rc.1 Blazor Server

### ISSUE THREAD

**Issue by iotalambda** [microsoft/fluentui-blazor#922]
# 🐛 Bug Report

FluentNavGroups don't expand in 4.0.0-rc.1 Blazor Server. If setting rendermode = InteractiveServer, then they do, but then the FluentNavLink/FluentNavGroup caret does not follow the active route anymore.

## 💻 Repro or Code Sample

1. `dotnet new install Microsoft.FluentUI.AspNetCore.Templates::4.0.0-rc.1`
2. `dotnet new fluentblazor -o Test`
3. replace NavMenu.razor contents with this:
```
<nav>
    <FluentNavMenu Width="250" Collapsible="true" Title="Custom navigation menu">
        <FluentNavLink Href="/" Match="NavLinkMatch.All" Icon="@Icon.FromImageUrl("/images/home.svg")" IconColor="Color.Accent">Home</FluentNavLink>
        <FluentNavGroup Href="counter" Title="Counter" Icon="@Icon.FromImageUrl("/images/counter.svg")" IconColor="Color.Accent">
            <FluentNavLink Href="weather" Icon="@Icon.FromImageUrl("/images/weather.svg")" IconColor="Color.Accent">Weather</FluentNavLink>
        </FluentNavGroup>
    </FluentNavMenu>
</nav>
```
4. Click the chevron next to "Counter"

## 🤔 Expected Behavior

The group should expand

## 😯 Current Behavior

The group does not expand

**Comment by agriffard** [comment]
I can confirm (I was about to create the same issue).

Also, the menu should be responsive on small screens, as in the demo site.

**Comment by agriffard** [comment]
`App.razor` needs an InteractiveServer rendermode, I think:

Currently:

```
    <HeadOutlet />
</head>

<body>
    <Routes />
```

Fix:

```
    <HeadOutlet @rendermode="@RenderMode.InteractiveServer" />
</head>

<body>
    <Routes @rendermode="@RenderMode.InteractiveServer" />
```

**Comment by agriffard** [comment]
Active links seem to keep on working:

![Animation](https://github.com/microsoft/fluentui-blazor/assets/703248/63d4f652-f6dd-4dbf-b481-ca8c7a232d4e)

**Comment by vnbaaij** [comment]
Ok, couple of things here. If you create a project as described in the repo steps (`dotnet new fluentblazor -o Test`) the **default** rendermode will be **SSR**. This is the same as with the out-of -the-box VS template (Blazor Web App)

Things like expand/collapse will obviously not work then so this is not an error/issue in the template. If you want this behavior, you'll need to change some code like @agriffard did here https://github.com/microsoft/fluentui-blazor/issues/922#issuecomment-1793467065. 

If you want this to work from the start, you'll need to use some extra commands when creating the project with the template. This is what you can do:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/741e5eb2-3987-4e33-9c69-c52d0b670738)

Use `dotnet new fluentblazor -?` to get this output. All of this can be worked with when creating a new project in Visual Studio as well.

The settings you'd want to play with `-int` and/or `-ai`. Changing these will alter the output the template generates!

What is an error, is that the menu then has the `Collapse=true` parameter. I'll change that.

**Comment by iotalambda** [comment]
@vnbaaij _What is an error, is that the menu has the Collapse=true parameter in the SSR variant. I'll change that._

Ok, great. It surely seemed a bit off.

And thanks @agriffard for the clue on how to set the render mode appropriately.
