### ISSUE TITLE
4.0.0-rc1 Wasm Template errors

### ISSUE THREAD

**Issue by agriffard** [microsoft/fluentui-blazor#923]
When you try the `fluentblazorwasm` template, there is an error because there is a LoginDisplay.razor.css without the LoginDisplay.razor file.

`The scoped css file 'Layout\LoginDisplay.razor.css' was defined but no associated razor component or view 
was found for it.`

Then, another error because the service-worker.js is missing in wwwroot:

`Could not copy the file "wwwroot\service-worker.js" because it was not found.`

**Comment by vnbaaij** [comment]
Yes, seen that one. Will fix for next version
