### ISSUE TITLE
W3C links

### ISSUE THREAD

**Issue by agriffard** [microsoft/fluentui-blazor#925]
It seems that the links you made to W3C ARIA patterns pages lead to a page like this: 
https://w3c.github.io/aria-practices/#accordion

![image](https://github.com/microsoft/fluentui-blazor/assets/703248/bdf75341-4dee-46a5-8ef3-66967b01fb92)

while you could use a direct link like this:
https://www.w3.org/WAI/ARIA/apg/patterns/accordion/

![image](https://github.com/microsoft/fluentui-blazor/assets/703248/53a9dce1-94c7-4030-9d2a-9c198d2fa16e)

**Comment by vnbaaij** [comment]
Were is that link?

**Comment by agriffard** [comment]
https://www.fluentui-blazor.net/Accordion

and many other pages:
https://github.com/search?q=repo%3Amicrosoft%2Ffluentui-blazor+https%3A%2F%2Fw3c.github.io&type=code
