### ISSUE TITLE
Comments format

### ISSUE THREAD

**Issue by agriffard** [microsoft/fluentui-blazor#930]
The comments should all begin by `Gets or sets the ...` or directly by `The ...`, but it would be better to be consistent and not have a mix:

https://www.fluentui-blazor.net/Stack#fluentstack-class_properties

![image](https://github.com/microsoft/fluentui-blazor/assets/703248/820258f6-67f5-4640-b5d2-643355b210e0)

**Comment by dvoituron** [comment]
I agree with you. It's best to be consistent and always use the "Gets or sets...`" format.
Could you update these descriptions in your PR #929?

**Comment by agriffard** [comment]
Sorry but it is not only on this one. 
There are too many occurences (almost all components are not consistent) to include them in my PR that fixes typos.

It would be better to make this changes by core contributors.

**Comment by vnbaaij** [comment]
I also agree that it is better to be consistent, but this is too much of a change to spend a lot of time on now. 

We will add it to our "coding guidelines" and be more vigilant in enforcing it from now on. If and when we revisit classes/properties for changes and/or updates, we will make the changes along the way.
