### ISSUE TITLE
v3.3.0 DemoPage Error (TextField, TextArea, NumberField)

### ISSUE THREAD

**Issue by tomokusaba** [microsoft/fluentui-blazor#934]
# 🐛 Bug Report

v3.3.0 DemoPage Error (TextField, TextArea, NumberField)
I don't see anything
## 🤔 Expected Behavior
Make sure that the demo page is displayed normally

## 😯 Current Behavior
I don't see anything

## 💁 Possible Solution
Readonly -> ReadOnly

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by dvoituron** [comment]
Hi,
The `ReadOnly` property has been correctly renamed in [v4.0.0-rc.1](https://fluentui-blazor.net/WhatsNew#v4.0.0-rc.1)

**Comment by vnbaaij** [comment]
And also in 3.3.0. Samples have been fixed
