### ISSUE TITLE
MessageBar will not display

### ISSUE THREAD

**Issue by grumpykiwi** [microsoft/fluentui-blazor#935]
# 🐛 Bug Report

MessageBar will not display. Error is displayed instead.

InvalidOperationException: Cannot provide a value for property 'MessageService' on type 'PCPortal.Fluent4.Components.Pages.Timesheets.Index'. There is no registered service of type 'Microsoft.Fast.Components.FluentUI.IMessageService'.

## 💻 Repro or Code Sample

MainLayout.razor

I have placed the following in the file.

```
<FluentBodyContent Style="background: #f7f9fc; height: 100%!important;">
	<FluentMessageBarProvider Section="MESSAGES_TOP" ClearAfterNavigation="true" MaxMessageCount="5" />
		<div style="width: 97%; height: 94%; margin: 25px; background-color: white; padding: 25px;">
			@Body
		</div>
	<FluentToastProvider MaxToastCount="5" Position="Microsoft.FluentUI.AspNetCore.Components.ToastPosition.TopCenter" ShowCloseButton="true" RemoveToastsOnNavigation="true" />
</FluentBodyContent>
```

Index.razor.cs

`[Inject] IMessageService MessageService { get; set; }`

And the calling code:

`await MessageService.ShowMessageBarAsync("Timesheet has already been posted", MessageIntent.Error);`

## 🤔 Expected Behavior

The message should display

## 😯 Current Behavior

When trying to run the site in debug mode, I get the above error at startup

## 🔦 Context

Trying to provide useful feedback to the user. Had the same issue when trying to use the Toast Service. Following the guidance with the Inject for that. Yet again the ToastService could not be found. 

The call to AddFluentUIComponents is in program.cs after the call to AddHttpClient

## 🌍 Your Environment

Windows 11 23H2
VS 2022 Version 17.8.0 Preview 6.0
MS Edge / .Net 8.0 project using the FluentUI 4.0 Interactive Server project template

**Comment by vnbaaij** [comment]
Hi,

We need a repo to be able to look at what is causing the issue and can get more details. You say you used v4 template yet the error shows a relation with Fast (which is v3)

**Comment by vnbaaij** [comment]
Ive made quite some changes to the templates after rc1 build. We plan to upload rc2 builds soon (as in about an hour). Maybe try again with those packages? Remember to uninstall the rc1 templates first:
```
dotnet new uninstall Microsoft.FluentUI.AspNetCore.Templates
