### ISSUE TITLE
fix: EditForm with submit outside form fails

### ISSUE THREAD

**Issue by softinvent-cto** [microsoft/fluentui-blazor#940]
Given the below contents of a dialog component with an EditForm that has its submit button outside of the form, causes the following DOMException in web-components.min.js: 

`Uncaught DOMException: Failed to execute 'requestSubmit' on 'HTMLFormElement': The specified element is not owned by this form element.`

Is should be possible to place a submit button outside of its form according to HTML5.

```html
<FluentDialogHeader>
        <h4>Title</h4>
</FluentDialogHeader>
<FluentDialogBody>
    <EditForm id="editForm" Model="Content" OnValidSubmit="OnSaveAsync">
		<div>
			<FluentLabel>Name</FluentLabel>
			<FluentTextField Autofocus="true" @bind-Value="@Content.Name" />
		</div>
		<div>
			<FluentLabel>Notes</FluentLabel>
			<FluentTextArea Rows="10" Cols="60" @bind-Value="@Content.Notes" />
		</div>
        <DataAnnotationsValidator />
    </EditForm>
</FluentDialogBody>
<FluentDialogFooter>
    <FluentButton FormId="editForm" Type="ButtonType.Submit" Appearance="Appearance.Accent">Save</FluentButton>
    <FluentButton OnClick="OnCancelAsync">Cancel</FluentButton>
</FluentDialogFooter>
```

or am I doing something wrong?

**Comment by vnbaaij** [comment]
Hi, 

In the future, please make sure you post a minimal working repo we can use to investigate...


By doing it like this:
```
<FluentDialog Hidden=false>
    <EditForm id="editForm" Model="Content" OnValidSubmit="OnSaveAsync">

<FluentDialogHeader>
        <h4>Title</h4>
</FluentDialogHeader>
<FluentDialogBody>
		<div>
			<FluentLabel>Name</FluentLabel>
			<FluentTextField Autofocus="true" @bind-Value="@Content.Name" />
		</div>
		<div>
			<FluentLabel>Notes</FluentLabel>
			<FluentTextArea Rows="10" Cols="60" @bind-Value="@Content.Notes" />
		</div>
        <DataAnnotationsValidator />
</FluentDialogBody>
<FluentDialogFooter>
    <FluentButton FormId="editForm" Type="ButtonType.Submit" Appearance="Appearance.Accent">Save</FluentButton>
    <FluentButton OnClick="OnCancelAsync">Cancel</FluentButton>
</FluentDialogFooter>
    </EditForm>
</FluentDialog>
@code {
    public class ContentClass
    {
        public ContentClass()
        {
        }

        public string? Name { get; set; }
        public string? Notes { get; set; }
    }

    private ContentClass Content { get; set; } = new ContentClass();
	
    private void OnSaveAsync()
	{
		      // Save
	}

	private void OnCancelAsync()
    {
              // Cancel
    }
}
```
Filling the form and then clicking save brings me to the `OnSaveAsync` method

**Comment by kamazheng** [comment]
I met this problem also. 
When this error occur, I found the browser has warning, 'button[part]' is not supported by Firefox for Android.:
![image](https://github.com/microsoft/fluentui-blazor/assets/49426393/105d055f-c277-447c-a2ff-a0faa2de08c5)

It's not always wrong, when it works, there's no this error. When you refresh the page, it sometimes works.
Strange.

Any solution? put the button inside the form, sometimes is not clean for the layout.

**Comment by vnbaaij** [comment]
> I met this problem also. When this error occur, I found the browser has warning, 'button[part]' is not supported by Firefox for Android.: ![image](https://private-user-images.githubusercontent.com/49426393/335995159-105d055f-c277-447c-a2ff-a0faa2de08c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTAyOTgsIm5iZiI6MTcxNzQwOTk5OCwicGF0aCI6Ii80OTQyNjM5My8zMzU5OTUxNTktMTA1ZDA1NWYtYzI3Ny00NDdjLWEyZmYtYTBmYWEyZGUwOGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNzIwNjQ5MWFhZjRmMjMyYTViYmM1ZDQ4YTI3ZmM2MDk3M2M3ODQzYjgxMGVjN2FhMjQwZTE1OWUxYWVjZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jicrGxYvVBt-AQPTuBfJorbxVKNPECiQQ5oF0tHOqYU)
> 
> It's not always wrong, when it works, there's no this error. When you refresh the page, it sometimes works. Strange.
> 
> Any solution? put the button inside the form, sometimes is not clean for the layout.

See #1205 and especially https://github.com/microsoft/fluentui-blazor/issues/1205#issuecomment-1870432561

**Comment by kamazheng** [comment]
> > I met this problem also. When this error occur, I found the browser has warning, 'button[part]' is not supported by Firefox for Android.: ![image](https://private-user-images.githubusercontent.com/49426393/335995159-105d055f-c277-447c-a2ff-a0faa2de08c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTAyOTgsIm5iZiI6MTcxNzQwOTk5OCwicGF0aCI6Ii80OTQyNjM5My8zMzU5OTUxNTktMTA1ZDA1NWYtYzI3Ny00NDdjLWEyZmYtYTBmYWEyZGUwOGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNzIwNjQ5MWFhZjRmMjMyYTViYmM1ZDQ4YTI3ZmM2MDk3M2M3ODQzYjgxMGVjN2FhMjQwZTE1OWUxYWVjZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jicrGxYvVBt-AQPTuBfJorbxVKNPECiQQ5oF0tHOqYU)
> > It's not always wrong, when it works, there's no this error. When you refresh the page, it sometimes works. Strange.
> > Any solution? put the button inside the form, sometimes is not clean for the layout.
> 
> See #1205 and especially [#1205 (comment)](https://github.com/microsoft/fluentui-blazor/issues/1205#issuecomment-1870432561)

I've already add both formid and buttonId for the button, it's not always work.  It has chance not working when the browser has warning of "'button[part]' is not supported by Firefox for Android.", when you refresh the page, it might work again.
