### ISSUE TITLE
feat: Make Height and Width optional for FluentCard 

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#945]
# 🙋 Feature Request

In V2 Height and Width where optional for Card and that worked very well. 

 https://calm-sea-053fa6a03-archivesv2.westeurope.3.azurestaticapps.net/Card

For V3 a default value is 350 pixels for both Height and Width.

https://calm-sea-053fa6a03-archivesv3.westeurope.3.azurestaticapps.net/Card

To enable a card to grow based on its content you therefore need to set `<FluentCard Width="" Height=""`. This feels redundant and I think the old functionality worked better.

**Comment by vnbaaij** [comment]
If I make them optional (which is easy to do) this means the Height would indeed adjust to content. For the Width the default value of 100% from the web component style will be used. So you would get this:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/7678998e-c803-4655-b243-5c4852da8ef8)

**Comment by dvoituron** [comment]
I also prefer to have "empty" values by default, which will give a dynamic height and width of 100%.

**Comment by vnbaaij** [comment]
Ok, default width and height be gone! (in the next version)

**Comment by Ogglas** [comment]
@vnbaaij Great! :)

**Comment by ApacheTech** [comment]
I have hundreds of cards that have suddenly been forced to 350px square. All of them. `--card-width` and `--card-height` are set to `350px` within the `style` tag for every card. How do I stop this, for every card on the site; current, and future? How do you get rid of `--card-width` and `--card-height`?
