### ISSUE TITLE
The latest version does not have HostingModel as a member

### ISSUE THREAD

**Issue by ssccinng** [microsoft/fluentui-blazor#950]
# 🐛 Bug Report
![image](https://github.com/microsoft/fluentui-blazor/assets/22047352/0b49fec3-351c-4458-bd12-84aaaf8ab519)
![image](https://github.com/microsoft/fluentui-blazor/assets/22047352/9b7efdd5-c767-4e38-b510-c0ce6d23fa7e)

## 💻 Repro or Code Sample

builder.Services.AddFluentUIComponents(option =>
{
    option.HostingModel = BlazorHostingModel.Server;
});

## 🌍 Your Environment

4.0.0-rc.3

**Comment by vnbaaij** [comment]
Correct, this is not needed anymore and should be removed from your code. We have already changed the docs for this and the will go live on next publish.
