### ISSUE TITLE
There is no element with id="container".

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [microsoft/fluentui-blazor#953]
Both in the files `MainLayout.razor.js` and `theme.js` there is a function called `switchDirection` that it is meant to switch the direction RTL/LTR. Both try to access `const container = document.getElementById('container');`, but there is no `container` element. I wonder if it is a typo or some naming changed along the way. My guess is that the root node `<div @ref="_container">` once in a time had a `id="container"` attribute.

Also, there are two `switchDirection` javascript functions in these two separate files. If they do the same thing, maybe a refactor would be a good idea.

**Comment by vnbaaij** [comment]
Refactor it is! None of the two `switchDirection` js functions were being used anymore. I've removed them.

**Comment by benjaminsampica** [comment]
As a small note, there's also a css style for `body, #container` too. Seems like this should just be `body`.
