### ISSUE TITLE
FluentCheckbox or FluentSwitch does not show correct first checked state in EditForm

### ISSUE THREAD

**Issue by michaelc06** [microsoft/fluentui-blazor#956]
# 🐛 Bug Report

The checked state does not show on first check when  `FluentCheckbox` or `FluentSwitch` is used in `EditForm`. Clicking on it 3 times will show the correct checked state.

## 💻 Repro or Code Sample

[Counter.razor.txt](https://github.com/microsoft/fluentui-blazor/files/13348267/Counter.razor.txt)

## 🤔 Expected Behavior

Show the correct checked state.

## 😯 Current Behavior

Not showing the correct checked state on first check.

## 💁 Possible Solution
Workaround: use `checked` and `onchange` instead of `@bind-Value`

`<FluentCheckbox checked="@Content.IsChecked"
        @onchange="@(() => Content.IsChecked = !Content.IsChecked)">Check test</FluentCheckbox>`

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser: Microsoft Edge, Google Chrome, Mozilla FireFox, Opera
* .NET6.0 and Microsoft.Fast.Components.FluentUI Version 3.3

**Comment by ggomarighetti** [comment]
As far as I understand, you have in a blazor component, an editform which has as context the variable `Content` of type `TestData`, which to initiate it or to load it, in the cases in which you request the information and `IsChecked` returns `true`, the checkbox corresponding to that property, is not represented selected.

The code that you passed, as far as I understand, is a reference code and not the real case where your problem happens, so, I recommend you to check, if after loading the information in a possible `OnInitializedAsync` or `OnAfterRenderAsync` method, check that at the end you execute a `StateHasChanged()` or `InvokeAsync(StateHasChanged)`.

**Comment by michaelc06** [comment]
Thanks for looking into this. I have tried copying the sample `BasicFormFluentUIComponents.razor` and `Starship.cs` and seeing the same issues. Testing this on the server side.

**Comment by ParamITNL** [comment]
I am seeing this issue to (rendermode: ServerPrerendered). 

Simply put:

``` 
<FluentSwitch @bind-Value="_value1" Label="Test Switch"></FluentSwitch>

@code {
  private bool _value1;
}
``` 
As long as the value of _value1 is false by default, setting it to true the first time using the switch won't be shown. I tested by adding some console logging - This shows setting the value is working, it is only not visually represented by the switch/checkbox control.

when using

```
@code {
  private bool _value1 = true;
}
```

the switch/checkbox components function as expected.

Hope this helps/
