### ISSUE TITLE
feat: add proportional resize to splitter

### ISSUE THREAD

**Issue by tlmii** [microsoft/fluentui-blazor#957]
# 🙋 Feature Request

Right now when the splitter resizes it does so by setting a fixed pixel width for the left/top panel and letting the right/bottom panel take "the rest". See

https://github.com/microsoft/fluentui-blazor/blob/f338cbb670e72b301a8c91d6e14f865ecce72af9/src/Core/wwwroot/js/SplitPanels.js#L105

and

https://github.com/microsoft/fluentui-blazor/blob/f338cbb670e72b301a8c91d6e14f865ecce72af9/src/Core/wwwroot/js/SplitPanels.js#L112

This leads to the behavior seen in the second half of screen recording in this comment: https://github.com/dotnet/aspire/pull/819#issuecomment-1811556472 where  resizing the overall splitter control can "lose" the right/bottom pane because the top/left pane have fixed width/height.

It'd be nice to either

1. Have this set proportionally all the time, or
2. Have an option to have this set proportionally (ResizeMode enum?)

## 🤔 Expected Behavior

An ability to have the panel sizes be resized proportionally

## 😯 Current Behavior

Resize is always done with fixed with for first panel and second panel getting "the rest"

## 💁 Possible Solution

I think there's two parts to the solution:
1. Implementing proportional resize. This is easy since you're already collecting the two sizes. We'd just need to change how the sizes are written back out. 
2. Deciding whether this is the default, which would technically be a breaking change to the behavior of what was just released, or an option. If its an option, we'd need to decide on the option name (ResizeMode?) and values (Fixed & Proportional? FixedFirst & Proportional? Fixed & Fractional (since fr is fractional units)?) and make the default be the current behavior.

Another option would be to also add a FixedLast mode to the ResizeMode so you could change which one stayed "fixed" when the window resized.
 
## 🔦 Context

This stems from using the FluentSplitter in the Summary/Details View for Aspire. I ran into it while preparing https://github.com/dotnet/aspire/pull/819 and then it got called out in https://github.com/dotnet/aspire/pull/819#issuecomment-1811556472 before I could get this issue filed, so I don't think its just me.

**Comment by vnbaaij** [comment]
I vote for changing the implementation so it will always do the resize proportional. That makes the behavior consitent with how it works before a resize of the splitter itself has taken place:
![proportional split](https://github.com/microsoft/fluentui-blazor/assets/1761079/28c35bfa-93dc-4d7c-82fb-c5b8fb84f8f5)
As the behavior was internal to the component, I don't think consider this a breaking change. I dont really see a value in having both modes available.

With this change I have **not** changed the returned `SplitResizeEventArgs`. This still reports back the sizes in **pixels**

**Comment by vnbaaij** [comment]
Oh, I'm also adding a `BarSize` parameter so dev can specify the width/height of the splitter bar.
