### ISSUE TITLE
feat: add minimum sizes to FluentSplitter

### ISSUE THREAD

**Issue by tlmii** [microsoft/fluentui-blazor#958]
# 🙋 Feature Request

It would be nice to either

1. Add Panel1MinSize and Panel2MinSize (or similar) and enforce them as part of the resize, or
2. Show how this can already be done with the existing control via an example in the samples.

## 🤔 Expected Behavior

When a minimum size is set and you try to move the splitter past that size, it won't resize.

## 😯 Current Behavior

There's no way to set a minimum size so the user can always shrink either side to zero

## 💁 Possible Solution

I'm not positive on this one. May require combination of CSS and JS to make it work and enforce as part of the drag mechanism.

## 🔦 Context

This came up as part of the feedback to https://github.com/dotnet/aspire/pull/819

**Comment by vnbaaij** [comment]
Added `Panel1MinSize` and `Panel2MinSize`. In example below, `Panel1MinSize` has been set to '0.15fr'. `Panel2MinSize` has been set to '50px'

![splitter-minvalues](https://github.com/microsoft/fluentui-blazor/assets/1761079/3b98d32f-9e35-4b65-b965-84c11009ecab)
