### ISSUE TITLE
How to make Toast show using the templated code?

### ISSUE THREAD

**Issue by dannypang** [microsoft/fluentui-blazor#964]
Hi I am new to the Blazor FluentUI and have been trying very hard to figure out how to make the Toast showing on the UI.

I followed the instructions and put in the FluentToastProvider in the end of the MainLayout.razor. But, there is not showing any toast. 

I used the templates to generate the skeleton code but I can't make it to work. Can any of you please help? Is there any examples that show how it works?

Thanks a lot.

**Comment by vnbaaij** [comment]
Hi,

Please see the examples at https://www.fluentui-blazor.net/Toast

**Comment by gsnyder87** [comment]
I agree that something is missing from the documentation on how to get the toast to work.  
I have the <FluentToastProvider MaxToastCount="10"/> added to my mainLayout page 
and am Injecting IToastService onto my component, but the toast never shows up when activating the ToastService.ShowToast method.

**Comment by MSFTJim** [comment]
I had the same issue, I think I was not clear after reading the docs on adding render mode.  I added it globally to the app.razor and it worked properly.  I then tested by adding rendermode to just the toast component, and that also worked.

Here is an example:
`<FluentToastProvider @rendermode="InteractiveServer" MaxToastCount="10" />`

Hope that helps some folks!!
