### ISSUE TITLE
Fluent Blazor Web App NavMenu.razor Issue

### ISSUE THREAD

**Issue by g123413927** [microsoft/fluentui-blazor#965]
# 🐛 Bug Report

open the counter page 

Error: One or more errors occurred. (Root component type 'BlazorAppMSTest.Components.Layout.NavMenu' could not be found in the assembly 'BlazorAppMSTest'.)

## 🌍 Your Environment

* OS & Device: [ Windows, Linux] 
* Browser [e.g. Microsoft Edge]
* .NET 8 and FAST Version 4

ps: remove the code @rendermode InteractiveAuto  in NavMenu.razor, it will be ok

**Comment by g123413927** [comment]
> Hi,
> 
> Please supply details on how to reproduce the issue. Did you use our templates? What options did you use when creating your app? There is not enough information for us to work with.

I used a template called Fluent Blazor Web App when I installed Microsoft FluentUI AspNetCore Templates

**Comment by vnbaaij** [comment]
> I used a template called Fluent Blazor Web App when I installed Microsoft FluentUI AspNetCore Templates

Ok, that helps a, but only a tiny bit. What options did you choose?

**Comment by pk9r327** [comment]
Hi, I have opened an issue related to this issue at #992
