### ISSUE TITLE
Fluent Blazor WebAssembly cannot be debugged or started

### ISSUE THREAD

**Issue by g123413927** [microsoft/fluentui-blazor#966]
# 🐛 Bug Report

When you start debugging the project, then

Error MSB3030 Unable to copy file 'wwwrootservice-worker.js' because the file could not be found.	BlazorAppWASM	C:Program Filesdotnetsdk8.0.100SdksMicrosoft.NET.Sdk.BlazorWebAssemblytargets Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets	146	

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Microsoft Edge
* .NET 8.0 and FAST Version 4

**Comment by vnbaaij** [comment]
Hi,

Please supply details on how to reproduce the issue. Did you use our templates? What options did you use when creating your app?
There is not enough information for us to work with.

**Comment by vnbaaij** [comment]
Did you create a project from the template or did you install the template NuGet package in your project and run that code? I have verief project created by templateto to run.

Please go through the readme for the template package and try again...https://www.nuget.org/packages/Microsoft.FluentUI.AspNetCore.Templates#readme-body-tab

Closing as not actionable from our side.
