### ISSUE TITLE
fix: MessageBox component broken in demo site

### ISSUE THREAD

**Issue by benjaminsampica** [microsoft/fluentui-blazor#968]
# 🐛 Bug Report

![Screenshot 2023-11-16 092239](https://github.com/microsoft/fluentui-blazor/assets/25310886/b2854002-66a6-46ee-9dc0-dab35852c961)

## 💻 Repro or Code Sample

https://www.fluentui-blazor.net/MessageBox

* OS & Device: IPhone Safari, Windows Chrome/Edge

**Comment by dvoituron** [comment]
Ho, indeed.
We just pushed a fix to correct this. We'll push it into production as soon as possible.
In the meantime, it's already available on https://preview.fluentui-blazor.net/MessageBox

**Comment by benjaminsampica** [comment]
Thanks! Awesome job at dotnet conf
