### ISSUE TITLE
fix: On click nav group does not trigger expected event in NavMenu

### ISSUE THREAD

**Issue by Narvalex** [microsoft/fluentui-blazor#972]
# 🐛 Bug Report

As the title states this is similar to #859 

## 💻 Repro or Code Sample

Go the [nav menu in the Fluent UI Blazor page](https://www.fluentui-blazor.net/NavMenu).
Try trigger the exansion/contraction of the Nav Group clicking near the edges as shown in the picture bellow
![image](https://github.com/microsoft/fluentui-blazor/assets/11648387/95498ae5-5e3b-4775-b0d4-4a2e52f741b8)

## 🤔 Expected Behavior

This should trigger the contraction and or expansion of the group

## 😯 Current Behavior

Nothing happens.

## 💁 Possible Solution

You can "train" your users to click always in the middle of the button, but this is not a good user experience.

## 🌍 Your Environment

This happens in the live demo site of Fluent UI Blazor, Version: 4.0.0+a65ce47e55bfa95705788063a1f7105cb4e41dfe  -  [Powered by .NET 8.0.0](https://dotnet.microsoft.com/en-us/learn/aspnet/what-is-aspnet-core)

**Comment by vnbaaij** [comment]
Yes, found the error. Movin `@onclick` and `@onkeydown` to positioning region so whole area will trigger expand/collapse.

Will be fixed in next update.
