### ISSUE TITLE
Docs: Opening SplashScreen causes unhandled error

### ISSUE THREAD

**Issue by digitaldirk** [microsoft/fluentui-blazor#973]
# 🐛 Bug Report

When clicking on the "Open splash screen" or "Open splash screen (async)" buttons under the "Default splash screen" section on this page of the documentation: [https://www.fluentui-blazor.net/SplashScreen](https://www.fluentui-blazor.net/SplashScreen), you get an unhandled error.

## 💻 Repro or Code Sample

I could not reproduce this when debugging locally, it only happens me to on the live site.

## 🤔 Expected Behavior

Open splash screen without errors.

## 😯 Current Behavior

Unhandled error, forcing a reload. 
![image](https://github.com/microsoft/fluentui-blazor/assets/22691956/46138a1c-d66d-4649-9220-3eb033e3c2e9)

## 💁 Possible Solution

Could not find an obvious solution, I have little knowledge about this project as I was just evaluating it via the docs.

## 🌍 Your Environment
* Win 11 pc
* Microsoft Edge, Google Chrome

**Comment by dvoituron** [comment]
Ho, indeed.
We just pushed a fix to correct this. We'll push it into production as soon as possible.
In the meantime, it's already available on https://preview.fluentui-blazor.net/SplashScreen

**Comment by vnbaaij** [comment]
Definitely fixed with https://github.com/microsoft/fluentui-blazor/commit/5ad5104b0b52d8137df540eb031ce24c5111f464
