### ISSUE TITLE
FluentUI.Demo.Server project throws FileNotFound Exception for Microsoft.FluentUI.AspNetCore.Component Version=4.0.0.23318

### ISSUE THREAD

**Issue by dannypang** [microsoft/fluentui-blazor#976]
Hi,

When I tried to run the Demo project locally, I got a FileNotFoundException for Microsoft.FluentUI.AspNetCore.Component Version=4.0.0.23318 on the fluentui-blazor github master build. 

I think the referenced package for the Icons/Emoji is referencing the Microsoft.FluentUI.AspNetCore.Component build from the NuGet package. Can you please let me know if that is right? Please see the screenshot below. Thanks.

<img width="512" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/26168669/2ccae451-40ba-4caf-980a-67dcd33d2ad0">

**Comment by dvoituron** [comment]
Hi,
We also found this and corrected it in the current `dev` branch.
You need to update your local [Directory.Build.props](https://github.com/microsoft/fluentui-blazor/blob/main/Directory.Build.props) file to increase the `VersionFile` and `VersionPrefix` versions to > 4.0.0. 

Example
```
<VersionFile>4.0.1</VersionFile>
<VersionPrefix>4.0.1</VersionPrefix>
```
