### ISSUE TITLE
fix: [Error: RuntimeHelpers does not contain a definition for CreateInferredBindSetter] in [FluentSearch]

### ISSUE THREAD

**Issue by KyleLJohnson** [microsoft/fluentui-blazor#978]
# 🐛 Bug Report

Added example code to project and immediately received error.
![image](https://github.com/microsoft/fluentui-blazor/assets/2169245/641b6c6b-68a8-410d-8de3-46989866a19e)

## 💻 Repro or Code Sample
![image](https://github.com/microsoft/fluentui-blazor/assets/2169245/65dcf33c-7206-4af7-9c16-bdadb969cb1d)

```
 private void HandleCountryFilter(ChangeEventArgs args)
 {
     if (args.Value is string value)
     {
         nameFilter = value;
     }
 }

 private void HandleClear()
 {
     if (string.IsNullOrWhiteSpace(nameFilter))
     {
         nameFilter = string.Empty;
     }
 }
```

## 🌍 Your Environment

OS & Device:  Windows
Browser: Microsoft Edge
VS,  .NET 6 and FAST Version [e.g. 3.3.0]

**Comment by KyleLJohnson** [comment]
I figured out the issue.

**Comment by TomasK145** [comment]
my blazor app used .net6, it was needed to change it (in my case to .net9) and then it works

**Comment by vnbaaij** [comment]
Not sure why you are referring to a MudBlazor issue here...

**Comment by TomasK145** [comment]
edited, but that question provided some clues to solve my issue and I thought that it could be usefull
