### ISSUE TITLE
feat: add Azure DevOps like `Filter` component

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui-blazor#980]
# 🙋 Feature Request

I need [Azure DevOps like `Filter`](https://developer.microsoft.com/en-us/azure-devops/components/filter) component
![image](https://github.com/microsoft/fluentui-blazor/assets/2365592/b3364268-4789-4828-81c5-f184b2fb43ca)

## 🤔 Expected Behavior

Has functionality the same as that Azure DevOps UI component

## 🔦 Context

Apply multiple filters

**Comment by dvoituron** [comment]
Thank you for your request, but this component is not currently planned.

But you could do this easily by using a [FluentPopup ](https://www.fluentui-blazor.net/Popover) containing a [FluentSearch](https://www.fluentui-blazor.net/Search) and a [FluentListbox](https://www.fluentui-blazor.net/Listbox).
