### ISSUE TITLE
feat: add Azure DevOps like `FilterBar` component

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui-blazor#981]
# 🙋 Feature Request

I need [Azure DevOps like `FilterBar`](https://developer.microsoft.com/en-us/azure-devops/components/filter#basic-filter-bar) component
![image](https://github.com/microsoft/fluentui-blazor/assets/2365592/82dfc739-d6c9-4c01-ab58-cb678a208ad1)

## 🤔 Expected Behavior

Has functionality the same as that Azure DevOps UI component

## 🔦 Context

Apply multiple filters and search by keyword

**Comment by dvoituron** [comment]
Why not to use a [FluentMenuButton](https://www.fluentui-blazor.net/MenuButton)? 

If you need to include a filter searc, you could use the [FluentPopover](https://www.fluentui-blazor.net/Popover)
