### ISSUE TITLE
feat: add Azure DevOps like `TagPicker` component

### ISSUE THREAD

**Issue by xperiandri** [microsoft/fluentui-blazor#982]
# 🙋 Feature Request

I need [Azure DevOps like `TagPicker`](https://developer.microsoft.com/en-us/azure-devops/components/tagpicker) component
![image](https://github.com/microsoft/fluentui-blazor/assets/2365592/5085f20a-92fa-4dba-aea5-51d54d4140ee)
![image](https://github.com/microsoft/fluentui-blazor/assets/2365592/69fee64f-7f24-44c8-b81a-76c963300bc3)

## 🤔 Expected Behavior

Has functionality the same as that Azure DevOps UI component

## 🔦 Context

Add multiple tags to a list that look like a textbox with items
See also `TokenizingTextBox` from Windows Community Toolit
![image](https://github.com/microsoft/fluentui-blazor/assets/2365592/21913a38-df27-4327-b5d9-f742ca7d53f6)

**Comment by dvoituron** [comment]
I think this component is similar to our [FluentAutocomplete](https://www.fluentui-blazor.net/Autocomplete) component.
