### ISSUE TITLE
feat: add chart components

### ISSUE THREAD

**Issue by aweklin** [microsoft/fluentui-blazor#984]
# 🙋 Feature Request

Please add chart components as we currently have it for the FluentUI component library.

## 🤔 Expected Behavior

Ability to create different chart types for creating dashboard diagrams to represent KPIs or trends.

## 😯 Current Behavior

Can't see chart components section on the documentation page at https://www.fluentui-blazor.net/ 

## 💻 Examples

Few chart components samples include but not limited to the following images:

<img width="1254" alt="Screenshot 2023-11-18 at 07 02 14" src="https://github.com/microsoft/fluentui-blazor/assets/5461083/e01e40e0-de7e-46c9-b3a0-7c63f4d926e0">

<img width="1042" alt="Screenshot 2023-11-18 at 07 03 24" src="https://github.com/microsoft/fluentui-blazor/assets/5461083/b0984059-1dfc-4a73-81a0-b84583b27b66">

<img width="1082" alt="Screenshot 2023-11-18 at 07 03 57" src="https://github.com/microsoft/fluentui-blazor/assets/5461083/c55e7770-fe29-41ea-b4b5-f7a791b55627">

<img width="1050" alt="Screenshot 2023-11-18 at 07 05 01" src="https://github.com/microsoft/fluentui-blazor/assets/5461083/f693f265-fbbf-4241-a2e3-0ac7e4589482">

More available at https://developer.microsoft.com/en-us/fluentui#/controls/web/

Thanks in anticipation.

**Comment by dvoituron** [comment]
Thank you for your request, but these features are not currently planned.
We are prioritizing [these FluentUI components](https://fluent2.microsoft.design).
But maybe we'll think about it later.
