### ISSUE TITLE
fix: In v3 library in .NET 8. Interactivity does not work with @rendermode="@(new InteractiveServerRenderMode(prerender: false))"

### ISSUE THREAD

**Issue by Gabriel123N** [microsoft/fluentui-blazor#993]
# 🐛 Bug Report

After updating from  .NET8 RC2 to .NET8 GA, all interactivity stopped working even after applying the fix from this  #623 issue

## 💻 Repro or Code Sample

1. Create a new Blazor web app project with the following properties:
![image](https://github.com/microsoft/fluentui-blazor/assets/50913834/957bffa7-c8de-4287-9bc9-44af4b33690d)
2. Install `Microsoft.Fast.Components.FluentUI` to version `3.3.0`
3. Configure the fluent service in `Program.cs`
```CSharp
 builder.Services.AddFluentUIComponents(options =>
 {
     options.HostingModel = BlazorHostingModel.Server;
 });
```
4. Update `App.razor with this content 
```razor
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="BlazorApp6.styles.css" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <script type="module" src="https://cdn.jsdelivr.net/npm/@@fluentui/web-components@@2.5.16/dist/web-components.min.js"></script>

    <HeadOutlet @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />
</head>

<body>
    <Routes @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />
    <script src="_framework/blazor.web.js"></script>
</body>

</html>
```
5. Update `Home.razor` to the following
```razor
@page "/"
@using Microsoft.Fast.Components.FluentUI;

<PageTitle>Home</PageTitle>

<Microsoft.Fast.Components.FluentUI.FluentLabel>
    Selected value is: @_selected
</Microsoft.Fast.Components.FluentUI.FluentLabel>
<FluentTreeView RenderCollapsedNodes="false">
    <FluentTreeItem Text="root1">
        <FluentTreeItem Text="child1">
            <FluentTreeItem Text="value1" SelectedChanged="@(() => SetValue("root1", "child1", "value1"))">

            </FluentTreeItem >
            <FluentTreeItem Text="value2" SelectedChanged="@(() => SetValue("root1", "child1", "value2"))">

            </FluentTreeItem>
            <FluentTreeItem Text="value3" SelectedChanged="@(() => SetValue("root1", "child1", "value3"))">

            </FluentTreeItem>
        </FluentTreeItem>
        <FluentTreeItem Text="child2">
            <FluentTreeItem Text="value" SelectedChanged="@(() => SetValue("root1", "child2", "value"))">

            </FluentTreeItem>
        </FluentTreeItem>
    </FluentTreeItem>
    <FluentTreeItem Text="root2">
        <FluentTreeItem Text="child1">
            <FluentTreeItem Text="value" SelectedChanged="@(() => SetValue("root2", "child1", "value"))">

            </FluentTreeItem>
        </FluentTreeItem>
    </FluentTreeItem>
</FluentTreeView>

@code {
    private string _selected = "";
    private void SetValue(string key1, string key2, string value)
    {
        _selected = $"{key1}/{key2}/{value}";
    }
}
```

## 🤔 Expected Behavior

When a tree item with the `SelectedChange` event is clicked, the function `SetValue` is called and the value of `_selected is updated`

## 😯 Current Behavior

The function is never called and the UI/field not updated.
## 🔦 Context

Several elements that were previously working in RC2 such as tree views or text fields no longer trigger their events and update their binded properties. This effectively makes several applications now unusable in .NET8 GA

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Tested in Edge and Firefox
* .NET and FAST Version: .NET 8 GA and  FAST 3.3.0

**Comment by vnbaaij** [comment]
Hi,

The V3 library does **NOT** work with .NET 8.

We will add a note about the `Appearance.Filled` change. hanks for spotting and reporting that!

**Comment by keval1725** [comment]
I used Fluent Ui in my Razor page  but it could not render js and css for fluent Ui
for the  Fluent Ui i uss 
<link href="_content/Microsoft.Fast.Components.FluentUI/css/reboot.css" rel="stylesheet" />
    <link href="_content/Microsoft.Fast.Components.FluentUI/css/variables.css" rel="stylesheet" />
    And 
    <script src="_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js" type="module" async></script>
    
    But they not load package

**Comment by vnbaaij** [comment]
V3 does not work in .NET 8 anymore. Use V4.
