### ISSUE TITLE
feat: Add month and year selection to the calendar/date-picker

### ISSUE THREAD

**Issue by glen-84** [microsoft/fluentui-blazor#999]
# 🙋 Feature Request

Add month and year selection to the calendar/date-picker.

The UX is poor if you need to select a date with a year in the far future or past.

## 🤔 Expected Behavior

Like other UI libraries. There are various alternatives like inline selection boxes and separated year/month selection "pages/screens" (see example images below).

## 😯 Current Behavior

It would improve the UX by allowing the user to quickly select a date in the far future or past.

## 💁 Possible Solution

n/a

## 🔦 Context

n/a

## 💻 Examples

| Inline | Screen |
|--------|--------|
| ![image](https://github.com/microsoft/fluentui-blazor/assets/261509/a9b4d6df-3abf-4730-9e03-398a7610c554) | ![image](https://github.com/microsoft/fluentui-blazor/assets/261509/05428e84-7825-41de-8e4e-da4a7335b0d9) |

**Comment by dvoituron** [comment]
Yes, this will certainly be a future development.

We added this component a few months ago because the FluentUI Web Components don't have a DatePicker, but we felt it was essential to have a minimal version like this one.

**Comment by glen-84** [comment]
Ya, it's a bit visually inconsistent across browsers.

**Comment by dvoituron** [comment]
Yes :-(

**Comment by dvoituron** [comment]
I'm working on this component to add a month and year view.
I'd like to finalize some details (optimization and unit tests) before to create a PR, but the result could be...

1. Days / Months / Years views.
![CalendarView](https://github.com/microsoft/fluentui-blazor/assets/8350694/226fe1af-0154-4dd5-9cf7-31f30c122b16)

2. FluentDatePicker with view navigation.
![DatePicker](https://github.com/microsoft/fluentui-blazor/assets/8350694/f593ba16-74b8-41ab-95ea-9b8541cc383d)

**Comment by yavulan** [comment]
Thank you for working on this!

What might be useful for me, listed by priority descending:
- date range selection (not sure it should be a part of this component or
it should be a separate component?)
- ability to provide min and max allowed dates
- callbacks for each view selection, e.g. YearSelected etc.
- ability to control the starting view to select date - e.g., start from
year, not from day selection.

**Comment by dvoituron** [comment]
> Thank you for working on this! What might be useful for me, listed by priority descending: ...

1. It is not planned to create a component to select a date or time range. For this situation, it is preferable to place two components. For example: Start date and end date.
2. To specify a min/max date, you can use the `DisabledDateFunc` attribute.
    Example: `DisabledDateFunc="@(date => date.Year < 2021 || date.Year > 2023)"`
3. You have two Event callbacks (which will be the same for Day/Month/Year views):
   - **PickerMonthChanged**: Fired when the display month changes.
   - **ValueChanged**: Fired when the display month changes.
   You can see the use of these events in my previous GIFs (above).
4. At this moment, when using a DatePicker, it will not be possible to start the view from a Month/Year view (always from the Days view). But you can use the FluentCalendar to select the view of your choice. This could be a future enhancement to create a month/year selection component.
